### ISSUE TITLE
GCP cloudSQL check failing even though should pass - rule bug???

### ISSUE THREAD

**Issue by jaksky** [bridgecrewio/checkov#100]
**Describe the bug**
Check fails even though configuration correct for GCP cloudSQL
Check: CKV_GCP_6: "Ensure all Cloud SQL database instance requires all incoming connections to use SSL"
	FAILED for resource: google_sql_database_instance.db-instance
	File: /:29-41

		29 | resource "google_sql_database_instance" "db-instance" {
		30 |   name             = var.instance_name
		31 |   database_version = var.database_version
		32 |
		33 |   settings {
		34 |     # Second-generation instance tiers are based on the machine
		35 |     # type. See argument reference below.
		36 |     tier            = var.instance_tier
		37 |     ip_configuration {
		38 |       require_ssl = true
		39 |     }
		40 |   }
		41 | }

**To Reproduce**
Create resource as in the output

**Expected behavior**
Check PASS

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Checkov Version 1.0.173

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by jaksky** [comment]
Based on this test https://github.com/bridgecrewio/checkov/blob/master/tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabaseRequireSsl.py it should pass unless I am missing sth crucial

**Comment by jonjozwiak** [comment]
I've corrected this and it should be working now.

**Comment by jaksky** [comment]
Thx! How come that test has been passing and I don't see the fixed test as a part of PR? Does that imply that test wasn't working?

**Comment by schosterbarak** [comment]
@jaksky  seems like the issue was both in the test and in the code. see fix here: https://github.com/bridgecrewio/checkov/pull/101/files

**Comment by jaksky** [comment]
Yea, sorry I overlooked the second commit. Thx for a quick response!!
