### ISSUE TITLE
CKV_AWS_107, CKV_AWS_108, CKV_AWS_109, and CKV_AWS_110: check should require effect=Allow

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#1000]
**Describe the bug**

The CKV_AWS_107, CKV_AWS_108, CKV_AWS_109, and CKV_AWS_110 rules treat a `Deny` policy the same as an `Allow` policy. We had the following policy which is a generic IP lock on AWS API calls get flagged:

```hcl
Check: CKV_AWS_109: "Ensure IAM policies does not allow permissions management / resource exposure without constraints"
	FAILED for resource: aws_iam_policy_document.DenyOutsideCallers
	File: iam-policies.tf:7-28
		7  | data "aws_iam_policy_document" "DenyOutsideCallers" {
		8  |   statement {
		9  |     sid       = "DenyOutsideCallers"
		10 |     effect    = "Deny"
		11 |     actions   = ["*"]
		12 |     resources = ["*"]
		13 | 
		14 |     condition {
		15 |       test     = "NotIpAddress"
		16 |       variable = "aws:SourceIp"
		17 |       values = [
		18 |         "1.2.3.4/16"
		19 |       ]
		20 |     }
		21 | 
		22 |     condition {
		23 |       test     = "Bool"
		24 |       variable = "aws:ViaAWSService"
		25 |       values   = ["false"]
		26 |     }
		27 |   }
		28 | }
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Checkov Version: 1.0.845

**Comment by schosterbarak** [comment]
I've created a fix at: https://github.com/salesforce/cloudsplaining/pull/166 but I also need to fix something in the upstream repo: https://github.com/salesforce/cloudsplaining/pull/166 
I hope to update soon. Thank you for reporting this.
