### ISSUE TITLE
terraform flatten  and coalescelist functions support

### ISSUE THREAD

**Issue by ismailyenigul** [bridgecrewio/checkov#1006]
**Is your feature request related to a problem? Please describe.**
checkov can't parse terraform codes with flatten and coalescelist functions. it returns
 Error parsing file 

**Describe the solution you'd like**
Give flatten and coalescelist  function parse support

How to reproduce:

```
git clone https://github.com/terraform-aws-modules/terraform-aws-eks
cd terraform-aws-eks/examples/basic
checkov -d

Check: CKV_AWS_79: "Ensure Instance Metadata Service Version 1 is not enabled"
	FAILED for resource: module.eks.aws_launch_template.workers_launch_template
	File: /../../workers_launch_template.tf:238-244
	Calling File: /main.tf:125-160
	Guide: https://docs.bridgecrew.io/docs/bc_aws_general_31

		238 | resource "aws_launch_template" "workers_launch_template" {
		239 |   count = var.create_eks ? (local.worker_group_launch_template_count) : 0
		240 |   name_prefix = "${coalescelist(aws_eks_cluster.this[*].name, [""])[0]}-${lookup(
		241 |     var.worker_groups_launch_template[count.index],
		242 |     "name",
		243 |     count.index,
		244 |   )}"


Error parsing file /Users/ismail/dev/eks/terraform-aws-eks/data.tf
Error parsing file /Users/ismail/dev/eks/terraform-aws-eks/outputs.tf
Error parsing file /Users/ismail/dev/eks/terraform-aws-eks/irsa.tf

```
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/outputs.tf#L51 line 
and
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/irsa.tf#L14
has flatten function if you remove it, checkov will parse `outputs.tf` and `irsa.tf`
and https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L72 has coalescelist function.

**Comment by nimrodkor** [comment]
[coalesce](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py#L153), coalescelist and flatten have been added to the supported tf operators
