### ISSUE TITLE
Raising code quality

### ISSUE THREAD

**Issue by gruebel** [bridgecrewio/checkov#1007]
**Is your feature request related to a problem? Please describe.**
During developing my first Terraform checks for AWS resources I was surprised that their are no kind of code quality tools, like black or flake8 enforced.

**Describe the solution you'd like**
It would be great to add following tools:
- black (formatting)
- flake8 (linting)
- isort (import sorting)
- mypy (type checking)

**Additional context**
I'm happy to help you out here and also a GitHub action named `lint` should be added to check, if a new PR follows those new standards.

**Comment by JamesWoolfenden** [comment]
i like gha but also pre-commit framework? something like that/both?

**Comment by gruebel** [comment]
you probably mean https://github.com/pre-commit/pre-commit yeah that would also be a great addition.

**Comment by nimrodkor** [comment]
Implemented in #2091 and the subsequent issues
