### ISSUE TITLE
Ability to disable some rules globally

### ISSUE THREAD

**Issue by jaksky** [bridgecrewio/checkov#102]
**Is your feature request related to a problem? Please describe.**
Some default policies might be troublesome in some environments like production. We want to be able to disable globally some default checks e.g. CKV_GCP_10: "Ensure 'Automatic node upgrade' is enabled for Kubernetes Clusters" which might not be an ideal for production environments. 

**Describe the solution you'd like**
Have an cli option where you specify list of excluded default checks

**Describe alternatives you've considered**
Forcing people to use `skip` check is against main motivation of the tool which should define what the standard is and is fight against what the best practice is 

**Additional context**

**Comment by schosterbarak** [comment]
loud and clear. will work on it.

**Comment by kmcquade** [comment]
We could also really use this as well.

**Comment by schosterbarak** [comment]
@kmcquade @jaksky solved!

To scan you directory with only a specific check use the -c\ --check flag. You can use multiple checks with comma , delimiter. This is another way to skip execution of specific checks on a whitelist fashion

The following example will show results only for 2 scans (CKV_AWS_1 and CKV_AWS_2) :

checkov -d /user/tf --check CKV_AWS_1,CKV_AWS_2
