### ISSUE TITLE
#1022 broke colered output for gitlab ci

### ISSUE THREAD

**Issue by floh96** [bridgecrewio/checkov#1025]
in #1022 the docker image was switched to alpine but in the alpine image the script package is not included witch is needed for  colered output for gitlab ci. See https://www.checkov.io/4.Integrations/gitlab.html

Screenshot

![Unbenannt](https://user-images.githubusercontent.com/49693964/113028643-c9f9b900-918b-11eb-9e2f-1028fd408f51.PNG)

**Comment by schosterbarak** [comment]
@floh96 do you know which package we should add to the docker file to add that?
We would accept a PR on that.

**Comment by ismailyenigul** [comment]
It is util-linux package @schosterbarak  https://pkgs.alpinelinux.org/contents?file=script&path=&name=util-linux&branch=edge&repo=main&arch=x86_64

**Comment by floh96** [comment]
@ismailyenigul thank you for your comment I didn't know about the package search.
I googled and found https://github.com/gliderlabs/docker-alpine/issues/160 and opened the pr.
@schosterbarak as a follow up it would be possible to remove the package from the dockerfile and add it to a before script block in the gitlab-ci.yml
```
  before_script:
    - apk add util-linux
```
this would be a breaking change for existing gitlab users of course wich should be communicated before.
