### ISSUE TITLE
Links to documentation broken

### ISSUE THREAD

**Issue by quixoticmonk** [bridgecrewio/checkov#1029]
**Describe the bug**
The links to the bridgecrew.io based documents or blogs are broken.

**To Reproduce**
1. Go to https://github.com/bridgecrewio/checkov
2. Select read the docss : https://docs.bridgecrew.io/?utm_campaign=checkov-github-repo&utm_source=github.com&utm_medium=read-docs-button
3. 
![Screen Shot 2021-03-31 at 10 59 02 AM](https://user-images.githubusercontent.com/11953035/113165669-1be42280-9210-11eb-862c-147ed71ef936.png)

**Comment by quixoticmonk** [comment]
Seems to be fixed now. I guess the domain wasn't renewed during the time I was checking.

**Comment by schosterbarak** [comment]
We had a nameserver migration that went a little off. Thank you for reporting this.
