### ISSUE TITLE
CKV_AZURE_46 fails if variables.tfvars is located in a different folder

### ISSUE THREAD

**Issue by Marcus-James-Adams** [bridgecrewio/checkov#1033]
**Describe the bug**
Check: CKV_AZURE_46: "Specifies a retention period of less than 90 days."
        FAILED for resource: azurerm_mssql_database_extended_auditing_policy.server
        File: /sql_auditing_and_diags.tf:11-18
        Guide: https://docs.bridgecrew.io/docs/bc_azr_general_12

                11 | resource "azurerm_mssql_database_extended_auditing_policy" "server" {
                12 |   database_id                             = azurerm_mssql_database.server.id
                13 |   log_monitoring_enabled                  = true
                14 |   storage_endpoint                        = azurerm_storage_account.server.primary_blob_endpoint
                15 |   storage_account_access_key              = azurerm_storage_account.server.primary_access_key
                16 |   storage_account_access_key_is_secondary = true
                17 |   retention_in_days                       = var.log_rention_policy_days
                18 | }
				
Checkov Version 1.0.861

In this scenario
var.log_rention_policy_days = 90

This fails if variables.tfvars is located in a different folder

eg terraform apply -var-file=..\common.tfvars

**Comment by gruebel** [comment]
Thanks to @mikeurbanski1  this is fixed since version `2.0.380` 🚀  you can specify a parameter `--var-file`, which points to the var file 🙂
