### ISSUE TITLE
download-external-modules parameter does not download remote modules on v2.0

### ISSUE THREAD

**Issue by ismailyenigul** [bridgecrewio/checkov#1049]
**Describe the bug**
 `--download-external-modules true` option download remote modules and scan it.
It was working on v1.X release but does not work on checkov 2.0

**To Reproduce**
export LOG_LEVEL=DEBUG
checkov -d . --download-external-modules true

It will not download any remote modules.

**Expected behavior**
It should download remote modules and scan it.
**Screenshots**

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Checkov Version 2.0.26

**Comment by schosterbarak** [comment]
fixed at: https://github.com/bridgecrewio/checkov/pull/1053
