### ISSUE TITLE
Tracking: networkx vulnerability

### ISSUE THREAD

**Issue by robeden** [bridgecrewio/checkov#1051]
**Describe the bug**
[Snyk reports](https://snyk.io/vuln/SNYK-PYTHON-NETWORKX-1062709) a new Deserialization of Untrusted Data vulnerability in networkx. This should be fixed with networkx/networkx#4541. When that is released, Checkov dependencies should be re-locked.

**Additional Context**

Snyk found via `kubernetes/requirements.txt`
![Screen Shot 2021-04-09 at 10 37 09 AM](https://user-images.githubusercontent.com/1891321/114205093-8e938300-991f-11eb-80e9-0dbf065f7146.png)

**Comment by robeden** [comment]
@schosterbarak - Oh, I’m sure you’re not. Didn’t mean to imply you were, but it will just help checkov not to show up in vulnerability scans if it updates requirements to the new networkx version when available. There’s no urgent issue that needs to be worked around.

**Comment by nimrodkor** [comment]
Version 2.6.3 is now in checkov, and this issue was resolved in 2.6.2
