### ISSUE TITLE
CKV_AZURE_12: Retention policy of 0 is not supported

### ISSUE THREAD

**Issue by kylelaker** [bridgecrewio/checkov#1055]
**Describe the bug**
When setting the `retention_period.days` value on `azurerm_network_watcher_flow_log` to `0`, `CKV_AZURE_12` still fails. `0` is the value to signify indefinite/forever retention.

**To Reproduce**
1. Create an `azurerm_network_watcher_flow_log` resource
2. Set
```
  retention_policy {
    enabled = true
    days    = 0
  }
```
3. Run `checkov`
4. Receive failure for `CKV_AZURE_12`

**Expected behavior**
`0` is an accepted value as documented at https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-overview#how-logging-works

**Desktop (please complete the following information):**
 - OS: Linux
 - Checkov Version: 2.0.26

**Additional context**
At https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/azure/NetworkWatcherFlowLogPeriod.py#L17 likely need to adjust the innermost `if` statement to something like:

```python
if retention_in_days is not None and (retention_days == 0 or retention_days >= 90):
```

Happy to open a pull request if this is an acceptable solution.

**Comment by nimrodkor** [comment]
That would be a very welcome contribution @kylelaker !
