### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by ashishpatel-git** [bridgecrewio/checkov#1056]
Hi there, it appears that the link including a list of all checks performed is no longer working https://github.com/bridgecrewio/checkov/blob/master/docs/3.Scans/resource-scans.md. Is this located elsewhere?

**Comment by ashishpatel-git** [comment]
This is part of the first bullet under features:

* Over 750 built-in policies cover security and compliance best practices for AWS, Azure and Google Cloud.

**Comment by nimrodkor** [comment]
Hi @ashishpatel-git !
We've taken our policy index to a new location - https://github.com/bridgecrewio/checkov/tree/master/docs/5.Policy%20Index
Please note we are still working on updating these docs, so expect changes in the coming week or so!
