### ISSUE TITLE
Denoising CKV_AWS_135 for enabled-by-default instance types

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#1074]
CKV_AWS_135 triggers for any EC2 instance which doesn't have `ebs_optimized` in the metadata. This can be noisy on projects which use the many instance types which are EBS optimized by default:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html

> The following table lists the instance types that support EBS optimization and EBS optimization is enabled by default. There is no need to enable EBS optimization and no effect if you disable EBS optimization. 

I don't believe there's not a great way to handle this without API calls or maintaining a list of instance types but I wonder whether that might be worthwhile to avoid people thinking of Checkov as noisy.

**Comment by schosterbarak** [comment]
@acdha i think we can do an api call as part of the packaging pipeline of checkov and by that keep the list up to date. 
do you know what API or aws CLI command will help us get this data?

**Comment by acdha** [comment]
Based on https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypes.html I think that'd be `DescribeInstanceTypes` with `ebs-info.ebs-optimized-support=default`:

```
aws ec2 describe-instance-types --filters Name=ebs-info.ebs-optimized-support,Values=default --query InstanceTypes[].[InstanceType] --output=text
```
