### ISSUE TITLE
S3 default encryption duplicate?

### ISSUE THREAD

**Issue by gruebel** [bridgecrewio/checkov#1076]
**Describe the bug**
With the new `checkov` 2.0 version a couple of new checks were added and one them is `CKV_AWS_145` (Ensure that S3 buckets are encrypted with KMS by default), but there was already the check `CKV_AWS_19` (Ensure all data stored in the S3 bucket is securely encrypted at rest). So even you are complaint with the old one, you can be uncomplaint with the new one. So, does it even make sense to keep the old one?

**Comment by nimrodkor** [comment]
Hi @gruebel !
The slight difference is the usage of KMS vs AES256
For some use cases, KMS is not required - in other it is. You can use the skip comment to justify why the bucket doesn't require KMS keys.

Does that make sense?

**Comment by gruebel** [comment]
Looking at it and thinking about it, it seems to make sense 😄 yeah, let's close it. Thanks @nimrodkor for your description 👍
