### ISSUE TITLE
File that only contains locals with expression can't be parsed

### ISSUE THREAD

**Issue by andir** [bridgecrewio/checkov#1089]
**Describe the bug**

```
locals {
  some_local_variable = (
    length(var.some_input_list)
    + length(var.some_other_input_list)
  ) > 0
}
```

Note: It doesn't matter if the variables are declared or not the error that is visible to me is always the same.

**To Reproduce**
1. Write the above example into a file
2. Run cli command  'checkov -f  my_file.tf`
3. See error

**Expected behavior**
The expression is valid HCL Terraform code and thus should be parsed as such. 

**Desktop:**
 - OS: Linux
 - Checkov Version: 2.0.46

**Comment by nimrodkor** [comment]
This is an issue in the underlying hcl parser, hcl2. We're using our own fork - https://github.com/bridgecrewio/python-hcl2
The problem is that it is multi-line. We would love a contribution if you're up for it

@arielkru / @schosterbarak FYI
