### ISSUE TITLE
CKV_AZURE_109 tfsec collision AZU020

### ISSUE THREAD

**Issue by ChapChap** [bridgecrewio/checkov#1090]
There is a collision between guidelines on which nacl rule to add to an azurerm_key_vault

[This doc](https://docs.bridgecrew.io/docs/ensure-that-key-vault-allows-firewall-rules-settings) from bridgecrew tells to allow default (which is what checkov checks)
[This doc](https://tfsec.dev/docs/azure/AZU020/) from tfsec.dev tells to deny default.

OMHO, I think tsec is right on that.

cf. https://github.com/tfsec/tfsec/issues/690

**Comment by nimrodkor** [comment]
Great catch @ChapChap !
Will be resolved in the PR mentioned above ^^
