### ISSUE TITLE
Ability to run Checkov with 'quiet mode'

### ISSUE THREAD

**Issue by mgrecar** [bridgecrewio/checkov#110]
**Is your feature request related to a problem? Please describe.**
The default `cli` output is very noisy on a clean, successful run.  For example, I have 11 checks that run on my current project, and if it is successful, with no problems at all, I get:
 - 8 lines of output displaying `Checkov` in fancy branding and the version
 - 2 lines of output displaying how many checks passed, failed or were skipped
 - 4+ lines of output _for each successful check_, showing the line, the name of the check, the fact that it passed, and the evaluation of every variable evaluated in an expression that check, which adds an extra line each (which could be a lot if it's checking a complex object)
 - 5+ lines of output _for each skipped check_, show the same as successful check, but with also the skipped comment

This means running the tool, on a repo with no issues, scrolls by about 2 pages of noise, which I have to scroll back up to check on the actual status, which is printed at the top of the output.

**Describe the solution you'd like**
I would like the tool to behave like a standard CLI utility, with respect to default output.  If there are no errors, don't print out anything and return code 0.  If there are problems, just show the problems, and not a full report of everything possible, and return a code greater than 0.  I still believe the default `cli` output has value, for when you need to validate that rule is running or you are investigating a possible problem, but that giant report is unnecessary 90% of the time when you're just iterating through changes, making sure you didn't introduce something foolish.  IMO, the default `cli` output should be what I've just described, and if you want a full report on all checks, version, summary, etc, you should explicitly supply `--output report`.

**Describe alternatives you've considered**
One could pipe the output from Checkov into a few chained together CLI utilities, to filter down the unnecessary noise, but that definitely feels like hacking into place something that should be more or less the default.

**Additional context**
None

**Comment by schosterbarak** [comment]
Thanks @mgrecar We would accept a contribution in that area if you'd like to join :)

**Comment by schosterbarak** [comment]
added the `--check` flag to enabled viewing of a single command
and the `--quiet` enables showing only failed checks ( added here : https://github.com/bridgecrewio/checkov/pull/273) 

let me know if that helps :)

**Comment by mgrecar** [comment]
:raised_hands: Sweet, that `--quiet` flag helps out quiet a bit, thanks!
