### ISSUE TITLE
Error while checking Dockerfile USER set with env variable

### ISSUE THREAD

**Issue by atz-dev** [bridgecrewio/checkov#1101]
**Describe the bug**
The **checkov** CLI return an error when analyzing a Dockerfile with USER set according to an ENV variable. 

**To Reproduce**
1. Get this snippet :
```Dockerfile
FROM python:alpine

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

ENV USERNAME=app
RUN addgroup -S ${USERNAME} && adduser -s /sbin/nologin -S ${USERNAME} -G ${USERNAME} && chown -R ${USERNAME} /app
USER ${USERNAME}

COPY --chown=${USERNAME} script.py .

CMD python3 script.py
```
2. Run cli command  'checkov -f Dockerfile'
3. See error

**Expected behavior**
No error.

**Screenshots**
<img width="750" alt="" src="https://user-images.githubusercontent.com/44492274/115271564-c380b080-a13d-11eb-9c4d-cb086e3bd9fd.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - Checkov Version 2.0.55

**Comment by gruebel** [comment]
Thanks for reporting the error, I took a look into my code and realized, how we test the docker checks is actually incorrect and that's why this error slipped through 🙈
