### ISSUE TITLE
Terraform scan - OpenStack provider ?

### ISSUE THREAD

**Issue by xanhacks** [bridgecrewio/checkov#1103]
Hello,

Do you plan to support Terraform scans with OpenStack in the future ?

Regards

**Comment by schosterbarak** [comment]
Hi @xanhacks this can be a relatively easy contribution:
take a look at: https://www.checkov.io/6.Contribution/Contribute%20New%20Terraform%20Provider.html 
we would gladly accept a PR on it

**Comment by mohitsaxenaknoldus** [comment]
If this is still available can you please assign it to me? I'll do it.

**Comment by JamesWoolfenden** [comment]
go for it!

**Comment by mohitsaxenaknoldus** [comment]
@JamesWoolfenden I checked the repo and the required files are already there I think.

**Comment by schosterbarak** [comment]
@mohitsaxenaknoldus where?

**Comment by mohitsaxenaknoldus** [comment]
https://github.com/bridgecrewio/checkov/tree/master/tests/terraform/checks/resource/linode

**Comment by JamesWoolfenden** [comment]
let me know if you need any support on this.
