### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' with an empty yaml file in custom dir

### ISSUE THREAD

**Issue by dwilliams782** [bridgecrewio/checkov#1109]
**Describe the bug**
When an empty yaml file is declared in an external checks dir, you get this AttributeError

`AttributeError: 'NoneType' object has no attribute 'get'`

**To Reproduce**
1. Create a directory with an empty yaml file
2. Point checkov at that custom directory: `checkov -f <your-file>.tf --external-checks-dir <your-path>`

**Expected behavior**
The empty file should be ignored

**Desktop (please complete the following information):**
 - OS: os X
 - Checkov Version: 2.0.64

**Comment by njgibbon** [comment]
I'll work on resolving this :)

**Comment by njgibbon** [comment]
@gruebel - another one to close.

**Comment by gruebel** [comment]
Thanks to @njgibbon it is fixed since version `2.0.418`
