### ISSUE TITLE
Option to display parsing errors

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#111]
When checkov reports parsing errors there's no way to see the error or even the file which caused it. I'm testing this in a project which passes `terraform validate`.

```
$ checkov -f main.tf 

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
version: 1.0.181 

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

```

**Comment by schosterbarak** [comment]
Thank you @acdha can you share what version of terraform are you using?
also, if you can share a code snippet of main.tf it will help me understand

**Comment by acdha** [comment]
```
Terraform v0.12.21
+ provider.aws v2.51.0
```

The main.tf file is fairly large — it's from a project I was asked to review so I'm still working my way through it.

**Comment by acdha** [comment]
A little bit of binary searching found this was due to two inconsistencies in HCL parsing. The first was a map which used the older 0.11 syntax with `{KEY: VALUE}` — replacing that with `{KEY = VALUE }` fixed those files.

The second was similar: a variable declaration had a default value of an empty map. Checkov (but not Terraform) choked when that was split over two lines:

```hcl
variable "tags" {
  default = {
  }
}
```

Combining it onto one line solved that:

```hcl
variable "tags" {
  default = {}
}
```

**Comment by schosterbarak** [comment]
You can now get verbose logs using environment variable LOG_LEVEL=DEBUG - it can give further info about what's checkov is doing

**Comment by acdha** [comment]
Excellent, thanks!
