### ISSUE TITLE
Pipelines no longer stopping upon checkov failed checks

### ISSUE THREAD

**Issue by eparisca** [bridgecrewio/checkov#1111]
Dear team,

It appears that since checkov https://github.com/bridgecrewio/checkov/releases/tag/2.0.49 our pipelines went from erroring to passing without any changes on our side. Is it the case that checkov is no longer returning non-zero exit codes? Is this the new expected behavior? If so, the [documentation does not currently reflect it](https://www.checkov.io/4.Integrations/Bitbucket%20Cloud%20Pipelines.html)

We currently run the tool as follows:

`checkov -d ./terraform --quiet`

However, removing `--quiet` does not change the outcome.  

Thank you!

**Comment by larryboymi** [comment]
I was going to comment the same! Thanks for raising this

**Comment by schosterbarak** [comment]
Thank you so much! we've just pushed a fix at: https://github.com/bridgecrewio/checkov/pull/1112
would you mind checking again with latest version?

**Comment by larryboymi** [comment]
I did, version `2.0.67` worked for me. Thanks!

**Comment by eparisca** [comment]
Confirmed 2.0.67 workes as expected! Thank you @mikeurbanski1 !!!
