### ISSUE TITLE
Feature: Provide our own guideline link in a custom check

### ISSUE THREAD

**Issue by dwilliams782** [bridgecrewio/checkov#1115]
**Is your feature request related to a problem? Please describe.**
We are implementing checkov with the --output github_failed_only mode enabled. This leaves all failed custom checks with an empty guideline column. 

**Describe the solution you'd like**
We should be able to include "guideline" in the metadata section of a custom check.

**Comment by schosterbarak** [comment]
Hi @dwilliams782 . Thank you for this one. This feature is available in the bridgecrew.cloud platform. Feel free to give it a try :)

**Comment by njgibbon** [comment]
@gruebel  - Another one where related issue and PR's have been closed so this 1 can too.

**Comment by gruebel** [comment]
thanks to @vangundy-jason-pfg this is possible since version 2.0.484 🚀
