### ISSUE TITLE
When scanning a terraform plan, module resources are not fully qualified in the resource name

### ISSUE THREAD

**Issue by dwilliams782** [bridgecrewio/checkov#1116]
**Describe the bug**
![image](https://user-images.githubusercontent.com/42545485/115747593-52cfd300-a38d-11eb-82bb-380fc047d020.png)

each instance here of `google_storage_bucket.this` is created by a module, but we are unable to see which module is invoking this because the resource doesn't include `module.x.` before it.

**To Reproduce**
1. Scan a plan that contains resources created with modules, and use the github_failed_only output to see this table

**Expected behavior**
Any module created resources should be explicit in the output `module.x.resource.name`

**Desktop (please complete the following information):**
 - OS: OS X
 - Checkov Version: 2.0.67

**Comment by dwilliams782** [comment]
Is this a regression issue @robeden ?

https://github.com/bridgecrewio/checkov/issues/772

**Comment by dwilliams782** [comment]
https://github.com/bridgecrewio/checkov/issues/772

This issue was closed but reports the same error. The "solution" that closed that PR appears to target when checkov is scanning a module directory, but the issue reported is related to the resource in the plan file.

**Comment by pascal-hofmann** [comment]
This is still an issue. In addition to the incomplete resource address, the source code lines printed are also incorrect. checkov always reports all issues for the first resource with a given address inside a module.

**Comment by willgleich** [comment]
I was giving checkov a try and couldn't get custom module checks to work on terraform plan output. Would this bug prevent checkov from doing any module checks from `terraform plan` output?

```
class ModuleCheck(BaseModuleCheck):
    def __init__(self):
        name = "Some test for module calls"
        id = "CKV_M_999"
        # supported_resources = ['module']
        categories = [CheckCategories.BACKUP_AND_RECOVERY]
        super().__init__(name=name, id=id, categories=categories)

    def scan_module_conf(self, conf):
        """
        Some test for module source
        :param conf: module call
        :return: <CheckResult>
        """
        return CheckResult.FAILED


scanner = ModuleCheck()

```
