### ISSUE TITLE
<string>:1: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?

### ISSUE THREAD

**Issue by dwilliams782** [bridgecrewio/checkov#1128]
**Describe the bug**
We get the syntax error above when running checkov against certain directories:

![image](https://user-images.githubusercontent.com/42545485/116095490-61293200-a6a0-11eb-8e54-fac79ac33d51.png)

I've narrowed this down to being caused by .auto.tfvars, this is the example config:

```
iam_bindings.tf

resource "google_project_iam_member" "gcp_devs" {
  for_each = toset(var.gcp_devs_bindings["roles"])
  role     = each.value
  member   = var.gcp_devs_bindings["member"]
}

variable "gcp_devs_bindings" {}
```

```
iam_bindings.auto.tfvars

gcp_devs_bindings = {
  member = "group:gcp-devs@loveholidays.com",
  roles = [
    "roles/viewer",
    "roles/bigquery.admin",
    "roles/cloudscheduler.admin",
    "roles/container.clusterAdmin",
    "roles/run.admin",
    "roles/storagetransfer.user",
    "roles/automl.admin",
    "roles/cloudsql.admin",
    "roles/cloudtasks.admin",
    "roles/composer.admin",
    "roles/compute.admin",
    "roles/cloudscheduler.jobRunner",
    "roles/serviceusage.apiKeysAdmin",
  ]
}

```

If I replace the auto.tfvars file with locals, the error goes away. 

**To Reproduce**
1. Run checkov against the above code.

**Expected behavior**
No error, or more concise where the error is coming from.

**Desktop (please complete the following information):**
 - OS: os X
 - Checkov Version 2.0.77

**Comment by zachpetersen** [comment]
I am having a similar issue with AzureRM provider Terraform. Error message is slightly different:

`<string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?`


```
user@host:~/projects/tf.test/tf.test.networking$ docker run --volume $(pwd):/src bridgecrew/checkov --directory /src --output junitxml > checkovreport.xml
<string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
user@host:~/projects/tf.test/tf.test.networking$ docker run --volume $(pwd):/src bridgecrew/checkov --directory /src
<string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.113
````

**Comment by tronxd** [comment]
> **Describe the bug**
> We get the syntax error above when running checkov against certain directories:
> 
> ![image](https://user-images.githubusercontent.com/42545485/116095490-61293200-a6a0-11eb-8e54-fac79ac33d51.png)
> 
> I've narrowed this down to being caused by .auto.tfvars, this is the example config:
> 
> ```
> iam_bindings.tf
> 
> resource "google_project_iam_member" "gcp_devs" {
>   for_each = toset(var.gcp_devs_bindings["roles"])
>   role     = each.value
>   member   = var.gcp_devs_bindings["member"]
> }
> 
> variable "gcp_devs_bindings" {}
> ```
> 
> ```
> iam_bindings.auto.tfvars
> 
> gcp_devs_bindings = {
>   member = "group:gcp-devs@loveholidays.com",
>   roles = [
>     "roles/viewer",
>     "roles/bigquery.admin",
>     "roles/cloudscheduler.admin",
>     "roles/container.clusterAdmin",
>     "roles/run.admin",
>     "roles/storagetransfer.user",
>     "roles/automl.admin",
>     "roles/cloudsql.admin",
>     "roles/cloudtasks.admin",
>     "roles/composer.admin",
>     "roles/compute.admin",
>     "roles/cloudscheduler.jobRunner",
>     "roles/serviceusage.apiKeysAdmin",
>   ]
> }
> ```
> 
> If I replace the auto.tfvars file with locals, the error goes away.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Run checkov against the above code.
> 
> **Expected behavior**
> No error, or more concise where the error is coming from.
> 
> **Desktop (please complete the following information):**
> 
> * OS: os X
> * Checkov Version 2.0.77

Hi @dwilliams782, I ran the latest checkov version (2.0.117) against your configuration and got no errors. can you please try upgrading checkov and see if the problem persists?

**Comment by tronxd** [comment]
> I am having a similar issue with AzureRM provider Terraform. Error message is slightly different:
> 
> `<string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?`
> 
> ```
> user@host:~/projects/tf.test/tf.test.networking$ docker run --volume $(pwd):/src bridgecrew/checkov --directory /src --output junitxml > checkovreport.xml
> <string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
> <string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
> <string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
> user@host:~/projects/tf.test/tf.test.networking$ docker run --volume $(pwd):/src bridgecrew/checkov --directory /src
> <string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
> <string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
> <string>:1: SyntaxWarning: 'set' object is not subscriptable; perhaps you missed a comma?
> 
>        _               _
>    ___| |__   ___  ___| | _______   __
>   / __| '_ \ / _ \/ __| |/ / _ \ \ / /
>  | (__| | | |  __/ (__|   < (_) \ V /
>   \___|_| |_|\___|\___|_|\_\___/ \_/
> 
> By bridgecrew.io | version: 2.0.113
> ```

Hi @zachpetersen, do you mind sharing a sample (can be anonymized) so I will debug it?

**Comment by zachpetersen** [comment]
> Hi @zachpetersen, do you mind sharing a sample TF configuration (can be anonymized) so I will debug it?

Here is the file that seems to be triggering the error:

```
locals {
  addrs_by_idx  = cidrsubnets(var.base_cidr_block, var.networks[*].new_bits...)
  addrs_by_name = { for i, n in var.networks : n.name => local.addrs_by_idx[i] if n.name != null }
  network_objs = [for i, n in var.networks : {
    name       = n.name
    new_bits   = n.new_bits
    cidr_block = n.name != null ? local.addrs_by_idx[i] : tostring(null)
  }]
}
```

Here is the TF module link: https://github.com/hashicorp/terraform-cidr-subnets

**Comment by dwilliams782** [comment]
> > **Describe the bug**
> > We get the syntax error above when running checkov against certain directories:
> > ![image](https://user-images.githubusercontent.com/42545485/116095490-61293200-a6a0-11eb-8e54-fac79ac33d51.png)
> > I've narrowed this down to being caused by .auto.tfvars, this is the example config:
> > ```
> > iam_bindings.tf
> > 
> > resource "google_project_iam_member" "gcp_devs" {
> >   for_each = toset(var.gcp_devs_bindings["roles"])
> >   role     = each.value
> >   member   = var.gcp_devs_bindings["member"]
> > }
> > 
> > variable "gcp_devs_bindings" {}
> > ```
> > 
> > 
> > ```
> > iam_bindings.auto.tfvars
> > 
> > gcp_devs_bindings = {
> >   member = "group:gcp-devs@loveholidays.com",
> >   roles = [
> >     "roles/viewer",
> >     "roles/bigquery.admin",
> >     "roles/cloudscheduler.admin",
> >     "roles/container.clusterAdmin",
> >     "roles/run.admin",
> >     "roles/storagetransfer.user",
> >     "roles/automl.admin",
> >     "roles/cloudsql.admin",
> >     "roles/cloudtasks.admin",
> >     "roles/composer.admin",
> >     "roles/compute.admin",
> >     "roles/cloudscheduler.jobRunner",
> >     "roles/serviceusage.apiKeysAdmin",
> >   ]
> > }
> > ```
> > 
> > 
> > If I replace the auto.tfvars file with locals, the error goes away.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Run checkov against the above code.
> > 
> > **Expected behavior**
> > No error, or more concise where the error is coming from.
> > **Desktop (please complete the following information):**
> > 
> > * OS: os X
> > * Checkov Version 2.0.77
> 
> Hi @dwilliams782, I ran the latest checkov version (2.0.117) against your configuration and got no errors. can you please try upgrading checkov and see if the problem persists?

Hi, I've just tried with 2.0.124 and still see the same warnings.

**Comment by schosterbarak** [comment]
fixed. thanks @tronxd
