### ISSUE TITLE
CKV_AZURE_109 is case sensitive

### ISSUE THREAD

**Issue by lengland** [bridgecrewio/checkov#1131]
**Describe the bug**
Creating an Azure Key Vault using Terraform without `network_acls` block triggers `CKV_AZURE_109` to be raised
Adding the block defined [on the checkov docs](https://docs.bridgecrew.io/docs/ensure-that-key-vault-allows-firewall-rules-settings) fixes the check, but fails deployment as the allowed values are `[Allow Deny]` in Terraform. 
Changing the `default_action = "deny"` to `default_action = "Deny"` causes the `CKV_AZURE_109` to be raised again.

**To Reproduce**
1. Create a `azurerm_key_vault` resource in Terraform
    * Running Checkov complains about Key Vault Firewall
2. Add the `network_acls` example block from the docs
    * Running Checkov passes
    * Running Terraform plan fails 
3. Change the `deny` to `Deny`
    * Running Checkov fails again

**Expected behavior**
Using `default_action = "Deny"` should appease both Checkov and Azure

**Desktop (please complete the following information):**
 - OS: Ubuntu container (mcr.microsoft.com/vscode/devcontainers/base:0-focal)
 - Checkov Version 2.0.67 (As bundled in [Terraform pre-commit hook](https://github.com/antonbabenko/pre-commit-terraform)

**Comment by htonkovac** [comment]
I can confirm this is broken. I tried fixing the rule, but I am not sure if I need to update anything else: https://github.com/bridgecrewio/checkov/pull/1165

**Comment by htonkovac** [comment]
@lengland @schosterbarak My PR that fixes this behaviour was merged. How can I update the docs as well?

**Comment by nimrodkor** [comment]
Resolved in #1165
