### ISSUE TITLE
-c CHECK doesn't seem to work for custom checks?

### ISSUE THREAD

**Issue by dwilliams782** [bridgecrewio/checkov#1133]
**Describe the bug**
I have a bunch of custom checks which correctly report errors:
![image](https://user-images.githubusercontent.com/42545485/116228260-f3870f80-a74c-11eb-89af-49f5b8f1e477.png)

However, I can't pass those in using the `-c` arg:

![image](https://user-images.githubusercontent.com/42545485/116228356-17e2ec00-a74d-11eb-8ace-777a15021723.png)

I verified it works if you pass in one of the built-in checks, just not the custom ones.

**Desktop (please complete the following information):**
 - OS: os X
 - Checkov Version 2.0.79

**Comment by gruebel** [comment]
@schosterbarak what is the expected behaviour here? I found the code part, which makes it not possible to set an `--external-checks-dir` and limit which ones to check via `--checks` flag.

**Comment by gruebel** [comment]
hey @dwilliams782 tested it with the latest version and it works to limit checkv you want to run via `--check` for custom checks.
