### ISSUE TITLE
Sample Integration with Azure DevOps

### ISSUE THREAD

**Issue by istairbn** [bridgecrewio/checkov#1145]
**Is your feature request related to a problem? Please describe.**
Currently, there are sample integrations with GitLab, Github etc. I'd like a similar document for Azure DevOps - specifically in configuring the Test Plans

**Describe the solution you'd like**
A similar documentation page to Jenkins, with screens and examples. 

**Describe alternatives you've considered**
I mean, I could move to a different SCM, but my enterprise is stuck on it!

**Additional context**

**Comment by zachpetersen** [comment]
This article helped me get going in Azure DevOps Pipelines:  https://adinermie.com/publishing-checkov-terraform-quality-checks-to-azure-devops-pipelines/
