### ISSUE TITLE
Unable to skip CKV_AWS_130

### ISSUE THREAD

**Issue by paliwalvimal** [bridgecrewio/checkov#1146]
**Describe the bug**
I have a two-tier network infrastructure template written in terraform which basically sets up a VPC network. In there, I have a public subnet block which has parameter `map_public_ip_on_launch` set to **true**. Even after adding `#checkov:skip=CKV_AWS_130:Public IP required in public subnet` within the resource check still fails. I do have other check skips but just the `CKV_AWS_130` is failing

**To Reproduce**
1. Create an aws subnet resource block
2. Add the skip statement
3. Test it and see the error

**Expected behavior**
It should be shown as skipped check

**Screenshots**
<img width="723" alt="Screenshot 2021-04-29 at 9 08 22 PM" src="https://user-images.githubusercontent.com/34170345/116578775-60f29600-a92f-11eb-83cb-aedc04daf72c.png">

<img width="610" alt="Screenshot 2021-04-29 at 9 08 34 PM" src="https://user-images.githubusercontent.com/34170345/116578819-69e36780-a92f-11eb-8868-213a2e183b45.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Checkov Version: 2.0.84

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by gruebel** [comment]
I tried exactly your code and there was no issue on my side, my checkov version is a bit higher than yours, but I don't think that could be the problem

```shell

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.87 

terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 1

Check: CKV_AWS_130: "Ensure VPC subnets do not assign public IP by default"
        SKIPPED for resource: aws_subnet.pub_sub
        Suppress comment: Public IP required in public subnet
        File: /main.tf:5-14

```

**Comment by paliwalvimal** [comment]
Where could I be possibly going wrong then? Anything from the screenshot that can help you identify the issue or is there anything I can provide you for help because I'm using other skip statements too in the same main.tf file and they all work. This is the only check that is failing.

<img width="643" alt="Screenshot 2021-04-29 at 9 59 28 PM" src="https://user-images.githubusercontent.com/34170345/116585589-2dffd080-a936-11eb-9136-8bd0db7cd8be.png">

**Comment by paliwalvimal** [comment]
One thing I noticed while running the scan in DEBUG mode is that the evaluation key is present for the public IP check for public subnet resource whereas there isn't any evaluation key for S3 MFA delete or any other checks I'm skipping.
<img width="1420" alt="Screenshot 2021-04-29 at 10 18 18 PM" src="https://user-images.githubusercontent.com/34170345/116588622-67860b00-a939-11eb-857d-3ad8925f37f8.png">

<img width="1413" alt="Screenshot 2021-04-29 at 10 18 44 PM" src="https://user-images.githubusercontent.com/34170345/116588637-69e86500-a939-11eb-952d-6ffe847b0b28.png">

**Comment by nimrodkor** [comment]
@paliwalvimal Hey!
looking at your output - is it just me or are the line numbers off?
That might affect the supression

**Comment by paliwalvimal** [comment]
Sorry, @nimrodkor. I didn't get your point.

**Comment by JamesWoolfenden** [comment]
I don't see this issue with 2.0.344:
`resource "aws_subnet" "pub_sub" {
	# checkov:skip=CKV_AWS_130: no reason
    count = length(var.azs)
    vpc_id= aws_vpc.vpc.vpc_id
    map_public_ip_on_launch=true
    cidr_block = cidrsubnet(
        var.cidr_block,
        var.pub_subnet_mask - local.vpc_mask,
        count.index
    )
    availability_zone=element(var.azs, count.index)
}`

Is suppressed just fine.

```
> checkov -f subnet.tf

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.344 

terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 1

Check: CKV_AWS_130: "Ensure VPC subnets do not assign public IP by default"
        SKIPPED for resource: aws_subnet.pub_sub
        Suppress comment:  no reason
        File: /subnet.tf:1-12
```

@paliwalvimal can you verify with the latest checkov pls.

**Comment by paliwalvimal** [comment]
weird. still fails for me on the latest version

<img width="817" alt="Screenshot 2021-09-07 at 5 36 52 PM" src="https://user-images.githubusercontent.com/34170345/132341818-6ec94174-606d-402b-8d29-30dc2d0099d7.png">
<img width="453" alt="Screenshot 2021-09-07 at 5 37 27 PM" src="https://user-images.githubusercontent.com/34170345/132341873-edbd00a3-6217-4bc9-bf7e-60e8c6e0910a.png">
<img width="778" alt="Screenshot 2021-09-07 at 5 37 51 PM" src="https://user-images.githubusercontent.com/34170345/132341930-7548e287-75ca-404c-b110-deb7b87ca4aa.png">

**Comment by JamesWoolfenden** [comment]
@paliwalvimal  if you post your code rather than an image, i could verify?

**Comment by paliwalvimal** [comment]
@JamesWoolfenden sure
`resource "aws_subnet" "pub_sub" {
  # checkov:skip=CKV_AWS_130: Public IP required in public subnet
  count                   = length(var.azs)
  vpc_id                  = aws_vpc.vpc.id
  map_public_ip_on_launch = var.map_public_ip_for_public_subnet
  cidr_block = cidrsubnet(
    var.cidr_block,
    var.pub_subnet_mask - local.vpc_mask,
    count.index,
  )
  availability_zone = element(var.azs, count.index)

  tags = merge({
    Name = "${var.network_name}-pub-sub-${element(var.azs, count.index)}"
    Tier = "public"
  }, var.tags, var.add_eks_tags ? { "kubernetes.io/role/elb" : "1" } : {})
}`
