### ISSUE TITLE
checkov directory switch not repeatable

### ISSUE THREAD

**Issue by snackwagon** [bridgecrewio/checkov#115]
**Describe the bug**
When running checkov -h, the directory switch claims it is repeatable but when you repeat it, only the last directory listed is scanned

```
  -d DIRECTORY, --directory DIRECTORY
                        Terraform root directory (can not be used together with --file). Can be repeated
```

**To Reproduce**
1. Create two directories (directory1, directory2) containing valid terraform files
2. Run cli command  `checkov -d ./directory1 -d ./directory2`
3. Only directory2 is scanned

**Expected behavior**
Both directory1 and directory2 are scanned

**Desktop (please complete the following information):**
 - Checkov Version: 1.0.180 

**Additional context**
I would actually prefer a recursive switch, using the -d directive multiple times is a workaround

**Comment by sp3nx0r** [comment]
Dogpile for recursive option. Our IaC repo is highly branched and doing a workaround to pass all the applicable files would be painful. A `-r` for recursive arg would be awesome

**Comment by nimrodkor** [comment]
Hey @sp3nx0r !
Just opened a PR for the original request. Your request isn't directly connected, so I'll open a new issue for it.
However, checkov does iterate through local modules referenced. Does that, together with having a multiple -d switch, usable?

**Comment by sp3nx0r** [comment]
Yeah, that'd do with a tad bit of overhead to string it together. Our mono-repo has individual branches for each cluster (dev, test, build, prod, etc.) with a few abstracted modules pulled out. Will give the PR a shot and provide more feedback. Thanks!

**Comment by JeanFred** [comment]
Hi!

Even with #209, the behaviour is not as expected: at the end of the loop there is [a call to `runner_registry.print_reports` ](https://github.com/bridgecrewio/checkov/blob/master/checkov/main.py#L71), which [has an `exit`](https://github.com/bridgecrewio/checkov/blob/master/checkov/common/runners/runner_registry.py#L55) − the additional directories are never processed.

I thought an easy fix was to just move the call to `runner_registry.print_reports` after the loop ; this sort of works: the analysis is ran on both directories, and the report for each is printed. However, things become tricky switching to a different output formats: `json` does result in a valid JSON (bit the schema seems off) ; and with `junitxml` it generates the `<?xml version="1.0" ?>
` preamble twice − so not sure whether this is viable…

**Comment by metahertz** [comment]
I'm potentially missing something here, but with talk of an `-r` flag, checkov's behaviour is recursive for `-d` anyway;

Given a directory with the following layout:
```
➜  terraform git:(master) ls -la
total 0
drwxr-xr-x   5 matt  staff  160  7 Oct 16:41 .
drwxr-xr-x   9 matt  staff  288  7 Oct 16:41 ..
drwxr-xr-x  16 matt  staff  512  7 Oct 16:41 aws
drwxr-xr-x  17 matt  staff  544  7 Oct 16:41 azure
drwxr-xr-x   9 matt  staff  288  7 Oct 16:41 gcp
➜  terraform git:(master) ls
```

Checkov will return results from all three, this is from the terragoat project under `./terraform`
https://github.com/bridgecrewio/terragoat/tree/master/terraform

Does that not solve the original issue of needing to scan multiple directories?

**Comment by JeanFred** [comment]
> I'm potentially missing something here, but with talk of an -r flag, checkov's behaviour is recursive for -d anyway;
> Does that not solve the original issue of needing to scan multiple directories?

Not sure whether this is a common use case, but in my case the repository layout is so that the common parent also contains a bunch of directories that I do not want to scan (either because they would raise false positives, or are irrelevant and just slow down the execution to a crawl).

In my case for example the repo looks like as follows:
```
├── _ext_modules ← vendored modules, full of false positives, should not be checked
├── layers      ← Terraform code, also needs to be checked
├── modules ← Terraform code, needs to be checked
├── packer ← packer definitions, irrelevant
├── spec  ← serverspec code, irrelevant
└── vendor  ← 100 MB worth of Ruby dependencies, irrelevant 
```

I would then want to execute `checkov -d ./layers -d ./modules`

(In my case, for the most part, the code in `moduels` is referenced from `layers` so checkov follows fine ; but the general use case stands I think)
