### ISSUE TITLE
When using --skip-check the summary still reports "Skipped checks: 0"

### ISSUE THREAD

**Issue by kevincantu** [bridgecrewio/checkov#1151]
Without the flag there are many checks done (18 in my sample Terraform code):
```sh
% checkov --quiet --file plan.tfplan.json
...
terraform_plan scan results:

Passed checks: 17, Failed checks: 1, Skipped checks: 0
...
```

Using checkov 2.0.84, I find that if I skip a terraform check or terraform_plan check like so:
```sh
checkov --quiet --file plan.tfplan.json --skip-check CKV_GCP_2
```

Then the total reported shows _nothing skipped_!
```
terraform_plan scan results:

Passed checks: 9, Failed checks: 0, Skipped checks: 0
```

I would have expected the same total number of checks, just a bunch more skipped.  Does that make sense?

**Comment by nimrodkor** [comment]
Hi @kevincantu!
I realize the terms might be confusing, but the `Skipped checks` in the report are checks which were evaluated, but skipped. When utilizing the `--skip-check` functionality, you disable the evaluation of a specific check altogether - therefore they are not counted towards the `Skipped checks` counter. 

I understand we should add this clarification somewhere, open to good ideas!

**Comment by shukla2009** [comment]
Where can I see the skipped check count one which are passed as parameter as we have requirement to demonstrate what all check we skipped.

**Comment by shukla2009** [comment]
I went with the annotation option for helm/Kubernetes which I believe is the better auditable manner of skipping the checks and also available in skipped check count and details.
```
"annotations"
      "checkov.io/skip1": "CKV_K8S_12=QoS of BestEffort Desired"
```

**Comment by kevincantu** [comment]
Yeah: but last time I was exploring, for Terraform there were still some things you couldn't skip through the inline annotations (particularly when validating plan files).
