### ISSUE TITLE
Broken link: https://www.checkov.io/4.Integrations/pre-commit.html

### ISSUE THREAD

**Issue by tomarv2** [bridgecrewio/checkov#1167]
Hi Team, this link was working a couple of weeks ago I think and today when I tried to use it, it says not found.

<img width="943" alt="Screen Shot 2021-05-04 at 9 29 23 AM" src="https://user-images.githubusercontent.com/11890959/117037453-559ac400-acbb-11eb-9d09-25d208a8c300.png">

**Comment by schosterbarak** [comment]
Thank you @tomarv2 fixed!
