### ISSUE TITLE
Running checks against terraform state

### ISSUE THREAD

**Issue by renehernandez** [bridgecrewio/checkov#1169]
**Is your feature request related to a problem? Please describe.**
For some features of terraform e.g. `for_each`, I would like to evaluate our custom checks against a terraform plan (in a pull request) and against the terraform state (after `terraform apply` and changes have been merged to our default branch). I can currently perform the custom checks against a terraform plan, but not a terraform state 

**Describe the solution you'd like**
Support terraform state (in json format), similar to how a Terraform plan is supported

**Comment by schosterbarak** [comment]
Hmm. interesting. would you mind sharing an anonymized state (without sensitive data ) for testing purposes?

**Comment by dwilliams782** [comment]
@renehernandez are you sure custom checks are working against your plan? They aren't for me. See #1135
