### ISSUE TITLE
Add filename to the output for each failed check when using directory option

### ISSUE THREAD

**Issue by dc401** [bridgecrewio/checkov#1170]
**Is your feature request related to a problem? Please describe.**
When scanning multiple files in a directory, failed checks while providing the line numbers of the offending code do not provide the filename associated with this. When you've got more than a handful of templates to check; this becomes cumbersome to back trace especially when you have similar code or variables names that one can't simply grep for.

Applicable to run option:  checkov --directory ./

**Describe the solution you'd like**
Somewhere in the failed check output, can you add the filename(s) of the offending check or create a "verbose" option so that we an see this.

**Describe alternatives you've considered**
The only other option is to attempt to grep a very specific and unique section of an offending portion of code which gets difficult. Or necessarily iterate a for loop in a script denoting each file and then having a print statement or a log file capture each iterations file name.

**Additional context**
N/A

**Comment by nimrodkor** [comment]
Hi @dc401 !

I checked the output of the latest checkov version, 2.0.115, and it does contain the file name for checks. Example:
![Uploading image.png…]()
There's the `Check: CKV...` line, then the result line (`FAILED for re...` or `PASSED for re...`) and then the `File: /...` line. Can you share your output please?

**Comment by dc401** [comment]
Hi, thanks for this, currently using  version: 2.0.113. I investigated further and because I was using PowerShell with the same color background your file line was not showing up. My apologies!
