### ISSUE TITLE
CKV_AWS_111 Fails on IAM write actions that cannot be restricted. 

### ISSUE THREAD

**Issue by caruso-billfire** [bridgecrewio/checkov#1173]
**Describe the bug**
There are IAM write actions that you cannot restrict via "resource" 

**To Reproduce**
Add any of the following IAM actions to an IAM Policy Document 

Write Actions:
 "xray:PutTraceSegments",  
"xray:PutTelemetryRecords",  

**Expected behavior**
Checkov should allow these actions to have "unrestricted write access". 

Do you guys know if I need to add this issue to https://github.com/salesforce/cloudsplaining ? 
We are using cloudformation, I know checkov uses an integration with them.

**Screenshots**
![image](https://user-images.githubusercontent.com/48571322/117224539-0b056e80-adc5-11eb-86d2-9665cae13ef5.png)
Another Screenshot from the docs (linked below) note how these 2 iam actions have to have unrestricted write
![image](https://user-images.githubusercontent.com/48571322/117224778-a26ac180-adc5-11eb-8d5a-d842ccacaa56.png)

**Desktop (please complete the following information):**
 - linux
 - 2.0.113

**Additional context** 
https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsx-ray.html

**Comment by nimrodkor** [comment]
Hi @caruso-billfire !

You are correct, these checks are using logic in [cloudsplaining](https://github.com/salesforce/cloudsplaining). Do you mind opening an issue for it there?

**Comment by nimrodkor** [comment]
Keeping this issue open for tracking

**Comment by caruso-billfire** [comment]
Yup, I can open it there
You guys might want to check the terraform side of this though.

**Comment by kmcquade** [comment]
@nimrodkor @caruso-billfire @schosterbarak - I think I uncovered the underlying issue. See my comment in Cloudsplaining here: https://github.com/salesforce/cloudsplaining/issues/190#issuecomment-841598595
