### ISSUE TITLE
Bug when running checkov with official docker image

### ISSUE THREAD

**Issue by anavarreteuk** [bridgecrewio/checkov#119]
**Describe the bug**
When I try to use the scanner locally it shows me five failed checks but I can only see two of them
in the output. Also it outputs an UnboundLocalError

**To Reproduce**
1. docker pull bridgecrew/checkov
2. docker run -t -v /$PWD:/tf bridgecrew/checkov -d tf
3. See error

**Expected behavior**
A full output of all the tests failing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/39244818/76407969-81a70780-638c-11ea-985c-1dad728c3f98.png)

**Desktop (please complete the following information):**
 - OS: [Centos 7]
 - Checkov Version [latest docker image]

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by bakeruk** [comment]
I get the same error when using the CLI command `checkov -f main.tf ` or `checkov -d . `.

I think it might be the `checkov` package itself.

**Comment by tronxd** [comment]
Hey @bakeruk , can you please provide the configuration files you are trying to scan? And please provide the `checkov` version you are currently using.

**Comment by schosterbarak** [comment]
Hey @bakeruk . I've just pushed a temporal fix here: https://github.com/bridgecrewio/checkov/commit/2f72f11fe236dc59fa0601e2e9b9d24643dcb235
Would love to get a code sample and add it to our unit tests to make sure it won't happen again
