### ISSUE TITLE
boto3 is fixed at the patch level version

### ISSUE THREAD

**Issue by Raffaello** [bridgecrewio/checkov#1211]
**Is your feature request related to a problem? Please describe.**
free boto3 dependency patch version.

**Describe the solution you'd like**
replace the line here:
https://github.com/bridgecrewio/checkov/blob/master/Pipfile#L29

with 
```
boto3 = "==1.17.*"
```
**Describe alternatives you've considered**
there are no alternatives as the patch version i don't see why is locked.
it can cause conflicts with already installed boto3 library 

**Additional context**

**Comment by nimrodkor** [comment]
Would love a PR on it. tnx @Raffaello !
