### ISSUE TITLE
Suppressing findings per resource when scanning a Terraform plan?

### ISSUE THREAD

**Issue by christophetd** [bridgecrewio/checkov#1224]
**Is your feature request related to a problem? Please describe.**
Problem: It seems unsupported to [suppress](https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html) findings on a resource when scanning a TF plan.

**Describe the solution you'd like**
A way to tag / comment a resource so the findings are not only suppressed when scanning the HCL code, but also the plan.

**Describe alternatives you've considered**
None. This seems like a quite important blocking point

**Comment by pascal-hofmann** [comment]
I think this issue can be close.

**Comment by christophetd** [comment]
Indeed! Thanks
