### ISSUE TITLE
Failed with error message "Failed to get customer assumed role"

### ISSUE THREAD

**Issue by deepakcpakhale06** [bridgecrewio/checkov#1243]
**Describe the bug**
Unable to run checkov locally. Fails with error "Failed to get customer assumed role"

**To Reproduce**
Run checkov locally. Supply mandatory parameters bc_api_key and repo_id as mentioned in the workshop

**Expected behavior**
Local scans of checkov should not be dependent on cloud account

**Screenshots**
![image](https://user-images.githubusercontent.com/25992105/119424367-e4898200-bd37-11eb-83ad-e3cfb0d7c90d.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Checkov Version [2.0.161]

**Comment by magnologan** [comment]
Same issue here. It happened after I tried to integrate the results with Bridgecrew via bc_api_key. Afterward, it kept happening even when not using the bc_api_key parameter anymore. Tried reinstalling it, but it didn't do the trick. The only option was using the Docker version.


<img width="1792" alt="Screen Shot 2021-10-05 at 3 51 28 PM" src="https://user-images.githubusercontent.com/1558043/136093229-b7619eab-0f5c-4759-ae3a-f27506a7a2c8.png">

[checkov_error.txt](https://github.com/bridgecrewio/checkov/files/7288847/checkov_error.txt)


Desktop:

OS: Mac
Checkov Version 2.0.469

**Comment by schosterbarak** [comment]
hey guys looks like you are working under a VPN or a firewall that is changing the cert
try using --ca-certificate CA_CERTIFICATE flag to keep encrypted traffic with your cert

**Comment by magnologan** [comment]
Hi Barak,

No firewalls or VPNs here AFAIK. And it was working properly before I used the --bc_api_key parameter. The Docker version works fine in the same environment.

**Comment by schosterbarak** [comment]
do you use --bc_api_key with the docker version too?

**Comment by magnologan** [comment]
no, I didn't.

**Comment by magnologan** [comment]
What is curious is that even after I stopped using the bc_api_key with the command locally the issue still persisted, even after reinstalling checkov.

**Comment by nimrodkor** [comment]
Seems unrelated to checkov - this is a general SSL error. If you disagree and still run into this - please reopen!
