### ISSUE TITLE
Monitor services in azure

### ISSUE THREAD

**Issue by ashishsme14** [bridgecrewio/checkov#1250]
Our task is -

- Write a terraform script in azmonitor.tf to create a storage account, storage container, storage blob to monitor and send log reports everyday.
- Define the variables resourcegroup and location in the variables.tf file, and call those variables in the azmonitor.tf file using string interpolation syntax

With help of vi command we created variables.tf file as

```
variable "resourcegroup"
{
default = "user-ktywkgjskfgc"
}
variable "location"
{ 
default = ["East US"]
}
```

In normal way we can create storage account as -

`
az storage account create --resource-group $user-ofbujdqwzbib --name $storageccountName --location $location
`

how to call those variables in the azmonitor.tf and above command in tf file we are not sure. Please suggest us expertise advice.

**Comment by nimrodkor** [comment]
This is a terraform question, unrelated to checkov
