### ISSUE TITLE
RDS triggers CKV2_AWS_16: "Ensure that Auto Scaling is enabled on your DynamoDB tables"

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#1251]
I noticed a regression with 2.0.165:

Check: CKV2_AWS_16: "Ensure that Auto Scaling is enabled on your DynamoDB tables"
	FAILED for resource: aws_appautoscaling_policy.read_replicas
	File: /rds/main.tf:169-187
	Guide: https://docs.bridgecrew.io/docs/ensure-that-auto-scaling-is-enabled-on-your-dynamodb-tables

The resource in question is an RDS Aurora cluster which would explain this failure if it's looking for resource IDs to start with dynamodb or something like that:

```hcl
resource "aws_appautoscaling_policy" "read_replicas" {
  depends_on = [aws_appautoscaling_target.read_replicas]

  name               = "target-metric"
  policy_type        = "TargetTrackingScaling"
  resource_id        = "cluster:${aws_rds_cluster.this.cluster_identifier}"
  scalable_dimension = "rds:cluster:ReadReplicaCount"
  service_namespace  = "rds"

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "RDSReaderAverageCPUUtilization"
    }

    scale_in_cooldown  = 300
    scale_out_cooldown = 300
    target_value       = 70
  }
}
```

**Comment by gruebel** [comment]
I checked the code and how it is implemented it doesn't make much sense at the moment. it will flag each `aws_appautoscaling_policy` resource, which is not related to a DynamoDB table

**Comment by nimrodkor** [comment]
Thanks for reporting @acdha !
