### ISSUE TITLE
checkov plan -f not reading json file

### ISSUE THREAD

**Issue by Marcus-James-Adams** [bridgecrewio/checkov#1257]
**Describe the bug**
checkov -f fails to scan terraform.json

**To Reproduce**
terraform show -json > tfplan.json
checkov -f tfplan.json

**Expected behavior**
*NOTE* this was taken by running checkov plan -d . in the same directory

```
       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.168

terraform scan results:

<<<RESULTS SNIPPED FOR READABILITY>>>

Passed checks: 11, Failed checks: 11, Skipped checks: 0
c:\myfolder
```

**Actual behavior**
```
checkov -f ./tfplan.json

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.168
c:\myfolder>
```

**Desktop (please complete the following information):**
 
OS: Windows 10 - both command prompt and PowerShell, Python 3.9.5
Checkov v2.0.168
Terraform v0.15.3 (also tried on v0.15.4)
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.20.0
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.57.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.4

**Comment by kartikp10** [comment]
Hey @Marcus-James-Adams could you please update checkov and let me know if this is still failing? For me, I'm getting an output when I use the -f flag to scan a plan file.
```
❯ checkov -f tfplan.json

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.193

terraform_plan scan results:

Passed checks: 3, Failed checks: 5, Skipped checks: 0

Check: CKV_AWS_153: "Autoscaling groups should supply tags to launch configurations"
	PASSED for resource: aws_autoscaling_group.my_asg
	File: /tfplan.json:0-0

Check: CKV_AWS_88: "EC2 instance should not have public IP."
	PASSED for resource: aws_instance.web
	File: /tfplan.json:0-0
	Guide: https://docs.bridgecrew.io/docs/public_12

Check: CKV_AWS_46: "Ensure no hard-coded secrets exist in EC2 user data"
	PASSED for resource: aws_instance.web
	File: /tfplan.json:0-0
	Guide: https://docs.bridgecrew.io/docs/bc_aws_secrets_1

Check: CKV_AWS_79: "Ensure Instance Metadata Service Version 1 is not enabled"
	FAILED for resource: aws_instance.web
	File: /tfplan.json:0-0
	Guide: https://docs.bridgecrew.io/docs/bc_aws_general_31

Check: CKV_AWS_126: "Ensure that detailed monitoring is enabled for EC2 instances"
	FAILED for resource: aws_instance.web
	File: /tfplan.json:0-0
	Guide: https://docs.bridgecrew.io/docs/ensure-that-detailed-monitoring-is-enabled-for-ec2-instances

Check: CKV_AWS_135: "Ensure that EC2 is EBS optimized"
	FAILED for resource: aws_instance.web
	File: /tfplan.json:0-0
	Guide: https://docs.bridgecrew.io/docs/ensure-that-ec2-is-ebs-optimized

Check: CKV_AWS_8: "Ensure all data stored in the Launch configuration EBS is securely encrypted"
	FAILED for resource: aws_instance.web
	File: /tfplan.json:0-0
	Guide: https://docs.bridgecrew.io/docs/general_13

Check: CKV_AWS_8: "Ensure all data stored in the Launch configuration EBS is securely encrypted"
	FAILED for resource: aws_launch_configuration.my_web_config
	File: /tfplan.json:0-0
	Guide: https://docs.bridgecrew.io/docs/general_13
```

**Comment by jkesterson** [comment]
I have also had this issue on latest version (v2.0.247)

**Comment by jshrack-ssi** [comment]
Add me to the list.

![image](https://user-images.githubusercontent.com/6249804/138162538-ad402824-dd03-442f-8a6b-b8ec82b2b651.png)

**Comment by jkesterson** [comment]
@jshrack-ssi looks like your tfplan has parsing issues, my issue was that there was 0 output other than the banner, but I realized that was from no resources being created in my plan (i think)

**Comment by jkesterson** [comment]
@jshrack-ssi woah you may have found the issue, just found that another issue of mine (where one plan fails a check, and a nearly identical plan doesnt), the plan that passes is 0.1, the one that fails is 0.2

**Comment by jshrack-ssi** [comment]
I think to truly validate the assumption would require outputting a tfplan <v0.15 with format_version '0.1' and seeing what the outputs are. It's suspect checkov cannot auto-identify the output format as it perviously did without specifying --framework terraform_plan.
