### ISSUE TITLE
Dockerfile Framework Only Scans files named "Dockerfile"

### ISSUE THREAD

**Issue by knoxknot** [bridgecrewio/checkov#1262]
**Is your feature request related to a problem? Please describe.**
The tool cannot scan file names other than Dockerfile for the dockerfile framework 
Ex. checkov -f Dockerfile --framework dockerfile #works
      checkov -f Dockerfile.prod --framework dockerfile  #does not work

**Describe the solution you'd like**
Passing a framework flag should be able to scan the file irrespective of whether it is the default naming for that framework

**Comment by njgibbon** [comment]
@gruebel - This can be closed as PR resolved issue.

**Comment by gruebel** [comment]
thanks to @Xitric it is fixed since version `2.0.473`
