### ISSUE TITLE
Checkov don't work with custom checks when -f option is given

### ISSUE THREAD

**Issue by michal-adamkiewicz** [bridgecrewio/checkov#1270]
**Describe the bug**
When I work with **-d** flag and points terraform files everything works like a charm accordingly with documentation. But because we all know, that some things are being generated using modules in Terraform (a lot!) - modules hide underneath resources details - that's why we often need to provide a full plan (in JSON format) as input for Checkov (instead of static files). As soon as I'm switching for the **-f** flag, and point to my JSON plan I cannot force Checkov to trigger my custom checks.

I have been trying with local policy (--external-checks-dir) so as with remote one (--external-checks-git). Both YAML and JSON type. 
There is no error message, just a blank welcome record with Checkov

As soon as I go back to the **-d** flag it works.

**To Reproduce**
* checkov -f plan.json --check CUSTOM_AWS_1 --external-checks-git ....git
* checkov -f plan.json --check CUSTOM_AWS_1 --external-checks-dir my-policies/

**Expected behavior**
Run my custom checks against the plan file.

**Screenshots**
<img width="378" alt="obraz" src="https://user-images.githubusercontent.com/54705469/120992871-4eb41500-c783-11eb-9d0f-43cf25220af9.png">

**Desktop (please complete the following information):**
 - OS:  Mac 10.15.7
 - Checkov Version 2.0.181

**Comment by nimrodkor** [comment]
Hey @michal-adamkiewicz !

Can you please add these details:
1. Are these yaml (aka graph) checks or python checks?
2. Did providing the absolute path to the checks still reproduce this issue?

**Comment by michal-adamkiewicz** [comment]
Sure. First of all, thank you @nimrodkor for such a quick response!
It's crucial for me, as I would like incorporate checkov into our generic CI/CD standard

1. I have been trying with both of them, but let me paste my YAML check:

`---
metadata:
       name: "Check that all resources are tagged with the key - checkit"
       id: "CUSTOM_AWS_1"
       category: "GENERAL_SECURITY"
scope:
       provider: AWS
definition:
       cond_type: "attribute"
       resource_types: 
              - "all"
       attribute: "tags.checkit"
       operator: "exists"
`
This file is being saved in **policies/policy1.yaml**

2. How I run checkov?

`checkov -f plan-test.json --check CUSTOM_AWS_1 --external-checks-dir policies` (being one level up)

the same if I provide full absolute path:

`checkov -f plan-test.json --check CUSTOM_AWS_1 --external-checks-dir /Users/michal.adamkiewicz/git/projectABB/policies`

I have been trying also using the git protocol, but the outcome is still the same. Just welcome screen from Checkov and nothing more. Remove --check flag triggers regular checks against all default built-in policies, but unfortunately, that's not the point here.

<img width="296" alt="obraz" src="https://user-images.githubusercontent.com/54705469/121071541-59e16200-c7d0-11eb-894f-1a22a670642e.png">

3. To be fully transparent, I have been testing that against multiple plans. Also even including some generated only for testing purpose like one below:

`{
  "format_version": "0.1",
  "terraform_version": "0.13.6",
  "planned_values": {
    "root_module": {
      "resources": [
        {
          "address": "aws_autoscaling_group.my_asg",
          "mode": "managed",
          "type": "aws_autoscaling_group",
          "name": "my_asg",
          "provider_name": "aws",
          "schema_version": 0,
          "values": {
            "availability_zones": [
              "us-west-1a"
            ],
            "desired_capacity": 4,
            "enabled_metrics": null,
            "force_delete": true,
            "health_check_grace_period": 300,
            "health_check_type": "ELB",
            "initial_lifecycle_hook": [],
            "launch_configuration": "my_web_config",
            "launch_template": [],
            "max_size": 5,
            "metrics_granularity": "1Minute",
            "min_elb_capacity": null,
            "min_size": 1,
            "mixed_instances_policy": [],
            "name": "my_asg",
            "name_prefix": null,
            "placement_group": null,
            "protect_from_scale_in": false,
            "suspended_processes": null,
            "tag": [],
            "tags": null,
            "termination_policies": null,
            "timeouts": null,
            "wait_for_capacity_timeout": "10m",
            "wait_for_elb_capacity": null
          }
        },
        {
          "address": "aws_instance.web",
          "mode": "managed",
          "type": "aws_instance",
          "name": "web",
          "provider_name": "aws",
          "schema_version": 1,
          "values": {
            "ami": "ami-09b4b74c",
            "credit_specification": [],
            "disable_api_termination": null,
            "ebs_optimized": null,
            "get_password_data": false,
            "iam_instance_profile": null,
            "instance_initiated_shutdown_behavior": null,
            "instance_type": "t2.micro",
            "monitoring": null,
            "source_dest_check": true,
            "tags": null,
            "timeouts": null,
            "user_data": null,
            "user_data_base64": null
          }
        },
        {
          "address": "aws_launch_configuration.my_web_config",
          "mode": "managed",
          "type": "aws_launch_configuration",
          "name": "my_web_config",
          "provider_name": "aws",
          "schema_version": 0,
          "values": {
            "associate_public_ip_address": false,
            "enable_monitoring": true,
            "ephemeral_block_device": [],
            "iam_instance_profile": null,
            "image_id": "ami-09b4b74c",
            "instance_type": "t2.micro",
            "name": "my_web_config",
            "name_prefix": null,
            "placement_tenancy": null,
            "security_groups": null,
            "spot_price": null,
            "user_data": null,
            "user_data_base64": null,
            "vpc_classic_link_id": null,
            "vpc_classic_link_security_groups": null
          }
        }
      ]
    }
  },
  "resource_changes": [
    {
      "address": "aws_autoscaling_group.my_asg",
      "mode": "managed",
      "type": "aws_autoscaling_group",
      "name": "my_asg",
      "provider_name": "aws",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "availability_zones": [
            "us-west-1a"
          ],
          "desired_capacity": 4,
          "enabled_metrics": null,
          "force_delete": true,
          "health_check_grace_period": 300,
          "health_check_type": "ELB",
          "initial_lifecycle_hook": [],
          "launch_configuration": "my_web_config",
          "launch_template": [],
          "max_size": 5,
          "metrics_granularity": "1Minute",
          "min_elb_capacity": null,
          "min_size": 1,
          "mixed_instances_policy": [],
          "name": "my_asg",
          "name_prefix": null,
          "placement_group": null,
          "protect_from_scale_in": false,
          "suspended_processes": null,
          "tag": [],
          "tags": null,
          "termination_policies": null,
          "timeouts": null,
          "wait_for_capacity_timeout": "10m",
          "wait_for_elb_capacity": null
        },
        "after_unknown": {
          "arn": true,
          "availability_zones": [
            false
          ],
          "default_cooldown": true,
          "id": true,
          "initial_lifecycle_hook": [],
          "launch_template": [],
          "load_balancers": true,
          "mixed_instances_policy": [],
          "service_linked_role_arn": true,
          "tag": [],
          "target_group_arns": true,
          "vpc_zone_identifier": true
        }
      }
    },
    {
      "address": "aws_instance.web",
      "mode": "managed",
      "type": "aws_instance",
      "name": "web",
      "provider_name": "aws",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "ami": "ami-09b4b74c",
          "credit_specification": [],
          "disable_api_termination": null,
          "ebs_optimized": null,
          "get_password_data": false,
          "iam_instance_profile": null,
          "instance_initiated_shutdown_behavior": null,
          "instance_type": "t2.micro",
          "monitoring": null,
          "source_dest_check": true,
          "tags": null,
          "timeouts": null,
          "user_data": null,
          "user_data_base64": null
        },
        "after_unknown": {
          "arn": true,
          "associate_public_ip_address": true,
          "availability_zone": true,
          "cpu_core_count": true,
          "cpu_threads_per_core": true,
          "credit_specification": [],
          "ebs_block_device": true,
          "ephemeral_block_device": true,
          "host_id": true,
          "id": true,
          "instance_state": true,
          "ipv6_address_count": true,
          "ipv6_addresses": true,
          "key_name": true,
          "network_interface": true,
          "network_interface_id": true,
          "password_data": true,
          "placement_group": true,
          "primary_network_interface_id": true,
          "private_dns": true,
          "private_ip": true,
          "public_dns": true,
          "public_ip": true,
          "root_block_device": true,
          "security_groups": true,
          "subnet_id": true,
          "tenancy": true,
          "volume_tags": true,
          "vpc_security_group_ids": true
        }
      }
    },
    {
      "address": "aws_launch_configuration.my_web_config",
      "mode": "managed",
      "type": "aws_launch_configuration",
      "name": "my_web_config",
      "provider_name": "aws",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "associate_public_ip_address": false,
          "enable_monitoring": true,
          "ephemeral_block_device": [],
          "iam_instance_profile": null,
          "image_id": "ami-09b4b74c",
          "instance_type": "t2.micro",
          "name": "my_web_config",
          "name_prefix": null,
          "placement_tenancy": null,
          "security_groups": null,
          "spot_price": null,
          "user_data": null,
          "user_data_base64": null,
          "vpc_classic_link_id": null,
          "vpc_classic_link_security_groups": null
        },
        "after_unknown": {
          "ebs_block_device": true,
          "ebs_optimized": true,
          "ephemeral_block_device": [],
          "id": true,
          "key_name": true,
          "root_block_device": true
        }
      }
    }
  ],
  "configuration": {
    "provider_config": {
      "aws": {
        "name": "aws",
        "expressions": {
          "region": {
            "constant_value": "us-west-1"
          }
        }
      }
    },
    "root_module": {
      "resources": [
        {
          "address": "aws_autoscaling_group.my_asg",
          "mode": "managed",
          "type": "aws_autoscaling_group",
          "name": "my_asg",
          "provider_config_key": "aws",
          "expressions": {
            "availability_zones": {
              "constant_value": [
                "us-west-1a"
              ]
            },
            "desired_capacity": {
              "constant_value": 4
            },
            "force_delete": {
              "constant_value": true
            },
            "health_check_grace_period": {
              "constant_value": 300
            },
            "health_check_type": {
              "constant_value": "ELB"
            },
            "launch_configuration": {
              "constant_value": "my_web_config"
            },
            "max_size": {
              "constant_value": 5
            },
            "min_size": {
              "constant_value": 1
            },
            "name": {
              "constant_value": "my_asg"
            }
          },
          "schema_version": 0
        },
        {
          "address": "aws_instance.web",
          "mode": "managed",
          "type": "aws_instance",
          "name": "web",
          "provider_config_key": "aws",
          "expressions": {
            "ami": {
              "constant_value": "ami-09b4b74c"
            },
            "instance_type": {
              "constant_value": "t2.micro"
            }
          },
          "schema_version": 1
        },
        {
          "address": "aws_launch_configuration.my_web_config",
          "mode": "managed",
          "type": "aws_launch_configuration",
          "name": "my_web_config",
          "provider_config_key": "aws",
          "expressions": {
            "image_id": {
              "constant_value": "ami-09b4b74c"
            },
            "instance_type": {
              "constant_value": "t2.micro"
            },
            "name": {
              "constant_value": "my_web_config"
            }
          },
          "schema_version": 0
        }
      ]
    }
  }
}`

**Comment by michal-adamkiewicz** [comment]
Probably I have to switch to a different tool if this functionality doesn't work :(

**Comment by schosterbarak** [comment]
hi @michal-adamkiewicz i'll work on a fix sometime next week. Stay tuned.

**Comment by michal-adamkiewicz** [comment]
@schosterbarak seriously? 🙀 Thank you so much, buddy 👍 . I have already incorporated checkov inside Atlantis Gitops tool - your tool is a life safer for people like me;). I will be very grateful for any update on this 👌

**Comment by jkesterson** [comment]
Also having this issue, checks that aren't manually placed into the checkov default checks folder will not load. --external-checks-dir flag seems to do nothing right now (v.2.0.187)

**Comment by mikeurbanski1** [comment]
@jkesterson Are you also running on a plan file?

**Comment by mikeurbanski1** [comment]
@kartikp10 @schosterbarak could be related to https://github.com/bridgecrewio/checkov/issues/1257

**Comment by michal-adamkiewicz** [comment]
Hmm IMHO it looks exactly the same as the "mine" issue in the console. That's right.

**Comment by michal-adamkiewicz** [comment]
I'm sorry guys for focusing very much on this, but I'm only asking - do you think it's something "doable" or it will take longer than thought?

**Comment by lelandothegreat** [comment]
Our team is also very much awaiting this in order to use it

**Comment by michal-adamkiewicz** [comment]
Seems that unfortunately, I have to look for another solution, as I thought It will be easy solvable :/

**Comment by lelandothegreat** [comment]
Hi guys, any idea on when this would be fixed?

**Comment by nimrodkor** [comment]
Hey guys!
Sorry for the late response @lelandothegreat . Plan scanning does not generate a graph (no rendering is needed) and so custom graph checks do not run on it.
I've written a small workaround, will open a PR soon
@michal-adamkiewicz FYI
