### ISSUE TITLE
Will Checkov support Terragrunt ?

### ISSUE THREAD

**Issue by matthieu-audin** [bridgecrewio/checkov#1284]
I would like to know if checkov plan to support terragrunt ? If yes, when it is planned ?

**Comment by ismailyenigul** [comment]
Hi @matthieu-audin 


You can use `terragrunt plan` output in json with checkov.
```
terragrunt init
terragrunt plan -out tf.plan
terragrunt show -json tf.plan  > tf.json 
checkov -f tf.json
```

**Comment by sbkg0002** [comment]
This doesnt work for run-all unfortunately.

**Comment by jonjozwiak** [comment]
In my current project I'm using a before_hook in my pipelines.  I have used this with ```terragrunt run-all plan``` previously, but currently am using it just with ```terragrunt plan``` and it has worked well.  An example of this in your terragrunt.hcl is below: 

```
terraform {
    source = "git::https://ghe.mycompany.com/repo/my-terraform-repo.git//.?ref=v0.1.0"

    before_hook "checkov" {
        commands = ["plan"]
        execute = [
            "checkov",
            "-d",
            ".",
            "--quiet",
            "--skip-path",
            "/*/examples/*",
            "--framework",
            "terraform",
        ]
    }
}
```

**Comment by mf-anson** [comment]
Hi @jonjozwiak, in my case, checkov failed to convert terragrunt.hcl `input` to be the input of the module.
May I know when you use the before_hook setup like this, are you using input block from terragrunt.hcl, or directly put the input values to modules ?

**Comment by jonjozwiak** [comment]
@mf-anson Well I thought it did.  :(

I did a quick test.  Example main.tf: 

```
variable "port" {
  type = string
}

variable "cidr" {
  type = string
}

resource "aws_instance" "web_host" {
  # ec2 have plain text secrets in user data
  ami           = "ami-09a5b0b7edf08843d"
  instance_type = "t2.nano"

  vpc_security_group_ids = [
  "${aws_security_group.web-node.id}"]
  subnet_id = "subnet-0360d5a653b112345"
  user_data = <<EOF
#! /bin/bash
sudo apt-get update
sudo apt-get install -y apache2
sudo systemctl start apache2
sudo systemctl enable apache2
export AWS_ACCESS_KEY_ID=<from terragoat>
export AWS_SECRET_ACCESS_KEY=<from terragoat>
export AWS_DEFAULT_REGION=us-west-2
echo "<h1>Deployed via Terraform</h1>" | sudo tee /var/www/html/index.html
EOF
}

resource "aws_security_group" "web-node" {
  # security group is open to the world in SSH port
  name        = "test-sg"
  description = "Test Security Group"
  vpc_id      = "vpc-007f8a23445b12345"

  ingress {
    from_port = 80
    to_port   = 80
    protocol  = "tcp"
    cidr_blocks = [
    "0.0.0.0/0"]
  }
  ingress {
    from_port = var.port
    to_port   = var.port
    protocol  = "tcp"
    cidr_blocks = [
    var.cidr ]
  }
  egress {
    from_port = 0
    to_port   = 0
    protocol  = "-1"
    cidr_blocks = [
    "0.0.0.0/0"]
  }
}

output "ec2_public_dns" {
  description = "Web Host Public DNS name"
  value       = aws_instance.web_host.public_dns
}
```

Example terragrunt.hcl:

```
locals {
    port = 22
    cidr = "0.0.0.0/0"
}

terraform {
    source = "./"

    before_hook "env" {
        commands = ["plan"]
        execute = [
            "env"
        ]
    }

    before_hook "checkov" {
        commands = ["plan"]
        execute = [
            "checkov",
            "-d",
            ".",
            "--framework",
            "terraform",
        ]
    }
}

inputs = {
    port = local.port
    cidr = local.cidr
}
```

Executed terragrunt init && terragrunt plan:

Check: CKV_AWS_24: "Ensure no security groups allow ingress from 0.0.0.0:0 to port 22"
	PASSED for resource: aws_security_group.web-node
	File: /main.tf:30-57
	Guide: https://docs.bridgecrew.io/docs/networking_1-port-security

Terragrunt creates environment variables TF_VAR_ for each input.  Example from my `env` hook:

```
TF_VAR_cidr=0.0.0.0/0
TF_VAR_port=22
``` 

It doesn't appear these are being read in (I tested outside of terragrunt as well) although it looks like they should be.

**Comment by mf-anson** [comment]
@jonjozwiak, thanks for the quick example, I think `checkov` is not working well when using terraform registry module, like below: https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest
```
input = {
ingress_with_cidr_blocks = [
    {
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      description = "ssh temaplate"
      cidr_blocks = "0.0.0.0/0"
    }
  ]

  egress_with_cidr_blocks = [
    {
      from_port   = 0
      to_port     = 0
      protocol    = "-1"
      description = "egress all"
      cidr_blocks = "0.0.0.0/0"
    },
  ]
}
```
it seems not able to parse through list(map) to check for security check.
I used a workaround:
- output plan file
- convert to json
- checkov on the json output

**Comment by sbkg0002** [comment]
Did anyone find a trick on how to use checkov and terragrunt?

**Comment by ChaseFreeman17** [comment]
> Hi @matthieu-audin
> 
> You can use `terragrunt plan` output in json with checkov.
> 
> ```
> terragrunt init
> terragrunt plan -out tf.plan
> terragrunt show -json tf.plan  > tf.json 
> checkov -f tf.json
> ```

This works however if you want to skip a block the comments are not in the final JSON. For example:
```
resource "aws_iam_role_policy_attachment" "task_admin" {
  #checkov:skip=CKV_AWS_274:Comment Here
  role       = module.ecs_service_task.task_role_name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}
```

Has anyone found a way to suppress rules for specific blocks while using this method?

**Comment by ImagineBrkr** [comment]
You can export your plan to the current directory even while using run --all (newest version, don't know if it works on previous versions).

I use this as a workaround in my CI:
```
terragrunt plan --all -out $PWD/plan.tfplan
terragrunt show --all -json $PWD/plan.tfplan > $PWD/plan.json
checkov -f plan.json
```
