### ISSUE TITLE
Add new check: Documentdb encryption

### ISSUE THREAD

**Issue by schosterbarak** [bridgecrewio/checkov#129]
Encryption of data at rest
see: https://www.terraform.io/docs/providers/aws/r/docdb_cluster.html

**Comment by jonjozwiak** [comment]
Encryption in transit is enabled by default for new clusters unless you explicitly create a parameter group to disable it.  

https://www.terraform.io/docs/providers/aws/r/docdb_cluster_parameter_group.html#parameter
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbclusterparametergroup.html

**Comment by jonjozwiak** [comment]
Don't forget CloudFormation too! 
StorageEncrypted: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html
