### ISSUE TITLE
Pre-commit hook always shows "passed" from 2.0.49 onwards

### ISSUE THREAD

**Issue by lmpardey** [bridgecrewio/checkov#1296]
**Describe the bug**
Since version 2.0.49, when checkov runs via `pre-commit`, the result of the hook is always "Passed" even when the scanned code fails checks. This does not happen for versions 2.0.48 and older.

**To Reproduce**

Install checkov as a git commit hook with the pre-commit framework:
1. Get a repository with IaC configuration
2. Install pre-commit in your python virtual environment
3. Create a hook for checkov in `.pre-commit-config.yaml` as per the documentation, using version `2.0.49` as the ref:
```
repos:
- repo: https://github.com/bridgecrewio/checkov.git
  rev: '2.0.49'
  hooks:
  - id: checkov
```
4. Create a Terraform file with a resource that will fail checks, e.g. `s3.tf`:
```
resource "aws_s3_bucket" "bad" {
  name = "my-bad-bucket"
}
```
5. Run checkov via pre-commit: `pre-commit run checkov --verbose --all-files`
6. Note that the status of the operation is "Passed"
```
$ pre-commit run checkov --all-files --verbose
Checkov..................................................................Passed
- hook id: checkov
- duration: 2.25s

_               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.49
Update available 2.0.49 -> 2.0.196
Run pip3 install -U checkov to update


terraform scan results:

Passed checks: 5, Failed checks: 6, Skipped checks: 0

Check: CKV_AWS_70: "Ensure S3 bucket does not allow an action with any Principal"
        PASSED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/bc_aws_s3_23

Check: CKV_AWS_143: "Ensure that S3 bucket has lock configuration enabled by default"
        PASSED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/ensure-that-s3-bucket-has-lock-configuration-enabled-by-default

Check: CKV_AWS_93: "Ensure S3 bucket policy does not lockout all but root user. (Prevent lockouts needing root account fixes)"
        PASSED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/bc_aws_iam_53

Check: CKV_AWS_20: "S3 Bucket has an ACL defined which allows public READ access."
        PASSED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/s3_1-acl-read-permissions-everyone

Check: CKV_AWS_57: "S3 Bucket has an ACL defined which allows public WRITE access."
        PASSED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/s3_2-acl-write-permissions-everyone

Check: CKV_AWS_18: "Ensure the S3 bucket has access logging enabled"
        FAILED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/s3_13-enable-logging

                1 | resource "aws_s3_bucket" "bad" {
                2 |   name = "my-bad-bucket"
                3 | }

Check: CKV_AWS_144: "Ensure that S3 bucket has cross-region replication enabled"
        FAILED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/ensure-that-s3-bucket-has-cross-region-replication-enabled

                1 | resource "aws_s3_bucket" "bad" {
                2 |   name = "my-bad-bucket"
                3 | }

Check: CKV_AWS_19: "Ensure all data stored in the S3 bucket is securely encrypted at rest"
        FAILED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/s3_14-data-encrypted-at-rest

                1 | resource "aws_s3_bucket" "bad" {
                2 |   name = "my-bad-bucket"
                3 | }

Check: CKV_AWS_145: "Ensure that S3 buckets are encrypted with KMS by default"
        FAILED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/ensure-that-s3-buckets-are-encrypted-with-kms-by-default

                1 | resource "aws_s3_bucket" "bad" {
                2 |   name = "my-bad-bucket"
                3 | }

Check: CKV_AWS_52: "Ensure S3 bucket has MFA delete enabled"
        FAILED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3

                1 | resource "aws_s3_bucket" "bad" {
                2 |   name = "my-bad-bucket"
                3 | }

Check: CKV_AWS_21: "Ensure all data stored in the S3 bucket have versioning enabled"
        FAILED for resource: aws_s3_bucket.bad
        File: /s3.tf:1-3
        Guide: https://docs.bridgecrew.io/docs/s3_16-enable-versioning

                1 | resource "aws_s3_bucket" "bad" {
                2 |   name = "my-bad-bucket"
                3 | }
```

**Expected behavior**
The result of the pre-commit operation should show "Failed" if any checks run by checkov appear to fail. 

**Screenshots**
No screenshots to upload at this time.

**Desktop (please complete the following information):**
 - OS: Windows
 - Checkov Version: 2.0.49 onwards

**Additional context**
I spot-checked a the versions below, up to the latest (2.0.196) and the problem persisted in each of them:
- 2.0.196
- 2.0.153
- 2.0.100
- 2.0.50
- 2.0.49

The issue does not reproduce on version 2.0.48 or earlier.

**Comment by gruebel** [comment]
I tried on Linux and it works as intended, could be a Windows issue, hard to say.
Could you try to change the pre-commit config to
```yaml
repos:
  - repo: https://github.com/bridgecrewio/checkov
    rev: 2.0.211
    hooks:
      - id: checkov
        entry: checkov -d .
```
that's basically the the same entry point as in `checkov` configured.

**Comment by lmpardey** [comment]
@gruebel thanks for looking into this! Changing the entry-point didn't help, it still reports passed when it should fail. The same issue happens in PowerShell, CMD and git-bash (Windows 10). Please see the screenshot below for reference (redacted usernames/machine info).

If it helps, if I run `checkov`, either the binary or invoked via python, on the same set of files does returns an exit code of `1`. This is the same as in version 2.0.48.

Based on this issue appearing since 2.0.49, which merged https://github.com/bridgecrewio/checkov/pull/1082 , I wonder if replacing `exit()` with `return`, in combination with running on Windows, is causing sending the wrong exit codes to pre-commit? Unfortunately debug information is limited on pre-commit so I cannot see exactly what the tool is receiving from checkov.


### Screenshots
![image](https://user-images.githubusercontent.com/29401786/122772101-53121f00-d2a7-11eb-8b4c-65d38ffd18e7.png)
