### ISSUE TITLE
Add new check: DocDB snapshot encryption

### ISSUE THREAD

**Issue by schosterbarak** [bridgecrewio/checkov#130]
Encryption of data at rest.
See: https://www.terraform.io/docs/providers/aws/r/docdb_cluster_snapshot.html

**Comment by DrFaust92** [comment]
DocDb Snapshot does have an argument to define encryption, this is done in the parent cluster resource.

**Comment by njgibbon** [comment]
Hey all. 

As @DrFaust has mentioned snapshot encryption for DocDB is controlled by enabling Encryption at Rest for DocDB.

And there is already a terraform check for this: https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/DocDBEncryption.py

I believe that all that is needed here it to implement the DocDBEncryption for cloud formation and then this issue could be closed.

> You encrypt data at rest in your Amazon DocumentDB cluster by specifying the storage encryption option when you create your cluster. Storage encryption is enabled cluster-wide and is applied to all instances, including the primary instance and any replicas. It is also applied to your cluster’s storage volume, data, indexes, logs, automated backups, and snapshots. [0]

[0] AWS DocDB Enc at rest doc: https://docs.aws.amazon.com/documentdb/latest/developerguide/encryption-at-rest.html
