### ISSUE TITLE
Is there any data being sent anywhere?

### ISSUE THREAD

**Issue by MarlonMrN** [bridgecrewio/checkov#1315]
Hi, I'm just opening this issue at first before going deeper in the code to check on that...

But I would like to know if is there any info being sent outside of the machine that's running checkov? If so, is there any way to run it "offline"?

Reading the docs, I saw that in the disclaimer (https://github.com/bridgecrewio/checkov#disclaimer) stating that there's no identifiable information being saved.
Also, that "checkov uses Bridgecrew's API to enrich the results with links to remediation guides. To skip this API call use the flag --no-guide"

So if I run with -no-guide, can I expect that the code won't make any internet calls when executing (at least none sending any kind of data) or is there something being sent?

Thanks for your assistance :))
Also, is checkov.io terribly slow only here?

**Comment by nimrodkor** [comment]
Hi @MarlonMrN !

Checkov uses the internet for 2 things:
1. Retrieving the guidelines, which can be turned off as you stated.
2. Integration with the Bridgecrew platform, which requires a Bridgecrew API key. The data that is passed in that case is related to the findings only.

Regarding checkov.io - we did improve it a little I hope. Let me know if it is still super slow!
