### ISSUE TITLE
Add --warn option similar to --check

### ISSUE THREAD

**Issue by jkesterson** [bridgecrewio/checkov#1326]
There are many great checks that come with Checkov that allow me to block deployments of insecure, noncompliant resources. The problem is, there are many cases where I want devs to be AWARE of a potential security misconfig without entirely blocking their deployment. For example, I wouldn't want to block a deployment of an ALB for not redirecting to HTTPS, but I would like them to KNOW about it.

A simple --warn flag similar to the --check flag would solve this issue. Provide a list of check IDs that you would like to warn on in the output without causing a failure. This would also be similar to the --soft-fail flag, but only for a subset of checks that are deemed non-essential, but desired. 

Alternatively, the soft-fail flag could be modified to take a list of checks to soft-fail on, with ALL being specified to mimic the option's current function.

**Comment by nimrodkor** [comment]
Hey @jkesterson !

We've recently merged #1327 , which adds the flags that can help you do that. try `--soft-fail-on` :)
