### ISSUE TITLE
Specify Output File

### ISSUE THREAD

**Issue by overallcoma** [bridgecrewio/checkov#1328]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to run checkov via a container and simply output json to a file for subsequent processing.

**Describe the solution you'd like**
A switch that specifies an output file.  Specifically I'm trying to make a scan output a json file and simply save the file.

**Describe alternatives you've considered**
I struggled with this for a while today trying different approaches to get a checkov container to generate output non-interactively.  The traditional "-o" switch used to specify file output only modifies output format with no option I've found to specify a way to save the output.  I even went as far as building my own image off the python3 base image, installing checkov, and writing a python wrapper with output redirection - no luck.

**Additional context**
I just want the content that gets printed to the screen to be able to be saved to a file easily via a switch.

**Comment by gruebel** [comment]
you can just redirect the output with `>`, like
```shell
checkov --quiet -o junitxml -d . > reports/checkov.xml
```

**Comment by overallcoma** [comment]
Checkov errors out if you start a docker container with ">" in the command.  It'll interpret ">" as part of the checkov command along with anything after and spit out the help.

Same if you try to pipe the output and use tee.

**Comment by gruebel** [comment]
that's strange, are you on Windows? I just ran following command on my Mac and there was no issue at all
```shell
docker run -t -v /foo/bar:/cfn bridgecrew/checkov --quiet -o junitxml -d /cfn > output.xml
```

**Comment by overallcoma** [comment]
![image](https://user-images.githubusercontent.com/30637170/123435970-c2cc2680-d593-11eb-9aa1-fcd4c2f79729.png)
This is the relevant section of the docker inspect
![image](https://user-images.githubusercontent.com/30637170/123436131-f1e29800-d593-11eb-8d03-c38b57269bbb.png)
This is what happens if you try to do it this way - the command becomes part of the parameters for checkov.

It could be remedied with a "specify output file" switch

**Comment by overallcoma** [comment]
Relevant section of the docker inspect:
![image](https://user-images.githubusercontent.com/30637170/123436607-69b0c280-d594-11eb-9cff-8adf47ec91f2.png)
Output from the container:
![image](https://user-images.githubusercontent.com/30637170/123436711-84833700-d594-11eb-8a9d-03dd3db1455f.png)

It is due to interpreting the inputs as parameters and checkov trying to analyze them.  I guess you could fix it if you launched it from an interactive bash shell, but that's not really an ideal way to integrate the tool programmatically into a larger workflow.

Again - I'm pretty sure if there was an "output to file" switch it'd make the whole thing flow smoothly.

**Comment by overallcoma** [comment]
If I change the entrypoint to /bin/sh and run "'checkov --quiet -o junitxml -d /scan/test-data > /scan/output/checkovscan.xml' - the container can't locate checkov to run it.

If I change the entrypoint to /bin/sh and run "/usr/local/bin/checkov --quiet -o junitxml -d /scan/test-data > /scan/output/checkovscan.xml' I get this:
![image](https://user-images.githubusercontent.com/30637170/123438914-d200a380-d596-11eb-992a-1e2f28d9d97b.png)

If I change the entrypoint to "/usr/local/bin/python" and the command to "'/usr/local/bin/checkov' '--quiet' '-o' 'junitxml' '-d' '/scan/test-data' '>' '/scan/output/checkovscan.xml'" I just get the help file again.

**Comment by gruebel** [comment]
we added a couple of months ago a flag to output the first selected output to a file
```shell
  --output-file-path OUTPUT_FILE_PATH
                        Name for output file. The first selected output via output flag will be saved to the file (default output is cli)
```
