### ISSUE TITLE
Latest tag 2.0.244 is not available on docker hub and image pull gets failed.

### ISSUE THREAD

**Issue by nisargtk** [bridgecrewio/checkov#1346]
**Describe the bug**
Latest tag bridgecrew/checkov:2.0.244 is not available on docker hub and image pull gets failed.

**To Reproduce**
1. Run command from cli :  docker pull bridgecrew/checkov:2.0.244
Getting image pull error
Error response from daemon: manifest for bridgecrew/checkov:2.0.244 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 3.19 seconds before retry.

**Expected behavior**
It should download the image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : linux ubuntu
 - Checkov Version [e.g. 22] : 2.0.244

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by nimrodkor** [comment]
Looking into it

**Comment by nimrodkor** [comment]
I think I might have found the issue, pushing https://github.com/bridgecrewio/checkov/commit/291e229f6e3ae2626ed15b741d0ecd1374e25e12

**Comment by nimrodkor** [comment]
latest tag, 2.0.246 was released. 👍 
Thanks!
