### ISSUE TITLE
Add new check: RDS - Check encryption at rest for database cluster

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#139]
Currently checkov looks to ensure aws_db_instance is encrypted.  However, there is not a check for aws_db_cluster.  Ensure the cluster is encrypted at rest.  Also, the CloudFormation check for aws_db_instance does not yet exist.  

storage_encrypted: https://www.terraform.io/docs/providers/aws/r/rds_cluster.html
StorageEncrypted: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html

**Comment by JamesWoolfenden** [comment]
aws_rds_cluster is RDS Aurora only. So not also,

**Comment by njgibbon** [comment]
@schosterbarak Hey, actually. This issue should stay open to cover the Terraform side. Above merge has implemented the Aurora enc at rest check for CF. 

Here we need to make sure RDS and Aurora have the same checks in Terraform.

**Comment by njgibbon** [comment]
This can be closed now. Aurora and RDS encryption checks are there for terraform and cloudformation.

**Comment by schosterbarak** [comment]
Thanks @njgibbon
