### ISSUE TITLE
Missing equivalent check as tfsec for sensitive data in terraform variable

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [bridgecrewio/checkov#1390]
**Is your feature request related to a problem? Please describe.**
tfsec has some general checks (https://tfsec.dev/docs/general/home/) for detecting passwords and other things in terraform variables. There does not appear to be an equivalent for checkov

**Describe the solution you'd like**
For now we run both checkov and tfsec side by side, which is wasteful

**Describe alternatives you've considered**
?

**Comment by JamesWoolfenden** [comment]
Have your tried the new secret scanner in checkov?

**Comment by nimrodkor** [comment]
Closed due to inactivity
