### ISSUE TITLE
failed test on resource "aws_volume_attachment"

### ISSUE THREAD

**Issue by dbbc96** [bridgecrewio/checkov#1402]
So i did a yaml file for checking all resources for missing tags that we are requiring.  Only so far tested on an AWS EC2 terraform deployment.  I noticed that its failing on aws_volume_attachment.  The test passed on the EBS volumes themselves so i know its picking up that but the attachment doesn't have any tagging capabilities in Terraform so it shouldn't be flagging that.  

Not sure if your code when using "all" for resources will do any resource or only resources that have tag capacity.

running 2.0.255 version.

**Comment by JamesWoolfenden** [comment]
Have you tried setting default tags via the provider instead?

**Comment by dbbc96** [comment]
even with doing default tags, checkov still reports as missing tags.  The tagging is correct in terraform deployment but just reporting missing in ebs attachments (which there isn't tagging possible for that resource).  One thing i don't know is if checkov "all" resources will flag every resource whether or not tagging is possible for that resource.

**Comment by JamesWoolfenden** [comment]
can you post a code sample and the error please

**Comment by dbbc96** [comment]
here is the error. this is using default tags and not tagging within resources. 

Check: CUSTOM_AWS_2: "Check that all resources are tagged with the key - agency"
        FAILED for resource: aws_volume_attachment.ec2_D
        File: /main.tf:93-97

                93 | resource "aws_volume_attachment" "ec2_D" {
                94 |   device_name = "xvdb"
                95 |   volume_id   = aws_ebs_volume.ec2_D.id
                96 |   instance_id = module.ec2.id[0]
                97 | }


Below is my custom scan:

metadata:
 name: "Check that all resources are tagged with the key - agency"
 id: "CUSTOM_AWS_2"
 guidelines: "Tags Governance - in case of the matched condition below -> add a tag of your agency"
 category: "general"
 severity: "critical"
scope:
  provider: "aws"
definition:
       cond_type: "attribute"
       resource_types: "all"
       attribute: "tags.agency"
       operator: "exists"

**Comment by JamesWoolfenden** [comment]
looks like all resources is just that, if you wait for https://github.com/bridgecrewio/checkov/pull/1336 you should have a check for provider default tags which i think is what you want?

**Comment by dbbc96** [comment]
so in our environment we might have cases where we are using default tags but others cases where we are just using modules and resource deployments.  in the case where we are not using provider default tags, would need to understand why checkov is flagging it as "missing tags" when ebs attachments don't offer tagging capabilities.  As in my original post, it picks up the tags for the ebs volumes and passes but fails on the "attachment" resource.

**Comment by nimrodkor** [comment]
He @dbbc96 !

First of all - @JamesWoolfenden is correct, if you check all resources, it will get flagged. I'd like to offer 2 options to fix this:
1. Leverage [yor](www.yor.io) to create tags throughout your terraform by default.
2. Exclude the resource_types that can't be tagged in your policy. This may be non-scalable, manual labor. Which brings me back to option number 1.
