### ISSUE TITLE
CKV2_AWS_5 should dettect when a SG is attached to an ELB

### ISSUE THREAD

**Issue by alexppg** [bridgecrewio/checkov#1409]
**Describe the bug**
This check is: `Ensure that Security Groups are attached to an other resource`. 

But when reading the [documentation](https://docs.bridgecrew.io/docs/ensure-that-security-groups-are-attached-to-ec2-instances-or-elastic-network-interfaces-enis), it says: `Security Groups are not attached to EC2 instances or ENIs`.

As you can read on `aws_lb` resource [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elb), it supports an optional parameter that's a list of SGs.

**Expected behavior**
This check should detect when a SG is used in an ELB, not only on EC2 or ENIs.

PD: Thanks for your work, checkov is awesome!

**Comment by schosterbarak** [comment]
hey @alexppg thank you for reporting this. would you be able to provide a terraform snippet demonstrating it?

**Comment by JamesWoolfenden** [comment]
This rule already does check against aws_llb and aws_elb
