### ISSUE TITLE
Add new check: Amazon WorkSpaces - Check encryption at rest 

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#141]
WorkSpaces should have both root and user volumes encrypted at rest. 

RootVolumeEncryptionEnabled / UserVolumeEncryptionEnabled: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspaces-workspace.html

This is not supported in Terraform as of yet, but coming with an aws_workspaces_workspace and root_volume_encryption_enabled/user_volume_encryption_enabled: 
https://github.com/terraform-providers/terraform-provider-aws/pull/11608
https://github.com/terraform-providers/terraform-provider-aws/issues/434

**Comment by Tensho** [comment]
Hi 🙂 JFYI, I'd be cautious about mandatory workspace volume encription because it blocks image creation and you can't disable encryption at the moment.
https://docs.aws.amazon.com/workspaces/latest/adminguide/encrypt-workspaces.html#encryption_limits

**Comment by jonjozwiak** [comment]
It's good to be aware of those limitations.  For the image creation use case, is this typically an administrator creating an image that is then deployed for many users?  Are there times when a users machine would be used to create an image?

**Comment by Tensho** [comment]
Yes, administrator.
Not necessary, user workspace could be used to bake an image. However, administrator usually works with test workspace to bake and distribute an image.
