### ISSUE TITLE
CKV_AWS_78 misreported

### ISSUE THREAD

**Issue by luchetto81** [bridgecrewio/checkov#1458]
**Describe the bug**
Checkov is returning as vulnerability CKV_AWS_78, but the solution breaks Terraform validation.

Accordigly to Checkov if `encryption_disabled = false` is not set in the main block it can be considered a vulnerability

```
resource "aws_codebuild_project" "project-with-cache" {
  name           = "test-project-cache"
  description    = "test_codebuild_project_cache"
  build_timeout  = "5"
  queued_timeout = "5"
+ encryption_disabled = false
} 
```
as described here: https://docs.bridgecrew.io/docs/bc_aws_general_30

Unfortunately in Terraform v1.0.3 `encryption_disabled` is not available in that location but only in blocks `artifacts`, `secondary_artifacts` and `logs_config: s3_logs` as you can see here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project

So if not set it gives vulnerability, if set terraform fails during the validation.

**To Reproduce**
1. Set in **aws_codebuild_project**  **encryption_disabled = false**
```
resource "aws_codebuild_project" "project-with-cache" {
  name           = "test-project-cache"
  description    = "test_codebuild_project_cache"
  build_timeout  = "5"
  queued_timeout = "5"
+ encryption_disabled = false
} 
```
2. Run `terraform validate`
3. See error

**Expected behavior**
No vulnerability or vulnerability if not set the attribute in all the 3 blocks

**Desktop (please complete the following information):**
 - terraform --version: Terraform v1.0.3 on linux_amd64
 - checkov --version: 2.0.326

**Comment by JamesWoolfenden** [comment]
The actual check looks at encryption inside of the artifacts block, the suggested fix is incorrect and ive updated the docs. There is also currently a bug where any value causes the check to fail, a fix for that is in the pipe, but since it has the default value you want, its best to remove this attribute.
