### ISSUE TITLE
Add new check: CloudFront Distribution should have WAF enabled 

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#146]
AWS WAF gives you control over how traffic reaches your applications by enabling you to create security rules that block common attack patterns, such as SQL injection or cross-site scripting, and rules that filter out specific traffic patterns you define. 

web_acl_id: https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html
WebAclId: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html

**Comment by njgibbon** [comment]
https://github.com/bridgecrewio/checkov/pull/736 

This should close this issue.
