### ISSUE TITLE
CKV_AWS_61: Consider adding Federated to Principal

### ISSUE THREAD

**Issue by marcmodin** [bridgecrewio/checkov#1464]
I have a module where **Iam_role** is adding trust by either` ['Principal']['AWS']` or `['Principal']['Federated']`, when `Federated` is set I also need to set `['AWS']` and point my account even though I don't want that.

**Describe the solution you'd like**
Is it possible to add condition for Federated and not only AWS ?

**Comment by schosterbarak** [comment]
makes since. @marcmodin we will accept a pull request on it

**Comment by marcmodin** [comment]
I don't know go!

You can close this unless you want it around for reference.

**Comment by JamesWoolfenden** [comment]
@marcmodin if you supply ans example trust policy that you wish to be valid?
