### ISSUE TITLE
Checkov scan of Terraform file and the corresponding plan file produces different results for module

### ISSUE THREAD

**Issue by rdenchev** [bridgecrewio/checkov#1469]
**Describe the bug**
Scanning a module itself produces the same correct results for the Terraform file and the corresponding plan file.
Scanning the same module via a module call produces different results. The scan result of the plan file is wrong.

**To Reproduce**
For a better understanding, I have put together a sample project under https://github.com/rdenchev/checkov-terraform-scan-vs-plan.git. For the sake of simplicity, the scanning is restricted to only one check. The module code is copied from the Bridgecrew documentation under https://docs.bridgecrew.io/docs/ensure-that-postgresql-server-enables-customer-managed-key-for-encryption.

1. Clone the test repo and navigate to the repo
      ``` bash
      git clone https://github.com/rdenchev/checkov-terraform-scan-vs-plan.git
      cd checkov-terraform-scan-vs-plan
      ```
2. Create Terraform plan for the module itself
      ``` bash
      $ terraform init && terraform plan -out tf.plan > /dev/null && terraform show -json tf.plan > tf.plan.json
      ```
3. Scanning the module itself passes:
      ``` bash
      $ checkov -f main.tf  -c CKV2_AZURE_17 --quiet
      
      Passed checks: 1, Failed checks: 0, Skipped checks: 0
      ```

      ``` bash
      $ checkov -f tf.plan.json -c CKV2_AZURE_17 --quiet
      
      Passed checks: 1, Failed checks: 0, Skipped checks: 0
      ```
4. Create Terraform plan for the module call
      ``` bash
      $ cd example && terraform init && terraform plan -out tf.plan > /dev/null && terraform show -json tf.plan > tf.plan.json
      ```
5. Scanning the module call produces different results
      ``` bash
      $ checkov -d . -c CKV2_AZURE_17 --quiet
      
      terraform scan results:
      
      Passed checks: 1, Failed checks: 0, Skipped checks: 0
      
      terraform_plan scan results:
      
      Passed checks: 0, Failed checks: 1, Skipped checks: 0
      
      Check: CKV2_AZURE_17: "Ensure that PostgreSQL server enables customer-managed key for encryption"
              FAILED for resource: azurerm_postgresql_server_key.ok
              File: /tf.plan.json:0-0
              Guide: https://docs.bridgecrew.io/docs/ensure-that-postgresql-server-enables-customer-managed-key-for-encryption
      ```

**Expected behavior**
Checkov scan of Terraform files and the corresponding plan file produces the same conistent results.

**Desktop (please complete the following information):**
 - OS: WSL2
 - Checkov Version: 2.0.330

**Additional context**
If the module itself is scanned, the connections from _azurerm_postgresql_server_key_ to the resources _azurerm_key_vault_key_ and _azurerm_postgresql_server_ are identified.

``` bash
$ checkov -f tf.plan.json -c CKV2_AZURE_17 -o json

...
"entity": {
              "azurerm_postgresql_server_key": {
                  "ok": {
                      "timeouts": [
                          null
                      ],
                      "start_line": [
                          0
                      ],
                      "end_line": [
                          0
                      ],
                      "key_vault_key_id": [
                          "azurerm_key_vault_key.ok"
                      ],
                      "server_id": [
                          "azurerm_postgresql_server.ok"
                      ]
                  }
              }
                    }
...
```

If the module call is scanned, the connections from _azurerm_postgresql_server_key_ to the resources _azurerm_key_vault_key_ and _azurerm_postgresql_server_ are missing in the check result.

``` bash 
checkov -f example/tf.plan.json -c CKV2_AZURE_17 -o json

...
"entity": {
              "azurerm_postgresql_server_key": {
                  "ok": {
                      "timeouts": [
                          null
                      ],
                      "start_line": [
                          0
                      ],
                      "end_line": [
                          0
                      ]
                  }
              }
...
```

**Comment by nimrodkor** [comment]
Hey @rdenchev !
I looked at the check - it includes a `connection` condition. Plan files do not have graph connections as they are, by design, resolved from a variable / value perspective. Any ideas how we can make connection queries for this usecase? I don't have any...
