### ISSUE TITLE
Add new check: ALB should have WAF enabled 

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#147]
https://www.terraform.io/docs/providers/aws/r/wafregional_web_acl_association.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-webaclassociation.html

Note checkov will need to be able to correlate an ALB resource to an association resource to ensure it exists

**Comment by JamesWoolfenden** [comment]
only if public facing surely?

**Comment by jonjozwiak** [comment]
Good call out.  Definitely valuable for public facing.  Internal the threat level is much lower.

**Comment by heggenu** [comment]
Added an improvement #1519 to support AWS WAFv2 to this check.
