### ISSUE TITLE
Allow multiple output formats

### ISSUE THREAD

**Issue by jkesterson** [bridgecrewio/checkov#1483]
When implementing checkov use-cases, I'd love to be able to see both the cli formatted output for human consumption, as well as json format for logging purposes without having to run two scans.

Multiple -o flag compatibility would resolve this as I could specify -o cli AND -o json and receive both formats output to stdout.

Alternatively, I could run two scans on the same plan/directory with json and cli outputs respectively, or build a json object from the out of -o cli or vice versa.

**Comment by deric4** [comment]
other tooling in this space supports this feature (i.e. inspec)
