### ISSUE TITLE
K8S Resource written in terraform format(.tf)

### ISSUE THREAD

**Issue by johnwongapi** [bridgecrewio/checkov#1487]
**Is your feature request related to a problem? Please describe.**
currently Checkov seems do not check K8S Resource written in terraform format(.tf), e.g.:
```
resource "kubernetes_secret" "example" {
  metadata {
    name = "basic-auth"
    namespace = "default"
  }

  data = {
    username = "admin"
    password = "P4ssw0rd"
  }

  type = "kubernetes.io/basic-auth"
}
```

The above sample violate CKV_K8S_21(The default namespace should not be used) but no fail cases shown.

**Describe the solution you'd like**
Should checkov be able to check k8s resource written in .tf files?

**Comment by nimrodkor** [comment]
Hey @johnwongapi !

You're right, we don't scan the `kubernetes` provider by default. Feel free to contribute new checks in a new dir here:
https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource

**Comment by nimrodkor** [comment]
Duplicates #762
