### ISSUE TITLE
Add new check: Athena Workgroup should have encryption enabled

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#149]
encryption_configuration / Encryption options: https://www.terraform.io/docs/providers/aws/r/athena_workgroup.html

ResultConfiguration - EncryptionConfiguration - EncryptionOptions: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-athena-workgroup-resultconfiguration.html

**Comment by schosterbarak** [comment]
solved thanks to @njgibbon at https://github.com/bridgecrewio/checkov/pull/751/files
