### ISSUE TITLE
Add option to output checks skipped from baseline

### ISSUE THREAD

**Issue by bobziuchkovski** [bridgecrewio/checkov#1502]
**Is your feature request related to a problem? Please describe.**
Yes.  We've inherited a terraform repo with a lot of legacy problems.  We've introduced checkov to ensure new config going 
forward meets our standards.  We've also generated baseline files for all of the existing legacy terraform config, so that we only fail checks for new problems.  However, we'd like to keep visibility on all of the baseline/legacy config that we're skipping.  In particular, with junitxml output, we'd like to see the checks that are being skipped due to the baseline.  So we'd effectively be treating all of the legacy config as skipped tests with visibility on those as we update/fix them.

**Describe the solution you'd like**
Add the ability to explicitly output baseline-skipped checks as baseline-skipped.  For junitxml output formatting, render these as skipped tests.

**Describe alternatives you've considered**
We've considered running checkov twice.  Once with the `--baseline` flag and once without, and then comparing the output junitxml files.  Failures unique to the run without the `--baseline` flag would basically be those skipped checks, so we could post-process the result XML and display those as skipped tests.  However, this is pretty ugly.

**Comment by nimrodkor** [comment]
Sounds very interesting. We're open for contributions here, should be implemented somewhere near this:
https://github.com/bridgecrewio/checkov/blob/ca2673633080910d69ae5a6c8133eefdaeb36787/checkov/common/output/baseline.py#L13

**Comment by oliver-pham** [comment]
I'm interested in giving this a try. Has anyone worked on this issue yet?

**Comment by bobziuchkovski** [comment]
Our team at my company had intended to, but haven't been able to prioritize it yet.  Would still love to see this, though.

**Comment by chtnnh** [comment]
@nimrodkor I could give this a shot, if @oliver-pham isn't already working on this

**Comment by oliver-pham** [comment]
@chtnnh you can go ahead 🚀
