### ISSUE TITLE
Skip checks now throws exception

### ISSUE THREAD

**Issue by yvonnerogell** [bridgecrewio/checkov#1512]
This same command worked fine the other day. 

Today:
![image](https://user-images.githubusercontent.com/8989751/129779993-a8b54cdd-7db3-45c8-86d3-c64dcce79889.png)

4 days ago:
![image](https://user-images.githubusercontent.com/8989751/129779943-3ce9c5b9-f132-4c29-a640-0e168fadbc83.png)

Docker image context (pipeline file):
![image](https://user-images.githubusercontent.com/8989751/129780436-89f618e6-7f41-439b-ae19-92c4da1a8cca.png)

Looks like this [commit](https://github.com/bridgecrewio/checkov/pull/1498) changed how the DependsOn property is processed, which is something that we're using in our cloud formation template and which seems to be the reason for the key error. 

For reference, this is how we're using DependsOn (shows how it's looking for the key that can't be found):
![image](https://user-images.githubusercontent.com/8989751/129781604-4ca99554-b41d-490e-a86d-a37edab5ff40.png)

Is there something in the syntax of the command that needs to change to get this back to working again?

**Comment by Saarett** [comment]
Hi @yvonnerogell, and thanks for the input!

It seems like this issue was fixed in [this](https://github.com/bridgecrewio/checkov/pull/1517) PR.
Please update checkov to the latest version, try again, and let us know if the issue persists.

**Comment by yvonnerogell** [comment]
Great, thank you!
