### ISSUE TITLE
terraform merge and variables that cant be resolved

### ISSUE THREAD

**Issue by coffeecoco** [bridgecrewio/checkov#1515]
I have a check that looks for mandatory tags 

there seems to be a scenario when tags and terraform merge is used, and when checkov is unable to evaluate the variable
resource "aws_iam_policy" "lambda_ssm_policy" {
  name        = "${local.full_name}-policy"
  description = "IAM policy for reading from SSM parameter store"
  policy      = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ssm:GetParameter"
      ],
      "Resource": "arn:aws:ssm:*:*:parameter/${local.full_name}/*",
      "Effect": "Allow"
    }
  ]
}
EOF
 tags = merge(
    var.tags,
    {
      Name = "${local.full_name}-policy"
    },
  )

}

locals {
  full_name             = "${var.instance}-${var.app_name}"
}

variable "instance" {
  description = "Name of the application instance being deployed"
  type        = string
  default = ""
}

variable "app_name" {
  description = "Name of the application itself"
  type        = string
  default = ""
}

when i debug the check i created the conf shows this

{'description': ['SecurityGroupfor-Lambda'], 'lifecycle': [{'create_before_destroy': [True]}], 'name': ['xxx-sg'], 'tags': ["merge({'Application':'test','Client':'test','DataClassification':'test','Environment':'test','Name':'test','Owner':'test','Product':'test','Schedule':'test','Service':'test','TaggingStandardVersion':'test','Team':'test'},{'Name':xxx-sg},)"], 'vpc_id': ['data.aws_vpc.selected.id'], 'entity_type': 'aws_security_group'}

the problem is it in the tags section
tags = ["merge({'Application':'test','Client':'test','DataClassification':'test','Environment':'test','Name':'test','Owner':'test','Product':'test','Schedule':'test','Service':'test','TaggingStandardVersion':'test','Team':'test'},{'Name':xxx-sg},)"]

checkov cant resolve one of the variables so it wont render everything
you can see that the last part has broken the structure because xxx-sg has no quotes around it 

what should i do with this?

**Comment by meizenga** [comment]
Same issue here. @coffeecoco I see you closed this issue. Did you find a solution?
