### ISSUE TITLE
variables with single quote checks dont run

### ISSUE THREAD

**Issue by coffeecoco** [bridgecrewio/checkov#1516]
variable "tags" {
  type        = map(string)
  description = "Shared/default tags to apply to **ALL** taggable resources"
  default     = {
    "Name" = "test"
    "Product"                = 'test'
    "Application"            = "test"
    "Service"                = "test"
    "Environment"            = "test"
    "Owner"                  = "test"
    "Client"                 = "test"
    "Team" = "test"
    "DataClassification"     = "test"
    "Schedule"               = "test"
    "TaggingStandardVersion" = "test"
  }
}

If someone accidently makes a variable with a single quote, i found that checkov wont run checks
is there a way to make sure it still resolves the value? i am aware that its supposed to be double quotes, but what happens if someone accidently uses single quote ? so far it seems like a sneaky way to mypass a check

**Comment by nimrodkor** [comment]
Hey @coffeecoco !

 I do believe you can actually not use quotes at all, i.e.
```terraform
variable "tags" {
  type = map(string)
  default = {
    Name = "test"
    Product = "test"
  }
}
```

Which checks are you planning to implement?
And does single-quote tags work as expected when deployed?

**Comment by coffeecoco** [comment]
mandatory tagging,  of all terraform resources, i scraped up all the terraform resources from the aws provider.
