### ISSUE TITLE
Add new check: Enforce IMDSv2 in EC2 instance and Launch Configuration

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#152]
Blog Post Here: https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html
	- Doesn’t appear possible for individual EC2 instance… 

Terraform: It does not appear configurable, but suggest further research.  
https://www.terraform.io/docs/providers/aws/r/launch_template.html
https://www.terraform.io/docs/providers/aws/r/instance.html

**Comment by KevinHock** [comment]
This would be a great feature to have!

For Terraform, I think we would do
```python
if (
	metadata_options["http_tokens"] == "required"
	or
	metadata_options["http_endpoint"] == "disabled"
):
    # return and don't alert...
# alert 
```
from https://www.terraform.io/docs/providers/aws/r/instance.html#metadata-options

**Comment by KevinHock** [comment]
This is kinda done as far as Terraform goes, re: my commit above ref'ing this issue

What should we do for cloudformation?

**Comment by rollwagen** [comment]
FYI - as far Cloudformation goes, it seems this is still not possible on an EC2 instance level; still marked as 'open' on the roadmap. For details see <https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/655>

**Comment by nimrodkor** [comment]
I believe this has been implemented for [cloudformation](https://github.com/bridgecrewio/checkov/blob/master/checkov/cloudformation/checks/resource/aws/IMDSv1Disabled.py) and [terraform](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/IMDSv1Disabled.py). If someone disagrees - please reopen!

**Comment by rollwagen** [comment]
@nimrodkor - thanks for the update and looking into this. 
In cloudformation the checkov check is for a (EC2-) LaunchConfiguration, this is at the moment still the workaround for setting IMDSv2; still can't do directly on and EC2 resource type (issue in cloudformation repo on this is still open, see [link](aws-cloudformation/cloudformation-coverage-roadmap#655). So technically not fully closed as title says "Enforce IMDSv2 in EC2 instance", however, practically, at the moment, I believe there's not much more that can be done (for cloudformation).
