### ISSUE TITLE
Thread Pools

### ISSUE THREAD

**Issue by Zordrak** [bridgecrewio/checkov#1531]
**Is your feature request related to a problem? Please describe.**

Checkov v2 does not successfully execute on our largest terraform root module. It is highly complex with many provider configurations and countable modules across multiple provider regions.

It appears that Checkov is entirely single-threaded, and I wonder if there is space in the codebase for some thread pools to parallelise the execution of some of heavier moving parts so that it might have a chance of succeeding.

**Describe the solution you'd like**
All reasonably parallelisable activities to make use of the multiprocessing library to execute in parallel threads.

**Describe alternatives you've considered**
¯\_(ツ)_/¯

**Comment by schosterbarak** [comment]
Interesting. I love the suggestion. What should be our benchmark for performance or a test terraform repo we can try?

**Comment by schosterbarak** [comment]
If you’ll try to scan the root of: https://github.com/cloudposse/terraform-aws-components
with the command `checkov -d`you’ll see results in 34 seconds
if you use the command
`IGNORE_HIDDEN_DIRECTORY_ENV=false checkov -d . --quiet --compact --download-external-modules True --external-modules-download-path .external_modules`
you’ll see results in 26 minutes 

I saw that most of the time checkov’s is halted on polling the files from git which makes sense.
2 reactors we need to do to improve runtime on modules:

1. If module is being used multiple times - We are downloading the same module multiple times, 1 per caller. We should put them in a common directory so we won’t download the same module several times.
2. We can parallelize the download of modules but the code there is stateful so not a 1 hours refactor.

**Comment by gruebel** [comment]
@schosterbarak from my point of view the logic behind downloading external modules need to be refactored in general. I started in the past #1287 and made some good progress, but hit a road block on how external modules are looked up by graph checks. I think it would be great, if I talk with @rotemavni and @nimrodkor on a good way to implement it there and then both of your points should be also incorporated.

**Comment by nimrodkor** [comment]
#1919 Should improve the performance of this issue greatly. From my tests - 37 minutes turned into ~10.
Leaving this issue open as parallelizing modules is still an open issue!

**Comment by nimrodkor** [comment]
Hello again!

#1922 reworks the module downloading to further imporve the performance. From my tests, what was ~10 minutes is now ~6 minutes. 🎊
