### ISSUE TITLE
Checkov no longer analyses local modules on windows

### ISSUE THREAD

**Issue by JamesWoolfenden** [bridgecrewio/checkov#1542]
Clone https://github.com/JamesWoolfenden/terraform-aws-dynamodb

```
checkov -d . 
```

You see multiple check results.

run 
```
checkov -d .\example\examplea
```

Expected: 1st pass results +1 more. 
Actual: just the contents of examplea folder and not the local module referenced

This used to work, works as expect on wsl and mac/linux

v 2.0.367

**Comment by gruebel** [comment]
thanks to @njgibbon this should be fixed since version `2.0.490` 🏅
