### ISSUE TITLE
CKV2_AZURE_10 Error for Azure Linux Virtual Machines

### ISSUE THREAD

**Issue by rajuvadarevu** [bridgecrewio/checkov#1549]
Creating Azure Linux Virtual Machine using Terraform.
Passed main.tf file to checkov and then it gives:
**CKV2_AZURE_10: "Ensure that Microsoft Antimalware is configured to automatically updates for Virtual Machines"**

But when I checked Azure Documentation here: **https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/iaas-antimalware-windows**
It says, "The Microsoft Antimalware solution is supported on Windows Server 2008 R2, Windows Server 2012, and Windows Server 2012 R2 operating system families. It is not supported on the Windows Server 2008 operating system, and **also is not supported in Linux.**"

Is Operating System check not placed in checkov for this CKV2_AZURE_10 error ?

**Comment by kyteinsky** [comment]
Hey I would like to work on this issue.
I found this file (terraform/checks/graph_checks/azure/AzureAntimalwareIsConfiguredWithAutoUpdatesForVMs.yaml) with the information mentioned in the issue description, am I looking at the right place?

Secondly, I need to include a condition to exclude Linux, right?

Thanks.

**Comment by nimrodkor** [comment]
Hi @kyteinsky , you are spot on. We would appreciate a contribution here!

**Comment by kyteinsky** [comment]
Hey @nimrodkor,

I am very sorry. I am completely lost where I found this issue and how to correct it. Unfortunately, even looking at the docs and the comments does not bring things back.

I hope you understand.

Cheers.

**Comment by julienLemarie** [comment]
Hi, 
CKV2_AZURE_10: "Ensure that Microsoft Antimalware is configured to automatically updates for Virtual Machines" still failed for Linux Virtual Machine.
Version 2.1.87
