### ISSUE TITLE
CKV_AWS_173 - slight bug

### ISSUE THREAD

**Issue by izunadropx** [bridgecrewio/checkov#1556]
**Describe the bug**
Checkov flags this failure if there is a KMS key set, but no env variables. It would make more sense to skip if there are no env vars, rather than failing if there is a key and no vars present. 

**To Reproduce**
Set kms_key_arn on a lambda_function with no environment vars declared for the function.

**Expected behavior**
I expect this check to be skipped if we have no variables set, even if a kms_key_id is present. 

**Desktop (please complete the following information):**
Gitlab runner (latest)

**Comment by gruebel** [comment]
@JamesWoolfenden I think you added this check and also the comment
```python
#no env vars so should be no key as that causes state mismatch
```

**Comment by JamesWoolfenden** [comment]
@gruebel I did, the check is correct, if you set the key and there are no env vars then you cause a state mismatch in your tf. If you read the documentation for aws_lambda_function   [aws_lambda_function](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function ) - "If this configuration is provided when environment variables are not in use, the AWS Lambda API does not save this configuration and Terraform will show a perpetual difference of adding the key."

**Comment by zoltan-kecskemethy-epam** [comment]
Uhm this has been caused headache to me. I believe this should be handled nicer than fail... also add hint into docs could help a lot.
