### ISSUE TITLE
Add new check: EC2 instance should use IAM role and not hardcoded credentials 

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#156]
Check for an IAM instance role/profile associated with an instance or launch config

iam_instance_profile: https://www.terraform.io/docs/providers/aws/r/instance.html
iam_instance_profile: https://www.terraform.io/docs/providers/aws/r/launch_configuration.html
IamInstanceProfile: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html
IamInstanceProfile: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html

**Comment by JamesWoolfenden** [comment]
i dont see how this can be possible, its valid to have an no instance profile. Id dont see how you could check for credential on an instance for tf.
