### ISSUE TITLE
Plan file scan slowness - json.loads custom decoder

### ISSUE THREAD

**Issue by larryboymi** [bridgecrewio/checkov#1585]
**Describe the bug**
With a larger plan JSON to check, seeing times of 20-30 minutes due to slowness using [custom decoder](https://github.com/bridgecrewio/checkov/blob/3081a8560f6369465314ee8f4ac8a8ec01649d68/checkov/terraform/context_parsers/tf_plan/tf_plan_json.py#L346) in the plan parsing section of the code.

When I remove the custom parser, and use either the regular `json` or `ujson` decoder without a custom class, the time to decode drops to almost no time.

Is there anything I can do to improve the performance? My plan example contains data I can't necessarily share here, but is about a 9-10MB JSON file

Note: I am still actively debugging which part of the custom decoder is the culprit, might just its use in general. Running a profile on it to see what might be the biggest issue.

Deleted cumulative times less than a second from call list (note for line numbers I have added a few debug logging statements so they probably don't line up with master currently).

```txt
   ncalls  tottime  percall  cumtime  percall   filename:lineno(function)
        1     0.000     0.000   1355.540   1355.540   <string>:1(<module>)
        1     0.000     0.000   1353.681   1353.681   __init__.py:15(parse)
       55     0.000     0.000   1353.469     24.609   __init__.py:299(loads)
12011/2041     0.101     0.000   1249.348     0.612   decoder.py:217(JSONArray)
       55     0.000     0.000   1353.469     24.609   decoder.py:332(decode)
       55     0.001     0.000   1353.468     24.609   decoder.py:343(raw_decode)
        1     0.001     0.001   1355.540   1355.540   main.py:52(run)
        1     0.000     0.000   1354.567   1354.567   plan_parser.py:119(parse_tf_plan)
        1     0.000     0.000   1354.567   1354.567   plan_runner.py:30(run)
        1     0.000     0.000   1355.131   1355.131   runner_registry.py:38(run)
  32731/1     1.329     0.000   1353.467   1353.467   tf_plan_json.py:149(cfn_json_object)
 193722/1     0.338     0.000   1353.467   1353.467   tf_plan_json.py:272(_scan_once)
 168372/8     0.299     0.000   1353.432    169.179   tf_plan_json.py:311(scan_once)
   213114     1.169     0.000   1347.026     0.006   tf_plan_json.py:321(get_beg_end_mark)
        1     0.100     0.100   1353.681   1353.681   tf_plan_json.py:333(load)
12011/2041     0.073     0.000   1265.956     0.620   tf_plan_json.py:369(JSONArray)
   297639     1.210     0.000     2.203     0.000   tf_plan_json.py:78(py_scanstring)
        1     0.000     0.000   1355.540   1355.540   {built-in method builtins.exec}
   429177   1344.920     0.003   1344.920     0.003   {method 'count' of 'str' objects}
```

**To Reproduce**
1. Run terraform plan, generate sizable plan file, convert to JSON.
2. Run checkov `terraform_plan` framework against JSON.
3. Wait

**Expected behavior**
Not lightning speed, but consistent scanning speed with smaller scans (which normally complete in 1-2 minutes).

**Comment by larryboymi** [comment]
I'm thinking it's how many times it is calling the `count` method for strings inside of the `get_beg_end_mark` function, looks borrowed from [cfn-lint](https://github.com/aws-cloudformation/cfn-lint/blob/main/src/cfnlint/decode/cfn_json.py)

**Comment by schosterbarak** [comment]
@larryboymi you are correct. the code is inspired by cfn-lint. we will accept a PR to fix performance

**Comment by larryboymi** [comment]
With the merging of PR #1596 this issue is good to close. Thanks!
