### ISSUE TITLE
Scan is slow since 2.0.357

### ISSUE THREAD

**Issue by TLaborde** [bridgecrewio/checkov#1589]
**Describe the bug**
Running the scan at the root of the repo is 6 times slower than running it for each subfolder. The issue appeared around version 2.0.357.

**To Reproduce**
1. downgrade to 2.0.356, time a scan of the repo
2. update to current version, time a scan of the repo
3. Compare

**Expected behavior**
The scan should be faster.

**Screenshots**
version -> time in sec to run scan
version 2.0.352 : 106.2096581
version 2.0.353 : 103.2969057
version 2.0.354 : 83.3623289
version 2.0.355 : 84.4924343
version 2.0.356 : 76.3720223
version 2.0.357 : 1086.3829189
version 2.0.358 : 778.0082139
version 2.0.359 : 1442.6692375
version 2.0.402 : 674.2031332

on 2.0.402, running on 22 modules one by one, time in seconds:
```
Count    : 22
Average  : 4.40065963181818
Sum      : 96.8145119
Maximum  : 5.3321704
Minimum  : 3.8702054
```
The sum of module time is lower than running checkov at the root

**Desktop (please complete the following information):**
 - OS: tested on windows 2019 and windows 10

**Comment by schosterbarak** [comment]
@TLaborde we had a contribution by @gruebel fixing a few performance issues that should be released in the next 30minutes. please reopen the ticket if it still an issue
