### ISSUE TITLE
feat(metadata): Allow custom policies to provide guideline urls

### ISSUE THREAD

**Issue by AjkayAlan** [bridgecrewio/checkov#1595]
## The Problem

Currently if I write a custom policy, and someone's resource violates that policy, they get the feedback in the console which states that they failed, but don't get a "guide" url. It would be hugely beneficial if my custom policies can incorporate guides to help engineers fix their resources.

## The Solution

This can be tackled in a number of ways. A few ideas:

- Allow "guide" in the metadata of a custom policy. If provided, it should be used in terminal output.
- Allow an "external-checks-guide" CLI arg that can be used with "external-checks-git"
- Create a repo template that people can use with "external-checks-git", perhaps with a "guidelines.json" file at the root, showing how you can map your ids to guidelines. Allow docs to be inlined in the git repo (markdown?) or allow external urls

**Comment by njgibbon** [comment]
This has also been requested as part of this issue: https://github.com/bridgecrewio/checkov/issues/1433 which will be closed because the bug part can be easily worked around.

**Comment by njgibbon** [comment]
Also requested here: https://github.com/bridgecrewio/checkov/issues/1115

**Comment by njgibbon** [comment]
The current implementation obtains the IDs dynamically with an API call which has all of the Check ID to Check Guideline mappings.

I think that adding it as an optional field to the base class would be a good thing. If it's set then the guideline is used. If it's not set then nothing will change and the guideline will be obtained dynamically if it exists.

I think that I will look in to implementing this.

**Comment by schosterbarak** [comment]
@njgibbon @AjkayAlan currently centralized guideline management is a platform feature at bridgecrew.cloud . you can start using it for free :)

**Comment by gruebel** [comment]
thanks to @vangundy-jason-pfg this is possible since version `2.0.484` 🚀
