### ISSUE TITLE
Bug: file preview not working with SARIF results uploaded from Checkov to Github

### ISSUE THREAD

**Issue by harringj** [bridgecrewio/checkov#1599]
Being able to view the code responsible for a security alert in Github's code scanning feature is crucial for developers. The file preview provides important contextual information for devs that helps them arrive at a fix without a lot of context switching.

Other tools, like CodeQL and tfsec, currently display file previews in code scanning without issue. The individual result view for Checkov, however, currently looks like this. 

![image](https://user-images.githubusercontent.com/21954788/132904065-3bce96cd-69a6-4db7-8f5a-012a74d18fb1.png)

Note the odd double slash in front of the filename. My hunch is that the double slash is preventing code scanning's rendering engine from displaying a file preview because, in this example, //backend.tf is not a valid filepath, as it needs to be per https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#physicallocation-object.

The bug seems to be affecting the individual result view specifically, since the list view does have a valid filepath, as can be seen here:

![image](https://user-images.githubusercontent.com/21954788/132904002-a8418ec0-36fd-4267-b8d8-f7b59dec0f95.png)

I don't know Checkov's codebase well enough to suggest a fix -- and it looks like Bridgecrew is committed to absolute URIs, which may make a fix trickier -- but `record.file_path` is somehow ending up with an additional prepended slash it shouldn't have:

https://github.com/bridgecrewio/checkov/blob/a217a1a04d92ed0ca6456ed5e3e13f4403f0eef1/checkov/common/output/report.py#L230

**Comment by nimrodkor** [comment]
Hey @harringj !

Yes, we prepend `/` to all the paths in the record I believe. If sarif needs it without the `/` - we're open to a contribution removing this `/` specifically for sarif. The snippet you put in the issue seems like the right place to me :)
