### ISSUE TITLE
Please add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by jeromepin** [bridgecrewio/checkov#16]
**Is your feature request related to a problem? Please describe.**
I would like to contribute, but between the lack code documentation and the lack of "how to start contributing", it's pretty hard to start. I know it's not the first thing you think about when you publish a project, but it would be very nice to see that kind of documentation 😃 

**Describe the solution you'd like**
It could mention :

* coding and commit style
* how to get started : pipenv, dependencies, etc...
* Should I commit pipfile and pipfile.lock
* etc...

Thanks in advance !

**Comment by tronxd** [comment]
Hey @jeromepin, thank you for your kind comments!

We are writing the contribution page, so you won't be disappointed in the near future :)
In the meanwhile, read the [Sample Policy](https://github.com/bridgecrewio/checkov/blob/master/docs/1.Introduction/Getting%20Started.md#sample-policy) section for getting started on how to write your own checks.

We will move this section into the contribution page when it's ready, so it will be more transparent to future contributors.

**Comment by jeromepin** [comment]
Hey @tronxd, nice to hear that ! 

I read the documentation but I was more interested in contributing to the core code (for now). I cloned and encountered some issues while running it, thus I was looking to try things.

Anyway, it will be a nice addition ! 😃

**Comment by nimrodkor** [comment]
Hey @jeromepin!

Please check out https://github.com/bridgecrewio/checkov/blob/master/docs/Contributing.md
If something is still missing for you, let us know!

**Comment by jeromepin** [comment]
Hi @tronxd @nimrodkor , sorry I was off. Thank you very much for adding that documentation. It's nice to have something to start with and I hope it will help future contributors !
