### ISSUE TITLE
Add new check: Firehose Delivery Stream S3 Destination Encrypted

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#160]
If using an S3 destination, encryption should be enabled 

s3_configuration - kms_key_arn: https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html
ExtendedS3DestinationConfiguration - EncryptionConfiguration: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisfirehose-deliverystream.html

**Comment by byarbrough** [comment]
It looks like the check could simply be if s3_configuration/extended_s3_configuration kms_key_arn is not null?
