### ISSUE TITLE
Secrets framework scan not working in 2.0.407

### ISSUE THREAD

**Issue by mtcolman** [bridgecrewio/checkov#1603]
**Describe the bug**
This is to duplicate #1536 which has been closed. I don't believe the issue has been resolved.

```
bash-5.1# pwd
/test
bash-5.1# checkov -d . --framework all

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.407

bash-5.1# ls -la
total 4
drwxrwxrwx    1 root     root          4096 Aug 25 16:35 .
drwxr-xr-x    1 root     root          4096 Sep 12 16:29 ..
-rwxrwxrwx    1 root     root            73 Aug 25 16:26 password.txt
-rwxrwxrwx    1 root     root            44 Aug 25 16:34 providers.tf
-rwxrwxrwx    1 root     root            30 Aug 25 16:35 secret_password.yaml

bash-5.1# cat providers.tf
access_key = "sfffglfgjldfjdlrt5454002lfofd"bash-5.1# cat password.txt
password: mypassword
b64password: bXlwYXNzd29yZAo=
mypassword=secretkey

bash-5.1# cat secret_password.yaml
pwd: correcthorsebatterystaple

bash-5.1# checkov -d ./ --framework secrets

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.407

bash-5.1# ls -la
total 4
drwxrwxrwx    1 root     root          4096 Aug 25 16:35 .
drwxr-xr-x    1 root     root          4096 Sep 12 16:29 ..
-rwxrwxrwx    1 root     root            73 Aug 25 16:26 password.txt
-rwxrwxrwx    1 root     root            44 Aug 25 16:34 providers.tf
-rwxrwxrwx    1 root     root            30 Aug 25 16:35 secret_password.yaml
```

**To Reproduce**
1. See above and details in #1536 

**Expected behavior**
I expect secrets to be detected.

**Desktop (please complete the following information):**
 - running the checkov container
 - Checkov Version: 2.0.204

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by gruebel** [comment]
Before I dig into this topic deeper, just a quick heads up. `checkov` doesn't check all files, only with specific file extensions. The `secrets` are only checked in following file extensions
- .tf
- .yml
- .yaml
- .json
- .template
so the secret in `password.txt` will not be flagged.

Your `access_key` is not a "real" AWS Access Key, therefore it is not flagged. A real one needs to validate against following regex `AKIA[0-9A-Z]{16}`

For `secret_password.yaml` I'm not sure, if there is a check, which is supposed to find this kind of password, maybe @tronxd can give some more details about it 🙂

**Comment by mtcolman** [comment]
@gruebel if you see this blog - the secret_password.yaml is exactly as per the example given: https://bridgecrew.io/blog/checkov-secrets-scanning-find-exposed-credentials-in-iac/.

**Comment by mtcolman** [comment]
I've amended the password files and given this another go at versions `2.0.407` and `2.0.413`. It is now finding the AWS secret, but still failing to find the "Base64 High Entropy String" (as per https://docs.bridgecrew.io/docs/git_secrets_6):
```
bash-5.1# pwd
/test

bash-5.1# ls -la
total 4
drwxrwxrwx    1 root     root          4096 Sep 14 09:32 .
drwxr-xr-x    1 root     root          4096 Sep 14 09:39 ..
-rwxrwxrwx    1 root     root            73 Aug 25 16:26 password.txt
-rwxrwxrwx    1 root     root            36 Sep 14 09:35 providers.tf
-rwxrwxrwx    1 root     root            76 Sep 14 09:39 secret_password.yaml
drwxrwxrwx    1 root     root          4096 Sep 14 09:32 terraform

bash-5.1# cat providers.tf
access_key = "AKIAAI0SF0DNN7EXAMPLE"

bash-5.1# cat secret_password.yaml
pwd: correcthorsebatterystaple
newpwd: Y29ycmVjdGhvcnNlYmF0dGVyeXN0YXBsZQ==

bash-5.1# checkov -d ./

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.413

secrets scan results:

Passed checks: 0, Failed checks: 2, Skipped checks: 0

Check: CKV_SECRET_2: "AWS Access Key"
        FAILED for resource: 2b4e50bcbde22261373a5e3cf6925a818837181a
        File: /providers.tf:1-2
        Guide: https://docs.bridgecrew.io/docs/git_secrets_2

                1 | access_key = "AKIAAI0SF0DNN7EXAMPLE"


Check: CKV_SECRET_2: "AWS Access Key"
        FAILED for resource: 2b4e50bcbde22261373a5e3cf6925a818837181a
        File: /terraform/aws/providers.tf:1-2
        Guide: https://docs.bridgecrew.io/docs/git_secrets_2

                1 | access_key = "AKIAAI0SF0DNN7EXAMPLE"
```

I can't see any difference between what I'm doing with `secret_password.yaml` and what was shown in the [blog](https://bridgecrew.io/blog/checkov-secrets-scanning-find-exposed-credentials-in-iac/).

**Comment by mtcolman** [comment]
@gruebel that probably explains it then! Please let me know how this progresses, thank you.

**Comment by nimrodkor** [comment]
@gruebel for IaC, we're looking for cross-matches of the entropies + the secret keyword matcher (i.e. `password`, `secret` etc). So I'm not too worried about the noise. I'm open to reducing the threshold there
