### ISSUE TITLE
Access to Terraform Plan `resource_changes`

### ISSUE THREAD

**Issue by roymartinezblanco** [bridgecrewio/checkov#1605]
**Is your feature request related to a problem? Please describe.**

In a `Terraform` plan, we have additional sections `resource_changes` & `output_changes` and  `plan_parser.py` only looks at `resources` meaning there is no way to access 
https://github.com/bridgecrewio/checkov/blob/eee62f8147bbe59e8e6d00d57c0ab01301287551/checkov/terraform/plan_parser.py#L126-L145

Example use case:
I'm looking to prevent or `warn` in the event of a `DB` user from been `renamed` without also removing `DB`
https://github.com/hashicorp/terraform-provider-google/issues/3820

**Describe the solution you'd like**

Preventing user error means viewing the type of changes to be done to a given resource.  Exposing the content of those fields as we have for `conf.keys()` will allow custom policies to be created:

**Additional context**

https://codifiedsecurity.slack.com/archives/C016DJYKALU/p1631280277015000

**Comment by schosterbarak** [comment]
@roymartinezblanco we have a community contribution on the way at: https://github.com/bridgecrewio/checkov/pull/1598 that might be a good way to solve your need too. wdyt?

**Comment by roymartinezblanco** [comment]
@schosterbarak I could create a custom check to look at terraform's JSON plan, this would allow me to create the rule I mentioned.

 Would like to see Chekov's terraform plan scan only new resources vs the whole infrastructure. IDK if this would need a new issue to be raised. To provide a bit more context, I'm adding checkov to an already existing infrasturcture, which a lot of checks that checkov run will fire but this could be a bit overwhelming to show a developer when they are adding just one resource. I would like to scan only the resource changes that are part of the terraform plan, to give whoever is making a change a scan result to their changes only.
