### ISSUE TITLE
Ability to disable the ASCII art logo to make app more automation friendly

### ISSUE THREAD

**Issue by gwvandesteeg** [bridgecrewio/checkov#1619]
**Is your feature request related to a problem? Please describe.**

When running checkov as part of automation and process tooling such as pre-commit, the many lines of ASCII art overwhelm the meaningful output of the checks themselves (what passed and what failed).

**Describe the solution you'd like**
Make the '--quiet' option (or another explicit option) disable the output of the logo, we already know what the name of the tool being executed is.  Anything to reduce the amount of superfluous lines of text in automation outputs will help the community track down actual issues.

**Describe alternatives you've considered**
Looked at various different output formats when run in CI/CD such as JUnit or the like, but none of those outputs are developer friendly when run using pre-commit or other CLI tools during development.

**Comment by nimrodkor** [comment]
Hey @gwvandesteeg !

I do believe the JSON output does not include the ASCII art. Will that work for you?

**Comment by gwvandesteeg** [comment]
> Hey @gwvandesteeg !
> 
> I do believe the JSON output does not include the ASCII art. Will that work for you?

Not really, JSON output is not human friendly without post-processing, and doesn't really suit for local development.  I think I've gotten around it with pre-commit if there are no issues, but would still like to be able to do this when there are issues so that they can be actioned.

**Comment by rafaeelaudibert** [comment]
Hey! Could I work on this? I think that a `--quiet` or a `--no-art` flag would be a great addition to the tool.
