### ISSUE TITLE
CKV2_AWS_19 does not check for aws_transfer_server

### ISSUE THREAD

**Issue by harishachappa** [bridgecrewio/checkov#1631]
**Describe the bug**
The CKV2_AWS_19 needs to be updated to check for aws_transfer_server.

Check: CKV2_AWS_19: "Ensure that all EIP addresses allocated to a VPC are attached to EC2 instances"
        FAILED for resource: aws_eip.eip
        File: /sftp.tf:147-163
        Guide: https://docs.bridgecrew.io/docs/ensure-that-all-eip-addresses-allocated-to-a-vpc-are-attached-to-ec2-instances

**To Reproduce**
Terraform code used

```
resource "aws_transfer_server" "transfer_server_vpc" {
  count                        = local.count
  identity_provider_type       = "SERVICE_MANAGED"
  url                          = var.serviceendpoint_url
  invocation_role              = var.invocation_role
  logging_role                 = var.logging_role
  endpoint_type                = "VPC"

  endpoint_details {
    address_allocation_ids     = aws_eip.eip.*.id[count.index]
    subnet_ids                 = var.public_subnetids
    vpc_id                     = var.vpc_id
  }
}

resource "aws_eip" "eip" {
  count = local.count
  vpc   = true
}
```

**Expected behavior**
Check CKV2_AWS_19 should not fail if the IP is assigned to aws_transfer_server

**Desktop (please complete the following information):**
 - OS: Windows
 - Checkov Version : 2.0.395

**Comment by schosterbarak** [comment]
thanks for reporting @harishachappa fixed by @mikeurbanski1
