### ISSUE TITLE
Add new check: DynamoDB Accelerator (DAX) encryption at rest enabled

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#164]
https://www.terraform.io/docs/providers/aws/r/dax_cluster.html#server_side_encryption
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dax-cluster.html#cfn-dax-cluster-ssespecification

**Comment by JamesWoolfenden** [comment]
my solution is for terraform. Shouldn't this be 2 separate issues?
