### ISSUE TITLE
Add new check: Ensure DocumentDB Encryption in transit is NOT disabled

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#165]
Encryption in transit is enabled by default for new clusters unless you explicitly create a parameter group to disable it.  

https://www.terraform.io/docs/providers/aws/r/docdb_cluster_parameter_group.html#parameter
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbclusterparametergroup.html

**Comment by njgibbon** [comment]
Ok cool, I will look at the CloudFormation implementation of this check as well :)
