### ISSUE TITLE
Since 2.0.438, Error parsing all files

### ISSUE THREAD

**Issue by ddanf** [bridgecrewio/checkov#1663]
**Describe the bug**
Since release 2.0.438, I have been seeing "Error parsing file /Users/s0046840/src/redi/redi-terraform/outputs.tf" repeated for every file in my tf project.  The errors are happening well before the 60s timeout that was implemented with 2.0.438. 

**To Reproduce**
                                ${pipenv} --python 3
                                ${pipenv} install
                                ${pipenv} install dataclasses
                                ${pipenv} install checkov
                                ${pipenv} run checkov -d .

**Expected behavior**
list of failed and then skipped checks

**Screenshots**
![image](https://user-images.githubusercontent.com/11450360/134998291-d34c6ab7-a336-4c8e-b668-ceeeaa4bbbb8.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.6 (Big Sur)
 - Checkov Version:  2.0.438+ (tested through 446)

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by ddanf** [comment]
This is the first file that fails to parse:

`output "logging_bucket_domain_name" {
  value = module.data.logging_bucket_domain_name
}

output "headers_lambda_qualified_arn" {
  value = module.web.headers_lambda_qualified_arn
}`

tflint reports no errors and tf plan and apply work with no issues.

**Comment by ddanf** [comment]
also, after the file parse errors, I am getting the false positives on CKV_SECRET_6 reported in issue #1660.

example:
> secrets scan results:

> 
> Passed checks: 0, Failed checks: 23, Skipped checks: 0
> 
> Check: CKV_SECRET_6: "Base64 High Entropy String"
>         FAILED for resource: 7af6c8ab2087e8cbf8400ebd0e529d6d3b173909
>         File: /modules/api/functions.tf:2398-2399
>         Guide: https://docs.bridgecrew.io/docs/git_secrets_6
> 
>                 2398 |       GLOBAL_SECRET_NAME = "redi-global-db-admin"

**Comment by makemesteaks** [comment]
bump

**Comment by willholley** [comment]
I'm seeing this as well - seems like a regression of https://github.com/bridgecrewio/checkov/issues/1361

**Comment by nimrodkor** [comment]
Has been resolved! 🎊

**Comment by jsimoni** [comment]
this seems to still be occurring in 2.0.639
