### ISSUE TITLE
Add new check: Glue Data Catalog Encryption at rest and connection parameter encryption

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#169]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-datacatalogencryptionsettings-datacatalogencryptionsettings.html

Note this is currently not covered in Terraform: https://github.com/terraform-providers/terraform-provider-aws/issues/9736

**Comment by DrFaust92** [comment]
when https://github.com/terraform-providers/terraform-provider-aws/pull/14916 is merged ill add the check 😉

**Comment by angatha** [comment]
@DrFaust92 https://github.com/terraform-providers/terraform-provider-aws/pull/14916 was merged a few days ago. 😃
