### ISSUE TITLE
JUnit Output for TestCase.Name Property Prefixes "None" to String

### ISSUE THREAD

**Issue by AErmie** [bridgecrewio/checkov#1695]
**Describe the bug**
After running Checkov (via the Docker container method), and retrieving output in JUnit format, when the results are populated in an Azure DevOps pipeline, it includes the word "None" as a prefix to the name/title.

NOTE: This line corresponds to the testcase.name property in the XML file

**To Reproduce**
```yaml
docker run --rm \
  --volume $(System.DefaultWorkingDirectory):/tf \
  bridgecrew/checkov \
  --directory /tf \
  --output junitxml > $(System.DefaultWorkingDirectory)/Checkov-Report.xml
```

**Expected behavior**
A user-friendly title. 

**Screenshots**
![Checkov-Bug](https://user-images.githubusercontent.com/10376796/135699772-f0c350db-5cac-4e93-856f-80a0bf57b170.png)

**Desktop (please complete the following information):**
 - Checkov Version: 2.0.461 

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by Pretty-19** [comment]
Hi, @AErmie  what should be mentioned as an alternative to  None ?

**Comment by AErmie** [comment]
Hey @Pretty-19, why is "None" included in the first place? What is it supposed to represent? 

If you look at how the results are published by [TFSec](https://github.com/aquasecurity/tfsec), they just show the rule/check name.

![TFSec-Results](https://user-images.githubusercontent.com/10376796/135727793-4597cd61-c9cc-4edf-ba8e-9de0b49906a1.png)
