### ISSUE TITLE
Add new check: Glue Enable Encryption of data at rest

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#170]
Both Glue Jobs and Glue Crawlers use a security configuration resource:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-securityconfiguration.html

https://www.terraform.io/docs/providers/aws/r/glue_job.html
https://www.terraform.io/docs/providers/aws/r/glue_crawler.html
https://www.terraform.io/docs/providers/aws/r/glue_security_configuration.html

**Comment by JamesWoolfenden** [comment]
check to ensure that glue job has security config set
check to ensure that glue crawler  has security config set
check to ensure that security config is all encrypted?
