### ISSUE TITLE
Severity levels for Checks

### ISSUE THREAD

**Issue by raghavtan** [bridgecrewio/checkov#1707]
**Description**
A bit quirky Question about checkov usage

If there is a way to add severity to certain checks
as in that high severities would return fail exit code … warnings would return a different exit code
and a mix of both would definitely be fail

**Comment by simonwendel** [comment]
The combination of severity levels and configurability which level to fail on would be a good tool for multi-team scenarios.

**Comment by gruebel** [comment]
I'm closing this in favour of #884.
