### ISSUE TITLE
Documentation issue in `GitLab CLI.md`

### ISSUE THREAD

**Issue by shreemaan-abhishek** [bridgecrewio/checkov#1733]
Expected:
> There is also a working example of using GitLab CI with Checkov [here](https://gitlab.com/guided-explorations/ci-cd-plugin-extensions/checkov-iac-sast).

Found: 
> The there is also a working example of using GitLab CI with Checkov [here](https://gitlab.com/guided-explorations/ci-cd-plugin-extensions/checkov-iac-sast).

See [this](https://github.com/bridgecrewio/checkov/blob/2c7f33ea108c21121d5d63d12a42e816eaee22f2/docs/4.Integrations/GitLab%20CLI.md#L106) line.

**Comment by gruebel** [comment]
fixed with #2088
