### ISSUE TITLE
Add new check: Secrets Manager secrets should have a rotation schedule set

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#175]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html

This will require checkov to correlate the secret with the schedule 

Terraform does it all in one resource: https://www.terraform.io/docs/providers/aws/r/secretsmanager_secret.html

**Comment by rileydak** [comment]
I have a working check for Terraform - but the Cloudformation version is dependent on https://github.com/bridgecrewio/checkov/issues/155 due to requiring correlation between of the secret and schedule... should I still PR or wait?

**Comment by schosterbarak** [comment]
@rileydak  sure. feel free!
