### ISSUE TITLE
[Alignment Bug] CTA button are aligned to the center instead of left.

### ISSUE THREAD

**Issue by rohiraanjali** [bridgecrewio/checkov#1755]
Call to Action buttons at bridgecrew.io are aligned to the center when the text around it is aligned to left. This looks like an alignment issue.
![Screenshot (24)](https://user-images.githubusercontent.com/74822422/137118113-a2964ea8-4b7a-4f32-b206-4444272f395e.png)

Can be fixed by:
CSS:
.cta-row--center {
text-align: left;
}

**Comment by rohiraanjali** [comment]
I can fix it by raising a pr. Please review.

**Comment by nimrodkor** [comment]
The bridgecrew.io domain is not managed via checkov
