### ISSUE TITLE
CKV_GCP_32 not working with terraform plan output

### ISSUE THREAD

**Issue by bgoareguer** [bridgecrewio/checkov#1764]
**Describe the bug**
When running Checkov on the `terraform plan` output, the `CKV_GCP_32` check does not work.

**To Reproduce**
1. Create a Terraform script that creates a `google_compute_engine` resource with `block-project-ssh-keys` set to `true`
2. Run cli command  'terraform init'
3. Run cli command  'terraform plan --out review.tfplan.binary'
4. Run cli command  'terraform show -json review.tfplan.binary > review.tfplan.json'
5. Run cli command  'checkov -f review.tfplan.json'
6. See error

**Expected behavior**
The CKV_GCP_32 check should be passed

**Screenshots**
![image](https://user-images.githubusercontent.com/43874676/137483848-14aa5679-5d42-405c-b77a-ba4546807014.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Checkov Version: 2.0.489

**Additional context**
The same Terraform script passes all checks when Checkov is run on the Terraform files instead of on the `terraform plan` output.

**Comment by jbrule** [comment]
I submitted a fix for this #6663 . The policy is coded to only accept a boolean value but Terraform accepts strings as valid input too.
