### ISSUE TITLE
Checkov parsing error on TF plan that uses encrypted_secret and pgp_key in a aws_iam_access_key resource

### ISSUE THREAD

**Issue by gustavoortega** [bridgecrewio/checkov#1768]
**Describe the bug**
Checkov parsing error on a terraform plan (for AWS resources) that use pgp_key and output with encrypted_secret

**To Reproduce**
I am using a TF resource of type "aws_iam_access_key", using the argument pgp_key, and an output with value = aws_iam_access_key.pipeline_user_key.encrypted_secret".
In the first run, when the AWS object doesn't exist, the terraform plan shows that it needs to create the resources.
So, I run checkov to this TF plan and everything works ok.

The command is: 
checkov -f /tmp/terraform_plan.json --repo-root-for-plan-enrichment /path/to/repo

Well, after that, when the infra was deployed to AWS, i modify any value, for example, i add an s3 bucket (the same of the checkov documentation that shows how exclude some check).
Then, i run terraform plan again, and, within this new plan.json, but this time, the following happens:

1- a lot of errors of type: "Check: CKV_SECRET_6: "Base64 High Entropy String"
2 - parsing error

Next step, when i skip this check, using the command:
checkov -f /tmp/terraform_plan.json --repo-root-for-plan-enrichment /path/to/repo --skip-framework secrets

       _               _              
   _| |   _  ___| | _____   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.491 

cloudformation scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file /tmp/terraform_plan.json

**Expected behavior**
Like all the other scans, the scan should ends with or without findings, but not with an error parsing000

**Screenshots**

**Desktop (please complete the following information):**
 - OS: This job runs on a gitlab pipeline. The container image is alpine:latest and the commands to install checkov:
 -  apk add py3-pip
 - pip install checkov
 - Checkov Version 2.0.491

**Additional context**
If I try the bucket code only on a different terraform file, and i create the plan, i can modify it every time without problems.

**Comment by bilalcaliskan** [comment]
i still have the same problem. is there any possible fix for that problem?
