### ISSUE TITLE
Parsing error scanning terraform file with "[*]"

### ISSUE THREAD

**Issue by benglerHIG** [bridgecrewio/checkov#1782]
**Describe the bug**
Receiving the error "Error parsing file c:\Users\BE53599\Documents\GitHub\cto_awsdocs\examples\hig_tfe_rhel7_ec2_server_fleet\dev\output.tf" when scanning a file of terraform code in Checkov that contains the string "[*]" (without quotes). We use the [*] token in Ansible for post-provisioning configuration management. Removing the [*] string allows the file to be scanned without error. Checkov is not scanning the entire directory where a file with the [*] string is contained. 

**To Reproduce**
1. Go to directory with file of terraform code containing [*] token
2. Run cli command  'checkov -f output.tf'
3. See error

**Expected behavior**
Checkov should scan files that contain [*] without generating a parsing error and generate accurate results. 

**Screenshots**
![image](https://user-images.githubusercontent.com/92762953/137820719-c2fdf62a-6baa-44be-92f2-14c445644796.png)
![image](https://user-images.githubusercontent.com/92762953/137820734-b9b970bd-5cda-4a53-9a89-45ef8cf56fe0.png)
![image](https://user-images.githubusercontent.com/92762953/137820755-8227b641-be72-4834-b899-98b9657b7a41.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Checkov Version 2.0.495

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by kartikp10** [comment]
Hey @benglerHIG, I tested this out and found that if I scan a directory with a file that has a splat expression `[*]`, the scanning works (you're probably not seeing results from the output.tf file in the last screenshot since there might not be any findings). See the example below:

```
❯ ccat test.tf
resource "aws_elb" "learn" {
  instances                   = aws_instance.ubuntu[*].id
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400
  tags                        = local.common_tags
}

resource "aws_elb" "learn2" {
  instances                   = flatten(aws_instance.ubuntu[*].id)
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400
  tags                        = local.common_tags
}
❯ checkov -d .

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.495

terraform scan results:

Passed checks: 4, Failed checks: 2, Skipped checks: 0

Check: CKV_AWS_127: "Ensure that Elastic Load Balancer(s) uses SSL certificates provided by AWS Certificate Manager"
	PASSED for resource: aws_elb.learn
	File: /test.tf:1-7
	Guide: https://docs.bridgecrew.io/docs/ensure-that-elastic-load-balancers-uses-ssl-certificates-provided-by-aws-certificate-manager

Check: CKV_AWS_138: "Ensure that ELB is cross-zone-load-balancing enabled"
	PASSED for resource: aws_elb.learn
	File: /test.tf:1-7
	Guide: https://docs.bridgecrew.io/docs/ensure-that-elb-is-cross-zone-load-balancing-enabled

Check: CKV_AWS_127: "Ensure that Elastic Load Balancer(s) uses SSL certificates provided by AWS Certificate Manager"
	PASSED for resource: aws_elb.learn2
	File: /test.tf:9-15
	Guide: https://docs.bridgecrew.io/docs/ensure-that-elastic-load-balancers-uses-ssl-certificates-provided-by-aws-certificate-manager

Check: CKV_AWS_138: "Ensure that ELB is cross-zone-load-balancing enabled"
	PASSED for resource: aws_elb.learn2
	File: /test.tf:9-15
	Guide: https://docs.bridgecrew.io/docs/ensure-that-elb-is-cross-zone-load-balancing-enabled

Check: CKV_AWS_92: "Ensure the ELB has access logging enabled"
	FAILED for resource: aws_elb.learn
	File: /test.tf:1-7
	Guide: https://docs.bridgecrew.io/docs/bc_aws_logging_23

		1 | resource "aws_elb" "learn" {
		2 |   instances                   = aws_instance.ubuntu[*].id
		3 |   idle_timeout                = 400
		4 |   connection_draining         = true
		5 |   connection_draining_timeout = 400
		6 |   tags                        = local.common_tags
		7 | }


Check: CKV_AWS_92: "Ensure the ELB has access logging enabled"
	FAILED for resource: aws_elb.learn2
	File: /test.tf:9-15
	Guide: https://docs.bridgecrew.io/docs/bc_aws_logging_23

		9  | resource "aws_elb" "learn2" {
		10 |   instances                   = flatten(aws_instance.ubuntu[*].id)
		11 |   idle_timeout                = 400
		12 |   connection_draining         = true
		13 |   connection_draining_timeout = 400
		14 |   tags                        = local.common_tags
		15 | }
```

That said if a file is scanned using the `-f` flag, scanning is failing. I think that's the problem here. I'll take a look at this further.

**Comment by kartikp10** [comment]
Sounds good. Closing per the latest comment.
