### ISSUE TITLE
--external-checks-git generates error, custom policies not checked

### ISSUE THREAD

**Issue by benglerHIG** [bridgecrewio/checkov#1785]
**Describe the bug**
The --external-checks-git argument generates the following error and custom policies are not checked: 
"Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\BE53599\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'c:\\Users\\BE53599\\Documents\\GitHub\\cto_cloud_refarch\\templates\\sns\\v1.0\\3df0b144_checks\\clone\\.git\\objects\\pack\\pack-b4638997d5a4a734af44106d70eb92321d408879.idx'"

**To Reproduce**
1. Go to directory with a file to scan
2. Run cli command  'checkov -f template.yml --external-checks-git https://github.test.com/test/cto_cloud_iac_scanning.git'
3. See error

**Expected behavior**
Using the --external-checks-git argument should scan the code without error and scan the code using the custom policies defined in the git repo

**Screenshots**
![image](https://user-images.githubusercontent.com/92762953/137822918-0e028224-b3e9-4b54-8179-380468df92b1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Checkov Version 2.0.495

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by nimrodkor** [comment]
Related to #1778
