### ISSUE TITLE
Is CKV_AWS_116 still relevant?

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#1795]
CKV_AWS_116 flags any Lambda without a dead-letter queue (DLQ) enabled. There's no explanation given for this recommendation:

https://docs.bridgecrew.io/docs/ensure-that-aws-lambda-function-is-configured-for-a-dead-letter-queue-dlq

AWS has retired it from their Foundational Security Best Practices controls on August 31, 2021:

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-lambda-4

**Comment by schosterbarak** [comment]
@gruebel can we verify if "on failure" is set in IaC too?  
also. can you suggest an edit at: https://docs.bridgecrew.io/docs/ensure-that-aws-lambda-function-is-configured-for-a-dead-letter-queue-dlq ? 

i think we should change the check name if "on failure" can be inspected. "Ensure lambda message delivery in DLQ or Failure behiavor" maybe?

**Comment by gruebel** [comment]
Yeah that's possible, but needs to be a YAML check, because we need to check if the Lambda function has a connection to `aws_lambda_function_event_invoke_config` https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function_event_invoke_config

**Comment by chtnnh** [comment]
Hey @schosterbarak, can I take this up?

**Comment by gruebel** [comment]
@chtnnh sure, go ahead. Do you know what you need to do?

**Comment by chtnnh** [comment]
@gruebel I went through the previous comments, but am not a 100% sure. Could you give me a quick rundown?
