### ISSUE TITLE
Support for kustomize based kubernetes yamls 

### ISSUE THREAD

**Issue by rams3sh** [bridgecrewio/checkov#1798]
**Is your feature request related to a problem? Please describe.**
Currently I use lot of my k8 deployments based on kustomize to manage the definitions easily. I wanted to have checkov configured as part of my pipeline for code linting. I tried the current version with my k8 yamls but it ended up showing as parse error.  

**Describe the solution you'd like**
It would be good if checkov could support kustomize based k8 yamls.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rams3sh** [comment]
Hey Team

Just wanted to bump up this issue.  This feature is a really helpful feature and was thinking if there is any release plans on this.

**Comment by exocode** [comment]
I tried this `--framework kustomize` option, but my output keeps empty:

Any ideas?


Thank you

```
❯ kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}

❯ checkov -f ./app/demo-app/overlays/demo --framework kustomize

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.791

More details: https://www.bridgecrew.cloud/projects?repository=myname_cli_repo/overlays&branch=bc-6be578d_master&runId=latest

```

**Comment by rams3sh** [comment]
Commenting just to keep the issue active.

**Comment by rams3sh** [comment]
Commenting just to keep the issue active.

**Comment by winston0410** [comment]
> I tried this `--framework kustomize` option, but my output keeps empty:
> 
> Any ideas?
> 
> Thank you
> 
> ```
> ❯ kustomize version
> {Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}
> 
> ❯ checkov -f ./app/demo-app/overlays/demo --framework kustomize
> 
>        _               _
>    ___| |__   ___  ___| | _______   __
>   / __| '_ \ / _ \/ __| |/ / _ \ \ / /
>  | (__| | | |  __/ (__|   < (_) \ V /
>   \___|_| |_|\___|\___|_|\_\___/ \_/
> 
> By bridgecrew.io | version: 2.0.791
> 
> More details: https://www.bridgecrew.cloud/projects?repository=myname_cli_repo/overlays&branch=bc-6be578d_master&runId=latest
> ```

I still have the same error, is kustomize going to be supported by checkov?

**Comment by DarshanAwachat** [comment]
I am also getting the output as empty. Team any updates on this.
