### ISSUE TITLE
Add new check: Ensure Cloudwatch logs group has retention days specified 

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#182]
You don’t want to keep logs forever.  If you do, please send me your money instead.  

retention_in_days: https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_group.html
RetentionInDays: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html

**Comment by jroden** [comment]
Just opened pr https://github.com/bridgecrewio/checkov/pull/343
thanks for the help! :)
