### ISSUE TITLE
Add new check: API Gateway should have WAF enabled

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#185]
This check will require checkov to correlate between resources

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-webaclassociation.html
https://www.terraform.io/docs/providers/aws/r/wafregional_web_acl_association.html

**Comment by jonjozwiak** [comment]
This check should be for public facing API gateway...

**Comment by DrFaust92** [comment]
This is tricky as it's not an APIGW resource and the waf_assocation resource can be used for ALB as well.
