### ISSUE TITLE
json/junitxml output adds branding

### ISSUE THREAD

**Issue by afterdesign** [bridgecrewio/checkov#187]
**Describe the bug**
When you select output to be shown as json or junitxml full "checkov" logo and version is printed also.

**To Reproduce**
Just run `checkov -d terraform -o json`

**Expected behavior**
Pure json/xml output without any additional things.

**Screenshots**
![Zrzut ekranu 2020-03-26 o 18 24 41](https://user-images.githubusercontent.com/672767/77676779-14e85b80-6f8f-11ea-9ba2-850038d45a12.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Checkov Version 1.0.215

**Comment by schosterbarak** [comment]
@afterdesign thanks for reporting this!
solved.

**Comment by afterdesign** [comment]
@schosterbarak ❤️
