### ISSUE TITLE
Error parsing multiline expression

### ISSUE THREAD

**Issue by rtollevik** [bridgecrewio/checkov#1871]
checkov (2.0.510 and 2.0.528) fails to parse terraform multiline expressions when a line starts with a new operator.  The following expressions all parses ok:
```
locals {
  ok1 = (false || true)
  ok2 = (false ||
         true)
  ok3 = (false ?
         true
         : false)
}
```
These expressions all fails to parse:
```
locals {
  fail1 = (false
           || true)
  faill2 = (false
            ? true
            : false)
}
```

**Comment by schosterbarak** [comment]
@arielkru would it be easy to add support of this?

**Comment by gruebel** [comment]
@schosterbarak it should be easy to add, but I don't know, if it will have some side effects.

**Comment by arielkru** [comment]
@schosterbarak It might be one of the cases where the lark parser type gets confused if we add the change but Im not sure, need to look into it
