### ISSUE TITLE
Parsing error with odd quotation mark

### ISSUE THREAD

**Issue by benglerHIG** [bridgecrewio/checkov#1873]
**Describe the bug**
When scanning a file with Checkov that has a non-standard quotation mark, a parsing error is generated and the file is not scanned properly. This problem is isolated to only files with the odd quotes. Removing the odd quotation mark allows checkov to scan the file normally.

Copy/paste of the code triggering the issue:
search_path: "$user”,public"

Screenshot of the code triggering the issue:
![image](https://user-images.githubusercontent.com/92762953/139503148-11b0ba7c-bf8d-40ee-8b02-201780ce324b.png)

Output/Error Message:
2021-10-29 13:08:53,431 [MainThread  ] [ERROR]  Cannot read file contents: .\template.yml - 'charmap' codec can't decode byte 0x9d in position 275: character maps to <undefined>
2021-10-29 13:08:53,435 [MainThread  ] [ERROR]  Cannot read file contents: .\template.yml
2021-10-29 13:08:53,436 [MainThread  ] [ERROR]  Cannot read file contents: .\template.yml

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.528

cloudformation scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file .\template.yml

**To Reproduce**
1. Go to 'directory with template.yml that has odd quotation mark'
2. Run cli command  'checkov -f .\template.yml'
3. See error

**Expected behavior**
Should be able to scan a file with the odd quotation mark without generating a parsing error and get accurate scan results for the file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Checkov Version v2.0.528

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by benglerHIG** [comment]
Log from scan
[checkov_parsing_error_log1.txt](https://github.com/bridgecrewio/checkov/files/7444978/checkov_parsing_error_log1.txt)

**Comment by gruebel** [comment]
thanks for reporting, is it a CloudFormation template?

**Comment by schosterbarak** [comment]
@benglerHIG  can you share the template file?

**Comment by benglerHIG** [comment]
@schosterbarak good news, latest version fixed this problem. I retested this morning before providing you the template file and found it's working well now. Thank you!
