### ISSUE TITLE
Parsing error scanning terraform plan output

### ISSUE THREAD

**Issue by benglerHIG** [bridgecrewio/checkov#1887]
**Describe the bug**
Receiving a parsing error when scanning terraform plan output. parsing error is in the cloudformation scan results. the file being scanned contains no cloudformation code. the terraform_plan scan results are reporting well

**To Reproduce**
1. Go to a folder which contains the output of a terraform plan piped into a tf.json file
2. Run cli command  checkov -f .\tf.json
3. See error in attached scanlog.txt

**Expected behavior**
Expect to be able to scan terraform plan output without encountering a parsing error

**Screenshots**
scanlog.txt
[scanlog.txt](https://github.com/bridgecrewio/checkov/files/7464351/scanlog.txt)

ts.json - terraform plan output being scanned
[tf.json.txt](https://github.com/bridgecrewio/checkov/files/7464354/tf.json.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Checkov Version 2.0.536

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by jkesterson** [comment]
I have had this issue quite a bit as well.
