### ISSUE TITLE
Implement user-defined loadable checks

### ISSUE THREAD

**Issue by jeromepin** [bridgecrewio/checkov#19]
**Is your feature request related to a problem? Please describe.**
Having integrated checks is cool. But it would even better if (as users) we could load our own checks. Like I have a policy saying that my RDS must be highly-available when deployed in our "production" environment. Such policy shouldn't belong to the core checks.

**Describe the solution you'd like**
Some parameter to provide a directory where `checkov` can find Python files to load.

I already implemented it in my own fork. Thus would you consider a PR ?

**Comment by schosterbarak** [comment]
@jeromepin Thanks a lot for the idea and contribution.
Feature merged at: https://github.com/bridgecrewio/checkov/pull/22
