### ISSUE TITLE
Check of Json file including null values results in parsing error

### ISSUE THREAD

**Issue by Pellovic26** [bridgecrewio/checkov#1903]
**Describe the bug**
Checking a Terraform Plan output saved as json results in parsing error if there is at least one parameter set to null, even if null is an accepted value. Checking directly the main.tf file is working without parsing error. 

**To Reproduce**
1. Create a Terraform configuration, in which the corresponding plan includes at least one null value. Simple example: Use "azurerm" provider and create a resource "azurerm_resource_group" with the required values for name and location. In the resulting final output the field for tag would be set to "null", which is correct.  
![TFCode](https://user-images.githubusercontent.com/93720518/140331877-56ec11e2-88b7-4990-b4a4-88829698ad19.png)

2. Run CLI command: terraform init
3. Run CLI command: terraform plan -out tf.plan
4. Run CLI command: terraform show -json tf.plan > tf.json (the attached file was pretty-printed to see better the corresponding row, but even with pretty-printing this issue comes up)
![TFPlan-json](https://user-images.githubusercontent.com/93720518/140331895-7b30c08a-60fa-4f95-9835-b880cf902aac.png)
5. LOG_LEVEL=DEBUG checkov -f tf.json
6. Parsing Error, with LOG_LEVEL=DEBUG it is visible that the correct null value is the problem.
![ParsingError](https://user-images.githubusercontent.com/93720518/140332728-24e8c03a-30a8-4753-812f-ae903cce0919.png)

**Expected behavior**
Null values are not resulting in general in parsing errors for json files. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Checkov Version 2.0.545
 - Python Version 3.8.10

**Additional Context**
I think from list of issues, the issues #1414 and #1887 are similar and could have the same root cause.

**Comment by antoinert** [comment]
I also ran into this and for documentation's sake I proceeded reproduce the original case in a notebook with latest Ubuntu.

[https://www.tinnable.com/tins/2250abc7-04b9-4ac3-8840-a2b705619122](https://www.tinnable.com/tins/2250abc7-04b9-4ac3-8840-a2b705619122?utm_source=github&utm_campaign=1ST2021)

**Comment by BrewToR** [comment]
I encounter the same issue, when do you plan a fix ?
