### ISSUE TITLE
Checkov unable to scan all ther serverless.yml in root directory

### ISSUE THREAD

**Issue by Prashanthkool7** [bridgecrewio/checkov#1904]
Hello Team,
Here is the my current checkov_scan.yml file
name: Run Checkov action serverless
        id: checkov1
        uses: bridgecrewio/checkov-action@master
        with:
          #skip_check: CKV_AWS_23 # optional: skip a specific check_id
          #quiet: true # optional: display only failed checks
          #log_level: DEBUG # optional: set log level. Default WARNING
          output_format: cli # optional: the output format, one of: cli, json, junitxml, github_failed_only
          framework: serverless
I have not mentioned directory path so that checkov scan both my terraform files and serverless.yml as well
but there are two files in the root directory serverless.yml and serverless-nonprod.yml
checkov is skipping the one of the file "serverless-nonprod.yml " if Irename the file from "serverless-nonprod.yml " to "serverless.yml" checkov is scanning.
is there way from github actions to pass a specific list of files to scan
I see there is an option checkov -f file name
but if i use github actions  "bridgecrewio/checkov-action@master" i don't have any documentation to pass a file
can anyone please let me know how accomplish this.

**Comment by schosterbarak** [comment]
checkov is looking for serverless files named serverless.yml and it is defined here:
https://github.com/bridgecrewio/checkov/blob/0f64314b7ae727606a376d81478ae8418d25512f/checkov/serverless/runner.py#L27
if you'd like to contribute a PR that extract those to an environment variable that can be overridden we will accept this contribution

**Comment by Prashanthkool7** [comment]
checkov/checkov/serverless/runner.py

 SLS_FILE_MASK = ["serverless.yml", "serverless.yaml", serverless-nonprod.yml]

**Comment by Prashanthkool7** [comment]
moving forward will he having bunch of serverless-xxxx.yml file in the same directory

can you please let me know how are we handling additional files for checkov to scan.

**Comment by schosterbarak** [comment]
The code change should enable SLS_FILE_MASK to read values from an environment variable CKV_SLS_FILE_MASK

A similar code exists for the env variable CKV_IGNORED_DIRECTORIES

**Comment by AbhijithGanesh** [comment]
@schosterbarak Can I please get assigned to this issue ?I am new to the Checkov project, I have experience with Python.
