### ISSUE TITLE
CKV2_AWS_13 wants a Backup Plan for Redshift - but AWS Backup Plan does not support Redshift

### ISSUE THREAD

**Issue by jmcvetta** [bridgecrewio/checkov#1917]
**Describe the bug**
CKV2_AWS_13 wants a Backup Plan for Redshift - but AWS Backup Plan does not support Redshift.  Instead, Redshift uses snapshots for backup.

**To Reproduce**
1. Setup code as described [in the docs](https://docs.bridgecrew.io/docs/ensure-that-redshift-clusters-has-backup-plan-of-aws-backup).
2. Run cli command  `terraform apply`.
3. AWS returns an error saying the Redshift ARN is not a supported resource.

**Expected behavior**
Instead, Checkov should ensure a Redshift cluster has snapshots configured.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Checkov Version 2.0.556

**Comment by gruebel** [comment]
You are correct 😄 if we wait long enough, then AWS will offer support for Redshift for sure 😄 
@schosterbarak any thoughts about it?

**Comment by JamesWoolfenden** [comment]
We are soo ahead of AWS
