### ISSUE TITLE
CKV_AZURE_53 is a duplicate of CKV_AZURE_90

### ISSUE THREAD

**Issue by anhdle14** [bridgecrewio/checkov#1925]
**Is your feature request related to a problem? Please describe.**
CKV_AZURE_53 is a duplicate of CKV_AZURE_90. We should use only one.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gruebel** [comment]
@schosterbarak looks like both do really the same, but `CKV_AZURE_53` looks better on how it is programmed 🙂
