### ISSUE TITLE
COMMENT_REGEX does not skip custom checks with non-numerical endings

### ISSUE THREAD

**Issue by jmeredith16** [bridgecrewio/checkov#1941]
**Describe the bug**
The COMMENT_REGEX for skipping checks does not account for custom checks with a non-numerical naming schema.

```
COMMENT_REGEX = re.compile(r'(checkov:skip=|bridgecrew:skip=) *([A-Z_\d]+)(:[^\n]+)?')
```

The above regex matches checks like what Checkov uses internally `CKV_AWS_20`, but does not match something like `ABC_AWS_MyCheckName`. Specifically, the `MyCheckName` section which is not captured by the `\d` in the regex.

I believe changing the regex to something like the following would allow for custom Check skips for those of us wanting a more descriptive naming schema:
```
(checkov:skip=|bridgecrew:skip=) *([A-Z_\S]+)(:)([^\n]+)?
```
(note the `\d` changing to `\S` and the addition of the `(:)` group)

**To Reproduce**
1. Create a check with a string instead of a number for the last part of the Check ID
2. Run Checkov against it with a skip in the terraform
```
$ checkov -f /path/to/custom/AWSKeyPairDisallowed/AWSKeyPairDisallowed.tf --external-checks-dir /path/to/custom/checks
...
terraform scan results:

Passed checks: 0, Failed checks: 1, Skipped checks: 0

Check: ABC_AWS_AWSKeyPairDisallowed: "Ensure aws_key_pair is not used"
	FAILED for resource: aws_key_pair.abc_unittest_fail
	File: /AWSKeyPairDisallowed.tf:3-7

		3 | resource "aws_key_pair" "abc_unittest_fail" {
		4 |   # checkov:skip=ABC_AWS_AWSKeyPairDisallowed:Blah blah blah
		5 |   key_name   = "aws_key_pair_name"
		6 |   public_key = "aws_key_pair_public_key"
		7 | }

```

**Expected behavior**
I expect Checkov to skip my custom check

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/17982571/141831781-4b4faf0a-10c0-4163-93c2-074446b22c98.png)

Proposed:
![image](https://user-images.githubusercontent.com/17982571/141831872-f2991756-9ed8-464e-9d45-a0c8d5961fa6.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Checkov Version 2.0.556

**Additional context**
I realize this is very specific and not necessarily something most users are going to run into. If not something that can be addressed in the repo is there a way I can override the regex to behave how I want locally?

Thank you!

**Comment by jmeredith16** [comment]
Would it be OK to make a PR with this change? Wanted to check if I was missing anything before moving forward.

**Comment by nimrodkor** [comment]
Hey @jmeredith16 !

Yes, your solution looks good and we'd appreciate a PR with it! Thanks!
