### ISSUE TITLE
CKV_AWS_129: Ensure that respective logs of RDS are enabled.

### ISSUE THREAD

**Issue by JohnNMwangi** [bridgecrewio/checkov#1943]
**Describe the bug**
I am running this check against an example from a module but the check still fails.

**To Reproduce**

module "rds_instance_complete" {
  source                              = "./../"
  subnet_ids                          = data.aws_subnet_ids.rds.ids
  name                                = "randominstancecomplete"
  username                            = random_string.rds_usr.result
  password                            = random_string.rds_pwd.result
  kms_key_id                          = data.aws_kms_alias.rds.target_key_arn
  environment                         = "beta"
  monitoring_interval                 = "60"
  multi_az                            = "true"
  iam_database_authentication_enabled = "true"
  enabled_cloudwatch_logs_exports     = ["general", "error", "slowquery"]

**Outcome**

Check: CKV_AWS_129: "Ensure that respective logs of Amazon Relational Database Service (Amazon RDS) are enabled"
        FAILED for resource: aws_db_instance.main
        File: /tfplan.json:0-0
        Guide: https://docs.bridgecrew.io/docs/ensure-that-respective-logs-of-amazon-relational-database-service-amazon-rds-are-enabled

**Additional context**
This check only passes when I run it against the module itself.

**Comment by Saarett** [comment]
Hi @joni254 !

Could you please share the failed resource - `aws_db_instance.main` ?
The module `rds_instance_complete` might not propagate the argument `enabled_cloudwatch_logs_exports` to the failed resource.

**Comment by joni254** [comment]
Hey @Saarett here is how the `aws_db_instance.main` looks like.

resource "aws_db_instance" "main" {
  allocated_storage                   = var.allocated_storage
  allow_major_version_upgrade         = var.allow_major_version_upgrade
  auto_minor_version_upgrade          = var.auto_minor_version_upgrade
  apply_immediately                   = var.apply_immediately
  backup_retention_period             = var.backup_retention_period
  backup_window                       = var.backup_window
  copy_tags_to_snapshot               = var.copy_tags_to_snapshot
  db_subnet_group_name                = local.db_subnet_group_name
  enabled_cloudwatch_logs_exports     = var.enabled_cloudwatch_logs_exports
  engine                              = var.engine
  engine_version                      = var.engine_version
  final_snapshot_identifier           = "${var.name}finalsnapshot"
  iam_database_authentication_enabled = var.iam_database_authentication_enabled
  identifier                          = var.name
  publicly_accessible                 = var.publicly_accessible
  instance_class                      = var.instance_class
  kms_key_id                          = var.kms_key_id
  maintenance_window                  = var.maintenance_window
  monitoring_interval                 = var.monitoring_interval
  monitoring_role_arn                 = var.monitoring_role_arn
  availability_zone                   = var.availability_zone
  multi_az                            = var.multi_az
  name                                = var.name
  option_group_name                   = var.option_group_name
  parameter_group_name                = var.parameter_group_name
  username                            = var.username
  password                            = var.password
  port                                = var.port
  vpc_security_group_ids              = var.vpc_security_group_ids
  skip_final_snapshot                 = var.skip_final_snapshot
  storage_encrypted                   = var.storage_encrypted
  storage_type                        = var.storage_type
  tags = merge(
    {
      "Name"        = var.name
      "Environment" = var.environment
    },
    var.other_tags,
  )
}
