### ISSUE TITLE
Error on install checkov with dockerfile

### ISSUE THREAD

**Issue by wiliansilvazup** [bridgecrewio/checkov#1947]
**Describe the bug**
I have an Dockerfile with installation of the checkov inside 

**To Reproduce**
1. Create Dockerfile in any place:
```Dockerfile
FROM python:3.10.0-alpine

RUN apk add --quiet --no-cache wget

RUN pip3 install --upgrade pip==21.3.1 && pip3 install --upgrade setuptools==59.1.1
RUN pip3 install checkov==2.0.579
```
2. Run cli command in some place of the dockerfile:
```sh
docker build -t "custom-python-image:latest" .`
```
3. See error:
```sh
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-clx4xkkk/pycares_e8e1c1bbdc6f42069ff0aabb941cbb89/setup.py'"'"'; __file__='"'"'/tmp/pip-install-clx4xkkk/pycares_e8e1c1bbdc6f42069ff0aabb941cbb89/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7sugs03f/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/pycares Check the logs for full command output.
```

**Expected behavior**
No error installing checkov

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Checkov Version 2.0.579

**Additional context**
I'm attaching the output of the complete command, any other information just tell me.
[checkov-error-output.txt](https://github.com/bridgecrewio/checkov/files/7546647/checkov-error-output.txt)

**Comment by gruebel** [comment]
hi @wiliansilvazup we added new packages for leveraging `asyncio` and it seems like Alpine has a few issues with it, because those packages have to be created especially for the OS. We also create an Alpine based Docker image, so probably this can help you
https://github.com/bridgecrewio/checkov/blob/de5425d974fcfea749f4924678b426faa8af9e14/Dockerfile#L5-L7
this is based on the `3.9-alpine` image

**Comment by wiliansilvazup** [comment]
tnks for you support @gruebel i changed and works fine. If you want to see more about horusec we are using checkov in conjunction with other security tools in [Horusec](https://github.com/ZupIT/horusec). 🚀
