### ISSUE TITLE
Add new check: IAM Policy should follow least privilege

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#195]
Do not allow a policy with action or resource of `“*”`
Ensure this covers both IAM Policies and Managed Policies

https://www.terraform.io/docs/providers/aws/r/iam_policy.html
https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html

**Comment by nimrodkor** [comment]
@jonjozwiak I'm not sure having resource = "*" is a bad idea
And by `IAM Policies and Managed Policies` do you mean `inline policies and managed policies`?
