### ISSUE TITLE
Add OCI TF check - OCI Default Security List of every VCN allows all traffic on SSH port (22)

### ISSUE THREAD

**Issue by GiladMark** [bridgecrewio/checkov#1954]
RQL equivalent query

config from cloud.resource where cloud.type = 'oci' AND api.name = 'oci-networking-security-list' AND json.rule = (displayName contains "Default Security List for") and (ingressSecurityRules[?any((source equals 0.0.0.0/0) and (((*.destinationPortRange.min == 22 or *.destinationPortRange.max == 22) or (*.destinationPortRange.min < 22 and *.destinationPortRange.max > 22)) or (protocol equals "all") or ((tcpOptions does not exist) and (udpOptions does not exist) and (protocol does not equal 1))))] exists)

**Comment by GiladMark** [comment]
Note that RQL queries are spotting the error while “Checkov logic wish to find the Desired state” use the referance below in order to get more data for the check needed -

_This policy identifies OCI Default Security lists associated with every VCN that allow unrestricted ingress access to port 22. It is recommended that no security group allows unrestricted ingress access to port 22. As a best practice, remove unfettered connectivity to remote console services, such as Secure Shell (SSH),  to reduce server's exposure to risk._


https://github.com/PaloAltoNetworks/prisma-cloud-policies/blob/master/policies/OCI-Default-Security-List-of-every-VCN-allows-all-traffic-on-SSH-port-22.json

**Comment by gruebel** [comment]
@praveen-panw tagging you here too
