### ISSUE TITLE
Add OCI TF check - OCI IAM password policy for local (non-federated) users does not have minimum 14 characters

### ISSUE THREAD

**Issue by GiladMark** [bridgecrewio/checkov#1969]
Equivalent RQL query

config from cloud.resource where cloud.type = 'oci' AND api.name = 'oci-iam-authentication-policy' AND json.rule = 'passwordPolicy.minimumPasswordLength less than 14'

**Comment by GiladMark** [comment]
Note that RQL queries are spotting the error while “Checkov logic wish to find the Desired state” use the referance below in order to get more data for the check needed -

_This policy identifies Oracle Cloud Infrastructure(OCI) accounts that do not have a minimum of 14 characters in the password policy for local (non-federated) users. As a security best practice, configure a strong password policy for secure access to the OCI console._
https://github.com/PaloAltoNetworks/prisma-cloud-policies/blob/master/policies/OCI-IAM-password-policy-for-local-non-federated-users-does-not-have-minimum-14-characters.json

**Comment by JamesWoolfenden** [comment]
Think this is done @GiladMark
