### ISSUE TITLE
Add OCI TF check - OCI MFA is disabled for IAM users

### ISSUE THREAD

**Issue by GiladMark** [bridgecrewio/checkov#1970]
Equivalent RQL query

config from cloud.resource where cloud.type = 'oci' AND api.name = 'oci-iam-user' AND json.rule = 'isMfaActivated is false'

**Comment by JamesWoolfenden** [comment]
This property is no exposed for OCI user resource oci-identity-user, and i cant see where else this would be set.

**Comment by GiladMark** [comment]
Note that RQL queries are spotting the error while “Checkov logic wish to find the Desired state” use the referance below in order to get more data for the check needed -

_This policy identifies Identify Access Management (IAM) users for whom Multi Factor Authentication (MFA) is disabled. As a best practice, enable MFA to add an extra layer of protection for increased security of your OCI user’s identity and complete the sign-in process._

https://github.com/PaloAltoNetworks/prisma-cloud-policies/blob/master/policies/OCI-MFA-is-disabled-for-IAM-users.json
