### ISSUE TITLE
Add OCI TF check - OCI Security List allows all traffic on SSH port (22)

### ISSUE THREAD

**Issue by GiladMark** [bridgecrewio/checkov#1974]
Equivalent RQL query

config from cloud.resource where cloud.type = 'oci' AND api.name = 'oci-networking-security-list' AND json.rule = (ingressSecurityRules[?any((source equals 0.0.0.0/0) and (((*.destinationPortRange.min == 22 or *.destinationPortRange.max == 22) or (*.destinationPortRange.min < 22 and *.destinationPortRange.max > 22)) or (protocol equals "all") or ((tcpOptions does not exist) and (udpOptions does not exist) and (protocol does not equal 1))))] exists)

**Comment by ayajbara** [comment]
@GiladMark if the "source" is not equal to  0.0.0.0/0, should the check skip or fail?
