### ISSUE TITLE
Add OCI TF check - OCI users Auth Tokens have aged more than 90 days without being rotated

### ISSUE THREAD

**Issue by GiladMark** [bridgecrewio/checkov#1978]
Equivalent RQL query

config from cloud.resource where cloud.type = 'oci' AND api.name = 'oci-iam-user' AND json.rule = 'authTokens[?any(lifecycleState equals ACTIVE and (_DateTime.ageInDays(timeCreated) > 90))] exists'

**Comment by JamesWoolfenden** [comment]
not possible for checkov. Would need something like prowler for OCI

**Comment by GiladMark** [comment]
agree - closing
