### ISSUE TITLE
Add OCI TF check - OCI users customer secret keys have aged more than 90 days without being rotated

### ISSUE THREAD

**Issue by GiladMark** [bridgecrewio/checkov#1979]
Equivalent RQL query

config from cloud.resource where cloud.type = 'oci' AND api.name = 'oci-iam-user' AND json.rule = 'customerSecretKeys[?any(lifecycleState equals ACTIVE and (_DateTime.ageInDays(timeCreated) > 90))] exists'

**Comment by JamesWoolfenden** [comment]
No possible for checkov, would need something like prowler for OCI.

**Comment by GiladMark** [comment]
agree @nimrodkor - I'm closing it now
