### ISSUE TITLE
Directory scan creates multiple JSONs/XMLs

### ISSUE THREAD

**Issue by afterdesign** [bridgecrewio/checkov#198]
**Describe the bug**
When running checkov against directory it's creating JSON/XML for each `check_type` that it finds.

**To Reproduce**
Create directory that has terraform cloudformation definitions and some other like generic IAM.
Run:
`checkov -d directory -o json python3 -c 'import json;import sys;print(json.load(sys.stdin));'` to verify if it's correctly formatted JSON.

**Expected behavior**
I think in this case it should be list of dictionaries for JSON (or maybe even single JSON). I don't know junit format to say how it should behave.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Checkov Version 1.0.216

**Additional context**
I'm trying to integrate checkov output with reviewdog and to do this I'm doing right now wrapper to change JSON to checkstyle format. If I'll have time then I will try to integrate checkstyle formatting natively to checkov.

**Comment by schosterbarak** [comment]
hey @afterdesign  can you give an example of the expected output format in json?

**Comment by afterdesign** [comment]
@schosterbarak I have 2 ideas for this. I will write them down tomorrow as today I'm not gonna find time for this.

**Comment by afterdesign** [comment]
Here is JSON output for 2 types that is currently produced:

```
{
    "check_type": "terraform",
    "results": {
        "passed_checks": [
            {
                "check_id": "CKV_AWS_41",
                "check_name": "Ensure no hard coded AWS access key and and secret key exists",
                "check_result": {
                    "result": "PASSED"
                },
            }
        ]
    }
}
{
    "check_type": "cloudformation",
    "results": {
        "passed_checks": [
            {
                "check_id": "CKV_AWS_36",
                "check_name": "Ensure CloudTrail log file validation is enabled",
                "check_result": {
                    "result": "PASSED"
                },
            }
        ]
    }
}
```

So there are 2 options in my opinion.
First: list of JSONs (but I think this won't work for junit xml):

```
[
  {
      "check_type": "terraform",
      "results": {
          "passed_checks": [
              {
                  "check_id": "CKV_AWS_41",
                  "check_name": "Ensure no hard coded AWS access key and and secret key exists",
                  "check_result": {
                      "result": "PASSED"
                  },
              }
          ]
      }
  },
  {
      "check_type": "cloudformation",
      "results": {
          "passed_checks": [
              {
                  "check_id": "CKV_AWS_36",
                  "check_name": "Ensure CloudTrail log file validation is enabled",
                  "check_result": {
                      "result": "PASSED"
                  },
              }
          ]
      }
  }
]
```

Second: add check_type to single check information (and this might work somehow for junit xml):
```
{
    "check_type": "terraform",
    "results": {
        "passed_checks": [
            {
                "check_id": "CKV_AWS_41",
                "check_type": "terraform",
                "check_name": "Ensure no hard coded AWS access key and and secret key exists",
                "check_result": {
                    "result": "PASSED"
                },
            },
            {
                  "check_id": "CKV_AWS_36",
                  "check_type": "cloudformation",
                  "check_name": "Ensure CloudTrail log file validation is enabled",
                  "check_result": {
                      "result": "PASSED"
                  },
              }
        ]
    }
},
```
