### ISSUE TITLE
Delimiter in wrong position when using multi-output with empty error list

### ISSUE THREAD

**Issue by tonikarppi** [bridgecrewio/checkov#1995]
**Describe the bug**
The "--- OUTPUT DELIMITER ---" message appears below two outputs when running on a project without any errors to output. This causes problems when trying to use parsers to split the output.

**To Reproduce**
1. mkdir -p /tmp/checkov-bug
2. cd /tmp/checkov-bug
3. docker run -it -v $PWD:/app -w /app bridgecrew/checkov:2.0.591 -o cli -o junitxml -d .

Output is:
       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.590 
Update available 2.0.590 -> 2.0.591
Run pip3 install -U checkov to update 

\<?xml version="1.0" ?\>
\<testsuites/\>

--- OUTPUT DELIMITER ---

**Expected behavior**

The expected behaviour would be for the XML snippet to be below "--- OUTPUT DELIMITER ---", since it was the second output option passed to checkov.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker image bridgecrew/checkov
 - Checkov Version 2.0.591

**Additional context**

**Comment by gruebel** [comment]
Hi @tonikarppi thanks for raising this issue. This seems to be a bug and only happens, as you described it, when there is no violation. Just for your information, it doesn't matter, how the order of the output parameters are, they will always be printed out in a specific order and CLI should be first and then the other ones are followed up.
