### ISSUE TITLE
Receiving a parsing error while using Checkov on tf.json

### ISSUE THREAD

**Issue by hkubram** [bridgecrewio/checkov#1997]
**Describe the bug**
An attempt to run a Checkov scan on a plan file leads to a Parsing Error

**To Reproduce**
1. Go to the terminal
2. Run cli commands:
    terraform init
    terraform plan -out tf.plan
    terraform show -json tf.plan  > tf.json 
    checkov -f tf.json`
3. See the error:
    Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1
    Error parsing file tf.json

**Expected behavior**
   No Parsing error

**Screenshots**
![image](https://user-images.githubusercontent.com/41157379/142707324-dd6b2a17-e495-420e-8eea-6ee0d6d651c9.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Checkov Version 2.0.591

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by hkubram** [comment]
This issue is a duplicate

**Comment by schosterbarak** [comment]
hey @hkubram  thanks for reporting, what is the delicate issue? 

also would you be able to share a plan file so we can test the cause?
