### ISSUE TITLE
Has terraform_plan depreciated? 

### ISSUE THREAD

**Issue by hkubram** [bridgecrewio/checkov#2016]
"-framework terraform_plan" is not in the Checkov documentation below.  
https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

Has "-framework terraform_plan" depreciated?

Below is the error "-framework terraform_plan" resolved:
https://stackoverflow.com/questions/70037670/receiving-a-parsing-error-while-using-checkov

**Comment by gruebel** [comment]
Hi @hkubram, thanks for raising the issue, the `terraform_plan` framework option is not deprecated. The documentation is just not up-to-date 🙈 
@schosterbarak we probably should have a look in our documentation, if we have more areas, which don't reflect the current feature status.

**Comment by hkubram** [comment]
Thank you
