### ISSUE TITLE
Getting KeyError : 0 while scanning cloud formation template

### ISSUE THREAD

**Issue by methelegend-sys** [bridgecrewio/checkov#2018]
**Describe the bug**
Getting KeyError : 0 while scanning cloud formation template

**Screenshots**

![image](https://user-images.githubusercontent.com/55847022/143419131-4981910f-46ed-406b-8dd9-6ab62ecbcedd.png)

**Comment by nimrodkor** [comment]
Hey @methelegend-sys !

It seems checkov fails to parse an `if` operator. Can you share the relevant template that is causing this?

**Comment by methelegend-sys** [comment]
I hope I could but I am not the author of this template so editing this is kind of pain for me

**Comment by methelegend-sys** [comment]
I wish I could share it with you but that is not possible. 

> Hey @methelegend-sys !
> 
> It seems checkov fails to parse an `if` operator. Can you share an anonymized version of the relevant template that is causing this?
