### ISSUE TITLE
Adding category filtering

### ISSUE THREAD

**Issue by vicmar57** [bridgecrewio/checkov#2028]
**Is your feature request related to a problem? Please describe.**
No, it's just a feature I think is worth adding support to. 
Currently, in the CLI tool there is an option to skip specific checks, through the --check CLI parameter. 
I thought it would be great to add support for category filtering (for example, an option to check only "networking" rules).

**Describe the solution you'd like**
Enable category filtering using the category property of each check

**Describe alternatives you've considered**
passing all checks for a ceratin category, by name (less convenient of course, and requires knowing exactly which checks are there per specific category)

**Comment by nimrodkor** [comment]
Directly related to #1445 , closing this one in favor of the legacy issue
