### ISSUE TITLE
CKV_AZURE_42 false positive

### ISSUE THREAD

**Issue by teemukom** [bridgecrewio/checkov#2037]
**Describe the bug**
CKV_AZURE_42 is reported as failure altough enableSoftDelete and enablePurgeProtection are set to true

**To Reproduce**
1. Create ARM/Bicep template with Microsoft.KeyVault/vaults resource in it
2. Set enableSoftDelete and enablePurgeProtection to true
2. Run checkov
3. See error Resource Microsoft.KeyVault/vaults.[parameters('keyVaultName')] failed in check CKV_AZURE_42/Ensure the key vault is recoverable - /main.json:[723, 743] - Guideline: https://docs.bridgecrew.io/docs/ensure-the-key-vault-is-recoverable

**Expected behavior**
When these two settings are set to true, CKV_AZURE_42 should not fail

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Checkov Version: docker.io/bridgecrew/checkov:latest (DIGEST:sha256:b1846df8780cd9a986b14461bc1f618850344317b779653a9f8840587085cd71)

**Comment by nimrodkor** [comment]
Hey @teemukom , can you share an anonimized version of the template? Could be with just that resource, so we can test. The reason is we already have test cases for this, and the relevant test case seems to be passing... So there must be something weird, either with what we expect is not the correct configuration or there's another way to write it.

Can you share a simple example which should pass but fails?

**Comment by teemukom** [comment]
Just did a quick test myself and it seems that when using Bicep and defining the resource creation through module the test fails. When using a simple template which has the resource in it, the test succeeds. Only difference between these approaches is that when using modules the JSON file created by Bicep includes the Deployment resource (Microsoft.Resources/deployments) also.

I've attached four files:
- keyvault.bicep.txt, includes the Keyvault resource and it's parameters
- main.bicep.txt, only includes sections to call keyvault.bicep as a module
- main.json.txt & keyvault.json.txt, the JSON formatted files after calling az bicep build

Files converted to TXT to be able to upload
[keyvault.bicep.txt](https://github.com/bridgecrewio/checkov/files/7626344/keyvault.bicep.txt)
[keyvault.json.txt](https://github.com/bridgecrewio/checkov/files/7626346/keyvault.json.txt)
[main.bicep.txt](https://github.com/bridgecrewio/checkov/files/7626347/main.bicep.txt)
[main.json.txt](https://github.com/bridgecrewio/checkov/files/7626348/main.json.txt)
