### ISSUE TITLE
Enable GitHub releases for custom checks to import git repositories with --external-checks-git 

### ISSUE THREAD

**Issue by WickramBug** [bridgecrewio/checkov#2059]
**Is your feature request related to a problem? Please describe.**
As per my understanding, we cannot use GitHub specific repository release with the --external-checks-git and it would need a git URL to clone the repository to the temporary folder. We are in a need of using GitHub releases to use different types of custom checks according to the release versions.

**Describe the solution you'd like**
It would be great if we get a feature update to use the GitHub releases with external checks.
The available usage, 
`checkov --external-checks-git  https://github.com/bridgecrewio/checkov.git`
What is expected,
Sample release URL: https://github.com/my-sample-repo/sample-project/releases/tag/v1.0.0
`checkov --external-checks-git  https://github.com/my-sample-repo/sample-project/releases/tag/v1.0.0`
Or 
`checkov --external-checks-git  https://github.com/bridgecrewio/checkov.git --git-release v1.0.0`

**Describe alternatives you've considered**
Currently, we are not using the GitHub releases.

**Additional context**
N/A

**Comment by schosterbarak** [comment]
@WickramBug looks like release url should be supported: https://github.com/bridgecrewio/checkov/commit/876be836ffc55a501350260dc2af6d05f4ad4222#diff-925156d1e7980b2d131a101797ceaf8378af8c13b83da4de01efb20b3fc62c64 
If it is not it should be around those lines to debug and fix

**Comment by WickramBug** [comment]
Hi @schosterbarak thank you for your suggestion.

Could you please able to show a sample command to pass release URLs? Because I get the below fatal error,
`fatal: repository 'https://github.com/sample-repo/sample-proj/releases/tag/v1.0.0/' not found`

Command used: `checkov -d . --framework kubernetes --external-checks-git https://github.com/sample-repo/sample-proj/releases/tag/v1.0.0//security/tools/static-scanning/iac/checkov/kubernetes`

May I know where am I going wrong here?

**Comment by schosterbarak** [comment]
Is it a private repo?

**Comment by WickramBug** [comment]
@schosterbarak yes, that is correct.

**Comment by schosterbarak** [comment]
@WickramBug we don't support private repositories for external checks at the moment. Having said that you can utilize birdgecrew.cloud for centralized policy management and start using it for free.

**Comment by WickramBug** [comment]
@schosterbarak thank you for the update and I'll try out the cloud solution.
