### ISSUE TITLE
New Issue Classification Process

### ISSUE THREAD

**Issue by nimrodkor** [bridgecrewio/checkov#2060]
Hello everyone!

We've reached the point where we have over 200 open issues, and want to have a good way to sort through them and to easily capture the different "classes" of issues - from first time contribution opportunities, through critical regression issues and bugs, to feature requests that can help Checkov become even more awesome!

The best and easiest way we thought of was to make a more extensive use of github labels! From (quickly :sweat_smile: ) reviewing the existing open issues, we've found these topics as recurring enough to have their own label:
* `checks` - for issues around new checks, false positives in existing checks, enhancements to checks etc.
* `best practices` - for features pertaining to acheiving best practices, [example 1](https://github.com/bridgecrewio/checkov/issues/853) [example 2](https://github.com/bridgecrewio/checkov/issues/482)
* `output enhancement` - for requests to add another output format, add fields to existing output etc. [example 1](https://github.com/bridgecrewio/checkov/issues/559)
* `languages` - for issues requesting support of more languages / extend support of existing languages. [example 1](https://github.com/bridgecrewio/checkov/issues/568) [example 2](https://github.com/bridgecrewio/checkov/issues/762) [example 3](https://github.com/bridgecrewio/checkov/issues/864)
* `integrations` - bugs and features around checkov's integration with other tools, such as [pre-commit](https://github.com/bridgecrewio/checkov/issues/661) & [AWS Security Hub](https://github.com/bridgecrewio/checkov/issues/753)
* `graph` - graph building, rendering, and supported operators for graph checks. [example 1](https://github.com/bridgecrewio/checkov/issues/773)
* `crash` - critical regression / crash issues that you run into.
* `skips` - requests, bugs and enhancements around the skipping capabilities. [example 1](https://github.com/bridgecrewio/checkov/issues/1224) [example 2](https://github.com/bridgecrewio/checkov/issues/1680)
* `parser` - bugs and errors around parsing of source files. [example 1](https://github.com/bridgecrewio/checkov/issues/1469)
* `noise` - issues regarding the cleanliness of the output, the verbosity of logs etc

Moreover, we would like to highly recommend adding a framework tag to denote the relevant framework that is suffering from this issue. For the framework label please use the framework name as it is defined [here](https://github.com/bridgecrewio/checkov/blob/master/checkov/main.py#L51).

We're open to suggestions, please feel free to share your thoughts / upvote (:+1:) if this sounds good to you too!

Thanks,
The BC team

**Comment by pascal-hofmann** [comment]
Hi,
I'm not able to assign labels to issues. What's the plan here? Will the labels always be assigned by project maintainers?

**Comment by nimrodkor** [comment]
We can leverage the issue templates for this
https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner/31366954#31366954

**Comment by schosterbarak** [comment]
@nimrodkor great! lets do it :)

**Comment by metahertz** [comment]
Suggest a "noise" tag as well, for developer/user UX stuff which is causing more output than expected, noisy output, etc.

**Comment by nimrodkor** [comment]
Added @metahertz
