### ISSUE TITLE
CKV_AWS_174 incorrect reporting

### ISSUE THREAD

**Issue by jgreaves91** [bridgecrewio/checkov#2063]
CKV_AWS_174 is being triggered in our terraform code even though we have the viewer certificate set to use TLSv.1.2. Snippet of our code here:

viewer_certificate {
   acm_certificate_arn = aws_acm_certificate.cert.arn
   ssl_support_method       = "sni-only"
   minimum_protocol_version = "TLSv1.2_2019" 
}

Running checkov on our terraform code

**Expected behavior**
This check should be passed

**Additional context**
It looks to me like the issue is in the code between lines 17 and 19. I dont think based on the terraform documentation and the if statements that it would ever pass if using an acm certificate

https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/CloudfrontTLS12.py

**Comment by gruebel** [comment]
Hi @jgreaves91 you are correct, the check should be adjusted, as a workaround you could set `cloudfront_default_certificate = false` and then the check should pass. Do you want to fix it? Then I can give you some pointers, what you have to do 💪

**Comment by nimrodkor** [comment]
Thanks for reporting @jgreaves91 !

We'd happily accept a contribution on this if you're willing!
