### ISSUE TITLE
Parameterize Checkov Generator script

### ISSUE THREAD

**Issue by kmcquade** [bridgecrewio/checkov#2077]
The Checkov rule generator script written by @jmeredith16 is **awesome**. However, it seems like it is tied to Checkov's library-specific location here:

https://github.com/bridgecrewio/checkov/pull/1886/files#diff-e1b586bdac25f3a8dc7ebb37254391e9b3a24328e6bac60cb88ac4bb10ac3c50R12-R13

We have our own Checkov wrapper internally, and I'd love to use it internally without duplicating his script entirely. It would be awesome to be able to override the values for `CKV_PKG_DIRECTORY` AND `CKV_TEST_DIRECTORY` . This way, we can create a script on our end that wraps that functionality and pumps the files into our own directories.

I'm happy to tackle this and can create a PR for it. In the meantime, feel free to ask any questions or provide your thoughts!

**Comment by schosterbarak** [comment]
Let's do it via env variables :) 
Can you add a CKV prefix to the env variable names?

**Comment by kmcquade** [comment]
sure, that works!
