### ISSUE TITLE
checkov fails to scan modules hosted in private repos

### ISSUE THREAD

**Issue by carloscruzadomatrix** [bridgecrewio/checkov#2098]
**Describe the bug**
I cant check external repos, the logs print  "Failed to download module ". I try this in my pc and with github actions (uses: bridgecrewio/checkov-action@master). The error is the same.

**To Reproduce**

1. Run cli command
checkov -d . --download-external-modules true --download-external-modules .external_modules

2. See error
2021-12-13 12:22:15,601 [ThreadPoolEx] [WARNI]  Failed to download module terraform-aws-modules/vpc/aws:3.11.0

![01](https://user-images.githubusercontent.com/95088398/145860130-06310f4a-0203-47a0-acf7-ffcd0cece50d.PNG)
![02](https://user-images.githubusercontent.com/95088398/145860132-3b0809a5-3125-4167-9aaa-6b8fdbbc4ea3.PNG)

**Comment by gruebel** [comment]
Hi @carloscruzadomatrix can you post the `module` usage in your Terraform template, then I can better recreate the issue.

**Comment by carloscruzadomatrix** [comment]
I have 2 modules:

source = "terraform-aws-modules/eks/aws"
source = "terraform-aws-modules/vpc/aws"

2021-12-14 16:36:48,043 [MainThread  ] [WARNI]  Failed to download module terraform-aws-modules/eks/aws:17.24.0
2021-12-14 16:36:48,043 [MainThread  ] [WARNI]  Failed to download module terraform-aws-modules/vpc/aws:3.11.0

**Comment by gruebel** [comment]
I tested it and it works fine, my best guess is, that there is some issue with Windows. As I can see you are running the check on your `G` drive on Windows right? Can you try it on the `C` drive?

**Comment by carloscruzadomatrix** [comment]
but the same problem happend in github actions,
![01](https://user-images.githubusercontent.com/95088398/146264689-f21573aa-3af6-419c-bbb8-4fe2c3e73bcb.PNG)

**Comment by nimrodkor** [comment]
Hey @carloscruzadomatrix , did #2118 get this resolved for you?

**Comment by tspearconquest** [comment]
This is an issue I just ran into

**Comment by tspearconquest** [comment]
```
~/test ❯ checkov -d . -o junitxml
2022-04-27 18:43:18,300 [MainThread  ] [WARNI]  Failed to download module gitlab.com/private/project1/azure:0.0.14 (for external modules, the --download-external-modules flag is required)
2022-04-27 18:43:18,301 [MainThread  ] [WARNI]  Failed to download module gitlab.com/private/project2/azure:0.0.3 (for external modules, the --download-external-modules flag is required)
2022-04-27 18:43:18,302 [MainThread  ] [WARNI]  Failed to download module gitlab.com/private/project3/azure:0.0.4 (for external modules, the --download-external-modules flag is required)
2022-04-27 18:43:18,302 [MainThread  ] [WARNI]  Failed to download module gitlab.com/private/project4/azure:0.0.2 (for external modules, the --download-external-modules flag is required)
2022-04-27 18:43:18,302 [MainThread  ] [WARNI]  Failed to download module gitlab.com/private/project5/azure:0.0.20 (for external modules, the --download-external-modules flag is required)
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="0" tests="0" time="0.0">
	<testsuite disabled="0" errors="0" failures="0" name="None scan" skipped="0" tests="0" time="0">
		<properties>
			<property name="directory" value="['.']"/>
			<property name="add_check" value="False"/>
			<property name="list" value="False"/>
			<property name="output" value="['junitxml']"/>
			<property name="output_bc_ids" value="False"/>
			<property name="include_all_checkov_policies" value="True"/>
			<property name="quiet" value="False"/>
			<property name="compact" value="False"/>
			<property name="framework" value="['all']"/>
			<property name="run_all_external_checks" value="False"/>
			<property name="soft_fail" value="False"/>
			<property name="repo_id" value="cli_repo/armed-stack"/>
			<property name="branch" value="master"/>
			<property name="skip_download" value="False"/>
			<property name="no_guide" value="False"/>
			<property name="skip_suppressions" value="False"/>
			<property name="skip_policy_download" value="False"/>
			<property name="skip_fixes" value="False"/>
			<property name="download_external_modules" value="False"/>
			<property name="external_modules_download_path" value=".external_modules"/>
			<property name="evaluate_variables" value="True"/>
			<property name="create_baseline" value="False"/>
		</properties>
	</testsuite>
</testsuites>
```

Source lines for these modules look as:

source  = "gitlab.com/private/project1/azure"
source  = "gitlab.com/private/project2/azure"
source  = "gitlab.com/private/project3/azure"
source  = "gitlab.com/private/project4/azure"
source  = "gitlab.com/private/project5/azure"

**Comment by 64J0** [comment]
I'm having the same problem mentioned by @tspearconquest

**Comment by tsmithv11** [comment]
This should be resolved thanks to @kartikp10. Let us know if you are still running into issues.

**Comment by tspearconquest** [comment]
@tsmithv11 do you mind please linking to the pull request which solves this? Thank you in advance.

**Comment by kartikp10** [comment]
Hey @tspearconquest, the fixes for this came across a few different PRs. Checkov can access private repos using cached git credentials or using a personal access token that's available in an env var. Refer to the `Scanning Private Terraform Modules` section [here](https://www.checkov.io/7.Scan%20Examples/Terraform%20Plan%20Scanning.html). I'm pasting an example of the github-action for the benefit of others on the issue, however, I realize that your use case is not supported at the moment. 

```
name: checkov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

      - uses: actions/checkout@v3
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          download_external_modules: true
          log_level: DEBUG
          github_pat: ${{ secrets.GH_PAT }}
          framework: terraform
```

In your case, the format `gitlab.com/<namespace>/<module-name>/<module-system>` refers to a GitLab self-hosted module registry that implements the [Terraform Module Registry Protocol](https://www.terraform.io/internals/module-registry-protocol), which is not supported in checkov currently (but will be in the future).  
We do presently support generic git repo formats (private and public) and almost all other sources (minus buckets and mercurial) mentioned [here](https://www.terraform.io/language/modules/sources).

**Comment by tspearconquest** [comment]
Wow, thank you for the clear update! I appreciate it! Is there an issue I can subscribe to for the Terraform Module Registry Protocol support you mentioned is coming?

**Comment by tspearconquest** [comment]
Wow, thank you for the great update! I'll open that issue now!

**Comment by faheemgani** [comment]
@kartikp10 I'm trying to use this to download modules from my Azure DevOps Private Git Repository using the vcs_base_url, vcs_username and vcs_token environment variables, with no luck. I'm using this with the Checkov Docker Image - like so:

```docker run --name checkov_scan_1 --rm --volume 'c:\users\faheem\dev\core\:/core' --env vcs_base_url=https://dev.azure.com/ --env vcs_username=any --env vcs_token=xxx ff86b03e9775 --file '/core/tfplan.json' --repo-root-for-plan-enrichment '/core' --download-external-modules true -o junitxml --soft-fail```

I'm also wondering if we can use pre-existing modules that exist on the file system (and inside of the Docker container) rather than downloading them again. In my case all the modules exist inside the Docker container under the /core/.terraform folder so not sure why Checkov tries to download them again.

This is what my module configuration looks like: 

```
module "acr" {
  source = "git::https://dev.azure.com/xxx/Infrastructure/_git/tf-modules//src/modules/acr"
  environment     = var.environment
  project         = var.project
  tenant_id       = var.tenant_id
  subscription_id = var.subscription_id
  rg_name         = var.rg_name
  region          = var.region
  ado_project     = "Infrastructure"
  common_tags     = var.common_tags

  providers = {
    azurerm = azurerm.development
  }

  #checkov:skip=CKV_AZURE_139:Not a premium ACR - this does not support private endpoints
  #checkov:skip=CKV_AZURE_163:Not a premium ACR - this does not support vulnerability scanning
  #checkov:skip=CKV_AZURE_165:Not a premium ACR - this does not support geo-replication
  #checkov:skip=CKV_AZURE_167:Not a premium ACR - this does not support retention periods
}
```

**Comment by AshishDadhich4h2** [comment]
@faheemgani  I was trying same (downloading modules from Azure DevOps Private Git Repository) with docker cli with passing --download-external-modules true and got same warnings like 
`[WARNI]  Failed to download module`

Not sure what is the fix to allow checkov for scanning already downloaded modules in .terraoform directory as part in  terrafom init process rather than trying to download and failing without giving any specific reason.

**Comment by mikeurbanski1** [comment]
@AshishDadhich4h2 you can probably get more info using `LOG_LEVEL=DEBUG`

**Comment by AshishDadhich4h2** [comment]
@mikeurbanski1  I don't see LOG_LEVEL option in checkov cli. I am running chekcov docker image and couldn't find any option to pass LOG_LEVEL

**Comment by AshishDadhich4h2** [comment]
@kartikp10 did you fix your issue ?

**Comment by AshishDadhich4h2** [comment]
> @mikeurbanski1 I don't see LOG_LEVEL option in checkov cli. I am running chekcov docker image and couldn't find any option to pass LOG_LEVEL

Never mind  I am able to pass LOG_LEVEL as an env varaiable. Thank you ! But still it doesn't solve the problem
