### ISSUE TITLE
Bypass level up prompt

### ISSUE THREAD

**Issue by yocally** [bridgecrewio/checkov#2099]
**Is your feature request related to a problem? Please describe.**
Checkov has mandatory interaction on first run asking if you'd like to "level up", which breaks CI pipelines.

**Describe the solution you'd like**
Some kind of "assume no" or "no interaction" CLI flag that disables both this and any other future interaction so that CI pipelines don't get broken.

**Describe alternatives you've considered**
There is a work around, calling checkov like `echo "n" | checkov` solves the problem, but I don't think this is acceptable for a tool that is largely used in non-interactive environments.

**Comment by gruebel** [comment]
Hi @yocally , how do you actually invoke `checkov`? The level up prompt is only shown, if you don't use `--quiet` or don't pass any file or directory to be checked. `checkov` is run in a lot of CI pipelines, either free or paid, without the need to interact with it.

**Comment by yocally** [comment]
My bad, I wasn't setting the directory correctly, please disregard.
