### ISSUE TITLE
Discrepancy in caller_file_path and source_module_

### ISSUE THREAD

**Issue by pinaki16shaw** [bridgecrewio/checkov#2109]
**Describe the bug**
When a terraform project has multiple references to a git repo for a module source, the caller_file_path info and the "path" in "source_module_" do not match.
 
**To Reproduce**
1. Create IaC Project A
2. Create IaC Project B
3. In a module in Project A, File 1 - mention Project B as source
4. In another module in Project A, File 2 - mention Project B as source
5. Run Checkov Scan using CLI and with "download-external-modules' set to True
6. In the Checkov response, check the caller_file_path and the source_module_path
7. For a failed check (assume in File X of Project B), output observed:
   "caller_file_path":  "/path to Project A source code folder/dir/File1.tf"
   “source_module_":  [
                       			 {
                            				"type": "module",
                           				 "name": "second_module",
                           				 "path": "/path to Project A source code folder /File2.tf"
                        	}]

**Expected behavior**
   "caller_file_path":  "/path to Project A source code folder/dir/File1.tf"
   “source_module_":  [
                       			 {
                            				"type": "module",
                           				 "name": "second_module",
                           				 "path": "/path to Project A source code folder /File1.tf"
                        	}]

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Checkov Version: 2.0.648

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by schosterbarak** [comment]
@pinaki16shaw thanks for letting us know. what is the usecase for this change? what would a user benefit from it?
