### ISSUE TITLE
Caller file path and line range information when an external module source reference has a child module pointing to another project

### ISSUE THREAD

**Issue by pinaki16shaw** [bridgecrewio/checkov#2110]
**Is your feature request related to a problem? Please describe.**
If IaC project A has a module reference to a git repo project B which has reference to a git repo project C, checks for any files in Project C do not have the caller_file_path and caller_file_line_range information. Following is what is reported by Checkov for a check:
                "caller_file_path": null,
                "caller_file_line_range": null,

**Describe the solution you'd like**
Since the originating source is a file in Project A, the caller_file_path and caller_file_line_range information should have the details about the file in Project A. This information should be made available no matter how many such chained references (Proj A -> B ->C -> D etc.) are there.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by schosterbarak** [comment]
@pinaki16shaw thanks for letting us know. what is the usecase for this change? what would a user benefit from it?
