### ISSUE TITLE
Breadcrumbs missing for checks performed on source code of projects referenced as module sources in different ways

### ISSUE THREAD

**Issue by pinaki16shaw** [bridgecrewio/checkov#2113]
**Describe the bug**
Consider the following module reference example:
Project A File 1 -- > Proj B  -- > Proj X
Also, Project A File 2 -- > Proj C  -- > Proj X
For a check on a file in Proj X, no breadcrumbs information or call_file_path information is available

**To Reproduce**
1. Create IaC Project A
2. In a module in Project A, File 1 - mention Project B as source
3. In a module in Project B, mention Project X as source
4. In another module in Project A, File 2 - mention Project C as source
5. In a module in Project C, mention Project X as source
6. Run Checkov Scan using CLI and with "download-external-modules' set to True
7. Check Checkov report for a check on a file on Project X.

**Expected behavior**
1. Since the originating source is a file in Project A, the caller_file_path and caller_file_line_range information should have the details about the file in Project A
2. Breadcrumbds should have source_module_ which provides info about Proj A, Proj B, Proj C etc. from where Proj X is ultimately referenced.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Checkov Version: 2.0.648

**Additional context**
N/A

**Comment by schosterbarak** [comment]
@pinaki16shaw thanks for letting us know. what is the usecase for this change? what would a user benefit from it?
