### ISSUE TITLE
Check CKV2_AZURE_8 is performed against Storage Account instead of Storage Container

### ISSUE THREAD

**Issue by arogic** [bridgecrewio/checkov#2134]
**Describe the bug**
The checkov Check "CKV2_AZURE_8: Ensure the storage container storing the activity logs is not publicly accessible" is performed against the Azure Storage Account instead of the Azure Storage Container (https://docs.bridgecrew.io/docs/ensure-the-storage-container-storing-the-activity-logs-is-not-publicly-accessible). The Argument "container_access_type" is set to "private" on the Terraform Resource "azurerm_storage_container", but it seems not be checked by checkov.

```
resource "azurerm_storage_container" "sc" {
  name                                 = var.storage_container_name
  storage_account_name  = azurerm_storage_account.sa.name
  container_access_type   = "private"
}
```

**To Reproduce**
1. Open Commandline
2. checkov --directory ./terraform --skip-check "CKV_DOCKER_*"

**Expected behavior**
The checkov Check "CKV2_AZURE_8: Ensure the storage container storing the activity logs is not publicly accessible" should check against the "azurerm_storage_container" Resource and not the "azurerm_storage_account" Resource.

**Screenshots**
<img width="886" alt="Screenshot 2021-12-21 at 14 24 28" src="https://user-images.githubusercontent.com/56870423/146937662-9bd54e7b-2b76-436e-be20-b721b05e80cf.png">

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.6
 - Checkov Version 2.0.678

**Comment by gruebel** [comment]
Yeah, definitely an interesting check 😄 it doesn't check if the container is private or not, but it checks if you also added a `azurerm_monitor_activity_log_alert`, if not then it fails or if you disabled it, then it also fails.

**Comment by adamrushuk** [comment]
I was about to log this issue, so I'm glad to find it's already being looked at :)

**Comment by Joerg-L** [comment]
> I was about to log this issue, so I'm glad to find it's already being looked at :)

same for me.

**Comment by byteknacker** [comment]
I am encountering the same problem. Just noticed this today. It should check against the azurerm_storage_container resource and not the azurerm_storage_account resource. Plus, the azurerm_monitor_activity_log_alert entry in the docs is confusing and is not required by this policy. In my console output there is also no link to the documentation. This link should be added to the console output as the value of the key "Guide:"

https://docs.bridgecrew.io/docs/ensure-the-storage-container-storing-the-activity-logs-is-not-publicly-accessible

If this is not on the priority list, then I will just skip this policy for now until further notice.
