### ISSUE TITLE
Skip Comment for Dockerfile is valid for the whole file

### ISSUE THREAD

**Issue by jynolen** [bridgecrewio/checkov#2139]
**Describe the bug**
During integration of Dockerfile with checkov we have a multistage Dockerfile (included at ends of issues)
We use ADD to download some artifact from Internet (Denied by CKV_DOCKER_4) but we do some gpg verification so it's ok to use ADD (from our POV)
We added some checkov skip comment after (tried before) lines.
We voluntary forget one to verify behavior. And the line hadn't trigger

**To Reproduce**
1. Download files at https://gist.github.com/jynolen/0bfa1437597548039519bd7e3833bd81
2. Put all .pipline__* file under .pipeline folder
You should have following files
```
<test_folder>/.pipeline/hashicorp.gpg
<test_folder>/.pipeline/tfsec.gpg
<test_folder>/.pipeline/tflint.gpg
<test_folder>/.pipeline/Dockerfile
<test_folder>/.pipeline/requirements.txt
<test_folder>/.pipeline/terraform.provider.downloader.py
<test_folder>/.terraform.lock.hcl
```
3. Run `checkov -d .pipeline` from test_folder

**Expected behavior**
Checkov should have trigger on Dockerfile line 123

**Additional comments**
[https://github.com/bridgecrewio/checkov/blob/master/checkov/dockerfile/parser.py#L33](https://github.com/bridgecrewio/checkov/blob/master/checkov/dockerfile/parser.py#L33)
Show that skip checked are added whenever it occurs in file

**Desktop (please complete the following information):**
 - OS: Linux (Python slim Container)
 - Checkov Version : 2.0.685

Sample:
[https://gist.github.com/jynolen/0bfa1437597548039519bd7e3833bd81](https://gist.github.com/jynolen/0bfa1437597548039519bd7e3833bd81)

**Comment by jynolen** [comment]
Not necessary an issue but needs to be documented IMO

**Comment by gruebel** [comment]
hi @jynolen, thanks for creating the issue.
you are correct, the `skip` comment is valid for the whole file. Just out of curiosity, why don't you use a `RUN` command to download the packages and then unpack it? As far as I can tell you have `tar` and `unzip` installed and depending what the base of the image is, probably also a `wget` or `curl` is included.

**Comment by jynolen** [comment]
It was mainly because we wanted to try some new stuff :p
Moreover [https://github.com/bridgecrewio/checkov/blob/master/checkov/common/checks/base_check.py#L45](https://github.com/bridgecrewio/checkov/blob/master/checkov/common/checks/base_check.py#L45)
I think the test `if skip_info`  is wrong, it should be `self.id == skip_info["id"]`

Right now I got
```
self.id = "CKV_DOCKER_2" 
skip_info = { "id": "CKV_DOCKER_4" }
````
So at the end CKV_DOCKER_2 is skip
