### ISSUE TITLE
Suppression on Terraform Dynamic Blocks

### ISSUE THREAD

**Issue by gargoylexxx** [bridgecrewio/checkov#2156]
New user to CheckOV, and please let me know the proper way i should handle this.

**Background**:
1. Created a custom policy to check AWS Resources Tag, using `supported_resources = ['aws_*']`
2. Created Terraform with dynamic loop blocks, variables from external **.tfvars** file
3. Command used currently in Jenkins:
```
terraform plan -input=false -detailed-exitcode --var-file=envs/\${ENVIRONMENT}.tfvars -out=tfplan
terraform show -json tfplan | jq '.' > tfplan.json 
checkov --config-file config.yaml --external-checks-dir custom_policy/ -f tfplan.json -o junitxml
```

**Issue;**
Found that `aws_route53_resolver_rule_association` didnt expect for a Tag input, and shall skip the custom policy for the AWS resource. Tried to add checkOv in-line suppression, but it didnt work as it is skipped and treated as comment during Terraform plan phase.
```
resource "aws_route53_resolver_rule_association" "association" {
  count = length(var.vpc_id)   <--- List of multiple VPC ID
  vpc_id     = var.vpc_id[count.index]
  resolver_rule_id = aws_route53_resolver_rule.forwarder.id
  # checkov:skip=CUSTOM_RULE_01:"Terraform didnt expect for Tag Input on aws_route53_resolver_rule_association object"
}
```

In my case, how can i skipped new custom policy to skip only on specified resources  `aws_route53_resolver_rule_association` in my case? Any helps and suggestions are very much appreciated here. Is it possible to use external checkOv config file to do the suppression?

**Comment by gruebel** [comment]
hi @gargoylexxx thanks for reaching out, check suppression with Terraform plan doesn't work right out of the box, because the comments are not transported by Terraform to the plan, but you can use an extra flag and most of the time it should work 🙂 
```shell
  --repo-root-for-plan-enrichment REPO_ROOT_FOR_PLAN_ENRICHMENT
                        Directory containing the hcl code used to generate a given plan file. Use with -f.
```

**Comment by gargoylexxx** [comment]
hi @gruebel , thank for the reply. As i am using Jenkins, i am trying to add the flag `--repo-root-for-plan-enrichment` to the checkov command. 

`checkov --config-file config.yaml --external-checks-dir custom_policy/ -f tfplan.json --repo-root-for-plan-enrichment ${WORKSPACE} -o junitxml`

But the custom policy is not skipped for the `aws_route53_resolver_rule_association.association` object.

**Comment by gargoylexxx** [comment]
I believe there is issue on chekcOv file parser on my HCL file. 
It have issue parsing the tags section as example below:

```
resource "aws_route53_resolver_rule" "fwd" {
  name                 = "forwarder-name"
  ......

  tags = "${merge(var.common_tags, map(
    "Name", var.endpoint_name
  ))}"
}
```
As a workaround, i have moved the `aws_route53_resolver_rule_association` section to a new TF file.
