### ISSUE TITLE
Yaml to Python conversion

### ISSUE THREAD

**Issue by bhuvi11** [bridgecrewio/checkov#2159]
I am new to checkov and planning to add custom policies and execute them using checkov.
I went through the documents and i understand that i can just create a Yaml template for the policy, but I need to understand how the yaml file is dynamically converted and run against the codebase?

Can someone help me with that?

**Comment by gruebel** [comment]
Hi @bhuvi11 sure, let me try to give some insights.

We parse the YAML check file and then evaluate the the different `operator` and blocks separated by `and/or`. The most important thing to understand is, that the YAML checks define the passing conditions for the related resources, so it can become a bit more complicated when you try to do some `if` logic.

So, if you are ok with those constraints, then go with YAML checks, if you need more flexibility then you should create a Python check.
