### ISSUE TITLE
CKV_AWS_149 Error on attribute comparison

### ISSUE THREAD

**Issue by jkesterson** [bridgecrewio/checkov#2164]
**Describe the issue**
This check checks if resource config does not contain 'kms_key_id' (if not kms_key_id). If a kms key is not configured for a secretmanager secret, the config contains 'kms_key_id': [None], causing the error 'TypeError: argument of type 'NoneType' is not iterable'.

**FIX**
This can be fixed by adding an or in the comparison like so:
BEFORE:      if not kms_key_id:
AFTER:         if not kms_key_id or kms_key_id == [None]:

**Version (please complete the following information):**
 - Checkov Version 2.0.658

**Additional context**
![image](https://user-images.githubusercontent.com/72165155/147779883-6e50fe81-0add-49db-b771-4d6acdc3ae07.png)

![image](https://user-images.githubusercontent.com/72165155/147780177-5931ef09-75bb-4ced-b881-e67cc930244e.png)

**Comment by nimrodkor** [comment]
Hi @jkesterson !
Yes, that can happen when running from a plan file. You solution looks good, we'd appreciate a contribution if you're up for it!

**Comment by jkesterson** [comment]
@nimrodkor I can get a PR in after the holidays, no problem.
