### ISSUE TITLE
Custom Policy

### ISSUE THREAD

**Issue by bhuvi11** [bridgecrewio/checkov#2176]
I am trying to write custom policies using YAML file and I see the need to specify the resource_type and attributes.
Is there a list of predefined resources and their attributes that can be referred?

**Comment by gruebel** [comment]
depending on what framework you want to check, we support all Terraform, CloudFormation and Kubernetes resource types and their attributes, we don't apply any validation of values you put in. We just check if the resource type you chose has the attribute you chose in the files you check with `checkov` 🙂 

Examples:
https://github.com/bridgecrewio/checkov/blob/5ed21e0e1060e6871363167670df34288caf79bd/checkov/terraform/checks/graph_checks/aws/APIProtectedByWAF.yaml
https://github.com/bridgecrewio/checkov/blob/5ed21e0e1060e6871363167670df34288caf79bd/checkov/kubernetes/checks/graph_checks/k8s/AllowedCapabilities.yaml
https://github.com/bridgecrewio/checkov/blob/master/checkov/cloudformation/checks/graph_checks/aws/LambdaFunction.yaml

**Comment by eurogig** [comment]
Off the back of this I'll make a few changes to our docs to make it clearer on this page (https://www.checkov.io/3.Custom%20Policies/YAML%20Custom%20Policies.html).
We use 'aws_redshift_cluster' as an example 'resource_types' where something more obvious would have been useful like 'aws_s3_bucket' with the attribute 'acl' and showing the reference terraform block like:
`resource "aws_s3_bucket" "financials" {
  bucket        = "${local.resource_prefix.value}-financials"
  acl           = "public-read"
  force_destroy = true
}`
Anton gave some great pre-made examples above for all IaC types.

**Comment by gruebel** [comment]
@bhuvi11 any attribute the resource support can be used, so if you are looking for AWS Terraform resource attributes you can check the official [Terraform AWS provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)
