### ISSUE TITLE
[Question] Is there anyway to disable inline skips?

### ISSUE THREAD

**Issue by jmeredith16** [bridgecrewio/checkov#2179]
**Describe the issue**
I run Checkov as part of CI and would like to block downstream users from using the inline skip functionality.

Basically I don't want users to be able to use, for example, `#checkov:skip=CKV_AWS_20:The bucket is a public static content host` when running we run Checkov against the code in CI.

**Examples**
`#checkov:skip=CKV_AWS_20:The bucket is a public static content host` added to the codebase being scanned.

I'm hoping there's a flag similar to `checkov --disable-inline-skips` that would ignore the above line, but I don't see anything in the docs.

**Version (please complete the following information):**
 - Checkov Version 2.0.706

**Comment by gruebel** [comment]
Currently it is not possible to do with setting a flag, but it is possible to implement it 😄 

To clarify, you would like to disable all skip comments or only specific ones?

**Comment by jmeredith16** [comment]
I'd like to add a flag to do that then if you are open to it.

I want to disable all skip comments in the target being scanned. My reasoning is that in CI I need to enforce my company's Checkov policy. If users are able to just skip checks inline in their own projects, they could easily bypass our controls.

**Comment by schosterbarak** [comment]
Hey @jmeredith16 this feature is available in the Bridgecrew SaaS solution or Prisma cloud. See example at: https://docs.bridgecrew.io/changelog/suppression-rules-improvements#developer-suppressions
 Bridgecrew you are welcome to [signup](https://www.bridgecrew.cloud/login/signUp) and you can start using it for [free](https://bridgecrew.io/pricing)

**Comment by williamsjo-reninc** [comment]
So you implement a security loophole in the tool, then force users to pay up to fix it?

**Comment by williamsjo-reninc** [comment]
If you're using GitHub actions, just add another step at the end of the Checkov job:

```
      - name: Prevent Checkov skips
        run: |
          if grep -r 'checkov:skip' .; then
            echo 'Found comments disabling Checkov alerts. Remove them and try again.'
            exit 1
          else
            echo 'No checkov:skip comments found.'
            exit 0
          fi
        if: success() || failure()
```
