### ISSUE TITLE
OneOf conditional checking based on the configuration of multiple like-resources

### ISSUE THREAD

**Issue by jasonvangundy** [bridgecrewio/checkov#2196]
**Describe the issue**
I have more of a question and am looking for guidance, potentially on contributing back to checkov.  My team and I are trying to implement a graph-based check that fails if "one of" a specifically configured resource does not exist.   The current concrete example is:  

> If a VPC is present, then at least one VPC Flow Log must be present that is configured with a LogDestination of s3, and the destination path must be a specific centralized bucket. 

As far as I can tell there isn't a way I can write this sort of check.  We have explored a yml graph-based approach as well as pondered how we could write this in python proper.  It seems to me that the yml logic diverges from the available to-be-subclassed python classes for writing checks.  In the yaml case we have access to the graph and can write checks based on connected resources, but (again afaict) don't have the ability to say "one of _n_ like resource types must be configured a certain way".  On the python side we could accomplish the latter, but only have access to one resource at a time, and don't know how many we might encounter.

Is my interpretation of current state accurate?

I can think of two possible ways checkov might support this, but would greatly appreciate some input. 

1. implement a solver (e.g. `OneOfSolver` that operates like https://github.com/bridgecrewio/checkov/blob/master/checkov/common/checks_infra/solvers/complex_solvers/and_solver.py but expects `any()` to pass.

2. somehow offer another implementation or variation on `scan_resource_conf` that provides greater context than it does today.  for example maybe all instances of configured `resource_types` for a check could be passed into the scan function.  or the rest of the template could be provided as context.  something like that. 

Absolutely welcome alternate thoughts and approaches.  If there is a potential desired path here details would be great as my team and I would consider PRing the functionality.

Thanks!

**Examples**
An example template that illustrates the situation I described above.  1 vpc, 2 flow logs, one of which meet a "check passed" criteria.  However, the `team-flow-log` would cause a failure without the ability to define `OneOf` conditional criteria.

```
{
    "Resources": {
      "VPCB9E5F0B4": {
        "Type": "AWS::EC2::VPC"
      },
      "team-flow-log": {
        "Type": "AWS::EC2::FlowLog",
        "Properties": {
          "ResourceId": {
            "Ref": "VPCB9E5F0B4"
          },
          "ResourceType": "VPC",
          "TrafficType": "ALL",
          "LogDestination": "arn:aws:s3:::my-teams-bucket",
          "LogDestinationType": "s3"
        }
      },
      "company-required-flow-log": {
        "Type": "AWS::EC2::FlowLog",
        "Properties": {
          "ResourceId": {
            "Ref": "VPCB9E5F0B4"
          },
          "ResourceType": "VPC",
          "TrafficType": "ALL",
          "LogDestination": "arn:aws:s3:::company-required-bucket",
          "LogDestinationType": "s3"
        }
      }
    }
  }
```

**Version (please complete the following information):**
 - Checkov Version - latest

**Additional context**
N/A

**Comment by NoaAzoulay** [comment]
Hi @jasonvangundy  :)
so I would like to better understand few things : 
1. Does the bucket should be with a specific arn or we want to be able to choose from a set of different arn’s ?
2. In the example you provided - which resource would you like to fail / pass ? (VPC? flow log? Both?)
3. Did you try using the or complex solver?
4. It will be great if you can add more details about what you meant in : "one of n like resource types must be configured a certain way"

thanks :)
