### ISSUE TITLE
not scanning kubernetes yaml files

### ISSUE THREAD

**Issue by ManasaVaishnaviTinnaluriTR** [bridgecrewio/checkov#2203]
2022-01-13 12:52:52,477 [MainThread ] [DEBUG] Cannot read file contents: helm/x/y/z/test-connection.yml - is it a yaml?

files are skipped from being scanned?

webhook:

name: scanning helm
uses: bridgecrewio/checkov-action@v12.641.0
with:
directory: helm
framework: kubernetes
download_external_modules: false
log_level: DEBUG

**Comment by gruebel** [comment]
Hi @ManasaVaishnaviTinnaluriTR can you share that YAML file? Otherwise we can't really help much.
