### ISSUE TITLE
[BUG] `checkov` depends on incorrect version range of CycloneDX libraries - `checkov` CycloneDX output is broken

### ISSUE THREAD

**Issue by madpah** [bridgecrewio/checkov#2205]
`checkov` defines it's dependencies on CycloneDX libraries as follows:

_setup.py_:
```
...
"cyclonedx-python-lib>=0.11.0",
...
```

This means `checkov` is now pulling in latest version >= 1.0.0 which has breaking changes (hence the major version bump), which breaks `checkov`'s CycloneDX integration.

There are two tasks:
- [ ] Quickly correct `checkov`'s current dependency definition to be  >= 0.11.0 and < 1.0.0 - #2206 
- [ ] Adopt the breaking changes which provides CycloneDX 1.4 support (i.e. `cyclonedx-python-lib>=1.0.0`)

**Comment by nimrodkor** [comment]
Hi @madpah !
We'd appreciate a contribution here, if you're up for it. You've identified the problem correctly

**Comment by madpah** [comment]
PR coming shortly @nimrodkor !

**Comment by madpah** [comment]
https://github.com/bridgecrewio/checkov/pull/2206 raised @nimrodkor
