### ISSUE TITLE
Jenkins use docker image instead of installing Checkov

### ISSUE THREAD

**Issue by HariSekhon** [bridgecrewio/checkov#2207]
**Describe the issue**
I think the Jenkins documentation is old, why would you install checkov instead of just using the bridgecrew/checkov docker image directly?

https://www.checkov.io/4.Integrations/Jenkins.html

**Examples**
This can be done via docker agent stanza, or better, via a Kubernetes agent pod, such as:

https://github.com/HariSekhon/Kubernetes-configs/blob/f4804dcc95a0392871b04c3651c3f5b43155eb7b/jenkins-agent-pod.yaml#L269

which you can just exec into using `container('checkov'){ <checkov commands> }` for a given set of steps in your pipeline.

**Comment by schosterbarak** [comment]
thanks @HariSekhon . we would love a contribution at: https://github.com/bridgecrewio/checkov/blob/master/docs/4.Integrations/Jenkins.md

**Comment by HariSekhon** [comment]
I've just pushed a Checkov jenkins shared library function and Jenkinsfile containerized (Kubernetes) example to my [Jenkins](https://github.com/HariSekhon/Jenkins) repo which you can use:

[Jenkinsfile](https://github.com/HariSekhon/Jenkins/blob/f35340ce528ec843910d8abfa446954a9ab551a0/Jenkinsfile#L493)

[vars/checkov.groovy](https://github.com/HariSekhon/Jenkins/blob/master/vars/checkov.groovy)
