### ISSUE TITLE
CKV_AZURE_80 - dotnet_framework_version with v6.0 fails

### ISSUE THREAD

**Issue by Dunklas** [bridgecrewio/checkov#2209]
**Describe the issue**
Currently .NET 6.0 is the latest LTS version. However, CKV_AZURE_80 expects that latest version is v5.0.

**Examples**
```
resource "azurerm_app_service" "searchApi" {
  ...
  site_config {
    dotnet_framework_version = "v6.0"
  }
}
```
There should be no warning for CKV_AZURE_80 with the above configuration.

**Version (please complete the following information):**
 - Checkov Version 2.0.717

**Comment by gruebel** [comment]
@Dunklas thanks for reporting 💪 you are totally right, since the new 6.0 version was released it a few months ago, this check should be adjusted. Do you want to try and fix it?

**Comment by Dunklas** [comment]
Sure thing! I'll look into it during the weekend :)

**Comment by gruebel** [comment]
to make your life easier, you will need to adjust those files
https://github.com/bridgecrewio/checkov/blob/9f448d714432d3118a00a453c76dd8762aa284ab/checkov/terraform/checks/resource/azure/AppServiceDotnetFrameworkVersion.py
https://github.com/bridgecrewio/checkov/blob/9f448d714432d3118a00a453c76dd8762aa284ab/tests/terraform/checks/resource/azure/test_AppServiceDotnetFrameworkVersion.py
