### ISSUE TITLE
Bump jsonschema to the latest version and make it compatible with versions 4.X

### ISSUE THREAD

**Issue by manuel-sommer** [bridgecrewio/checkov#2227]
**Describe the issue**
Right now jsonschema is set to version 3.0.2. Upgrade it to the latest version and enable compatibility with newer versions. 

**Version (please complete the following information):**
Checkov version 2.0.727

**Additional context**
I have another dependency which uses jsonschema 4.X.

**Comment by manuel-sommer** [comment]
bump, still present

**Comment by RachelleJanssen** [comment]
I'm experiencing bugs in the jsonschema package, but checkov is preventing me from upgrading to 4.x

**Comment by dc232** [comment]
When we build our containers we get conflicts when integrating other packages

```
The conflict is caused by:
    checkov 2.2.201 depends on jsonschema<4.0.0 and >=3.0.2
    semgrep 1.2.1 depends on jsonschema~=4.6
```

Would it be possible to upgrade jsonschema to latest?
