### ISSUE TITLE
CKV_AZURE_98: Fails on new network profile

### ISSUE THREAD

**Issue by zendassie** [bridgecrewio/checkov#2229]
**Describe the issue**
Tests against the Terraform plan file fails, because the network profile is being created as part of the same workspace. (See below).
Check [CKV_AZURE_98](https://docs.bridgecrew.io/docs/ensure-that-azure-container-container-group-is-deployed-into-virtual-network) should cater for `(known after apply)` since the rule will be satisfied as soon as the infrastructure has been applied.

**Example**
Below was the TF plan which Checkov tested against*. The `network_profile_id` is there, but not yet applied.
```
+ resource "azurerm_container_group" "cg" {
      + exposed_port        = (known after apply)
      + fqdn                = (known after apply)
      + id                  = (known after apply)
      + ip_address          = (known after apply)
      + ip_address_type     = "Private"
      + location            = "westeurope"
      + name                = "example-name"
      + network_profile_id  = (known after apply)
      + os_type             = "Windows"
      + resource_group_name = "example_rg"
      + restart_policy      = "Always"
```

The `ANY_VALUE` field in `checkov\terraform\checks\resource\azure\AzureContainerGroupDeployedIntoVirtualNetwork.py` should probably change to cater for resources not yet created which will be applied:
![image](https://user-images.githubusercontent.com/2021922/149898867-0eef86d8-ee25-4c5e-91ea-bdd710e0a527.png)

**Version:**
 - Checkov Version 2.0.727 (PyPI package)

> \* excluding anonymization fields

**Comment by nimrodkor** [comment]
This is true for many plan-based checks, as today checkov does not take into account the `after_unknown` section of the plan file. Fix should be an extension to the [plan file parser](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/plan_parser.py#L122)

@schosterbarak - did we run into this issue in the past?
