### ISSUE TITLE
Github Action ignores baseline file

### ISSUE THREAD

**Issue by regel** [bridgecrewio/checkov#2272]
**Describe the issue**

Running checkov in github action (runs docker image bridgecrew/checkov:2.0.756) ignores the baseline, outputs all errors, and exits with non-zero status code.

**Test 1**

The path to the baseline file is defined in checkov config file. Test is KO. Checkov runs, but reports all errors, as-if the baseline did not exist, and Github action fails due to non-zero status.

Content of the config file is:

```
branch: master
baseline: charts/cardano/.checkov.baseline
directory:
- charts/cardano
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- helm
output:
- github_failed_only
skip-check:
- CKV_K8S_21
- CKV_K8S_10
- CKV_K8S_11
- CKV_K8S_12
- CKV_K8S_13
skip-path:
- /cardano/templates/tests/*
- /redis/*
```

Github Action [Logs](https://github.com/regel/cardano-charts/runs/4929499567?check_suite_focus=true) (truncated):

```
running checkov on directory: charts/cardano
checkov -d charts/cardano   --quiet  --output sarif   --config-file charts/cardano/.checkov    

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.756 
helm scan results:

Passed checks: 0, Failed checks: 24, Skipped checks: 0
```

**Test 2**

The path to the baseline is set in github action YAML settings. Test is KO. Checkov runs, but reports all errors, as-if the baseline did not exist, and Github action fails due to non-zero status.

Github Action [Logs](https://github.com/regel/cardano-charts/runs/4929182246?check_suite_focus=true) (truncated): 

```
running checkov on directory: charts/cardano
checkov -d charts/cardano   --quiet  --output sarif   --config-file charts/cardano/.checkov    --baseline charts/cardano/.checkov.baseline

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.756 
helm scan results:

Passed checks: 0, Failed checks: 24, Skipped checks: 0
```

**Test 3 (running the command line locally)**

```
$ checkov -d charts/cardano --baseline charts/cardano/.checkov.baseline --config-file charts/cardano/.checkov
| check_id   | file   | resource   | check_name   | guideline   |
|------------|--------|------------|--------------|-------------|


---


$ checkov --version
2.0.735
```

**Comment by nimrodkor** [comment]
Hey @regel !
Thanks for reporting. I wonder if it is a paths issue. Are the paths of the failing resources in the report the same as the paths in the baseline file?

**Comment by regel** [comment]
> Hey @regel ! Thanks for reporting. I wonder if it is a paths issue. Are the paths of the failing resources in the report the same as the paths in the baseline file?

Hey @nimrodkor  , thanks. You're right, the helm 'RELEASE-NAME' is lower case in github actions but upper case in the baseline file. I will try to replace to see if that's solving the issue.

Example of path in github actions log:

```
Check: CKV_K8S_15: "Image Pull Policy should be Always"
	FAILED for resource: CronJob.default.release-name-topology-updater-push
Error: 	File: /cardano/templates/topology-updater-push.yaml:3-120
	Guide: https://docs.bridgecrew.io/docs/bc_k8s_14
```

The baseline file contains:

```
        {
            "file": "/cardano/templates/topology-updater-push.yaml",
            "findings": [
                {
                    "resource": "CronJob.default.RELEASE-NAME-topology-updater-push",
                    "check_ids": [
                        "CKV_K8S_15",
                        "CKV_K8S_20",
                        "CKV_K8S_31",
                        "CKV_K8S_35",
                        "CKV_K8S_43"
                    ]
                }
            ]
        },
....
```

**Comment by regel** [comment]
Hey @nimrodkor , it was indeed a lower / upper-case issue in the baseline file. Thanks for your help, we can close the issue.

The 'release-name' lower-case output surprised me. I've always seen this output upper-case coming from Helm.

**Comment by solita-mao** [comment]
github restric access to environment
