### ISSUE TITLE
Summary Only Output

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [bridgecrewio/checkov#2289]
**Describe the issue**
For my usecase, the output is far too verbose. I only need the summary numbers and I'll push those into a backend of my choosing.
I would like to output **only** the summary JSON block:

```
"summary": {
        "passed": 10,
        "failed": 3,
        "skipped": 0,
        "parsing_errors": 0,
        "resource_count": 0,
        "checkov_version": "2.0.765"
}
```

**Comment by schosterbarak** [comment]
@Dynatrace-Adam-Gardner  can you elaborate on the usecase and why fetching this data from the json output isn't going to work?

**Comment by Dynatrace-Adam-Gardner** [comment]
I don't want or need the additional output. I don't want to include another dependency `jq` just to process the JSON. If this isn't currently possible, that's fine, but assume this is an enhancement request :)
