### ISSUE TITLE
whitelist CKV_AWS_59 for public unauthenticated APIs

### ISSUE THREAD

**Issue by sachinguptahsc** [bridgecrewio/checkov#2292]
In our serverless deployment, We have some APIs which are un-authenticated and which are used by all users. (An example of those API could be user-registration).
For those APIs CKV_AWS_59 fails as we are not adding any authentication mechanism.

I know, we can add API-Key for those APIs but API-Keys are not designed for this use-case. They are generally used in internal (machine to machine) communication.

We wanted to know, Is there a way available to bypass/whitelist this check.
We are using latest Checkov version.

**Comment by nimrodkor** [comment]
Hey @sachinguptahsc ! Please take a look at this page in the docs:

**Comment by nimrodkor** [comment]
https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html

**Comment by sachinguptahsc** [comment]
Hi @nimrodkor,
Thanks for reply. We have already checked mentioned URL. But it didn't work for our case, as we are using serverless deployment. 
In the case of serverless deployment, cloud formation template is generated by serverless framework only. Is there any way available to add suppression in serverless.yml too ?
