### ISSUE TITLE
update defaults for branch from master to main

### ISSUE THREAD

**Issue by tkishel** [bridgecrewio/checkov#2295]
**Describe the issue**

Given that the default branch name has changed from `master` to `main`:

https://github.com/github/renaming

Should the default for `--branch` be changed as well?

https://github.com/bridgecrewio/checkov/blob/master/checkov/main.py#L347

**Comment by nimrodkor** [comment]
Sounds good to me. Want to contribute that change?

**Comment by tkishel** [comment]
I don't have enough of an understanding of the potential impact of this change to the internal workflows of the project (aka: I know enough to be dangerous ) and have not set up all of the testing in the CONTRIBUTING document. So, yes, but not yet. Also, this may be a change to hold back for the next major or minor release, rather than a patch?
