### ISSUE TITLE
Checkov showing non-compliance of certain parameters even with right expected values.

### ISSUE THREAD

**Issue by charanreddypruthvi** [bridgecrewio/checkov#2298]
**Describe the issue**
CKV_AZURE_41/Ensure that the expiration date is set on all secrets.
This check should pass if we provide the expiration date of Key Vault secret which is not happening .

**Examples**
Below is the default setting of the expiration date on secrets that are being created in Azure Kay Vault.
expiration_date = timeadd(formatdate("YYYY-MM-DD'T'00:00:00Z", timestamp()), "2191h")

**Version (please complete the following information):**
 - Checkov Version - 2.0.679

**Additional context**

**Comment by nimrodkor** [comment]
I believe the issue is we don't support these operators yet (`timeadd`, `formatdate` etc) - hence checkov doesn't know how to handle it
