### ISSUE TITLE
Fails to find check skip when 2 resources are skipping the same check

### ISSUE THREAD

**Issue by toast-gear** [bridgecrewio/checkov#2301]
**Describe the issue**
The skip mechanism seems to struggle if you are skipping duplicate checks that are indentical in the same file in 2 in resources:

**Examples**

Even though the `CKV_SECRET_6` check is set to be skipped by both resources, the check fails on the second resource when configured like this in this order in the file:
```hcl
resource "github_actions_organization_secret" "deploy_webhook_token" {
  #checkov:skip=CKV_SECRET_6:This secret is happy to be high entropy
  secret_name     = "DEPLOYMENT_METRICS_DEPLOY_WEBHOOK_TOKEN"
  visibility      = "private"
  plaintext_value = data.aws_ssm_parameter.deploy_webhook_secret.value
}

resource "github_actions_organization_secret" "deploy_webhook_url" {
  #checkov:skip=CKV_SECRET_6:This secret is happy to be high entropy
  #checkov:skip=CKV_GIT_4:it's not sensitive
  secret_name     = "DEPLOYMENT_METRICS_DEPLOY_WEBHOOK_URL"
  visibility      = "private"
  plaintext_value = "${local.webhook_url}/deploy-webhook"
}
```

If I change the order of the check skip so the order in the second resource doesn't match the order in the first resource then it works, like this:

```hcl
resource "github_actions_organization_secret" "deploy_webhook_token" {
  #checkov:skip=CKV_SECRET_6:This secret is happy to be high entropy
  secret_name     = "DEPLOYMENT_METRICS_DEPLOY_WEBHOOK_TOKEN"
  visibility      = "private"
  plaintext_value = data.aws_ssm_parameter.deploy_webhook_secret.value
}

resource "github_actions_organization_secret" "deploy_webhook_url" {
  #checkov:skip=CKV_GIT_4:it's not sensitive
  #checkov:skip=CKV_SECRET_6:This secret is happy to be high entropy
  secret_name     = "DEPLOYMENT_METRICS_DEPLOY_WEBHOOK_URL"
  visibility      = "private"
  plaintext_value = "${local.webhook_url}/deploy-webhook"
}
```

**Version (please complete the following information):**
```
$ checkov -v
2.0.769
```

**Comment by gruebel** [comment]
Hi @toast-gear thanks for creating the issue.

The secrets checks work a bit different in regards of skipping them, you need to add the skip comment directly next to the violating line, like it is described in the docs https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html#secrets-example

**Comment by toast-gear** [comment]
aaahhhh that explains why the re-order worked then. I guess this isn't a bug then.

**Comment by gruebel** [comment]
great, that it makes now sense 😄
