### ISSUE TITLE
python hcl2 dependancy changes

### ISSUE THREAD

**Issue by Fran-Rg** [bridgecrewio/checkov#2317]
**Describe the issue**
One of the module dependancy is 'bc-python-hcl2':
https://github.com/bridgecrewio/checkov/blob/ee9668d826565f227fbf58db59f8abc791dbf471/Pipfile#L35

Unfortunately this module has renamed to "python-hcl2":
https://pypi.org/project/bc-python-hcl2/
->
https://pypi.org/project/python-hcl2/
Both are exactly the same but the readme points to "pip3 install python-hcl2"

Additionally that would requires to set an upper boundary on the dependency python-hcl2

**Additional context**
This will avoid some difficult to find module conflicts

**Comment by Fran-Rg** [comment]
Being honest I think the problem also comes from the source library.

I think the main issues it causes on higher version is on:
https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/parser.py#L243

List can be an empty list.

**Comment by gruebel** [comment]
hi @Fran-Rg we created in past a forker, due to internal code relying heavily on the old behaviour of the original package, therefore changing this dependency will need quite a lot of refactoring and will break the current customizations of our users.

So, what exactly is your issue, you need the newer version of the original package?

**Comment by Fran-Rg** [comment]
I've packed checkov with another tool that was using the other python-hcl2 version. I had a lot of trouble to find out where the problem came from. I wish the fork had renamed the import to "bchl2" thus no name conflict...

I don't know if there's something that can be done on your side to be honest.

**Comment by Fran-Rg** [comment]
The most sensible solution I could think of is to have a little disclaimer in the requirements.txt about this possible conflict

**Comment by gruebel** [comment]
We are currently in a state that even with renaming our `hcl2` package fork, it won't work next to the original, because we upgraded the underlying package `lark` to the latest version. Therefore I'm gonna close this issue, because we won't go back anymore or try to stay in sync.
