### ISSUE TITLE
CKV_AWS_40: failure even when not setting users

### ISSUE THREAD

**Issue by paulolieuthier** [bridgecrewio/checkov#2318]
**Describe the issue**
The check fails when executing checkov on Terraform plan's JSON output.

**Examples**
```
resource "aws_iam_policy_attachment" "attachment" {
  ...
  roles = [...]
  # no users
}
```
JSON:
```
{
  "address": "aws_iam_policy_attachment.attachment",
  ...
  "values": {
    ...
    "roles": [
      "data-analytics@eng-0"
    ],
    "users": []
  },
...
```
The `users` field is set to `[]` in JSON, and the [check implementation](https://github.com/bridgecrewio/checkov/blob/e2538c48df14363d6ed46e5b838e19cc71ba6cbf/checkov/terraform/checks/resource/base_resource_negative_value_check.py#L39-L53) doesn't handle this scenario correctly:

https://github.com/bridgecrewio/checkov/blob/e2538c48df14363d6ed46e5b838e19cc71ba6cbf/checkov/terraform/checks/resource/base_resource_negative_value_check.py#L39-L53

**Version (please complete the following information):**
```
> checkov --version
2.0.780
```

I saw there are tests for the check implementation, but only targeting Terraform source files. Are there tests targeting JSON output from Terraform plan?

**Comment by gruebel** [comment]
hi @paulolieuthier thanks for raising this issue, I fixed that for other tests, but didn't expect it was an issue here too. A new version with the fix should be out by tomorrow.

**Comment by paulolieuthier** [comment]
Nice! Looking forward to the release.
