### ISSUE TITLE
Skip comments for custom policies do not work

### ISSUE THREAD

**Issue by mikeurbanski1** [bridgecrewio/checkov#2329]
**Describe the issue**
Adding a skip comment using the policy ID for a custom policy from the Bridgecrew platform does not result in that violation being skipped.

**Examples**

I have a policy in the platform for S3 buckets that fails if `arn` is not present (so, it always fails).

```
resource "aws_s3_bucket" "x" {
  # checkov:skip=mikegithub_AWS_1643124345239: ADD REASON
  bucket        = "x"
}
```

If I scan this bucket using my API key, I still get an error for the custom policy

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]: 2.0.782

**Additional context**

**Comment by gruebel** [comment]
I think PR #2181 will fix this issue

**Comment by mikeurbanski1** [comment]
Oops, you right. I ended up making my own and adding a test, which the other one was missing, and it was trivial anyways
