### ISSUE TITLE
Shielded GKE nodes is default as of provider version 4.0.0

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/checkov#2341]
**Describe the issue**
I wouldn't expect to get the alert if not defined explicitly. 

**Examples**
https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.0.0

**Version (please complete the following information):**
 - Checkov Version 2.0.780

**Comment by gruebel** [comment]
hi @brettcurtis thanks for creating the issue.

looks like we should adjust our check to respect the new default behaviour. Do you want to do the change and contribute back to `checkov`?

**Comment by brettcurtis** [comment]
Let me look at the guidelines and see if I can figure it out!
