### ISSUE TITLE
Checkov crashes when testing main.tf

### ISSUE THREAD

**Issue by kmroz0991** [bridgecrewio/checkov#237]
**Describe the bug**
I try to run checkov against main.tf and get a python exception error show below.

**To Reproduce**
1. Install checkov version 1.0.255
2. Run checkov -f main.tf
3. See error

**Expected behavior**
It should give a scan of passing or failing resources

**Screenshots**
![image](https://user-images.githubusercontent.com/11996283/80405513-56b73b00-8888-11ea-9a76-cd515a3bd864.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Checkov Version 1.0.255

**Additional context**
It scans configuration.tf without any issues.

**Comment by schosterbarak** [comment]
@kmroz0991  can you please add the `main.tf` content?

**Comment by kmroz0991** [comment]
@schosterbarak some of it is kind of sensitive.

**Comment by kmroz0991** [comment]
resources include SG, "aws_msk_configuration", "aws_msk_cluster", "aws_security_group_rule", "random_uuid"

**Comment by kmroz0991** [comment]
terraform validate and plan confirms the file is configured correctly

**Comment by kmroz0991** [comment]
sorry , there was a bad code within the file. Closing as this is a non issue.
