### ISSUE TITLE
Add ability to select checks to run 

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#238]
**Is your feature request related to a problem? Please describe.**
I would like to be able to find the output of a specific check without looking at all others.  It would be good for checkov to have a flag to specify which checks you want to run rather than executing all of them. 

An alternative request I could see is to exclude specific checks from a run.  

**Describe the solution you'd like**
Add a '-c <check>' flag where I can specify a single check or multiple checks that are comma separated  

If going the exclude route, that would probably be a different flag.  

**Describe alternatives you've considered**

**Additional context**

**Comment by nimrodkor** [comment]
Related to #88 - this feature could resolve both issues

**Comment by schosterbarak** [comment]
done: https://github.com/bridgecrewio/checkov/pull/255
