### ISSUE TITLE
ImportError: cannot import name 'SecretsCollection' from 'detect_secrets'

### ISSUE THREAD

**Issue by ocofaigh** [bridgecrewio/checkov#2384]
**Describe the issue**
When I install checkov using `python3 -m pip install checkov` and then try to execute `checkov` I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 33, in <module>
    from checkov.common.util.docs_generator import print_checks
  File "/usr/local/lib/python3.9/site-packages/checkov/common/util/docs_generator.py", line 16, in <module>
    from checkov.secrets.runner import CHECK_ID_TO_SECRET_TYPE
  File "/usr/local/lib/python3.9/site-packages/checkov/secrets/runner.py", line 7, in <module>
    from detect_secrets import SecretsCollection
ImportError: cannot import name 'SecretsCollection' from 'detect_secrets' (/usr/local/lib/python3.9/site-packages/detect_secrets/__init__.py)
```

However, if I install with Brew I do not face this issue.

**Desktop (please complete the following information):**
 - OS: Mac 12.1
 - Checkov Version: 2.0.817

**Additional context**
I have tried a few different versions, but always reproduce. I even face the same issue using `Debian GNU/Linux 11 (bullseye)`. Am I doing something wrong?

**Comment by gruebel** [comment]
hi @ocofaigh thanks for creating the issue.

This a very strange error, can you run following command and add your output here.
```shell
$ python -m pip show detect_secrets
Name: detect-secrets
Version: 1.1.0
...
```
I have the suspicion that `pip` installs an old version of that library.

**Comment by ocofaigh** [comment]
I actually have an ibm version of detect_secrets installed with pip (`python3 -m pip install -q --upgrade "git+https://github.com/ibm/detect-secrets.git@0.13.1+ibm.47.dss#egg=detect-secrets`. Could that be the problem?

```
$ python3 -m pip show detect_secrets
Name: detect-secrets
Version: 0.13.1+ibm.47.dss
Summary: Tool for detecting secrets in the codebase
Home-page: https://github.ibm.com/Whitewater/whitewater-detect-secrets
Author: 
Author-email: 
License: UNKNOWN
Location: /usr/local/lib/python3.9/site-packages
Requires: boxsdk, packaging, pyyaml, requests
Required-by: 
```

**Comment by ocofaigh** [comment]
Are you proposing for checkov install to overwrite that exact version of detect_secrets? I still need to be able to use that version of ibm detect secrets directly (outside of checkov). Is that use case possible?

**Comment by gruebel** [comment]
yeah, that would be result. then you can run `checkov` with skipping the `secrets` framework, like that
```shell
checkov -d . --skip-framework secrets
```
and hopefully it will work.

**Comment by ocofaigh** [comment]
Hi @gruebel just wondering if you have come u with any ideas on above? Thanks

**Comment by gruebel** [comment]
currently you can only move to either run `checkov` via our Docker image or use `pipx` to install it in a dedicated virtual env.

**Comment by gruebel** [comment]
yeah, pre-commit hook also works, because it creates a dedicated virtual env and installs all the dependencies there, also the latest version of `detect-secrets`. Same goes for brew installation it creates a virtual env with all needed dependencies, which are not shared with your global python env.
