### ISSUE TITLE
Scanning terraform plan/json files for Rancher

### ISSUE THREAD

**Issue by johnqa** [bridgecrewio/checkov#2385]
I have an on premise Rancher kubernetes cluster provisioned with Terraform and I am trying to use checkov to scan the terraform plan for it.

What I see is that  checkov ignores the json files and returns nothing.

Is it even possible to scan such files with checkov?

**Comment by gruebel** [comment]
yes, it is possible, but we don't have any checks for the rancher provider at the moment, that's why you don't see any results probably

**Comment by johnqa** [comment]
Thank you for you answer. I wish that supported providers were written in documentation (or maybe I missed that info), as I spent a day trying to make it work.

**Comment by gruebel** [comment]
sure, we have here a list of all the resources, which have a check related to it https://github.com/bridgecrewio/checkov/blob/master/docs/5.Policy%20Index/terraform.md

**Comment by schosterbarak** [comment]
@johnqa here is contribution guidelines on how to contribute a new provider: https://www.checkov.io/6.Contribution/Contribute%20New%20Terraform%20Provider.html

**Comment by JamesWoolfenden** [comment]
I spoke to Rancher directly yesterday. Hopefully they will collaborate on this.
