### ISSUE TITLE
CKV_AWS_103 - Mentioned Checkov Checks producing an Exception, when the Listener protocol is HTTP (ALB).

### ISSUE THREAD

**Issue by karthickmuthuraj** [bridgecrewio/checkov#2441]
Background of the Issue :  

We have been using mentioned Checkov inbuilt checks/policy ID (CKV_AWS_103/ BC_AWS_GENERAL_43) for connection requests in AWS Load balancer.  it was working fine when application team using the Module, "aws_lb_listener" "redirect" will only enable when application team users "HTTPS" Protocol. The particular issue is being presented when we attempt "HTTP" Protocol (Development Environment)

Sample Module snippet (AWS Load Balancer Listener ) (Re-direct Action) :- 

resource "aws_lb_listener" "redirect_http_listeneter" {
load_balancer_arn = aws_lb.front_end.arn
port = "80"
protocol = "HTTP" 
}

default action {
   type = "redirect"

redirect {
  port =  "443"
  }
}
}

ISSUE :- 
Exception Occur :- [If application team used the protocol HTTP]   

Exception message sample 
"[MainThread][ERROR] Failed to run check: Ensure the load balancer is using TLS1.2 for configuration:{'alpn_policy':[None],'arn':['arn:aws:elasticloadbalancing:**********:listener/app/dev-opsmanager-ec2-alb/******/*****],'certicate_arn':[None], 'default_action':

In bridgecrewio github,  [ checkov/terraform/checks/resource/aws/AppLoadBalancerTLS12.py ]
supports only HTTPS and it not producing any proper results, if we application team using HTTP.  So require your support to tweak globally in the in-built check ID. 

checkov version : 2.0.704

kindly let me know any other additional inputs require from our end.

**Comment by nimrodkor** [comment]
Hey @karthickmuthuraj !

I do believe the attribute should be `default_action`, not `default action`. Does that work for you?

**Comment by karthickmuthuraj** [comment]
Yes, mistake at my end. it should be default_action.

**Comment by karthickmuthuraj** [comment]
Additional exception message,
I think the root cause is "[[]]" as a "re-direct" value. 

'default_action': [{'authenticate_cognito':[[]]},
                            'authenticate_oidc':[[]],
                            'fixed_response':[[]],
                            'forward:'[[]],
                            'order': [1],
                            'redirect':[[]],
                            'target_group_arn' "
