### ISSUE TITLE
checkov Docker image DNS requests to www.bridgecrew.cloud

### ISSUE THREAD

**Issue by dan-m8t** [bridgecrewio/checkov#2459]
Hey there,

I am using checkov inside a GitLab CI/CD pipeline, which will always run when new code is pushed to a repo.
Operations team at my company now complains about massive DNS requests from our gitlab instance to www.bridgecrew.cloud.
The DNS servers are rate limited, so the machine gets limited in DNS lookups.

What is that request for ? I already expirimented with `--no-guide` option, everytime the pipeline runs a container gets started by GitLab that make DNS requests to the website.

Can you tell me what that request is about? Update check or something? Is there a way to disable those lookups and use only the integrated policies? Some kind of an offline/air-gapped mode? ;)

Thanks

Dan

**Comment by nimrodkor** [comment]
Hi @dan-m8t !

I'd love to talk a little more on this, it seems we're missing some things here. Care to slack our workspace, https://slack.bridgecrew.io/, so we can help troubleshoot and understand the root cause of this?

**Comment by slmagus** [comment]
use the --skip-download replaces --no-guide option
