### ISSUE TITLE
checkov skipping terraform file

### ISSUE THREAD

**Issue by pimperator** [bridgecrewio/checkov#2462]
**On parsing a terraform file checkov skips parsing file**
So I am validating a terraform module file and I managed to create the smallest subset of lines for debugging. 
Nevertheless I can reproduceably make the file being unparseable.

```
checkov --download-external-modules True --framework terraform -d .

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.858

terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file /src/lookup-ecs-alb/main.tf
```

While `terraform validate` reports it being valid:
```
Success! The configuration is valid.
```
This is the version of terraform:
```
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.1.0
```

So the expectation here is to parse it properly.

**Examples**
```hcl
data "aws_ssm_parameter" "param_cluster_arn" {
  name = try(
    "/${join("/",
      compact([
        coalesce(
          var.cluster_prefix,
          join("/", compact([
            var.cluster_app_name,
            (var.tags.Environment == "prod") ? "prod" : "dev"
            ])
          )
        ),
      var.param_cluster_arn])
    )}",
  null)
}

variable "tags" {
  type = map(any)
  default = {
    Project     = "undef"
    Environment = "undef"
  }
  description = "Tags"
}

variable "cluster_prefix" {
  type        = string
  description = "optional prefix of the cluster with environment"
  default     = ""
}

variable "cluster_app_name" {
  type        = string
  description = "cluster app name that is being used by ecs-cluster stacks"
  default     = "common/ecs-cluster"
}

variable "param_cluster_arn" {
  type        = string
  description = "ssm parameter name that contains the cluster arn"
  default     = "cluster_arn"
}
```

**Version (please complete the following information):**
 - Checkov Version 2.0.858

**Additional context**

**Comment by gruebel** [comment]
hi @pimperator thanks for creating the issue. I took a look and our parser for Terraform files can't handle what you put into the `try` function. This is actually a not recommended usage of the `try` function, why not creating a `locals` block and do most of the work in separate steps, also easier to maintain.

> Warning: The try function is intended only for concise testing of the presence of and types of object attributes. Although it can technically accept any sort of expression, we recommend using it only with simple attribute references and type conversion functions as shown in the examples above. Overuse of try to suppress errors will lead to a configuration that is hard to understand and maintain.

**Comment by pimperator** [comment]
Dear gruebel,

thanks for the fast answer!
It is a good info that I abuse the try function. The whole functionality of that code is somewhen from the beginning of terraform 0.12 - so ages ago when neither terraform nor me were experienced. I will rework the code since it is also hard to read
