### ISSUE TITLE
Support SSH for --external-checks-git

### ISSUE THREAD

**Issue by Harmelodic** [bridgecrewio/checkov#2471]
**Describe the issue**
If an external git repository is used for [custom Checkov policies that are shared](https://www.checkov.io/3.Custom%20Policies/Sharing%20Custom%20Policies.html), the current implementation only supports `https`.

It would be good to also support SSH.

**Examples**
Would like to define SSH URLs, for example:
```shell
checkov --compact --quiet \
  --framework=terraform \
  --directory . \
  --external-checks-git "git@github.com:some-user/checkov-custom-policies.git" \
```
or:
```shell
checkov --compact --quiet \
  --framework=terraform \
  --directory . \
  --external-checks-git "ssh://git@scm.example.com/some-group/checkov-custom-policies.git" \

```

**Version (please complete the following information):**
 - Checkov Version - latest

**Comment by Harmelodic** [comment]
Huh - I'll give things another go.

Pretty sure I'm on latest checkov, but I'll double check!(ov)

**Comment by Harmelodic** [comment]
Not sure what version I was on before, but I upped to `2.0.580` and now I can reference the SSH repo!

Neat 👌

**Comment by naveencloud** [comment]
Hello @njgibbon ., 

While checkout the internal private repo where the username/token are exposed as Environment variable using "external-checks-git" it not working  
external-checks-git:
  -  https://${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}@gitlab.com/osp/search/iac/naveencheckov.git//checkov_policy
