### ISSUE TITLE
CKV_TF_DATA_EXTERNAL_1: "Ensure terraform external data blocks runs vetted code"

### ISSUE THREAD

**Issue by ocofaigh** [bridgecrewio/checkov#2476]
**Describe the issue**
With the latest checkov release, the following code block is now failing for us:
```
data "external" "cluster_proxy_node_image_digest" {
  depends_on = [data.ibm_container_cluster_config.cluster_config]
  program = ["bash", "${local.scripts_location}/configure_image_digest.sh",
  data.ibm_container_cluster_config.cluster_config.config_file_path]
}
```
Failure is:
```
Check: CKV_TF_DATA_EXTERNAL_1: "Ensure terraform external data blocks runs vetted code"
	FAILED for resource: module.deploy_proxy.external.cluster_proxy_node_image_digest
	File: /main.tf:80-84
	Calling File: /examples/deploy-proxy-existing-cluster/main.tf:5-8

		80 | data "external" "cluster_proxy_node_image_digest" {
		81 |   depends_on = [data.ibm_container_cluster_config.cluster_config]
		82 |   program = ["bash", "${local.scripts_location}/configure_image_digest.sh",
		83 |   data.ibm_container_cluster_config.cluster_config.config_file_path]
		84 | }
```

It looks like this check was added yesterday in https://github.com/bridgecrewio/checkov/commit/63d36e5ba309e9c03ef99a13f264ba256d756d8d but I cannot find any documentation on how to update the code to get it to pass this check. Can you please advise?

**Version (please complete the following information):**
 - 2.0.855

**Comment by schosterbarak** [comment]
Thank you for reporting this. I've moved this check to the tests directory. I originally thought to suggest every user will vett and suppress if the external code is legit. but I understand that's a bit of an overkill and therefore have moved it to a test repository.
