### ISSUE TITLE
Environment variable  IGNORE_HIDDEN_DIRECTORY_ENV  not working

### ISSUE THREAD

**Issue by chrisfromzurigo** [bridgecrewio/checkov#2548]
**Describe the issue**
After setting the environment variable IGNORE_HIDDEN_DIRECTORY_ENV  to false, checkov is not scanning any folder beginning with ".". I'm trying to check also terraform modules in directory .terraform.

**Examples**
chris@ /mnt/c/workspace/bxs/backupplaygroundbxs (main) $ export IGNORE_HIDDEN_DIRECTORY_ENV=false
chris@ /mnt/c/workspace/bxs/backupplaygroundbxs (main) $ echo $IGNORE_HIDDEN_DIRECTORY_ENV
false
chris@ /mnt/c/workspace/bxs/backupplaygroundbxs (main) $ checkov -d .

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.906
Update available 2.0.906 -> 2.0.907
Run pip3 install -U checkov to update

terraform scan results:

Passed checks: 3, Failed checks: 0, Skipped checks: 0

Check: CKV_AZURE_77: "Ensure that UDP Services are restricted from the Internet "
        PASSED for resource: azurerm_network_security_group.devops
        File: /virtual_machine.tf:57-62
        Guide: https://docs.bridgecrew.io/docs/ensure-that-udp-services-are-restricted-from-the-internet
Check: CKV_AZURE_9: "Ensure that RDP access is restricted from the internet"
        PASSED for resource: azurerm_network_security_group.devops
        File: /virtual_machine.tf:57-62
        Guide: https://docs.bridgecrew.io/docs/bc_azr_networking_2
Check: CKV_AZURE_10: "Ensure that SSH access is restricted from the internet"
        PASSED for resource: azurerm_network_security_group.devops
        File: /virtual_machine.tf:57-62
        Guide: https://docs.bridgecrew.io/docs/bc_azr_networking_3

chris@ /mnt/c/workspace/bxs/backupplaygroundbxs (main) $
chris@ /mnt/c/workspace/bxs/backupplaygroundbxs (main) $
chris@ /mnt/c/workspace/bxs/backupplaygroundbxs (main) $ checkov -d .terraform

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.906
Update available 2.0.906 -> 2.0.907
Run pip3 install -U checkov to update

terraform scan results:

Passed checks: 4, Failed checks: 9, Skipped checks: 0

Check: CKV_AZURE_118: "Ensure that Network Interfaces disable IP forwarding"
        PASSED for resource: azurerm_network_interface.vm-nic
        File: /modules/vm01/main.tf:50-64
        Guide: https://docs.bridgecrew.io/docs/ensure-that-network-interfaces-disable-ip-forwarding
Check: CKV_AZURE_92: "Ensure that Virtual Machines use managed disks"
        PASSED for resource: azurerm_linux_virtual_machine.vm
        File: /modules/vm01/main.tf:79-126
        Guide: https://docs.bridgecrew.io/docs/ensure-that-virtual-machines-use-managed-disks
Check: CKV_AZURE_118: "Ensure that Network Interfaces disable IP forwarding"
        PASSED for resource: azurerm_network_interface.vm-nic
        File: /modules/vm02/main.tf:50-64
        Guide: https://docs.bridgecrew.io/docs/ensure-that-network-interfaces-disable-ip-forwarding
Check: CKV_AZURE_92: "Ensure that Virtual Machines use managed disks"
        PASSED for resource: azurerm_linux_virtual_machine.vm
        File: /modules/vm02/main.tf:79-126
        Guide: https://docs.bridgecrew.io/docs/ensure-that-virtual-machines-use-managed-disks
Check: CKV_AZURE_1: "Ensure Azure Instance does not use basic authentication(Use SSH Key Instead)"
        FAILED for resource: azurerm_linux_virtual_machine.vm
        File: /modules/vm01/main.tf:79-126
        Guide: https://docs.bridgecrew.io/docs/bc_azr_networking_1

                79  | resource "azurerm_linux_virtual_machine" "vm" {
                80  |   name                = var.vm_name
                81  |   resource_group_name = var.resource_group.name
                82  |   location            = var.resource_group.location

**Version (please complete the following information):**
 - Checkov Version 2.0.906

**Comment by nimrodkor** [comment]
Hey @chrisfromzurigo , Can you try overriding `CKV_IGNORED_DIRECTORIES` with `""` and run this again?

**Comment by MooreDerek** [comment]
@nimrodkor I think the problem is in `terraform/parser.py`, it explicitly strips out any hidden files or directories - https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/parser.py#L202
