### ISSUE TITLE
"level up" your Checkov powers for free?

### ISSUE THREAD

**Issue by davidaavilar** [bridgecrewio/checkov#2554]
Hi there.. We are getting this message on our pipeline about "leveling up" our free Checkov to Bridgecrew.. is there any option or flag to bypass this? Thanks!

I'm simply executing `checkov -f myfile.yaml`

```
By Bridgecrew.io | version 2.0.908

Would you like to "level up" your powers for free? The upgrade includes...


...

and much more...

It's easy and only takes 2 minutes. We can do it right now!

```

**Version:**
 - Checkov Version 2.0.908

![checkov-issue](https://user-images.githubusercontent.com/33632789/156104533-4f19c17e-9206-42c6-aaa4-e2d49db4587b.jpeg)

**Comment by nimrodkor** [comment]
Hey @davidaavilar !
I'm not sure how your command is passed in. It seems the parameters get messed up since there's an explicit `elif` between the case of specifying `-f` and the case of running through the onboarding. Can you share here an `echo` of the command that if being run?

**Comment by davidaavilar** [comment]
Hi, @nimrodkor. Thank you for your prompt response. Actually, it's random.. some colleagues are using `checkov -f` and/or `checkov --config config.yaml` and it shows the message. Always when you send just the command `checkov`, it shows the message, I think that's okay, but why is showing the message when we are scanning? or when it should show the message? Thanks!

<img width="582" alt="image" src="https://user-images.githubusercontent.com/33632789/156183865-b380f113-a533-49fe-9275-7f6a75872691.png">

**Comment by ManasviMahalwar-Veolia** [comment]
Hello

Do we have any flag to bypass this, it's causing CI to fail.
