### ISSUE TITLE
add-matcher causes an error, which then fails the CI run

### ISSUE THREAD

**Issue by allanyung** [bridgecrewio/checkov#2588]
**Describe the issue**
The action has suddenly started returning an error regarding matchers, rather than running to completion

**Version (please complete the following information):**
 - Checkov Version: 2.0.928
 - Checkov Action Version: master

**Additional context**
The following error occurs during the run:
```
Error: Unable to process command '::add-matcher::bridgecrew-problem-matcher-warning.json' successfully.
13
Error: Could not find file '/home/runner/work/REDACTED/bridgecrew-problem-matcher-warning.json'.
```
I've traced this to this commit: https://github.com/bridgecrewio/checkov/commit/a2a03a56238fa913889970dc9a7d12c114473602

The issue looks to be either:
1) the entrypoint has erroneous updates
2) the updates are legit, but some additional files weren't checked in

I haven't submitted a PR as it's unclear which the issue might be, and if it's *2* then I don't have the missing files

**Comment by rotemavni** [comment]
Hello @allanyung, thank you for reporting this issue.
We have reverted the change (https://github.com/bridgecrewio/checkov/pull/2589) for now and we will come up with a better solution.
Can you please verify the CI runs work as expected now?

**Comment by lukerosser** [comment]
Thanks @rotemavni - it's working as expected for me through the Github action now

**Comment by allanyung** [comment]
@rotemavni Thanks for the quick fix!

I can confirm that the Github action run is working again
