### ISSUE TITLE
Update Runner.run method to support both root_folder and files parameters 

### ISSUE THREAD

**Issue by smrojas** [bridgecrewio/checkov#2633]
https://github.com/bridgecrewio/checkov/blob/d83f5024bf771fa8d795f9a303e603ed107895e1/checkov/terraform/runner.py#L74-L110

Right now, the terraform Runner class cannot be run on specific files, even though this is supported. This is because the `root_folder` is a required parameter, and because of this, the `files` parameter can never be used because of the `if/else` logic of the `run` method. This looks like an oversight because there is an explicit exception raised if _neither_ of these parameters are set, implying they should be optional.

This PR makes the `root_folder` parameter optional. It looks like this is handled differently in the various provider types (cloudformation, kubernetes, etc) so I wasn't sure what approach y'all would ideally want.

## Code Example 
```
        runner = Runner()
        current_dir = os.path.dirname(os.path.realpath(__file__))

        test_files_dir = os.path.join(current_dir, 'resources/terraform')
        report = runner.run(
            root_folder=test_files_dir,
            files = ['/path/to/file.tf'],  # completely ignored because `root_folder` takes precedence
            runner_filter=RunnerFilter(checks=[check.id]),
        )

```

## Ideal behavior
        runner = Runner()
        current_dir = os.path.dirname(os.path.realpath(__file__))

        test_files = os.path.join(current_dir, 'resources/terraform/file.tf')
        report = runner.run(
            files = test_files,  # Runner will now scan this specific file
            runner_filter=RunnerFilter(checks=[check.id]),
        )
```

**Comment by nimrodkor** [comment]
Is this issue based on the typing only? Because scanning files using the -f flag works for sure. If so - would appreciate a contribution on this

**Comment by smrojas** [comment]
This issue is only when writing tests using the built in runner class (see code sample)

Checkov when run from the CLI works fine when passing a directory or file
