### ISSUE TITLE
CKV_GCP_13 - Modify certificate authentication method by OAuth method

### ISSUE THREAD

**Issue by hg-orng** [bridgecrewio/checkov#2662]
Hello,

ID=CKV_GCP_13
Description=Ensure a client certificate is used by clients to authenticate to Kubernetes Engine Clusters.

This check should be modified to check if the authentication method used is the OAuth method and not the client certificate anymore.

**Comment by nimrodkor** [comment]
Thanks for reporting @hg-orng !
We'd appreciate a contribution here!
The relevant check:
https://github.com/bridgecrewio/checkov/blob/b77412b5b1dfeb9adedb47e1062a281dc786f973/checkov/terraform/checks/resource/gcp/GKEClientCertificateEnabled.py
