### ISSUE TITLE
Upload Visual Studio Code extension to Open VSX

### ISSUE THREAD

**Issue by saerosV** [bridgecrewio/checkov#2687]
**Describe the issue**

As stated in the [Archlinux Wiki](https://wiki.archlinux.org/title/Visual_Studio_Code#Extensions_support), the open-source builds of VSCode (Code, VSCodium) don't have access to [Microsoft's Marketplace](https://marketplace.visualstudio.com/vscode). Instead, they use the [Open VSX](https://open-vsx.org/) registry.

To increase Checkov's extension visibility, and facilitate users' experience, I suggest uploading Checkov's VSCode extension to the [Open VSX](https://open-vsx.org/) registry.

**Comment by JamesWoolfenden** [comment]
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by saerosV** [comment]
@schosterbarak any comments on this? Should be reasonably simple to set up, and would greatly benefit users of open-source builds of VSCode.

**Comment by 4d1m** [comment]
Hello! Are there any plans to add Checkov to Open-VSX? It would benefit every user of VSCodium. Thank you for all your splendid work!
