### ISSUE TITLE
Helm Chart issues have wrong `repo_file_path` in report

### ISSUE THREAD

**Issue by lolgab** [bridgecrewio/checkov#2708]
**Describe the issue**
Checks relying on Helm (like `CKV_K8S_38`) don't return a correct `repo_file_path`.
What they return is some invented path which seems to be build from the concatenation of
the `name` field in `Chart.yaml` and the actual filename.

**Examples**
Using this example:
https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-to-sd

The expected file path for an issue in `templates/deployment.yaml` is `/templates/deployment.yaml`.
What I get is `../tmp/tmpjr32d99d/prometheus-to-sd/templates/deployment.yaml`
where `prometheus-to-sd` is taken from the [chart name](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-to-sd/Chart.yaml#L11)

**Version:**
 - Checkov Version 2.0.399

**Additional context**
Other paths in the report are wrong as well:
```json
        "file_path": "/prometheus-to-sd/templates/deployment.yaml",
        "file_abs_path": "/tmp/tmpyhnqvylp/prometheus-to-sd/templates/deployment.yaml",
        "repo_file_path": "/../tmp/tmpyhnqvylp/prometheus-to-sd/templates/deployment.yaml",
```

**Comment by srinivasakartheek** [comment]
Implemented the fix in https://github.com/bridgecrewio/checkov/pull/4044
