### ISSUE TITLE
💡 Feature Request: Include check severity

### ISSUE THREAD

**Issue by AErmie** [bridgecrewio/checkov#2721]
**Describe the issue**
When using Checkov in a CI/CD pipeline, it would be helpful to receive information about what severity a check/rule is (ie. Critical, High, etc.). Other tools (like [TFSec](https://github.com/aquasecurity/tfsec#example-output)) include this, which allows for a phased adoption (ie. only initially blocking/failing the scan if `critical` vulnerabilities are discovered).

Using Checkov would mean an "all or nothing" adoption, instead of focusing on the most critical/high vulnerabilities.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

```CMD
Check: CKV2_AWS_12: "Ensure the default security group of every VPC restricts all traffic"
	FAILED for resource: aws_vpc.main
	File: /vpc.tf:5-8
	Guide: https://docs.bridgecrew.io/docs/networking_4

		5 | resource "aws_vpc" "main" {
		6 |   cidr_block           = "10.0.0.0/16"
		7 |   enable_dns_hostnames = true
		8 | }
```

The expectation would be to identify the severity of the vulnerability.

**Version (please complete the following information):**
 - Checkov Version 2.0.962

**Additional context**
These scans are being run using the Docker container option for Checkov, in an Azure Pipeline.

**Comment by tsmithv11** [comment]
Hey @AErmie, as @gruebel noted, this is available today if you include a Bridgecrew API key. Check out this blog: https://bridgecrew.io/blog/checkov-iac-policy-severities-prioritize-skip-fail/

**Comment by gruebel** [comment]
@tsmithv11 I also wanted to post Mike's blog post 😄

**Comment by AErmie** [comment]
Thanks @tsmithv11, but that has a reliance on your platform, and is not in the open-source standalone version of Checkov.

**Comment by kderck** [comment]
Hit this issue today. This is frustrating that you have to have an `API Key` for severity.
