### ISSUE TITLE
Checkov returns the wrong resource address for the file that failed the check

### ISSUE THREAD

**Issue by Muhammada3178** [bridgecrewio/checkov#2725]
**Describe the issue**
Currently in my project, I have the following structure 
|── policies
    |── testing.yaml
    |── testt.yaml
    |── test.yaml
|── test.tf

Out of the three policy files above, the only one that should fail `CKV_AWS_63` is `testt.yaml`. However, when I generate a plan file which creates three new resources from the content that is in the three policies files shown above, the json output for checkov shows that `test.yaml` is the resource address of the file that failed the check which is not correct. 

This is a simple example for demonstration purposes but during my testing on more complex examples, I consistently found that checkov returned the incorrect resource address as well. 

**Additional context**
The command that I ran: `checkov -f tf-plan.json -o json`
Here's the contents of each file: 

testing.yaml: 
```
{
    "Statement": [
        {
            "Action": [
                "s3:PutObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::take-bucket-123/*",
                "arn:aws:s3:::take-buceket-123"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```
test.yaml
```
{
    "Statement": [
        {
            "Action": [
                "s3:PutObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::fake-bucket-123/*",
                "arn:aws:s3:::fake-buceket-123"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```
testt.yaml
```
{
    "Statement": [
        {
            "Action": [
                "*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::cake-bucket-123/*",
                "arn:aws:s3:::cake-buceket-123"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```
test.tf: 
```
resource "aws_iam_policy" "test" {
  for_each = fileset("policies/", "*.yaml")

  name        = replace(basename(each.value), ".yaml", "")
  path        = "/"
  description = ""

  policy = jsonencode(yamldecode(file("policies/${each.value}")))
  lifecycle {
    ignore_changes = [description]
  }
}
```
relevant part of the checkov output: 
```
"failed_checks": [
            {
                "check_id": "CKV_AWS_63",
                "bc_check_id": "BC_AWS_IAM_48",
                "check_name": "Ensure no IAM policies documents allow \"*\" as a statement's actions",
                "check_result": {
                    "result": "FAILED",
                    "evaluated_keys": [
                        "policy",
                        "inline_policy"
                    ]
                },
                "code_block": [],
                "file_path": "/tf-plan.json",
                "file_abs_path": "/home/no/Desktop/tf-plan.json",
                "repo_file_path": "/tf-plan.json",
                "file_line_range": [
                    0,
                    0
                ],
                "resource": "aws_iam_policy.test",
                "evaluations": null,
                "check_class": "checkov.terraform.checks.resource.aws.IAMStarActionPolicyDocument",
                "fixed_definition": null,
                "entity_tags": null,
                "caller_file_path": null,
                "caller_file_line_range": null,
                "resource_address": "aws_iam_policy.test[\"test.yaml\"]",
```

**Suggested remediation:**
I would say that for the short-term, the resources address should not be reported back in the json output when scanning a terraform plan file. Right now it's consistently returning the wrong result which will only stand to hurt whoever is ingesting that output right now.

**Comment by nimrodkor** [comment]
Hi @Muhammada3178 !

This seems like a rather complex use of terraform, with several operators we don't fully support yet. That might be the root of the issue in this case. I'm actually surprised we were able to parse the for_each here and scan the yaml files. I don't believe this is really an output bug, but rather a scanning bug. If you hardcode those files in separate resources instead of using the for each, does it work?

**Comment by Muhammada3178** [comment]
@nimrodkor Ty for the response! If I hardcode then I get the expected output. Are there any plans to make `checkov` compatible with a `for_each` workflow? 

It is a common use-case among individuals and organizations to make use of a `for_each` and it seems I'm not the only one facing this problem. While digging through the issues I noticed another person has reported issues with using `checkov` in their `for_each` workflow as well https://github.com/bridgecrewio/checkov/issues/2230
