### ISSUE TITLE
Support Rollout Kind

### ISSUE THREAD

**Issue by boris154** [bridgecrewio/checkov#2726]
**Describe the issue**
When using Argo Rollouts, checkov is not running checks on it because the `Rollout` Kind is not supported. It would be great to have the checks run against Rollout as well.

**Version (please complete the following information):**
 - Checkov Version 2.0.1012

**Additional context**
Argo Rollout specification: https://argoproj.github.io/argo-rollouts/features/specification/

**Comment by ltshb** [comment]
That's a shame that this one has been closed, is there no plan on supporting Argo Rollout ?
