### ISSUE TITLE
Skipping checks in particular resources in a Terraform plan file

### ISSUE THREAD

**Issue by hobbyhorse** [bridgecrewio/checkov#2769]
In .tf files checkov is able to read the comments in each resource and so skip certain checks.

I do not see a way to do this when checking against a Terraform plan file as the plan drops all comments. 

Is there a way around this?

**Comment by gruebel** [comment]
Hi @hobbyhorse yeah there is, you need to add a flag which points to the root of the  original TF files
```shell
  --repo-root-for-plan-enrichment REPO_ROOT_FOR_PLAN_ENRICHMENT
                        Directory containing the hcl code used to generate a given plan file. Use with -f.
```

**Comment by hobbyhorse** [comment]
Thank you!
