### ISSUE TITLE
HCL parser cannot parse variables with multi-line conditions containing comments

### ISSUE THREAD

**Issue by domroutley** [bridgecrewio/checkov#2771]
**Describe the issue**

Terraform HCL parser fails to parse files containing comments in the variable.validation block, condition function call, resulting in all/any checks that rely on variables in the same file failing. This is only an issue in versions `2.0.1036` and `2.0.1037`.

We believe this to be a bug, as Terraform formatted in this way passes Terraform validate, and will also apply/destroy fully.

As the issue is non-trivial to replicate I have put the basic (working) code that can replicate this issue into a repo ([here](https://github.com/domroutley/checkov-issue-duplication)). In my example/explanation, I will refer to this repo as an example.

**Example Value**

If you refer to [this line](https://github.com/domroutley/checkov-issue-duplication/blob/main/variables.tf#L8) in my uploaded example, you should see a comment line that is within a multi-line condition function call. If this comment line is removed (or moved either within the list, or outside of the function call entirely) then Checkov runs and results in zero failed checks.

As the code stands however, Checkov fails the rule CKV_AZURE_35 relating to the storage account defined in `main.tf`. This is because the entire `variables.tf` file gets ignored due to the parsing error, therefore the `default_action` [variable](https://github.com/domroutley/checkov-issue-duplication/blob/main/variables.tf#L21) is not propogated and the failed check appears.

Running Checkov with `LOG_LEVEL="DEBUG"` results in [this trace](https://github.com/domroutley/checkov-issue-duplication/blob/main/trace.log), which confirms the issue.

*To replicate the issue*

1. Clone the example
    - `git clone https://github.com/domroutley/checkov-issue-duplication.git`
1. Run Checkov from within the repo
    - We have a `.checkov` file in the root, so the config is auto-set
1. Delete line 8 in the `variables.tf` file and rerun Checkov to see the error disappear

**Versions affected**

`2.0.1036` and later

**Comment by gruebel** [comment]
Hi @domroutley thanks for creating the issue and adding the great example. We changed our Terraform file parser recently to be able to support different ways of doing line breaks and sadly such changes also break other use cases. But I'm working on a fix, so please hold on and look forward to it.

**Comment by domroutley** [comment]
Thank you @gruebel !
