### ISSUE TITLE
CloudFormation: S3 default encryption check should look for ServerSideEncryptionByDefault

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#280]
The CloudFormation check for CKV_AWS_19 only looks for `ServerSideEncryptionRule`, not `ServerSideEncryptionByDefault`:

https://github.com/bridgecrewio/checkov/blob/864d12ad0dfc6ca898dbacf7dc16fdc20f702733/checkov/cloudformation/checks/resource/aws/S3Encryption.py

The syntax used in the S3 template does not appear to be used anywhere else in GitHub:

https://github.com/bridgecrewio/checkov/blob/864d12ad0dfc6ca898dbacf7dc16fdc20f702733/tests/cloudformation/checks/resource/aws/S3Templates/ExampleS3.yaml#L13 

All of the working CloudFormation templates which I've seen look like this:

https://github.com/cloudconformity/documentation-api/blob/cba56c057d42c19db606f7d72ca197ee52d97848/examples/cloudformation-snippets/S3Bucket.yml#L8-L11

Checkov version: 1.0.312

**Comment by nimrodkor** [comment]
Thanks for reporting!
