### ISSUE TITLE
Checkov can't find separate resources used for fixing checkov issues

### ISSUE THREAD

**Issue by minedetector** [bridgecrewio/checkov#2803]
We are upgrading terraform version `3.74.3 -> 3.75.1` and a lot of arguments for the resource `aws_s3_bucket` have become deprecated.

In this example 

Here are all the checkov alerts I need to skip although they weren't needed before.
CKV_AWS_19 = Ensure all data stored in the S3 bucket is securely encrypted at rest
- encryption at rest is configured by the resource `aws_s3_bucket_server_side_encryption_configuration`

CKV_AWS_21 = Ensure all data stored in the S3 bucket have versioning enabled
- versioning is enabled through the resource `aws_s3_bucket_versioning`

CKV_AWS_145 = Ensure that S3 buckets are encrypted with KMS by default
- The bucket is encrypted with KMS by using the `aws_s3_bucket_server_side_encryption_configuration` resource
```
resource "aws_s3_bucket" "default" {
  #checkov:skip=CKV_AWS_18
  #checkov:skip=CKV_AWS_19
  #checkov:skip=CKV_AWS_21
  #checkov:skip=CKV_AWS_145
  bucket        = local.bucket_name
  force_destroy = false

}

resource "aws_s3_bucket_acl" "default" {
  bucket = aws_s3_bucket.default.id
  acl    = "private"
}

resource "aws_s3_bucket_versioning" "default" {
  bucket = aws_s3_bucket.default.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "default" {
  bucket = aws_s3_bucket.default.bucket

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.default.arn
    }
  }
}

resource "aws_s3_bucket_public_access_block" "default" {
  bucket = aws_s3_bucket.default.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
```

**Version (please complete the following information):**
 - Checkov Version 2.0.158

**Comment by nimrodkor** [comment]
Hey @minedetector ! We released official support for the new AWS provider already, see #2638 
I believe your checkov version is outdated, can you try an updated one?

**Comment by minedetector** [comment]
Thanks for the quick response, will check it soon.

**Comment by citrix-eg** [comment]
I ran into this as well but I am on a contemporary version of checkov: 

```
resource "aws_s3_bucket" "bucket" {
  bucket = "bucket-${var.environment}"
}

resource "aws_s3_bucket_server_side_encryption_configuration" "worker-deploy" {
  bucket = aws_s3_bucket.bucket.bucket
  rule {
    apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
    }
  }
```

still gives me a CKV_AWS_145 finding.

**Comment by citrix-eg** [comment]
Ran into this with some minor PEBCAK which I wanted to write down here since this is the first google result. The check is explicitly requiring CMKs not just the service default keys.

The wording made it a little confusing so it was not totally clear. A better example is the same check for DynamoDB which states that it requires a CMK.
