### ISSUE TITLE
Question about contribution

### ISSUE THREAD

**Issue by mirtov-alexey** [bridgecrewio/checkov#2804]
Hey!
I am in the process of adding support for yandex cloud terraform provider checks https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/compute_instance . I understand how to do similar checks like aws and others. You need to create a check file and a test file. But the question : **how can I test that my check passes correctly on a specific tf file?** what do I need to do for this? Didn't find the answer in the documentation. Can I somehow build with my new files in mind?

**Comment by gruebel** [comment]
hey @mirtov-alexey great question, we have a specific way of testing and use actual Terraform files, you can check out this PR https://github.com/bridgecrewio/checkov/pull/2068, it should be quite helpful to achieve what you want to do.

**Comment by schosterbarak** [comment]
also see: https://github.com/bridgecrewio/checkov/blob/master/docs/6.Contribution/Contribute%20New%20Terraform%20Provider.md

**Comment by mirtov-alexey** [comment]
yep thank you
allready read this

i have a slightly different question

here I added the first check to my fork - https://github.com/mirtov-alexey/checkov/commit/cd7fd822f039072a131ee23f3ad0565ec28d9e2c

Now to test it I have to run the test file. Looks like it works correct.

1) but how can i emulate the actual behavior of the software when checking the tf file - as if the changes are already committed? for example, maybe I can somehow build the application itself, taking into account my new files and edits, and run checkov cli for example?is it possible?

2) Also how do you think this files are correct? can i continue the same way for other checks? 


Link to template terraform resource
https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/compute_instance

![image](https://user-images.githubusercontent.com/85429798/162981432-b817c533-6051-46cd-a76f-8a830336607c.png)

**Comment by mirtov-alexey** [comment]
this is my slack - alexweeee

maybe if someone will be easier to answer me there

possibly Russian-speaking developers - I think there are such judging by the name of the product)

**Comment by MooreDerek** [comment]
@mirtov-alexey You can test it locally - make sure you follow all the `CONTRIBUTING.md` steps on setting up a local dev env - then you can run:
`pipenv run python  -m pytest tests/terraform/checks/resource/yandexcloud/test_EC2PublicIP.py --capture=tee-sys`

**Comment by mirtov-alexey** [comment]
Hello!
@MooreDerek 

I made this check - let me remind you, my code is here https://github.com/mirtov-alexey/checkov/commit/cd7fd822f039072a131ee23f3ad0565ec28d9e2c

I am attaching a screenshot of the result of the command: `pipenv run python -m pytest tests/terraform/checks/resource/yandexcloud/test_EC2PublicIP.py --capture=tee-sys`
![image](https://user-images.githubusercontent.com/85429798/163364708-68b5c6ac-32eb-4d20-b0a6-7c0136b036e7.png)

also i built a new version with my files according to instructions https://github.com/bridgecrewio/checkov/blob/master/CONTRIBUTING.md#build-package-locally

based on the results, I ran the utility with a file check https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/resources/compute_instance

it doesn't have the nat=true option, but I've tried changing that as well. the result is empty (I'm attaching a screenshot)
![image](https://user-images.githubusercontent.com/85429798/163366056-f496837a-3bf5-4d26-bf33-4b317a006882.png)

**Comment by gruebel** [comment]
@mirtov-alexey I think the last thing you are missing is to add the import of the new module (has to be done once, all other checks later added will work right ahead) https://github.com/mirtov-alexey/checkov/blob/cd7fd822f039072a131ee23f3ad0565ec28d9e2c/checkov/terraform/checks/resource/__init__.py#L11
```python
from checkov.terraform.checks.resource.yandexcloud import *
```

**Comment by mirtov-alexey** [comment]
thank you - look like it works
@gruebel 
![image](https://user-images.githubusercontent.com/85429798/163799161-a2b4b487-d26e-4288-a6cf-3e38f677d253.png)
