### ISSUE TITLE
No colour option

### ISSUE THREAD

**Issue by Fran-Rg** [bridgecrewio/checkov#2805]
**Describe the issue**
Checkov cli output is heavily targeted for a dark background. Using a light theme makes it very hard to read.
Is there a way to remove color or control the theme used?

**Version:**
 - Checkov Version 2.0.1050

**Additional context**
Small search I found you use termcolor: https://github.com/bridgecrewio/checkov/blob/d55c68ff909c65e341e91938c13a155c99601f5f/checkov/common/output/report.py#L16
but I couldn't find a way to "mute" it. Maybe simply overwriting that function "colored" with a dummy lambda would do it.

**Comment by schosterbarak** [comment]
thanks @Fran-Rg . Happy to get a contribution with environment variable that will mute it.

**Comment by gruebel** [comment]
As described in #2824 the env var should be named `NO_COLOR`

**Comment by MooreDerek** [comment]
@gruebel @schosterbarak There is an existing setting in `termcolor.py` to control this -> `ANSI_COLORS_DISABLED` -> https://github.com/Uninett/PyMetric/blob/master/termcolor.py#L95. However one function in `record.py` needs to be fixed to address this `_code_line_string`. I'll make a PR for this method to be governed by the existing `termcolor` setting, unless there is a strong preference to have a `NO_COLOR` setting?

**Comment by gruebel** [comment]
not from my side, if we get most of the functionality for free, by leveraging the other env var, then lats go with that for now. Great find @MooreDerek
