### ISSUE TITLE
Supress individual checks on plan output

### ISSUE THREAD

**Issue by travisnburton** [bridgecrewio/checkov#2814]
When running checkov against Terraform plan files (`checkov --directory . --framework terraform_plan`), there's no mechanism to supress individual checks, i.e. `checkov:skip=<check_id>:<suppression_comment>` since the terraform resource blocks are not being evaluated.

I've tried injecting the suppression string into resource names and tags, which show up in the plan json, but they are ignored.

Since JSON does not support comments, I cannot write the supression string directly into the JSON file.  Is there another method?

**Comment by gruebel** [comment]
hi @travisnburton you can leverage a flag named `--repo-root-for-plan-enrichment` it will also parse your local TF files and grab the skip comments to map them against the plan
```shell
checkov -f tf-test/planfile.json --repo-root-for-plan-enrichment tf-test
```
