### ISSUE TITLE
Azure - new resources azurerm_linux/windows_web_app

### ISSUE THREAD

**Issue by 0xdbe** [bridgecrewio/checkov#2818]
**Describe the issue**
``azurerm_app_service`` has been deprecated in version 3.0 of the AzureRM provider and will be removed in version 4.0. it's superseded by  ``azurerm_linux_web_app`` and ``azurerm_windows_web_app`` resources.

**Examples**

```
resource "azurerm_linux_web_app" "app" {
  name                = xxxxxxxx
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_service_plan.main.location
  service_plan_id     = azurerm_service_plan.main.id

  site_config {
    minimum_tls_version = "1.0"
    application_stack {
      java_server         = "JAVA"
      java_version        = "java11"
      java_server_version = "11"
    }
  }

  https_only = false
}
```

Rules ``CKV_AZURE_13`` to ``CKV_AZURE_18`` are not take into consideration on new ressources: ``azurerm_linux_web_app`` and ``azurerm_windows_web_app``.

**Version (please complete the following information):**
 - Checkov Version 2.0.1063
 - Azurerm provider: 3.0.2

**Comment by RajanikanthGitHub** [comment]
Seems to me you are passing values as string for application stack (java) which is causing the issue.

You can get valid version combinations for java using below command:
`az webapp list-runtimes --linux`

Output:
`JAVA:11-java11`

try to use below format:
```
site_config {
    minimum_tls_version = "1.0"
    application_stack {
      java_server         = "JAVA" --> string
      java_version        = "java11" --> string
      java_server_version = 11 --> number
    }
  }
```

I got the same issue and it got resolved with above format.
