### ISSUE TITLE
Unable to process command '::add-matcher::XXXX`

### ISSUE THREAD

**Issue by AliAllomani** [bridgecrewio/checkov#2838]
**Describe the issue**

Related to https://github.com/bridgecrewio/checkov-action/issues/81

```
Error: Unable to process command '::add-matcher::checkov-problem-matcher.json' successfully.
Error: Could not find file '/home/runner/_work/XXXX/checkov-problem-matcher.json'.
```

Seems github actions is looking for matcher files in the original repo directory outside the container, therefore the copy commands in the container entrypoint have no effect

https://github.com/bridgecrewio/checkov/blob/cf3836c6fde51b614b421641d715ced95cd6525c/github_action_resources/entrypoint.sh#L11-L14

This issue is solved when adding the files `checkov-problem-matcher.json` or `checkov-problem-matcher-softfail.json` to the repo code.

maybe it would be nice to have these as optional and with the possibility of setting custom file names

**Comment by nimrodkor** [comment]
Replied in the other issue, closing this as it is a duplicate
https://github.com/bridgecrewio/checkov-action/issues/81
