### ISSUE TITLE
Accessing principal in IAM Policy 

### ISSUE THREAD

**Issue by SiSiHenry** [bridgecrewio/checkov#2840]
**Describe the issue**
I would like to craft a rule to that prevents principal from being "*", would you be able to provide an example?

**Examples**
```
data "aws_iam_policy_document" "fail" {
  version = "2012-10-17"

  statement {
    sid="ListAndCreateExecutionRoles"
    effect = "Allow"
    actions = [
        "*"
    ]
    resources = [
      "arn::s3:111111111",
    ]
    principals {
      type = "AWS"
      identifiers = ["*"]
    }
  }
}

```

**Version (please complete the following information):**
 - Checkov Version [2.0.1068]

**Additional context**

**Comment by nimrodkor** [comment]
Sure thing!

We support IAM attributes only through python policies for now. Example:
https://github.com/bridgecrewio/checkov/blob/1d9802bf99477514c9c399c3750b2c5a350a8b0d/checkov/terraform/checks/data/aws/StarActionPolicyDocument.py
