### ISSUE TITLE
Accessing principals in terraform data source  

### ISSUE THREAD

**Issue by SiSiHenry** [bridgecrewio/checkov#2847]
**Describe the issue**
I am unable to access the principal attribute of the data source iam_policy_document

I am trying to reference the variables using  the following logic: 

**Examples**
```
              if ( 
                     isinstance(statement, dict) 
                     and statement.get("effect", ["Allow"]) == ["Allow"] 
                     and statement.get("principals") 
                   and "*" in force_list(statement["principals"]["type"]) 
```
```
data "aws_iam_policy_document" "fail" {
  version = "2012-10-17"

  statement {
    effect = "Allow"
    actions = [
      "*"
    ]
    resources = [
      "arn:aws:s3:::my_corporate_bucket/*",
    ]
principals{
type= *
identifiers=*
}
  }
}
```

**Version (please complete the following information):**
 - Checkov Version [2.0.1065]

**Additional context**

**Comment by gruebel** [comment]
your code should work, but your Terraform config is invalid, you can't just write `type=*` that's how it should be
```hcl
data "aws_iam_policy_document" "fail" {
  version = "2012-10-17"

  statement {
    effect = "Allow"
    actions = [
      "*"
    ]
    resources = [
      "arn:aws:s3:::my_corporate_bucket/*",
    ]
    principals {
      type="*"
      identifiers=["*"]
    }
  }
}
```

**Comment by SiSiHenry** [comment]
Hello, yes that was a typo, type, was passed a string. 
The code does not work. How do I call the principal because, I am unable to reference it with the code provided above.

**Comment by SiSiHenry** [comment]
I get a parsing error
