### ISSUE TITLE
All Results Are `error` in Sarif Output

### ISSUE THREAD

**Issue by jrmash** [bridgecrewio/checkov#2848]
I'm working with the `sarif` output and noticed that the reported "level" for all detected policy failures is `error`, regardless of the actual severity. As an example, the following issue is `LOW` severity:

- https://docs.bridgecrew.io/docs/git_secrets_6

In the `sarif` JSON output, the level is reported as an `error` instead of the expected `note`:

![image](https://user-images.githubusercontent.com/2574997/164488563-43c8876a-c36e-4689-96bf-a236e9b73544.png)

**Comment by gruebel** [comment]
hi @jrmash the level is always `error` for all checks, if you don't use an API token from our platform. Or are using one, then it would be a bug?

**Comment by jrmash** [comment]
I am not using an API token, as I'm just reviewing the available options for this sort of tooling. This was a discrepancy I noticed between `checkov` and its competitors.

If this is not a bug and is not likely to make it into the base tool without requiring an API token, please feel free to close the issue.

**Comment by nimrodkor** [comment]
I do feel like using the `--soft-fail` should help not failing on specific options, and is already implemented in the base tool. If it is not working - please reopen this issue as it is a bug @jrmash

**Comment by jrmash** [comment]
The `--soft-fail` option isn't really relevant to the sarif output providing incorrect data, but thanks for the response.
