### ISSUE TITLE
Plain text db password in terraform files

### ISSUE THREAD

**Issue by Roqche** [bridgecrewio/checkov#2853]
Hi,
I'm new to infrastructure security. I know exactly that I have several databases in terraform files such as SQL Server or PostgreSQL with admin passwords in plain text. I don't understand why checkov can't tell me this is some kind of issue? In my IT experience, this is quite a critical issue as anyone with access to the GIT repository can see the passwords. Am I wrong?

I'm attaching two examples.
```
resource "azurerm_sql_server" "sql_server" {
  provider                     = azurerm.providername
  name                         = "${var.sql_server_name}"
  resource_group_name          = azurerm_resource_group.sql_rg.name
  location                     = var.location
  version                      = "12.0"
  administrator_login          = "adminuser"
  administrator_login_password = "My_STRONG_password(!)"
  tags                         = var.tags
}

resource "azurerm_postgresql_flexible_server" "psql" {
  name                   = "${var.postgresql_name}"
  resource_group_name    = azurerm_resource_group.postrgressql_rg.name
  location               = azurerm_resource_group.postrgressql_rg.location
  version                = "13"
  delegated_subnet_id    = var.delegated_subnet_id
  private_dns_zone_id    = azurerm_private_dns_zone.private_dns.id
  administrator_login    = "psqladmin"
  administrator_password = "My_STRONG_password(!)"
  zone                   = "1"

  sku_name   = "B_Standard_B1ms"
}
```

**Comment by MooreDerek** [comment]
@Roqche There two ways of addressing this behaviour that I'm aware of 
1. Use a `var.password` in the tf file and passing in the password as a variable on the command line or
2. Using a `data` to retrieve a password from the azurem key vault. 
So a simple check could be to verify that it's simply not a string, would that work for you?

**Comment by Roqche** [comment]
@MooreDerek Thank you for the solution on how to handle secrets.
But my question was rather, why didn't checkov inform me there are plain text passwords in files?

**Comment by nimrodkor** [comment]
We have some detections for secrets and tokens, but usually they are more random (base64 / hex entropy).
We have room for improvement on the `secrets` runner, are you up for helping out? @Roqche

**Comment by MooreDerek** [comment]
@Roqche The secrets detection is failing on the example above due to the complexity of the password :) The check only looks for alphanumeric characters the `(!)` causes the the regex to fail and the password is not detected. If you test the following examples:

``` hcl
resource "azurerm_postgresql_flexible_server" "psql" {
  name                   = "${var.postgresql_name}"
  resource_group_name    = azurerm_resource_group.postrgressql_rg.name
  location               = azurerm_resource_group.postrgressql_rg.location
  version                = "13"
  delegated_subnet_id    = var.delegated_subnet_id
  private_dns_zone_id    = azurerm_private_dns_zone.private_dns.id
  administrator_login    = "psqladmin"
  administrator_password = "My_STRONG_password"
  zone                   = "1"

  sku_name   = "B_Standard_B1ms"
}
```
Then you get the following error:
```
Check: CKV_SECRET_6: "Base64 High Entropy String"
        FAILED for resource: 7ab187878c2c51d9502bbd8d7b36d1eca9319c18
        File: /tmp/azure/main.tf:20-21
        Guide: https://docs.bridgecrew.io/docs/git_secrets_6
```

**Comment by Roqche** [comment]
@nimrodkor Sure, I will try to help as much as I can
