### ISSUE TITLE
Do provider checks using the BaseProviderCheck class work against plan files?

### ISSUE THREAD

**Issue by solaris187** [bridgecrewio/checkov#2861]
Hello! Trying to write a provider based check to ensure that only certain AWS regions are being specified in Terraform. For testing, to ensure that I generally understand how the BaseProviderChecks worked, I pulled over this check below from the Checkov code and tried running it against my plan file.

```
import re
from typing import Dict, List, Any

from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.terraform.checks.provider.base_check import BaseProviderCheck
from checkov.common.models.consts import access_key_pattern, secret_key_pattern


class AWSCredentials(BaseProviderCheck):
    def __init__(self) -> None:
        name = "Ensure no hard coded AWS access key and secret key exists in provider"
        id = "CKV_AWS_41"
        supported_provider = ["aws"]
        categories = [CheckCategories.SECRETS]
        super().__init__(name=name, id=id, categories=categories, supported_provider=supported_provider)

    def scan_provider_conf(self, conf: Dict[str, List[Any]]) -> CheckResult:
        """
        see: https://www.terraform.io/docs/providers/aws/index.html#static-credentials
        """
        if self.secret_found(conf, "access_key", access_key_pattern):
            return CheckResult.FAILED
        if self.secret_found(conf, "secret_key", secret_key_pattern):
            return CheckResult.FAILED
        return CheckResult.PASSED

    @staticmethod
    def secret_found(conf: Dict[str, List[Any]], field: str, pattern: str) -> bool:
        if field in conf.keys():
            value = conf[field][0]
            if re.match(pattern, value) is not None:
                return True
        return False


check = AWSCredentials()
```
I noticed it did not run when pointing to the plan file however using the following command:
`checkov -f tfplan2.json --external-checks-dir ../../../../checkov/checkov-custom-rules/all_resources/regions/`

That path has both the custom check in it, as well as the __init__.py file

When running the same check with checkov pointed to my raw Terraform code (not the plan file), it works:
`checkov -d . --external-checks-dir ../../../../checkov/checkov-custom-rules/all_resources/regions/`

Is this a bug? Or is it intended behavior?

**Comment by JamesWoolfenden** [comment]
Hi Solaris, It indeed doesn't look like provider checks run against plan files. Im guessing its just that this case is a bit niche, external provider checks are uncommon and even less so against plan files.  So if you fancy taking it on, wed welcome the submission?
