### ISSUE TITLE
[bicep] Checks on referenced resources executed

### ISSUE THREAD

**Issue by holly79** [bridgecrewio/checkov#2870]
**Describe the issue**
If I reference an existing resource in a bicep file, eg a Storage Account, checks are executed. Because I could not add any properties of a reference. Keyword is "existing"

Check: CKV_AZURE_3: "Ensure that 'supportsHttpsTrafficOnly' is set to 'true'"
	PASSED for resource: Microsoft.Storage/storageAccounts.StorageAccount

**Examples**
```bicep
resource StorageAccount 'Microsoft.Storage/storageAccounts@2021-08-01' existing = {
  name: storageAccountName
}
```

**Version (please complete the following information):**
 - Checkov Version [2.0.1084]

**Additional context**

**Comment by gruebel** [comment]
hey @holly79 thanks for pointing this out, you are right. `checkov` doesn't take into account that resource with the `existing` keyword can't be changed and is only used to be referenced. It shouldn't be too hard to fix it, I hope 😄
