### ISSUE TITLE
Option to ignore .terraform catalog

### ISSUE THREAD

**Issue by acidflash** [bridgecrewio/checkov#291]
**Is your feature request related to a problem? Please describe.**
When i run `checkov -d .` in my project it always take some time before the output comes do to .terraform catalog. I just want to validate the files in the project and not the .terraform catalog.

**Describe the solution you'd like**
Parameter to ignore .terraform catalog like checkov -i
Helpfile
-i  --ignore-directory  Ignore the .terraform in the catalog you stand in.

**Describe alternatives you've considered**
I just want to see some way of ignoring the .terraform directory so you don't have to do this in the runs. But it should not be a compelling thing, but as an alternative as there are certainly several people who want to see everything.

**Additional context**
-

**Comment by holgiosalos** [comment]
@acidflash did you find any workaround to ignore the .terraform catalog?

**Comment by acidflash** [comment]
> @acidflash did you find any workaround to ignore the .terraform catalog?
Sorry, but no. I waiting for a feature update or fix in the software itself.

**Comment by schosterbarak** [comment]
Hey @holgiosalos and @acidflash thank you for this. On it. Opened a PR here: https://github.com/bridgecrewio/checkov/pull/356
