### ISSUE TITLE
CHK_AWS_42 fails if value is a variable

### ISSUE THREAD

**Issue by tomerleib** [bridgecrewio/checkov#2945]
**Describe the issue**
Using AWS provider v4, CHK_AWS_42 is looking for encrypted EFS, if I'm passing the value directly to the code, the check pass but if the value is set to be a variable, the check if failing:
**Examples**   

_Failing code:_
```hcl
resource "aws_efs_file_system" "efs" {
  encrypted = var.encrypt_efs
  lifecycle_policy {
     transition_to_ia = var.efs_transition_to_ia
  }
  tags = {
    Name = "${var.environment_name}-efs"
  }
}
```

_Working code:_
```hcl
resource "aws_efs_file_system" "efs" {
  encrypted = true
  lifecycle_policy {
     transition_to_ia = var.efs_transition_to_ia
  }
  tags = {
    Name = "${var.environment_name}-efs"
  }
}
```
**Version (please complete the following information):**
 - Checkov Version [2.0.1124]

**Additional context**

**Comment by gruebel** [comment]
hi @tomerleib could you also share the config part of the used variable?

**Comment by tomerleib** [comment]
Issue solved, thank you
