### ISSUE TITLE
Output: Differentiate Soft-Fail From Hard-Fail

### ISSUE THREAD

**Issue by AjkayAlan** [bridgecrewio/checkov#2947]
## The Problem

Currently when running Checkov and getting output, you cannot tell what checks are hard-failing versus what checks are soft-failing.

This makes it notably difficult for end users to understand which failures are actually breaking their pipeline (when using Checkov in a pipeline) when a central team is managing a common config (to dictate what checks are hard-fail and what checks are soft-fail) which is abstracted from the end users (though those users can view the config if needed).

Example:

![image](https://user-images.githubusercontent.com/14236618/167484712-f7225b8c-5ad7-4bc3-8ca4-04907f347957.png)

In the above image, I ran checkov against an offending Cfn template, with the args `--soft-fail-on CKV_AWS_111 --quiet --compact`. So my pipeline gets a nonzero exit code and CKV_AWS_33 is the only rule causing me to have a non-zero exit code.

## Why It Matters

If it was clearer in output if a check is soft failing, it would allow end users to more easily troubleshoot and understand which rules they should prioritize fixing first.

## Potential Solutions (likely a combination of some of the items stated below)

1. Change the color of the output of soft-failing checks from red to yellow or some other color to help indicate that the resource is still in violation of the rule, but it is not causing a non-zero exit code. Could likely do it at https://github.com/bridgecrewio/checkov/blob/05e61f5a6619bd4e3090625f4fc0be8bd82929dc/checkov/common/output/record.py#L137, though some more information would likely have to be plumbed in to the class.
2. Change the output text to better indicate that the check is soft-failed. Could likely do it at https://github.com/bridgecrewio/checkov/blob/05e61f5a6619bd4e3090625f4fc0be8bd82929dc/checkov/common/output/record.py#L192, or somewhere around those parts, but still would need more information sent to the class before you could do it
3. Add a `SOFT_FAILED` entry to the CheckResult enum, and some logic to shift FAILED to SOFT_FAILED based on if the check is in the soft_failed list. This one could be pretty painful based on the amount of checks to see if CheckResult == FAILED.
4. Something else?

**Comment by AjkayAlan** [comment]
Bumping so this doesn’t auto close

**Comment by davidfischer-ch** [comment]
This is a good idea as I was investigating the pipeline result and cannot differentiate _admitted_ failures from _actual_ failures.

**Comment by pingoleon108** [comment]
Bumping so this doesn’t auto close
