### ISSUE TITLE
only caputring the first line https://github.com/bridgecrewio/checkov/blob/2.0.1131/checkov/dockerfile/checks/WorkdirIsAbsolute.py

### ISSUE THREAD

**Issue by spark1825** [bridgecrewio/checkov#2964]
def scan_entity_conf(self, conf):
        for mydir in conf:
            mypath = mydir["value"]
            if re.match(PATH, mypath):
                return CheckResult.FAILED, mydir
        return CheckResult.PASSED, None

**Comment by gruebel** [comment]
hi @spark1825 what exactly is the issue, can you give an example Dockerfile, which fails, but should actually pass?
