### ISSUE TITLE
[CloudFormation] Missing check for "Template format error: Every Parameters object must contain a Type member."

### ISSUE THREAD

**Issue by ankon** [bridgecrewio/checkov#2965]
**Describe the issue**

A change in our CloudFormation stacks added a new parameter but missed the `Type: Number` part. Checkov passed, and we only found the problem when the changeset creation failed with the message "Template format error: Every Parameters object must contain a Type member."

This was in a nested stack.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
 - Checkov Version 2.0.1123

**Additional context**

**Comment by ankon** [comment]
I would expect to flag this generically, I'm a bit concerned that this might be a problem related to nested stacks though. I'll try to build a reproduction case over the coming days ...

**Comment by gruebel** [comment]
Hi @ankon we actually don't validate a CloudFormation template for having the correct syntax. I highly recommend to use the AWS CLI to do the validation for you
```shell
aws cloudformation validate-template --template-body file://template.yaml
```
