### ISSUE TITLE
Multiple path in --skip-path flag

### ISSUE THREAD

**Issue by abdurrahman** [bridgecrewio/checkov#2987]
Hello, I simply wanted use `--skip-path` flag for more than one path. What I want is describe it once instead of using the flag multiple times. 

I've tried `--skip-path /Database, /Tests` didnt work
I've tried `--skip-path ["/Database", "/Tests"]` didnt work
I've tried `--skip-path ["/Database/Dockerfile", "/Tests/Dockerfile"]` didnt work

I've tried `--skip-path "/Database/Dockerfile" --skip-path "/Tests/Dockerfile"` and it **worked**. :+1:
I've tried `--skip-path "/Database" --skip-path "/Tests"` and it **worked**. :+1:

**Isn't possible to give multiple path in one flag like** ["/path-1", "/path-2", "/path-3"] ?
I haven't figure it out when its mentioned in the documentation [_Can be specified multiple times._](https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html#cli-command-reference)

**Examples**
```shell
docker run --tty --volume "$(System.DefaultWorkingDirectory)/src":/scan bridgecrew/checkov --directory /scan --framework dockerfile --skip-path /Database /Tests
```

**Version**
 - Checkov Version [ 2.0.1079]

**Additional context**
Maybe its better adding some sample to how to use in to documentation would be useful for those who don't know.

**Comment by gruebel** [comment]
hi @abdurrahman great question, you just have to use the flag several times 🙂 ex.
```shell
checkov -d /scan --framework dockerfile --skip-path /Database --skip-path /Tests
```
