### ISSUE TITLE
Configuration via file

### ISSUE THREAD

**Issue by twmartin** [bridgecrewio/checkov#299]
**Describe the solution you'd like**

I feel like it would be powerful to be able to configure `checkov` options via file rather than simply CLI options.

**Additional context**

I've had good experiences working with the yamllint configuration file (https://github.com/adrienverge/yamllint#features). This could be a decent source of inspiration.

**Comment by schosterbarak** [comment]
not bad. indeed a requested feature. Having each one of the checkov CLI options accessible via a file will defiantly help for CI/CD use cases. Would you like to contribute that piece

**Comment by twmartin** [comment]
I'm certainly willing to contribute the feature. I won't be disappointed if someone else beats me to the punch either.

**Comment by angatha** [comment]
@twmartin do you still work on this?

**Comment by twmartin** [comment]
> @twmartin do you still work on this?

I am not currently working on this.

**Comment by angatha** [comment]
So question to everybody, which style would you linke? The yaml one from yamllint or one using configparser? (Or both?)

**Comment by tymartin-novu** [comment]
> So question to everybody, which style would you linke? The yaml one from yamllint or one using configparser? (Or both?)

I'm super ignorant on configparser, but I do like think yaml would be a solid choice.

Some elegance going the yamllint route here is that folks could hit the `checkov` config yaml file with `yamllint` for all the linting glory. Generally, if audiences are using `checkov` for their Cloudformation templates, they are most likely already writing those templates in yaml, and may already be running `yamllint` or could benefit by doing so.

**Comment by JeanFred** [comment]
Looks like this was implemented by  #1248
