### ISSUE TITLE
Allow file exclusion on directory scan

### ISSUE THREAD

**Issue by twmartin** [bridgecrewio/checkov#300]
**Describe the solution you'd like**
Allow specific files to be excluded from a directory scan

e.g. `checkov -d ./cfn/ --exclude-file bad-cfn-template.yml,worse-cfn-template.yml`

This can help in situations where teams may wish to start reaping the benefits of `checkov` scans, but perhaps they have a handful of files in a directory that require more time to get "checkov-compliant".

**Comment by antonydenyer** [comment]
You can use `--skip-path` https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

**Comment by saloyiana** [comment]
> --skip-path

I did try it but i didn't work. 
Does it work with as expected ?
