### ISSUE TITLE
Issues with AWS S3 Checks for Versioning, Bucket Logging, Encryption

### ISSUE THREAD

**Issue by kairu97** [bridgecrewio/checkov#3002]
I have made a Terraform Script for AWS S3 Buckets. I am now using Terraform Binary version 4.4.0 of AWS. 

```
resource "aws_s3_bucket" "S3BucketForCloudTrail" {
  bucket = "cloudtrail-access-${data.aws_caller_identity.current.account_id}"
  force_destroy = true
}

resource "aws_s3_bucket_logging" "cloudtrail_s3_data_logging" {
  bucket = aws_s3_bucket.S3BucketForCloudTrail.id

  target_bucket = aws_s3_bucket.S3BucketForCloudTrail.id
  target_prefix = "log/cloudtrail_s3_access/"
}

resource "aws_s3_bucket_versioning" "cloudtrail_bucket_versioning_config" {
  bucket = aws_s3_bucket.S3BucketForCloudTrail.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "s3_cloudtrail_bucket_encryption_config" {
  bucket = aws_s3_bucket.S3BucketForCloudTrail.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.cmk-s3-cloudtrail.key_id
      sse_algorithm     = "aws:kms"
    }
  }
}
```

What happens with this is that the checks cannot detect that it has already been added. Here are the codes for checking: [CKV_AWS_18], [CKV_AWS_21], [CKV_AWS_19], and [CKV_AWS_145].

I am currently using CheckOV version 2.0.1158.

I am hoping that there is support for the new Terraform binary for AWS.

**Comment by achiar99** [comment]
Hello @kairu97, thanks for raising an issue.
We’ve ran checkov on the provided resources and got the following results (attach screenshot).
![Uploading Screen Shot 2022-05-24 at 10.08.50.png…]()

Can you please give more details about the output you’re receiving so we can address the issue?

**Comment by kairu97** [comment]
Hi.

I can't see the attached screenshot. I am running this on Jenkins using
Rocky Linux EC2. I have to skip the S3 tests.

Regards,


KYLE KRISTOFFER V. ATENDIDO
*EMAIL:* ***@***.***

**Comment by achiar99** [comment]
Hello @kairu97, thanks for raising an issue.
We’ve ran checkov on the provided resources and got the following results (attach screenshot).
![Uploading Screen Shot 2022-05-24 at 10.08.50.png…]()

Can you please give more details about the output you’re receiving so we can address the issue?

**Comment by kairu97** [comment]
How come I can't see the screenshot on your side. Anyway, I am running CheckOV on Rocky Linux EC2. 
![image](https://user-images.githubusercontent.com/63029919/170018649-6851827e-745f-4f36-8b09-799ff9ed57b4.png)


This is the CheckOV Version running inside the instance. 
![image](https://user-images.githubusercontent.com/63029919/170018893-46ecfab1-a045-407f-bf89-97e3bd04bfe1.png)

**Comment by achiar99** [comment]
sorry i cant upload it.
I just copied your tf file and run checkov and these are the results- 
terraform scan results:

Passed checks: 4, Failed checks: 0, Skipped checks: 0

Check: CKV_AWS_18: "Ensure the S3 bucket has access logging enabled"
        PASSED for resource: aws_s3_bucket.S3BucketForCloudTrail
        File: /s3.tf:1-4
        Guide: https://docs.bridgecrew.io/docs/s3_13-enable-logging
Check: CKV_AWS_19: "Ensure all data stored in the S3 bucket is securely encrypted at rest"
        PASSED for resource: aws_s3_bucket.S3BucketForCloudTrail
        File: /s3.tf:1-4
        Guide: https://docs.bridgecrew.io/docs/s3_14-data-encrypted-at-rest
Check: CKV_AWS_145: "Ensure that S3 buckets are encrypted with KMS by default"
        PASSED for resource: aws_s3_bucket.S3BucketForCloudTrail
        File: /s3.tf:1-4
        Guide: https://docs.bridgecrew.io/docs/ensure-that-s3-buckets-are-encrypted-with-kms-by-default
Check: CKV_AWS_21: "Ensure all data stored in the S3 bucket have versioning enabled"
        PASSED for resource: aws_s3_bucket.S3BucketForCloudTrail
        File: /s3.tf:1-4
        Guide: https://docs.bridgecrew.io/docs/s3_16-enable-versioning

**Comment by kairu97** [comment]
Ohhhh. Looks like it's a problem with how CheckOV scans the terraform directory. This is how my directory looks like. 

```
.
├── .DS_Store
├── .gitignore
├── .terraform.lock.hcl
├── Jenkinsfile
├── LayoutDiagram-Setup.png
├── LayoutDiagram.drawio
├── README.md
├── backend.tf
├── dev.tfvars
├── dev.tfvars.bak
├── install_apache.sh
├── main.tf
├── module
│   ├── alb
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── cloudtrail
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── cloudwatch
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── config
│   │   ├── main.tf
│   │   ├── mas-trmg.tf
│   │   ├── mas-trmg.tf.bak
│   │   ├── nist-csf.tf
│   │   ├── nist-csf.tf.bak
│   │   └── variables.tf
│   ├── ec2
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── iam
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── rds
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── s3
│   │   ├── main.tf
│   │   └── outputs.tf
│   ├── security_group
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   ├── security_hub
│   │   └── main.tf
│   └── vpc
│       ├── main.tf
│       ├── outputs.tf
│       └── variables.tf
├── outputs.tf
├── packer
│   ├── README.md
│   ├── install_apache_1.sh
│   ├── install_apache_2.sh
│   ├── packer-1.json
│   ├── packer-1.json.pkr.hcl
│   └── packer-2.json
├── provider.tf
└── variables.tf
```

**Comment by kairu97** [comment]
I was able to determine that this has something to do with the jenkins user. It is Jenkins that is having the problem @achiar99 . I'll try to troubleshoot this. Thank you so much for your help!

**Comment by achiar99** [comment]
good luck!
