### ISSUE TITLE
CKV_AWS_111 incorrectly triggered

### ISSUE THREAD

**Issue by JavaScriptBach** [bridgecrewio/checkov#3015]
**Describe the issue**
Checkov tells me that the following Terraform configuration fails CKV_AWS_111:

```
data "aws_iam_policy_document" "ecr-push-oidc" {
  statement {
    sid = "1"
    actions = [
      "ecr:BatchCheckLayerAvailability",
      "ecr:CompleteLayerUpload",
      "ecr:InitiateLayerUpload",
      "ecr:PutImage",
      "ecr:UploadLayerPart",
    ]
    resources = [
      "*",
    ]
  }
}
```
This a standard set of permissions to push an image to ECR, as documented in https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-push.html. Furthermore, none of the permissions are outlined in https://docs.bridgecrew.io/docs/ensure-iam-policies-do-not-allow-write-access-without-constraint.

**Version (please complete the following information):**
 - Checkov Version [e.g. 22] 2.0.983

**Comment by gruebel** [comment]
feel free to write here again or open a new ticket, if you still have questions connected to the check.
