### ISSUE TITLE
Incorrect file_path when Checkov is executed in an AWS lambda

### ISSUE THREAD

**Issue by pinaki16shaw** [bridgecrewio/checkov#3047]
**Describe the issue**
We are executing Checkov from a Python script in an AWS lambda execution environment (Runtime: Python 3.7). Source code is downloaded from Gitlab and stored in the '/tmp/' directory of the lambda. Sample directory structure:
/tmp/projectA/folder1

Checkov is run with the command:
**_checkov -d /tmp/projectA -o json --no-guide --framework terraform --external-checks-dir /var/task/custom_policies -c CKV_AWS_24,CKV_AWS_77,CKV_AWS_34,CKV_AWS_74_**

If _project A_ has a vulnerable TF named A.tf, the following attributes are expected as a part of the Checkov output:
       "file_path": "/folder1/A.tf",
        "file_abs_path": "/tmp/projectA/folder1/A.tf",
        "repo_file_path": "/tmp/projectA/folder1/A.tf",
        "file_line_range": [
          1,
          4
        ]

However, Checkov is behaving erratically in some subsequent lambda invocations. For the next lambda invoked for a scan on project B where source code resides in: /tmp/projectB/folder2

Checkov is run with the command:
**_checkov -d /tmp/projectB -o json --no-guide --framework terraform --external-checks-dir /var/task/custom_policies -c CKV_AWS_24,CKV_AWS_77,CKV_AWS_34,CKV_AWS_74_**

If _project B_ has a vulnerable TF named B.tf, the following attributes are **_incorrectly_** provided as a part of the Checkov output:
       "file_path": "/../projectA/folder1/A.tf",
        "file_abs_path": "/tmp/projectA/folder1/A.tf",
        "repo_file_path": "/tmp/projectA/folder1/A.tf",
        "file_line_range": [
          1,
          4
        ]

**_Expected response:_**
       "file_path": "/folder2/B.tf",
        "file_abs_path": "/tmp/projectB/folder2/B.tf",
        "repo_file_path": "/tmp/projectB/folder2/B.tf",
        "file_line_range": [
          1,
          4
        ]

We are cleaning up the /tmp/ folder before and after each scan so ruling out the possibilty of residual files from previous lambda executions. Also, we do not experience this issue in Checkov version 2.0.67. Have seen this with 2.0.1145 and 2.0.1182 so assuming most later versions have this issue.

**Comment by schosterbarak** [comment]
Hey @pinaki16shaw, we have a managed solution at [bridgecrew](https://bridgecrew.io/) that is already running Checkov correctly using a serverless approach. You don't need to host it on your cloud). You can try it out (starting for [free](https://bridgecrew.io/pricing/)) and move to pay as you go, model as you scale your code scanning requirements. 

Checkov was intended to be used as a CLI/CI tool. For managed cloud orchestrated solutions, we suggest using [bridgecrew.cloud](https://bridgecrew.cloud/)

I am closing this issue for now.

**Comment by pinaki16shaw** [comment]
@schosterbarak Thanks for your reply and the references to the managed solution for serverless.
While we look into the managed solution, could you please reopen the issue and still look into it and let us know if its a known issue?
