### ISSUE TITLE
checkov skips scaning files if it cannot parse file

### ISSUE THREAD

**Issue by harishachappa** [bridgecrewio/checkov#3065]
**Describe the issue**
Checkov skips terraform file when it can't parse a file. When you are using checkov in gitlab ci pipeline with junitxml output, it will be better to include such erros in 'Errors' list instead of ignoring them.

**Examples**
```
resource "aws_alb" "alb" {
  name                             = "foobar-nlb"
  load_balancer_type               = "network"
  enable_cross_zone_load_balancing = true

  tags = "${merge("${var.custom_tags}", tomap({
     Name = "foobar-nlb"
  )}"
}
```

**Version (please complete the following information):**
 - 2.0.1162

**Comment by nimrodkor** [comment]
Hey @harishachappa !
I'm not sure about the behavior here - not everyone would like to fail the entire scan on malformed files. The current behavior takes that into account, however, we've recently added the option to fail on parsing errors - #3027 .
So IMO, it would be best to add right before this line, if this option is set, an error per parsing error the report already has:
https://github.com/bridgecrewio/checkov/blob/cea2c48c64b2c2528ae7ab4deb24827c06687bc5/checkov/common/output/report.py#L443

We're open to contributions here!
