### ISSUE TITLE
Error parsing terraform files when comment is present

### ISSUE THREAD

**Issue by gone-for-coding** [bridgecrewio/checkov#3071]
**Describe the issue**
When testing a terraform file with a certain valid structure checkov fails with "error parsing file" and prints a control char after the file name. When a comment is removed, the file is parsed fine.

**Examples**
```tf
locals {
  servers = [
    # Test
    for serverkey in local.configjson.Servers : merge(
      { a = "b" }
    )
  ]
}
```
Results in
```
root@8ad4bb9bf907:/code# checkov -f test.tf

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.1206

terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file /code/test.tfֿ
```

- Note the strange char after test.tf.
- When you remove "# Test" it works.
- checkov exits with RC 0 despite the issue!

**Version (please complete the following information):**
 - 2.0.1206

**Comment by gruebel** [comment]
hi @gone-for-coding thanks for reporting, I checked it briefly and it is an issue with our parser. I will try to fix it in the next days 🚀

**Comment by niklash-dev** [comment]
If you leave out the leading space characters, before the comment, it seems to work:

```hcl
locals {
  servers = [
# Test
    for serverkey in local.configjson.Servers : merge(
      { a = "b" }
    )
  ]
}
```
