### ISSUE TITLE
Add cli switch to inspect a file

### ISSUE THREAD

**Issue by rpdelaney** [bridgecrewio/checkov#31]
**Is your feature request related to a problem? Please describe.**
We would like to use `checkov` in conjunction with [pre-commit](https://pre-commit.com) so that infra engineers can be notified of misconfigurations locally (and before `checkov` is executed in CI). 

However, it seems `checkov` can only be run on directories. That means we cannot adopt this workflow without running static analysis on every terraform file in the repo every time we make a commit with any terraform changes -- or, at best, every terraform file that shares a path with any terraform file being committed.

**Describe the solution you'd like**
A command-line switch such as `-f` or `--file` that accepts a path to an individual file to be analyzed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by schosterbarak** [comment]
Thank you @rpdelaney for submitting this feature request! 
A great use case for Checkov.

We'd be happy if you'd contribute a piece of code to make that possible. 
It would probably include an addtional code pieces at the following files: 
[bin/checkov](https://github.com/bridgecrewio/checkov/blob/master/bin/checkov) 
[checkov/terraform/parser.py](https://github.com/bridgecrewio/checkov/blob/3a3ec27bf1b6b1ceacaa8cf1a5eb414f7a1dcf33/checkov/terraform/parser.py#L11)
[checkov/terraform/runner.py](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/runner.py)

**Comment by DmitriyLyalyuev** [comment]
To integrate checkov with pre-commit I've made PR: https://github.com/bridgecrewio/checkov/pull/36

Used in my everyday work with no issues.

**Comment by schosterbarak** [comment]
Thank you @DmitriyLyalyuev ! much appreciated :)

**Comment by rpdelaney** [comment]
#36 will help with creating a pre-commit hook pinned to releases from this repo. Thanks for that. Unfortunately it PR does not seem to address the problem I raised in this issue: the hook will still run static analysis on files that are not being committed.

**Comment by schosterbarak** [comment]
Thank you @rpdelaney . Re-opening then.
We would love a contribution in that area!

**Comment by schosterbarak** [comment]
Hey @rpdelaney, I've just pushed a commit to solve this one:
https://github.com/bridgecrewio/checkov/pull/53
Can you please take a look?
