### ISSUE TITLE
How to Check a Data Source connected to a Resource

### ISSUE THREAD

**Issue by mfollypp** [bridgecrewio/checkov#3109]
**Describe the issue**
I want to check if the attribute "group" of the resource "azuredevops_group_membership" refers to a data source "azuredevops_group" with the attribute "name" = "Build Administrators" for example.

**Examples**
Snippet from [terraform registry](https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/group_membership)
```terraform
data "azuredevops_group" "example" {
  project_id = azuredevops_project.example.id
  name       = "Build Administrators"
}

resource "azuredevops_group_membership" "example" {
  group = data.azuredevops_group.example.descriptor
  members = [
    azuredevops_user_entitlement.example.descriptor
  ]
}
```
I tryed creating a custom policy in python but I didn't understand how I could make this work, I was only able to create a policy to check if the attribute name of the data azuredevops_group was equal to "Build Administrators":

```python
from typing import Dict, List, Any

from checkov.terraform.checks.data.base_check import BaseDataCheck
from checkov.common.models.enums import CheckResult, CheckCategories

class NoBuildAdministratorCreated(BaseDataCheck):
    def __init__(self) -> None:
        name = 'Ensure no build administrator is created on file'
        id = "CKV_ADO_9000"
        supported_data = ["azuredevops_group"]
        categories = [CheckCategories.GENERAL_SECURITY]
        super().__init__(name=name, id=id, categories=categories, supported_data=supported_data)

    def scan_data_conf(self, conf: Dict[str, List[Any]]) -> CheckResult:

        if (conf.get("name", "Build Administrators")):
            return CheckResult.FAILED
    
        return CheckResult.PASSED

check = NoBuildAdministratorCreated()
```

**Version (please complete the following information):**
 - Checkov Version 2.0.1223

**Additional context**
My goal is to check if people are creating admin groups inside of a terraform file. I'm kinda new to reading documentations and code libraries of open source projects so I'm having a bit of a hard time understanding how to use the checkov python scan functions to create custom policies. So any advice or code example to help me understand better how it works and what is this **conf** would be much appreciated, thanks!

**Comment by gruebel** [comment]
hey @mfollypp thanks for reaching out. You definitely need to do it with a Graph (YAML) check. I was surprised that we already supported connection checks, but not attribute checks. So, with my PR your use case should be possible and I used your goal as an example for the docs, I hope it is ok 😉 https://github.com/bridgecrewio/checkov/pull/3126/files#diff-27a9da9868e7467aaec794c04c552285b1185b128b7f19db8daf65599e70101f

**Comment by mfollypp** [comment]
Hey @gruebel thanks! I'm glad it turned out as something useful! 🙂

**Comment by timrupe** [comment]
hey @gruebel Sorry to dig up such an old issue, but is this still today not possible to do in Python? For example, let's say we want to check that a property in a databricks_schema matches up to a property in its databricks_catalog, but with some string manipulations that aren't available in terraform. Can the python code get ahold of the graph for this, or is there some other way of doing it?

**Comment by gruebel** [comment]
Yeah, nowadays it is possible to access the graph in a Python check via `self.graph`.
