### ISSUE TITLE
baseline output can change resource order for each run

### ISSUE THREAD

**Issue by james-mullen-bjss** [bridgecrewio/checkov#3119]
If I generate a baseline file and I have then made some improvements to my Terraform code and I run the baseline again. What I am finding is that the order of the resources for each file can often change which then shows up as a diff against the prevous baseline file - when in reality nothing has change but the order of the resources in the findings array in the baseline output file 

I was wondering could the findings array just be sorted before being output? Then the resource order should be fixed and any actual diffs should be real changes to check_ids (which is sorted already) or new resources being added?

e.g. this is a diff from two runs of generating a baseline file nothing has actually change just resources moved around in the array.

```
@@ -100,13 +100,12 @@
             "file": "/main.tf",
             "findings": [
                 {
-                    "resource": "aws_s3_bucket.canary_artifacts",
+                    "resource": "aws_s3_bucket.backups",
                     "check_ids": [
                         "CKV2_AWS_6",
                         "CKV_AWS_144",
                         "CKV_AWS_145",
-                        "CKV_AWS_18",
-                        "CKV_AWS_21"
+                        "CKV_AWS_18"
                     ]
                 },
                 {
@@ -119,12 +118,13 @@
                     ]
                 },
                 {
-                    "resource": "aws_s3_bucket.lambdas",
+                    "resource": "aws_s3_bucket.canary_artifacts",
                     "check_ids": [
                         "CKV2_AWS_6",
                         "CKV_AWS_144",
                         "CKV_AWS_145",
-                        "CKV_AWS_18"
+                        "CKV_AWS_18",
+                        "CKV_AWS_21"
                     ]
                 },
                 {
@@ -137,7 +137,7 @@
                     ]
                 },
                 {
-                    "resource": "aws_s3_bucket.backups",
+                    "resource": "aws_s3_bucket.lambdas",
                     "check_ids": [
                         "CKV2_AWS_6",
                         "CKV_AWS_144",
```

**Comment by gruebel** [comment]
hey @james-mullen-bjss thanks for reaching out! Yeah makes sense to order them, especially when added to your SCM.

**Comment by gruebel** [comment]
@james-mullen-bjss nice, happy to hear 😄
