### ISSUE TITLE
json output suddenly became a list 2 days ago

### ISSUE THREAD

**Issue by prabhu** [bridgecrewio/checkov#312]
**Describe the bug**
JSON output file has suddenly become a list since this commit https://github.com/bridgecrewio/checkov/blob/master/checkov/common/runners/runner_registry.py#L38

**To Reproduce**
1. Go to an terraform repo
2. Run cli command  with `-o json`
3. See error the resulting file

**Expected behavior**
Some discipline where the outputs are checked every build. If there is a breaking change it has to be communicated accordingly.

**Screenshots**

**Desktop (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by schosterbarak** [comment]
hey @prabhu this feature was requested here : https://github.com/bridgecrewio/checkov/issues/198

what i think we can do is put an object if its a list in a size of 1, and a list in other cases.

**Comment by prabhu** [comment]
@schosterbarak I am fine with the proposed work-around.

I think the feature request and the implementation does make sense. I have fixed scan to work with both list and dict object. But we might have broken other integrations out there so the suggested workaround is good.

**Comment by schosterbarak** [comment]
done: https://github.com/bridgecrewio/checkov/pull/326
