### ISSUE TITLE
Unable to load module when referencing a submodule

### ISSUE THREAD

**Issue by alexandrezanetti** [bridgecrewio/checkov#3141]
Hello, I'm using a Terraform Code with Modules from another Repo, and I have created a user/token for this download.

Terraform is working fine, but when I tried to use checkov to validate this main.tf which uses a source from another git, I received this error below.

[0/6]2022-06-29 01:18:00,393 [MainThread  ] [WARNI]  Unable to load module (source="git::https://{user}:{token}@github.{provider}.com/{repo}/terraform-helloworld-modules.git//modules" version="latest"): [Errno 2] No such file or directory: '/tf/.external_modules/github.{provider}.com/{repro}/terraform-helloworld-modules/HEAD/modules'

My problem, in this case, occurred because my customer is using one repo for terraform modules (common modules) in different subdirectories.

In this case, in main.tf we used a "//modules" to choose with the "module" we are using and because of this, the error occurred.

Can someone help me?

**Comment by gruebel** [comment]
hey @alexandrezanetti thanks for reaching out. Can you add an example of the `module` usage in one of the TF files. If there  are sensible data, just replace them with something 😄 then it is easier for me to reproduce it.

**Comment by alexandrezanetti** [comment]
Hi
Below you can see my main.tf
====================================================
module "storage_account" {
  source = "git::https://{user}:{token}@github.ibm.com/alexandre-zanetti/terraform-helloworld-modules.git//modules"
  #  name                     = var.storage_account_name
  #  resource_group_name      = var.resource_group_name
  #  location                 = var.location
}
====================================================

And below you can see my module zzzcheckov.tf:
====================================================
resource "azurerm_storage_account" "storage_account" {
  name                     = var.storage_account_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_replication_type = var.account_replication_type
  account_tier             = var.account_tier
}
====================================================

**Comment by gruebel** [comment]
just to clarify it is exactly written with the placeholders for user and token or you just removed them for posting it here
```hcl
module "storage_account" {
  source = "git::https://{user}:{token}@github.ibm.com/alexandre-zanetti/terraform-helloworld-modules.git//modules"
  ...
} 
```
and not something like
```hcl
module "storage_account" {
  source = "git::https://user123:token123@github.ibm.com/alexandre-zanetti/terraform-helloworld-modules.git//modules"
  ...
} 
```
because the error you get has nothing to do with accessing the submodule, we just couldn't download the repo at all.

**Comment by alexandrezanetti** [comment]
Hi, I have only remove my credentials, because here is public.
 I'm using like you share:
module "storage_account" {
  source = "git::https://user123:token123@github.ibm.com/alexandre-zanetti/terraform-helloworld-modules.git//modules"
  ...
}

**Comment by gruebel** [comment]
hmmm 🤔 I created a private repo with a simple module and it all works well. I think something is blocking the download. Can you run the `checkov` command with `DEBUG` logging enabled, maybe we get a bit more info, what could be wrong.

```shell
LOG_LEVEL=DEBUG checkov -d . --download-external-modules true --framework terraform
```

**Comment by alexandrezanetti** [comment]
Hi Gruebel,

Have you create a subdirectory for example moduloRG, moduleStorageAccount and try to use checkov  validations (consequently download submodules)?

"git::https://user123:token123@github.ibm.com/alexandre-zanetti/terraform-helloworld-modules.git//moduleStorageAccount"

That's the problem.

Let me know if you could reproduce this.

**Comment by gruebel** [comment]
yeah I did 🙂 
```hcl
module "bucket" {
  source = "git::https://user123:token123@github.com/gruebel/private-tf-modules.git//bucket"

  name = "anton-1234567890"
}
```
and then the result was
```shell
       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.1.20 

terraform scan results:

Passed checks: 5, Failed checks: 6, Skipped checks: 0

Check: CKV_AWS_41: "Ensure no hard coded AWS access key and secret key exists in provider"
	PASSED for resource: aws.default
	File: /main.tf:1-4
	Guide: https://docs.bridgecrew.io/docs/bc_aws_secrets_5
Check: CKV_AWS_70: "Ensure S3 bucket does not allow an action with any Principal"
	PASSED for resource: module.storage_account.aws_s3_bucket.this
	File: /.external_modules/github.com/gruebel/private-tf-modules/HEAD/bucket/main.tf:1-3
	Calling File: /main.tf:6-10
	Guide: https://docs.bridgecrew.io/docs/bc_aws_s3_23

...
```

**Comment by alexandrezanetti** [comment]
Hi Gruebel,
 
  Next Monday I asked to Fernando (who works with me) to reexecute and share the result in this issue.

   Sorry about that, because I'm on vacation (since last Friday night) and I'm abroad of my country.

**Comment by alexandrezanetti** [comment]
Looking for your command, I forget to use "--framework terraform".

I will ask Fernando to try to execute with this.

**Comment by dpradhan20** [comment]
Hello ,

Even I am facing the same issue . 

Checkov works fine with below repo structure (for terraform common modules )  
![image](https://user-images.githubusercontent.com/109503618/179455544-c5839ce8-763f-4655-9a8e-4bc9b50dc664.png)


whereas it fails when the repo is structure is like below . 

![image](https://user-images.githubusercontent.com/109503618/179455773-c5dd8831-6ec5-4009-971f-47c483b7d7e2.png)

We are following the 2nd repo structure to maintain all our common terraform modules so can someone help ?

**Comment by thiagoha** [comment]
We are following the 2nd repo structure to maintain only main.tf, all our common terraform modules following the first one.

**Comment by nmarian85** [comment]
What worked for me is to create a dummy TF module which will download all the modules you have in the remote repo. Since we specify the top level folder in the repo, then all modules are downloaded locally and cached.

```bash
# apparently when specifying a module name in the Git URL checkov can no longer parse the token
module "checkov_dummy_download_module" {
  source = "git::https://oauth2:xxx@yyy/path/to/git/repo.git//?ref=v1"
}
```

Once that is done, checkov will no longer follow the git URL to download the sub-modules in the remote repo but use the ones it downloaded locally.

```bash
module "my_module" {
  source = "git::https://oauth2:xxx@yyy/path/to/git/repo.git//my-module?ref=v1"
}
```

**Comment by efernandes-dev-ops** [comment]
We are experiencing a similar issue and we think it's due to how we tag our terraform modules. Unfortunately we have a mono-repo which consists of all our modules. These modules make use of external modules. When we enable the flag to download external modules we get the following message back - 

```
2023-02-15 11:43:00,507 [MainThread  ] [DEBUG]  Cache miss for git@github.com:xxxxxx-Infra/terraform-modules.git//modules//account?ref=account-v1.0.0:latest
2023-02-15 11:43:00,548 [MainThread  ] [WARNI]  Module git@github.com:xxxxxx-Infra/terraform-modules.git//modules//account?ref=account-v1.0.0:latest failed to load via <class 'checkov.terraform.module_loading.loaders.github_loader.GithubLoader'>
2023-02-15 11:43:00,[54](https://github.com/xxxxxx-Infra/aws-accounts/actions/runs/4183495950/jobs/7247921624#step:8:55)9 [MainThread  ] [WARNI]  Unable to load module (git@github.com:xxxxxx-Infra/terraform-modules.git//modules//account?ref=account-v1.0.0:None): invalid git url
```

**Comment by oStenvall** [comment]
Experiencing the same issue
```txt
2024-03-26 14:50:59,619 [MainThread  ] [WARNI]  Unable to load module - source: 
git::https://gitlab.private.com/common-infra/modules.git//security/iam/oidc-role?ref=v2.1.6, version: latest, error: 
[Errno 2] No such file or directory: '/builds/project-infra/project-
terragrunt/modules/.external_modules/gitlab.private.com/common-infra/modules/v2.1.6/security/iam/oidc-role'
``` 
```hcl
module "iam_oidc_role" {
  source = "git::https://gitlab.private.com/common-infra/modules.git//security/iam/oidc-role?ref=v2.1.6"
  ...
  ...
}
```

Is it possible to reopen this issue or do you know a solution? @gruebel
