### ISSUE TITLE
Checkov not produces kubernetes scan results while scanning Kubernetes json file

### ISSUE THREAD

**Issue by karthickmuthuraj** [bridgecrewio/checkov#3150]
**Describe the issue**
Checkov produces not proper output when scanning a kubernetes JSON file in the version 2.0.1121.  We have observed proper output was not produced by checking Kubernetes JSON file scanning older version of checkov and got different results.  We would like to understand is Kubernetes json scan was disabled in the checkov product in the latest version ?

**Examples**
We couldn't able to share the file of JSON due to data privacy.

We used deployment kubernetes JSON File 

sample syntax in very high level :- 

"kind": "Deployment",
    "apiVersion": "apps/v1",

when we try to scan in 2.0.1121  >>> only could find the failed checks in secret scan results "CKV_SECRET_6" and couldn't find the kubernetes can results.
same we try to scan in 2.0.1000 >>>> we got kubernetes scan results like "Passed checks: 82, Failed checks: 7, Skipped checks: 0" with secret scan results without any issues..

**Version (please complete the following information):**
 - Current Checkov Version :- 2.0.1121 [we are using at our end] [Plan to upgrade in nearby future]

**Additional context**
Require your asusual valuable support to address our concern and let us know for any other additional inputs at our end. Thank you

**Comment by gruebel** [comment]
hey @karthickmuthuraj thanks for reaching out. You found indeed an error, which accidentally slipped in 🙈 I created a fix and it should be released in the next days 🚀
