### ISSUE TITLE
Not able to supress check for cloud formation file (In JSON format)

### ISSUE THREAD

**Issue by sachinguptahsc** [bridgecrewio/checkov#3170]
Hello,

We are following below thread to supress some issue in cloud formation template:

https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html

We tried to put Metadata values in resource section, but it is not supressing that issue.

We are using latest version of checkov. following configuration is used to suppress the issue:
```
"Metadata": {
			"checkov": {
				"skip": [
					{
						"id": "CKV_AWS_59",
						"comment": "Public API"
					}
				]
			}
		}
```

**Comment by sachinguptahsc** [comment]
@gruebel thanks for the reply. Here serverless framework is being used to generate cloud formation template JSON. Resultant resource looks something like that:
```
"SampleMethod": {
			"Type": "AWS::ApiGateway::Method",
			"Properties": {
				......
				......
			},
			"Metadata": {
				"checkov": {
					"skip": [
						{
							"id": "CKV_AWS_59",
							"comment": "Public API"
						}
					]
				}
			}
		}
```

**Comment by gruebel** [comment]
if it is still not working, feel free to adding here more info.
