### ISSUE TITLE
docs are garbled

### ISSUE THREAD

**Issue by andresvia** [bridgecrewio/checkov#318]
At: https://github.com/bridgecrewio/checkov/commit/a01e8f4330c8bd171ec7fbffd8533366cdc7fd7e

![Screen Shot 2020-06-03 at 2 34 17 PM](https://user-images.githubusercontent.com/4180794/83691872-c9ae8280-a5a7-11ea-9284-6d893372a813.png)

**Comment by schosterbarak** [comment]
fixed! thank you :)
