### ISSUE TITLE
Issue in using --prisma-api-url 

### ISSUE THREAD

**Issue by swapneil** [bridgecrewio/checkov#3181]
**Describe the issue**
I am trying to integrate checkov in CICD and trying to use the prisma URL(Licensed to our organisation) using the access key and secret key in --bc-api-key but its giving unauthorized error.

What specific endpoint do we need to provide in the --prisma-api-url so that it works?

**Comment by mikeurbanski1** [comment]
Hi Swapneil. It should be a value like `https://api.prismacloud.io`, `https://api3.prismacloud.io`, etc.

Your API key should be your access key and secret in the format `ACCESS_KEY::SECRET_KEY`. It must be a developer or a sysadmin token.
