### ISSUE TITLE
CKV_AZURE_110 purge protection not handling input variable default

### ISSUE THREAD

**Issue by nbjohnson** [bridgecrewio/checkov#3187]
**Describe the issue**
Check ID: CKV_AZURE_110
For the key vault purge_protection_enabled variable the logic doesn't seem to handle defaults from a variable, only a hardcoded true value

**Examples**
The following configuration which defaults to true fails the check:
main.tf
```
purge_protection_enabled = var.purge_protection_enabled
```

variables.tf
```
variable "purge_protection_enabled" {
  type = bool
  default = true
}
```

While hardcoding the configuration works:
main.tf
```
purge_protection_enabled = true
```

Is it possible to modify the logic to properly account for the passed in default value that satisfies the check?

**Version (please complete the following information):**
 - Checkov Version 2.1.36

**Comment by gruebel** [comment]
hey @nbjohnson, thanks for reaching out. I tried following config with the latest version and passes
```hcl
variable "purge_protection_enabled" {
  type = bool
  default = true
}

resource "azurerm_key_vault" "ok" {
  name                     = "example"
  location                 = azurerm_resource_group.ok.location
  resource_group_name      = azurerm_resource_group.ok.name
  tenant_id                = data.azurerm_client_config.current.tenant_id
  sku_name                 = "premium"
  purge_protection_enabled = var.purge_protection_enabled
}
```
and it results in
```shell
Check: CKV_AZURE_110: "Ensure that key vault enables purge protection"
        PASSED for resource: azurerm_key_vault.ok
        File: /main.tf:10-17
        Guide: https://docs.bridgecrew.io/docs/ensure-that-key-vault-enables-purge-protection
```
is your config maybe more complex, because such a simple default variable to resource reference shouldn't be issue.
