### ISSUE TITLE
Auto generated documentation is missing

### ISSUE THREAD

**Issue by jaksky** [bridgecrewio/checkov#320]
**Describe the bug**
Not sure if you are aware but your autogenerated documentation is not there https://github.com/bridgecrewio/checkov/blob/master/docs/3.Scans/resource-scans.md
And really some explanation why is sth bad would improve the project to the next level

**To Reproduce**
2. Run cli command  '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by schosterbarak** [comment]
Thank you! fixed :)
