### ISSUE TITLE
Move CLI output summary to the bottom of the output

### ISSUE THREAD

**Issue by tsmithv11** [bridgecrewio/checkov#3222]
**Describe the issue**
If you have more than a few failed checks, it can be difficult to scroll to the top to see the summary or in a terminal, it may even be cut off. Can we move the summary to the bottom after the policy violations?

**Comment by nimrodkor** [comment]
Sensational! I love this. 
The relevant part of our code that needs to be refactored:
https://github.com/bridgecrewio/checkov/blob/5fdaf23e404b247f686ce6e07ec8f98032380a2d/checkov/common/output/report.py#L245
Would appreciate a contribution here!
