### ISSUE TITLE
CSV file blank - No results added

### ISSUE THREAD

**Issue by Gaurav-Jadhav** [bridgecrewio/checkov#3240]
**Describe the issue**
I am trying to generate an Output CSV file upon a successful scan It created CSV files but results are not getting added inside CSV.

**Additional context**
Please check attached image 
<img width="879" alt="issuecsv" src="https://user-images.githubusercontent.com/25578218/180148709-484acd15-c5d2-4bf7-ab9e-02108908ee59.png">

pipenv run bridgecrew --version
2.1.65

**Comment by gruebel** [comment]
hey @Gaurav-Jadhav thanks for reaching out. I actually found 2 problems, which needs to be fixed.

1. support for `--output-file-path` with `csv` output
2. actually add the packages to the generated `csv` output 😄 

Container image information will be added soon, so please don't be surprised about it being empty 😄
