### ISSUE TITLE
Checkov skip parameter gets ignored

### ISSUE THREAD

**Issue by jaksky** [bridgecrewio/checkov#3248]
**Describe the issue**
When running 

checkov  -f cf.yaml --skip-check MEDIUM

severity it doesn't produce any result even though I know that file contains critical severity. Filtering obviously doesn't work. According to manual "severity equal or higher will be included". Produces no results at all, providing false sense of security I consider a security hole.  Running file on cloudformation.

**Examples**
checkov  -f cf.yaml --skip-check MEDIUM

my file contains: CKV_AWS_115, CKV_AWS_192, CKV_AWS_86, CKV_AWS_116

**Version (please complete the following information):**
 - Checkov Version 2.1.67

**Additional context**

**Comment by gruebel** [comment]
hey @jaksky thanks for reaching out. Severity related features, like skipping or even showing in the output only works with a valid API token.

**Comment by jaksky** [comment]
Ok, thanks for clarification. There were no mention of token in the documentation
