### ISSUE TITLE
Unable to install checkov

### ISSUE THREAD

**Issue by pravindhawas** [bridgecrewio/checkov#3267]
Unable to install checkov on windows. It is giving error:

"Could not find a version that satisfies the requirement checkov (from versions: )
No matching distribution found for checkov".

Please let me know how we can resolve this issue.

Please see the console output below:
PS C:\WINDOWS\system32> pip install checkov
Collecting checkov
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10054, 'An existing connection was forcibly closed by the remote host'))': /simple/checkov/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10054, 'An existing connection was forcibly closed by the remote host'))': /simple/checkov/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10054, 'An existing connection was forcibly closed by the remote host'))': /simple/checkov/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10054, 'An existing connection was forcibly closed by the remote host'))': /simple/checkov/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10054, 'An existing connection was forcibly closed by the remote host'))': /simple/checkov/
  Could not find a version that satisfies the requirement checkov (from versions: )
No matching distribution found for checkov

**Comment by JamesWoolfenden** [comment]
Can you install anything else from pip?

**Comment by pravindhawas** [comment]
I have checked and No I cant install anything using pip

**Comment by JamesWoolfenden** [comment]
Ok then  i think you have an IT issue at your company blocking pip, you could try using the container https://hub.docker.com/r/bridgecrew/checkov instead but i imagine they have blocked that too. If that doesnt work you could build it from source. Id try getting your IT dept to open to pip or maybe its available in some controlled way?

**Comment by pravindhawas** [comment]
Thank you James for your quick response! I will check with our IT team.
