### ISSUE TITLE
CheckOV Fails CKV2_AWS_6

### ISSUE THREAD

**Issue by Ranjanijana20** [bridgecrewio/checkov#3278]
Check: CKV2_AWS_6: "Ensure that S3 bucket has a Public Access block"
        FAILED for resource: aws_s3_bucket.accesslog_bucket
        File: /tf.json:0-0
        Guide: https://docs.bridgecrew.io/docs/s3-bucket-should-have-public-access-blocks-defaults-to-false-if-the-public-access-block-is-not-attached

when I run the terraform file directly having resource block s3 checkov is passed but whenever I try to call it  from module it is CKV2_AWS_6 failing

**main.tf** 
```hcl
module "test" {
  source = "./module"
  
}
```

**module**
```hcl
locals {
  bucket_prefix = "testing-bucket-checkov"
}


resource "aws_s3_bucket" "accesslog_bucket" {
  bucket = "${local.bucket_prefix}-testing"

}


resource "aws_s3_bucket_versioning" "accesslog_bucket" {
  bucket = aws_s3_bucket.accesslog_bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  bucket                  = aws_s3_bucket.accesslog_bucket.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
```

**Comment by Ranjanijana20** [comment]
@gruebel when I run the terraform file directly having resource block s3 checkov is passed but whenever I try to call it from module it is CKV2_AWS_6 failing

**Comment by gruebel** [comment]
hey @Ranjanijana20 thanks for reaching out. Just to make sure, you are actually scanning the Terraform plan, right?

**Comment by Ranjanijana20** [comment]
yes @gruebel 
kindly find the plan output attached

Terraform used the selected providers to
generate the following execution plan.
Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # module.test.aws_s3_bucket.accesslog_bucket will be created
  + resource "aws_s3_bucket" "accesslog_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "testing-checkov-testing"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + cors_rule {
          + allowed_headers = (known after apply)
          + allowed_methods = (known after apply)
          + allowed_origins = (known after apply)
          + expose_headers  = (known after apply)
          + max_age_seconds = (known after apply)
        }

      + grant {
          + id          = (known after apply)
          + permissions = (known after apply)
          + type        = (known after apply)
          + uri         = (known after apply)
        }

      + lifecycle_rule {
          + abort_incomplete_multipart_upload_days = (known after apply)
          + enabled                                = (known after apply)
          + id                                     = (known after apply)
          + prefix                                 = (known after apply)
          + tags                                   = (known after apply)

          + expiration {
              + date                         = (known after apply)
              + days                         = (known after apply)
              + expired_object_delete_marker = (known after apply)
            }

          + noncurrent_version_expiration {
              + days = (known after apply)
            }

          + noncurrent_version_transition {
              + days          = (known after apply)
              + storage_class = (known after apply)
            }

          + transition {
              + date          = (known after apply)
              + days          = (known after apply)
              + storage_class = (known after apply)
            }
        }

      + logging {
          + target_bucket = (known after apply)
          + target_prefix = (known after apply)
        }

      + object_lock_configuration {
          + object_lock_enabled = (known after apply)

          + rule {
              + default_retention {
                  + days  = (known after apply)
                  + mode  = (known after apply)
                  + years = (known after apply)
                }
            }
        }

      + replication_configuration {
          + role = (known after apply)

          + rules {
              + delete_marker_replication_status = (known after apply)
              + id                               = (known after apply)
              + prefix                           = (known after apply)
              + priority                         = (known after apply)
              + status                           = (known after apply)

              + destination {
                  + account_id         = (known after apply)
                  + bucket             = (known after apply)
                  + replica_kms_key_id = (known after apply)
                  + storage_class      = (known after apply)

                  + access_control_translation {
                      + owner = (known after apply)
                    }

                  + metrics {
                      + minutes = (known after apply)
                      + status  = (known after apply)
                    }

                  + replication_time {
                      + minutes = (known after apply)
                      + status  = (known after apply)
                    }
                }

              + filter {
                  + prefix = (known after apply)
                  + tags   = (known after apply)
                }

              + source_selection_criteria {
                  + sse_kms_encrypted_objects {
                      + enabled = (known after apply)
                    }
                }
            }
        }

      + server_side_encryption_configuration {
          + rule {
              + bucket_key_enabled = (known after apply)

              + apply_server_side_encryption_by_default {
                  + kms_master_key_id = (known after apply)
                  + sse_algorithm     = (known after apply)
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }

      + website {
          + error_document           = (known after apply)
          + index_document           = (known after apply)
          + redirect_all_requests_to = (known after apply)
          + routing_rules            = (known after apply)
        }
    }

  # module.test.aws_s3_bucket_public_access_block.this will be created
  + resource "aws_s3_bucket_public_access_block" "this" {
      + block_public_acls       = true
      + block_public_policy     = true
      + bucket                  = (known after apply)
      + id                      = (known after apply)
      + ignore_public_acls      = true
      + restrict_public_buckets = true
    }

  # module.test.aws_s3_bucket_versioning.accesslog_bucket will be created
  + resource "aws_s3_bucket_versioning" "accesslog_bucket" {
      + bucket = (known after apply)
      + id     = (known after apply)

      + versioning_configuration {
          + mfa_delete = "Disabled"
          + status     = "Enabled"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Commands used 
terraform init
terraform plan -out tf.plan
terraform show -json tf.plan  > tf.json
checkov -f tf.json

**Comment by Ranjanijana20** [comment]
Added it also seems that when I try to skip as mentioned in the document 

resource "aws_s3_bucket" "foo-bucket" {
  region        = "ap-south-1"
    #checkov:skip=CKV_AWS_21:The bucket is a public static content host
  bucket        = "testingbucket"
  force_destroy = true
  acl           = "public-read"
}

I cannot see the skipped count nor it is being skipped 

By bridgecrew.io | version: 2.1.82 

@gruebel kindly find scan results 

terraform_plan scan results:

Passed checks: 8, Failed checks: 6, Skipped checks: 0

**Comment by Ranjanijana20** [comment]
+ Added Facing 
 
when I try to skip as mentioned exactly in the document

resource "aws_s3_bucket" "foo-bucket" {
region = "ap-south-1"
#checkov:skip=CKV_AWS_21:The bucket is a public static content host
bucket = "testingbucket"
force_destroy = true
acl = "public-read"
}

I cannot see the skipped count nor it is being skipped


By bridgecrew.io | version: 2.1.82


kindly find the terraform_plan scan results

Passed checks: 8, Failed checks: 6, Skipped checks: 0

Check: CKV_AWS_21: "Ensure all data stored in the S3 bucket have versioning enabled"
        FAILED for resource: aws_s3_bucket.foo-bucket
        File: /tf.json:0-0
        Guide: https://docs.bridgecrew.io/docs/s3_16-enable-versioning
