### ISSUE TITLE
Error parsing file where [ 'xxxx' ] usage

### ISSUE THREAD

**Issue by PoborcaMaciej** [bridgecrewio/checkov#3293]
Hi,

Checkov is failing to parse bicep files where face something like that
![image](https://user-images.githubusercontent.com/31986044/182367046-08e203f3-216b-4a8d-8524-b10527431027.png)

It's about line 114, when i comment that line everything works. Also works if i did something like that 
![image](https://user-images.githubusercontent.com/31986044/182367173-458ee5e8-d9a4-47b8-b5a1-590891b04385.png)

But i think should be fixed

**Comment by gruebel** [comment]
hey @PoborcaMaciej thanks for reaching out! This looks like the new Bicep syntax, which allows arrays to be written as a one-liner. It should be solved with the open PR #3291
