### ISSUE TITLE
Consider replacing some terms

### ISSUE THREAD

**Issue by prabhu** [bridgecrewio/checkov#330]
**Is your feature request related to a problem? Please describe.**
Let's replace blacklist with blocklist and whitelist with allowlist. This is similar to what other projects are doing atm.

**Describe the solution you'd like**
Find and replace should be enough

**Describe alternatives you've considered**

**Additional context**

**Comment by schosterbarak** [comment]
we will accept a contribution there, should be easy

**Comment by schosterbarak** [comment]
Thank you @twmartin and @prabhu
