### ISSUE TITLE
Kubernetes Cross Reference Collection Checks and Horizontal Pod Autoscaling Target Check 

### ISSUE THREAD

**Issue by BrianWolverton** [bridgecrewio/checkov#3314]
**Describe the issue**
This will add the ability to perform cross reference checks on the collection of scanned files for Kubernetes.  This will allow for checks that reference other "kind" such as the target for Horizontal Pod Autoscaling.  

The HorziontalPodAutoscalerTarget check will examine the kind HorizontalPodAutoscaler and examine the scaleTargetRef for kind and name properties.  Once found, it examines the collection for the target kind, name combination to confirm the exists of the target.  

Logic:
Modified check_definitions, run_check, and mutateKuberneteResults in the runner.py for Kubernetes, to send the entire collection to the checks for collection before running individual checks and process the results.
Modified the base_registry.py to process entity_type of 'collection' to send the entire collection of files as a parameter. 
Added Check "CKV_K8S_900" HorizontalPodAutoscaler to check each horizontal pod autoscaler in the collection has a corresponding target. 
**Examples**
File 1:
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscaler-pods
...
File 2:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-pod
spec:
  selector:
    ...
Outcome:
Fail the check due to the name typo in the scaleTargetRef.

**Version (please complete the following information):**
 - Checkov Version 2.1.99

**Comment by gruebel** [comment]
hey @BrianWolverton thanks for reaching out and also creating a PR to tackle your issue 💪 Sadly I have to inform you that we won't add it the way you implemented it, we will add this functionality to graph, which already exists in our Kubernetes code base to also support connections. I can't tell you, when it will be implemented, but we are starting to tackle it in the next weeks.
If you have more examples of connections between different K8s objects, then please add them here, so we can put into consideration what else we should tackle.
Thank you for the effort 🏅
