### ISSUE TITLE
Bitbucket scanning use deprecated APP_PASSWORD

### ISSUE THREAD

**Issue by jonandez** [bridgecrewio/checkov#3328]
**Describe the issue**
Bitbucket have deprecated the app password login option, and checkov integration is unable to work:

`LOG_LEVEL=DEBUG BITBUCKET_REPO_FULL_NAME=$BITBUCKET_REPO_FULL_NAME BITBUCKET_USERNAME=$BITBUCKET_USERNAME BITBUCKET_REPO_FULL_NAME=$BITBUCKET_REPO_FULL_NAME checkov -d . --framework bitbucket_configuration`
.
.
.
`2022-08-09 09:17:23,828 [MainThread  ] [DEBUG]  Filtered list of policies: []`
`2022-08-09 09:17:23,829 [MainThread  ] [DEBUG]  Getting exit code for report bitbucket_configuration
2022-08-09 09:17:23,829 [MainThread  ] [DEBUG]  In get_exit_code; soft_fail: False, soft_fail_on: None, hard_fail_on: None, hard_fail_on_parsing_errors: False
2022-08-09 09:17:23,829 [MainThread  ] [DEBUG]  No failed checks, or soft_fail is True and soft_fail_on and hard_fail_on are empty - returning 0`

**Comment by gruebel** [comment]
hey @jonandez thanks for reaching out. I didn't find anything related to a deprecation of the app password, only of the usage of the personal account password https://bitbucket.org/blog/deprecating-atlassian-account-password-for-bitbucket-api-and-git-activity.
