### ISSUE TITLE
Installing Checkov 2.1.108 via `pip` on macOS 12.5 (21G72) x86_64 results in error

### ISSUE THREAD

**Issue by davidjeddy** [bridgecrewio/checkov#3333]
**Describe the issue**

Executing `pip3 install -U checkov` results in an error during install process referencing an inability to satisfy dependencies related to `pyston-lite==2.3.4.2`.

Note: After install 2.1.106, then upgrading to 2.1.108. Checkov installs as expected.

**Examples**

```sh
Davids-MacBook-Pro:.tmp david$ pip3 install -U checkov
Defaulting to user installation because normal site-packages is not writeable
Collecting checkov
  Using cached checkov-2.1.108-py3-none-any.whl (1.3 MB)
ERROR: Could not find a version that satisfies the requirement pyston-lite==2.3.4.2; python_version == "3.8" and (sys_platform == "linux" or sys_platform == "darwin") and platform_machine == "x86_64" (from checkov) (from versions: none)
ERROR: No matching distribution found for pyston-lite==2.3.4.2; python_version == "3.8" and (sys_platform == "linux" or sys_platform == "darwin") and platform_machine == "x86_64" (from checkov)
WARNING: You are using pip version 20.2.3; however, version 22.2.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Davids-MacBook-Pro:.tmp david
```

**Version (please complete the following information):**

- Checkov Version 2.1.108

**Additional context**

- Python and pip location and version:

```sh
Davids-MacBook-Pro:.tmp david$ which python
Davids-MacBook-Pro:.tmp david$ which python3
/usr/bin/python3
Davids-MacBook-Pro:.tmp david$ which pip
/Users/david/Library/Python/3.8/bin/pip
Davids-MacBook-Pro:.tmp david$ which pip3
/usr/bin/pip3
```

- Checkov 2.1.106 does install as expected.

**Comment by gruebel** [comment]
hey @davidjeddy thanks for reaching out. I tested right now and had no issues with the mentioned dependency. Can you upgrade your pip version like suggested and try it again, because quite often older pip version have problems with resolving dependencies correctly.

**Comment by gruebel** [comment]
@davidjeddy closing the issue for now, feel free to reach out with further info.
