### ISSUE TITLE
brew version of Checkov at 2.1.105

### ISSUE THREAD

**Issue by davidjeddy** [bridgecrewio/checkov#3334]
**Describe the issue**
The version of Checkov available via macOs `brew` is 2.1.105; current recent released version on Github is 2.1.108.

**Examples**

- https://github.com/bridgecrewio/checkov/releases
- https://formulae.brew.sh/formula/checkov#default

```sh
$ brew install checkov
...
$ checkov --version
2.1.105


**Version (please complete the following information):**
2.1.105

**Additional context**
n/a

**Comment by gruebel** [comment]
hey @davidjeddy thanks for reaching out. As far as I remember we only release every 15 versions to brew, so the next versions are `2.1.120`, `2.1.235`, etc.

**Comment by davidjeddy** [comment]
Understood. Submitted a PR updating the readme.md to inform consumers who use brew as the install method.

https://github.com/bridgecrewio/checkov/compare/master...davidjeddy:checkov:patch-1
