### ISSUE TITLE
Allow specifying the output file name

### ISSUE THREAD

**Issue by tspearconquest** [bridgecrewio/checkov#3341]
**Describe the issue**
Hello, I was looking for a way to change the output filename when using the `-o` flag.

I can specify the path to save the file, but as per [2500](https://github.com/bridgecrewio/checkov/pull/2500/files#diff-38786ae57e8435a1c2c390d07eb59c18995c91fada560575800a4f4e4ad6c6feR214-R218) it appears that the path is only configurable and not the filename itself.

**Additional context**

The below output demonstrates the issue:
```
$ checkov -d . -o json --output-file-path ./checkov-keycloak-report.json
[-snip-]
2022-08-10 16:51:48,144 [MainThread  ] [ERROR]
An error occurred while writing json results to file: ./checkov-keycloak-report.json/results_json.json
Traceback (most recent call last):
  File "/usr/local/Cellar/checkov/2.1.60/libexec/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 102, in save_output_to_file
    with open(file_name, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: './checkov-keycloak-report.json/results_json.json'
```

However, If I change `--output-file-path .` then it creates the file results_json.json. I want to change the filename locally from `results_json.json` to `checkov-keycloak-report.json`

**Comment by gruebel** [comment]
hey @tspearconquest thanks for reaching out. you can easily achieve this by redirecting the CLI output
```shell
checkov -d . -o json > checkov-keycloak-report.json
```

**Comment by tspearconquest** [comment]
Hello,

Thank you for that. In #661 I proposed to make a wrapper script for the pre-commit hook. I can include this redirect in the wrapper to satisfy the requirement for the hook but it would be much better if checkov instead took the `--output-file-path` as a filename.

The lines highlighted on [this link](https://github.com/bridgecrewio/checkov/pull/2500/files#diff-38786ae57e8435a1c2c390d07eb59c18995c91fada560575800a4f4e4ad6c6feR213-R219) could be shortened to:

```
        if config.output_file_path:
            for output in config.output:
                self.save_output_to_file(file_name=f'{config.output_file_path}', data=data_outputs[output],
                                     data_format=output)
```

Where `config.output_file_path` can contain either a full or relative path, or just simply a filename, and that would satisfy everything this issue requests. Please advise if a PR would be accepted with this proposed change? I'm happy to submit.

**Comment by gruebel** [comment]
this would basically be a breaking change for a flag, which I don't see the need for. Creating a new flag for it is possible, but I'm not sure why this is actually a requirement for the hook?

**Comment by tspearconquest** [comment]
It's a requirement for all of checkov. I need output in json format from my pre-commit hooks to submit for government compliance requirements in my organization.

**Comment by tspearconquest** [comment]
It's a requirement for all of checkov. I need output in json format from my pre-commit hooks to submit for government compliance requirements in my organization.

It's preferable in my case to have the hook drop the output file in the root of the repo where I can add it to my gitignore without any path on it, so it doesn't get committed.

**Comment by tspearconquest** [comment]
I don't like the filename being chosen for me. I would rather name the file as checkov-keycloak-report.json to match every other file like this created from my pre-commit hooks where it is formatted as "toolname-projectname-report.json"

**Comment by tspearconquest** [comment]
As you suggested, I am proceeding with the redirect, but I would still request this be added as a new flag.

**Comment by Mikaciu** [comment]
> 

Hello, 

I'm afraid the redirection does not export the report for the SARIF format

```console
$ checkov --directory . --hard-fail-on MEDIUM --skip-check CKV_DOCKER_2 --output sarif > checkov.sarif
$ tail -n5 checkov.sarif
        File: /docker/Dockerfile:38-38
        Guide: https://docs.bridgecrew.io/docs/ensure-that-a-user-for-the-container-has-been-created


Wrote output in SARIF format to the file 'results.sarif'
```

**Comment by gruebel** [comment]
hey @tspearconquest , why wouldn't something like this work?
```yaml
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '' # change to tag or sha
    hooks:
      - id: checkov
        args: ["-o=json", "--output-file-path=./checkov-report.json,"]
```

**Comment by tspearconquest** [comment]
My apologies, I haven't tested it yet, and was reviewing the code on my phone.

I'll give this a try when I get some time and report back if I see any problems. Otherwise this can stay closed. Thanks!
