### ISSUE TITLE
Please add support for third-party module registries

### ISSUE THREAD

**Issue by tspearconquest** [bridgecrewio/checkov#3355]
**Describe the issue**
If an existing integration is malfunctioning, please describe the current state and 
what you expect to be happening.
For new integrations, please share an example use case this integration will help 
checkov support.

Hello, as mentioned in #2098 this issue is opened to request support for the Terraform Module Registry Protocol to Checkov.

**Comment by prakyathr** [comment]
@kartikp10 I am having this issue as we have a private repo for Terraform modules. Any updates on this issue?
