### ISSUE TITLE
CKV_AWS_119 using terraform_plan framework fails to detect use of a KMS key ARN passed as a variable

### ISSUE THREAD

**Issue by citrix-eg** [bridgecrewio/checkov#3370]
**Describe the issue**
CKV_AWS_119: Ensure DynamoDB Tables are encrypting using a KMS CMK. This only occurs when checking the plan not the raw tf

I am creating an AWS KMS key in the root of a project and then using that key inside a module to provision a DynamoDB table.

Checkov is falsely flagging the DynamoDB resource as not passing check 119 regarding SSE even though it is being set.

When I used the passed var to conduct a data source lookup, the issue does not occur.

**Examples**
Use of the key outside the module:
![image](https://user-images.githubusercontent.com/58476689/184911417-1f93a857-e942-466e-a085-70a235885105.png)

Use of the key inside the module inside the DDB resource (failure state):
![image](https://user-images.githubusercontent.com/58476689/184911837-ce3532a2-b0ae-484b-a5d5-c18020a374f3.png)

Performing a data source lookup using the ARN
![image](https://user-images.githubusercontent.com/58476689/184912131-2c432563-92d2-4449-a768-c839a5cac647.png)

Using the data source output in the resource creation (success state):
![image](https://user-images.githubusercontent.com/58476689/184912260-ca5204f3-37f8-4b70-b873-55ebecff87b6.png)

**Version (please complete the following information):**
checkov 2.1.130
terraform 1.2.3
aws provider 4.23.0

**Additional context**
Its worth noting that this same pattern is being used for S3 bucket SSE but it is not failing the SSE-specific checks for an S3 bucket. So whatever is broken is specific to DDB (and maybe other resources).

![image](https://user-images.githubusercontent.com/58476689/184917549-ec5ad289-de21-4b2f-97cd-2142e0baa10c.png)

**Comment by kenneth-citrix** [comment]
Any help getting to the bottom of this important issue is much appreciated!

**Comment by gruebel** [comment]
hey @citrix-eg thanks for reaching out. Is the KMS key created during the same plan creation or was it created in previous one? Since Terraform marks them as `known after apply`, which we don't support and therefore it is marked as not existent.
https://github.com/bridgecrewio/checkov/issues/3138#issuecomment-1173105186

**Comment by citrix-eg** [comment]
Yes, you assume correctly that the key is created in the same plan. I guess its a bit of an edge case but it still behaves differently than the S3 SSE. The S3 SSE did not suffer from this problem.
