### ISSUE TITLE
Add CVK_AWS_## number in CLI output

### ISSUE THREAD

**Issue by m-wynn** [bridgecrewio/checkov#34]
**Is your feature request related to a problem? Please describe.**
I would like to be able to more easily add suppressions based on CLI output

**Describe the solution you'd like**
Add the check number in the output, Something like:
```
Check: CKV_AWS_23: "Ensure every security groups rule has a description"
        FAILED for resource: aws_security_group_rule.my_rule
        File: /ec2_security_rules.tf:211-218

                211 | resource "aws_security_group_rule" "my_rule" {
                212 |   type              = "ingress"
                ...
                218 | }
```

**Describe alternatives you've considered**
Look at [the docs](https://github.com/bridgecrewio/checkov/blob/master/docs/3.Scans/resource-scans.md) and compare the text to the provided table

**Comment by schosterbarak** [comment]
thanks @m-wynn  ! 
Handled at https://github.com/bridgecrewio/checkov/pull/37
