### ISSUE TITLE
Outdated check for `google_container_cluster` binary authorization

### ISSUE THREAD

**Issue by calexandre** [bridgecrewio/checkov#3409]
**Describe the issue**
`Check: CKV_GCP_66: "Ensure use of Binary Authorization"` is not checking [against the updated property](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_binary_authorization) causing the check to fail.

The current property states that the old method [`enable_binary_authorization`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enable_binary_authorization) is deprecated in favor the new [`binary_authorization`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_binary_authorization) block

**Examples**

Before:
```hcl
enable_binary_authorization = true
```

Now:
```hcl
  binary_authorization {
    evaluation_mode = "PROJECT_SINGLETON_POLICY_ENFORCE"
  }
```

**Version (please complete the following information):**
 - Checkov Version 2.1.149

**Comment by gruebel** [comment]
hey @calexandre thanks for reaching out. Great catch with the deprecation 🚀 are you maybe interested in contributing the needed change?

**Comment by JamesWoolfenden** [comment]
@gruebel the changes is that that binary auth is now always on so the check isnt needed at all

**Comment by gruebel** [comment]
@JamesWoolfenden but as far as I understand, you can set the mode to `DISABLED` and then it is actually disabled. So it is more like a negative check, as long as you don't set it to `DISABLED` you are fine, right?

**Comment by losisin** [comment]
I think what @calexandre is trying to say is how we do the check needs to change. What used to be `bool` now is moved in module block. Missing block or setting `evaluation_mode` as `DISABLED` should still fail though. If @gruebel and @JamesWoolfenden agree I can have a go with this one.
