### ISSUE TITLE
Issues with OCI policy statements

### ISSUE THREAD

**Issue by behnazh-w** [bridgecrewio/checkov#3412]
**Describe the issue**
Checkov currently evaluates the `statements` attributes of a Terraform resource, which contain IAM policies. However, the syntax of the policies differ for different providers, which results in unexpected evaluations. Oracle Cloud Infrastructure uses a [special syntax](https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/policysyntax.htm) for the policy statements, but Checkov seems to try to evaluate it as a JSON object. Here is an example:

**Example**
When Checkov analyzes the following Terraform code that contains a policy statement:
```terraform
resource "oci_identity_policy" "example" {
  compartment_id = var.compartment_id
  description = var.policy_description
  name = var.policy_name
  statements = ["allow group group-admin-001 to use groups in tenancy where target.group.name != 'Administrators'"]
}
```
It evaluates the `statement` to `True`. So 
```python
def scan_resource_conf(self, conf: dict) -> CheckResult:
    print(conf["statements"][0]) # ['True']
```
Would print
```bash
['True']
```
Instead of
```bash
["allow group group-admin-001 to use groups in tenancy where target.group.name != 'Administrators'"]
```
[Here is a potential solution](https://github.com/bridgecrewio/checkov/pull/3411) which prevents evaluating the `statements` attributes when the provider is set to `OCI` through an environment variable. But as a result, the following policy statements would appear as `str` instead of `list` after resolving the variables:
```terraform
resource "oci_identity_policy" "example_policy" {
  name           = "example_policy"
  description    = "Example policy"
  compartment_id = var.tenancy_id
  statements     = local.policy_statements
  provider       = oci.home
}

locals {
  policy_statements = [
    "allow group group-admin-001 to use groups in tenancy where target.group.name != 'Administrators'",
    "allow service example to read keys in tenancy",
  ]
}
```
So `conf["statements"][0]` in the example above would be a `str` instead of a `list`.
```bash
['["allow group group-admin-001 to use groups in tenancy where target.group.name != \'Administrators\'", \'allow service example to read keys in tenancy\']']
```

What would be the solution? I'm happy to work on a PR with your guidance.

**Comment by behnazh-w** [comment]
@gruebel I was wondering if you had a chance to look at this issue?

**Comment by gruebel** [comment]
hey @behnazh-w thanks for reaching out. OCI definitely behaves differently compared to other cloud providers 😄 I think your change in the draft PR looks pretty straight forward and quite easy. If you can add some tests to prove the changes behaviour, then there shouldn't be a problem with merging it 🙂 I think the only drawback would be that we wouldn't retry to evaluate it, if someone used a interpolated string, but still better than the current behaviour 😄 
Do you need anything else to work further on the PR?

**Comment by behnazh-w** [comment]
Thanks @gruebel . The PR is ready for review.

Since I need to run the tests after setting the env variable `PROVIDER` through shell, I have added an additional `pytest` run in the `pr-test.yml` workflow. Please let me know if you can think of a better way to set the env variable and make it available at the module load time.

**Comment by behnazh-w** [comment]
@gruebel Just a friendly reminder that your change request for [the PR](https://github.com/bridgecrewio/checkov/pull/3411) is addressed. Is there anything else to do on my side? Thanks again :slightly_smiling_face:
