### ISSUE TITLE
For sarif output, add helpUri property to rules

### ISSUE THREAD

**Issue by chuckwondo** [bridgecrewio/checkov#3432]
**Describe the issue**

Currently, for sarif output, the `help` property of rules includes the URI of the full details of the rule. However, the URI should be placed in the `helpUri` property instead. See https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317848

By placing the URI in the `helpUri` property, this allows tools to use the URI to construct links, which is particularly helpful for viewing tools. For example, the Sarif Viewer (by Microsoft DevLabs) extension for VS Code appears not to make use of the `help` property, but when the `helpUri` property is supplied, it creates a hyperlink on the value of the "Rule Id" that it displays in the info panel for a rule, which makes it _extremely_ convenient to click through to see the details of the rule.

**Comment by gruebel** [comment]
hey @chuckwondo thanks for reaching out. Yeah this sounds like a great idea, I will create a fix for it 🙂
