### ISSUE TITLE
Could not locate docs for GCP issues CKV_GCP_74, CKV_GCP_76, CKV_GCP_78, CKV_GCP_81

### ISSUE THREAD

**Issue by oleksiypavlenko** [bridgecrewio/checkov#3439]
Hello, I could not find the documentation with details for the following issues:

- CKV_GCP_74 - Ensure that private_ip_google_access is enabled for Subnet
- CKV_GCP_76 - Ensure that Private google access is enabled for IPV6
- CKV_GCP_78 - Ensure Cloud storage has versioning enabled
- CKV_GCP_81 - Ensure Big Query Tables are encrypted with Customer Supplied Encryption Keys (CSEK)

Though they messages are mostly self-explanatory, other issues such as [CKV_GCP_46](https://docs.bridgecrew.io/docs/bc_gcp_iam_7) (Ensure default Service Account is not used at project level) have dedicated page describing them.

**Comment by gruebel** [comment]
hey @oleksiypavlenko thanks for reaching out. Yeah, we are slowly going through the missing docs and adding them step by step.

**Comment by gruebel** [comment]
As far as I can tell, they are now all added 🙂
