### ISSUE TITLE
CKV2_AWS_19 Flagging an EIP w/ an attached instance

### ISSUE THREAD

**Issue by tarfeef101** [bridgecrewio/checkov#3445]
**Describe the issue**
`CKV2_AWS_19` is failing the below resource, despite it clearly attaching to an EC2 instance

**Examples**
```
resource "aws_eip" "foo" {
  instance = aws_instance.foo.id
  vpc      = true
}
```

**Version (please complete the following information):**
 - Checkov Version [2.1.27]

**Additional context**
Not sure what else to say, it just shouldn't fail that. No modules being used for these resources. Running within `atlantis`, post-plan I am using `terraform show -no-color -json` to feed the plan file into `checkov`

**Comment by gruebel** [comment]
feel free to share your Terraform plan file here, then I can reopen the issue.
