### ISSUE TITLE
CKV_ALI_35,CKV_ALI_36,CKV_ALI_37:some parameters value of 'alicloud_db_instance' must be Lowercase letters

### ISSUE THREAD

**Issue by zhuxl1207** [bridgecrewio/checkov#3448]
**Describe the issue**
**alibaba cloud resource ['alicloud_db_instance']: some parameters value must be Lowercase letters **
CKV_ALI_35,CKV_ALI_36,CKV_ALI_37

**Examples**
Terraform scripts config like blew can not pass checkov check if the value is Lowercase :
resource "alicloud_db_instance" "this" {
   .....
  parameters{
    name = "log_disconnections"
    value = "on"
  }
  parameters{
    name = "log_connections"
    value = "on"
  }
  parameters {
        name = "log_duration"
        value = "on"
    }
}
--->if I set the value = "on"  will can't pass checkov scan
      Then I set the value = "ON" can pass checkov scan but execute ERROR when run  'terrform apply' to create alicloud RDS  resource

 

SoureCode File Path：checkov\checkov\terraform\checks\resource\alicloud\AbsRDSParameter.py
Method: scan_resource_conf()
Line23-24 is :
                       if param['name'][0] == self.parameter and param['value'][0] == 'ON':
                       return CheckResult.PASSED

-->so,can we ignore case sensitivity when check alibaba cloud resource ['alicloud_db_instance']  just like this:
                       if param['name'][0] == self.parameter and param['value'][0].upper() == 'ON':
                       return CheckResult.PASSED

**Version:**
 - Checkov Version：[2.1.171]

**Comment by gruebel** [comment]
hey @zhuxl1207 thanks for reaching out. Are you interested in contributing the change you suggested?
