### ISSUE TITLE
Checkov hangs/slow if local kubeconfig points to a cluster that is unreachable

### ISSUE THREAD

**Issue by duncan485** [bridgecrewio/checkov#3494]
**Checkov performs slow if the local kubeconfig points to a cluster that is unreachable**
When my local `kubeconfig` file has a current_context that is set to a kubernetes cluster that is not reachable at that moment (because it is for example only accessble through VPN which is not connected at that time), checkov takes verry long to run. 

I've did a couple of tests, in the cases that had connection issues to the cluster set in current-context, checkov took at least 34 seconds to run. With a working cluster connection, it takes just 4-5 seconds.

Because I was unaware that checkov had any dependency on the current context set in kubectl, it took quite a while before I found that this was happening. 

I'd be more than willing to work on a PR myself to fix this, but would need some help from someone pointing me to the right direction in terms of where the depedendency of checkov to the kubctl context is created.

**Comment by gruebel** [comment]
hey @duncan485 thanks for reaching out. Definitely an interesting you found here 😄 my guess is it comes from the `kustomize` framework. Can you try to run `checkov` while skipping this framework and see if it is still taking so long?
```shell
checkov -d . --skip-framework kustomize
```

**Comment by duncan485** [comment]
Hey @gruebel thanks! Apologies for the delay, but I think I found the problem, and have a potential solution. 

@gruebel 

I think it is due to the `kubectl version` command that is being run here:

https://github.com/bridgecrewio/checkov/blob/6eb4c17aa28c6447a932f7b1f5d3aa9ee53b8563/checkov/kustomize/runner.py#L228

When I run `kubectl version` locally, with the same conditions, I also see the 30 second delay when my VPN is turned off. 

How would you feel about running this command with `kubectl version --client=true`, this would only show the client version, without a server connection required (also see kubctl refrence docs: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#version). 

If you think this is a good solution I'd like to work on the PR myself.

**Comment by duncan485** [comment]
Yes, will create a PR shortly

Op di 11 okt. 2022 om 16:06 schreef Anton Grübel ***@***.***>:
