### ISSUE TITLE
OpenAPI check failures for non-required security fields

### ISSUE THREAD

**Issue by amaybaum** [bridgecrewio/checkov#3509]
CKV_OPENAPI_4: "Ensure that the global security field has rules defined"
Fails even if no global security field is defined.

CKV_OPENAPI_5: "Ensure that security operations is not empty."
Fails even if no security operations field is defined.

If these are not required fields according to the OpenAPI specification, should their absence still generate check failures?

Example:
`{
  "openapi": "3.0.0",
  "info": {
    "title": "example",
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "operationId": "example",
        "summary": "example",
        "responses": {
          "200": {
            "description": "200 response"
          }
        },
        "parameters": [
          {
            "name": "limit2",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object"
            }
          }
        ]
      }
    }
  }
}`

Expected Result:
CKV_OPENAPI_4 => PASSED for resource: security
CKV_OPENAPI_5 => PASSED for resource: security

Checkov Version:
2.1.195

Checkov seems to be inconsistent with OpenAPI specification for non-required security fields:
https://spec.openapis.org/oas/v3.0.0#operation-object

**Comment by gruebel** [comment]
hey @amaybaum thanks for reaching out. I think there is a misunderstanding on what `checkov` actually tries to tell you. Even the security fields are not required it is recommended to set them, that's why your example fails both checks.

**Comment by amaybaum** [comment]
Hi @gruebel, thanks for the clarification.  Is there currently any way to configure Checkov to produce these failures according to the standard OpenAPI specification, as opposed to the recommended best practices?  If not, are there any plans to add this type of capability?

**Comment by Saarett** [comment]
@amaybaum I would suggest a couple of possibilities:
1. Skip specific checks, e.g. `checkov -d . --skip-check CKV_OPENAPI_4,CKV_OPENAPI_5`
2. Create custom check to support whatever you wish 😄 You can read more [here](https://www.checkov.io/3.Custom%20Policies/Custom%20Policies%20Overview.html)
3. Contribute a couple of checks 🥇 

Hope this helps 😃

**Comment by gruebel** [comment]
as @Saarett mentioned, we currently have no plans to add those kind of checks, we are more focused on security related ones. But you can easily create your own custom checks to validate anything you like for OpenAPI configs.
