### ISSUE TITLE
Ignore certain directories to speed up performance

### ISSUE THREAD

**Issue by prabhu** [bridgecrewio/checkov#351]
**Describe the bug**
Running checkov on projects with directories such as `node_modules` is negatively affecting performance. I can see some code such as [this](https://github.com/bridgecrewio/checkov/blob/f5bdb7d86abd1a154adce16378b6d93e9f8d595d/checkov/kubernetes/runner.py#L41). But ensure this filter is applied globally and made configurable.

List of ignored directories used by scan is [here](https://github.com/ShiftLeftSecurity/sast-scan/blob/master/lib/config.py#L84)

**To Reproduce**
1. Use a node.js based project such as [this](https://github.com/prabhu/flight-manual.atom.io)
2. Run npm install and then checkov with -d argument
3. See the performance degradation even though the project only has 2 yaml files

**Expected behavior**
Ignore directories while doing os.walk. Or consider replacing the logic to use Pathlib.rglob along with ignore.

**Screenshots**

**Desktop (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by acdha** [comment]
This is also a problem with Terraform: by default, all of the Terraform code in your `.terraform/modules` directory will be scanned so e.g. a module which has examples, tests, etc. in its source will take longer to scan and may give failures due to code which is not present in your project or used by it.

**Comment by schosterbarak** [comment]
agreed. @prabhu we will gladly accept a contribution there.

**Comment by schosterbarak** [comment]
Thank you for this. Opened a PR here: https://github.com/bridgecrewio/checkov/pull/356
