### ISSUE TITLE
Checkov custom policy does not recognise arm/bicep resources

### ISSUE THREAD

**Issue by jayshreejannela** [bridgecrewio/checkov#3550]
**Describe the issue**
I am trying to create a custom policy using yaml that checks for ddos protection. I am using arm templates and the custom check does not recognise arm resource but it work fine with terraform

**Examples**
metadata:
 name: "Check whether ddos protection is enabled or not "
 id: "CKV2_AZURE_1"
 category: "GENERAL_SECURITY"
definition:
     - cond_type: "attribute"
       resource_types:
       - "Microsoft.Network/virtualNetworks.[variables('virtualNetworkName')]"
       attribute: "properties.enableDdosProtection"
       operator: "equals"
       value: "true"

**Version (please complete the following information):**
 - latest

**Additional context**

**Comment by gruebel** [comment]
hey @jayshreejannela thanks for reaching out. YAML checks don't work for ARM templates, only for Bicep. And the `resource_types` you chose won't work it needs to be `Microsoft.Network/virtualNetworks`
ex. https://github.com/bridgecrewio/checkov/blob/master/checkov/bicep/checks/graph_checks/SQLServerAuditingEnabled.yaml

**Comment by gruebel** [comment]
feel free to reach, if you have still issues
