### ISSUE TITLE
Markdown output extension is .txt not .md

### ISSUE THREAD

**Issue by evannorstrand** [bridgecrewio/checkov#3558]
**Describe the issue**
The markdown output extension is .txt not .md

**Additional context**
[The error can be found on line 333 of runner_registry.py](https://github.com/bridgecrewio/checkov/blob/ed8c376e6d03d962dac470148f1f84bc1b2eb5cc/checkov/common/runners/runner_registry.py#L333)

Swap .txt to .md and that should fix the issue!

**Comment by gruebel** [comment]
hey @evannorstrand thanks for reaching out. Good catch 🚀 are you interested in contributing the needed change?
