### ISSUE TITLE
[docs] Python Custom Policy Docs are inconsistent

### ISSUE THREAD

**Issue by tarfeef101** [bridgecrewio/checkov#3559]
the docs instruct users to set either `check = ClassName()` or `scanner = ClassName()` at the end of a custom check file. it should be clear which is correct

**Comment by gruebel** [comment]
hey @tarfeef101 thanks for reaching out. Actually it doesn't matter what kind of variable name you choose 🙂 we welcome contribution, if you are interested.

**Comment by gruebel** [comment]
Fixed in #3593
