### ISSUE TITLE
Terraform - Add resource checks for already existing AWS data policy checks

### ISSUE THREAD

**Issue by gruebel** [bridgecrewio/checkov#3572]
**Describe the issue**
We currently have following `data.aws_iam_policy_document` checks

- CKV_AWS_1 - Ensure IAM policies that allow full "*-*" administrative privileges are not created -> CKV_AWS_62
- CKV_AWS_49 - Ensure no IAM policies documents allow "*" as a statement\'s actions -> CKV_AWS_63
- CKV_AWS_107 - Ensure IAM policies does not allow credentials exposure
- CKV_AWS_108 - Ensure IAM policies does not allow data exfiltration
- CKV_AWS_109 - Ensure IAM policies does not allow permissions management / resource exposure without constraints
- CKV_AWS_110 - Ensure IAM policies does not allow privilege escalation
- CKV_AWS_111 - Ensure IAM policies does not allow write access without constraints

which should also be implemented for the `resource` equivalents types, ex.
https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py

**Comment by jjchavanne** [comment]
Created [PR#3794](https://github.com/bridgecrewio/checkov/pull/3794) for CKV_AWS_109

**Comment by bo156** [comment]
Support for CKV_AWS_110 was added [here](https://github.com/bridgecrewio/checkov/pull/4376) as CKV_AWS_286

**Comment by bo156** [comment]
This [PR](https://github.com/bridgecrewio/checkov/pull/4386) adds support for 107/108/109/111 in CKV_AWS_287-390
