### ISSUE TITLE
Installation documentation fix for alpine

### ISSUE THREAD

**Issue by friedrich-brunzema** [bridgecrewio/checkov#359]
**Describe the bug**
Cant install checkov on alpine because of outdated setup tools

**To Reproduce**
try to install on alpine

**Expected behavior**
it installs

**Screenshots**
it bails with a weird error 

**Desktop (please complete the following information):**

**Additional context**
Add the following to the README.md or install document
RUN
pip3 install --upgrade pip && pip3 install --upgrade setuptools
before running
pip3 install checkov

**Comment by schosterbarak** [comment]
is the issue with alpine or with checkov?

**Comment by schosterbarak** [comment]
Thank you @friedrich-brunzema readme updated: https://github.com/bridgecrewio/checkov/blob/master/README.md#installation
