### ISSUE TITLE
CKV2_AWS_15 fails for aws_lb but it is build for aws_elb

### ISSUE THREAD

**Issue by xnick123** [bridgecrewio/checkov#3592]
**Describe the issue**
Check ID CKV2_AWS_15 fails, it seems it is applicable for ELB only (aws_elb = classic lb) although it would make sense to aws_lb too. It does fail when used with aws_lb. I can skip it, but ideally it should not fail imho.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.
It does check for existence of elb argument in the aws_autoscaling_attachment resource, but would be nice if it could check for either elb or 
![image](https://user-images.githubusercontent.com/19893697/193263936-fbddabce-2216-45a0-a866-ed472b66e0d7.png)
I didnt deep dive too much, but It would be good if it could check with an OR statement for elb or lb_target_group_arn in 

**Version (please complete the following information):**
 - Checkov Version 2.1.242

**Additional context**

**Comment by gruebel** [comment]
hey @xnick123 thanks for reaching out! Yeah, it sounds like a good idea to extend it to checking for `lb_target_group_arn` too.
