### ISSUE TITLE
Checkov is not handling ternary operators parsing correctly.

### ISSUE THREAD

**Issue by Jhanvi12** [bridgecrewio/checkov#3613]
Checkov version - `2.0.606`
In the below code of Terraform 
------------------------------------------------------------
```tf
locals {
      var = “a" == “b” ? "true” : "false”
}

resource “aws_vpc_endpoint” “acm_pca” {
      policy = var
}
```

What we would expect in this case – is that policy is populated with string “false”, but what actually happens is that policy is populated with “false’] – omitting the closing quote and adding a single quote and a bracket

Now it becomes even more broken if you nest conditional expressions:
--------------------------------------------------------------------
>

```tf
locals {
      var = “a” == “b” ? “true” : "false”
      tmp = local.var == “true” ? “a==b” : “a!=b”
}

resource “aws_vpc_endpoint” “acm_pca” {
      policy = tmp
}

```
In this case we would expect policy to be “a!=b” string, but what it ends up being is: true:: `“true” ? “a::b” : “a!=b”}’]`

Can you please help us to fix this ?

**Comment by gruebel** [comment]
hey @Jhanvi12 thanks for reaching out.
i can validate that we now support the first case correctly, but not the second 😅
