### ISSUE TITLE
Add new check: Multi-region cloudtrail

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#362]
Check to confirm CloudTrail is configured for multi-region.  

CloudFormation - IsMultiRegionTrail: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html

**Comment by schosterbarak** [comment]
done for terraform: https://github.com/bridgecrewio/checkov/pull/368

**Comment by schosterbarak** [comment]
done for cfn https://github.com/bridgecrewio/checkov/pull/784
