### ISSUE TITLE
How often the policies for checkov gets updated?

### ISSUE THREAD

**Issue by 5-sk** [bridgecrewio/checkov#3622]
How often the policies for checkov gets updated.If I am using checkov as a kubernetes service to scan files.Is there a way to check if all the policies are up to date or any command which looks fir the updates and pulls it in.

**Comment by gruebel** [comment]
hey @5-sk thanks for reaching out. We package the policies directly with `checkov` together, if your `checkov` version is up-to-date, then you also have the latest policies.
