### ISSUE TITLE
Misleading and missing documentation for CKV_AWS_115

### ISSUE THREAD

**Issue by RachelleJanssen** [bridgecrewio/checkov#3637]
**Describe the issue**
We use Checkov for our AWS lambda functions made with SAM. The AWS check for "Ensure AWS Lambda function is configured for function-level concurrent execution limit" has no documentation on why it's an issue and has a weird suggestion. It suggests to put the reserved_concurrent_executions property of a lambda on 0. This can result in lambda functions not running. This can be problematic for lambda functions that should have run as a cron or an event.

Bridgecrew Policy ID: BC_AWS_GENERAL_63
Checkov Check ID: CKV_AWS_115

**Examples**
No code examples to give. It's about the documentation

**Version (please complete the following information):**
 - Checkov Version 2.1.212

**Additional context**

**Comment by tsmithv11** [comment]
We've updated the docs: https://github.com/bridgecrewio/checkov/issues/3637

Let me know if that doesn't resolve your Issue.

**Comment by RachelleJanssen** [comment]
Yes, this is better, thanks!

**Comment by bdoyle0182** [comment]
Can this check be revisited? Reserved concurrency is a nice feature and understand the value of having a peak concurrency allowed for the function to prevent potential runaway concurrency, but it takes away from your account's concurrency quota. For a function that is highly variable in concurrency used i.e. very variable peak to trough something like it uses 1000 concurrency for an hour a day but all other times it uses 50. Setting reserved concurrency in that case would be worse for the account than letting that function just leverage unreserved concurrency as you would have to unnecessarily permanently take away 1000 from your account's limit
