### ISSUE TITLE
CKV_GCP_22 should not trigger with remove_default_node_pool=

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#364]
Checkov `1.0.385` will raise CKV_GCP_22 on a GKE `google_container_cluster` which does not have a `node_type` specifying COS as the base image but this should be suppressed when Terraform is configured to remove the default node pool with `remove_default_node_pool=true`.

**Comment by schosterbarak** [comment]
fix: https://github.com/bridgecrewio/checkov/pull/367
