### ISSUE TITLE
Output filenames should be configurable

### ISSUE THREAD

**Issue by JonZeolla** [bridgecrewio/checkov#3643]
**Describe the issue**
Currently the output filenames are a part of a [hard-coded mapping](https://github.com/bridgecrewio/checkov/blob/4e8e19ba0d35faaa0a2094739fbfb664b3830745/checkov/common/runners/runner_registry.py#L383-L388).  They should be configurable.

In some cases users can redirect stdout/stderr to meet their needs, but this is not the case in my situation.

**Comment by JonZeolla** [comment]
It looks like parser args are [here](https://github.com/bridgecrewio/checkov/blob/11edf57b86913c2a7ca53d1bc4d9047005826887/checkov/main.py#L373) which gets parsed into [config](https://github.com/bridgecrewio/checkov/blob/11edf57b86913c2a7ca53d1bc4d9047005826887/checkov/main.py#L113).  Looks like this was recently touched via 11edf57b86913c2a7ca53d1bc4d9047005826887

**Comment by gruebel** [comment]
yeap, you can leverage my change like described in the help text
```shell
checkov -d . -o cli -o junitxml --output-file-path console,results.xml
```
for a single output you need still to append a comma, otherwise it will use the old mechanism.

**Comment by JonZeolla** [comment]
That works, thanks!  By the way, I did read that help text but didn't expect it would work that way.
