### ISSUE TITLE
Checkov installation on Ubuntu

### ISSUE THREAD

**Issue by zamirTo1** [bridgecrewio/checkov#3649]
**Describe the issue**
If it is related to an existing check, please note the relevant check ID.
Also, explain the logic for this addition / change.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**

Hey, 
Tried to install checkov on Ubuntu 18.04 and got this error
Could not find a version that satisfies the requirement pyston-autoload==2.3.5; python_version < "3.11" and (sys_platform == "linux" or sys_platform == "darwin") and platform_machine == "x86_64" (from checkov) (from versions: )
No matching distribution found for pyston-autoload==2.3.5; python_version < "3.11" and (sys_platform == "linux" or sys_platform == "darwin") and platform_machine == "x86_64" (from checkov)

**Comment by gruebel** [comment]
hey @zamirTo1 thanks for reaching out. Which Python version are you using?

**Comment by zamirTo1** [comment]
3.7.14

**Comment by nikolaik** [comment]
Created an issue in pyston for alpine/musllinux wheels https://github.com/pyston/pyston/issues/279

**Comment by MikeBerryFR** [comment]
I'd like to add a similar issue to this.  
We still have several CentOS 7 hosts running Python 3.7.3 and all Checkov installs from v2.1+ are installing pyston_lite-2.3.5

This completely breaks Python as psyton v2.3.5 support for Python 3.7x appears to be broken. 

Symptom:
* Confirm working install: `checkov -v` --> `v2.0.1140`
* Install Checkov v2.1+ `pip3 install --user checkov==2.2.0`
* Confirm broken install: `checkov -v` --> `Segmentation Fault`
* Confirm broken python3: `pip3 list` --> `Segmentation Fault`

Workaround: 
* Forcefully remove Pyston: `rm -rf /HOME/USER/PATH/TO/site-packages/pyston*`
* Confirm working install: `checkov -v` --> `v2.2.0`

**Comment by gruebel** [comment]
hey everyone, we don't plan on supporting old OS versions like Ubuntu 18.04 which reaches EOL in Spring 23, so probably a good idea to start upgrading to 20.04 or even 22.04. Same goes for CentOS/RHEL 6.
Also old patch versions of Python are not tested and are not recommended to use in any environment. 3.7.3 was released in 03.2019 probably a good idea to update it.
You still have the possibility to use our Docker image, if it is not possible to install `checkov` on your system.

**Comment by dheeg** [comment]
@gruebel 
I don't think the issue should be closed with the summary provided.

We use the 11 days old Alpine with Python 3.10 and can't install Checkov easily anymore.

Dockerfile for testing:
```
FROM alpine:3.16.3

RUN apk add --update --no-cache python3 python3-dev py3-pip py3-wheel
RUN pip3 install --no-cache-dir --ignore-installed checkov==2.2.104
```

Error occurs while building for amd64:
```
#0 18.92 ERROR: Could not find a version that satisfies the requirement pyston==2.3.5; python_version < "3.11" and (sys_platform == "linux" or sys_platform == "darwin") and platform_machine == "x86_64" (from checkov) (from versions: none)
#0 18.92 ERROR: No matching distribution found for pyston==2.3.5; python_version < "3.11" and (sys_platform == "linux" or sys_platform == "darwin") and platform_machine == "x86_64"
```

**Comment by nikolaik** [comment]
A possible workaround for running checkov under alpine would be to use python 3.11, since pyston deps requires python 3.10 or less

**Comment by nikolaik** [comment]
@dheeg I used a similar Dockerfile to run checkov on alpine under python 3.11. Notice that I'm installing python 3 from the edge apk repo:

```dockerfile
FROM alpine:3.17

ARG CHECKOV_VERSION=2.2.105

RUN apk add --update --no-cache gcc musl-dev && \
  apk add --update --no-cache python3 python3-dev py3-pip --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main &&
  pip3 install --no-cache-dir install checkov==$CHECKOV_VERSION
```
