### ISSUE TITLE
CKV_AWS_70 can not evaluate bucket policy if policy is defined in data object

### ISSUE THREAD

**Issue by RishiKapadia20** [bridgecrewio/checkov#3669]
**Describe the issue**
CKV_AWS_70 can not evaluate bucket policy if policy is defined in data object, as what is returned to checkov is the HCL where the data object is called but not the actual contents of the data.

Is there a way within the Python Library to be able to get the contents of the data object by doing some lookup

**Examples**

resource "aws_s3_bucket_policy" "test_bucket_policy" {
  bucket = aws_s3_bucket.test_bucket.id
  policy = data.aws_iam_policy_document.test_bucket_policy_document.json
}

**Version (please complete the following information):**
 - Checkov Version -- 2.1.106

**Additional context**

**Comment by gruebel** [comment]
hey @RishiKapadia20 thanks for reaching out. No, we don't offer this functionality for Python based checks. It should be possible with a YAML based check.

**Comment by RishiKapadia20** [comment]
@gruebel any example you can share on how to achieve this. Also having issues when trying to write my own custom checks around having logging enabled or lifecycle rules on S3 bucket, since both have now become additional resource in terraform (aws_s3_bucket_lifecycle_configuration and aws_s3_bucket_logging), not sure how to say when evaluating S3 bucket check if these resources also exist. I don't think that's something that can be done right ?

**Comment by gruebel** [comment]
here is an example with a data block https://github.com/bridgecrewio/checkov/blob/master/docs/3.Custom%20Policies/Examples.md#simple-connection-state-block-and-filter-and-attribute-blocks---data-block-example
and for the new provider version, which split the S3 resources, you can check out https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/graph_checks/aws/S3BucketLogging.yaml

**Comment by RishiKapadia20** [comment]
Thanks for the links very helpful, is it possible to do the S3 split resource checks in python or is this something also can only be done in the yaml template?

**Comment by gruebel** [comment]
if you need a connection between different resources, then you need to use YAML based checks. Currently there is no plan on adding this capability to Python checks. So, yeah you need 🙂

**Comment by RishiKapadia20** [comment]
@gruebel is there a way in python to resolve a variable to get its value within python. Example if s3 bucket tags are defined in a variable.
