### ISSUE TITLE
skip-path still tries to download modules

### ISSUE THREAD

**Issue by mw-root** [bridgecrewio/checkov#3688]
**Describe the issue**
We have a standard examples folder in our terraform modules that contain example usage. We do not want to scan these files.

with setting skip-path examples it appears that checkov is still trying to download the module references in the examples files.

**Examples**
Folder structure is this:
```
.
./main.tf
./examples
./examples/docs
./examples/docs/main.tf
```

main.tf is empty

examples/docs/main.tf has the following:
```hcl
module "not_real" {
  source = "git@github.com:doesnotexist/somerepo.git//modules/somemodule?ref=somemodule@X.X.X"
}
```

Checkov is still trying to download this git ref and throws warnings.

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/12434761/196473088-75b51702-3bee-4a2b-8504-381854f66765.png">

**Version (please complete the following information):**
 - Checkov Version: 2.1.270

**Additional context**
This is slow and problematic, I'm sure checkov would ignore checking that folder from scans, but IMO it would be best to ignore the file and not attempt to download that module.

**Comment by mw-root** [comment]
When downloading external modules is enabled:

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/12434761/196473772-4ef60932-e620-446d-9a47-427011b017af.png">

**Comment by Joerg-L** [comment]
We are facing the same issue documented here https://github.com/bridgecrewio/checkov/issues/3756
