### ISSUE TITLE
Inconsistent Python Version Compatibility

### ISSUE THREAD

**Issue by jrinder42** [bridgecrewio/checkov#3695]
**Describe the issue**
There seems to be inconsistencies with what Python versions are compatible with this program. It would be helpful to clear this up.

**Examples**
The official tag states it is compatible with Python 3.7 and several builds use Python 3.7, yet multiple places in the README state you can use Python 3.7+ and the integration tests in the *build* workflow use Python versions 3.7-3.10. Furthermore, there is even a package in the pip lockfile `asynctest` that needs Python version < 3.8, indicating that versions >= 3.8 cannot be used. 

**Version (please complete the following information):**
 This is not related to the version, so the most recent version is sufficient.

**Comment by gruebel** [comment]
hey @jrinder42 thanks for reaching out. As stated in the main readme, we support `Python >= 3.7`. the lib `asynctest` is used by `aiohttp` and it will only be installed on Python 3.7. for higher versions it is not needed and therefore it won't be installed. We recently added support for Python 3.11 ahead of its release end of the month.

**Comment by jrinder42** [comment]
@gruebel Thanks for the response. As such, I think it would be helpful to both update the Python version badge in the README as well as update some of the workflows that only test Python 3.7 to work with all versions of Python 3.7-3.10/3.11 (as an example, one workflow to update would be *build.yml*).

**Comment by gruebel** [comment]
badge was updated and reflects all supporting Python versions. we do our main test in the PRs against all versions and different OS. In the final build, we do a sanity check, if it is still working against all Python versions, but not every job needs the whole treatment.
