### ISSUE TITLE
CKV_AWS_4 is an invalid check

### ISSUE THREAD

**Issue by jare19** [bridgecrewio/checkov#371]
**Describe the bug**
CKV_AWS_4 for terraform resource `aws_ebs_snapshot` is invalid. There is not an argument for encryption. Please remove this check.

**To Reproduce**
1. create tf file ckv_aws_4_test.tf:
```
resource "aws_ebs_volume" "example" {
  availability_zone = "us-west-2a"
  encrypted = true
  size              = 40

  tags = {
    Name = "HelloWorld"
  }
}

resource "aws_ebs_snapshot" "example_snapshot" {
  volume_id = "${aws_ebs_volume.example.id}"

  tags = {
    Name = "HelloWorld_snap"
  }
}
```

2. Run cli command  'checkov -f ckv_aws_4_test.tf'
3. Failed when should have passed

**Expected behavior**
Passing check

**Screenshots**
![image](https://user-images.githubusercontent.com/15948264/85431230-dd199180-b546-11ea-824f-b763481a3bfe.png)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Checkov Version [1.0.391]

**Additional context**
- [link to resource doc](https://www.terraform.io/docs/providers/aws/r/ebs_snapshot.html)
As you can see, there is not an argument for encryption listed.  Only a computed artifact named encryption.
![image](https://user-images.githubusercontent.com/15948264/85432245-4c43b580-b548-11ea-8b5f-9b663364bb52.png)

- [TF SourceCode shows encryption as being computed](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ebs_snapshot.go)
![image](https://user-images.githubusercontent.com/15948264/85432117-1d2d4400-b548-11ea-9378-2dcb88c98cb2.png)

- The docs from AWS explain that snapshots that are taken from encrypted volumes are automatically encrypted. [link](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-creating-snapshot.html)

**Comment by schosterbarak** [comment]
you are right @jare19 . thank you for reporting this.  removing. cc: @nimrodkor
