### ISSUE TITLE
CKV_AWS_2 should be restricted to HTTP protocol

### ISSUE THREAD

**Issue by elaygl** [bridgecrewio/checkov#375]
**Describe the bug**
Check CKV_AWS_2 fails for all protocols besides HTTPS.

**To Reproduce**
1. Create aws_lb_listener resource with any protocol besides HTTPS
2. Run checkov check

**Expected behavior**
Only if the protocol is HTTP, checkov will fail the check.

**Comment by schosterbarak** [comment]
That's the goal of the check :) 
Try suppressing it 
    #checkov:skip= CKV_AWS_2:The ALB is using custom protocol for XXX
