### ISSUE TITLE
[Helm] Providing --skip-path for a path that doesn't exist causes the scan not to run

### ISSUE THREAD

**Issue by cameronwaterman** [bridgecrewio/checkov#3758]
**Describe the issue**

If I provide a `--skip-path <path>` option for a path that does not exist, the scan fails to run entirely. I would expect this to no-op and continue the scan, ignoring the invalid directory.

**Examples**

`checkov -d ./helm --framework helm --skip-path tests` causes the scan to not run at all if the `tests` directory does not exist. I am running checkov as part of an Azure Pipeline and want to skip scanning directories that only exist in some of my Helm charts.

**Version (please complete the following information):**
 - 2.1.280

**Comment by gruebel** [comment]
hi @cameronwaterman thanks for reaching out. I tried it with absolute and relative paths and I can't reproduce it. It always finishes the scan. My guess is you have something else in the repos which results in the error.

**Comment by cameronwaterman** [comment]
@gruebel - Thanks for following up. It does seem like you're right, I'm not able to reproduce this issue with a simple chart generated by `helm create`. I'm going to close this issue and will follow-up if I can pin down the exact issue.
