### ISSUE TITLE
CKV_AWS_20 and CKV_AWS_57 have incorrect descriptions

### ISSUE THREAD

**Issue by RishiKapadia20** [bridgecrewio/checkov#3773]
Both rules have a description saying "S3 Bucket has an ACL defined **which allows** public READ/WRITE access." however this is saying that public access should be allowed, which shouldn't be the case for most use cases. However the underlying code for this check is correct in terms that its looking to make sure that public read and write are not enabled, therefore the decription of the checks are incorrect. Could these please be fixed to say "S3 Bucket has an ACL defined which **does not allows** public READ/WRITE access."

Links to places where i could find reference to this mistake however you need to scan to check for more places these are just examples:
https://www.checkov.io/5.Policy%20Index/terraform.html
https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/graph_checks/aws/S3PublicACLRead.yaml
https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/graph_checks/aws/S3PublicACLWrite.yaml

**Comment by RishiKapadia20** [comment]
@gruebel is this something you could have a look at ?

**Comment by JamesWoolfenden** [comment]
This has been solved
