### ISSUE TITLE
Add a support flag

### ISSUE THREAD

**Issue by gruebel** [bridgecrewio/checkov#3783]
For better supporting customer and in a second step OSS users we would like to add a new support flag, which automatically sends the logs to our backend.

- add a support flag `--support`
- a copy of the logs should be uploaded next to the run metadata info, **only when the flag is used**
- extend run metadata with following info
  - OS system info, ex. `Darwin Kernel Version 21.6.0`
  - CPU architecture info, ex. `x86_64`
  - Python implementation, ex `CPython`
  - (Optional) System environment variables, just the names, not their values

**Comment by tronxd** [comment]
@gruebel We should verify that the uploaded logs would not contain sensitive information, such as secrets

**Comment by gruebel** [comment]
@reemodo just testing

**Comment by gruebel** [comment]
Added in #4397
