### ISSUE TITLE
Add baseline functionality

### ISSUE THREAD

**Issue by KevinHock** [bridgecrewio/checkov#379]
In other static analysis tools, like [detect-secrets](https://github.com/Yelp/detect-secrets#setting-up-a-baseline), you can write the output to a file, then reference that file when running the tool, and it will only alert of the difference between the baseline and the current code.

This makes it easy to implement 'from now on' security, and audit baselines asynchronously. It also easily allows seeing how loud the tool is. e.g. iterate through git history making a baseline from the previous commit, and seeing how much the tool yells at a dev for each PR.

**Comment by KevinHock** [comment]
To clarify, would y'all be open to a PR for this? cc @schosterbarak 

If the `--baseline` option was only usable with `--output json`.

**Comment by schosterbarak** [comment]
baseline option would be awesome. :) 
Most of the users I've talked with use the default output format (colorful cli). 
for that reason, I believe it should be implemented in a way that will enable calculating the diff from baseline regardless of the output format.

**Comment by KevinHock** [comment]
++, I shall try :)

**Comment by KevinHock** [comment]
So it was super easy to add this functionality in my super cool `checkov` wrapper package, I didn't have to add it to `checkov` itself. I think I can close this as other folks like me will do my method of wrapping `checkov`.
