### ISSUE TITLE
--directory with --root-for-plan-enrichment does not work

### ISSUE THREAD

**Issue by coffeecoco** [bridgecrewio/checkov#3791]
**Describe the issue**
I am trying to run -d against a directory and also use root-for-plan-enrichment
I can get it to work if i -f /iac/tf.json root-for-plan-enrichment /iac, but when i do it this way it wont do scans of the other iac that need to be scanned e.g docker, or cloudformation

**Examples**
-d /iac -f /iac/tf.json root-for-plan-enrichment /iac # this wil result in the terraform scans with out enrichment

**Version (please complete the following information):**
 - Checkov Version latest

**Additional context**
I want to make it work so i can scan terraform with enrichment and scan the other iac files in other folders

**Comment by coffeecoco** [comment]
I did a bit of creative debugging and testing a code change here
https://github.com/bridgecrewio/checkov/blob/master/checkov/common/runners/runner_registry.py#L127
if add below while using -f & -d & --root-for-plan-enrichment it works.
obviously i hacked it up just to proove a point
repo_root_for_plan_enrichment = ['iac/folder/terragoat']

**Comment by coffeecoco** [comment]
I found a more elegant way to solve it
https://github.com/bridgecrewio/checkov/blob/master/checkov/main.py#L297
Add the argument, and it does what i needed, is this okay if i propose this ?
repo_root_for_plan_enrichment=config.repo_root_for_plan_enrichment

**Comment by gruebel** [comment]
we are currently not planning to add such a use case. Terraform plan scanning was always supposed to be a single file scan.
