### ISSUE TITLE
Possible false-positive in ALBListenerHTTPS check (doesn't check for TLS)

### ISSUE THREAD

**Issue by KevinHock** [bridgecrewio/checkov#380]
The Cloud formation rule doesn't alert off of `TLS`, but the Terraform one does. _First day looking at tool, quite fallible_

See https://github.com/bridgecrewio/checkov/blob/c118129fcff54a409e1a684d508e08baebbe2c48/checkov/terraform/checks/resource/aws/ALBListenerHTTPS.py#L22-L29 vs. https://github.com/bridgecrewio/checkov/blob/c118129fcff54a409e1a684d508e08baebbe2c48/checkov/cloudformation/checks/resource/aws/ALBListenerHTTPS.py#L23-L28

**Comment by schosterbarak** [comment]
@KevinHock Good catch! Looks like you are on the spot on the lines of code. do you want to make a PR on that? 

That's completely fine if not, let me know and i'll fix :)

**Comment by KevinHock** [comment]
Sure thing, I'll do it after work hours today 👍

**Comment by schosterbarak** [comment]
Thank you for the contribution @KevinHock !
