### ISSUE TITLE
Azure AKS managed clusters RBAC - CKV_AZURE_5

### ISSUE THREAD

**Issue by sbe-arg** [bridgecrewio/checkov#3805]
**Describe the issue**
RBAC check fails when enableRBAC is set to true
https://github.com/bridgecrewio/checkov/blob/master/checkov/arm/checks/resource/AKSRbacEnabled.py

**Examples**
![image](https://user-images.githubusercontent.com/23391642/200213730-7908b8ff-acb2-4f16-aac0-e83ff7b7c01c.png)

**Version (please complete the following information):**
 - 2.2.22

**Comment by sbe-arg** [comment]
Noticed that was similar on other AKS checks. PR opened.

**Comment by sbe-arg** [comment]
Probably related but noticing similar behavior on other checks like the network policy 
CKV_AZURE {5-6-7-8}

![image](https://user-images.githubusercontent.com/23391642/200215826-3a09a0ab-940b-42a3-8f0c-0b9fb14f3ce0.png)

![image](https://user-images.githubusercontent.com/23391642/200215904-61ab3ddb-c42f-4894-afad-8447ed796c1a.png)

**Comment by sbe-arg** [comment]
https://github.com/bridgecrewio/checkov/pull/3523/files

**Comment by gruebel** [comment]
hey @sbe-arg thanks for reaching out. As far as I can tell you are using Bicep templates, right? is it possible to share the resource definition of the failing ones, then I can easier validate against them.

**Comment by sbe-arg** [comment]
hey @gruebel here is a minimal resource definition
in here I see 
AZURE_5 failing on forenableRBAC true
AZURE_6 failing on apiServerAccessProfile > authorizedIPRanges > cidr
AZURE_7 failing for networkPolicy 'azure'
AZURE_8 failing on kubeDashboard false

I could be doing something wrong on some of the checks but :man_shrugging: no idea.
Can you point me the checks behind this? I would assume it was scanning the arm templates converted from bicep.

```bicep
resource aks 'Microsoft.ContainerService/managedClusters@2022-08-03-preview' = {
  name: 'string'
  location: location()
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    enableRBAC: true
    agentPoolProfiles: [
      {
        name: 'agentpool'
        osDiskSizeGB: osDiskSizeGB
        osSKU: 'Ubuntu'
        osType: 'Linux'
      }
    ]
    addonProfiles: {
      omsagent: {
        config: {
          logAnalyticsWorkspaceResourceID: logAnalyticsWorkspace.id
        }
        enabled: true
      }
      kubeDashboard: {
        enabled: false
      }
    }
    apiServerAccessProfile: {
      authorizedIPRanges: [
        '10.0.0.0/8'
      ]
    }
    networkProfile: {
      networkPlugin: 'azure'
      networkPolicy: 'azure'
    }
    linuxProfile: {
      adminUsername: linuxAdminUsername
      ssh: {
        publicKeys: [
          {
            keyData: sshRSAPublicKey
          }
        ]
      }
    }
  }
}
```

**Comment by sbe-arg** [comment]
Sweet looking forward
