### ISSUE TITLE
Custom Policy creation for ARM template is missing

### ISSUE THREAD

**Issue by gyuvaraj10** [bridgecrewio/checkov#3824]
Custom Policy creation for ARM template is missing

**Comment by gruebel** [comment]
hey @gyuvaraj10 thanks for reaching out. Do you YAML policies or Python based? the latter one should work, but the former is currently not supported.

**Comment by gyuvaraj10** [comment]
sorry I meant YAML based policies. will there be any support soon?

**Comment by gruebel** [comment]
it is on our roadmap, but no ETA at the moment. Therefore it won't come anytime soon.
