### ISSUE TITLE
Ensure that Public Network Access is disabled for Azure Key Vault

### ISSUE THREAD

**Issue by tdefise** [bridgecrewio/checkov#3832]
**Describe the issue**
It seems that there are no Checkov checks related to the best practice of not allowing Public Network Access to Azure Key Vault
It should be either:

- A list of pre-approved ip_rules in a network_acls block
- A private endpoint

**Examples**

````hcl
resource "azurerm_key_vault" "example" {
  name                                   = "examplekeyvault"
  location                               = azurerm_resource_group.example.location
  resource_group_name                    = azurerm_resource_group.example.name
  enabled_for_disk_encryption            = true
  tenant_id                              = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days             = 90
  purge_protection_enabled               = enabled
  public_network_access_enabled          = false
  sku_name                               = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Get",
    ]

    secret_permissions = [
      "Get",
    ]

    storage_permissions = [
      "Get",
    ]
  }
}
````

**Version (please complete the following information):**
 - N/A

**Comment by gruebel** [comment]
hey @tdefise thanks for reaching out. Nice find 💪  this sounds like a good addition. Are you interested in contributing this check to `checkov`?

**Comment by tdefise** [comment]
Hi @gruebel,

Yes, I will read how to correctly contribute to Checkov and do it in the coming days.
(I will need a bit of time as it will be the first time)

Hopes it's fine.

**Comment by gruebel** [comment]
yeah, sure. if you need some help, feel free to reach out here.

**Comment by tdefise** [comment]
@gruebel I will start to work on it next week and let you know if I need any help.

**Comment by saipavanbm** [comment]
Hey
I am new to Opensource
@gruebel can I collaborate with you on this task

**Comment by gruebel** [comment]
hey @tdefise are you still interested in contributing this new check? if not, then @saipavanbm your welcome to give it a try.

**Comment by saipavanbm** [comment]
Hey @gruebel I was going through the repository
I didn't get how to add ID
Ex: id = "CKV_AZURE_124"
can you help on this

**Comment by tdefise** [comment]
Hello @gruebel, I didn't had time to do it.
Please @saipavanbm go ahead

**Comment by JamesWoolfenden** [comment]
@saipavanbm let me know if i can help/complete
