### ISSUE TITLE
fails to download modules hosted in private repos in ssh

### ISSUE THREAD

**Issue by lorirava** [bridgecrewio/checkov#3834]
I have a module hosted in gitlab and it is imported in my tf via ssh:

```
module "cluster_custom" {
  source = "git@gitlab.com:{myorg}/{myrepo}.git//cluster_sharednet"
```

Terraform download modules correctly using the ssh key of the current user. 
Checkov return download error instead:

`2022-11-09 15:26:20,271 [MainThread  ] [WARNI]  Failed to download module git@gitlab.com:{myorg}/{myrepo}.git//cluster_sharednet:None
`

I can't include module in terraform via HTTP/S, I need to use SSH. 

Is there a way to force checkov to use the ssh key of the current user as well?

**Comment by nikovega21** [comment]
Same here I'm not able to load modules using ssh even if I have already added the ssh key.
