### ISSUE TITLE
Support for .tfvars

### ISSUE THREAD

**Issue by ymohamme** [bridgecrewio/checkov#386]
We use .tfvars files to assign values to variables. Currently it looks like there is no support for files with a .tfvars extension. This is a great tool and adding this support would greatly benefit The terraform community.

**Comment by schosterbarak** [comment]
Thank you @ymohamme for reporting this one. We are working on it. We do see it as part of a larger task that will enable deep-assignment of variables. We have estimated in a few weeks of work and @rotemavni is working hard on this one.

**Comment by robeden** [comment]
@schosterbarak - I have an implementation (outside checkout) that I can contribute as a starting point if @rotemavni would like something to reference.

**Comment by schosterbarak** [comment]
Thanks, @robeden  that will definitely help. let me connect I'll open a joined channel on this topic on our slack workspace :)

**Comment by robeden** [comment]
I think we could handle "simple" variable parsing similar to what was done with serverless variables in #529. I've handled .tfvars, module and local references with a similar approach. There's some data that trickier (like existing resource lookups), but for basic variables it's pretty straight-forward.

**Comment by jdheyburn** [comment]
This looks useful - any further progress on this one?

**Comment by robeden** [comment]
I’m actively working on it right now. Hopefully we’ll have something to show soon.

**Comment by schosterbarak** [comment]
@ymohamme try the latest version by @robeden and @rotemavni  :)

**Comment by geertn** [comment]
I'm building my Storage Account names like this
```
name                = "${local.saname_prefix}diagnostics${module.tf-var-project.random_id}
```

With https://github.com/bridgecrewio/checkov/pull/429 merged I now get a Check failure on the SA name:

```
Check: CKV_AZURE_43: "Ensure the Storage Account naming rules"
	FAILED for resource: azurerm_storage_account.diagnostics
	File: /az_diag_sa.tf:8-22

		8  | resource "azurerm_storage_account" "diagnostics" {
		9  |   #checkov:skip=CKV_AZURE_35:Public access is allowed
		10 |   name                = "${local.saname_prefix}diagnostics${module.tf-var-project.random_id}"

````

**Comment by robeden** [comment]
@geertn - Would you mind opening a new bug with your report? It will help raise it for visibility. Thanks!
