### ISSUE TITLE
False Positive check with json plan file CKV2_AWS_11

### ISSUE THREAD

**Issue by NevoWeksler** [bridgecrewio/checkov#3871]
**Describe the issue**
Check Id: CKV2_AWS_11
There is a false positive (the check is failing when in reality the VPC flow logs are enabled)
the main.tf file refers to  aws_vpc module.
the code attached is of the json plan file.
changed to txt to upload the file because json is not supported here.

**Examples**
[plan_file.txt](https://github.com/bridgecrewio/checkov/files/10001519/plan_file.txt)

**Version (please complete the following information):**
 - Checkov Version 2.2.30

**Additional context**
also tested on my local machine using the command:
checkov -f ./plan_file.json -c CKV2_AWS_11 --quiet
the outcome:
![image](https://user-images.githubusercontent.com/95635081/201624339-440942d0-d6aa-4fce-9f4a-6c2d94a5b11a.png)

**Comment by NevoWeksler** [comment]
Do you have a workaround?

**Comment by dzirg44** [comment]
Have the same issue , but what I noticed, that I have this error only when I specify log destination.

**Comment by cness-fm** [comment]
Did this issue ever get resolved?
