### ISSUE TITLE
checkov `--soft-fail-on` with severity doesn't work as expected

### ISSUE THREAD

**Issue by lonegunmanb** [bridgecrewio/checkov#3889]
**Describe the issue**
I'd like to use `--soft-fail-on` to bypass error code with LOW severity issues but I failed.

**Examples**

1. git clone https://github.com/bridgecrewio/terragoat.git
2. cd into terragoat directory
3. execute `checkov --soft-fail-on CRITICAL,HIGH,MEDIUM,LOW --directory ./`
4. execute `echo $?`

Expected return code: `0`
Actual return code: `1`

**Version (please complete the following information):**
 - Checkov Version `2.1.282`

**Additional context**

**Comment by gruebel** [comment]
hey @lonegunmanb thanks for reaching out. Are you using an API key when doing the scan? if not, then `--soft-fail-on` with a severity won't work, because severities are only added to the check, when used with an API key.

**Comment by lonegunmanb** [comment]
Thanks @gruebel for your reply, that answered my question so I'm closing this issue now. May I suggest Checkov might need to upgrade the [document](https://www.checkov.io/2.Basics/Hard%20and%20soft%20fail.html) since it didn't mentioned the API Key, nor the help information from checkov cli.
