### ISSUE TITLE
Terraform's `terraform.workspace` value is not evaluated and can result in an error.

### ISSUE THREAD

**Issue by domroutley** [bridgecrewio/checkov#3901]
**Describe the issue**

Terraform supports workspaces ([docs](https://developer.hashicorp.com/terraform/language/state/workspaces)), but when using the value of `terraform.workspace` (which will always evaluate to _something_, "default" being the default value) in naming a storage account I came across this issue.

Checkov does not seem to evaluate the value of `terraform.workspace`.

**Example Value**

Here is my example Terraform code that shows the issue when checkov is run against it:
```hcl
resource "azurerm_resource_group" "main" {
  name     = "rg-testing"
  location = "UKSouth"
}

resource "azurerm_storage_account" "test" {
  # checkov:skip=CKV_AZURE_35:Hidden for demo
  # checkov:skip=CKV2_AZURE_1:Hidden for demo
  # checkov:skip=CKV2_AZURE_18:Hidden for demo
  # checkov:skip=CKV_AZURE_59:Hidden for demo
  # checkov:skip=CKV_AZURE_33:Hidden for demo
  # checkov:skip=CKV_AZURE_44:Hidden for demo
  name                     = "stexamplestore${terraform.workspace}"
  location                 = "UKSouth"
  resource_group_name      = azurerm_resource_group.main.name
  account_replication_type = "LRS"
  account_tier             = "Standard"
}
```

With no workspace set, I expect the name of the storage account to be "stexamplestoredefault" which meets the requirements for CKV_AZURE_43: "Ensure Storage Accounts adhere to the naming rules". Instead this check fails.

I do not believe (although I could be wrong) that this is an issue with the check, but is instead caused by checkov not dealing with the edge case of `terraform.workspace`.

**Comment by Greven145** [comment]
Can we re-open this please? We use `terraform.workspace` to adjust values like OP does, and it seemingly being ignore is causing false positives
