### ISSUE TITLE
Duplicate checks CKV_AZURE_3 & CKV_AZURE_60

### ISSUE THREAD

**Issue by tdefise** [bridgecrewio/checkov#3913]
**Describe the issue**
It seems that both CKV_AZURE_3 & CKV_AZURE_60 are duplicate
For instance, there are two Terraform checks for the same setting (enable_https_traffic_only) on the same resource (azurerm_storage_account)

**Examples**
N/A

**Version (please complete the following information):**
 - Checkov Version 2.2.80

**Additional context**
N/A

**Comment by JamesWoolfenden** [comment]
Ye gads he's right @gruebel
