### ISSUE TITLE
Unable to check security group association if security group is referenced to resource dynamically.

### ISSUE THREAD

**Issue by arkaprava-jana** [bridgecrewio/checkov#3919]
**Describe the issue**
Enforcing TLS encryption for AWS MSK need to be checked on attached Security Group Resource as specific ports support TLS.
Ref: https://docs.aws.amazon.com/msk/latest/developerguide/port-info.html

If Security Group and MSK Cluster is being provisioned together and dynamically referenced in terraform, yaml policy is unable to check connection.

Similar behavior is noticed in other cases where terraform plan shows parameter value as "known after apply".

 
**Examples**
Terraform code reference:
```hcl
resource "aws_msk_cluster" "msk_cluster" {
  count                        = var.enabled > 0 ? 1 : 0
  tags                         = var.tag_map
  cluster_name           = var.cluster_name
  kafka_version          = var.kafka_version
  number_of_broker_nodes = var.number_of_broker_nodes

  broker_node_group_info {
    instance_type   = var.instance_type
    ebs_volume_size = var.ebs_volume_size
    client_subnets  = data.aws_subnet_ids.tier2_app_layer.ids
    security_groups = [aws_security_group.msk_broker_sg.0.id]
  }

  client_authentication {
    sasl {
      scram    = true
    }
  }

  logging_info {
    broker_logs {
      cloudwatch_logs {
        enabled   = true
        log_group = aws_cloudwatch_log_group.msk_broker_log_group.0.name
      }
    }
  }
}

resource "aws_security_group" "msk_broker_sg" {
  count                        = var.enabled > 0 ? 1 : 0
  name                         = "${var.cluster_name}-cluster-sg"
  description                  = "MSK broker sg"
  vpc_id                       = data.aws_vpc.vpc.id
}
```

                                              
**Desktop (please complete the following information):**
 - Checkov Version [e.g. 22]  22

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by arkaprava-jana** [comment]
Plan json:
[msk-clean.zip](https://github.com/bridgecrewio/checkov/files/10073519/msk-clean.zip)

**Comment by gruebel** [comment]
hey @arkaprava-jana thanks for reaching out. We currently don't supported this, same goes for `for_each`. We plan on tackling it, but not this year.

The `"known after apply"` is a known limitation and we don't plan on supporting it any time soon, because as it says, you only after applying the plan what is happening.
