### ISSUE TITLE
Checkov validation skip issues when skip added in underlying module of terraform

### ISSUE THREAD

**Issue by pravindhawas** [bridgecrewio/checkov#3934]
**Issue Description:**
I have a terraform module which is calling other terraform repository as a submodule in azure devops. I have few skips added at resource level in that submodule repository. However, when I am running checkov against terraform_plan.json. It is not skipping that checkov validation and failing

**Examples:**
Main Azure Repo calling other repo as submodule:
```hcl
module "eks" {
  source = "git::ssh://azuredevops.abc.net/Main/Multi-Cloud/_git/module-sub-eks//.?ref=0.0.1"
}
```
Skip added at resource level in submodule repo module-sub-eks:

```hcl
_Removed unnecesarry code from here_

resource "aws_cloudwatch_log_group" "this" {
  #checkov:skip=CKV_AWS_158:Ensure that CloudWatch Log Group is encrypted by KMS
  count = length(var.cluster_enabled_log_types) > 0 && var.create_eks ? 1 : 0

  name              = "abcd"
  retention_in_days = 90
  kms_key_id        = var.cluster_log_kms_key_id

  tags = var.tags
}

_Removed unnecesarry code from here_
```

Expected result: It should have skipped the validation CKV_AWS_158

Actual results: It is failing with validation CKV_AWS_158 and skip is not getting identified

**Version (please complete the following information):**
 - Checkov Version 2.1.114

**Comment by gruebel** [comment]
hey @pravindhawas thanks for reaching out. How does the actual `checkov` scan command looks like?

**Comment by pravindhawas** [comment]
Hi @gruebel , I am using below command.
 checkov -f terraform_plan.json

**Comment by pravindhawas** [comment]
please let me know if any further information is needed from me.

**Comment by gruebel** [comment]
this should be aded via #3552 so you need to upgrade to almost the latest version of `checkov` and then use `--download-external-modules` and `--repo-root-for-plan-enrichment` flag

**Comment by pravindhawas** [comment]
Hi @gruebel , Later I have checked my pipeline for checkov scan command. The whole command is like below:
checkov -f terraform_plan.json -o junitxml   --repo-root-for-plan-enrichment 
and the version I am using is 2.1.114.

I will try with latest version and above mentioned flags and will let you know if that works.
Thanks for quick response and solution!!!

**Comment by gruebel** [comment]
feel free to reach out again, if you still have issues.
