### ISSUE TITLE
I don't see both --check or --skip-check working as expected

### ISSUE THREAD

**Issue by dolivetoa** [bridgecrewio/checkov#3953]
**Describe the issue**
version of checkov on Windows 10 (version: 2.1.67)
I am testing the results of the tools and on the exactly the same terraform code I did the following tests:
I want to silence all LOW severity violations but I don't get the behavior expected

**Examples**
1) checkov --directory terraform --check MEDIUM
 I do get an empty result - I would expect to get medium severity and above violated policies
2) checkov --directory terraform --check LOW
 I do get an empty result  - I would expect to get LOW severity and above violated policies
3) checkov --directory terraform --skip-check MEDIUM
I get the result below
4) checkov --directory terraform --skip-check LOW
I get the result below (same as above) - expected only HIGH and higer severity however as you can see from the policy inn the list there are LOW severity as well.
5) Running the command from the docker image
docker pull bridgecrew/checkov
docker run --tty --volume $(pwd):/tf --workdir /tf bridgecrew/checkov --directory terraform --skip-check LOW
I get 
checkov: error: unrecognized arguments: --skip-check LOW

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]

**RESULT**
> checkov --directory terraform --skip-check MEDIUM
[ secrets framework ]: 100%|████████████████████|[4/4], Current File Scanned=terraform\variables.tf
[ terraform framework ]: 100%|████████████████████|[4/4], Current File Scanned=variables.tf

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.1.67

terraform scan results:

Passed checks: 5, Failed checks: 13, Skipped checks: 0

Check: CKV_AZURE_57: "Ensure that CORS disallows every resource to access app services"
        PASSED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-cors-disallows-every-resource-to-access-app-services
Check: CKV_AZURE_83: "Ensure that 'Java version' is the latest, if used to run the web app"
        PASSED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-java-version-is-the-latest-if-used-to-run-the-web-app
Check: CKV_AZURE_81: "Ensure that 'PHP version' is the latest, if used to run the web app"
        PASSED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-php-version-is-the-latest-if-used-to-run-the-web-app
Check: CKV_AZURE_82: "Ensure that 'Python version' is the latest, if used to run the web app"
        PASSED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-python-version-is-the-latest-if-used-to-run-the-web-app
Check: CKV_AZURE_72: "Ensure that remote debugging is not enabled for app services"
        PASSED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-remote-debugging-is-not-enabled-for-app-services
Check: CKV_AZURE_13: "Ensure App Service Authentication is set on Azure App Service"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/bc_azr_general_2

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_65: "Ensure that App service enables detailed error messages"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/tbdensure-that-app-service-enables-detailed-error-messages

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_80: "Ensure that 'Net Framework' version is the latest, if used as a part of the web app"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-net-framework-version-is-the-latest-if-used-as-a-part-of-the-web-app

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_66: "Ensure that App service enables failed request tracing"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-app-service-enables-failed-request-tracing

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_78: "Ensure FTP deployments are disabled"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-ftp-deployments-are-disabled

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_63: "Ensure that App service enables HTTP logging"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-app-service-enables-http-logging

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_18: "Ensure that 'HTTP Version' is the latest if used to run the web app"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/bc_azr_networking_8

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_14: "Ensure web app redirects all HTTP traffic to HTTPS in Azure App Service"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/bc_azr_networking_5

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_71: "Ensure that Managed identity provider is enabled for app services"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-managed-identity-provider-is-enabled-for-app-services

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_15: "Ensure web app is using the latest version of TLS encryption"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/bc_azr_networking_6

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/ensure-that-app-services-use-azure-files

                Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_AZURE_17: "Ensure the web app has 'Client Certificates (Incoming client certificates)' set"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/bc_azr_networking_7

Check: CKV_AZURE_16: "Ensure that Register with Azure Active Directory is enabled on App Service"
        FAILED for resource: azurerm_app_service.api_app
        File: /main.tf:32-91
        Guide: https://docs.bridgecrew.io/docs/bc_azr_iam_1

                Code lines for this resource are too many. Please use IDE of your choice to review the file.

**Comment by gruebel** [comment]
hey @dolivetoa thanks for reaching out. Similar to this https://github.com/bridgecrewio/checkov/issues/3889#issuecomment-1316681833 the `--check` and `--skip-check` with severity only works when using an API key.
