### ISSUE TITLE
CKV_DOCKER_2

### ISSUE THREAD

**Issue by janchristian-haddorp** [bridgecrewio/checkov#3955]
**Description**
We build our application based on a Dockerfile, then run it via Kubernetes.

Kubernetes already provides liveness and readiness probes. Adding HEALTHCHECK to the Dockerfile feels unnecessary.

Is there a recommendation how to configure HEALTHCHECK in case of using Kubernetes? Duplicate checks should be avoided.

**Checkov Version**
2.2.106 

**Additional context**
You may add an ignore comment; but still does not feel good.
#checkov:skip=CKV_DOCKER_2

**Comment by janchristian-haddorp** [comment]
@gruebel, thanks for the quick response. Adding a skip comment inside Dockerfile file would require that we adapt each Dockerfile.

How can I disable the CKV_DOCKER_2 check completely as suggested?

**Comment by gruebel** [comment]
when you use CLI, then just add the `--skip-check` flag and it is comma separated
```shell
checkov -d . --skip-check CKV_DOCKER_2,xyz
```
also possible to do via env var `CKV_SKIP_CHECK=CKV_DOCKER_2,xyz`

**Comment by janchristian-haddorp** [comment]
Thanks! We use the GitHub Action bridgecrewio/checkov-action.
https://github.com/bridgecrewio/checkov-action

Adding ```skip_check: CKV_DOCKER_2```produces the expected result.
