### ISSUE TITLE
Where can I find Checkov files for download and do the installation in an environment air-gapped (offline)?

### ISSUE THREAD

**Issue by alexandrezanetti** [bridgecrewio/checkov#3990]
Hi all,

    I'm looking for Checkov files for download and do the installation in an environment air-gapped (offline).

    Where can I find this?

**Comment by gruebel** [comment]
hey @alexandrezanetti thanks for reaching out. You can grab the Python wheel or source files from `pypi` directly, but they don't include dependencies. https://pypi.org/project/checkov/#files
