### ISSUE TITLE
Working with Terraform Enterprise

### ISSUE THREAD

**Issue by jbrule** [bridgecrewio/checkov#4007]
It looks like TFC_HOST_NAME is hardcoded as a constant. Is there reason that this can't be specified via ENV or other method? I am trying to pull modules from TFE registry.

Thank you,
Josh

**Comment by jbrule** [comment]
Any comments? Ideas? Is there enough difference between TFC and TFE to negate the possibility. My understanding is TFC is the leading release with TFE lagging behind a bit. The module registry is basically identical as I understand it.

**Comment by dolivetoa** [comment]
My company needs to do the same pull modules from TFE registry, is there a solution for this?

**Comment by gruebel** [comment]
this was added a while back. Feel free to create a new issue, if you have problems using it.
