### ISSUE TITLE
Gitlab terraform module registry

### ISSUE THREAD

**Issue by balagurrr** [bridgecrewio/checkov#4009]
**Describe the solution you'd like**
Our team uses terraform modules, source are Gitlab Terraform module registry.
Example:
```
module "<module>" {
  source = "gitlab.com/<namespace>/<module-name>/<module-system>"
}
```
please add integration [Gitlab Terraform Module Registry](https://docs.gitlab.com/ee/user/packages/terraform_module_registry/) for scanning and download external private terraform modules, like [this](https://www.checkov.io/7.Scan%20Examples/Terraform.html#scanning-private-terraform-modules).

**Comment by nimrodkor** [comment]
We're up for a contribution here!
We'll need to add a new loader in [this dir](checkov/terraform/module_loading/loaders)
