### ISSUE TITLE
Switch to ignore inline suppressions

### ISSUE THREAD

**Issue by budgester** [bridgecrewio/checkov#4027]
When running a scan I want to know all failures that have occurred using just the checkov config file and CLI options.

if a resource is skipped using an inline suppression, I am unable to generate a full report based on my defined combination of --check and --skip-check in my config file.

So a flag like 

```
--disable-resource-skips = True
```

Would be really useful in a similar way that flake8 does it's --disable-noqa

https://flake8.pycqa.org/en/3.1.1/user/options.html#cmdoption-flake8--disable-noqa

**Comment by gruebel** [comment]
hey @budgester thanks for reaching out. This feature is available inside our platform, therefore we currently don't plan on adding it to `checkov` directly. Feel free to try the platform for free 🙂

**Comment by williamsjo-reninc** [comment]
It's a pretty crappy thing for them to introduce a security hole like this and lock the solution behind a paywall. Definitely turns me off from recommending Prisma to my company.

If you're using GitHub actions, just add another step at the end of the Checkov job:

```
      - name: Prevent Checkov skips
        run: |
          if grep -r 'checkov:skip' .; then
            echo 'Found comments disabling Checkov alerts. Remove them and try again.'
            exit 1
          else
            echo 'No checkov:skip comments found.'
            exit 0
          fi
        if: success() || failure()
```
