### ISSUE TITLE
Details has not been printed

### ISSUE THREAD

**Issue by juliopedrosa** [bridgecrewio/checkov#4088]
**Describe the issue**
I'm trying to add details to a custom policy, but it has not been printed.
Run: On MacOS and on Github Action checkov-action@v12.1943.0
Version: 2.2.168
**Additional context**

  MANDATORY_TAGS = [
      "Application",
	  "Env",
	  "Team",
  ]
  
  
  class MandatoryTags(BaseResourceCheck):

      def __init__(self):
          name = "Ensure all resources has madatory tags"
          id = "CUSTOM_AWS_001"
          supported_resources = ['aws_kms_key']
          categories = [CheckCategories.GENERAL_SECURITY]
          guideline = "Check page blah blah"
          super().__init__(name=name, id=id, categories=categories,
                supported_resources=supported_resources, guideline=guideline)
  
      def scan_resource_conf(self, conf):
          if 'tags_all' in conf.keys():
              resource_tags = list(conf['tags_all'][0].keys())
              if not all(tag in resource_tags for tag in MANDATORY_TAGS):
                  self.details.append("default_tags need to be set on provider level")
                  return CheckResult.FAILED
              return CheckResult.PASSED
   
  
  
  check = MandatoryTags()
  
  ** output **
  `                "check_id": "CUSTOM_AWS_001",
                "bc_check_id": null,
                "check_name": "Ensure all resources has mandatory tags",
                "check_result": {
                    "result": "FAILED",
                    "evaluated_keys": []
                },
                "code_block": [...],
                "file_path": "/plan_fmt.json",
                "file_abs_path": "/private/tmp/platform-checkov-custom-policies/plan_fmt.json",
                "repo_file_path": "/plan_fmt.json",
                "file_line_range": [...],
                "resource": "aws_kms_key.default",
                "evaluations": null,
                "check_class": "CheckMandatoryTags",
                "fixed_definition": null,
                "entity_tags": null,
                "caller_file_path": null,
                "caller_file_line_range": null,
                "resource_address": "aws_kms_key.default",
                "severity": null,
                "bc_category": null,
                "benchmarks": null,
                "description": null,
                "short_description": null,
                "vulnerability_details": null,
                "connected_node": null,
                "guideline": "",
                "details": [],
                "check_len": null
            },`

In the output, it shows the details list as empty.

**Comment by gruebel** [comment]
hey @juliopedrosa thanks for reaching out. Which output format did you choose exactly, `json`? Does it show up in the normal CLI output?

**Comment by juliopedrosa** [comment]
@gruebel Doesn't show on both. Follow bellow sarif output
       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.2.168 
terraform_plan scan results:

Passed checks: 1, Failed checks: 3, Skipped checks: 0

Check: CUSTOM_AWS_001: "Ensure all resources have mandatory tags"
        PASSED for resource: aws_kms_key.default
        File: /plan_fmt.json:4191-4216
Check: CUSTOM_AWS_001: "Ensure all resources have mandatory tags"
        FAILED for resource: aws_kms_key.default
        File: /plan_fmt.json:4191-4216

**Comment by juliopedrosa** [comment]
I've also printed the details in the log and the string is appended to the list but checkov doesn't show:
```
  def scan_resource_conf(self, conf):
      if 'tags_all' in conf.keys():
          resource_tags = list(conf['tags_all'][0].keys())
          if not all(tag in resource_tags for tag in MANDATORY_TAGS):
              self.details.append("default_tags need to be set on provider level")
              print(self.details)
              return CheckResult.FAILED
          return CheckResult.PASSED
```

**output**
['default_tags need to be set on provider level']
terraform_plan scan results:

Passed checks: 0, Failed checks: 1, Skipped checks: 0

Check: CUSTOM_AWS_001: "Ensure all resources have mandatory tags"
        FAILED for resource: aws_kms_key.default
        File: /plan_fmt.json:4191-4216

**Comment by gruebel** [comment]
found the issue, thanks. The details were just added for normal Terraform scans and not for Terraform plan scans.
