### ISSUE TITLE
AWS - Ensure State Machine has execution history logging enabled

### ISSUE THREAD

**Issue by gruebel** [bridgecrewio/checkov#4123]
**Describe the issue**
- add a new check for ensuring execution history logging for State Machine is enabled
```python
name = "Ensure State Machine has execution history logging enabled"
id = "CKV_AWS_285"
supported_data = ("aws_sfn_state_machine",)
categories = (CheckCategories.LOGGING,)
```

**Examples**
```hcl
resource "aws_sfn_state_machine" "sfn_state_machine" {
  name     = "my-state-machine"
  role_arn = aws_iam_role.iam_for_sfn.arn

  definition = <<EOF
{
  "StartAt": "HelloWorld",
  "States": {
    "HelloWorld": {
      "Type": "Task",
      "Resource": "${aws_lambda_function.lambda.arn}",
      "End": true
    }
  }
}
EOF

  logging_configuration {
    log_destination        = "${aws_cloudwatch_log_group.log_group_for_sfn.arn}:*"
    include_execution_data = true
    level                  = "ERROR"
  }
}
```

**Additional context**
logging is by default disabled

**Comment by gruebel** [comment]
Added with #4240

**Comment by jagoodhand** [comment]
@gruebel - i think this needs to be edited, unless i'm reading the Terraform docs wrong. The checks applied by CKV_AWS_285 apply to all types of StepFunction, whereas the Terraform docs state "The logging_configuration parameter is only valid when type is set to EXPRESS":

> [logging_configuration](https://registry.terraform.io/providers/hashicorp/aws/5.6.1/docs/resources/sfn_state_machine#logging_configuration) - (Optional) Defines what execution history events are logged and where they are logged. The logging_configuration parameter is only valid when type is set to EXPRESS. Defaults to OFF. For more information see [Logging Express Workflows](https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html) and [Log Levels](https://docs.aws.amazon.com/step-functions/latest/dg/cloudwatch-log-level.html) in the AWS Step Functions User Guide.

This check should be updated to only apply if the SFN type is 'EXPRESS'.
