### ISSUE TITLE
CKV2_AWS_5: aws_transfer_server is not checked

### ISSUE THREAD

**Issue by Teko012** [bridgecrewio/checkov#4136]
**Describe the issue**
When using `aws_transfer_server` in terraform aws provider, `CKV2_AWS_5` doesn't check for `security_group_ids` in `aws_transfer_server`, giving us a failed check. 

**Examples**
```
resource "aws_security_group" "transfer_server" {
  ingress {
    description = "SFTP"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_transfer_server" "transfer_server" {
  endpoint_type = "VPC"

  endpoint_details {
    address_allocation_ids = [var.eip_id]
    subnet_ids             = [var.subnet_id]
    vpc_id                 = var.vpc_id
    security_group_ids     = [aws_security_group.transfer_server.id]
  }
}
```

**Version (please complete the following information):**
 2.2.191

**Additional context**
I'm working on a PR with a fix.

**Comment by gruebel** [comment]
hey @Teko012 thanks for reaching out. Good catch 🎣 Are you interested in contributing the needed adjustment? You can find the needed code parts here #3310
