### ISSUE TITLE
Crash in enrich_definition_block while processing Terraform

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#414]
Checkov version 1.0.418 crashes in `enrich_definition_block()`. In my code this appears to be processing a Terraform `locals` definition which looks like it's expecting a dictionary but receiving a string:

```
 6  	    def __init__(self):
  7  	        definition_type = "locals"
  8  	        super().__init__(definition_type=definition_type)
  9  	
 10  	    def _collect_local_values(self, local_block):
 11  ->	        for local_name, local_value in local_block.items():
 12  	            local_value = local_value[0]
 13  	            if type(local_value) in (int, float, bool, str):
 14  	                dpath.new(self.context, ['assignments', local_name], local_value)
 15  	
 16  	    def get_block_type(self):
(Pdb) p local_block
'environment'
```

The source for that block looks like this:

```hcl
locals {
  environment   = lower(terraform.workspace)
}
```

It's also not clear why `enrich_definition_block` uses `enumerate()` since the index variable is never accessed:

```
 22  	    def enrich_definition_block(self, definition_blocks):
 23  	        self.context = super().enrich_definition_block(definition_blocks)
 24  	        for i, locals_block in enumerate(definition_blocks):
 25  ->	            self._collect_local_values(locals_block)
```

<details>

```Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 79, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=args.external_checks_dir,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 25, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 50, in run
    self.check_tf_definition(report, root_folder, runner_filter)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 80, in check_tf_definition
    definitions_context = parser_registry.enrich_definitions_context(definition)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/registry.py", line 27, in enrich_definitions_context
    self.definitions_context[tf_file][definition_type] = context_parser.run(tf_file, definition_blocks)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/base_parser.py", line 109, in run
    self.context = self.enrich_definition_block(definition_blocks)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/parsers/locals_context_parser.py", line 25, in enrich_definition_block
    self._collect_local_values(locals_block)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/parsers/locals_context_parser.py", line 11, in _collect_local_values
    for local_name, local_value in local_block.items():
AttributeError: 'str' object has no attribute 'items'
```
</details>

**Comment by schosterbarak** [comment]
I'm wondering if it's related to: https://github.com/bridgecrewio/checkov/pull/411
on it.

**Comment by schosterbarak** [comment]
@acdha  when running checkov on 
```
locals {
  environment   = lower(terraform.workspace)
}
```
i'm not getting the error. maybe on a different sample of tf file?

**Comment by acdha** [comment]
Interesting, let me try to reduce this project more.

**Comment by acdha** [comment]
I haven't traced exactly how this causes the problem but it's due to a difference in HCL2 parsing. With Terraform v0.12.28, the older map syntax using key:value rather than key=value is accepted, doesn't trigger validation errors, etc. but Checkov fails. My locals block had a definition block like this which is causing the crash:

```hcl
  cidr_allocations = {
    "production" : "10.1.10.0/23",
    "staging" : "10.1.20.0/23",
    "testing" : "10.1.30.0/23",
    "development" : "10.1.40.0/23",
  }
```

**Comment by robeden** [comment]
Colons are HCL1 syntax, I believe. Possibly they weren't previously being processed because they would be ignored by the HCL2 parser and now it's falling back to HCL1 syntax and parsing them.

The other possible culprit is python-hcl2 which updated to version 0.3.0 with recent updates.

**Comment by schosterbarak** [comment]
Thank you @robeden and @acdha . I'm reverting the HCL1 support for now.

**Comment by acdha** [comment]
I think Hashicorp has documented them as going away at some point but they definitely work in their current Go implementation without a deprecation warning. I was going to add a `tflint` request since that should be flagged for whenever they eventually remove support.

**Comment by acdha** [comment]
Oh, curious — the source for https://www.terraform.io/docs/configuration/types.html was updated to list colons as being supported but the public website hasn't been updated yet:

https://github.com/hashicorp/terraform/commit/0b45a3c83de7b61f4068c5955bbd69fe13d691ab#diff-ecb60e13d71a004cccaea28e7c98aec8

It does look like python-hcl2 should support this.

**Comment by schosterbarak** [comment]
@acdha would you mind trying checkov==1.0.422 (latest) and letting us know if the problem was resolved ?

**Comment by acdha** [comment]
Yes, that fixed the problem on my project. Thanks!
