### ISSUE TITLE
Prisma Cloud Integration Issue

### ISSUE THREAD

**Issue by regicsolutions** [bridgecrewio/checkov#4142]
**Describe the issue**

I am trying to generate a cyclonedx sbom from a docker container and unable to use checkov with my Prisma Cloud `key::secret` as documented [here](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-code-security/scan-monitor/development-pipelines/sbom-generation): 

**Command:**
`checkov --repo-id MYORG/MYREPO --docker-image MYIMAGE --prisma-api-url https://us-east1.cloud.twistlock.com/us-x-XXXXXXXXX --bc-api-key ****::**** -o cyclonedx_json --output-file-path .`

Error: 
****
```
  [MainThread  ] [ERROR]  Failed to get customer assumed role
  Traceback (most recent call last):
    File "/home/user/.local/lib/python3.8/site-packages/urllib3/connectionpool.py
```

**Comment by nimrodkor** [comment]
Hey!

It seems you're using twistlock URL instead of the prisma one. Prisma API usually look like this:
https://api0.prismacloud.io

can you verify your URL, make sure you are using Prisma creds, and try again?

**Comment by regicsolutions** [comment]
> Hey!
> 
> It seems you're using twistlock URL instead of the prisma one. Prisma API usually look like this:
> https://api0.prismacloud.io
> 
> can you verify your URL, make sure you are using Prisma creds, and try again?

Isn't twistlock now Prisma cloud? Figured this url would work. How would I find my api url?

**Comment by nimrodkor** [comment]
@regicsolutions Still relevant?
If so, when logging into prisma cloud, what's the website URL for you? Prisma has stacks around the globe...
