### ISSUE TITLE
Change default behavior of the cloud integration: BcPlatformIntegration.get_guidelines() 

### ISSUE THREAD

**Issue by jare19** [bridgecrewio/checkov#416]
**Is your feature request related to a problem? Please describe.**
Every time Checkov runs it reaches out to the Bridgecrew cloud API server to retrieve guideline information that is not even available in the CLI output. (from what I could find)
I believe this behavior falls under a privacy concern.

**Describe the solution you'd like**
I would like to see either a flag (off by default) to retrieve this information ( _if_ it is ever consumable from the cli output) or moved into [the block where an api key is validated.](https://github.com/bridgecrewio/checkov/blob/bbe95c49879566ef8053dd6a1731d8cc66e8bd9f/checkov/main.py#L61)
Either way, I (I am sure others as well) would like it NOT to reach out to the internet by default.

**Describe alternatives you've considered**
`export BC_API_URL=""` works but IMO is not the right work around.

**Additional context**
[BcPlatformIntegration.get_guidelines()](https://github.com/bridgecrewio/checkov/blob/bbe95c49879566ef8053dd6a1731d8cc66e8bd9f/checkov/common/bridgecrew/platform_integration.py#L135)

[called by default in main](https://github.com/bridgecrewio/checkov/blob/bbe95c49879566ef8053dd6a1731d8cc66e8bd9f/checkov/main.py#L69)

That said, I would bet you are not doing anything with my data, but the disclaimer is unclear that you reach out by default on every run. If I was getting useful info that we could do something with, that would be different (would still like to have it flagable though) but as far as I can tell, I can't do anything with the guideline dict that is retrieved from the API via CLI.  Maybe just add a field in the check for remediation links/info to be used in the output (if that is your end goal)?

**Comment by nimrodkor** [comment]
Hey @jare19 !

I completely understand your hesitance. As you can see from the code you've reviewed, the API doesn't actually send any data but rather gets data from our API. The guidelines that it gets are added to the findings printed in the end, in the report - you'll probably see a `Guide` for most of the findings if you use the CLI output. Example output:
```
Check: CKV_AWS_25: "Ensure no security groups allow ingress from 0.0.0.0:0 to port 3389"
	PASSED for resource: aws_security_group.aurora_cluster_sg
	Guide: https://docs.bridgecrew.io/docs/networking_2
	File: /accountStack/auroraRDS/rds/main.tf:147-201
```

Would you consider that useful enough?

**Comment by schosterbarak** [comment]
As a reference
The goal was to answer:
https://github.com/bridgecrewio/checkov/issues/89
and 
https://github.com/bridgecrewio/checkov/issues/46

**Comment by jare19** [comment]
Ah, that must of just got added recently and why i started getting this output today when i updated checkov:
`WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))': /api/v1/guidelines
2020-07-02 17:21:42,621 [MainThread  ] [WARNI]  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))': /api/v1/guidelines`
thus triggering my inspection.
I have not been able to see that output though, while on my vpn because of the proxy my company uses.  I do still see a case for enabling it and not having to disable it by default.

And yep, I did see that it is only`GET`ing data. That does not mean bridgecrew does not get data, it just means bridgecrew isn't getting Checkov `POST` data.

Thanks for your attention and responses

**Comment by schosterbarak** [comment]
hey @jare19  i've just added a `--no-guide` flag for this propose: https://github.com/bridgecrewio/checkov/pull/417 mind giving it a try?

**Comment by nimrodkor** [comment]
Thanks for reporting @jare19 . We're working on improving this, will update soon

**Comment by jare19** [comment]
If you prefer it on by default, it looks good to me. I tested and works great.  I did comment on #46 regarding external checks though, and how we might go about adding the same field.

**Comment by schosterbarak** [comment]
Thanks @jare19 . closing this issue for now. I'll answer on #46 thread regarding external checks
