### ISSUE TITLE
Checkov Taking 10x longer to check code since 2.2.252

### ISSUE THREAD

**Issue by darren-johnson** [bridgecrewio/checkov#4230]
**Describe the issue**
We have been using Checkov for over a year now with very few issues. However yesterday when the docker container version changed from 2.2.252 the checks went from 3 mins in our pipeline to over 30 mins! I am able to repeat this locally too.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**

**Comment by gruebel** [comment]
hey @darren-johnson thanks for reaching out. We enabled a new feature yesterday and colleague of my is working on a performance improvement. I will share the version number with the fix, when it is released.

**Comment by gruebel** [comment]
@darren-johnson the fix was merged and is included in version ` >= 2.2.256`. Would be great, if you can try it out again 🙂 
if it didn't get any better, then it would be great, if you could share more information about the flags you use and what kind of IaC you are checking against.

**Comment by YaaraVerner** [comment]
hey @darren-johnson, the fix is in version `2.2.256`, please let us know if it resolved the issue.

**Comment by darren-johnson** [comment]
Just tested and it seems to be back to 3 minutes again.  Thanks for your help!
