### ISSUE TITLE
Check: CKV_GCP_19: "Ensure GKE basic auth is disabled"

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/checkov#4264]
**Describe the issue**
The default for this is disabled yet the alert keeps firing. 

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
- 2.2.255

**Additional context**

**Comment by gruebel** [comment]
hey @brettcurtis thanks for reaching out.
Yeah you are right. The basic auth method was deprecated since GK! 1.19 😅
