### ISSUE TITLE
Some check should not apply when `enable_autopilot  = true`

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/checkov#4267]
**Describe the issue**

       │ Error: Conflicting configuration arguments
       │ 
       │   with module.test.google_container_cluster.this,
       │   on ../../../main.tf line 12, in resource "google_container_cluster" "this":
       │   12: resource "google_container_cluster" "this" {
       │ 
       │ "network_policy": conflicts with enable_autopilot
       ╵
       ╷
       │ Error: Conflicting configuration arguments
       │ 
       │   with module.test.google_container_cluster.this,
       │   on ../../../main.tf line 14, in resource "google_container_cluster" "this":
       │   14:   enable_binary_authorization = true
       │ 
       │ "enable_binary_authorization": conflicts with enable_autopilot

**Version (please complete the following information):**
 - 2.2.255

**Comment by gruebel** [comment]
hey @brettcurtis thanks for reaching out.
Yeah, this looks like a false positive on our side. Are you interested in contributing the needed change?

**Comment by brettcurtis** [comment]
If I can free up I might be able to but let me try to give a better list here because binary_auth is available I think it's just the provider that isn't ready for it. So I at least have to confirm that.
