### ISSUE TITLE
Suppression is failing for docker graph checks

### ISSUE THREAD

**Issue by JamesWoolfenden** [bridgecrewio/checkov#4278]
On an M1 mac:

Cant suppress any of the CKV2_DOCKER issues:

In the following dockerfile we have a violation of CKV2_DOCKER_2 and a suppression of it:
```
FROM arm64v8/alpine:3.17.1
# checkov:skip=CKV_DOCKER_3: Not a service
# checkov:skip=CKV_DOCKER_2: Not a service
# checkov:skip=CKV2_DOCKER_2: Not a service

RUN apk --no-cache add build-base git curl jq bash
RUN curl -s -k https://api.github.com/repos/bridgecrewio/yor/releases/latest | jq '.assets[] | select(.name | contains("linux_arm64")) | select(.content_type | contains("gzip")) | .browser_download_url' -r | awk '{print "curl -L -k " $0 " -o /usr/bin/yor.tar.gz"}' | sh
RUN tar -xf /usr/bin/yor.tar.gz -C /usr/bin/ && rm /usr/bin/yor.tar.gz && chmod +x /usr/bin/yor && echo 'alias yor="/usr/bin/yor"' >> ~/.bashrc
COPY entrypoint.sh /entrypoint.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/entrypoint.sh"]
```

The latest checkov- -2.2.278
gives us:
`
check: CKV2_DOCKER_2: "Ensure that certificate validation isn't disabled with curl"
        FAILED for resource: /Dockerfile.RUN
        File: /Dockerfile:7-7

                7 | RUN curl -s -k https://api.github.com/repos/bridgecrewio/yor/releases/latest | jq '.assets[] | select(.name | contains("linux_386")) | select(.content_type | contains("gzip")) | .browser_download_url' -r | awk '{print "curl -L -k " $0 " -o /usr/bin/yor.tar.gz"}' | sh

`

**Comment by mhanysz** [comment]
I also stumbled upon this issue. 

After a bit of code review it looks like `checkov\dockerfile\runner.py` contains code for skipping checks implemented in python (see `checkov\dockerfile\runner.py:142`) using comments, but similar code for graph checks seems to be missing.

`checkov\dockerfile\runner.py:211` calls `BaseRunner.run_graph_checks_results(...) which relies on the `runner_filter` to decide which result to include in the return value. A quick scan of the `RunnerFilter` class didn't come up with anything related to checking suppression comments in the scanned file. So it looks like the functionality to skip yaml based policies in dockerfiles is missing.
