### ISSUE TITLE
Add a check for AzureInstancePassword specific to scale sets 

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#428]
Currently AzureInstancePassword scans for virtual instance but not scale sets.  Either extend the existing check to also check scale sets or create a new check for scale sets only.   

https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-12-01/virtualmachinescalesets
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html
https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine_scale_set.html

**Comment by JamesWoolfenden** [comment]
check CKV_AZURE_1? @jonjozwiak
