### ISSUE TITLE
Bash Exit with Code 1

### ISSUE THREAD

**Issue by slalomdavidsinclair** [bridgecrewio/checkov#4293]
I am running checkov in an azure devops pipeline and get a bash exit with code 1 error during the run phase. Only the run portion encounters this error, the publish runs fine. My yaml code is

steps:
      - bash: |
          docker pull bridgecrew/checkov
        workingDirectory: $(System.DefaultWorkingDirectory)
        displayName: "Pull > bridgecrew/checkov"
      - bash: |
          docker run --volume $(System.DefaultWorkingDirectory):/terraform bridgecrew/checkov --directory /terraform --output junitxml > $(System.DefaultWorkingDirectory)/CheckovReport.xml
        workingDirectory: $(System.DefaultWorkingDirectory)
        displayName: "Run > checkov"
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunTitle: "Checkov Results"
          failTaskOnFailedTests: false
          testResultsFormat: "JUnit"
          testResultsFiles: "CheckovReport.xml"
          searchFolder: "$(System.DefaultWorkingDirectory)"
        displayName: "Publish > Checkov scan results"

**Comment by gruebel** [comment]
hey @slalomdavidsinclair thanks for reaching out.
If `checkov` finds incompliant resources, then it will return an exit code of `1`. To change this behaviour you need to the flag  `-s` or `--soft-fail`.
