### ISSUE TITLE
Use `#checkov:skip` in terraform tfvars file

### ISSUE THREAD

**Issue by ppawlowski** [bridgecrewio/checkov#4310]
**Describe the issue**
I have an IaC-defined infrastructure with one root module and multiple tfvars files, making my environments unique.
Since my `dev` environment does not need to be as strictly configured as the `production` one, I would like to skip several checks there but still check them on `production`.
Adding `#checkov:skip` in tfvars is not working for me.

**Examples**
I would like to add `#checkov:skip` in *.tfvars file to skip particular check in selected environment.

**Version (please complete the following information):**
 - 2.2.291

**Comment by JamesWoolfenden** [comment]
are all the tfvars files in one folder? How to run terraform differently between environments?

**Comment by ppawlowski** [comment]
> are all the tfvars files in one folder? How do you run terraform differently between environments?

Yes, tfvars files are in a different directory. I use them with teraform cli flag `--var-file` .

**Comment by gruebel** [comment]
we won't implement this. you can create multiple `checkov` config files and references them via the flag `--config-file` when scanning different folders
