### ISSUE TITLE
Check MariaDB SSL Enforcement Enabled

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#432]
For TF Azure and ARM templates, add a check for MariaDB SSL enabled.  This is the exact same check as CKV_AZURE_28.  However, it targets different resources: 

TF: azurerm_mariadb_server (https://www.terraform.io/docs/providers/azurerm/r/mariadb_server.html)
ARM: Microsoft.DBforMariaDB/servers (https://docs.microsoft.com/en-us/azure/templates/microsoft.dbformariadb/2018-06-01/servers)

Alternatively, just modify both MySQLServerSSLEnforcementEnabled.py files to cover these resources and update the text appropriately

**Comment by askalik** [comment]
is this still open, and needed ?  could i be assigned

**Comment by JamesWoolfenden** [comment]
Go for it @askalik!

**Comment by askalik** [comment]
@JamesWoolfenden  did you already correct this issue?  I am looking at both the azure mariadb ssl and azure mysql it seems like the ssl enabled check is already present
