### ISSUE TITLE
CKV_AZURE_12: Bicep reports always the retention is lower than 90 days

### ISSUE THREAD

**Issue by sbe-arg** [bridgecrewio/checkov#4325]
**Describe the issue**
CKV_AZURE_12 should accept values of 91 or higher in bicep and not report any errors.

**Examples**
![image](https://user-images.githubusercontent.com/23391642/214427933-3da3eba5-6903-456b-875b-a600e48e3cc4.png)

**Version (please complete the following information):**
 - latest v12

**Comment by gruebel** [comment]
hey @sbe-arg thanks for reaching out.
I tested it and I think it is related to the argument `enabled: enableLogs`, if this clearly not set to `true` then this check fails.

**Comment by sbe-arg** [comment]
hahaha great point @gruebel I had default to false that parameter I have done the opposite now default to true and send a false when required and the errors cleared up so is not that the information is not being captured.

Although if the logs are disabled regardless of the int value the check should be skipped right?

**Comment by sbe-arg** [comment]
or should analyzed also if set to false either way does not seem something is wrong or missing
