### ISSUE TITLE
broken links in policy index

### ISSUE THREAD

**Issue by PatMyron** [bridgecrewio/checkov#4333]
https://www.checkov.io/5.Policy%20Index/all.html

782 links to files directly in [`main/checkov/terraform/checks/graph_checks/`](https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/graph_checks) (missing the provider subdirectories before the direct file name)

---

unrelated, it'd also be nice if all policy index links were clickable as well

**Comment by gruebel** [comment]
hey @PatMyron thanks for reaching out.
Nice catch 🥇 should be no problem to add the provider to the link. For the link I need to check, where exactly the docs are generated 🧐
