### ISSUE TITLE
BaseCheck.details only used in terraform runner

### ISSUE THREAD

**Issue by mhanysz** [bridgecrewio/checkov#4336]
**Description of the issue**
The documentation regarding the implementation of custom policies in python tells the user to add error messages to `self.details` (see https://www.checkov.io/3.Custom%20Policies/Python%20Custom%20Policies.html). The only runner I could find in the codebase that actually makes use of this property is the terraform runner. All the other runners I looked at instantiate the `Record` class without specifying the details. Thus, the details are never shown in the console output or any other form of output.

**Additional context**
Terraform runner instantiates `Record` class with details: `checkov\terraform\runner.py:439`
Dockerfile runner instantiates `Record` class without details: `checkov\dockerfile\runner.py:259`
Kubernetes runner instantiates `Record` class without details: `checkov\kubernetes\runner.py:200`
etc.

**Comment by gruebel** [comment]
hey @mhanysz thanks fore reaching out.
The `details` property was an OSS contribution, so feel free to add it to the other runners and create a PR 🙂
