### ISSUE TITLE
First Run After (pip3 method) (cannot import name 'LegacyVersion' from 'packaging.version')

### ISSUE THREAD

**Issue by DevGumbo** [bridgecrewio/checkov#4348]
**Describe the issue**
This happened after first install on my macbook pro. Looking to run against a terraform plan that i exported and converted to json.
Install method was 
pip3 install checkov
Created env for this 

Apologize if this is not enough information. Will get better at asking questions as i understand the product better.

**Examples**
Traceback (most recent call last):
  File "/Users/jondoe/Python/envs/checkov/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/Users/jondoe/Python/envs/checkov/lib/python3.8/site-packages/checkov/main.py", line 20, in <module>
    from checkov.argo_workflows.runner import Runner as argo_workflows_runner
  File "/Users/jondoe/Python/envs/checkov/lib/python3.8/site-packages/checkov/argo_workflows/runner.py", line 8, in <module>
    from checkov.common.output.report import CheckType
  File "/Users/jondoe/Python/envs/checkov/lib/python3.8/site-packages/checkov/common/output/report.py", line 21, in <module>
    from checkov.common.util.json_utils import CustomJSONEncoder
  File "/Users/jondoe/Python/envs/checkov/lib/python3.8/site-packages/checkov/common/util/json_utils.py", line 6, in <module>
    from packaging.version import LegacyVersion, Version
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/Users/jondoe/Python/envs/checkov/lib/python3.8/site-packages/packaging/version.py)

**Version (please complete the following information):**
 - Checkov Version [Latest for pip3 install]

**Additional context**

**Comment by DevGumbo** [comment]
i did a brew install on my mac and it runs great. It also says that i was running on a version 2.2.300 and when i updated it throws the  above error.

Also of interest, when i run the check against the file in checks for aws terraform, it only checks the original items in the file and will not keep running down the terraform file to check the other config blocks that i added to test additional properties.

Is there a limit to the check files or a cache that must be refreshed after editing the file ?

**Comment by gruebel** [comment]
hey @DevGumbo thanks for reaching out.

The first error you posted was fixed roughly a month ago, so you somehow installed an old version, everything before `2.2.147` doesn't work with the newest `packaging` version.

I f you do a brew install then I recommend to stay with it, otherwise you can get strange errors, if links to the executable are not correctly updated.

I'm not sure, if I understand your problem. Did you write a custom check or some of the existing checks don't work correctly? Please add a bit more info on your setup, then I can probably help better 🙂

**Comment by DevGumbo** [comment]
Yes so i got brews version to work so i could start writing some custom checks.
I am working with the Terraform aws_dlm_lifecycle_policy check and looking to understand how the ingestion and serialization works for the reading of the terraform code into python checks.

TL:DR changing the order of child elements in policy_details causes the check to skip the block entirely

It is interesting to me since the code for the built in check is as follows

` def scan_resource_conf(self, conf):
        if conf.get("policy_details") and isinstance(conf.get("policy_details"), list):
            
            self.details.append(conf.get("policy_details"))
            policy = conf.get("policy_details")[0]`
            
            So i did an append to the output to see what it sees and get this
            `Details: [{'action': [{'cross_region_copy': [{'encryption_configuration': [{'cmk_arn': ['aws_kms_key.test.arn'], 'encryption': [False]}], 'retain_rule': [{'interval': [15], 'interval_unit': ['MONTHS']}]}], 'event_source': [{'parameters': [{'description_regex': ['^.*Created for policy: policy-1234567890abcdef0.*$'], 'event_type': ['shareSnapshot'], 'snapshot_owner': [['data.aws_caller_identity.current.account_id']]}], 'type': ['MANAGED_CWE']}], 'name': ['tf-acc-basic']}], 'policy_type': ['EVENT_BASED_POLICY'], 'resource_types': [[]], 'target_tags': [{}]}]`
            
            Which is great when i am trying to determine where in the object map that pieces can be found .
            
            However, if i change the order of child attributes in the terraform block specificaly for the "policy_details" which i would have thought returned a list of objects as follows
            
            `[
    {
    'action': [{
        'cross_region_copy': [{'encryption_configuration': [{'cmk_arn': ['aws_kms_key.test.arn'], 'encryption': [True]}], 'retain_rule': [{'interval': [15], 'interval_unit': ['MONTHS']}]}], 'name': ['tf-acc-basic']
        }], 
    'policy_type': ['EVENT_BASED_POLICY'],
    'resource_types': [[]], 
    'schedule': [{
        'create_rule': [{
            'interval': [24], 
            'interval_unit': ['HOURS'], 
            'times': [['23:45']]}], 
        'event_source': [{
            'parameters': [{
                'description_regex': ['^.*Created for policy: policy-1234567890abcdef0.*$'], 
                'event_type': ['shareSnapshot'], 
                'snapshot_owner': [['data.aws_caller_identity.current.account_id']]}], 
                'type': ['MANAGED_CWE']}], 
                'name': ['2 weeks of daily snapshots']}], 
    'target_tags': [{}]
    }
]`
So i should be able to use the get method and find what we want to check regardless of the terraform order which in the default is provided terraform check is as follows

`resource "aws_dlm_lifecycle_policy" "fail" {
  description        = "tf-acc-basic"
  execution_role_arn = aws_iam_role.example.arn

  policy_details {
    policy_type = "EVENT_BASED_POLICY"

    resource_types = []
    target_tags    = {}

   
       action {
        name = "tf-acc-basic"
        cross_region_copy {
          encryption_configuration {
            cmk_arn    = aws_kms_key.test.arn
            encryption = false
          }
          retain_rule {
            interval      = 15
            interval_unit = "MONTHS"
          }

        }

    event_source {
      type = "MANAGED_CWE"
      parameters {
        description_regex = "^.*Created for policy: policy-1234567890abcdef0.*$"
        event_type        = "shareSnapshot"
        snapshot_owner    = [data.aws_caller_identity.current.account_id]
      }

    }
    }
  }
}`

But if i change to where actions is not first in the policy_details block, the check doesnt even attempt it
Code below is changed terraform policy_details order

`resource "aws_dlm_lifecycle_policy" "pass" {
  description        = "tf-acc-basic"
  execution_role_arn = aws_iam_role.example.arn

  policy_details {
    policy_type = "EVENT_BASED_POLICY"

    resource_types = []
    target_tags    = {}

    schedule {
      name = "2 weeks of daily snapshots"

      create_rule {
        interval      = 24
        interval_unit = "HOURS"
        times         = ["23:45"]
      }
    action {
      name = "tf-acc-basic"
      cross_region_copy {
        encryption_configuration {
          cmk_arn    = aws_kms_key.test.arn
          encryption = true
        }
        retain_rule {
          interval      = 15
          interval_unit = "MONTHS"
        }

      }
    }

    event_source {
      type = "MANAGED_CWE"
      parameters {
        description_regex = "^.*Created for policy: policy-1234567890abcdef0.*$"
        event_type        = "shareSnapshot"
        snapshot_owner    = [data.aws_caller_identity.current.account_id]
      }
    }
  }
}
}`

**Comment by DevGumbo** [comment]
sorry for horrible code block editing, trying to figure out how to make it more legible.
