### ISSUE TITLE
GitLab SAST encounters error parsing the report

### ISSUE THREAD

**Issue by yeongzhiwei** [bridgecrewio/checkov#4384]
**Describe the issue**
`gitlab_sast` was added to the output in #4315. GitLab SAST produced the following error when attempting to parse the report.

```
[Schema] property '/vulnerabilities/0/identifiers/0/url' is not of type: string
[Schema] property '/vulnerabilities/0/links/0/url' is not of type: string
```

I found that `url` value is set to `null` which is not supported e.g.

```json
    "vulnerabilities": [
        {
            "id": "..."
            "identifiers": [
                {
                    "name": "CKV_AWS_283",
                    "type": "checkov",
                    "url": null,
                    "value": "CKV_AWS_283"
                }
            ],
            "links": [
                {
                    "url": null
                }
            ],
           ...
  ]
```

`url` is not a required field so instead of setting the value to `null`, drop the key altogether

schema reference: https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/sast-report-format.json

**Comment by gruebel** [comment]
hey @yeongzhiwei thanks for reaching out.
Didn't expect they are so picky on the values and not accepting `null` as a non-existing field. Will create a PR to fix it

**Comment by yeongzhiwei** [comment]
Thanks for fixing this. Now it no longer shows the error but it also says there's 0 vulnerabilities when there are couples... weird will check and create a new issue
