### ISSUE TITLE
Scanning IAM policy only takes First SID in json rather than looping through

### ISSUE THREAD

**Issue by kmroz0991** [bridgecrewio/checkov#443]
**Describe the bug**
It seems when specifying more than one SID in a json, the policies do not loop through each one rather it just looks at the first one and ends. 

**To Reproduce**
1. Create policy with more than one SID
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "SqsAllow",
      "Effect": "Allow",
      "Action": [
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl",
        "sqs:ListDeadLetterSourceQueues",
        "sqs:ListQueues",
        "sqs:ReceiveMessage",
        "sqs:SendMessage",
        "sqs:SendMessageBatch"
      ],
      "Resource": "*"
          },
    {
      "Sid": "ALL",
      "Effect": "Allow",
      "Action": [ "*"
      ],
      "Resource": ["*"]
    },`
2. Run Checkov against policy

**Expected behavior**
I would expect the scan to check each json within the policy rather than the first one

**Desktop (please complete the following information):**
 - OS: Mac
 - Checkov Version: 1.0.442

**Comment by tronxd** [comment]
Hey @kmroz0991, thank you for reporting this!
please install the latest checkov release and report if the issue re-occurs

**Comment by kmroz0991** [comment]
@tronxd  that worked, Thank you for the quick fix on this!
