### ISSUE TITLE
CKV_AWS_145 is using deprecated resource

### ISSUE THREAD

**Issue by slalomdavidsinclair** [bridgecrewio/checkov#4442]
Using Terraform for AWS to create an s3 bucket with encryption throws this in the code errors [NONE][CKV_AWS_145] Ensure that S3 buckets are encrypted with KMS by default. When you look at the explanation it is looking for an inline resource instead of a separate block https://docs.bridgecrew.io/docs/ensure-that-s3-buckets-are-encrypted-with-kms-by-default. If you look at the Terraform provider documentation the inline resource has been deprecated [
](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket)
the text is "NOTE on S3 Bucket Server Side Encryption Configuration:
S3 Bucket Server Side Encryption can be configured in either the standalone resource [aws_s3_bucket_server_side_encryption_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_server_side_encryption_configuration) or with the deprecated parameter server_side_encryption_configuration in the resource aws_s3_bucket. Configuring with both will cause inconsistencies and may overwrite configuration."

**Examples**
 resource "aws_s3_bucket" "config_backend_bucket" {
   bucket = var.config_bucket_name
   tags = merge(var.shared_tags,
     {
       Name = var.config_bucket_name
     }
   )
   lifecycle {
    prevent_destroy = true
   }
 }

resource "aws_s3_bucket_server_side_encryption_configuration" "encrypt_config_backend_bucket" {
  bucket = aws_s3_bucket.config_backend_bucket.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

**Version (please complete the following information):**
 - Checkov Version Latest

**Comment by nimrodkor** [comment]
Yes, the docs are outdated, thanks for noticing! Updated the tagging.

However, the check is implemented as a graph check checks the correct attributes of the connected resource. 
If you disagree, please:
1. Provide the actual checkov version, not `Latest`
2. Provide example file and output
@slalomdavidsinclair

**Comment by tsmithv11** [comment]
Docs were updated. Let me know if there are other issues.
