### ISSUE TITLE
Azure: Audit enabling of diagnostic logs 

### ISSUE THREAD

**Issue by VeselinaElze** [bridgecrewio/checkov#4462]
**Describe the issue**
I want to be sure that my azure resources have monitor diagnostic settings enabled.
Problem is that azurerm_monitor_diagnostic_setting is a separate resource. 
Need a way when scanning a resource to be able to check if there is a azurerm_monitor_diagnostic_setting linked to it.

Even if it's not in the standard policies, I cannot find a way to make a custom check for it.

**Examples**

```
resource "azurerm_key_vault" "example" {
  name                        = "examplekeyvault"
  location                    = azurerm_resource_group.example.location
  resource_group_name         = azurerm_resource_group.example.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = true
  public_network_access_enabled = false

  sku_name = "standard"
  network_acls {
    default_action = "Deny"
    bypass = "AzureServices" 
    }

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Get",
    ]

    secret_permissions = [
      "Get",
    ]

    storage_permissions = [
      "Get",
    ]
  }
}
```

Should return:
```
Check: CKV_AZURE_999: "Ensure that diagnostic logs are enabled"
        FAILED for resource: azurerm_key_vault.example
        File: /main.tf:87-118

```

**Version (please complete the following information):**
 - Checkov Version 2.2.357

**Comment by JamesWoolfenden** [comment]
You need to make a yaml graph check, something like https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/azure/VMHasBackUpMachine.yaml but with your resources.

**Comment by VeselinaElze** [comment]
Oh thanks! I missed that "connected_resource_types:" possibility in the docs
Do you have a python example by any chance?

**Comment by JamesWoolfenden** [comment]
nay - graph checks are always yaml

**Comment by VeselinaElze** [comment]
Thanks for the guidance. With this I can sort my policies out
