### ISSUE TITLE
Checkov and AZCli cannot exist in the same yml pipeline

### ISSUE THREAD

**Issue by davejones8389** [bridgecrewio/checkov#4492]
We have yml pipelines which haven't changed much at all over time

- name: Checkov GitHub Action
  uses: bridgecrewio/checkov-action@master
  with:
    directory: ./terraform

- name: Remove IP from Storage Account Allowlist
  uses: azure/CLI@v1
  with:
    inlineScript: |
      IP=$(curl ipinfo.io/ip)
      az storage account network-rule remove --resource-group mickeymouse --account-name mickeymouse123 --ip-address "$IP"

For some reason, if we run the AZCLI command AFTER Checkov, then the AZCLI command fails with error:
Error: Error: Unable to find image 'that:latest' locally
docker: Error response from daemon: pull access denied for that, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
& when I expand my AZCli output (in GitHub),  it references Checkov
Run azure/CLI@v1
with:
inlineScript: IP=$(curl ipinfo.io/ip)
az storage account network-rule remove --resource-group mickeymouse --account-name mickeymouse123 --ip-address "$IP"
azcliversion: agentazcliversion
env:
TERRAFORM_VERSION: 1.3.7
AZURE_HTTP_USER_AGENT:
AZUREPS_HOST_ENVIRONMENT:
TERRAFORM_CLI_PATH: /home/runner/work/temp/e27bde45-ee36-430f-8381-0a5c4c79e178
CHECKOV_RESULTS:
_               _
| |   ___  | | _______   __
/ _| ' \ / _ / | |/ / _ \ \ / /
| (| | | |  / (|   < () \ V /
_|| ||___|___|_|____/ _/
By bridgecrew.io | version: 2.2.326
terraform scan results:
Passed checks: 5, Failed checks: 0, Skipped checks: 0
Check: CKV_AZURE_110: "Ensure that key vault enables purge protection"
PASSED for resource: azurerm_key_vault.key_vault
File: /keyvault.tf:6-25
Guide: https://docs.bridgecrew.io/docs/ensure-that-key-vault-enables-purge-protection
Check: CKV_AZURE_189: "Ensure that Azure Key Vault disables public network access"
PASSED for resource: azurerm_key_vault.key_vault
File: /keyvault.tf:6-25
Check: CKV_AZURE_42: "Ensure the key vault is recoverable"
PASSED for resource: azurerm_key_vault.key_vault
File: /keyvault.tf:6-25
Guide: https://docs.bridgecrew.io/docs/ensure-the-key-vault-is-recoverable

**Comment by JamesWoolfenden** [comment]
cannot lie. thought this must be user error, could not think how this could be true. It is however 100% repeatable;
`---
# yamllint disable rule:line-length
name: Verify
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: read-all

env:
  terraform: 1.3.0
  branch: main
  name: Checkov GitHub Action
jobs:
  terraform:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
          fetch-depth: '0'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: az cli
        uses: azure/cli@v1.0.7
        with:
          inlineScript: az storage account list    
      - name: checkov 
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          soft_fail: true
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    
      - name: az cli
        uses: azure/cli@v1.0.7
        with:
          inlineScript: az storage account list`

causes the az cli to be messed up:

`Run azure/cli@v1.0.7
  with:
    inlineScript: az storage account list
    azcliversion: agentazcliversion
  env:
    terraform: 1.3.0
    branch: main
    name: Checkov GitHub Action
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    CHECKOV_RESULTS: 
         _               _              
     ___| |__   ___  ___| | _______   __
    / __| '_ \ / _ \/ __| |/ / _ \ \ / /
   | (__| | | |  __/ (__|   < (_) \ V / 
    \___|_| |_|\___|\___|_|\_\___/ \_/  
                                        
  By bridgecrew.io | version: [2](https://github.com/JamesWoolfenden/test/actions/runs/4234260453/jobs/7356304702#step:8:2).[3](https://github.com/JamesWoolfenden/test/actions/runs/4234260453/jobs/7356304702#step:8:3).32 
  terraform scan results:
  
  Passed checks: [4](https://github.com/JamesWoolfenden/test/actions/runs/4234260453/jobs/7356304702#step:8:4)1, Failed checks: [5](https://github.com/JamesWoolfenden/test/actions/runs/4234260453/jobs/7356304702#step:8:5), Skipped checks: 1
  
  Check: CKV_AWS_93: "Ensure S3 bucket policy does not lockout all but root user. (Prevent lockouts needing root account fixes)"
  	PASSED for resource: aws_s3_bucket.toxic
  	File: /aws/s3.tf:1-[7](https://github.com/JamesWoolfenden/test/actions/runs/4234260453/jobs/7356304702#step:8:7)
  	Guide: https://docs.bridgecrew.io/docs/bc_aws_s3_24
  Check: CKV_AWS_70: "Ensure S3 bucket does not allow an action with any Principal"
  	PASSED for resource: aws_s3_bucket.toxic
  	File: /aws/s3.tf:1-7
  	Guide: https://docs.bridgecrew.io/docs/bc_aws_s3_23
  Check: CKV_AWS_[9](https://github.com/JamesWoolfenden/test/actions/runs/4234260453/jobs/7356304702#step:8:9)3: "Ensure S3 bucket policy does not lockout all but root user. (Prevent lockouts needing root account fixes)"
  	PASSED for resource: aws_s3_bucket.duff
  	File: /aws/s[32](https://github.com/JamesWoolfenden/test/actions/runs/4234260453/jobs/7356304702#step:8:32).tf:1-3`

**Comment by davejones8389** [comment]
I dreaded the worst when I read 'user' error!  Happy to know it fails for you as well

**Comment by gruebel** [comment]
I took a look in the code of the Azure CLi GHA and they just pass all env vars directly to the container start, sounds like a big security risk 🙈 a possible workaround could be to set the `CHECKOV_RESULTS` env var to an empty string.
ex.
```yaml
      - name: az cli
        uses: azure/cli@v1.0.7
        with:
          inlineScript: az storage account list
        env:
          CHECKOV_RESULTS: ""
```
