### ISSUE TITLE
Unable to supply auth to private repositories in github action

### ISSUE THREAD

**Issue by zameer712** [bridgecrewio/checkov#4497]
**Describe the issue**
Unable to scan the terraform folders in an proper way according to our folder structure

**Examples**
terraform code scan for IAC

**Version (please complete the following information):**
 - [Checkov Version [e.g. 22]](version: 2.3.8)

**Additional context**
checkov is able to scan with . option but if we are specific a specific folder structure its not picking it up

please let me know if we can connect to fix it

**Comment by JamesWoolfenden** [comment]
you're going to have to describe the folder structure

**Comment by zameer712** [comment]
> you're going to have to describe the folder structure

![image](https://user-images.githubusercontent.com/102033066/218760499-1b9294e7-f67b-4306-8599-0860e119c3af.png)

This is how our folder structure is

**Comment by JamesWoolfenden** [comment]
and the command your using and which folder you cant see into?

**Comment by zameer712** [comment]
> and the command your using and which folder you cant see into?

![image](https://user-images.githubusercontent.com/102033066/218761085-acf0a9b6-aba1-43b5-9d4b-7362f26e8b6b.png)

**Comment by JamesWoolfenden** [comment]
You should really post this issue against the action repo, however what files are in the cloudnin directory?

**Comment by zameer712** [comment]
> You should really post this issue against the action repo, however what files are in the cloudnin directory?

All the files related to terraform code 

![image](https://user-images.githubusercontent.com/102033066/218761807-4c9f7c60-b19b-45d1-9638-f83153146acf.png)

**Comment by JamesWoolfenden** [comment]
and the output your getting?

**Comment by zameer712** [comment]
> and the output you're getting?

![image](https://user-images.githubusercontent.com/102033066/218762198-f87ae70e-c234-4796-8b3a-0d5bc5f58a27.png)

**Comment by JamesWoolfenden** [comment]
and those are private repos, how are you suppling the permission to get the private repos?

**Comment by zameer712** [comment]
> and those are private repos, how are you suppling the permission to get the private repos?

we are using github token to access the repos using personal tokens as well

**Comment by JamesWoolfenden** [comment]
i would use the checkov-action instead - it supports private repos and personal access tokens https://github.com/bridgecrewio/checkov-action/

**Comment by zameer712** [comment]
> i would use the checkov-action instead - it supports private repos and personal access tokens https://github.com/bridgecrewio/checkov-action/

Thanks for the update @JamesWoolfenden  keep you posted once its working fine

**Comment by gruebel** [comment]
Feel free to reach out again, if the issue still exists.
