### ISSUE TITLE
2.3.36 ignoring exceptions in modules

### ISSUE THREAD

**Issue by StorageMatt** [bridgecrewio/checkov#4548]
upgrading to 2.3.36, I'm now getting warnings regarding exceptions in place in modules already.

In my specific case I'm using a TF product to create IAM user accounts for multiple accounts which calls a central module, passing in parameters. There are exceptions in the module for `CKV_AWS_273` and `CKV_AWS_40` but I now get warnings output for every iteration of the module.
It's a bit noisy ;P

**Comment by gruebel** [comment]
hey @StorageMatt thanks for reaching out.

Can you share the warning output and the exceptions you get, hopefully it has some info we can use to investigate it.

**Comment by StorageMatt** [comment]
I'm going to have to apologise; sorry. When I went to grab the info for you, I noticed what I'd missed before - it was throwing errors on a plan json output file in the root of the repo (that I'd generated there as part of troubleshooting something else) not on the contents of the repo itself.
Sorry about that, and keep up the good work :)
