### ISSUE TITLE
skip-check and check options don't work

### ISSUE THREAD

**Issue by jeromevdl** [bridgecrewio/checkov#4552]
**Describe the issue**
_check_ and _skip-check_ options are not working as expected: 
- skip-check doesn't skip anything and run everything. 
- check doesn't check anything

**Examples**
`checkov -d .` returns `Passed checks: 440, Failed checks: 71`

`checkov -d . --skip-check LOW` returns the same while it should return nothing
`checkov -d . --skip-check MEDIUM` returns the same
`checkov -d . --skip-check HIGH` returns the same
`checkov -d . --skip-check CRITICAL` returns the same

`checkov -d . --check LOW` returns nothing while it should return everything
`checkov -d . --check MEDIUM` returns nothing 
`checkov -d . --check HIGH` returns nothing 
`checkov -d . --check CRITICAL` returns nothing 

**Version (please complete the following information):**

```
       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.3.38 
```                                      

**Additional context**

OS: MacOS M1 Monterey 12.6.3 
Installation: /opt/homebrew/bin/checkov (brew 4.0.3)
Python 3.10.9

**Comment by nimrodkor** [comment]
Hi @jeromevdl !
skipping by priority is available only by integrating with the platform via an API key. checkov itself does not have severities / priorities and so doesn't know how to handle it on its own.
