### ISSUE TITLE
--check and --skip-check does not work properly when severity (LOW, MEDIUM, HIGH, CRITICAL) is specified.

### ISSUE THREAD

**Issue by igor-pinchuk** [bridgecrewio/checkov#4567]
**Describe the issue**
When run checkov without providing severity level in --check and --skip-check it works fine and reports different issues (LOW and  MEDIUM).
`checkov -d /path/to/terraform`

When I run checkov with provided severity level it returns no alerts at all 
`checkov --check MEDIUM -d /path/to/terraform`

**Examples**
The command that returns no alerts:
`checkov --check MEDIUM -d /path/to/terraform`

**Version (please complete the following information):**
 version: 2.3.44

**Additional context**
When providing severity level with `--check MEDIUM` I expect to filter out LOW level alerts and get only MEDIUM, HIGH and CRITICAL alerts but receiving empty result instead.

**Comment by gruebel** [comment]
hey @igor-pinchuk thanks for reaching out.

Sorry for the possible misunderstanding, but severities are only added when using an API key, therefore the filter won't work. I'm adding now a warning message with my PR, because you are not the first to stumble upon it 🙂

**Comment by igor-pinchuk** [comment]
@gruebel , thank you for clarification and adding the warning message.
By the way, is there any reason not to show severity without API key?

**Comment by gruebel** [comment]
We keep the severity info in our backend, so users can adjust it to their needs. It was a product decision to not add them to `checkov`, I don't think it will change in the near future.
