### ISSUE TITLE
Wrong exit code with --hard-fail-on

### ISSUE THREAD

**Issue by dennisbrouwer91** [bridgecrewio/checkov#4574]
**Describe the issue**
In our pipeline we have certain checks that we want to hard fail (so a user cannot use the #checkov:skip line in their code to skip). I expect a non-zero exit code in this situation.
I'm testing it locally with the latest stable version, but it does not work.

**Examples**
Example of failing resource : 

```
resource "aws_s3_bucket" "test" {
  #checkov:skip=CKV2_AWS_6:La
  bucket = "test"
  versioning {
    enabled = true
  }
```

Then i run this command : 

`checkov --hard-fail-on CKV2_AWS_6 -d .`

After checking the exit-code with `echo $?` it shows the exit code was still 0.

**Version (please complete the following information):**
 - Checkov Version 2.3.30

**Additional context**

**Comment by gruebel** [comment]
hey @dennisbrouwer91 thanks for reaching out.

The flag `--hard-fail-on` was not meant to surpass skip comments. This functionality is only available in the platform to my knowledge and probably will stay there for the near future.
