### ISSUE TITLE
Update CKV2_AWS_12 for new resources

### ISSUE THREAD

**Issue by tsmithv11** [bridgecrewio/checkov#4581]
**Describe the issue**
AWS added two new resources in its latest provider:
aws_vpc_security_group_egress_rule
aws_vpc_security_group_ingress_rule

CKV2_AWS_12 - Ensure the default security group of every VPC restricts all traffic

Needs to be updated for this change

**Comment by Jhanvi12** [comment]
Hello , I would like to contribute for adding "aws_vpc_security_group_egress_rule" . Do we have to update the same rule CKV2_AWS_12 or create a new policy for this . Let me know and will work accordingly :)

**Comment by rotemavni** [comment]
@Jhanvi12 Thank you for wanting to contribute!
I think we can add it as an `or` condition to be backwards compatible to the old rule.
