### ISSUE TITLE
CHANGELOG is missing entries for 2.3.54, .55, and .56

### ISSUE THREAD

**Issue by ankon** [bridgecrewio/checkov#4598]
We started seeing our checkov checks fail again, and according to the logs we're on 2.3.56 ... but I cannot find changelog entries since 2.3.53.

The last update to it was https://github.com/bridgecrewio/checkov/commit/054871f8fcb0de4bb1d60379662aee5274a690d3, and it seems these happen out-of-band. Maybe the release process could be adjusted to make updating this file mandatory somehow?

(cc @gruebel)

**Comment by ankon** [comment]
Right, so the changelogs would "lag" for up to a day, which is a bit of an issue when checks start failing :)

I guess we could avoid this problem on our side by delaying the rollout (we're using the checkov github action with the floating tag introduced with https://github.com/bridgecrewio/checkov-action/pull/92), or the action updates itself should be made to lag; these look automated: https://github.com/bridgecrewio/checkov-action/commits/master

**Comment by gruebel** [comment]
yeah, we did in the past, but had to revert it back to be in-sync with the checkov package releases.
