### ISSUE TITLE
CKV_AWS_24,CKV_AWS_25,CKV_AWS_260 triggering for "self" security groups since 2.3.56

### ISSUE THREAD

**Issue by ankon** [bridgecrewio/checkov#4599]
**Describe the issue**

We've started to see failures with CKV_AWS_24, CKV_AWS_25 and CKV_AWS_260 since 2.3.56 for security groups in terraform that have a `self` setting:

```
  ingress {
    description = "Self"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    self        = true
  }
```

I think checkov should allow these by default, as the traffic will stay inside the security group. I could also see this being argued as "this is still bad", but then it should IMHO be a different check number so it can be specifically allowed.

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]: 2.3.56

**Additional context**

Bisected the failures to 74f235f19c09039a4714fa5428e1e17cfe75dc0e (https://github.com/bridgecrewio/checkov/pull/4575)
`self`: See for instance https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#self

_Why would you want that?????_: For instance this is needed for AWS Glue, see their documentation: https://docs.aws.amazon.com/glue/latest/dg/setup-vpc-for-glue-access.html

**Comment by gruebel** [comment]
yeah, I don't see any problem with allowing this by default, because the check itself targets a different use case, which is more about protecting yourself against unrestricted public access and to some degree also private one.
@JamesWoolfenden thoughts?

**Comment by JamesWoolfenden** [comment]
yeah seems like a user case the check wasnt designed for, but you know you asking for more logic in that base class....

**Comment by JamesWoolfenden** [comment]
However some of the reason for those checks is make people use non default ports for those activities, but that would be a different check where we just look for people using 22,80 and 3389. Think a new check that looks for standard ports?

**Comment by ankon** [comment]
FWIW: Getting the same one now for CKV_AWS_277 as well, somewhat expected as it shares the same base class.

**Comment by JamesWoolfenden** [comment]
they all greta fixed when the great merge in the sky happens
