### ISSUE TITLE
Check rational

### ISSUE THREAD

**Issue by bol** [bridgecrewio/checkov#46]
Thanks for sharing Checkov with the community. I've tried it out briefly on a few of our Terraform projects and found it easy enough to work with. I found some of the checks a little hard to understand the reasoning behind however.

Would it be reasonable to add a rational to each check where it's explained what kind of issues are being avoided by enforcing the check and why it is considered a best practice to follow a particular configuration?

**Comment by schosterbarak** [comment]
Hey @bol thanks for the input~
We tried to write the policies in a way that encapsulates the best practice+rationale and to avoid managing another dedicated KB (like https://www.cloudconformity.com/conformity-rules/ and https://github.com/cloudsploit/scans which are awesome)
Is there a specific check you think we should rename?

**Comment by jawoponlenuigalwaycom** [comment]
I can't download checkov. pip command didn't work . ERROR:  Could not find a version that satisfies the requirement checkov (from versions: )No matching distribution found for checkov
I tried with docker but it doesn't take in my file and the result is it has passed the test despite purposeful errors in tf file. ANY ADVISE WOULD BE GREATLY APPRECIATED
THANKS

**Comment by schosterbarak** [comment]
Hey @jawoponlenuigalwaycom can you please share more of the terminal logs?
i.e.:
```
Baraks-MacBook-Pro:tmp barak$ pipenv shell
Launching subshell in virtual environment…

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$  . /Users/barak/.local/share/virtualenvs/tmp-QvjedHaV/bin/activate
(tmp) bash-3.2$ pip install checkov
Collecting checkov
  Downloading checkov-1.0.172-py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 2.2 MB/s 
Collecting junit-xml==1.8
  Using cached junit-xml-1.8.tar.gz (10.0 kB)
Collecting six==1.13.0
  Using cached six-1.13.0-py2.py3-none-any.whl (10 kB)
Collecting pyyaml==5.2
  Using cached PyYAML-5.2.tar.gz (265 kB)
Collecting python-hcl2==0.2.0
  Using cached python-hcl2-0.2.0.tar.gz (43 kB)
Collecting urllib3==1.25.7
  Using cached urllib3-1.25.7-py2.py3-none-any.whl (125 kB)
Collecting termcolor==1.1.0
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Collecting requests==2.22.0
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Processing /Users/barak/Library/Caches/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e/docopt-0.6.2-py2.py3-none-any.whl
Collecting chardet==3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting tabulate==0.8.6
  Using cached tabulate-0.8.6.tar.gz (45 kB)
Collecting idna==2.8
  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)
Collecting dpath==1.5.0
  Using cached dpath-1.5.0.tar.gz (17 kB)
Collecting colorama==0.4.3
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Processing /Users/barak/Library/Caches/pip/wheels/01/a2/30/ebae6ffa73cf3aa1c972a24d4c78388afd910f91e43bf554aa/lark_parser-0.7.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Building wheels for collected packages: junit-xml, pyyaml, python-hcl2, termcolor, tabulate, dpath
  Building wheel for junit-xml (setup.py) ... done
  Created wheel for junit-xml: filename=junit_xml-1.8-py3-none-any.whl size=6760 sha256=c4ffeb4688e5a12f6a07358248e795dc7760804235c7607eb70c680d242dfc39
  Stored in directory: /Users/barak/Library/Caches/pip/wheels/6a/e1/0a/ffa1b973d53ace64a5f20f8a88583a8dcc244a5703af813f43
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.2-cp38-cp38-macosx_10_15_x86_64.whl size=44213 sha256=55895a7929e898fa5d273f0081b3ff1acb397195486b94554b409039106be4a1
  Stored in directory: /Users/barak/Library/Caches/pip/wheels/66/8c/82/1a5614c4cf7290946972709ebb54b579762043aed7f49c6620
  Building wheel for python-hcl2 (setup.py) ... done
  Created wheel for python-hcl2: filename=python_hcl2-0.2.0-py3-none-any.whl size=42000 sha256=da5bbd3b4f549dc8cdf3a4cbfdfb113b429e44076bc048e8e5a605dfa7002257
  Stored in directory: /Users/barak/Library/Caches/pip/wheels/75/3f/a9/b0dd11c30edfaf8d630a842358c03324b56337069c4b375686
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=2737a8043d6f58cf88d26af4b0261daddc0a8d2732547a30c9aebc6fad959969
  Stored in directory: /Users/barak/Library/Caches/pip/wheels/a0/16/9c/5473df82468f958445479c59e784896fa24f4a5fc024b0f501
  Building wheel for tabulate (setup.py) ... done
  Created wheel for tabulate: filename=tabulate-0.8.6-py3-none-any.whl size=23270 sha256=aac935223e58dd2e52e9d0f1fca3f7f6ce364cf684523fe76fd908aeef846957
  Stored in directory: /Users/barak/Library/Caches/pip/wheels/86/8c/d9/3b6c2f55efaefe656c52b725d2fdc5669085c83444979db8b3
  Building wheel for dpath (setup.py) ... done
  Created wheel for dpath: filename=dpath-1.5.0-py3-none-any.whl size=14590 sha256=a421b7bff68140de8a3ba9600a2a6ea7378e0c9b8a3c7511fc9c9afbebef5d3b
  Stored in directory: /Users/barak/Library/Caches/pip/wheels/62/70/49/400c325d1db02901ad862338304643ea65e8a68c84e36d9125
Successfully built junit-xml pyyaml python-hcl2 termcolor tabulate dpath
Installing collected packages: six, junit-xml, pyyaml, docopt, lark-parser, python-hcl2, urllib3, termcolor, certifi, idna, chardet, requests, tabulate, dpath, colorama, checkov
Successfully installed certifi-2019.11.28 chardet-3.0.4 checkov-1.0.172 colorama-0.4.3 docopt-0.6.2 dpath-1.5.0 idna-2.8 junit-xml-1.8 lark-parser-0.7.8 python-hcl2-0.2.0 pyyaml-5.2 requests-2.22.0 six-1.13.0 tabulate-0.8.6 termcolor-1.1.0 urllib3-1.25.7
(tmp) bash-3.2$ checkov -h
usage: checkov [-h] [-v] [-d DIRECTORY] [-f FILE] [--external-checks-dir EXTERNAL_CHECKS_DIR] [-l] [-o [{cli,json,junitxml}]]

Add some integers.

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         Checkov version
  -d DIRECTORY, --directory DIRECTORY
                        Terraform root directory (can not be used together with --file). Can be repeated
  -f FILE, --file FILE  Terraform file(can not be used together with --directory)
  --external-checks-dir EXTERNAL_CHECKS_DIR
                        Directory for custom checks to be loaded. Can be repeated
  -l, --list            List checks
  -o [{cli,json,junitxml}], --output [{cli,json,junitxml}]
                        Report output format

```

**Comment by jawoponlenuigalwaycom** [comment]
Collecting checkov
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fafff5bb208>: Failed to establish a new connection: [Errno -2] Name or service not known',))': /simple/checkov/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fafff5bb2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))': /simple/checkov/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fafff5bb358>: Failed to establish a new connection: [Errno -2] Name or service not known',))': /simple/checkov/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fafff5bb390>: Failed to establish a new connection: [Errno -2] Name or service not known',))': /simple/checkov/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fafff5bb550>: Failed to establish a new connection: [Errno -2] Name or service not known',))': /simple/checkov/
  Could not find a version that satisfies the requirement checkov (from versions: )
No matching distribution found for checkov

**Comment by jawoponlenuigalwaycom** [comment]
![Capture](https://user-images.githubusercontent.com/56373264/74253983-ba998100-4ce7-11ea-95e9-f2971d381f12.PNG)
![image](https://user-images.githubusercontent.com/56373264/74254818-e5d0a000-4ce8-11ea-892d-1190271a47fa.png)
1) pip command error 

2) The docker had been pulled at this point. Docker error: showing its correct although its not. Thanks again

**Comment by schosterbarak** [comment]
hey @jawoponlenuigalwaycom it looks like a networking issue. are you working on a non-public subnet with a pypi mirror? 
you can update to custom pypi mirror using that config: https://pipenv.kennethreitz.org/en/latest/advanced/
and download checkov that way.

as for docker -seems like you are not using the latest version. does it happen also at the latest?

**Comment by jawoponlenuigalwaycom** [comment]
Thanks for the reply, The error still occurs with latest. I also tried downloading the source file but even when extracted it's setup file doesn't execute.

**Comment by schosterbarak** [comment]
Thanks @jawoponlenuigalwaycom seems like something is missing, I'd love to set up an online Zoom session and debug it together with you. Can you please send some matching time slots to barak@brisgecrew.io ?

**Comment by jawoponlenuigalwaycom** [comment]
Thanks for your help!! My issue was a proxy configurations.Now it works fine.
![image](https://user-images.githubusercontent.com/56373264/74536225-8912f680-4f2f-11ea-9bb4-a664a78e7ad1.png)

**Comment by bol** [comment]
> Hey @bol thanks for the input~
> We tried to write the policies in a way that encapsulates the best practice+rationale and to avoid managing another dedicated KB (like https://www.cloudconformity.com/conformity-rules/ and https://github.com/cloudsploit/scans which are awesome)
> Is there a specific check you think we should rename?

Hello and sorry for the late reply, I've been locked out of my github account. 2FA is awesome until your phone breaks :-/

There is no specific check but more of a general usability question. I think that it's phrased better in the duplicate ticket #89 which seems to be actively worked on so I'll be happy to close this one.

**Comment by schosterbarak** [comment]
@bol done!
now you have a public guide link on each check 
![image](https://user-images.githubusercontent.com/6033501/86403267-08724e00-bcb6-11ea-8b70-c2ed620040ec.png)

**Comment by jare19** [comment]
Awesome work on the default checks, can we accomplish this with additional (external) checks as well?

**Comment by schosterbarak** [comment]
@jare19 2 ways to achieved that
1. You can try to implement the same API the bridgecrew platform has to match between checkov check_ids to external guideline links. Though this is not originally intended. 
2. This is a feature that bridgecrew SaaS team is working on. feel free to signup and get an update once it's available or track the enterprise [changelog](https://docs.bridgecrew.io/changelog/) .

**Comment by saybalex** [comment]
Hello i have installed checkov using pip but i am unable to still run it
