### ISSUE TITLE
[CKV_AWS_145] Ensure that S3 buckets are encrypted with KMS by default

### ISSUE THREAD

**Issue by jbstans** [bridgecrewio/checkov#4624]
**Describe the issue**
Terraform have split out the S3 options into rules, much like Security Group Rules have been split out from Security Groups. This check fails, even when encryption is enabled, if it's done using the new method.

**Examples**

Heavily cut down, but: 

```
resource "aws_s3_bucket" "this" {
  bucket = redacted
  tags   = merge(var.tags, var.s3_tags)
}

resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  count  = var.enable_sse_kms ? 1 : 0
  bucket = aws_s3_bucket.this.id
  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.this[count.index].arn
      sse_algorithm     = "aws:kms"
    }
  }
}
```

This should pass the check as SSE is enabled, but it is failing as it doesn't seem Checkov is checking for the updated syntax.

**Version (please complete the following information):**
 - Container version at build time was: 2.3.60

**Additional context**
None.

**Comment by gruebel** [comment]
hey @jbstans thanks for reaching out.

It is supported for almost a year. My guess is the `count  = var.enable_sse_kms ? 1 : 0` is evaluated as `false` and then we ignore the resource for the check evaluation. You can try to remove the count block and then re-run it.

**Comment by terra-conq** [comment]
If you are using default value for enable_sse_kms variable do ensure that it is not false. That's causing the check to be bypassed

**Comment by IskanderNovena** [comment]
I have a similar situation, where the encryption is set using this:

```
resource "aws_s3_bucket_server_side_encryption_configuration" "s3_encryption" {
  bucket = aws_s3_bucket.lb_logs.bucket
  rule {
    bucket_key_enabled = true
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}
```

And checkov triggers:

```
Check: CKV_AWS_145: "Ensure that S3 buckets are encrypted with KMS by default"
	FAILED for resource: aws_s3_bucket.lb_logs
```

**Comment by gruebel** [comment]
@jbstans in general it should work, but depending on where the value for `var.enable_sse_kms` comes from, it can get lost on the way. hard to say without having the full picture.

**Comment by gruebel** [comment]
feel free to reach out again with more information
