### ISSUE TITLE
CKV_AWS_27 reporting AWS-KMS Encrypted SQS Queues as Unencrypted

### ISSUE THREAD

**Issue by jamesthompson26-nhs** [bridgecrewio/checkov#4631]
**Describe the issue**
Despite our queues being AWS-KMS encrypted, checkov reports them as unencrypted (CKV_AWS_27). 

**Examples**
We're building SQS resources via a larger tf module and are following the prescribed steps as in https://docs.bridgecrew.io/docs/general_16-encrypt-sqs-queue. Checkov output below. Can also confirm that our SQS queues, as built by this module, in the console, report happily as being AWS-KMS encrypted with the CMK we provided.

```
Resource: module.blah.module.sqs_queue_blah.aws_sqs_queue.sqs_queue
File: ../modules/sqs/sqs_queue.tf: 1-14
Guideline: https://docs.bridgecrew.io/docs/general_16-encrypt-sqs-queue

		1  | resource "aws_sqs_queue" "sqs_queue" {
		2  |   name = "$blah-queue"
		3  | 
		4  |   message_retention_seconds   = var.message_retention_seconds
		5  |   visibility_timeout_seconds  = var.visibility_timeout_seconds
		6  |   fifo_queue                  = var.fifo_queue
		7  |   content_based_deduplication = var.content_based_deduplication
		8  |   max_message_size            = var.max_message_size
		9  | 
		10 |   kms_master_key_id                 = var.sqs_kms_key_arn
		11 |   kms_data_key_reuse_period_seconds = var.kms_data_key_reuse_period_seconds
		12 | 
		13 |   tags = local.default_tags
		14 | }
```

**Version (please complete the following information):**
 - Checkov Version 2.3.71 (checked against latest available version at the time of writing)

**Additional context**
N/A

**Comment by gruebel** [comment]
feel free to reach out with more info here, closing it for now 🙂
