### ISSUE TITLE
CKV2_AZURE_31,CKV2_AZURE_32,CKV2_AZURE_33 do not pass if private endpoint or association is called from another module 

### ISSUE THREAD

**Issue by IgorOrmus** [bridgecrewio/checkov#4638]
**Describe the issue**
CKV2_AZURE_31,CKV2_AZURE_32,CKV2_AZURE_33 
hiese checks fail if private endpoint or NSG association is called from another moudle .

**Examples**
```hcl
resource "azurerm_storage_account" "storage_account" {
  name                            = lower(var.name)
  resource_group_name             = var.resource_group_name
  location                        = var.location
  account_kind                    = var.account_kind
  account_tier                    = var.account_tier
  account_replication_type        = var.account_replication_type
  access_tier                     = var.access_tier
  enable_https_traffic_only       = var.enable_https_traffic_only
  is_hns_enabled                  = var.hns_enabled
  min_tls_version                 = var.min_tls_version
  allow_nested_items_to_be_public = var.allow_nested_items_to_be_public
  public_network_access_enabled   = var.public_network_access_enabled
  dynamic "network_rules" {
    for_each = var.network_rules != null ? [var.network_rules] : []
    content {
      default_action = network_rules.value.default_action
    }
  }
  queue_properties {
    dynamic "logging" {
      for_each = var.queue_properties_logging != null ? [var.queue_properties_logging] : []
      content {
        delete                = logging.value.delete
        read                  = logging.value.read
        write                 = logging.value.write
        version               = logging.value.version
        retention_policy_days = logging.value.retention_policy_days
      }
    }
  }
  tags                          = var.tags
}
module "storage_account_private_endpoints" {
  depends_on = [
    azurerm_storage_account.storage_account
  ] 
  source                               = "../azurerm_private_endpoint"
  for_each                             = { for private_endpoint in var.private_endpoints : private_endpoint.name => private_endpoint } 

  name                                 = each.key
  private_service_connection_name      = each.value.private_service_connection_name
  subnet_name                          = each.value.subnet_name
  subnet_vnet_name                     = each.value.subnet_vnet_name
  subnet_resource_group_name           = each.value.subnet_resource_group_name
  is_manual_connection                 = each.value.is_manual_connection
  location                             = var.location
  private_connection_resource_id       = azurerm_storage_account.storage_account.id
  resource_group_name                  = each.value.resource_group_name
  subresource_names                    = each.value.subresource_names
  private_dns_zone_name                = each.value.private_dns_zone_name
  private_dns_zone_resource_group_name = each.value.private_dns_zone_resource_group_name
  tags                                 = var.tags
}
```

In the above example that is same for key vault private endpoint checkov fails the test even though a private endpoint is provissioned with the resource 

**Version (please complete the following information):**
 - Checkov Version latest 

**Additional context**

https://github.com/bridgecrewio/checkov/blob/main/tests/terraform/graph/checks/resources/AzureStorageAccConfigWithPrivateEndpoint/main.tf

@gruebel @praveen-panw would you be able to help?

**Comment by gruebel** [comment]
hey @IgorOrmus thanks for reaching out.
We currently don't support `for_each` on `module` level, therefore I'm not surprised it fails. We are working on it, but there is a chance we won't be able to support your setup at the end.

**Comment by jed-exotic** [comment]
I am experiencing similar failed checks for CKV2_AZURE_31 and CKV2_AZURE_33. Very similar situation - 

CKV2_AZURE_33 - I create Private Endpoints as their own resource, with a `private service connection` for the corresponding storage account with the checkov failure. 

CKV2_AZURE_31 - My VNET Subnets have NSGs through a module.

I've attempted to provide the env vars `CHECKOV_NEW_TF_PARSER` and `CHECKOV_ENABLE_MODULES_FOREACH_HANDLING` and still yield the failures.

**Comment by corstuur** [comment]
I also experience this issue for CKV2_AZURE_31. I have a module that creates the subnet, NSG and the NSG association but checkov still thinks it is not associated. In my case i am also using for_each on the resource in the module which might make the issue more complex.

**Comment by jquinn99002** [comment]
This continues to be an issue. Is there plans to resolve this @gruebel
