### ISSUE TITLE
CKV_GCP_69: Proposed fix is incorrect

### ISSUE THREAD

**Issue by userbradley** [bridgecrewio/checkov#4640]
**Describe the issue**
Check ID: `CKV_GCP_69`
Check Page: [ensure-the-gke-metadata-server-is-enabled](https://docs.bridgecrew.io/docs/ensure-the-gke-metadata-server-is-enabled)

This check it's self is valid.

The issue is the proposed fix uses fields that no longer exist

Proposed fix is as below

```terraform
resource "google_container_cluster" "example" {
  name               = var.name
  location           = var.location
  initial_node_count = 1
  project            = data.google_project.project.name

+ node_config {
+   workload_metadata_config {
+     node_metadata = "GKE_METADATA_SERVER"
+   }
+ }
}
```

Where as the docs:
![image](https://user-images.githubusercontent.com/41597815/224380140-3f36a9eb-e97c-4aec-8ee4-61a7d0e5f0c3.png)

So it should really be:

```terraform
resource "google_container_cluster" "example" {
  name               = var.name
  location           = var.location
  initial_node_count = 1
  project            = data.google_project.project.name

+  node_config {
+      workload_metadata_config {
+             mode = "GKE_METADATA"
+   }
}
```

[See the Documentation here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_workload_metadata_config:~:text=metadata%20to%20pods.-,GKE_METADATA,-%3A%20Run%20the%20GKE)

**Comment by gruebel** [comment]
hey @userbradley thanks for reaching out.

yeah, that's true. The check itself got updated, but not the docs 🙈 You can actually create an account for free there and propose a change. But no need for this specific change, I will adjust it.
