### ISSUE TITLE
Very unintuitive behavior for `--output-file-path` flag - need to add trailing comma to be parsed properly for single item

### ISSUE THREAD

**Issue by laurit17** [bridgecrewio/checkov#4644]
**Describe the issue**

Hi, for my use case I was attempting to run `checkov -f ${target} -o sarif --output-file-path ${tmpfile}`

This printed sarif to `results.sarif` and also human readable results to the console (I didn't want this) until I read the source code and learned that the proper behavior is only achieved by adding a trailing comma - ie., making the end of the command `--output-file-path ${tmpfile},`

https://github.com/bridgecrewio/checkov/blob/634c38b13141d92443757d7d4ea792738c031fbe/checkov/common/runners/runner_registry.py#L298

This is probably not intended behavior. If it is, please document it. Thank you!

**Comment by gruebel** [comment]
hey @laurit17 thanks for reaching out.
it is an intended behaviour and also described in the help text of `checkov` CLI
```shell
  --output-file-path OUTPUT_FILE_PATH
                        Name of the output folder to save the chosen output formats. Advanced usage: By using -o cli -o junitxml --output-file-path console,results.xml the CLI output will be
                        printed to the console and the JunitXML output to the file results.xml.
```
we had to do it this way, because of backwards compatability.
