### ISSUE TITLE
CKV_AWS_133 not returning properly in recent version

### ISSUE THREAD

**Issue by nomeelnoj** [bridgecrewio/checkov#4669]
**Describe the issue**
We recently upgraded from checkov 2.2.148 to 2.3.79.  With this upgrade, one of our checks that was previously passing (and should have) is now failing.  I would expect that even with changes to graph logic or other flow control, the validation on the checks is correct.

**Examples**
Our RDS module uses conditional logic for `backup_retention_period`:
```hcl
resource "aws_db_instance" "default" {
  # ... removed for brevity
  backup_retention_period = var.replicate_source_db == null ? var.backup_retention_period : null
}
```
Using version 2.2.148, this check passes when called from the module.  However, when we use 2.3.79, it fails.  We were able to get it to pass with 2.3.79 by removing the conditional logic from the module:

```hcl
resource "aws_db_instance" "default" {
  backup_retention_period = var.backup_retention_period
}
```
However that is not ideal as it requires a change to every single call of the module.

For now, we have had to revert back to 2.2.148.

We have similar conditional / complex logic in many of our modules, and I expect that this is just the first issue we have seen.

**Version (please complete the following information):**
 - Checkov Version `2.2.148` & `2.3.79`

**Comment by nomeelnoj** [comment]
Based on some more investigation, it seems that this issue started occurring in version 2.2.289, and I have a suspicion that it is related to this change: #4296

**Comment by gruebel** [comment]
hey @nomeelnoj thanks for reaching out.

Sadly with this minimal information it is not possible to investigate the issue. There can be multiple issues, which changes the evaluation, like are there default values for the used variables or not?

**Comment by nomeelnoj** [comment]
Thanks for the reply. There are default values for both. The default for backup_retention is `7`, and the default for replication_source is `null`. 

It seems from my testing that regardless of what the variables are set to, the issue goes away when the conditional is removed--either not passing anything through from state to module and using the implicit variable defaults, or setting values in the module explicitly.  No matter what I do, the only way to get the check to pass on the newer versions of checkov is to remove the conditional entirely. 

Thanks in advance for any help you can provide! Let me know if you need more code snippets or examples/logs.

**Comment by cpeel** [comment]
I think it's a bit simpler than the testcase above and Checkov is failing to load a `null` as a default value:

Consider:
```hcl
variable "string_string" {
  description = "String var with string default"
  type        = string
  default     = "string"
}

variable "string_null" {
  description = "String var with null default"
  type        = string
  default     = null
}

resource "aws_db_instance" "default" {
  string_string = var.string_string
  string_null = var.string_null
}
```

And a hacky pytest shows that the `string_string` value is being loaded correctly as the default, but `null` isn't:
```
    def test_var_defaults_with_null(self):
        graph_manager = TerraformGraphManager('m', ['m'])
        local_graph, _ = graph_manager.build_graph_from_source_directory(
            os.path.join(TEST_DIRNAME, "test_resources", "var_defaults"), render_variables=True)
        resources_vertex = list(filter(lambda v: v.block_type == BlockType.RESOURCE, local_graph.vertices))
        assert resources_vertex[0].attributes.get('string_string')[0] == "string"
>       assert resources_vertex[0].attributes.get('string_null')[0] == None
E       AssertionError: assert 'var.string_null' == None

tests/terraform/graph/variable_rendering/test_renderer.py:429: AssertionError
```

**Comment by gruebel** [comment]
yeah, it is probably dropped somewhere along the way. `null` values are always tricky to handle.

**Comment by rotemavni** [comment]
> I think it's a bit simpler than the testcase above and Checkov is failing to load a `null` as a default value:
> 
> Consider:
> 
> ```terraform
> variable "string_string" {
>   description = "String var with string default"
>   type        = string
>   default     = "string"
> }
> 
> variable "string_null" {
>   description = "String var with null default"
>   type        = string
>   default     = null
> }
> 
> resource "aws_db_instance" "default" {
>   string_string = var.string_string
>   string_null = var.string_null
> }
> ```
> 
> And a hacky pytest shows that the `string_string` value is being loaded correctly as the default, but `null` isn't:
> 
> ```
>     def test_var_defaults_with_null(self):
>         graph_manager = TerraformGraphManager('m', ['m'])
>         local_graph, _ = graph_manager.build_graph_from_source_directory(
>             os.path.join(TEST_DIRNAME, "test_resources", "var_defaults"), render_variables=True)
>         resources_vertex = list(filter(lambda v: v.block_type == BlockType.RESOURCE, local_graph.vertices))
>         assert resources_vertex[0].attributes.get('string_string')[0] == "string"
> >       assert resources_vertex[0].attributes.get('string_null')[0] == None
> E       AssertionError: assert 'var.string_null' == None
> 
> tests/terraform/graph/variable_rendering/test_renderer.py:429: AssertionError
> ```

I followed this comment and created a test case in checkov version `2.3.158` and confirmed the issue has been resolved. 
Thank you all for providing guidelines on how to reproduce the issue.
