### ISSUE TITLE
How to customize the Checkov base rule (default rules) definitions

### ISSUE THREAD

**Issue by srinivaschary** [bridgecrewio/checkov#4679]
**Describe the issue**
Is there a provision to customise the messages that default Checkov rules prints on the console output for the violations. I have a requirement to build a life cycle management for these policies to move from Incubate to Blocked mode on a time interval, On each of the stage, I want to mention the violation messages with custom type that says WARN, BLOCK, INFO kind of strings with additional text.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
 - latest

**Additional context**

**Comment by gruebel** [comment]
you could use one of the output formats and then parse and adjust to your liking.

**Comment by nimrodkor** [comment]
Using checkov with the BC or PC platforms allows you to do this easily

**Comment by srinivaschary** [comment]
thank you.
