### ISSUE TITLE
Custom Policy for aws_iam_policy_document to scan tfplan

### ISSUE THREAD

**Issue by cloudtriquetra** [bridgecrewio/checkov#4685]
We need to develop custom policy to scan data block of aws_iam_policy_document which is used for setting up S3 Bucket Policy.

While trying to scan terraform plan json, data policies does not work.

As per my understanding, it is handled by cloudsplaining but how I write a Custom Policy with that?

Plan is generated from terraform code block like following:
```hcl
resource "aws_s3_bucket_policy" "s3_source_bucket_policy" {
  provider = aws.primary
  count    = local.enabled ? 1 : 0
  bucket   = aws_s3_bucket.source[count.index].id
  policy   = data.aws_iam_policy_document.s3_source_bucket_policy_app[count.index].json
}

data "aws_iam_policy_document" "s3_source_bucket_policy_app" {
  provider = aws.primary
  count    = local.enabled ? 1 : 0

  //Deny Unsecure Comm
  statement {
    sid    = "DenyUnSecureCommunications"
    effect = "Deny"

    resources = [
      "arn:aws:s3:::${aws_s3_bucket.source[count.index].id}/*"
    ]

    actions = [
      "s3:*"
    ]

    principals {
      identifiers = ["*"]
      type        = "AWS"
    }

    condition {
      test     = "Bool"
      values   = ["false"]
      variable = "aws:SecureTransport"
    }
  }
}
```

**Comment by gruebel** [comment]
hey @arkaprava-jana thanks for reaching out.

I don't know of any issue to write custom policies for `aws_iam_policy_document` data blocks. We use cloudsplaining to get more information about the policy itself, like what does it mean, when you use `s3:*` as an action. If you write your customer policy in Python then you can also leverage. If you write your policy in a YAML file, then you can't and have to access attributes on your own, like here
https://github.com/bridgecrewio/checkov/blob/cd8bc63b913b22a0994cc6708a24d99e87b9fb0b/checkov/terraform/checks/graph_checks/aws/IAMPolicyNotAllowFullIAMAccess.yaml#L46-L51

**Comment by arkaprava-jana** [comment]
I have attached terraform plan file, unable to figure out why Data Checks like CKV_AWS_1, CKV_AWS_49 are not being executed for it.
[plan2.json.zip](https://github.com/bridgecrewio/checkov/files/10999045/plan2.json.zip)

Can you please check?

**Comment by gruebel** [comment]
@arkaprava-jana thanks for the file. It looks like we just drop the `data` blocks, when scanning a plan file. I don't think it is intentionally and just was forgotten.

**Comment by arkaprava-jana** [comment]
Thanks for acknowledging. Hope a PR will fix this. Also, YAML connections does  not work for the plan I shared.
