### ISSUE TITLE
Integrate with tf-parliament

### ISSUE THREAD

**Issue by nimrodkor** [bridgecrewio/checkov#47]
**Is your feature request related to a problem? Please describe.**
Terraform lets us create and manage IAM policies. To keep them orderly and updated is a daunting task, which requires a lot of knowledge around IAM. https://github.com/rdkls/tf-parliament can help us manage that - we should think about integrating with it.

**Describe the solution you'd like**
Have a "check" which runs this python script on the policies in the dir.

**Additional context**
https://github.com/rdkls/tf-parliament

**Comment by schosterbarak** [comment]
it might be challenging since tf-parliament does not have a pypi package. 
I think integrating parliament directly would be easier.

**Comment by schosterbarak** [comment]
pending rdkls feedback.
Code is pending ( no tests yet): https://github.com/bridgecrewio/checkov/pull/49
