### ISSUE TITLE
Run pre-commit on changed files only

### ISSUE THREAD

**Issue by Amir-Ahmad** [bridgecrewio/checkov#4702]
**Describe the issue**

The checkov pre-commit hook currently runs against all files on a repository. For bigger monorepos, it can take a while to run (several minutes), and slows down CI builds.

Pre-commit supports sending a list of files (pass_filenames: true), perhaps the pre-commit can be updated to supported this?

There is some discussion on this issue https://github.com/bridgecrewio/checkov/issues/661, but I thought it's worth creating a ticket just to track this.

**Comment by JamesWoolfenden** [comment]
If you run checkov on the monorepo where is the entry point for variables to be? The checks need to know the values and may evaluate differently for different target environments. For pass_filenames to work you'd have to an individual run on each file - checkov -f ? Plus if a file contains variables, resource dependency or locals it might change the values of other resources and almost certainly will. Cherry picking in a graph isn't straight forward.
