### ISSUE TITLE
CKV_AZURE_117: "Ensure that AKS uses disk encryption set“ is positive

### ISSUE THREAD

**Issue by lsauthie** [bridgecrewio/checkov#4713]
**Describe the issue**
Hello team, hopefully you are doing well. I am struggling to understand a finding coming from an AKS policy. In my opinion, the finding is wrong.

While running Checkov on the following terraform snippet

--- start snippet ---
resource "azurerm_kubernetes_cluster" "default" {
  name                = "ludovic-aks"
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
  dns_prefix          = "ludovic-k8s"

  default_node_pool {
    name            = "default"
    node_count      = 2
    vm_size         = "Standard_B2s"
    os_disk_size_gb = 30
    **enable_host_encryption = true**
  }
  
	identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true
  }

  tags = {
    environment = "Demo"
  }
}
--- end snippet ---

it fails. In my understanding, because of the part in bold in the snippet (and as documented by Microsoft https://learn.microsoft.com/en-us/azure/aks/enable-host-encryption, it should pass.

**Comment by JamesWoolfenden** [comment]
I think this is because a disk encryption set can use a CMK generated by you and basic encryption is via MS managed keys. https://learn.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys. The docs could be clearer?
