### ISSUE TITLE
Support for Downloading Modules from JFrog Artifactory are missing

### ISSUE THREAD

**Issue by hari2anand** [bridgecrewio/checkov#4731]
**Describe the issue**
Our team uses terraform modules sourced from JFrog Artifactory Terraform module registry.
Example:
```
module "<module>" {
  source = "<artifactory-host>/<project>__<namespace>/<module-name>/<provider>"
  version = <version>
}
```
please add integration [Artifactory Terraform Module Registry](https://www.jfrog.com/confluence/display/JFROG/Terraform+Registry) for scanning and download external private terraform modules, like [this](https://www.checkov.io/7.Scan%20Examples/Terraform.html#scanning-private-terraform-modules).

**Comment by gruebel** [comment]
this was fixed with #4964
