### ISSUE TITLE
Trying to install checkov in AWS Codebuild

### ISSUE THREAD

**Issue by YuriGal** [bridgecrewio/checkov#4752]
We're trying to run 
```
pip3 install --upgrade --quiet checkov
```
in an AWS CodeBuild (aws/codebuild/standard:6.0) and getting this error message:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aws-sam-cli 1.72.0 requires regex==2021.9.30, but you have regex 2023.3.23 which is incompatible.
aws-sam-cli 1.72.0 requires requests==2.25.1, but you have requests 2.28.2 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
What could be the reason and how can we fix it?

**Comment by YuriGal** [comment]
I tried to install checkov in virtual environment, but still was getting the same error. I ended up having to uninstall aws-sam-cli before installing checkov, which is ok for now since we're not using it, but I'd rather prefer to find a way for them to co-exist.

**Comment by gruebel** [comment]
Not much we can do here, the SAM CLI is quite strict on their dependencies and as you can see `regex==2021.9.30` is ~1.5 years old. I created a PR to unpin it, but I recommend the solution by @YuriGal . By the way the installed SAM CLI version is also old, the current latest one is `1.78.0`.
https://github.com/aws/aws-sam-cli/pull/4924

**Comment by gruebel** [comment]
my PR in SAM CLI was merged, so either you uninstall the SAMl CLI or need to update it, when they release a new version with my fix.
