### ISSUE TITLE
Add new check: "A resource has a public IP address."

### ISSUE THREAD

**Issue by KevinHock** [bridgecrewio/checkov#476]
I saw [this check in tfsec](https://github.com/liamg/tfsec/blob/a450c423747c1ec2ef3cb52c1a270b05f2f5a62f/internal/app/tfsec/checks/aws_public_ip.go#L14-L24), which was one of the very few I didn't see an analogous rule for in checkov. Similarly, is there a check for when something new is placed behind a publicly reachable ELB?

(Apologies if I missed something, I wrote down in my notes that there wasn't a matching check a week or so ago, and am only transcribing it now.)

tags: `good-first-issue`

**Comment by KevinHock** [comment]
Slightly related: https://github.com/SummitRoute/aws_exposable_resources

**Comment by KevinHock** [comment]
Also related these 3 open issues https://github.com/bridgecrewio/checkov/issues?q=is%3Aissue+publicly+accessible+is%3Aopen, (DMS, MQ brokers, and Redshift clusters).

**Comment by KevinHock** [comment]
I want to add a check for EC2 instances with public IPs, is that okay @schosterbarak?

**Comment by schosterbarak** [comment]
Sounds good @KevinHock 
CC: @metahertz , @nimrodkor
