### ISSUE TITLE
CKV_K8S_8 & CKV_K8S_9 false positives

### ISSUE THREAD

**Issue by JohnARauchwarter** [bridgecrewio/checkov#4807]
**Describe the issue**
Our team is using a statefulset where the pod runs 2 init containers and then the app container.  Running the helm framework, these both produce errors against our statefulset chart.
We have liveness and readiness probes configured on the app container, and the init containers are not able to have such probess.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
 - Checkov Version 2.3.140
 - Framework Helm

**Additional context**

**Comment by JamesWoolfenden** [comment]
"Please share an example code sample (in the IaC of your choice) + the expected outcomes."

**Comment by JohnARauchwarter** [comment]
I will update this with the requested items this afternoon.
