### ISSUE TITLE
Pipfile makes no reference to "six" package, but is present in Pipfile.lock

### ISSUE THREAD

**Issue by mlschindler** [bridgecrewio/checkov#483]
**Describe the bug**
There is currently an issue with version mismatches between the pinned version of six in [setup.py](https://github.com/bridgecrewio/checkov/blob/master/setup.py#L80):

**To Reproduce**
I discovered this bug when attempting to build checkov in an Alpine container:
```
FROM alpine:latest
RUN apk add --no-cache python3 py-pip git bash
RUN python3 --version
RUN mkdir /app
RUN chmod +x /app/tf_checkov.sh
RUN python3 -m venv checkov_env
RUN . checkov_env/bin/activate && pip install --upgrade pip && pip install --upgrade setuptools
RUN pip install checkov
```
Which resulted in the following error:
```ERROR: checkov 1.0.475 has requirement six==1.13.0, but you'll have six 1.15.0 which is incompatible.```
**Expected behavior**
Normally on an install on a virtual environment locally, this is not an issue and checkov will install with `six=1.13.0`

**Desktop (please complete the following information):**
 - OS: Alpine
 - Checkov Version `latest`

**Additional context**
Findings include  pinned version of `six` within [setup.py](https://github.com/bridgecrewio/checkov/blob/master/setup.py#L80), and the absence of any version of `six` from [Pipfile](https://github.com/bridgecrewio/checkov/blob/master/Pipfile). In addition, `Pipfile.lock` makes [references to the pinned version](https://github.com/bridgecrewio/checkov/blob/master/Pipfile.lock#L135-L142) of `six=1.15.0`, but not the actually pinned version of `1.13.0` required by checkov as found in the setup.py file.

**Comment by schosterbarak** [comment]
agreed. thank you for reporting this. would you like to contribute this fix?

**Comment by mlschindler** [comment]
I will certainly try!

**Comment by mlschindler** [comment]
Would you want this version of `six` pinned to `1.15.0` since there's a conflict there?

**Comment by schosterbarak** [comment]
Fixed. Thanks for the contribution
