### ISSUE TITLE
Checkov scans for Bicep files

### ISSUE THREAD

**Issue by babicahmed** [bridgecrewio/checkov#4834]
When scanning appService.bicep in Azure Pipelines using docker image bridgecrew/checkov, runs are extremely unstable. Without any changes to files, when doing the scan, tests are sometimes failing, sometimes passing. No cache is being kept as it is run on Microsoft-hosted agents and every time docker image is pulled and Checkov is run.
Affected checks:
CKV_AZURE_14
CKV_AZURE_15
CKV_AZURE_16 
CKV_AZURE_17 

In the same repository, there are other bicep files and no discrepancies in other tests. 

Example of YAML
        steps:
          - bash: |
              docker pull bridgecrew/checkov
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: "Pull bridgecrew/checkov image"

          - bash: |
              docker run --volume $(pwd):/bicep bridgecrew/checkov --directory /bicep --output junitxml --soft-fail > $(pwd)/CheckovReport.xml
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: "Run checkov"

          - task: PublishTestResults@2
            inputs:
              testRunTitle: "Checkov Results"
              failTaskOnFailedTests: true
              testResultsFormat: "JUnit"
              testResultsFiles: "CheckovReport.xml"
              searchFolder: "$(System.DefaultWorkingDirectory)"
            displayName: "Publish Test results"

- Checkov Version - docker image using latest
- Bicep file - resource appService 'Microsoft.Web/sites@2022-03-01', multiple versions since 2018 tested, all getting the unstable results

Expected result: Consistency in test outcomes when no changes are applied to infrastructure
Actual result: Tests are sometimes failing, sometimes passing, without any change to the infrastructure

**Comment by gruebel** [comment]
hey @babicahmed thanks for reaching out.

Could you also post one of the affected resources as it is written inside the Bicep file.

**Comment by babicahmed** [comment]
`resource appService 'Microsoft.Web/sites@2022-03-01' = {
  name: name
  location: location
  kind: kind
  identity: identity
  properties: {
    enabled: true
    hostNameSslStates: [
      {
        name: '${name}.azurewebsites.net'
        sslState: 'Disabled'
        hostType: 'Standard'
      }
      {
        name: '${name}.scm.azurewebsites.net'
        sslState: 'Disabled'
        hostType: 'Repository'
      }
    ]
    serverFarmId: serverFarmId
    reserved: reserved
    isXenon: isXenon
    hyperV: hyperV
    scmSiteAlsoStopped: scmSiteAlsoStopped
    clientAffinityEnabled: clientAffinityEnabled
    clientCertEnabled: clientCertEnabled
    hostNamesDisabled: hostNamesDisabled
    // containerSize: containerSize
    dailyMemoryTimeQuota: dailyMemoryTimeQuota
    httpsOnly: httpsOnly
    redundancyMode: redundancyMode
   siteConfig: siteConfig
  }
}`

**Comment by babicahmed** [comment]
I found out that 4 checks stated above are triggered when 'httpsOnly' value is passed(either true or false). Every run is different, showcasing 2, 3 or 4 failures.

**Comment by nikolamalesevic** [comment]
I have had the exact same issue in the past, and gave up on Checkov because of it.

The results were almost random across commits with no changes to Biceps, and even across different branches on the same commit. But very stable on the same branch & commit.

**Comment by gruebel** [comment]
@babicahmed as I understand you are probably using a parameter or variable to control `httpsOnly` value. We do something, which we call variable rendering and this has different types of thresholds. The easiest way to get the most consistent result, but then you loose this functionality and you won't be able to use YAML based policies anymore, is to set env var `CHECKOV_CREATE_GRAPH=False`.
You could also try to set `RENDER_EDGES_DUPLICATE_PERCENT` to a number higher than `90`, which is the default and `100` is the max, but be carful with it.

**Comment by babicahmed** [comment]
@gruebel your suggestion helped a bit to have a more stable result by using CHECKOV_CREATE_GRAPH=False. However, I believe there is an issue connected to it :
1. When passing httpsOnly as a variable, my test '[NONE][CKV_AZURE_14] Ensure web app redirects all HTTP traffic to HTTPS in Azure App Service' **always shows a failure**. When providing value directly without a parameter/variable, it works fine with true and false. This is a killer for a process and way of working with bicep files as we can't afford to provide values directly to the resource but actually through variables.
2. In Addition to 'you won't be able to use YAML based policies anymore' - Does this mean that if we want to develop our own policies and checks and include it in scans, it will not work?
