### ISSUE TITLE
KeyError: 'suppress_comment' when running with -o junitxml flag

### ISSUE THREAD

**Issue by fabiodouek** [bridgecrewio/checkov#4835]
**Describe the issue**
I get the error KeyError: 'suppress_comment', when:
- Evaluating the Python rule, if I return CheckResult.SKIPPED in the scan_resource_conf method
- The error happens only when executing checkov with the flag -o junitxml

**Version (please complete the following information):**
 - Checkov Version 2.3.152

**Additional context**
Is there a way to either add the suppress_comment in the context or for the junit report not to throw an error?

**Comment by gruebel** [comment]
hey @fabiodouek thanks for reaching out.
yeah, this should be possible 🙂 but just a word of advise, the `CheckResult.SKIPPED` was not meant to be used in Python custom checks, for such a use case we `CheckResult.UNKNOWN`.

**Comment by fabiodouek** [comment]
Hi @gruebel , thanks for your feedback.
I was looking for a way to classify evaluation rules to NOT_APPLICABLE.

The use case here is the evaluation of Resource Policies. A rule which evaluates Deny Statements, if there is a Deny Statement and if fails/succeeds, then it will return appropriately PASSED/FAILED. 

But if there is no Deny statement in the policy, I would like to mark the rule status as NOT_APPLICABLE. I was keeping the UNKNOWN state for system errors.

I hope the above explains the use case. Keen to get your thoughts and also if there is a plan to support NOT_APPLICABLE status.
