### ISSUE TITLE
CheckOV can't check bicep files with modules published in Azure container registry

### ISSUE THREAD

**Issue by AlexLudwigITDienstleistungen** [bridgecrewio/checkov#4845]
**Describe the issue**
In a larger Bicep environment, we publish entire solutions to the Azure Container Registry. These solutions are called by users as modules in their Bicep deployments. Therefore, it is mandatory for us that CheckOV supports scanning of such environments.

In our view, these two solutions would sufficiently address the problem, with the first solution being our favorite:

1. CheckOV downloads the modules from the Azure container registry to enable scanning of the code.
2. CheckOV checks if the Azure container registry used is whitelisted and then scans only the available code. If the registry used is not whitelisted, CheckOV returns a hardfail.

The second option would be a workaround for us, as we only want users to use our registry. The modules that are published in this registry have been scanned by checkov before publishing.

In the current version of checkov (2.3.152) the scan of the bicep file fails with a parsing error.

**Example Value**
``` bicep
module modSampleSolution 'br:sampleregistry.azurecr.io/bicep/modules/company.department/sampleSolution:1.0.0' = {
  name: 'sampleSolution-deploy'
  params: {
    parSampleParameter: 'Sample'
  }
}
```

**Comment by gruebel** [comment]
hey @AlexLudwigITDienstleistungen thanks for reaching out.

The parsing error shouldn't happen, but I think I know how to fix it. I hope it is ok, if I use your example as my test case :smile:

Support for modules is currently not supported as you found out and I'm also not sure, when we will tackle it, because it is not on the short-term roadmap.

**Comment by AlexLudwigITDienstleistungen** [comment]
Hi @gruebel,
you are welcome to use this. It's just a simple module that does nothing more than demonstrate the problem.

Is there a time frame for this on your roadmap? Or is the roadmap publicly available somewhere?

**Comment by gruebel** [comment]
we have a small project board where we track work on planned changes without any ETA, but for this specific feature I need to reach out internally, if we plan to tackle it or not.

https://github.com/orgs/bridgecrewio/projects/5/views/4

**Comment by AlexLudwigITDienstleistungen** [comment]
Hi @gruebel,
have you made any progress with this error? You mentioned that you know how to fix it.

**Comment by gruebel** [comment]
hey @AlexLudwigITDienstleistungen 

yeah, I fixed the parsing issue, but I'm waiting to release a new version of parser, because I want to incorporate some other parsing issues related to new Bicep syntax extensions.
