### ISSUE TITLE
How to reclassify existing checkov rules say from "High" to "Medium"

### ISSUE THREAD

**Issue by munntjlx** [bridgecrewio/checkov#4848]
**Describe the issue**
I want to be able to re-classify a "high" or a critical according to my own scale. None of the docs indicate where the classification occurs.

**Examples**
Say CKV001 I want to move it from a 'critical' to a 'low' since in my cases we often have to re-classify, or there are checks that aren't granular enough. I still want to know about them, but NOT have them stop the pipeline.

**Version (please complete the following information):**
 - Checkov Version Current. All versions seem affected by this.

**Additional context**
A doc on how to reclassify (which I will contribute) if someone explains how to do this.

**Comment by gruebel** [comment]
Hey @munntjlx thanks for reaching out.

As far as I know this is only possible via the Prisma Console, by editing an existing policy.
