### ISSUE TITLE
for_each not working

### ISSUE THREAD

**Issue by netjordan** [bridgecrewio/checkov#4850]
**Describe the issue**
When a resource is created with `for_each`, and `each.value` or `each.key` is used, the correct value is not passed though to checks.

In the example below I would expect the variables to have been resolved to their values before being passed to checks, but they are not. This means that policies cannot work that are checking values.

I believe the following pull requests would have fixed this: #4787 #4588 and #4427

**Examples**
main.tf
```
module "buckets" {
  source = "./module"

  for_each = {
    "foo" = "eu-west-1"
  }

  name = each.key
  region = each.value
}
```

module/main.tf:
```
resource "aws_s3_bucket" "bucket" {
  bucket = "${var.name}-bucket"

  tags = {
    "Region" = var.region
  }
}
```

The resulting object passed to checks looks like this:
```
{
  "__end_line__": 7,
  "__start_line__": 1,
  "bucket": [
    "${each.key}-bucket"
  ],
  "tags": [
    {
      "Region": "each.value"
    }
  ],
  "__address__": "module.buckets.aws_s3_bucket.bucket"
}
```

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1 (also seen on windows)
 - Checkov Version: 2.3.152

**Comment by bo156** [comment]
Hey @netjordan, I believe the problem is that the env variables for `foreach` are currently `False` by default, so setting them to `True` in your env will solve the problem.
The relevant env vars are:
1. `CHECKOV_NEW_TF_PARSER`
2. `CHECKOV_ENABLE_FOREACH_HANDLING`
3. `CHECKOV_ENABLE_MODULES_FOREACH_HANDLING`

Please let us know if that solved your issue

**Comment by netjordan** [comment]
Apologies for the delay in testing this, I've just tried this again but no luck, although it is different:

With the command `CHECKOV_NEW_TF_PARSER=True CHECKOV_ENABLE_FOREACH_HANDLING=True CHECKOV_ENABLE_MODULES_FOREACH_HANDLING=True checkov -d . --external-checks-dir custom_policy/ --check TEST_1 --framework terraform`

I see this output now:
```
{
  "__end_line__": 7,
  "__start_line__": 1,
  "bucket": [
    "${var.name}-bucket"
  ],
  "tags": [
    {
      "Region": "var.region"
    }
  ],
  "__address__": "module.buckets[\"foo\"].aws_s3_bucket.bucket"
}
```

**Comment by bo156** [comment]
@netjordan what do you expect to see? do you also provide the relevant `var` object? (if you do, you didn't attach its code here)

**Comment by jbrule** [comment]
Same. If I replace `location = each.value["bigquery_location"]` in project-team/main_resources.tf with `location = "us"` then location is properly set. Same goes for labels as can be seen.

Result
```
google_bigquery_dataset {'__end_line__': 112, '__start_line__': 23,'classification': '${module.project}["label_classification"]', 'data_owner': '${module.project}["label_data_owner"]'}], 'location': ['each.value["bigquery_location"]']...
```

locals.tf
```hcl
config = { 
     
  d = {
    teams = {
      team1 = {
        group_email       = "...@...edu"
        bigquery_location = "US"
        bucket_location   = "us"
        registry_location = "us-central1"
        registry_format   = "DOCKER"
      }
    }
  }

  env_config = local.config["d"]
  teams  = local.env_config["teams"]
}
```

main.tf
```hcl
module "project_team" {
  source  = "tferegistry.../project-team/google"
  version = "...

  project_module_output = module.project
  teams                 = local.teams
}
```

project-team/main_resources.tf
```hcl
module "bigquery_dataset" {
  source  = "tferegistry...bigquery-dataset/google"
  version = "3.0.0"

  for_each = var.teams

  project_id                 = local.project_id
  description                = "Team project dataset - ${each.key}"
  classification             = local.label_classification
  data_source                = "team_${each.key}"
  location                   = each.value["bigquery_location"]
  env                        = local.env
  delete_contents_on_destroy = true

  labels = {
    classification = local.label_classification
    data_owner     = local.label_data_owner
    billing_group  = "${local.label_billing_group_prefix}-${each.key}"
  }
}
````

bigquery-dataset/main.tf
```hcl
resource "google_bigquery_dataset" "bq_dataset" {
  count       = var.enabled ? 1 : 0
  dataset_id  = local.dataset_id
  description = var.description
  location    = var.location

  default_table_expiration_ms = var.expiration
  project                     = var.project_id
  labels                      = var.labels

  dynamic "access" {
    for_each = [for s in var.access_rules_user : {
      role          = s.role
      user_by_email = s.user_by_email
    }]

    content {
      role          = access.value.role
      user_by_email = access.value.user_by_email

    }
  }

  dynamic "access" {
    for_each = [for s in var.access_rules_group : {
      role           = s.role
      group_by_email = s.group_by_email
    }]

    content {
      role           = access.value.role
      group_by_email = access.value.group_by_email

    }
  }

  dynamic "access" {
    for_each = [for s in var.access_rules_domain : {
      role   = s.role
      domain = s.domain
    }]

    content {
      role   = access.value.role
      domain = access.value.domain

    }
  }

  dynamic "access" {
    for_each = [for s in var.access_rules_special_group : {
      role          = s.role
      special_group = s.special_group
    }]

    content {
      role          = access.value.role
      special_group = access.value.special_group

    }
  }

  dynamic "access" {
    for_each = var.access_rules_view

    content {

      dynamic "view" {

        for_each = [access.value]

        content {
          project_id = view.value.project_id
          dataset_id = view.value.dataset_id
          table_id   = view.value.table_id
        }
      }

    }

  }
  dynamic "default_encryption_configuration" {
    for_each = var.kms_key_name != null ? [var.kms_key_name] : []
    content {
      kms_key_name = var.kms_key_name
    }
  }

  delete_contents_on_destroy = var.delete_contents_on_destroy
}
```

**Comment by Wolfsrudel** [comment]
> Hey @netjordan, I believe the problem is that the env variables for `foreach` are currently `False` by default, so setting them to `True` in your env will solve the problem. The relevant env vars are:
> 
> 1. `CHECKOV_NEW_TF_PARSER`
> 2. `CHECKOV_ENABLE_FOREACH_HANDLING`
> 3. `CHECKOV_ENABLE_MODULES_FOREACH_HANDLING`
> 
> Please let us know if that solved your issue

Where exactly are the variables documented?

I get a boolean error when I try to set it to "True". The funny thing about this is that a SKIP_EXTERNAL_DIRECTORY or something similar is automatically complained about.

**Comment by JonZeolla** [comment]
I would like this to be reopened

**Comment by isunp** [comment]
I would also like this issue to be reopened.

**Comment by Greg05000** [comment]
same here with modules and for_each
