### ISSUE TITLE
Wrong filename if using --output-file-path option

### ISSUE THREAD

**Issue by PascalTurbo** [bridgecrewio/checkov#4881]
When setting the output path using `--output-file-path output_directory` checkov reports

```
Wrote output in SARIF format to the file 'results.sarif'
```

But inside the output_directory the filename is written as **results_sarif.sarif**.

Additionally it would be great to see a message like

```
Wrote output in SARIF format to the file 'output_directory/results.sarif'
```

**Comment by PascalTurbo** [comment]
Hey @gruebel thanks for the fast response.

Here is the complete command:

```
$ checkov --version
2.3.150

$ checkov -d melee-island -o sarif --output-file-path output
[...lot of output]
Wrote output in SARIF format to the file 'results.sarif'

$ ls output
results_sarif.sarif
```

So if it's intentional to add `results_` (what makes absolutely sense after thinking about it 😄) the only "bug" is, that it writes the wrong filename to the last line of the output. (And as a feature request, add the given path).

**Comment by gruebel** [comment]
ok, found the problem. The printed message is actually a bug and shouldn't be shown, if you use the `--output-file-path` flag. The SARIF output is kind of special and the only one, which is directly saved to file. So, you actually have two files saved to the filesystem right now 😄 I will fix it and the message will be gone.
