### ISSUE TITLE
CKV2_AZURE_33 very specific usecase

### ISSUE THREAD

**Issue by Annesars90** [bridgecrewio/checkov#4882]
The CKV2_AZURE_33 isn't passing for the below code, which makes sense when you look at the test: https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/azure/AzureStorageAccConfigWithPrivateEndpoint.yaml.

However, it doesn't make sense to me that the networkrules.defaultaction should be set to allow when using a private endpoint. Same goes for the iprules. 

**Code**
```hcl
resource "azurerm_storage_account" "backend" {
  name                     = local.storage_account_name
  resource_group_name      = var.function_app_resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  #checkov:skip=CKV_AZURE_206:Unimportant data
  access_tier                      = "Hot"
  enable_https_traffic_only        = true
  min_tls_version                  = "TLS1_2"
  allow_nested_items_to_be_public  = false
  shared_access_key_enabled        = false
  default_to_oauth_authentication  = true
  public_network_access_enabled    = false
  cross_tenant_replication_enabled = false

  network_rules {
    default_action = "Deny"
    #checkov:skip=CKV_AZURE_36:Allow trusted services is not needed
    bypass                     = ["None"]
    ip_rules                   = []
    virtual_network_subnet_ids = []
  }
}

resource "azurerm_storage_container" "backend" {
  name                  = "releases"
  storage_account_name  = azurerm_storage_account.backend.name
  container_access_type = "private"
}

resource "azurerm_private_endpoint" "backend" {
  name                          = azurerm_storage_account.backend.name
  resource_group_name           = azurerm_storage_account.backend.resource_group_name
  location                      = var.location
  subnet_id                     = var.function_app_inbound_subnet.subnet_resource_id
  custom_network_interface_name = azurerm_storage_account.backend.name
  private_service_connection {
    name                           = azurerm_storage_account.backend.name
    private_connection_resource_id = azurerm_storage_account.backend.id
    is_manual_connection           = false
    subresource_names              = ["blob"]
  }
}
```
**Suggestion**
Please remove the check for the default action and the ip rules from the test as they are not relevant and also not really logical in this case.

**Comment by NathanDunning** [comment]
I agree, I am running into the same issues and I believe the check for this policy is incorrect. Similar to key vault, if we are checking that a private endpoint has been configured for the resource, it should not need to worry about the `network_rules.default_action` or `network_rules.ip_rules`. We can take a look at the [Key Vault Private Endpoint](https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/azure/AzureKeyVaultConfigPrivateEndpoint.yaml) check as an example.

I am happy to raise a pull request to update this check to what I think is right for this policy.
