### ISSUE TITLE
CKV_AWS_325 check might not be accurate for PostgreSQL RDS instances

### ISSUE THREAD

**Issue by rajien2** [bridgecrewio/checkov#4887]
**Describe the issue**
The CKV_AWS_325 check expects the 'audit' log type to be enabled for RDS Cluster audit logging. However, this log type may not be applicable for PostgreSQL RDS instances, which use the 'postgresql' log type instead.

**Examples**
For a PostgreSQL RDS instance with the following Terraform configuration:

**main.tf**

```
resource "aws_rds_cluster" "main" {
  # ... other configurations ...
  enabled_cloudwatch_logs_exports = var.enabled_cloudwatch_logs_exports
  # ... other configurations ...
}
```

**variables.tf**

```
variable "enabled_cloudwatch_logs_exports" {
  default = [
    "postgresql"
  ]
}
```

The CKV_AWS_325 check fails, even though the 'postgresql' log type is enabled for the RDS instance.

**Expected outcome**
The CKV_AWS_325 check should either not be applicable or should pass for PostgreSQL RDS instances with the 'postgresql' log type enabled.

**Version**

**Checkov Version:** Lastest

**Additional context**
This issue was discovered while analyzing a Terraform configuration for an AWS PostgreSQL RDS instance. The CKV_AWS_325 check might need to be updated to accommodate different log types for different RDS engines.

https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/RDSClusterAuditLogging.py

**Comment by Rumbles** [comment]
I've noticed this as well, I tried enabling audit logs but the API returns:

```
InvalidParameterCombination: You cannot use the log types 'audit' with engine version aurora-postgresql 14.5. For supported log types, see the documentation.
```

**Comment by gruebel** [comment]
hey @rajien2 thanks for reaching out.

yeah, it makes sense to treat the engines differently and I will disable it for `postgresql`, because to enable actual audit logging is a bit more complicated.
