### ISSUE TITLE
Checkov terraform scan Takes 2x time to process since 2.3.121

### ISSUE THREAD

**Issue by thedevopsjedi** [bridgecrewio/checkov#4905]
**Describe the issue**
We use checkov both locally and via pipelines and have noticed the time taken to complete a terraform scan has increased from around 3 mins to 6 mins.  

I have today validated this by testing the time taken to run locally with every released version from 2.3.71 to 2.3.171.

I can now confirm that the performance dropped when going from 2.3.115 (3 mins 34 secs) to 2.3.121 (6 mins 15 secs).

All scans complete successfully with no unexpected errors and the time taken stays around the 6 min mark for every version newer than 2.3.121.

To try and pin point the issue further I have checked for a single check only which saved about 30 seconds.

**Examples**
No specific code to share as the scans complete without issue just slower than before.

**Version (please complete the following information):**
 - All versions since 2.2.121

**Additional context**
Nothing further to add but happy to test anything if needed.

**Comment by gruebel** [comment]
hey @thedevopsjedi thanks for reaching out.

Can you tell me a bit more about what exactly are you scanning? Is it just one framework, like Terraform` or multiple?

**Comment by ChanochShayner** [comment]
Hey @thedevopsjedi I can see that `Support for_each/count statements in TF Modules` is in the release here - https://github.com/bridgecrewio/checkov/releases/tag/2.3.121
But this for_each feature is under an env var, maybe you set this env var to true?

**Comment by thedevopsjedi** [comment]
Hi @ChanochShayner no env var changes have been made to the pipeline agents or locally.

**Comment by thedevopsjedi** [comment]
Excellent thanks @gruebel!

@ChanochShayner What is the env var for the for_each and count stuff I can't see if in the docs and wondered if I can set to false?

**Comment by gruebel** [comment]
@thedevopsjedi we released version `2.3.175` which should include the previously mentioned fix, hope this helps 🙂

**Comment by thedevopsjedi** [comment]
I've run 2.3.175 locally via the docker container 3 times and it still takes just over 6 mins.

**Comment by ChanochShayner** [comment]
@thedevopsjedi Could you please share the specific command and the debug logs with us to better understand what is going on?

**Comment by thedevopsjedi** [comment]
Hi @ChanochShayner the command I am running is:

docker run --rm --volume $(pwd):/checkovvol bridgecrew/checkov:2.3.171 --directory /checkovvol --framework terraform --config-file ./checkovvol/dj.yaml --compact --quiet

The contents of the yaml file is below, but my organisation would not be comfortable sharing the debug log publicly, is there an email address I can send it to or another way to get it you privately?

Yaml file contents:

check:
  - CKV_AZURE*
  - CKV2_AZURE*
skip-check:
  - CKV_ALI*
  - CKV_AWS*
  - CKV2_ADO*
  - CKV2_AWS*
  - CKV_BCW*
  - CKV_DIO*
  - CKV_GCP*
  - CKV2_GCP*
  - CKV_GIT*
  - CKV2_GIT*
  - CKV_GLB*
  - CKV_K8S*
  - CKV_LIN*
  - CKV_NCP*
  - CKV_OCI*
  - CKV2_OCI*
  - CKV_OPENSTACK*
  - CKV_PAN*
  - CKV_YC*

**Comment by thedevopsjedi** [comment]
Having been through the logs I've been able to determine a delay when 'Creating Edges'

When scanning with 2.3.115 the log shows:

2023-04-18 09:45:43,802 [MainThread  ] [INFO ]  Creating edges
2023-04-18 09:45:52,535 [MainThread  ] [INFO ]  [TerraformLocalGraph] created 95836 edges

However when scanning the same repo with 2.3.178 it shows:

2023-04-18 08:18:57,011 [MainThread  ] [INFO ]  Creating edges
2023-04-18 08:20:36,112 [MainThread  ] [INFO ]  [TerraformLocalGraph] created 95836 edges

Is that any use to you?

**Comment by ChanochShayner** [comment]
@thedevopsjedi I think that I found the issue in the create edges (some old Python map that I removed)
PR with a potential fix opened - https://github.com/bridgecrewio/checkov/pull/4918/files

**Comment by thedevopsjedi** [comment]
Excellent as soon as a new version is available I will test it and confirm back.

**Comment by ChanochShayner** [comment]
@thedevopsjedi The new version with the fix is 2.3.180

**Comment by thedevopsjedi** [comment]
Ive tested a few times and now and can confirm it is back to the same performance as 2.3.115. 

Thanks a lot for your help @ChanochShayner & @gruebel  :)
