### ISSUE TITLE
CKV_AWS_312 ElasticBeanstalk enhanced health reporting

### ISSUE THREAD

**Issue by jamiegosling** [bridgecrewio/checkov#4908]
**Describe the issue**
New Enhanced Health Reporting check for Elastic Beanstalk in terraform failing, although enhanced health reporting is on

**Examples**
I have the following in the settings, along with a number of other settings
```
  setting {
    namespace = "aws:elasticbeanstalk:healthreporting:system"
    name      = "SystemType"
    value     = "enhanced"
    resource  = ""
  }
```

**Version (please complete the following information):**
 - Checkov Version [2.3.172]

**Additional context**
This setting was not previously set, but it looks like Heath Reporting is set to Advanced by default in my environment

**Comment by gruebel** [comment]
hey @jamiegosling thanks for reaching out.

Are you scanning normal Terraform files or is it a Terraform plan file?

**Comment by jamiegosling** [comment]
Hi @gruebel, we are scanning the terraform source files.

**Comment by gruebel** [comment]
hey @jamiegosling I tried to reproduce it without any luck. Is it possible to share the whole resource configuration, which fails for?

**Comment by gruebel** [comment]
Feel free to reach out again with more information.

**Comment by cardasac** [comment]
I am having the exact same issue. Even with the setting set in terraform with:
```
    {
      namespace = "aws:elasticbeanstalk:healthreporting:system"
      name      = "SystemType"
      value     = "enhanced"
    },
```

**Comment by gruebel** [comment]
Also here, please share the whole resource configuration to better investigate it.
