### ISSUE TITLE
S3 logging check isn't working in some cases

### ISSUE THREAD

**Issue by mlushpenko** [bridgecrewio/checkov#494]
**Describe the bug**
For one of our S3 buckets, `Ensure all data stored in the S3 bucket have versioning enabled` check passes when it should fail.

**To Reproduce**

Run checkov on the following resource :
```
resource "aws_s3_bucket" "k8s-logs" {
  #checkov:skip=CKV_AWS_52:we can't enable mfa delete via terraform
  bucket = var.logs-bucket-name
  acl    = "private"

  logging {
    target_bucket = var.kops-state-bucket-name
    target_prefix = "s3-access-logs/"
  }

  lifecycle_rule {

    id      = "logs"
    enabled = "true"

    transition {
      days          = 60
      storage_class = "GLACIER"
    }

    expiration {
      days = "365"
    }
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}
```

And the results is:

```
checkov -d test --quiet

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
by bridgecrew.io | version: 1.0.484 

terraform scan results:

Passed checks: 6, Failed checks: 0, Skipped checks: 1
```

**Expected behavior**
Fail as versioning wasn't enabled. It only works when I disable versioning explicitly:

```
Passed checks: 5, Failed checks: 1, Skipped checks: 1

Check: CKV_AWS_21: "Ensure all data stored in the S3 bucket have versioning enabled"
        FAILED for resource: aws_s3_bucket.k8s-logs
        File: /s3.tf:1-37
        Guide: https://docs.bridgecrew.io/docs/s3_16-enable-versioning

                1  | resource "aws_s3_bucket" "k8s-logs" {
                2  |   #checkov:skip=CKV_AWS_52:we can't enable mfa delete via terraform
                3  |   bucket = var.logs-bucket-name
                4  |   acl    = "private"
                5  | 
                6  |   versioning {
                7  |     enabled = false
                8  |   }
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Checkov Version 1.0.484 

**Additional context**
I thought perhaps it could be related to naming, so tested with resources names of `k8s-logs`, `k8s_logs` and `k8s` but still same result. Identical bucket works fine:

```
resource "aws_s3_bucket" "state_store" {
  #checkov:skip=CKV_AWS_52:we can't enable mfa delete via terraform
  bucket = var.kops-state-bucket-name
  acl    = "log-delivery-write"

  # versioning {
  #   enabled = true
  # }

  logging {
    target_bucket = var.kops-state-bucket-name
    target_prefix = "s3-access-logs/"
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  tags = merge(
    {
      "Name" = var.kops-state-bucket-name
    },
    var.tags,
  )
}

```

**Comment by nomeelnoj** [comment]
I am also seeing something similar around versioning.

We have an S3 module that is very similar to the open source module found here: https://github.com/terraform-aws-modules/terraform-aws-s3-bucket

The module value for versioning is:

```hcl
versioning {
  enabled = var.versioning
}
```
Then we have variables.tf with: 
```
variable "versioning" {
  default = false
  type.   = bool
}

Inside the module call, we set:
```
versioning = true
```
And then when checkov runs, we get a failure saying all buckets must have versioning enabled.

**Comment by njgibbon** [comment]
Hello :-)

Thank you so much for the report. Proved very useful feedback.

@mlushpenko  - we have fixed the problem you identified and I have just re-tested to confirm that now your S3 check pass / fail in the right circumstances. Update checkov to >= `1.0.668`.

@nomeelnoj  - Checkov has improved variable evaluation recently and so could you please re-test. Because of the module input override of the default though we will still need to investigate this one further if it is failing. If it is, i'd recommend you / we raise a new issue to track this and add the information there.

I think this issue can now be closed in accordance with the above.

**Comment by mlushpenko** [comment]
Thank you @njgibbon, I've checked and it works well, appreciate!
