### ISSUE TITLE
External checks from a package

### ISSUE THREAD

**Issue by fabiodouek** [bridgecrewio/checkov#4961]
**Describe the issue**
Currently it's possible to specify the external_checks_dir and external_checks_git.
However, I was looking for a better mechanism to be able to extract the checks from a Python package. Something like external_checks_package. Is this something you are planning to support?

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
 - Checkov Version 2.3.199

**Comment by gruebel** [comment]
hey @fabiodouek thanks for reaching out.

It is an interesting idea, but we currently don't plan on supporting such a use case.
