### ISSUE TITLE
CKV_AWS_103 does not support TLS 1.3 security policies - Cloudformation

### ISSUE THREAD

**Issue by surecloud-meason** [bridgecrewio/checkov#4962]
Describe the issue
If it is related to an existing check, please note the relevant check ID.
Also, explain the logic for this addition / change.

The AWS default security policy for aws_lb_listener (ELBSecurityPolicy-TLS13-1-2-2021-06) uses TLS 1.3 which the CKV_AWS_103 rule alerts as failed.

The check should ensure 1.2 or above is used.

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html#describe-ssl-policies

Examples
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

Cloudformation:

` "loadbalancerlistener": {
   "Type": "AWS::ElasticLoadBalancingV2::Listener",
   "Properties": {
    "DefaultActions": [
     {
      "FixedResponseConfig": {
       "ContentType": "text/plain",
       "MessageBody": "page not found",
       "StatusCode": "404"
      },
      "Type": "fixed-response"
     }
    ],
    "LoadBalancerArn": {
     "Ref": "loadbalancer"
    },
    "Certificates": [
     {
      "CertificateArn": {
       "Ref": "certificate"
      }
     }
    ],
    "Port": 443,
    "Protocol": "HTTPS",
    "SslPolicy": "ELBSecurityPolicy-TLS13-1-2-2021-06"
   }
}`
 
Version (please complete the following information):

Checkov Version: 2.3.199
Additional context

Looks to have been fixed for terraform only in this issue / PR: https://github.com/bridgecrewio/checkov/issues/3570

**Comment by gruebel** [comment]
hey @surecloud-meason thanks for reaching out.

I can see in the check logic it was adjusted for NLBs already, but not for ALBs. Are you interested in contributing the needed change?

**Comment by surecloud-meason** [comment]
@gruebel I haven't contributed to Checkov at this time so no right now, no.
