### ISSUE TITLE
Unable to install checkov - requirements conflict : requests/urllib3 2.0.0

### ISSUE THREAD

**Issue by AppSecAmael** [bridgecrewio/checkov#4981]
**Describe the issue**
I use gitpod and tried to install checkcov to test it. Installation failed because of a requirements conflict. This seems to be linked to a new version of urllib3 that is not yet supported by requests : https://github.com/psf/requests/issues/6432

**Exception Trace**
```
ERROR: requests 2.29.0 has requirement urllib3<1.27,>=1.21.1, but you'll have urllib3 2.0.0 which is incompatible.
ERROR: botocore 1.29.121 has requirement urllib3<1.27,>=1.25.4, but you'll have urllib3 2.0.0 which is incompatible.
```

**Desktop (please complete the following information):**
 - OS: docker image **gitpod/workspace-java-17:2023-01-08-19-21-22** based on ubuntu 20.04.5
- Installation command : `pip install checkov`
- checkcov package :  **checkov-2.3.202-py3-none-any.whl** 

**Additional context**
This seems to be linked to requests : https://github.com/psf/requests/issues/6432

**Comment by gruebel** [comment]
hey @AppSecAmael thanks for reaching out.

We don't pin `urllib3` in any way on our side, so this is error is a result of something you installed beforehand. I spun up a Gitpod and had no problem to install `checkov`.
