### ISSUE TITLE
Tests folder published in version 2.3.201

### ISSUE THREAD

**Issue by mklenbw** [bridgecrewio/checkov#4984]
The wheel of version 2.3.201 contains the tests folder and pollutes the site-packages even though setup.py excludes it explicitly.

**Comment by gruebel** [comment]
hey @mklenbw thanks for reaching out.

Looks like I forgot a comma 🙈 will fix the problem shortly 🚀

**Comment by by-grabthars-hammer** [comment]
I experienced this issue as well, starting from version 2.3.200. Looking forward to the fix. Thanks.
