### ISSUE TITLE
Checkov Docker Image

### ISSUE THREAD

**Issue by jdhornsby** [bridgecrewio/checkov#50]
**Is your feature request related to a problem? Please describe.**
We are using Gitlab CI. It would be easier/faster to integrate checkov if we had a docker image of it.

**Describe the solution you'd like**
Create a docker image and publish it to docker hub.

**Describe alternatives you've considered**
We are just getting started with checkov and just install it manually at build time. This works ok. We could build a docker image ourselves, but it'd be nice if it was official.

**Additional context**
Forgive me if this does not mesh with your vision for the tool or an image already exists. I couldn't find one docker hub.

**Comment by schosterbarak** [comment]
Hey @jdhornsby , thank you for interest. Do you mind sharing/contributing the dockerfile you have? It would save us some time. I'll add the publishing to dockerhub later on next week if the dockerfile is contributed :)

**Comment by jdhornsby** [comment]
Sure, I'll work on a PR this weekend for you. Thanks!

**Comment by schosterbarak** [comment]
@jdhornsby you should be able to open a PR from a fork

**Comment by schosterbarak** [comment]
Thanks! @jdhornsby docker is now available at: https://hub.docker.com/r/bridgecrew/checkov
Have a great week!

**Comment by jdhornsby** [comment]
Awesome. Thank you! I will update my CI pipeline this week.

**Comment by schosterbarak** [comment]
@jdhornsby if you'd like to share integration docs to circleci under docs/integrations/gitlab (just like the jenkins) that would be  super awesome and will help the community adapt your approach :)

**Comment by jdhornsby** [comment]
Sure thing. I'll work on that and send you a PR with the docs! Thanks for your work on this awesome tool.
