### ISSUE TITLE
CKV_AWS_338 does not account for 0 (keep forever) & has insufficient error message

### ISSUE THREAD

**Issue by richardgavel-ordinaryexperts** [bridgecrewio/checkov#5009]
**Describe the issue**
CKV_AWS_338 is a check for the number of retention days for a Cloudwatch log group. However, the actual check source code requires not just being specified, but also to be at least 1 year.

1 - The message "Ensure that CloudWatch Log Group specifies retention days" does not reflect the need to not only be specified, but also be of sufficient length (or provide ref to web page providing more detail on the check)

2 - 0 is a valid value and means that logs are always retained and never expire, which should result in passing the "must retain for at least 1 year" rule.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
2.3.212

**Comment by quixoticmonk** [comment]
This rule is similar to [CKV_AWS_66 ](https://github.com/bridgecrewio/checkov/blob/9e7a9dd78cbf3786e8cfeb4de99fa4f6b0b23532/checkov/terraform/checks/resource/aws/CloudWatchLogGroupRetention.py#L9).  May I ask the intention behind this rule ?

**Comment by bachya** [comment]
Not sure if this is the same issue, but as of 2.3.112, CKV_AWS_338 requires a list value; however, upon an apply, Terraform complains:

```
Inappropriate value for attribute "retention_in_days": number required.
```

**Comment by aidenvaines-bjss** [comment]
This one got me this morning too,

The CKV_AWS_338 check in https://www.checkov.io/5.Policy%20Index/terraform.html references a check script (https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/CloudWatchLogGroupRetentionYear.py) which seems to be validating the retention is at least 1 year, NOT that it is set as the name of the check would imply.

**Comment by debojitmegaco** [comment]
Faced the same issue this morning.. even though retention period is specified (less than 1 year), this is a hard check and failing when it is not at least more than 1 Year
