### ISSUE TITLE
checkov: error: Unable to open config file

### ISSUE THREAD

**Issue by AshishDadhich4h2** [bridgecrewio/checkov#5019]
**checkov: error: Unable to open config file]*
I am trying to pass config file like
`steps:
  - bash: |
          export BC_API_KEY=${{ parameters.checkov_api_token }}
          ls -lrt $(pwd)/checkov_config.yml
          docker run \
            --volume $(pwd):/tf --env BC_API_KEY=$BC_API_KEY bridgecrew/checkov \
            --directory /tf \
            --output junitxml \
            --bc-api-key $BC_API_KEY \
            --download-external-modules true  \
            --config-file $(pwd)/checkov_config.yml \
            --soft-fail > $(pwd)/CheckovReport.xml
    workingDirectory: $(workdir)
    displayName: "Compliance Run > checkov"   `

It throws an error like
checkov: error: Unable to open config file: /agent/_work/1/s/projectdir/checkov_config.yml. Error: No such file or directory

I verified that  checkov_config.yml exists in above directory. When I print s -lrt $(pwd)/checkov_config.yml it shows correct location

I am running on ADO build agent.

I gave permission chmod 755 $(pwd)/checkov_config.yml but still same error.

Did I miss any configuration?

**Comment by gruebel** [comment]
hey @AshishDadhich4h2 thanks for reaching out.

This error is related to your Docker setup and has nothing to do with `checkov` itself. If you mount the volume `--volume $(pwd):/tf` then all your paths inside the container start with `tf/` and not `$(pwd)/`.
