### ISSUE TITLE
Issues with Python libraries after newest Python update

### ISSUE THREAD

**Issue by Annesars90** [bridgecrewio/checkov#5023]
**Describe the issue**
Since the latest python update, we're getting the following error:
/usr/local/lib/python3.8/dist-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.0.1) or chardet (3.0.4)/charset_normalizer (3.1.0) doesn't match a supported version!

For instance urllib3 (2.0.1) is the latest version, so it looks like checkov is depending on a specific version of the above libraries.

**Comment by Annesars90** [comment]
Patch 15 resolved the issue it seems

**Comment by Annesars90** [comment]
Looks late another patch was released (216) which broke this again, same error as above.

**Comment by nimrodkor** [comment]
This is an issue with local dependencies. I highly suggest working with python in virtual environments to avoid these issues in general

**Comment by Annesars90** [comment]
We're using docker images and always install the latest version of both python (python3-pip) and checkov. It is broken since python came up with a new version of the libraries. We are constantly testing: patch 214 was broken, patch 215 worked and now patch 216 is broken again.
