### ISSUE TITLE
IP Allow List blocking Renovate Bot from checking for new versions of Checkov

### ISSUE THREAD

**Issue by RothAndrew** [bridgecrewio/checkov#5031]
I'm using Renovate to keep Checkov updated in my project, and I am getting this error. The configuration is correct, as testing it locally produces the results I expect, but when the GitHub Marketplace Renovate App tries, it gets this error:

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/16000938/236043512-9903ec77-9ff1-498e-86cb-7406807dea76.png">

Is this org using an IP allow list? If so, can we get this IP address added to it? The WHOIS says Amazon, so I would easily guess that the hosted Renovate Bot runs in AWS. I don't know whether there are other IP addresses that they use as well.

**Comment by gruebel** [comment]
hey @RothAndrew thanks for reaching out.

This is a known behaviour and further information can be found here https://github.com/renovatebot/renovate/discussions/17826
