### ISSUE TITLE
Is checkov scanner sharing source code to different location?

### ISSUE THREAD

**Issue by AshishDadhich4h2** [bridgecrewio/checkov#5043]
Question : Is checkov scanner sharing source code to different location?

We are exploring checkov tool and checking debug logs associated with this.
We would like to ensure that our source code and metadata shouldn't be shared with any other third party.
Can anyone explain how this checkov takes care of that **security/audit concern**?

**Examples**
As per checkov debug logs , it shows like
```
`PUT
/checkov/project2878/project1_cli_repo/tf/1683150502242/src/network.tf

content-md5:tGDujdOgypaOESARp2OsTA==
host:bc-scanner-results-890234264427-prod.s3-accelerate.amazonaws.com
x-amz-content-sha256:UNSIGNED-PAYLOAD
x-amz-date:20230503T214834Z
x-amz-security-token:FwoGZXIvYXdzEOf//////////wEaDGXXXXXXXXXXXNc=

content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-security-token
UNSIGNED-PAYLOAD
2023-05-03 21:48:34,334 [ThreadPoolEx] [DEBUG]  StringToSign`

```

We see many s3 PutObjectTask calls in debug logs. So are we sharing our source code to different storage?

**Version (please complete the following information):**
 - Checkov Version [2.3.220]
 

**Additional context**

**Comment by gruebel** [comment]
hey @AshishDadhich4h2 thanks for reaching out.

Our platform is hosted on AWS and as you found out, we upload the scanned files to our S3 bucket, when used with an API key.

**Comment by AshishDadhich4h2** [comment]
Thank you @gruebel
