### ISSUE TITLE
Checkov -v, get error on all versions of checkov 

### ISSUE THREAD

**Issue by Narullah404** [bridgecrewio/checkov#5048]
**Describe the issue**
```
checkov -v

checkov -d /path/to/terraform/code
```
Running this I should expect it to output the version of checkov installed. and run current tests on terraform code I have

**Exception Trace**
This is the error I get also I have below versions

terraform==1.3.9
python == 3.10.6
checkov==2.3.244

![image](https://user-images.githubusercontent.com/82094109/236436296-a569bd74-afb0-4f43-9b28-71ffcb5d2480.png)

Please let me know how to fix, I've tried everything, I need to get this working on my local system

**Comment by gruebel** [comment]
hey @Narullah404 thanks for reaching out.

I have the feeling you have a wrong version installed of one of our dependencies. Is it possible to run `pip3 list` and share the output here?

**Comment by Narullah404** [comment]
Hi @gruebel Thanks for your reply, here is full list

Package                Version
---------------------- ---------------
aiodns                 3.0.0
aiohttp                3.8.4
aiomultiprocess        0.9.0
aiosignal              1.3.1
ansible-base           2.10.8
apache-libcloud        3.2.0
apturl                 0.5.2
argcomplete            1.8.1
async-timeout          4.0.2
attrs                  22.2.0
Babel                  2.8.0
bc-detect-secrets      1.4.26
bc-jsonpath-ng         1.5.9
bc-python-hcl2         0.3.51
bcrypt                 3.2.0
beautifulsoup4         4.12.2
blinker                1.4
boto3                  1.26.126
botocore               1.29.126
Brlapi                 0.8.3
cached-property        1.5.2
cachetools             5.3.0
certifi                2020.6.20
cffi                   1.15.1
cfgv                   3.3.1
chardet                3.0.4
charset-normalizer     3.1.0
checkov                2.3.224
click                  8.0.3
click-option-group     0.5.5
cloudsplaining         0.5.1
colorama               0.4.3
command-not-found      0.3
ConfigArgParse         1.5.3
contextlib2            21.6.0
cryptography           3.4.8
cupshelpers            1.0
cyclonedx-python-lib   2.7.1
dbus-python            1.2.18
decorator              5.1.1
deep-merge             0.0.4
defer                  1.0.6
detect-secrets         1.4.0
distlib                0.3.6
distro                 1.7.0
distro-info            1.1build1
dnspython              2.1.0
docker                 6.0.1
dockerfile-parse       2.0.0
docopt                 0.6.2
docutils               0.15.2
dpath                  2.1.3
duplicity              0.8.21
exceptiongroup         1.1.0
fasteners              0.14.1
filelock               3.12.0
frozenlist             1.3.3
future                 0.18.2
gitdb                  4.0.5
GitPython              3.1.7
google-auth            2.16.0
httplib2               0.20.2
identify               2.4.10
idna                   2.8
igraph                 0.10.4
importlib-metadata     4.6.4
iniconfig              2.0.0
jeepney                0.7.1
Jinja2                 3.0.3
jmespath               0.10.0
jsonpath-ng            1.5.3
jsonschema             4.17.3
junit-xml              1.9
keyring                23.5.0
kubernetes             25.3.0
language-selector      0.1
lark                   1.1.5
lark-parser            0.7.8
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
lockfile               0.12.2
louis                  3.20.0
macaroonbakery         1.3.1
Mako                   1.1.3
Markdown               3.4.3
MarkupSafe             2.0.1
monotonic              1.6
more-itertools         8.10.0
multidict              6.0.4
netaddr                0.8.0
netifaces              0.11.0
networkx               2.6.3
nodeenv                0.13.4
ntlm-auth              1.4.0
oauthlib               3.2.0
olefile                0.46
openai                 0.27.6
packageurl-python      0.11.1
packaging              21.3
paramiko               2.9.3
pbr                    5.11.1
pexpect                4.8.0
Pillow                 9.0.1
pip                    23.1.2
platformdirs           3.5.0
pluggy                 1.0.0
ply                    3.11
policy-sentry          0.12.6
policyuniverse         1.5.0.20220613
pre-commit             3.3.1
prettytable            3.7.0
protobuf               3.12.4
ptyprocess             0.7.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycairo                1.20.1
pycares                4.3.0
pycep-parser           0.4.0
pycparser              2.21
pycryptodomex          3.11.0
pycups                 2.0.1
PyGObject              3.42.1
PyJWT                  2.3.0
pykerberos             1.1.14
pymacaroons            0.13.0
PyNaCl                 1.5.0
pyparsing              2.4.7
pyRFC3339              1.1
pyrsistent             0.19.3
pyston                 2.3.5
pyston-autoload        2.3.5
pytest                 7.2.1
python-apt             2.3.0+ubuntu2.1
python-dateutil        2.8.1
python-debian          0.1.43ubuntu1
pytz                   2022.1
pywinrm                0.3.0
pyxdg                  0.27
PyYAML                 6.0
regex                  2023.5.4
reportlab              3.6.8
requests               2.30.0
requests-kerberos      0.12.0
requests-ntlm          1.1.0
requests-oauthlib      1.3.1
requests-toolbelt      0.9.1
rsa                    4.9
s3transfer             0.6.0
schema                 0.7.5
SecretStorage          3.3.1
selinux                3.3
semantic-version       2.10.0
setuptools             67.7.2
simplejson             3.17.6
six                    1.15.0
smmap                  3.0.5
sortedcontainers       2.4.0
soupsieve              2.4.1
systemd-python         234
tabulate               0.8.6
termcolor              1.1.0
testresources          2.0.1
texttable              1.6.7
toml                   0.10.2
tomli                  2.0.1
tqdm                   4.65.0
typing_extensions      4.5.0
ubuntu-advantage-tools 27.12
ubuntu-drivers-common  0.0.0
ufw                    0.36.1
unattended-upgrades    0.1
unidiff                0.7.5
update-checker         0.18.0
urllib3                1.26.15
usb-creator            0.3.7
virtualenv             20.23.0
wadllib                1.3.6
wcwidth                0.2.6
websocket-client       1.5.1
wheel                  0.37.1
xdg                    5
xkit                   0.0.0
xmltodict              0.12.0
yarl                   1.9.2
zipp                   1.0.0

**Comment by gruebel** [comment]
thanks, I can see the issue. you have these 2 packages installed
```
lark 1.1.5
lark-parser 0.7.8
```
but only the upper `lark` one works and the other is interfering during the run. You probably installed with something else or is a left over from a very old `checkov` version. just uninstall `lark-parser` and you are good to go.
