### ISSUE TITLE
[docs][custom checks] Schema for `conf` object in python checks

### ISSUE THREAD

**Issue by tarfeef101** [bridgecrewio/checkov#5053]
When writing custom checks, it's difficult to figure out how to do what you want without a schema defined for the `conf` object (as seen [here](https://github.com/bridgecrewio/checkov/blob/3d4bbd32b50ec61e8c1551043bfbb58ee077bd85/checkov/cloudformation/checks/resource/aws/ECRPolicy.py#L12). If this could be published in the docs, users would have a much greater understanding of how to write better checks (I, for one, would love to know how to identify the resource type when in this function, other than inference based on available keys). 

(would expect this to be included on [this page](https://github.com/bridgecrewio/checkov/blob/main/docs/3.Custom%20Policies/Python%20Custom%20Policies.md))

**Comment by gruebel** [comment]
hey @tarfeef101 thanks for reaching out.

We never added a schema for the `conf` parameter, because it represents the actual resource configuration. We can add an example to the mentioned docs, would this be helpful? This won't help your actual question, because the resource type information is not present in the `conf` itself and can be accessed by a class attribute `self.entity_type`.

**Comment by tarfeef101** [comment]
For the question of a schema the entity, I'd say it'd be good to see an example of the contents. Specifically because we use `entity.keys()` to get the fields of the resource. It is difficult to predict what else, if anything, might be there. And makes it easier for users to figure out that first step if laid out in docs.

As for my use case, laying that out would be great (what `entity_type` is, possible values (ideally the same as `supported resources`, just a predictable string).

**Comment by gruebel** [comment]
@tarfeef101 feel free to check out the PR, if it answers your questions 🙂

**Comment by tarfeef101** [comment]
thanks, the `entity_type` stuff will be helpful for sure :) the example of the `conf` schema and type definitions are also great for figuring out how to expect things to be laid out for you given resource(s)

If you have the time to answer, I do also have an unrelated (to you, for me it's in the same custom check) question about `TF_PLAN_RESOURCE_CHANGE_ACTIONS`. Specifically, I'm wanting to know now just "did the resource change, and how", but I want to know "what field(s) changed"?

do you have any examples of this, and/or details on this variable? the best I found on it was [here](https://github.com/bridgecrewio/checkov/pull/3231/files), and even then I had to write an "exploratory check" to ascertain the possible values (seemingly no-op, delete, create, and change? (haven't tested it fully yet). but that is on the resource-level, not the field level

**Comment by gruebel** [comment]
Those are the official Terraform actions you find in the plan file https://developer.hashicorp.com/terraform/internals/json-format#change-representation the only one, which you won't find at the moment is just the `delete` one on its own. There is a feature request for it, but I haven't got any time to come up with a solution for it yet.
