### ISSUE TITLE
Providing Remediation Guidance in Custom Policies

### ISSUE THREAD

**Issue by jbrule** [bridgecrewio/checkov#5082]
How do I specify the value for `Guide:` when creating a policy. I haven't found anything in the documentation or the existing policies found under `/checkov/checkov/terraform/checks` . It's pretty simple with Regula https://regula.dev/development/writing-rules.html#adding-rule-metadata

```
checkov -f tf.json
Check: CKV_AWS_21: "Ensure all data stored in the S3 bucket have versioning enabled"
	FAILED for resource: aws_s3_bucket.customer
	File: /tf/tf1.json:224-268
	Guide: https://docs.bridgecrew.io/docs/s3_16-enable-versioning

		225 |               "values": {
		226 |                 "acceleration_status": "",
		227 |                 "acl": "private",
		228 |                 "arn": "arn:aws:s3:::mybucket",
```

**Comment by gruebel** [comment]
here in the docs
https://github.com/bridgecrewio/checkov/blob/7ef510ac7b10592def49b72612cbbae0e75fcc6e/docs/3.Custom%20Policies/Python%20Custom%20Policies.md?plain=1#L283-L291

**Comment by jbrule** [comment]
What about graph checks (yaml)?

**Comment by jbrule** [comment]
Never mind.  Appears to be same parameter name.
