### ISSUE TITLE
External check logic was rolled back

### ISSUE THREAD

**Issue by robeden** [bridgecrewio/checkov#511]
**Describe the bug**
Issue #466 changed the logic for loading external checks so that they are always loaded by default (and may be skipped with the `--skip-check flag`). That logic was recently rolled back with PR #502 so that external checks again have to be specified if any checks are.

It needs to be decided which behavior is desired.

**Comment by mikeurbanski1** [comment]
@robeden This is reverted back to your expected behavior. Sorry about that.

**Comment by robeden** [comment]
No worries. Thanks, @mikeurbanski1 !
