### ISSUE TITLE
Checkov v2.3.259 fails with CKV_AWS_356 for actions that must specify "all resources"

### ISSUE THREAD

**Issue by lborloz** [bridgecrewio/checkov#5134]
**Describe the issue**
CKV_AWS_356: "Ensure IAM policies limit resource access" produces failures on policies that include statements containing wildcard resources; however, some actions require "All Resources".

**Examples**
```
➜  /tmp cat test.tf 
data "aws_iam_policy_document" "policy" {
  statement {

    actions = [
      "s3:ListAllMyBuckets",
    ]

    resources = [
      "*"
    ]
  }
}
➜  /tmp docker pull bridgecrew/checkov:latest && docker run --rm --volume /tmp:/work --workdir /tf bridgecrew/checkov:latest --directory /work --framework terraform --download-external-modules true --compact --quiet
latest: Pulling from bridgecrew/checkov
Digest: sha256:4a196403a81c9a4540410d6511491389515b6db700efc46d0dcdb7e08ac57523
Status: Image is up to date for bridgecrew/checkov:latest
docker.io/bridgecrew/checkov:latest
terraform scan results:

Passed checks: 9, Failed checks: 1, Skipped checks: 0

Check: CKV_AWS_356: "Ensure IAM policies limit resource access"
        FAILED for resource: aws_iam_policy_document.policy
        File: /test.tf:1-12
```
<img width="2127" alt="image" src="https://github.com/bridgecrewio/checkov/assets/107714840/cd2d88d9-ad59-48e3-9d89-604fee7d5ee1">

**Version (please complete the following information):**
 - 2.3.259

**Additional context**
This check was introduced in: https://github.com/bridgecrewio/checkov/pull/5015

**Comment by gruebel** [comment]
hey @lborloz thanks for reaching out.

Good catch, we use in other checks a more conservative approach, which we should also do here 🙂
