### ISSUE TITLE
Checkov v2.3.261 fails with CKV_AWS_356 for KMS actions which must specify 'all resources'

### ISSUE THREAD

**Issue by aidenvaines-bjss** [bridgecrewio/checkov#5148]
**Describe the issue**
Checkov v2.3.261 fails with CKV_AWS_356 highlights IAM policies which are overly permissive but is incorrectly identifying actions for KMS policies which need to be for all resources potentially scoped with conditional access per https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-services.html

Similar issue for https://github.com/bridgecrewio/checkov/issues/5134 where certain actions like 'list' require all resources.

**Examples**
```
data "aws_iam_policy_document" "myKmsKey" {
    actions = [
      "kms:GenerateDataKey",
      "kms:Decrypt"
    ]
    resources = [
      "*"
    ]

    condition {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
      values = [
        <SOME OTHER RESOURCE>.arn
      ]
    }
  }
}
```
**Version (please complete the following information):**
 - Checkov Version 2.3.261

**Comment by gruebel** [comment]
hey @aidenvaines-bjss thanks for reaching out.

I think my fix, which was released today with version `2.3.263` should also handle your case, feel free to give it a try.

**Comment by aidenvaines-bjss** [comment]
Sadly, still seeing the issue with 2.3.263 and 2.3.264 I am still seeing the issue

Assuming that fix is https://github.com/bridgecrewio/checkov/pull/5135 it looks like KMS isn't covered

**Comment by aidenvaines-bjss** [comment]
Confirmed, this has resolved the issue, thanks @gruebel
