### ISSUE TITLE
Checkov crashes on the latest release. [Terraform]

### ISSUE THREAD

**Issue by AlastairMiller** [bridgecrewio/checkov#5182]
**Describe the issue**
Upgraded to the latest Checkov version v2.3.280 and ran checkov. Downgrading to v2.3.276 resolves this issue.

**Exception Trace**

[Debug.txt](https://github.com/bridgecrewio/checkov/files/11666034/Debug.txt)

**Desktop (please complete the following information):**
 - OS:  Linux
 - Checkov Version 2.3.280

**Comment by bo156** [comment]
Hi, first of all thanks for sharing, I opened this PR which I hope to make checkov not crash in your use-case.
However, it seems from the logs that one of our runners failed, which triggered the crash.
Can you share your `terraform_json` code? From the logs it seems like the relevant file is `/cdktf.out/stacks/cdk.tf.json`.

**Comment by bo156** [comment]
@AlastairMiller can you also update if the crash was solved?
