### ISSUE TITLE
Unable to specify a specific branch to pull external checks from

### ISSUE THREAD

**Issue by sjhood** [bridgecrewio/checkov#5214]
I was previously able to use ?ref=branch-name at the end of the external-checks-git flag and checkov would pull the checks from that specific branch. While using the same process, I am finding that checkov is still using the main branch for the checks. I also attempted to use a --branch branch-name but that also did not work. 

I would expect this would go ahead and clone the repo at the specified branch and use that for the checks, but I am only getting the main/master branch cloned.

(I marked this as an integration problem because it is kind of an issue with github integration but can totally change it to something better suited if needed)

**Comment by gruebel** [comment]
Closing in favour of #4842
