### ISSUE TITLE
Missing guide link for CKV_AZURE_3 report output

### ISSUE THREAD

**Issue by kwame-mintah** [bridgecrewio/checkov#5233]
**Describe the issue**
I'm using the [pre-commit hook](https://github.com/antonbabenko/pre-commit-terraform#checkov-deprecated-and-terraform_checkov) for checkov. During the pre-commit run of the hook, the report for `CKV_AZURE_3` does not include the guide link. Guide links for other checks are provided, however this one seems to be missing in the output.

A guide link does exist: https://docs.bridgecrew.io/docs/ensure-secure-transfer-required-is-enabled 

**Additional context**
```
Check: CKV_AZURE_3: "Ensure that 'Secure transfer required' is set to 'Enabled'"
	FAILED for resource: azurerm_storage_account.tfstate
	File: /storage.tf:23-59
```

**Comment by kwame-mintah** [comment]
Having trouble navigating the repository, would happily raise a PR for this issue, if someone can direct me to the correct file to make amendments.

**Comment by gruebel** [comment]
hey @kwame-mintah thanks for reaching out.

This can't be adjusted in here. The info is stored in our backend and it looks like it related to a previous problem of this check having a duplicate.

**Comment by kwame-mintah** [comment]
@gruebel, thanks for the quick response. I'm happy for the issue to be closed, since I have raised it in the wrong repository. Is there a particular repository I should raise the issue in? or is it best for the issue to be tracked here.

**Comment by gruebel** [comment]
nono, you can't do anything. I have to adjust it in our backend repo 😄
