### ISSUE TITLE
Checkov not loading/using custom checks

### ISSUE THREAD

**Issue by ws-daniel-d** [bridgecrewio/checkov#5238]
**Describe the issue**
I created two custom checks following the [guide](https://www.checkov.io/3.Custom%20Policies/Python%20Custom%20Policies.html), but `checkov` doesn't appear to load/use them.

If I run `checkov -d . --external-checks-dir checkov_checks --list`, `CKV_AWS_999` and `CKV_AWS_998` do not appear in the list.

If I run `checkov -d . --external-checks-dir checkov_checks --check CKV_AWS_999` there are no results.

I would expect that my custom checks would be shown in the list of checks, and that I should see failures for each check because they only return failure.

**Examples**
Within my project directory I created a dir called `checkov_checks`.

I created the following `__init__.py` according to the guide.
```
from os.path import dirname, basename, isfile, join
import glob
modules = glob.glob(join(dirname(__file__), "*.py"))
__all__ = [ basename(f)[:-3] for f in modules if isfile(f) and not f.endswith('__init__.py')]
```

The first check in `rdsencrypted.py`
```
from typing import List, Optional, Dict, Any
from checkov.terraform.checks.module.base_module_check import BaseModuleCheck
from checkov.common.models.enums import CheckCategories, CheckResult

class RDSEncrypted(BaseModuleCheck):
    def __init__(self):
        name = "Ensure RDS encryption has not been disabled"
        id = "CKV_AWS_999"
        catagories = [CheckCategories.ENCRYPTION]
        super().__init__(name=name, id=id, catagories=catagories)

    def scan_module_conf(self, conf: Dict[str, List[Any]]) -> CheckResult:
        return CheckResult.FAILED

check = RDSEncrypted()
```

The second check in `S3PCIPrivateACL.py`
```
from __future__ import annotations
from typing import Any
from checkov.terraform.checks.resource.base_resource_check import BaseResourceCheck
from checkov.common.models.enums import CheckResult, CheckCategories


class S3PCIPrivateACL(BaseResourceCheck):
    def __init__(self) -> None:
        name = "Ensure PCI Scope buckets has private ACL (enable public ACL for non-pci buckets)"
        id = "CKV_AWS_998"
        supported_resources = ["aws_s3_bucket"]
        categories = [CheckCategories.BACKUP_AND_RECOVERY]
        guideline = "Follow the link to get more info https://docs.bridgecrew.io/docs"
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources, guideline=guideline)

    def scan_resource_conf(self, conf: dict[str, list[Any]]) -> CheckResult:
        return CheckResult.FAILED

check = S3PCIPrivateACL()
```

**Version (please complete the following information):**
 - Checkov Version 2.3.285
 - Installed with `brew install checkov`
 - Running on Apple M1 Pro

**Comment by Roomysy** [comment]
Hi Team, have you planned to fix this problem because our team face the same issue?
