### ISSUE TITLE
Install Issue when running Pre-commit on OSX

### ISSUE THREAD

**Issue by ChristopherCowart-FCA** [bridgecrewio/checkov#5250]
**Describe the issue**

I'm attempting to install the pre-commit hook for checkov.  I'm getting the stack trace below when attempting this.   This is stopping the pre-commit hook from installing.  Any help thoughts or help with this would be appreciated.

Explain what you expected to happen when checkov crashed.

**Examples**

pre-commit-config.yaml entry for checkov

- repo: https://github.com/bridgecrewio/checkov.git
  rev: 2.3.301
  hooks:
  - id: checkov
    name: Checkov
    files: '' # Check all files, not just *.tf
    entry: checkov --framework serverless -d .

**Exception Trace**
[INFO] Initializing environment for https://github.com/bridgecrewio/checkov.git.
[INFO] Installing environment for https://github.com/bridgecrewio/checkov.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/christophercowart/.cache/pre-commit/repot8uemy_x
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting bc-python-hcl2==0.3.51 (from checkov==2.3.201)
      Using cached bc_python_hcl2-0.3.51-py3-none-any.whl (14 kB)
    Collecting bc-detect-secrets==1.4.21 (from checkov==2.3.201)
      Downloading bc_detect_secrets-1.4.21-py3-none-any.whl (117 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 1.2 MB/s eta 0:00:00
    Collecting bc-jsonpath-ng==1.5.9 (from checkov==2.3.201)
      Using cached bc_jsonpath_ng-1.5.9-py3-none-any.whl (29 kB)
    Collecting deep-merge (from checkov==2.3.201)
      Using cached deep_merge-0.0.4-py3-none-any.whl (5.1 kB)
    Collecting tabulate (from checkov==2.3.201)
      Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
    Collecting colorama (from checkov==2.3.201)
      Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
    Collecting termcolor (from checkov==2.3.201)
      Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
    Collecting junit-xml>=1.9 (from checkov==2.3.201)
      Using cached junit_xml-1.9-py2.py3-none-any.whl (7.1 kB)
    Collecting dpath==2.1.3 (from checkov==2.3.201)
      Using cached dpath-2.1.3-py3-none-any.whl (17 kB)
    Collecting pyyaml>=5.4.1 (from checkov==2.3.201)
      Using cached PyYAML-6.0-cp311-cp311-macosx_11_0_arm64.whl (167 kB)
    Collecting boto3>=1.17 (from checkov==2.3.201)
      Using cached boto3-1.26.159-py3-none-any.whl (135 kB)
    Collecting gitpython (from checkov==2.3.201)
      Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
    Collecting jmespath (from checkov==2.3.201)
      Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
    Collecting tqdm (from checkov==2.3.201)
      Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
    Collecting update-checker (from checkov==2.3.201)
      Using cached update_checker-0.18.0-py3-none-any.whl (7.0 kB)
    Collecting semantic-version (from checkov==2.3.201)
      Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
    Collecting packaging (from checkov==2.3.201)
      Using cached packaging-23.1-py3-none-any.whl (48 kB)
    Collecting cloudsplaining>=0.4.3 (from checkov==2.3.201)
      Using cached cloudsplaining-0.5.1-py3-none-any.whl (1.7 MB)
    Collecting networkx<2.7 (from checkov==2.3.201)
      Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)
    Collecting igraph (from checkov==2.3.201)
      Using cached igraph-0.10.4-cp39-abi3-macosx_11_0_arm64.whl (1.7 MB)
    Collecting dockerfile-parse (from checkov==2.3.201)
      Using cached dockerfile_parse-2.0.0-py2.py3-none-any.whl (14 kB)
    Collecting docker (from checkov==2.3.201)
      Using cached docker-6.1.3-py3-none-any.whl (148 kB)
    Collecting configargparse (from checkov==2.3.201)
      Using cached ConfigArgParse-1.5.3-py3-none-any.whl (20 kB)
    Collecting argcomplete (from checkov==2.3.201)
      Using cached argcomplete-3.1.1-py3-none-any.whl (41 kB)
    Collecting policyuniverse (from checkov==2.3.201)
      Using cached policyuniverse-1.5.1.20230608-py2.py3-none-any.whl (462 kB)
    Collecting typing-extensions>=4.1.0 (from checkov==2.3.201)
      Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
    Collecting importlib-metadata>=0.12 (from checkov==2.3.201)
      Using cached importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
    Collecting cachetools (from checkov==2.3.201)
      Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
    Collecting cyclonedx-python-lib<4.0.0,>=2.4.0 (from checkov==2.3.201)
      Using cached cyclonedx_python_lib-3.1.5-py3-none-any.whl (200 kB)
    Collecting packageurl-python (from checkov==2.3.201)
      Using cached packageurl_python-0.11.1-py3-none-any.whl (23 kB)
    Collecting click>=8.0.0 (from checkov==2.3.201)
      Using cached click-8.1.3-py3-none-any.whl (96 kB)
    Collecting aiohttp (from checkov==2.3.201)
      Using cached aiohttp-3.8.4-cp311-cp311-macosx_11_0_arm64.whl (332 kB)
    Collecting aiodns (from checkov==2.3.201)
      Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
    Collecting aiomultiprocess (from checkov==2.3.201)
      Using cached aiomultiprocess-0.9.0-py3-none-any.whl (17 kB)
    Collecting jsonschema<5.0.0,>=4.6.0 (from checkov==2.3.201)
      Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
    Collecting prettytable>=3.0.0 (from checkov==2.3.201)
      Using cached prettytable-3.8.0-py3-none-any.whl (27 kB)
    Collecting pycep-parser==0.3.9 (from checkov==2.3.201)
      Using cached pycep_parser-0.3.9-py3-none-any.whl (21 kB)
    Collecting charset-normalizer (from checkov==2.3.201)
      Using cached charset_normalizer-3.1.0-cp311-cp311-macosx_11_0_arm64.whl (121 kB)
    Collecting schema (from checkov==2.3.201)
      Using cached schema-0.7.5-py2.py3-none-any.whl (17 kB)
    Collecting requests>=2.27.0 (from checkov==2.3.201)
      Using cached requests-2.31.0-py3-none-any.whl (62 kB)
    Collecting yarl (from checkov==2.3.201)
      Using cached yarl-1.9.2-cp311-cp311-macosx_11_0_arm64.whl (61 kB)
    Collecting openai (from checkov==2.3.201)
      Using cached openai-0.27.8-py3-none-any.whl (73 kB)
    Collecting unidiff (from bc-detect-secrets==1.4.21->checkov==2.3.201)
      Using cached unidiff-0.7.5-py2.py3-none-any.whl (14 kB)
    Collecting ply (from bc-jsonpath-ng==1.5.9->checkov==2.3.201)
      Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
    Collecting decorator (from bc-jsonpath-ng==1.5.9->checkov==2.3.201)
      Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
    Collecting lark>=1.0.0 (from bc-python-hcl2==0.3.51->checkov==2.3.201)
      Using cached lark-1.1.5-py3-none-any.whl (107 kB)
    Collecting regex>=2022.1.18 (from pycep-parser==0.3.9->checkov==2.3.201)
      Using cached regex-2023.6.3-cp311-cp311-macosx_11_0_arm64.whl (288 kB)
    Collecting botocore<1.30.0,>=1.29.159 (from boto3>=1.17->checkov==2.3.201)
      Using cached botocore-1.29.159-py3-none-any.whl (10.9 MB)
    Collecting s3transfer<0.7.0,>=0.6.0 (from boto3>=1.17->checkov==2.3.201)
      Using cached s3transfer-0.6.1-py3-none-any.whl (79 kB)
    Collecting cached-property (from cloudsplaining>=0.4.3->checkov==2.3.201)
      Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
    Collecting click-option-group (from cloudsplaining>=0.4.3->checkov==2.3.201)
      Using cached click_option_group-0.5.6-py3-none-any.whl (12 kB)
    Collecting jinja2 (from cloudsplaining>=0.4.3->checkov==2.3.201)
      Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
    Collecting markdown (from cloudsplaining>=0.4.3->checkov==2.3.201)
      Using cached Markdown-3.4.3-py3-none-any.whl (93 kB)
    Collecting policy-sentry>=0.11.3 (from cloudsplaining>=0.4.3->checkov==2.3.201)
      Using cached policy_sentry-0.12.6-py3-none-any.whl (3.2 MB)
    Requirement already satisfied: setuptools>=47.0.0 in ./py_env-python3.11/lib/python3.11/site-packages (from cyclonedx-python-lib<4.0.0,>=2.4.0->checkov==2.3.201) (67.8.0)
    Collecting sortedcontainers<3.0.0,>=2.4.0 (from cyclonedx-python-lib<4.0.0,>=2.4.0->checkov==2.3.201)
      Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
    Collecting toml<0.11.0,>=0.10.0 (from cyclonedx-python-lib<4.0.0,>=2.4.0->checkov==2.3.201)
      Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
    Collecting zipp>=0.5 (from importlib-metadata>=0.12->checkov==2.3.201)
      Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
    Collecting attrs>=17.4.0 (from jsonschema<5.0.0,>=4.6.0->checkov==2.3.201)
      Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
    Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema<5.0.0,>=4.6.0->checkov==2.3.201)
      Using cached pyrsistent-0.19.3-cp311-cp311-macosx_10_9_universal2.whl (82 kB)
    Collecting six (from junit-xml>=1.9->checkov==2.3.201)
      Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
    Collecting wcwidth (from prettytable>=3.0.0->checkov==2.3.201)
      Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
    Collecting idna<4,>=2.5 (from requests>=2.27.0->checkov==2.3.201)
      Using cached idna-3.4-py3-none-any.whl (61 kB)
    Collecting urllib3<3,>=1.21.1 (from requests>=2.27.0->checkov==2.3.201)
      Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
    Collecting certifi>=2017.4.17 (from requests>=2.27.0->checkov==2.3.201)
      Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
    Collecting pycares>=4.0.0 (from aiodns->checkov==2.3.201)
      Using cached pycares-4.3.0-cp311-cp311-macosx_10_9_universal2.whl (136 kB)
    Collecting multidict<7.0,>=4.5 (from aiohttp->checkov==2.3.201)
      Using cached multidict-6.0.4-cp311-cp311-macosx_11_0_arm64.whl (29 kB)
    Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp->checkov==2.3.201)
      Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
    Collecting frozenlist>=1.1.1 (from aiohttp->checkov==2.3.201)
      Using cached frozenlist-1.3.3-cp311-cp311-macosx_11_0_arm64.whl (34 kB)
    Collecting aiosignal>=1.1.2 (from aiohttp->checkov==2.3.201)
      Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
    Collecting websocket-client>=0.32.0 (from docker->checkov==2.3.201)
      Using cached websocket_client-1.6.0-py3-none-any.whl (56 kB)
    Collecting gitdb<5,>=4.0.1 (from gitpython->checkov==2.3.201)
      Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)
    Collecting texttable>=1.6.2 (from igraph->checkov==2.3.201)
      Using cached texttable-1.6.7-py2.py3-none-any.whl (10 kB)
    Collecting contextlib2>=0.5.5 (from schema->checkov==2.3.201)
      Using cached contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)
    Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.30.0,>=1.29.159->boto3>=1.17->checkov==2.3.201)
      Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    Collecting urllib3<3,>=1.21.1 (from requests>=2.27.0->checkov==2.3.201)
      Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
    Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->checkov==2.3.201)
      Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
    Collecting beautifulsoup4 (from policy-sentry>=0.11.3->cloudsplaining>=0.4.3->checkov==2.3.201)
      Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
    Collecting cffi>=1.5.0 (from pycares>=4.0.0->aiodns->checkov==2.3.201)
      Using cached cffi-1.15.1-cp311-cp311-macosx_11_0_arm64.whl (174 kB)
    Collecting MarkupSafe>=2.0 (from jinja2->cloudsplaining>=0.4.3->checkov==2.3.201)
      Using cached MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl (17 kB)
    Collecting pycparser (from cffi>=1.5.0->pycares>=4.0.0->aiodns->checkov==2.3.201)
      Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
    Collecting soupsieve>1.2 (from beautifulsoup4->policy-sentry>=0.11.3->cloudsplaining>=0.4.3->checkov==2.3.201)
      Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
    Building wheels for collected packages: checkov
      Building wheel for checkov (setup.py): started
      Building wheel for checkov (setup.py): finished with status 'error'
      Running setup.py clean for checkov
    Failed to build checkov
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [48 lines of output]
          /Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
          !!
          
                  ********************************************************************************
                  Requirements should be satisfied by a PEP 517 installer.
                  If you are using pip, you can try `pip install --use-pep517`.
                  ********************************************************************************
          
          !!
            dist.fetch_build_eggs(dist.setup_requires)
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/setup.py", line 52, in <module>
              setup(
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 106, in setup
              _install_setup_requires(attrs)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
              _fetch_build_eggs(dist)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
              dist.fetch_build_eggs(dist.setup_requires)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
              return _fetch_build_eggs(self, requires)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
              resolved_dists = pkg_resources.working_set.resolve(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 827, in resolve
              dist = self._resolve_dist(
                     ^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
              dist = best[req.key] = env.best_match(
                                     ^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1133, in best_match
              return self.obtain(req, installer)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1145, in obtain
              return installer(requirement)
                     ^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
              wheel.install_as_egg(dist_location)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 117, in install_as_egg
              self._install_as_egg(destination_eggdir, zf)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
              self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
              os.rename(dist_info, egg_info)
          OSError: [Errno 66] Directory not empty: '/Users/christophercowart/.cache/pre-commit/repot8uemy_x/.eggs/PyYAML-6.0-py3.11-macosx-10.9-universal2.egg/PyYAML-6.0.dist-info' -> '/Users/christophercowart/.cache/pre-commit/repot8uemy_x/.eggs/PyYAML-6.0-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for checkov
      error: subprocess-exited-with-error
      
      × python setup.py clean did not run successfully.
      │ exit code: 1
      ╰─> [48 lines of output]
          /Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
          !!
          
                  ********************************************************************************
                  Requirements should be satisfied by a PEP 517 installer.
                  If you are using pip, you can try `pip install --use-pep517`.
                  ********************************************************************************
          
          !!
            dist.fetch_build_eggs(dist.setup_requires)
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/setup.py", line 52, in <module>
              setup(
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 106, in setup
              _install_setup_requires(attrs)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
              _fetch_build_eggs(dist)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
              dist.fetch_build_eggs(dist.setup_requires)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
              return _fetch_build_eggs(self, requires)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
              resolved_dists = pkg_resources.working_set.resolve(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 827, in resolve
              dist = self._resolve_dist(
                     ^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
              dist = best[req.key] = env.best_match(
                                     ^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1133, in best_match
              return self.obtain(req, installer)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1145, in obtain
              return installer(requirement)
                     ^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
              wheel.install_as_egg(dist_location)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 117, in install_as_egg
              self._install_as_egg(destination_eggdir, zf)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
              self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
            File "/Users/christophercowart/.cache/pre-commit/repot8uemy_x/py_env-python3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
              os.rename(dist_info, egg_info)
          OSError: [Errno 66] Directory not empty: '/Users/christophercowart/.cache/pre-commit/repot8uemy_x/.eggs/PyYAML-6.0-py3.11-macosx-10.9-universal2.egg/PyYAML-6.0.dist-info' -> '/Users/christophercowart/.cache/pre-commit/repot8uemy_x/.eggs/PyYAML-6.0-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed cleaning build dir for checkov
    ERROR: Could not build wheels for checkov, which is required to install pyproject.toml-based projects
Check the log at /Users/christophercowart/.cache/pre-commit/pre-commit.log

**Desktop (please complete the following information):**
 - OS: OSX Apple M1
 - Checkov: 2.3.301

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by gruebel** [comment]
hey @ChristopherCowart-FCA thanks for reaching out.

This looks more like a `pre-commit` issue as you can see from the line here

```shell
Directory not empty: '/Users/christophercowart/.cache/pre-commit/repot8uemy_x/.eggs/PyYAML-6.0-py3.11-macosx-10.9-universal2.egg/PyYAML-6.0.dist-info
```

maybe cleaning the cache could help `pre-commit clean`

**Comment by ChristopherCowart-FCA** [comment]
I don't think this is related to pre-commit.  I've been running this through the various revision on the pre-commit hook with checkov.  It looks like anything prior to 2.3.200 works fine (i.e. 2.3.199 consistently installs correctly...2.3.200 does not).

**Comment by gruebel** [comment]
did you try to install it in a separate virtual env without using `pre-commit`? we have multiple engineers, who use Mac M1 and work with `checkov` so installation is currently not a known issue. Sometimes it can be related to the Python version used, you can tell `pre-commit` to use a different one.

**Comment by ChristopherCowart-FCA** [comment]
I haven't seen any issues with it installing directly to a virtual environment. I'm only seeing this with pre-commit and this plugin.  Our development environment has about a dozen different checks running/installing off this.  We're using this for managed lambda runtimes on python 3.9.  I can try up revving the python version and let you know.
