### ISSUE TITLE
Checkov Managed Disk Encryption check in Bicep IaC failing

### ISSUE THREAD

**Issue by mmassey1993** [bridgecrewio/checkov#5252]
**Describe the issue**
Checkov Managed Disk Encryption check will fail despite having the required check in Bicep code. It will only be successful if both checks are in the code, but need to be hashed out.

**Examples**
```
resource Disks 'Microsoft.Compute/disks@2022-07-02' = [for (disk, i) in dataDisks: {
  name: disk.diskName
  location: location
  tags: tags
  sku: {
    name: disk.storageAccountType
  }
  zones: [
    avZone
  ]
  properties: {
    creationData: {
      createOption: 'Empty'
    }
    diskSizeGB: disk.diskSizeGB
    // encryption: {
    //   type: 'EncryptionAtRestWithCustomerKey'
    //   diskEncryptionSetId: diskEncryptionSetId
    // }
    encryption: {
      type: 'EncryptionAtRestWithCustomerKey'
      diskEncryptionSetId: diskEncryptionSetId
    }
    // encryptionSettingsCollection: {
    //   enabled: true
    //   encryptionSettings: [
    //     {
    //       diskEncryptionKey: {
    //         secretUrl: keyURL
    //         sourceVault: {
    //           id: keyVaultId
    //         }
    //       }
    //     }
    //   ]
    // }
  }
}]
```

**Version :**
 - Latest

**Additional context**
Even if I remove the commented out sections, the check will fail. If I have the "encryptionSettingsCollection" block, the check will fail. It will only work if it is formatted like the above.

**Comment by gruebel** [comment]
hey @mmassey1993  thanks for reaching out.

The current check logic doesn't consider for the `encryption` property, which probably didn't exist in the past. Will adjust it 🙂

**Comment by mmassey1993** [comment]
@gruebel Thank you yeah i thought it may be that. However, its not just that though. As it failed to work even when trying to evaluate with the "encryptionSettingsCollection" was uncommented, which is in the current checkov code logic.

**Comment by gruebel** [comment]
You are right, there was also a separate issue with Bicep resources wrapped by a loop. I hope my PR fixes both issues, so give it a try, when it is released.
