### ISSUE TITLE
Checkov Skipping Secrets in Plain Text File

### ISSUE THREAD

**Issue by r-gautam** [bridgecrewio/checkov#5256]
I'm new to Checkov and recently started using it for security scanning of my infrastructure code. I've noticed that Checkov is not detecting secrets stored in a plain text format inside a file. 

**Reproduction Steps**

- Create a plain text file named example secrets.txt.
- Add secrets in the file 
- AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
- Run Checkov with the -d flag to scan the directory containing secrets.txt.
- Observe that Checkov does not detect the secrets stored in secrets.txt.
- Run Checkov with the -f secrets.txt flag to scan the file directly.
- Notice that Checkov successfully detects the secret.

**Version (please complete the following information):**
 - Checkov Version 2.3.90

**Additional context**
Does it mean Checkov primarily focuses on scanning infrastructure as code (IaC) files, such as CloudFormation templates (template.json, template.yml, template.yaml) and Terraform configurations (*.tf files)?
I believe Checkov should be able to detect secrets stored in plain text files during a directory scan.

Note: As a new user of Checkov, I may have overlooked certain configurations or options. Please provide detailed instructions if there are specific steps I need to follow to enable secret detection in plain text files during directory scans or shall i include any other tool along with Checkov to scan secrets.

**Comment by nimrodkor** [comment]
Hello @r-gautam !
Checkov started as an IaC tool, and so we scan Infrastructure configuration files by default. To scan all files for secrets, you can set the `--enable-secret-scan-all-files` argument to enable scanning all files for secrets. The command reference - https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html
