### ISSUE TITLE
CKV_TF_1 doesn't support tags

### ISSUE THREAD

**Issue by Greven145** [bridgecrewio/checkov#5265]
**Describe the issue**
The new CKV_TF_1 only accepts commit hashes (and now local) but won't allow tags

**Examples**
```hcl
module "my_module" {
    source = "git@ssh.myhost.com/terraform_modules/my_module?ref=1.2.3"
}
```

**Version (please complete the following information):**
2.3.306

**Additional context**
Checking for a concrete reference is good, but tags are much easier to understand than a commit hash

**Comment by gruebel** [comment]
hey @Greven145 thanks for reaching out.

Tags are mutable and can be changed as you like, therefore you are vulnerable to a so called Supply Chain attack. This similar to using Docker tags vs Digest or GitHub Actions version tags vs commit hash.

If you are interested in this topic, I recommend to read the blog post by BoostSecurity https://medium.com/boostsecurity/erosion-of-trust-unmasking-supply-chain-vulnerabilities-in-the-terraform-registry-2af48a7eb2

**Comment by plcarman** [comment]
This rule is a bit heavy-handed and I feel most people are going to want to turn it off if they are fetching modules from an internal registry.

**Comment by gruebel** [comment]
if you trust your internal registry and it is immutable, then you can easily ignore it. But the majority of `checkov` users are using public modules and also as far as I know private modules are not immutable per default.

**Comment by sethbacon** [comment]
Private hashicorp registry that is branch-based uses a commit hash which makes the version immutable, so unless checkov is using an api call to determine if it is tag-based or branch-based, it is making an assumption that may not be true.
