### ISSUE TITLE
CKV_TF_1 does not account for TF modules references that pull from a Terraform module repository

### ISSUE THREAD

**Issue by richardgavel-ordinaryexperts** [bridgecrewio/checkov#5267]
**Describe the issue**
CKV_TF_1 does not account for TF modules references that pull from a Terraform module repository as a result of the change in https://github.com/bridgecrewio/checkov/pull/5264.

**Examples**
```
module "vpc" {
   source  = "terraform-aws-modules/vpc/aws"
   version = "3.14.0"
}
```

**Version (please complete the following information):**
 - Checkov Version 2.3.306

**Additional context**
The PR assumes only that anything that is NOT a local module MUST be a Git based module, which is incorrect.

**Comment by gruebel** [comment]
hey @richardgavel-ordinaryexperts thanks for reaching out.

As mentioned in #5265 also registry module version are mutable, because they rely on the tags in the Git repo.

**Comment by X-Guardian** [comment]
@gruebel, your assumption here is incorrect. When published to a Terraform registry, the 'version' of the module to be published is derived from a git tag, but then that version is immutable, and the source repo and any commit hash on the source repo are not applicable and irrelevant. This check should only be running on module references with a source prefix of `git::`.

**Comment by gruebel** [comment]
@X-Guardian maybe you should read the official docs before saying I'm incorrect. 

https://developer.hashicorp.com/terraform/registry/modules/publish#releasing-new-versions
> If your version doesn't appear properly, you may force a sync with GitHub by viewing your module on the registry and clicking "Resync Module" under the "Manage Module" dropdown. This process may take a few minutes. Please only do this if you do not see the version appear, since it will cause the registry to resync all versions of your module.
