### ISSUE TITLE
Deprecate CKV_GCP_67

### ISSUE THREAD

**Issue by fleroux514** [bridgecrewio/checkov#5270]
**Describe the issue**

CKV_GCP_67: https://docs.bridgecrew.io/docs/ensure-legacy-compute-engine-instance-metadata-apis-are-disabled

https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#protect_node_metadata

As per this article:  `The v0.1 and v1beta1 Compute Engine metadata server endpoints were deprecated and shutdown on September 30, 2020.`

**Comment by gruebel** [comment]
hey @fleroux514 thanks for reaching out.

Seems like it is time to retire the check 😄
