### ISSUE TITLE
Docker images missing for releases >= 2.3.294

### ISSUE THREAD

**Issue by peikk0** [bridgecrewio/checkov#5280]
There are no `bridgecrew/checkov` Docker images for releases 2.3.294 and above, except for their `-pyston` variants: https://hub.docker.com/r/bridgecrew/checkov/tags

**Comment by gruebel** [comment]
hey @peikk0 thanks for reaching out.

It looks like I forgot something, when I migrated the publish flow to a different repo 😅 will fix it.
