### ISSUE TITLE
When using modules installed from a module registry 'version' not 'ref' is used as a module code constraint

### ISSUE THREAD

**Issue by sylenama** [bridgecrewio/checkov#5284]
When using modules installed from a module registry `version` not `ref` is used as a module code constraint.
https://developer.hashicorp.com/terraform/language/modules/syntax#version
example:

```
module "consul" {
  source  = "hashicorp/consul/aws"
  version = "0.0.5"
  servers = 3
}
```

In this case the added check fails so please add check for this one.

**Comment by gruebel** [comment]
I think you are referring to the new `CKV_TF_1` check. Check out my comment here and read the blog post https://github.com/bridgecrewio/checkov/issues/5265#issuecomment-1609576408

**Comment by sylenama** [comment]
Thanks @gruebel for your answer and link to the blog. It says about important issue and the Supply Chain breaches. I understand it.  But what if I want to source my module from my company artifactory repo.  It is already checked against vulnerabilities nad I can trust it.

**Comment by gruebel** [comment]
if you can trust it, then it doesn't apply to you. This check enforces immutability of modules, which also a private registry usually doesn't offer for you.
