### ISSUE TITLE
Validate Terraform Resource Name Against Custom Naming Convention Policy

### ISSUE THREAD

**Issue by hosseinkarjoo** [bridgecrewio/checkov#5289]
**Description**
I would like to validate the resource name of a Terraform resource against a custom naming convention policy. Specifically, I want to ensure that the resource name does not contain dashes (-) within it. However, I'm unable to find a suitable method to accomplish this.

**Example Code**
```
resource "google_storage_bucket" "bucket-prd" {
}
```
**Environment**
Checkov Version: 2.3.311

**Expected Behavior**
I expect to be able to check the resource name (bucket-prd) against a custom naming convention policy that prohibits the use of dashes (-) within the name. However, I have been unable to find a way to achieve this.

Please provide guidance or suggest any available methods to validate the resource name against the desired custom policy. Thank you.

**Comment by gruebel** [comment]
hey @hosseinkarjoo thanks for reaching out.

you could access the `__address__` field in the `conf` dict, but be aware if the resource has a `count` or `for_each` then suffix of the index is added.

ex.
```python
conf = {
            "__address__": "aws_ssm_parameter.aws_ssm_parameter_foo",
            "__end_line__": 33,
            "__start_line__": 22,
            "description": ["Parameter foo"],
            "name": ["foo"],
            "tier": ["Advanced"],
            "type": ["String"],
            "value": [{"foo": {"answer ": 42, "hello": "world"}}],
        }
```

**Comment by hosseinkarjoo** [comment]
Thanks for fast response.
Perfect, Solved... 👍

**Comment by hosseinkarjoo** [comment]
Although is it possible to achieve this in custom YAML policy?

**Comment by gruebel** [comment]
yes, the available fields you see are the same for both Python and YAML based policies 🙂
