### ISSUE TITLE
Build k8s job for ARM

### ISSUE THREAD

**Issue by agardnerIT** [bridgecrewio/checkov#5290]
https://hub.docker.com/r/bridgecrew/checkov-k8s/tags is only available for AMD. Build for ARM too.

Multi-architecture support can be done like this:

```
docker buildx build --platform linux/arm64,linux/amd64 --push -t bridgecrew/checkov-k8s:latest -f ./Dockerfile .
```

**Comment by gruebel** [comment]
hey @agardnerIT thanks for reaching out.

yeah that shouldn't be any problem. our normal image is already a multiarch build.

**Comment by agardnerIT** [comment]
> our normal image is already a multiarch build.

Oh, I got a "seg fault" trying to run it on arm k3s. I also (thought I) checked dockerhub and only saw AMD - but rechecking now I see ARM.

Hmm, I will recheck this tomorrow. Strange. Sorry for the time wasted :)
