### ISSUE TITLE
AWS CodeBuild: Exec format error: 'checkov'

### ISSUE THREAD

**Issue by saftinaz** [bridgecrewio/checkov#5299]
I am encountering an unexpected error when running checkov as a subprocess in a Python script in an AWS CodeBuild environment. The error message is `[Errno 8] Exec format error: 'checkov'`. The script works as expected when run on my local Mac machine, but fails with the above error only in the CodeBuild environment.

**Environment**
Python versions tested: 3.8, 3.9, 3.11
AWS CodeBuild environment images tested: 
- aws/codebuild/amazonlinux2-x86_64-standard:5.0
- aws/codebuild/amazonlinux2-x86_64-standard:6.0
- aws/codebuild/standard:7.0 (ubuntu)
Checkov versions: 2.3.299, 2.3.313

**Steps to reproduce**
- Create a Python virtual environment in the AWS CodeBuild environment
- Install checkov into the virtual environment
- Call checkov as a subprocess in a Python script
  - subprocess.Popen(["checkov", "..."])
 
**Expected behavior**:
Checkov runs without errors, as it does on my local machine.

**Actual behavior**:
The script fails with the error message `[Errno 8] Exec format error: 'checkov'` with no additional information.

**Additional context**:
When installing checkov from requirements file, pip reports a few dependency conflicts:

safety 2.3.5 requires packaging<22.0,>=21.0, but packaging 23.1 is being installed.
botocore 1.30.1 requires urllib3<1.27,>=1.25.4, but urllib3 2.0.3 is being installed.
checkov 2.3.313 requires cyclonedx-python-lib<4.0.0,>=2.4.0, but cyclonedx-python-lib 4.0.1 is being installed.

I'm not sure if these conflicts are relevant to the error, but I'm including them here for completeness.

Has anyone encountered this before?  Let me know what other information I can provide that might be relevant.  

I can run other kinds of tests to help debug!

**Comment by gruebel** [comment]
hey @saftinaz thanks for reaching out.

Seeing the errors it looks like you are installing also other things and they don't play nice with each other. Probably `checkov` is not even installed at the end. You can easily find it our by running `pip list` and see, if it is there.

**Comment by saftinaz** [comment]
Thanks for the response and the suggestion!  I looked into that, and I have more information:

I saw there indeed was a dependency conflict with `pip-audit==2.6.0`, which had a release a couple days ago, required `cyclonedx-python-lib~=4.0`, whereas checkov requires `cyclonedx-python-lib<4.0.0`.

I downgraded to `pip-audit==2.5.6` and installed latest `checkov==2.3.314` version, but I am still seeing the error on CodeBuild `[Errno 8] Exec format error: 'checkov'`.

Any other ideas or ways I can get debug logs?  Could it be a permissions issue?

**Comment by gruebel** [comment]
I probably would recommend to approach it differently, instead of directly using Python try to make it work with normal shell commands.

Since you create a separate virtual env, first activate it, then try to invoke `checkov` sometimes you have to do it via `bin/checkov` because of how the `PATH` is set in the CI env. Maybe you really just need to change the `subprocess` call to `subprocess.Popen(["bin/checkov", "..."])` 🤷 and I also recommend to use `subprocess.run(...)` instead 🙂
