### ISSUE TITLE
CKV_OPENAPI_20 incorrectly flags API keys via HTTPS

### ISSUE THREAD

**Issue by ziggythehamster** [bridgecrewio/checkov#5300]
**Describe the issue**

#5253 added CKV_OPENAPI_20 with the message "Ensure that API keys are not sent over cleartext", but the [check](https://github.com/bridgecrewio/checkov/blob/main/checkov/openapi/checks/resource/generic/ClearTextAPIKey.py) does not check the API's supported schemes.

If the intent of this check is to prevent cleartext use of API keys, then if the root level [`schemes`](https://swagger.io/docs/specification/2-0/api-host-and-base-path/) key in OpenAPI 2.0 or [`servers`](https://swagger.io/docs/specification/api-host-and-base-path/) key in OpenAPI 3.0 specifies only `https` (2.0) or only `url`s which are HTTPS (3.0), this check should pass.

**Examples**

[fail2.json](https://github.com/bridgecrewio/checkov/blob/main/tests/openapi/checks/resource/generic/example_ClearTextAPIKey/fail2.json) and its YAML counterpart should fail, but if they specified `"schemes": ["https"]`, they should not.

Ditto for the OpenAPI 3.0 version of this example.

**Version (please complete the following information):**

2.3.312

**Additional context**

It may be that the message is wrong and you actually intend to flag all use of API keys, but if that's the case, the message should convey that. I also would argue that header API keys should not be scrutinized the same way as query parameter API keys, since the risk of leaking the API key unintentionally is higher with the latter.

**Comment by gruebel** [comment]
hey @ziggythehamster thanks for reaching out.

Yeah, the part about sending the token via header shouldn't be flagged, will check it with the creator of the check @tsmithv11
