### ISSUE TITLE
CKV_TF_1

### ISSUE THREAD

**Issue by pinaki-accenture** [bridgecrewio/checkov#5303]
**Describe the issue**
CKV_TF_1 checks for the commit hash with pattern `(?P<commit_id>([0-9a-f]{5,40}))` if "ref?" is used. But what about the tags? As in our environment, we use tags for source reference. 
I suggest tag reference also should be allowed with commit hash as stable versions are being tagged for reference.

Changes required - 
File name: RevisionHash.py
```
COMMIT_ID_PATTERN = re.compile(r"\?(ref=)(?P<commit_id>([0-9a-f.]{5,40}))")
```
**Examples**

Code which is failing - 
```
module "eventhub" {
   source = "git::https://dev.azure.com/pinakiscreation/terraform/_git/azure-eventhub//module?ref=0.1.0"
   ...
}
```
**Version (please complete the following information):**
 - Checkov Version: 2.3.310

**Comment by gruebel** [comment]
hey @pinaki-accenture please check this comment https://github.com/bridgecrewio/checkov/issues/5265#issuecomment-1609576408
