### ISSUE TITLE
Help in Running Checkov Custom rules in repo

### ISSUE THREAD

**Issue by rusherr02** [bridgecrewio/checkov#5311]
**Describe the issue**
I have added a new custom rule under a repo, but seems like it's not able to run that

**Examples**
```
from checkov.cloudformation.checks.resource.base_resource_check import BaseResourceCheck
from checkov.common.models.enums import CheckCategories
from checkov.common.models.enums import CheckResult


class TestRule(BaseResourceCheck):
    def __init__(self):
        name = 'Clu CFT sample Custom rule'
        id = 'CKV_CLU_01'
        supported_resources = ['*']
        categories = [CheckCategories.LOGGING]
        super().__init__(
            name=name, id=id, categories=categories, supported_resources=supported_resources
        )

    def scan_resource_conf(self, conf):
        if 'Resources' in conf:
            if 'ClumioDiscoverPolicy' in conf:
                if (
                    'Resource'
                    in conf['ClumioDiscoverPolicy']['Properties']['PolicyDocument']['Statement']
                    == 'abc'
                ):
                    return CheckResult.FAILED
                else:
                    return CheckResult.PASSED
        else:
            return CheckResult.PASSED


check = TestRule()
```

**PATH=  py/cdf/checkov/custom_rules.py**
**file path to whom I need to run aginst: py/cdf/cft.yaml**

**Output:**
```
checkov -d . --external-checks-dir ./cdf_lib/checkov --framework cloudformation --check CKV_CLU_02
[ cloudformation framework ]: 100%|████████████████████|[52/52], Current File Scanned=/acm/cftemplates/cloud-protect-adopt-vpc-version-18.yaml             
By bridgecrew.io | version: 2.3.316 

cloudformation scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 2
```

I need help running aginst in this way
thanks

**Comment by gruebel** [comment]
not sure, if you have a typo, but the check ID is `CKV_CLU_01` and in the `checkov` call you target `CKV_CLU_02`

**Comment by rusherr02** [comment]
yes it's typo with 1 one also it's showing the same error.

` checkov -d . --external-checks-dir ./cdf_lib/checkov --framework cloudformation --check CKV_CLU_01
[ cloudformation framework ]: 100%|████████████████████|[52/52], Current File Scanned=/acm/cftemplates/cloud-protect-adopt-vpc-version-18.yaml             
                                      
By bridgecrew.io | version: 2.3.316 

cloudformation scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 2

Error parsing file ./dynamite/arena/cftemplates/arena_data_export.yamlֿ
Error parsing file ./dynamite/arena/cftemplates/arena_base.yamlֿ
`

**Comment by gruebel** [comment]
how does the folder structure of `./cdf_lib/checkov` looks like?

**Comment by rusherr02** [comment]
![Uploading Screenshot 2023-07-10 at 5.07.37 PM.jpg…]()

**Comment by rusherr02** [comment]
@gruebel is this helps?

**Comment by rusherr02** [comment]
I think it's not able to scan the template which I wanted it to scan as seen in the console output it's scanning some 51-52 .yaml files, but do you know how can I pass or want it to scan my cloudformation file only?

**Comment by gruebel** [comment]
yeah, just pass the single file via `-f`
ex.
```shell
checkov -f ...
```

**Comment by gruebel** [comment]
closing, feel free to reach out again.
