### ISSUE TITLE
Skip a Check in Checkov via code

### ISSUE THREAD

**Issue by rusherr02** [bridgecrewio/checkov#5329]
**Describe the issue**
Like I read in the docs we can skip check using **--skip-check check_name** but it's via the CLI command,
If I want to skip a check via code how can I do it?
or like what if I create which will skip a specific check, is it possible
to need some help for the same?
thanks

**Comment by gruebel** [comment]
here you can find different ways of skipping/suppressing checks https://github.com/bridgecrewio/checkov/blob/main/docs/2.Basics/Suppressing%20and%20Skipping%20Policies.md
