### ISSUE TITLE
Git executable required to start

### ISSUE THREAD

**Issue by robeden** [bridgecrewio/checkov#533]
**Describe the bug**
checkov won't run in an environment that doesn't have a `git` executable, for example an AWS lambda (particularly using the python3.8 runtime using Amazon Linux 2... haven't tested earlier).

**To Reproduce**
1. docker run -it amazonlinux
2. amazon-linux-extras install python3.8
3. yum install python-virtualenv
4. virtualenv venv_al2 --python=/usr/bin/python3.8
5. venv_al2/bin/pip install checkov
6. Run: `venv_al2/bin/python -c "from checkov.main import run; run()" --soft-fail --no-guide --output json --framework terraform --directory little-repo-of-horrors-bad-terraform-config/ --check "CKV_AWS_1,CKV_AWS_41,CKV_AWS_49"`

(Note: I didn't run exactly that way so they're not 100% tested, but should be close enough to get there.)

**Expected behavior**
This makes sense if the `--external-checks-git` flag is set, but it should be able to soldier on gracefully if not. When that flag isn't used, it shouldn't care.

**Output**
Here's what I get for output when running from an Amazon Linux 2 image using a venv with checkov installed:

> bash-4.2# /source/venv_al2/bin/python -c "from checkov.main import run; run()" --soft-fail --no-guide --output json --framework terraform --directory little-repo-of-horrors-bad-terraform-config/ --check "CKV_AWS_1,CKV_AWS_41,CKV_AWS_49"
> Traceback (most recent call last):
>   File "/source/venv_al2/lib/python3.8/site-packages/git/__init__.py", line 83, in <module>
>     refresh()
>   File "/source/venv_al2/lib/python3.8/site-packages/git/__init__.py", line 73, in refresh
>     if not Git.refresh(path=path):
>   File "/source/venv_al2/lib/python3.8/site-packages/git/cmd.py", line 278, in refresh
>     raise ImportError(err)
> ImportError: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh()
> 
> All git commands will error until this is rectified.
> 
> This initial warning can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|none|n|0: for no warning or exception
>     - warn|w|warning|1: for a printed warning
>     - error|e|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/source/venv_al2/lib/python3.8/site-packages/checkov/main.py", line 12, in <module>
>     from checkov.common.goget.github.get_git import GitGetter
>   File "/source/venv_al2/lib/python3.8/site-packages/checkov/common/goget/github/get_git.py", line 3, in <module>
>     from git import Repo
>   File "/source/venv_al2/lib/python3.8/site-packages/git/__init__.py", line 85, in <module>
>     raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
> ImportError: Failed to initialize: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh()
> 
> All git commands will error until this is rectified.
> 
> This initial warning can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|none|n|0: for no warning or exception
>     - warn|w|warning|1: for a printed warning
>     - error|e|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet

**Comment by robeden** [comment]
I'll make it handle the issue gracefully...

**Comment by schosterbarak** [comment]
> I'll make it handle the issue gracefully...

you are the best!
