### ISSUE TITLE
Sarif report creates invalid uri for folder with spaces

### ISSUE THREAD

**Issue by Jiri-Stary** [bridgecrewio/checkov#5331]
**Describe the issue**
SonarQube will not import SARIF report from Checkov correctly because of invalid URI in SARIF

1) Scan folders with spaces that has some issues
example:
Secrets/Access Tokens/Azure/main.tf 

2) Output result as sarif
3) Resulting file is not valid SARIF due to invalid URI

The field Secrets/Access Tokens/Azure/main.tf corresponds to the results/locations/physicalLocation/artifactLocation/uri object in the SARIF report. There is character the space in the URI. This is not expected. The URI field shouldn’t have any spaces.
This is against specification of URI, which forbids spaces in URIs.

Because of this problem , import of issues in directories with spaces will fail in SonarQube and possibly other tools

**Comment by gruebel** [comment]
hey @Jiri-Stary thanks for reaching out.

Sure, we can remove or replace the space. I couldn't find any official recommendation for it, any thoughts? Either removing it or replace it with `%20`.

**Comment by Jiri-Stary** [comment]
@gruebel 

please replace it with %20 so that way it could be mapped back to the original source code.
Removing it would break it when imported by other tools

I believe there is an RFC defining what uri should look like - rfc3986
I believe %20 is correct

https://datatracker.ietf.org/doc/html/rfc3986



_For example, consider an information service that provides data,
   stored locally using an EBCDIC-based file system, to clients on the
   Internet through an HTTP server.  When an author creates a file with
   the name "Laguna Beach" on that file system, the "http" URI
   corresponding to that resource is expected to contain the meaningful
   string "Laguna%20Beach"._

**Comment by Jiri-Stary** [comment]
i think the proper approach is to use a function that creates a valid URI 

Something like this:

There is a function in urllib called urllib.parse.quote which removes special characters from urls and replaces them with their equivalent percent encoding.

**Comment by Jiri-Stary** [comment]
there are some online sarif validators that checks this as well - https://sarifweb.azurewebsites.net/Validation
You can check if the resulting file valid sarif  - it reports this issue as well

**Comment by gruebel** [comment]
sounds good, I also planed to use `urllib.parse.quote()` to do the proper encoding

**Comment by gruebel** [comment]
> there are some online sarif validators that checks this as well - https://sarifweb.azurewebsites.net/Validation You can check if the resulting file valid sarif - it reports this issue as well

yeah, I tested it already and it doesn't complain about the percent encoding.
