### ISSUE TITLE
Checkov Terragrunt 

### ISSUE THREAD

**Issue by vinodkumar4b9** [bridgecrewio/checkov#5359]
Hi Team,

I am trying to perform checkov scan for our Terragrunt repos , As I have seen there is no straightforward option for terragrunt and as of now I am using the below process to perform checkov scan for terragrunt repos 

1. First I am running terragrunt init
2. And then i am running terragrunt plan and sending that plan to tf.plan
3. Now I am converting that tf.plan to tf.json 
4. Once tf.json is generated , i am checkov scan using checkov -f tf.json 

Above process is working as expected for now , BUt i want to perform this checkov scan for all modules like by using "Terragrunt run-all plan and then generating json accordingly and scanning that, BUt it seems json is not generating as expected.

Is there any such option available ?

**Comment by gruebel** [comment]
Hey @vinodkumar4b9 thanks for reaching out.

I'm not sure, if this is actually a `checkov` question or more a Terragrunt one? At least from my side your approach with scanning the TF plan is the way to go for Terragrunt, because we don't support Terragrunt specific syntax.

**Comment by vinodkumar4b9** [comment]
Hi Gruebel,

Thanks for reaching out to me on this, I will check with Terragrunt team on this.
