### ISSUE TITLE
CKV2_AWS_19 fails on the latest aws provider (5.9.0) with "domain = vpc"

### ISSUE THREAD

**Issue by aaleksandrov** [bridgecrewio/checkov#5378]
**Describe the issue**
CKV2_AWS_19 fails when using new argument `domain   = "vpc"`. [Suggested solution](https://docs.bridgecrew.io/docs/ensure-that-all-eip-addresses-allocated-to-a-vpc-are-attached-to-ec2-instances) requires setting deprecated argument `vpc = true`

**Examples**
```
Check: CKV2_AWS_19: "Ensure that all EIP addresses allocated to a VPC are attached to EC2 instances"
	FAILED for resource: module.infra_provisioner.aws_eip.infra_provisioner_host_ip
	File: /src/modules/infra-provisioner/main.tf:10-13
	Guide: https://docs.bridgecrew.io/docs/ensure-that-all-eip-addresses-allocated-to-a-vpc-are-attached-to-ec2-instances

		10 | resource "aws_eip" "infra_provisioner_host_ip" {
		11 |   instance = aws_instance.infra_provisioner_host.id
		12 |   domain   = "vpc"
		13 | }
```

**Version (please complete the following information):**
latest, just installing it with `pip3 install checkov -q`

**Additional context**
The check passes when setting `vpc = true` instead of `domain   = "vpc"` 
`vpc` flag  was recently deprecated https://registry.terraform.io/providers/hashicorp/aws/5.9.0/docs/resources/eip
```
**vpc** - (Optional Deprecated) Boolean if the EIP is in a VPC or not. Use domain instead. Defaults to true unless the region supports EC2-Classic.
```

**Comment by gruebel** [comment]
hey @aaleksandrov thanks for reaching out.

Yeah sounds like a good idea to support both variants.
