### ISSUE TITLE
Skip Multiple Checks in a single comment

### ISSUE THREAD

**Issue by stepintooracledba** [bridgecrewio/checkov#5381]
**Describe the issue**

I'm running checkov scans for my terraform config,

Say for example, my IAM Policy triggers multiple checks like 

Check: CKV_AWS_355: "Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions"
Check: CKV_AWS_287: "Ensure IAM policies does not allow credentials exposure"

So what I'm doing right now to skip this check is to add a skip in the resource one for each Checks like,

# checkov:skip=CKV_AWS_355: Skip 1
# checkov:skip=CKV_AWS_287: Skip 2

Is it possible to add the skips of multiple check in a single line rather than defining multiple checks,

# checkov:skip=CKV_AWS_355,CKV_AWS_287: Skipping all checks

**Version (please complete the following information):**
 - Checkov Version - 2.3.343

**Additional context**

**Comment by lagerfeuer** [comment]
I'm surprised that this isn't possible already. Would also love to see this added.

**Comment by stepintooracledba** [comment]
Any update please?

**Comment by TarangGu** [comment]
Any way to skip multiple checks at once?

**Comment by talazuri** [comment]
should be solved with #6860

**Comment by stepintooracledba** [comment]
@talazuri Thanks for updating the thread. I confirm that multiple checks listed as below works,

#checkov:skip=CKV_AWS_355,CKV_AWS_287: Skipping all checks

But If i try to add comments to the skips like below it doesn't work.

#checkov:skip=CKV_AWS_355:Skipping first one,CKV_AWS_287: Skipping second one

Please advise,
