### ISSUE TITLE
[CKV_AZURE_178] Ensure linux VM enables SSH with keys for secure communication

### ISSUE THREAD

**Issue by Veereshsetty** [bridgecrewio/checkov#5387]
**Describe the issue**
Even though the admin SSH keys block has been defined for the azurerm_linux_virtual_machine module and password-based authentication has been disabled, the Checkov scan still failed.
**Examples**
```
 dynamic "admin_ssh_key" {
    for_each = var.disable_password_authentication == true ? [1] : []
    content {
      public_key =  tls_private_key.generate_ssh_keys_tls_private_key.public_key_openssh
      username   = var.adminusername
    }
  }
```

**Version (please complete the following information):**
 - Checkov Latest verison

**Additional context**

**Comment by gruebel** [comment]
hey @Veereshsetty thanks for reaching out.

I need some additional info, what exactly is the default for `var.disable_password_authentication`? and can you share the complete resource block?

**Comment by Veereshsetty** [comment]
> hey @Veereshsetty thanks for reaching out.
> 
> I need some additional info, what exactly is the default for `var.disable_password_authentication`? and can you share the complete resource block?

This is for azurerm_linux_virtual_machine , Default value for the variable disable_password_authentication is true.  we defined admin_ssh_key block in the resource block but, still the [CKV_AZURE_178] is being failed.

**Comment by gruebel** [comment]
ok, I tested it against following example and the check passes. Not sure what is different one your side. Are you setting some kind of env vars, when you call `checkov`? And which version are you using exactly? Are you scanning the TF templates or the plan file?

```hcl
variable disable_password_authentication {
  default = true
}

resource "tls_private_key" "generate_ssh_keys_tls_private_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "azurerm_linux_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  dynamic "admin_ssh_key" {
    for_each = var.disable_password_authentication == true ? [1] : []
    content {
      public_key = tls_private_key.generate_ssh_keys_tls_private_key.public_key_openssh
      username   = var.adminusername
    }
  }
}
```

**Comment by gruebel** [comment]
feel free to reach out again with more info 🙂

**Comment by realsatyamchaudhary** [comment]
> vars

below is the code the command for the checkov scan which we are running with ADO pipeline and the checkov version which we are using exactly is 2.3.347.

          terraform plan -out "$(build.artifactstagingdirectory)/checkov_modules_$folder.tfplan"

          terraform show -json "$(build.artifactstagingdirectory)/checkov_modules_$folder.tfplan" |jq '.' > "$(build.artifactstagingdirectory)/checkov_modules_$folder.json"
          checkov -f "$(build.artifactstagingdirectory)/checkov_modules_$folder.json" --output junitxml -s > "$(build.artifactstagingdirectory)/checkov_modules_$folder.xml"
          cd ..
        done
      workingDirectory: ${{ parameters.terraform_directory }}
    env:
      ${{ each parameter in parameters.provider_configs }}:
        TF_VAR_${{ parameter.Key }}: ${{ parameter.Value }}
      ARM_CLIENT_ID: ${{ parameters.spn_client_id }}
      ARM_CLIENT_SECRET: ${{ parameters.spn_client_secret }}
      ARM_SKIP_PROVIDER_REGISTRATION: "true"
      CHECKOV_NEW_TF_PARSER: "true"
      CHECKOV_ENABLE_MODULES_FOREACH_HANDLING: "true"

**Comment by junhu73** [comment]
> ok, I tested it against following example and the check passes. Not sure what is different one your side. Are you setting some kind of env vars, when you call `checkov`? And which version are you using exactly? Are you scanning the TF templates or the plan file?
> 
> ```terraform
> variable disable_password_authentication {
>   default = true
> }
> 
> resource "tls_private_key" "generate_ssh_keys_tls_private_key" {
>   algorithm = "RSA"
>   rsa_bits  = 4096
> }
> 
> resource "azurerm_linux_virtual_machine" "example" {
>   name                = "example-machine"
>   resource_group_name = azurerm_resource_group.example.name
>   location            = azurerm_resource_group.example.location
>   size                = "Standard_F2"
>   admin_username      = "adminuser"
>   network_interface_ids = [
>     azurerm_network_interface.example.id,
>   ]
> 
>   dynamic "admin_ssh_key" {
>     for_each = var.disable_password_authentication == true ? [1] : []
>     content {
>       public_key = tls_private_key.generate_ssh_keys_tls_private_key.public_key_openssh
>       username   = var.adminusername
>     }
>   }
> }
> ```

one needs to reproduce the issue by calling this terraform code through terraform module script. A quite numbers of Checkov checks give false positives when scanning terraform plan produced from module calling. Both terraform plans (produced from root module with this vm block, or produced from root module by calling the module with this vm block) have identical data except one is part of root module (checkov works correctly with scan passing), one is part of child module (checkov scan failing - false positive).  Since this issue has been there for months, can you let us know if this is bug or feature?
