### ISSUE TITLE
CKV_AWS_299 Fails for Values That Can't be Set

### ISSUE THREAD

**Issue by rossbush** [bridgecrewio/checkov#5394]
**Describe the issue**
Failing on - Check: CKV_AWS_299: "Ensure DMS S3 defines in-transit encryption"

When the endpoint of a DMS Migration Task has a Endpoint that is S3, there is no option in AWS to specify ssl_mode. AWS does not have an ssl_mode for DMS Endpoints. Setting this value on extra connections does nothing. Also, setting this in Terraform does nothing. I may be crazy, but I think DMS transfers to S3 uses SSL by default.

**Examples**
```

from __future__ import annotations

from typing import Any

from checkov.terraform.checks.resource.base_resource_value_check import BaseResourceValueCheck
from checkov.common.models.enums import CheckCategories


class DMSS3DefinesIntransitEncryption(BaseResourceValueCheck):
    def __init__(self) -> None:
        name = "Ensure DMS S3 defines in-transit encryption"
        id = "CKV_AWS_299"
        supported_resources = ("aws_dms_s3_endpoint",)
        categories = (CheckCategories.ENCRYPTION,)
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def get_inspected_key(self) -> str:
        return 'ssl_mode'

    def get_expected_values(self) -> list[Any]:
        return ["require", "verify-ca", "verify-full"]


check = DMSS3DefinesIntransitEncryption()

```

**Version (please complete the following information):**
 - Checkov Version 2.3.343

**Additional context**

This is property does nothing in terraform when the aws_dme_enpoint is s3 and I file and issue over there, however, it was closed with no fix.

**Comment by gruebel** [comment]
hey @rossbush thanks for reaching out.

I think you are right. I also checked and my guess is, it is a copy paste error by Terraform. the normal DMS endpoint offers this functionality, but not S3.

hey @JamesWoolfenden can you remember something, when you added it?

**Comment by rossbush** [comment]
> hey @rossbush thanks for reaching out.
> 
> I think you are right. I also checked and my guess is, it is a copy paste error by Terraform. the normal DMS endpoint offers this functionality, but not S3.
> 
> hey @JamesWoolfenden can you remember something, when you added it?

Greetings @gruebel, this a Quazi catch-22.  When the ssl_mode value is set to anything other than "none" then AWS returns an InvalidParamaterCombination, when the endpoint is of type S3.

See bug logged with terraform below. On one hand to pass Checkov the value is set it to anything other than "none", but then get an AWS exception during apply.

To get around the AWS exception we set the value to "none" but fail the Checov rule.

Currently, corporate has made this a soft fail for our pipelines, however, we are getting a heap of warnings and to me it just seems like an obsolete rule. Since there is no value allowed other than "none" for the resource backed by `DMSS3DefinesIntransitEncryption`
