### ISSUE TITLE
[CKV_AZURE_4] Ensure AKS logging to Azure Monitoring is Configured

### ISSUE THREAD

**Issue by GunasheelaSatharasi** [bridgecrewio/checkov#5395]
**Describe the issue**
Even though Configuring the oms_agent block with the Log Analytics Workspace ID to connect the AKS cluster to Azure Monitor, the Checkov scan still failed.

**Examples**

```hcl
dynamic "oms_agent" {
    for_each = var.kubernetes_cluster_oms_agent != null ? [1] : []
    content {
      log_analytics_workspace_id = data.azurerm_log_analytics_workspace.oms_log_analytics_id.id
    }
  }
```

**Version (please complete the following information):**
 - Checkov Version latest.

**Additional context**

**Comment by gruebel** [comment]
hey @GunasheelaSatharasi thanks for reaching out.

I tested it with a minimal example and can't reproduce it. It returns back a passed result.

```hcl
variable kubernetes_cluster_oms_agent {
}

resource "azurerm_kubernetes_cluster" "pass" {
  name                = "example"
  location            = "example"
  resource_group_name = "example"

  dynamic "oms_agent" {
    for_each = var.kubernetes_cluster_oms_agent != null ? [1] : []
    content {
      log_analytics_workspace_id = data.azurerm_log_analytics_workspace.oms_log_analytics_id.id
    }
  }
}
```

**Comment by gruebel** [comment]
feel free to reach out with more info again.
