### ISSUE TITLE
`Error: <linearGradient>` and `Uncaught TypeError` - main site

### ISSUE THREAD

**Issue by mbiesiad** [bridgecrewio/checkov#5414]
Hi,

# Repro steps:
1. Using Chromium based browser (ie. Chrome or Brave) go to https://www.checkov.io/
2. Check DevTools Console
3. See many errors

# Results:
`www.checkov.io/:448 Error: <linearGradient> attribute x1: Expected length, "-nan".`

`www.checkov.io/:448 Error: <linearGradient> attribute y1: Expected length, "-nan".`

`www.checkov.io/:448 Error: <linearGradient> attribute x2: Expected length, "-nan".`

`www.checkov.io/:448 Error: <linearGradient> attribute y2: Expected length, "-nan".`

`www.checkov.io/:539 Error: <linearGradient> attribute x1: Expected length, "-nan".`

`www.checkov.io/:539 Error: <linearGradient> attribute y1: Expected length, "-nan".`

`www.checkov.io/:539 Error: <linearGradient> attribute x2: Expected length, "-nan".`

`www.checkov.io/:539 Error: <linearGradient> attribute y2: Expected length, "-nan".`

`(index):746 Uncaught TypeError: Cannot read properties of undefined (reading 'initialise')
    at (index):746:26`

# Screenshot:
![image](https://github.com/bridgecrewio/checkov/assets/18367606/03767778-3e0d-4238-ad74-5adf7b229ea9)

# Additional information:
Using Firefox looks fine, no errors occurs.

Best wishes,

**Comment by FrancisBrokering** [comment]
I'm having the same issue. How were you able to solve this?
