### ISSUE TITLE
BCAuthError (status code 403)

### ISSUE THREAD

**Issue by DaVeToX** [bridgecrewio/checkov#5426]
Hi,
I´m using checkov for one project in a GH Action. Therefore I created an API token (to work with the severity level in findings).
It was working fine until recently, when all the sudden I got the error message:
**checkov.common.bridgecrew.platform_errors.BridgecrewAuthError: BCAuthError, Received unexpected response from platform (status code 403). Please verify that your API token is valid and has permissions to call the Bridgecrew APIs.The key must be associated with any role besides Auditor.** 

I never set any special permissions for the API token or associated any role to the token. 
I´m a bit clueless, why the issue occurs now.

How I run checkov:
```- name: Run Checkov f
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          api-key: XXXXXXXXXXXXXXX
          directory: ./01_setup
          quiet: true
          compact: true
          use_enforcement_rules: true
          check: MEDIUM
          output_format: github_failed_only
          output_file_path: ./checkov_output.md
```

Did I miss something?

Thanks for you help in advance

David

**Comment by JamesWoolfenden** [comment]
This can happen if your Bridgecrew account has expired (sustained inactivity), id try logging on to see if you still can. This can also happen if you overdo the resources when you're on the free tier. If the account its expired you can create a new account with another email acc. The platform shuts in Dec having been replaced by the Prisma platform, so you can connect to that (theres no free tier).

**Comment by DaVeToX** [comment]
hey @JamesWoolfenden ,
thx for your response.
So my Bridgecrew account seems to be fine (I´m still in free tier and used that heavily during testing :D). I can create new API keys with no issue and also got no email saying that the account is expired. So propably, I over used the free tier..

But good to know, that the plattform will shutdown and no free tier will be available. :-(

**Comment by DaVeToX** [comment]
Creating new API key with another email worked fine. So I probably used the free tier too much.
