### ISSUE TITLE
CKV_AWS_355 & CKV_AWS_356 incorrectly error on logs:DescribeLogGroups action with resource "*"

### ISSUE THREAD

**Issue by marlonparmentier** [bridgecrewio/checkov#5442]
CKV_AWS_355 & CKV_AWS_356 check whether resource is not set to resource:"\*" for IAM actions where this is unwanted and it should filter for resources that require resource:"\*" . It does, and for most resources this works correctly. But for logs:DescribeLogGroups Checkov errors on the resource:"*" definition even though the IAM action requires it. If the resource for this IAM action is set to an ARN, the IAM Policy document in AWS becomes invalid and does not grant access to anything.

**Examples**
Example below should not fail CKV_AWS_355, but it does (check 356 is exactly the same, but for the Data object):

Check: CKV_AWS_355: "Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions"
        FAILED for resource: aws_iam_policy.policy
        File: /data.tf:1-20

                1  | resource "aws_iam_policy" "policy" {
                2  |   name        = "test_policy"
                3  |   path        = "/"
                4  |   description = "My test policy"
                5  | 
                6  |   # Terraform's "jsonencode" function converts a
                7  |   # Terraform expression result to valid JSON syntax.
                8  |   policy = jsonencode({
                9  |     Version = "2012-10-17"
                10 |     Statement = [
                11 |       {
                12 |         Action = [
                13 |           "logs:DescribeLogGroups",
                14 |         ]
                15 |         Effect   = "Allow"
                16 |         Resource = "*"
                17 |       },
                18 |     ]
                19 |   })
                20 | }

I expect the outcome:

Check: CKV_AWS_355: "Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions"
        PASSED for resource: aws_iam_policy.policy
        File: /data.tf:1-20

**Version (please complete the following information):**
 - Checkov Version 2.3.360

**Additional context**
https://github.com/bridgecrewio/checkov/pull/5135 I think this specific IAM action is missing from the list of exclusions for some reason.

**Comment by gruebel** [comment]
hey @marlonparmentier is was fixed in the dependency we use. To make sure you have the fix check, which version of `policy-sentry` is installed, it should be `0.12.8`.
