### ISSUE TITLE
skip_checks are not working with config.yml file

### ISSUE THREAD

**Issue by metalcloudnerd** [bridgecrewio/checkov#5445]
**Describe the issue**
skip_checks feature is not working with config.yml file

**Examples**
config.yml file
```
# config.yml

skip_checks:
  - CKV2_AWS_6
  - CKV2_AWS_19
  - CKV2_AWS_18
  - CKV2_AWS_300

frameworks:
  - terraform

```

**command:**

`checkov -d . --config-file config.yml`

**ERROR:**
checkov: error: unrecognized arguments: --skip_checks=CKV2_AWS_6 --skip_checks=CKV2_AWS_19
**Version (please complete the following information):**
 - Checkov Version 2.3.365

**Additional context**
the config.yml file is in the current working directory

**Comment by gruebel** [comment]
hey @metalcloudnerd thanks for reaching out.

As in the help text of the flag is written

> Checks to skip; any other checks will not be run. Enter one or more items **separated by commas**.

**Comment by metalcloudnerd** [comment]
@gruebel  thanks for your response. Can you share a sample config.yml file for reference?

**Comment by metalcloudnerd** [comment]
The purpose of using the config.yml file, is will centralize all our configuration details, allowing us to customize Checkov's behavior consistently. I would like to transition from providing command-line arguments to utilizing the config.yml file, which will make our scans more organized and efficient.

**Comment by metalcloudnerd** [comment]
@gruebel  do you have any update for me?

**Comment by gruebel** [comment]
now I see the issue, you misspelled the key, they have to be identical to the actual flag

```yaml
skip-check:
  - CKV2_AWS_6
  - CKV2_AWS_19
  - CKV2_AWS_18
  - CKV2_AWS_300
```

**Comment by metalcloudnerd** [comment]
Thanks @gruebel
