### ISSUE TITLE
CKV_AWS_206 fails when no security_policy is provided case?

### ISSUE THREAD

**Issue by rajlearner17** [bridgecrewio/checkov#5457]
**Describe the issue**
If it is related to an existing check, please note the relevant check ID.
Also, explain the logic for this addition / change.

Check - CKV_AWS_206 ("Ensure API Gateway Domain uses a modern security Policy")
Should it result FAILED for the below case?
```
resource "aws_api_gateway_domain_name" "pass1" {
  certificate_arn = "arn:aws:acm:us-east-1:132322232:certificate/1dcc6fba-1xxxx-4e44-adb1-c516d0c07297"
  domain_name     = "startrainer.in"
}
```

IMO, when `security_policy` is not explicitly set, then by default, the API Gateway Domain name is associated to TLS_1_2

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
 - By bridgecrew.io | version: 2.4.2 

**Additional context**

**Comment by JamesWoolfenden** [comment]
If that's the cases then you are right. Where does it say that is the default? I haven't seen that in the docs or the provider code.
