### ISSUE TITLE
JUNIT XML Output file name incorrect in the docs

### ISSUE THREAD

**Issue by neilmca-inc** [bridgecrewio/checkov#5474]
**Describe the issue**
The documentation specifying the name of the JUNIT XML file output name is incorrect under the `--output-file-path OUTPUT_FILE_PATH` specification
https://github.com/bridgecrewio/checkov//blob/master/docs/2.Basics/CLI%20Command%20Reference.md

**Additional context**
The file name output is called `results_junitxml.xml` and not `results.xml` when specifying `-o junitxml --output-file-path ./path/to/etc/etc/`

**Comment by neilmca-inc** [comment]
Hi @gruebel 

When I ran this command....

`checkov -f tf.json -s -o junitxml --output-file-path /home/neilmca`

...the file produced was called `results_junitxml.xml`

**Comment by gruebel** [comment]
correct, as it is written in the docs

> Name of the output folder to save the chosen output formats.

It doesn't specify what the actual filenames will be. We overloaded the same flag to make it work with specifying a filename, but then you need to use the syntax I mentioned.

ex.
```
checkov -f tf.json -s -o junitxml --output-file-path /home/neilmca/results.xml,
```

the important part is the `comma` otherwise it will be a folder.
