### ISSUE TITLE
Bulk Resource Type Declaration

### ISSUE THREAD

**Issue by jbrule** [bridgecrewio/checkov#5477]
**Describe the issue**
I am trying to author a Terraform policy for GCP which detects if undesirable principal types are being applied to *_iam_member and *_iam_binding resource types. The policy is pretty simple. I am just looking for prefix "user:" for member attribute or entry of members attribute. The tough part is applying the policy to ALL of the binding resources, each resource type has associated binding resources so that is pretty big list that needs to be managed as new resource types are added. 

I know that attribute checks support appear to have some wildcard support https://github.com/bridgecrewio/checkov/blob/main/docs/3.Custom%20Policies/Python%20Custom%20Policies.md is there anything like that for Graph Checks?

**Example Code**
Policy as implemented in Hashcorp Sentinel

```hcl
find_resources_with_type_suffix = func(resource_suffix) {

  resources = filter tfplan.resource_changes as address, rc {
  	strings.has_suffix(rc.type,resource_suffix) and
  	rc.mode is "managed" and
  	(rc.change.actions contains "create" or rc.change.actions contains "update" or
     rc.change.actions contains "read" or rc.change.actions contains "no-op")
  }

  return resources
}

forbidden_member_prefix = "user:"

iam_member_resources = find_resources_with_type_suffix("iam_member")
iam_member_violations = map iam_member_resources as address,rc { filter_members_have_prefix(rc, plan.evaluate_attribute(rc, "member"), forbidden_member_prefix, false) }
iam_member_violations = merge_filter_results(iam_member_violations)

iam_binding_resources = find_resources_with_type_suffix("iam_binding")
iam_binding_violations = map iam_binding_resources as address,rc { filter_members_have_prefix(rc, plan.evaluate_attribute(rc, "members"), forbidden_member_prefix, false) }
iam_binding_violations = merge_filter_results(iam_binding_violations)
```

**Comment by gruebel** [comment]
Hey @jbrule thanks for reaching out.

Actually we talked internally about it a few days ago, but it currently doesn't have any priority to be tackled by us. Anyone is welcome to contribute the needed changes 🙂

**Comment by jbrule** [comment]
I decided to look at what it would take to add wildcard resource support. It appears the resource_types are parsed here https://github.com/bridgecrewio/checkov/blob/f3a0ba6a061cda05bd97d254c18d66a63b1822da/checkov/common/checks_infra/checks_parser.py#L235

I was basing my logic off of the "all" condition.
```python
            if (
                    not resource_type
                    or (isinstance(resource_type, str) and resource_type.lower() == "all")
                    or (isinstance(resource_type, list) and resource_type[0].lower() == "all")
            ):
                check.resource_types = resources_types or []
```
but it looks like that relies on [checkov/common/checks_infra/resources_types.py](https://github.com/bridgecrewio/checkov/blob/f3a0ba6a061cda05bd97d254c18d66a63b1822da/checkov/common/checks_infra/resources_types.py#L744) which is missing and/or has invalid resource types. I only reviewed the GCP provider.  

For instance [google_compute_instance_iam](https://github.com/bridgecrewio/checkov/blob/f3a0ba6a061cda05bd97d254c18d66a63b1822da/checkov/common/checks_infra/resources_types.py#L744 ) isn't a valid resource. It should be google_compute_instance_iam_member, google_compute_instance_iam_binding and google_compute_instance_iam_policy
```
Error: Invalid resource type

  on sp170.tf line 45, in resource "google_compute_instance_iam" "my_compute_iam":
  45: resource "google_compute_instance_iam" "my_compute_iam" {

The provider provider.google does not support resource type
"google_compute_instance_iam"
```
So I would have to assume that when ***resource_types: "all"*** is used Checkov IS NOT inspecting all resources. Or do I misunderstand the logic?

My plan for wildcard support is as follows
```yaml
cond_type: attribute
resource_types:
- "*_iam_member"
attribute: "member"
operator: "not_starting_with"
value: "user:"
```
This was my filtering logic
```python
# if resource_type contains asterisk "*" apply regex like following
input_resource_type = "*_iam_member"
wildcard_resource_pattern = "^{}$".format(input_resource_type.replace("*",".*"))
resource_type_regex = re.compile(wildcard_resource_pattern)
check.resource_types = [rt for rt in resource_types if resource_type_regex(rt)]
```

It would be ideal if we could filter resource_types as found in the infrastructure so we could avoid maintenance of this list
