### ISSUE TITLE
Extend CKV2_AWS_5 to include aws_appstream_fleet

### ISSUE THREAD

**Issue by abondrndc** [bridgecrewio/checkov#5487]
**Describe the issue**

Graph check CKV2_AWS_5 fails when connected resource type of `aws_appstream_fleet` is used. This check should pass when a security group is attached to an `aws_appstream_fleet`.

**Examples**
```terraform
resource "aws_security_group" "this" {
  name        = "allow_tls"
  vpc_id      = aws_vpc.main.id
}

resource "aws_appstream_fleet" "test_fleet" {
  name = "test-fleet"
  vpc_config {
    subnet_ids = [aws_security_group.this.id]
  }
}
```

**Desktop (please complete the following information):**
 - Checkov Version [2.3.366]

**Additional context**
Add any other context about the problem here (e.g. code snippets).

Connected resource types should be updated: https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml#L14

**Comment by gruebel** [comment]
Hey @abondrndc thanks for reaching out.

Makes sense, I think you are example is incorrect, because it should be 😉 

```hcl
resource "aws_security_group" "this" {
  name        = "allow_tls"
  vpc_id      = aws_vpc.main.id
}

resource "aws_appstream_fleet" "test_fleet" {
  name = "test-fleet"
  vpc_config {
    security_group_ids = [aws_security_group.this.id]
  }
}
```

Are you interested in contributing the needed change?
