### ISSUE TITLE
Check missing for RDS parameter_group using SSL/TLS?

### ISSUE THREAD

**Issue by dbbc96** [bridgecrewio/checkov#5494]
It would appear that there are not currently any checks to whether or not TSL/SSL is enforced in RDS in parameter groups.  I was looking here:  https://www.checkov.io/5.Policy%20Index/terraform.html

I did see one for Redshift but not finding any other references for "parameter_group" and TLS/SSL enforcement.  Please let me know if i missed it somewhere.

**Comment by gruebel** [comment]
hey @dbbc96 thanks for reaching out.

I double checked and I think you are right. We have it for a couple of other services, but not for RDS 😱

**Comment by JamesWoolfenden** [comment]
@dbbc96  what parameters do you want to ensure? rds.force_ssl is true? This the default so wed be looking for false? If we do that shall i also add a check that ssl_min_protocol_version is TLSv1.2 while were about it? WDYT?

**Comment by dbbc96** [comment]
@JamesWoolfenden so it will depend on the engine.  for instance mysql is using "require_secure_transport", postgres uses "rds.force_ssl", MSSQL also uses "rds.force.ssl"

but it should check whether it set to "1" or not.  which i believe is not set by default.

**Comment by ArjunMenon-bit** [comment]
@dbbc96  I would like to contribute to this issue. Can you share where exactly you saw the different parameter values that are used by the respective RDS engines. I got the code working for postgres, applying the same logic for others should do it I believe.

**Comment by ArjunMenon-bit** [comment]
@gruebel Could you please assign this issue to me?

**Comment by dbbc96** [comment]
@ArjunMenon-bit 

think you can find them here:  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group

**Comment by terra-conq** [comment]
Is there a branch created for this issue and are you working on this?

**Comment by martu-sf** [comment]
not stale
