### ISSUE TITLE
OpenTF support

### ISSUE THREAD

**Issue by skyzyx** [bridgecrewio/checkov#5501]
https://opentf.org/announcement

We want to understand how Checkov is affected by the OpenTF announcement, and what the plans for support are moving forward.

**Comment by gruebel** [comment]
hey @skyzyx thanks for reaching out.

We currently don't expect any drawback of using the Terraform fork, because we just scan `*.tf` files. This can become different in the future, if the syntax should diverge and then we will have to check what the effort will be to support both.

**Comment by skyzyx** [comment]
Thank you for your answer.

From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

**Comment by gruebel** [comment]
1. since we don't leverage actual Terraform CLI, we are not affected by any bugs, at least till now we weren't 😄 
2. As long as the syntax is the same, there is no need to test it.
3. This highly depends on the changes. So, time will tell till the first OpenTF-only features arrives.
