### ISSUE TITLE
Permission boundary consideration for ckv_aws_62  

### ISSUE THREAD

**Issue by pingoleon108** [bridgecrewio/checkov#5502]
**Describe the issue**
Is Ckv_aws_62  ( https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/IAMAdminPolicyDocument.py ) Considering effective permissions ?
I meant, are we considering permission boundaries here? 
Terraform resource: "aws_ssoadmin_permissions_boundary_attachment" 

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowAllActionsOnAllResources",
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```
with following permission boundary
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowReadOnlyAccessToTestBucket",
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::test/*",
        "arn:aws:s3:::test"
      ]
    }
  ]
}
```
should pass.
**Version (please complete the following information):**
 - all Checkov Version

**Comment by gruebel** [comment]
hey @pingoleon108 thanks for reaching out.

Currently there is no plan in supporting permission boundary.
