### ISSUE TITLE
Cloudformation Graph: Ability to pick the value from another config file and not the "Default" for parameter references

### ISSUE THREAD

**Issue by cbhat-ie** [bridgecrewio/checkov#5542]
Framework: Cloudformation (Graph)

Current behaviour: Checkov picks the "Default" value for a parameter if present in the file.
Requirement: Resolve the parameter with the value from another config file if provided and not pick the "Default" value.

Is there some way to do this today? If not, what other options is there for scanning a template/CFN file which has "Default" defined for parameters but should consider the values provided in another config file?

Use case: For teams building CFN templates for different use cases/services, to send both the template files and the file with parameter values for a Checkov scan to find IaC misconfigurations.

**Comment by gruebel** [comment]
Hey @cbhat-ie thanks for reaching out.

This is correct, we don't support an external file, like in Terraform the tfvars file, for CFN templates. We only look at the default values of the parameters.

**Comment by cbhat-ie** [comment]
Okay, thanks for confirming @gruebel 

Is there any plans to support this in future? This would bring a lot of flexibility to integrate Checkov scans, especially for the teams generating and releasing CFN templates.

**Comment by gruebel** [comment]
I wouldn't say no, but there is no real official way to do it, which makes it a bit more complicated to agree on something, but I would probably go for supporting a JSON file, which would also work with the official `--parameter-overrides` flag from the AWS CLI, WDYT?
