### ISSUE TITLE
CKV2_AWS_18 fails with efs and aws backup modules chained

### ISSUE THREAD

**Issue by nomeelnoj** [bridgecrewio/checkov#5544]
**Describe the issue**

When chaining EFS and AWS Backup modules together, check `CKV2_AWS_18` fails.

**Examples**
We use modules for everything, and when values need to be passed around we call multiple modules, using outputs from one as inputs to another. We try to follow best practice as much as possible, so the states we have that call our EFS module most often also call our AWS Backups module.  However, with a recent upgrade and the release of this check, we are now getting a failure.  

Our modules are quite involved with most all variables being complex types and we use `for_each` and dynamics frequently.  In testing, the same is true with a very simplified version of the code as shown below.

- Backup Module
```hcl
# ./backup/main.tf
resource "aws_backup_plan" "default" {}

resource "aws_backup_selection" "default" {
  plan_id   = aws_backup_plan.default.id
  resources = var.resources
}

variable "resources" {}
```
- EFS module
```hcl
# ./efs/main.tf
resource "aws_efs_file_system" "default" {}

resource "aws_efs_mount_target" "default" {
  file_system_id = aws_efs_file_system.default.id
}

output "object" {
  value = aws_efs_file_system.default
}
```
- State calling the modules
```hcl
# ./run/test.tf
module "efs" {
  source = "../efs"
}

module "backup" {
  source = "../backup"

  resources = [
    module.efs.object.arn
  ]
}
```

The outcome of the above when running checkov is:

```
╰─ checkov --framework terraform -d run -c CKV2_AWS_18


Check: CKV2_AWS_18: "Ensure that Elastic File System (Amazon EFS) file systems are added in the backup plans of AWS Backup"
	FAILED for resource: module.efs.aws_efs_file_system.default
	File: /efs/main.tf:1-1
	Guide: https://docs.paloaltonetworks.com/content/techdocs/en_US/prisma/prisma-cloud/prisma-cloud-code-security-policy-reference/aws-policies/aws-general-policies/ensure-that-elastic-file-system-amazon-efs-file-systems-are-added-in-the-backup-plans-of-aws-backup.html

		1 | resource "aws_efs_file_system" "default" {}

```

**Version (please complete the following information):**
 - 2.4.30

**Additional context**
The code above is streamlined to keep the issue example small, but regardless of the configuration values, nested in `for_each` or not, containing more arguments or not, etc., this check fails when the EFS and AWS Backup are created in two different modules.

So far, the only way I have been able to get  this configuration to pass the check is to call the `efs` resources (no module) right along side the `backup` module, `aws_backup` resources alongside the `efs` module.  If one of the two is a module and the other is using native `resource` blocks, the check passes.  But if both are modules, it fails.

**Comment by gruebel** [comment]
Hey @nomeelnoj thanks for reaching out.

This is correct, we currently only support a single reference either from or to a module, but not from module to module looking from a root. The reason is we don't track resource -> output -> variable -> resource chains.
