### ISSUE TITLE
Check "CKV2_AZURE_7" on Terraform resource "azurerm_sql_server" needs to be created for Terraform resource "azurerm_mssql_server"

### ISSUE THREAD

**Issue by tdefise** [bridgecrewio/checkov#5553]
**Describe the issue**

azure_sql_server will be deprecated in new version of terraform

![image](https://github.com/bridgecrewio/checkov/assets/36169753/349f5d3c-45d3-4928-b0f6-5d47e6a1c766)

**Examples**

Not applicable

**Version (please complete the following information):**

Not applicable

**Additional context**

Explained in the "Describe issue" section

**Comment by tdefise** [comment]
In order to solve this issue, does we need to "simply" add the "azure_mssql_server" to:

- resource_types
- values

![image](https://github.com/bridgecrewio/checkov/assets/36169753/df20cc7f-839d-4f07-8a68-bb788d03f479)

Also, note that

![image](https://github.com/bridgecrewio/checkov/assets/36169753/5f2e5ce2-c37b-4297-97e6-432f316d3d24)

**Comment by gruebel** [comment]
hey @tdefise thanks for reaching out.

I think check `CKV2_AZURE_27` does what you are asking for, because it looks for an AzureAD Admin login.

**Comment by tdefise** [comment]
Hi @gruebel,

Those are not exactly the same:

- **CKV2_AZURE_7**: Checks if an Azure Active Directory Admin is configured
- **CKV2_AZURE_27**: Checks if Azure AD authentication is enabled for Azure SQL

As describe [here](https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-configure?view=azuresql&tabs=azure-powershell), an Azure Active Directory Admin is required in order to enable Azure AD authentication

**Comment by gruebel** [comment]
The name is not exactly the same, but the way to configure it on the `mssql` resource is exactly what `CKV2_AZURE_27` checks for 🙂

**Comment by gruebel** [comment]
Feel free to reach out, if you have more questions.
