### ISSUE TITLE
--soft-fail and --hard-fail-on MEDIUM flags no behaving as expected in pre-commit hook

### ISSUE THREAD

**Issue by CaspervdKerk** [bridgecrewio/checkov#5560]
**Describe the issue**
When running terraform_checkov pre-commit hook without any fail flags, any matching rule will result in a failed output.
However when the --soft-fail and --hard-fail-on MEDIUM flags are enabled, everything passes. Even when violating a HIGH severity rule on purpose.
During testing we violate the [CKV_AZURE_104](https://docs.bridgecrew.io/docs/ensure-that-azure-data-factory-public-network-access-is-disabled) on purpose, which is a HIGH severity check. Checkov passes over this check when the `--soft-fail` and `--hard-fail-on MEDIUM` flags are enabled.

**Examples**
<details><summary>main.tf</summary>

```bash
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.28.0"
    }
  }
}

resource "azurerm_data_factory" "azure_data_factory" {
  name                   = var.factory_name
  resource_group_name    = var.resource_group_name
  location               = var.location
  public_network_enabled = true

  identity {
    type = "SystemAssigned"
  }

  lifecycle {
    ignore_changes = [tags]
  }
}
```
</details>
Above code snippet should violate CKV_AZURE_104, when using the `terraform_checkov` pre-commit hook. It does when the `--soft-fail` and `--hard-fail-on MEDIUM` are not passed. However, when these flags are enabled all checks are passed.

**Version (please complete the following information):**
 - Checkov Version 2.4.30
 - pre-commit 3.4.0
 - Terraform v1.5.7

**Additional context**
Please also view the issue I have raised on the [pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform/issues/568) repo. It was recommended there that I also raise this issue here.

**Comment by gruebel** [comment]
hey @CaspervdKerk thanks for reaching out.

Are you using `checkov` with an API key, when using those flags?

**Comment by CaspervdKerk** [comment]
Hey @gruebel ,
No. Checkov was installed using brew and no further configuration has been done.

**Comment by gruebel** [comment]
ok, got it.

Severities only work with an API key, that's why it doesn't work as expected.

**Comment by maximilianconrad** [comment]
Hey @gruebel,
would you mind adding this information to the documentation? I just spend two hours to troubleshoot the exact same issue :pensive:
