### ISSUE TITLE
Azure Cache for Redis - Ensure "Standard replication" is enabled

### ISSUE THREAD

**Issue by tdefise** [bridgecrewio/checkov#5574]
**Describe the issue**
It seems that there are no Checkov checks related to the best practice of ensuring that "Standard Replication" is enabled by having at least the "Standard" Tier [azurerm_redis_cache](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/azurerm_redis_cache)

**Examples**

````hcl
resource "azurerm_redis_cache" "example" {
  name                = "example-cache"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  capacity            = 2
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"

  redis_configuration {
  }
}
````

**Version (please complete the following information):**
 - N.A.
 
 
**Additional context**

![image](https://github.com/bridgecrewio/checkov/assets/36169753/6b8cf1f9-99cf-4613-aecd-e7fec7650583)

Azure Cache for Redis has a high availability architecture that ensures that managed instance are functioning, even when outages affect the underlying virtual machines (VMs). Whether the outage is planned or unplanned outages, Azure Cache for Redis delivers greater percentage availability rates than what's attainable by hosting Redis on a single VM.

An Azure Cache for Redis in the applicable tiers runs on a pair of Redis servers by default starting from the "Standard Tier".
The two servers are hosted on dedicated VMs. Open-source Redis allows only one server to handle data write requests.

This can be seen in the Azure Portal

![image](https://github.com/bridgecrewio/checkov/assets/36169753/1d5244e0-d667-4872-8d02-64927376ee69)

**Comment by tdefise** [comment]
This is still required

**Comment by Saarett** [comment]
Hi @tdefise , thanks for reaching out.
Would you like to contribute the new checks? It would be very helpful. 🙂
For now, I’m going to close this issue because I see no engagement for this request.
