### ISSUE TITLE
Azure Kubernetes Service - Ensure that the AKS cluster encrypt temp disks, caches, and data flows between Compute and Storage resources

### ISSUE THREAD

**Issue by tdefise** [bridgecrewio/checkov#5586]
**Describe the issue**
It seems that there are no checks in order to ensure that "Encryption at Host" is enabled or not.

**Examples**

````hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"
  enable_host_encryption  = true

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Production"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
  enable_host_encryption  = true

  tags = {
    Environment = "Production"
  }
}

````

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**

With host-based encryption, the data stored on the VM host of your AKS agent nodes' VMs is encrypted at rest and flows encrypted to the Storage service. This means the temp disks are encrypted at rest with platform-managed keys. The cache of OS and data disks is encrypted at rest with either platform-managed keys or customer-managed keys depending on the encryption type set on those disks.

By default, when using AKS, OS and data disks use server-side encryption with platform-managed keys. The caches for these disks are encrypted at rest with platform-managed keys. You can specify your own managed keys following [Bring your own keys (BYOK) with Azure disks in Azure Kubernetes Service](https://learn.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys). The caches for these disks are also encrypted using the key you specify.

Host-based encryption is different than server-side encryption (SSE), which is used by Azure Storage. Azure-managed disks use Azure Storage to automatically encrypt data at rest when saving data. Host-based encryption uses the host of the VM to handle encryption before the data flows through Azure Storage.

Note that on the documentation of Terraform, it is seens as "Preview".

![image](https://github.com/bridgecrewio/checkov/assets/36169753/54d1bce1-c867-4fe0-bb56-e644c8edf1d2)

However, it has been set as "General availability" on May 25, 2021

![image](https://github.com/bridgecrewio/checkov/assets/36169753/69e77141-c25e-4a9d-8df2-c896197cb086)

**Comment by gruebel** [comment]
hey @tdefise thanks for the PR.

I'm curious about it, if you can deploy it just by enabling it via TF or you need todo something else, because the docs indicate it as a preview feature as you stated, even it is already GA for some time.

**Comment by tdefise** [comment]
Hi @gruebel,

I don't find something related to that **in the portal**

![image](https://github.com/bridgecrewio/checkov/assets/36169753/7b9aa16d-5cc4-4dcf-a76e-f202e162511a)

However, the documentation point to some I don't manage and don't have access to, so I cannot answer to your question.

**Comment by gruebel** [comment]
ok, gotcha. let's add it as a check.
