### ISSUE TITLE
Checkov does not run checks, issues no errors, when deleting resources in Terraform plan.

### ISSUE THREAD

**Issue by eap** [bridgecrewio/checkov#5587]
I'm setting up Checkov as a presubmit test for a GitHub config management repo. When creating resources checkov will run checks as expected (including my custom check to guard against deletion). But when deleting resources checkov runs no checks at all and just reports success with no further information.

Here is an example of what the run looks like when evaluating a plan that deletes all my resources.
```
$ checkov --external-checks-dir tf/checks -f tf/plan.delete.json
[ arm framework ]: 100%|████████████████████|[1/1], Current File Scanned=tf/plan.delete.json
... more loading and pretty ascii art omitted for brevity ...

By bridgecrew.io | version: 2.4.47
Update available 2.4.47 -> 2.4.48
Run pip3 install -U checkov to update



$
```

If I make a plan against the same terraform project before I delete my resources it will run all of the checks including my custom check.
```
$ checkov --external-checks-dir tf/checks -f tf/plan.nochange.json
[ arm framework ]: 100%|████████████████████|[1/1], Current File Scanned=tf/plan.nochange.json
... more loading and pretty ascii art ...

By bridgecrew.io | version: 2.4.47
Update available 2.4.47 -> 2.4.48
Run pip3 install -U checkov to update

terraform_plan scan results:
Passed checks: 3, Failed checks: 3, Skipped checks: 0

Check: CKV_GIT_3: "Ensure GitHub repository has vulnerability alerts enabled"
	PASSED for resource: module.managed_github_repo["test"].github_repository.repository
Check: CKV_GIT_1: "Ensure GitHub repository is Private"
	PASSED for resource: module.managed_github_repo["test"].github_repository.repository
Check: DELETEREPO_GITHUB: "Ensure GitHub repository is not deleted"
	PASSED for resource: module.managed_github_repo["test"].github_repository.repository
Check: CKV_GIT_5: "GitHub pull requests should require at least 2 approvals"
	FAILED for resource: module.managed_github_repo["test"].github_branch_protection.protect_default_branch
```

Here's a heavily abbreviated version of my terraform plan that results in no checks being run. Note that there is a repository in the prior state and there's a repository in the resource changes section with `"change": { "actions": [ "delete"` that I am filtering for.
```
{
  "format_version": "1.2",
  "terraform_version": "1.5.7",
  "variables": {
    "github_token": {
      "value": "obviously-redacted-secret-key-value"
    }
  },
  "planned_values": {
    "root_module": {}
  },
  "resource_changes": [
    {
      "address": "module.managed_github_repo[\"test\"].github_repository.repository",
      "module_address": "module.managed_github_repo[\"test\"]",
      "mode": "managed",
      "type": "github_repository",
      "name": "repository",
      "provider_name": "registry.terraform.io/integrations/github",
      "change": {
        "actions": [
          "delete"
        ],
        "before": {
          ... a bunch of stuff
        },
        "after": null,
        "after_unknown": {},
        "before_sensitive": {
          ... more stuff
        },
        "after_sensitive": false
      },
      "action_reason": "delete_because_no_module"
    },
  ],
  "prior_state": {
    "format_version": "1.0",
    "terraform_version": "1.5.7",
    "values": {
      "root_module": {
        "child_modules": [
          {
            "address": "module.managed_github_repo[\"test\"]",
            "resources": [
              {
                "address": "module.managed_github_repo[\"test\"].github_repository.repository",
                "mode": "managed",
                "type": "github_repository",
                "name": "repository",
                "provider_name": "registry.terraform.io/integrations/github",
                "schema_version": 1,
                "values": {
                  ... config
                },
                "sensitive_values": {
                  ... config
                }
              },
            ],
          }
        ]
      }
    }
  },
  "configuration": {
    "provider_config": {
      "github": {
        "name": "github",
        "full_name": "registry.terraform.io/integrations/github",
        ... config
      }
    },
    "root_module": {
      "module_calls": {
        "managed_github_repo": {
          "source": "./v1/managed_github_repo",
          "expressions": {
            ... expressions
          }
        }
      }
    }
  },
  "relevant_attributes": [
    {
      "resource": "module.managed_github_repo[\"test\"].github_repository.repository",
      "attribute": [
        "node_id"
      ]
    }
  ]
}
```

For completeness; here's my custom "DELETEREPO_GITHUB" rule.
```
metadata:
  name: "Ensure GitHub repository is not deleted"
  id: "DELETEREPO_GITHUB"
  category: "GENERAL_SECURITY"
definition:
  cond_type: attribute
  resource_types:
    - github_repository
  attribute: __change_actions__
  operator: not_contains
  value: delete
  ```

**Comment by gruebel** [comment]
hey @eap thanks for reaching out.

This is correct, we ignore completely deleted resources at the moment, because they would currently be mixed up with the normal resources and therefore you would get all kinds of check results for a deleted resource, which you probably don't want to have.

This was raised in the past, but we still didn't find a good way on handling it yet.

**Comment by eap** [comment]
@gruebel 
> This is correct, we ignore completely deleted resources at the moment,

I'm a little confused, this issue https://github.com/bridgecrewio/checkov/issues/3148 and this pull request https://github.com/bridgecrewio/checkov/pull/3231 seem to imply otherwise. I got most of my custom action from one of the tests in that change.

Was this reverted or is there some other blocker to this feature? Obviously avoiding the deletion of our github repos (I'll be using planned imports to import quite a few) is a big deal and a blocker for us using terraform; if I cannot use checkov I'll have to write up a custom validator obviously I'd prefer the framework route cause of all other other features and benefits brought to the table.

**Comment by eap** [comment]
Thanks for the info. I just tested locally this and it works as you've described. I'll close this issue since I assume that if you wanted to track the complete-deletion question you'll do it in a more descriptive feature bug.

**Comment by aaron-lunsford-even** [comment]
@gruebel - Is there a bug/issue/feature to track the detection of resource deletion, rather than replacement? The behavior outlined in this issue has not changed as of today  (version `3.2.220`).

Additionally, there are multiple examples in the checkov documentation on how to detect resource deletion, but none of them are caveated with what you have outlined in your comments.

I couldn't find an issue so I'm happy to create one if none exists, as I think this is an important feature to add.

**Comment by tarfeef101** [comment]
Agreed, we have the ability to detect if the action for a resource is "just nuke it" or resource replacement. So it should be fairly easy to add some by-default logic to say "don't run a check against pure deletes unless the class explicitly declares that to be okay"

This can also be added as a breaking change and put into each check, of course, whatever is preferred is up to maintainer's discretion
