### ISSUE TITLE
junit ouptut format - add context information

### ISSUE THREAD

**Issue by jglapa** [bridgecrewio/checkov#559]
**Is your feature request related to a problem? Please describe.**
We're using CI to run the cli checkov analysis. It works good but with bigger code bases it takes a lot of scrolling to find the actually violation. 
We started using junit report which can be parsed and presented in a nicer form.
![image](https://user-images.githubusercontent.com/742104/92414400-5db65a00-f154-11ea-8730-f44cd97baf7f.png)

The problem now is how to locate the violation. The junit report contains no context information where exactly should we look into. We end up again using grep/find

**Describe the solution you'd like**
It would be great if the junit report contained context information where exactly did the violation occur.

**Describe alternatives you've considered**
One option would be to use multiple output at the same time cli+junit but this doesn't work as expected since junit doesn't create a dedicated ouptut file but rather you have to pipe it yourself e.g.

`checkov  -o junitxml > analysis.xml`

**Comment by tantweiler** [comment]
Hello! 

We have exactly the same use case and would be more than happy if the violated policy IDs would be visible in the junit reports. 

Thank you!

**Comment by schosterbarak** [comment]
Hi @tantweiler @jglapa can you supply a mock of the suggestion?

**Comment by tantweiler** [comment]
Hi @schosterbarak! Just an example --> It would be ok for me if I could see the ID (e.g. CKV_AZURE_6) in the suite column:

 
![image](https://user-images.githubusercontent.com/48676838/104896142-07b1b880-5977-11eb-8f22-e8d7749fc4ee.png)

**Comment by schosterbarak** [comment]
as concatenated value? 

Btw what system is the screenshot from?

**Comment by tantweiler** [comment]
Hi @schosterbarak,

That is GitLab! Concatenated value should work I would say.

**Comment by schosterbarak** [comment]
I think that be done by adding modifying the following line:
https://github.com/bridgecrewio/checkov/blob/feea72d817db0f0a1fbb9689164858f356325213/checkov/common/output/report.py#L117
to have `record.check_id` concatenated as string. 

I haven't done the testing, if you want to give it a try - we would accept a PR there.

**Comment by AFriemann** [comment]
I've been playing around with this a little together with tfsec

What's odd is that using warnings-ng to integrate this with github checks it detects findings from tfsec but none from checkov.

the format also differs slightly

tfsec:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tfsec" failures="1" tests="1">
	<testcase classname="/ec2/security_groups.tf" name="[AWS008][WARNING]" time="0">
		<failure message="Resource &#39;aws_security_group.alb&#39; defines a fully open ingress security group." type="">/ec2/security_groups.tf:11&#xA;       8 |     from_port   = 80&#xA;       9 |     to_port     = 80&#xA;      10 |     protocol    = &#34;tcp&#34;&#xA;      11 |     cidr_blocks = [&#34;0.0.0.0/0&#34;] # tfsec:ignore:AWS009&#xA;      12 |   }&#xA;      13 | &#xA;      14 |   ingress {&#xA;&#xA;See https://tfsec.dev/docs/aws/AWS008/ for more information.</failure>
	</testcase>
</testsuite>
```

checkov:

```xml
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="16" tests="924" time="0.0">
	<testsuite disabled="0" errors="0" failures="0" name="Ensure all data stored in the EBS is securely encrypted" package="checkov.terraform.checks.resource.aws.EBSEncryption" skipped="0" tests="2" time="0">
		<testcase classname="checkov.terraform.checks.resource.aws.EBSEncryption" file="/EBS/main.tf" name="terraform Ensure all data stored in the EBS is securely encrypted aws_ebs_volume.this"/>
	</testsuite>
</testsuites>
```

right now it's basically impossible to figure out which module the results relate to in Jenkins.

**Comment by ketumbra** [comment]
from screenshots above it seems to me that jenkins is not presenting the `file` attribute but reading the content of the tag. I don't think that's standard...

I would also like to see the check ID presented though, as it would make skipping a lot easier.

Further - it would be good if there was some docs for each check that could be linked to, justifying the reason for the check and acceptable use cases for skipping it. tfsec have done this really well.
