### ISSUE TITLE
--check and --skip-check lists defined in files

### ISSUE THREAD

**Issue by jglapa** [bridgecrewio/checkov#560]
**Is your feature request related to a problem? Please describe.**
We have a need to either define multiple `skip checks` or multiple `checks`. Would be great if we could load them from a file and not define explicitly in the cli param

**Describe the solution you'd like**
`--skip-check-list /path/to/file --check-list /path/to/file`

**Comment by angatha** [comment]
If you want to skip multiple test or just specify multiple you can separate them via a comma: `checkov --check "CKV_AWS_1,CKV_AWS_2"` or `checkov --skip-check "CKV_AWS_1,CKV_AWS_2"`

Otherwise there is #299 which I currently working on in #555. Feel free to comment on #555.

**Comment by jglapa** [comment]
> @jglapa if you want to skip multiple test or just specify multiple you can separate them via a comma: `checkov --check "CKV_AWS_1,CKV_AWS_2"` or `checkov --skip-check "CKV_AWS_1,CKV_AWS_2"`
> 
> Otherwise there is #299 which I currently working on in #555. Feel free to comment on #555.

yes, configuration via file will do the job too! thx

**Comment by konek3** [comment]
Something like .checkovingore would also come in handy!

**Comment by angatha** [comment]
Maybe to give you an update about that. In #555 there you can find two files (one [yaml](https://github.com/bridgecrewio/checkov/blob/bddec7af6be35e07fe0baafe372f3835ab54f1f0/tests/configs/full.yaml) and one [ini](https://github.com/bridgecrewio/checkov/blob/bddec7af6be35e07fe0baafe372f3835ab54f1f0/tests/configs/full)) containing example configuration. Is that what you want or would you have it in a different way?

It is not just for --check and --skip-check but moving as much of the cli options into a config file.

**Comment by derhally** [comment]
Curious if the PR for this will be accepted.   Would like to roll out checkov across multiple repos and have each repo define their own settings.

**Comment by larryboymi** [comment]
I would like something similar to the skip/suppress annotation functionality to be possible via CLI flag or external file as well. My use-case is enabling developers to submit terraform which must comply with policy (and adhering to approved exceptions to policy).

**Comment by tronxd** [comment]
> I would like something similar to the skip/suppress annotation functionality to be possible via CLI flag or external file as well. My use-case is enabling developers to submit terraform which must comply with policy (and adhering to approved exceptions to policy).

Please refer to the `--check` and `--skip-check` flags. Would those satisfy your requirements?

**Comment by larryboymi** [comment]
@tronxd do those let you specify which resources/modules to skip the check for?

**Comment by tronxd** [comment]
> @tronxd do those let you specify which resources/modules to skip the check for?

@larryboymi you can use the `--framework` / `--skip-framework` flags for restrictions on specific IaC type(s). The --check flag restrict specific checks on specific resource types, so tweaking it to scan only specific resource types is feasible. Explicit resource types granularity is not supported yet, but that's a great idea. 
@schosterbarak WDYT?

**Comment by larryboymi** [comment]
@tronxd yeah we track exceptions to policy at a granular level, and bring those exceptions into consideration during our CI/CD, so would like to incorporate an ability to specify which resources to allow the check to find new issues still. 

Letting the teams that submit the terraform annotate their own code doing the same might cause us some problems if it was abused.

**Comment by larryboymi** [comment]
To further illustrate the point I was trying to make, I established a very simple initial data contract for exceptions, such as:

```json
[{
  "policyId": "CKV_AWS_62",
  "comment": "Spike testing suppression",
  "resourceType": "aws_iam_policy",
  "resourceName": "iac_poc"
}]
```

Now we just need a mechanism (currently) to get those suppressions in-line (although my preference would lean towards a new mechanism where skips could be passed automatically to the filter where they're utilized). However, the current model can be processed by a shell script such as:

```sh
#!/usr/bin/env bash

grep_result=$(grep --exclude=process_exceptions.sh --exclude-dir=.git --exclude-dir=.terraform -r ".*checkov:skip=.*" .)

if [ $? -eq 1 ]; then
  echo "Phew, nobody messes with checkov."
else
  echo "Uh oh, someone is already trying to get by checkov."
  exit 1
fi

exceptions=$(cat exceptions.json | jq -r '.[] | @base64')

for exception in $exceptions; do
  _jq() {
    echo ${exception} | base64 --decode | jq -r ${1}
  }
  policyId=$(_jq '.policyId')
  comment=$(_jq '.comment')
  resourceType=$(_jq '.resourceType')
  resourceName=$(_jq '.resourceName')
  insert="#checkov:skip=$policyId:$comment"
  match='(^resource[ \t]*\"'"$resourceType"'\"[ \t]*\"'"$resourceName"'\".*$)'

  if [ "$(uname)" == "Darwin" ]; then
    LC_ALL=C find . -type f -not -path '*/\.*' -exec sed -i '' -E "s/$match/\1\n$insert/i" {} +
  else
    LC_ALL=C find . -type f -not -path '*/\.*' -exec sed -r "s/$match/\1\n$insert/i" {} +
  fi
done
```

This would need to be paired with a CLI flag to disable in-line suppressions (for audits sake an enterprise needs to track such security exceptions to established policy, things like approvals, requestor, requested date, expiration, last update, etc). I feel like the data retrieval on the JSON can be handled outside of checkov, and that checkov itself would not need all of this data, since it is purely doing the exception handling, but it would need a way to be passed in as a JSON blob or file. 

Note: this is just a preliminary analysis, something such as `moduleName` might also be necessary in the JSON to help distinguish between similar named resources at different levels, etc.

**Comment by Marcus-James-Adams** [comment]
I too think a .checkovignore file would be useful as we too have multiple repos/folders with different requirements.

Specifying each one individually via the cli is not an option when you are passing through to automated co/cd pipelines in the above scenario

**Comment by schosterbarak** [comment]
Thanks guys. @nimrodkor and @tronxd will work on adding a "baseline" file - inspired by yelp/detect-secrets to have that option

**Comment by larryboymi** [comment]
In addition, I am trying to figure out how a skip would work in a remote module (git source) scenario. Currently I'm using something like the above script to add in the comment suppressions, but while this module is downloaded and placed into the `.terraform` directory, I'm not sure that is checked during the "plan enrichment"/ #1221 flag checking. 

After a successful `terraform init` I go in and comment the code (which I know is not the greatest operational plan, and also indicative of the desire for the suppress via file functionality requested above), but so far it isn't working.

**Comment by elvis2** [comment]
> 

Love your sense of humor @larryboymi!

**Comment by larryboymi** [comment]
> 
> Love your sense of humor @larryboymi!

No reason work can’t be fun 🤩. I would have likely reworded it in production use lol

**Comment by iheanachochukwu** [comment]
Is there a roadmap to introduce .checkovignore file soon.
