### ISSUE TITLE
Missing bicep inline skip

### ISSUE THREAD

**Issue by gp-davidelettieri** [bridgecrewio/checkov#5602]
**Describe the issue**
It looks like there is no way to skip a policy inline in a bicep file. At least it is not documented. 

**Examples**
None

**Version (please complete the following information):**
 - Latest doc version https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html

**Additional context**
None

**Comment by gruebel** [comment]
hey @gp-davidelettieri thanks for reaching out.

It is identical to the Terraform one, that's why no special documentation was added.

ex.
https://github.com/bridgecrewio/checkov/blob/f3a0ba6a061cda05bd97d254c18d66a63b1822da/tests/bicep/examples/playground.bicep#L84-L92

**Comment by gp-davidelettieri** [comment]
Thanks for the quick response. I don't know how but I was sure to have tried that. 

Anyhow sample is clear and working. Thanks :)
