### ISSUE TITLE
Scanning multiple Directories with Docker image

### ISSUE THREAD

**Issue by serxansherif** [bridgecrewio/checkov#561]
According to the documentation, I can scan terraform files located in one directory by using the Docker image. I have multiple directories that store modules and other tf files. I would scan these directories with a single command. Does possible to scan multiple directories by using the Docker image?

**Comment by metahertz** [comment]
Hi @serxansherif 
So we depreciated the multiple `-d` / `--directory` options in Checkov as it was messing up a number of the reporting formats and paths, this will also apply to the docker image, which is just passing args to the checkov binary.

If you did want to scan multiple directories, while we'd recommend having different jobs per repository/directory scanned, you could use the fact that `-d` / `--directory` is recursive, so using docker to mount your files under a `/mounted/itema` and `/mounted/itemb` path, and running `checkov -d /mounted` would scan everything under both `itema` and `itemb` directories, as per the example below with a terragoat and cfngoat directories:

```
docker run -t -v /Users/matt/coderepo/terragoat/:/mounted/terragoat -v /Users/matt/coderepo/cfngoat/:/mounted/cfngoat bridgecrew/checkov --directory /mounted
```

Hope this answers your question?

**Comment by serxansherif** [comment]
Hi @metahertz 
Thanks for your clarification.
