### ISSUE TITLE
Support for terraform `try` function

### ISSUE THREAD

**Issue by shubham-dogra-pingsafe** [bridgecrewio/checkov#5614]
**Describe the issue**
Currently [try](https://developer.hashicorp.com/terraform/language/functions/try) function of terraform is not supported. 

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.
```
resource "aws_s3_bucket" "bucket" {
  bucket = try(var.bucket_name, "test")
  acl    = "private"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}
```
See the `bucket` key of `aws_s3_bucket` block generated by checkov
```
{
                "block_name_": "aws_s3_bucket.bucket",
                "block_type_": "resource",
                "label_": "resource: aws_s3_bucket.bucket",
                "id_": "aws_s3_bucket.bucket",
                "source_": "Terraform",
                "__end_line__": 9,
                "__start_line__": 1,
                "acl": "private",
                "bucket": "try(var.bucket_name,\"test\")",
                "tags": {
                    "Environment": "Dev",
                    "Name": "My bucket"
                }
            }
```

#### Expected
```
{
                "block_name_": "aws_s3_bucket.bucket",
                "block_type_": "resource",
                "label_": "resource: aws_s3_bucket.bucket",
                "id_": "aws_s3_bucket.bucket",
                "source_": "Terraform",
                "__end_line__": 9,
                "__start_line__": 1,
                "acl": "private",
                "bucket": "test",
                "tags": {
                    "Environment": "Dev",
                    "Name": "My bucket"
                }
            }
```
**Desktop (please complete the following information):**
 - OS: macos
 - Checkov Version : 2.3.214

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by shubham-dogra-pingsafe** [comment]
hi @gruebel any update on this?

**Comment by gruebel** [comment]
hey @shubham-dogra-pingsafe thasnk for reaching out.

Not sure, what kind of update you are looking for, but you are correct, we currently don't support the `try` function and there is plan on working it right now. We always welcome contribution.

**Comment by tsmithv11** [comment]
Now supported: https://github.com/bridgecrewio/checkov/pull/6043
