### ISSUE TITLE
Checkov has started reporting with inappropriate errors since Tuesday 

### ISSUE THREAD

**Issue by zameer712** [bridgecrewio/checkov#5620]
Below is the type of code we are using Since 2 years now 

1. Checkov scan was working completely fine until last week 
2. Suddenly our security tab started Reporting issues with Our Git Hash URL 
3. please check this issue the reason behind this errors
4. we are using tags for all the modules we are writing since an long time now 
5. Is their a way to leverage this issue without changing anything on Scan ?

![image](https://github.com/bridgecrewio/checkov/assets/102033066/b2874797-8652-48c1-b698-f8ef481882bd)

module "dnd_postgresql_server_flexi" {
  source                 = "git::https://github.com/<org-name>/<reponame>.git//infrastructure/modules/postgress-flexi-server-vnet?ref=v1.3.5"
  name                   = var.dnd_postgresql_server_name_flexi
  resource_group_name    = var.resource_group
  location               = var.location
  administrator_login    = "psqladmin"
  administrator_password = random_string.password_postgresql_dnd_server_flexi.result
  subnet_id              = module.postgresql_flexi_subnet.id
  private_dns_zone_id    = var.postgresql_private_dns_zone_id
  sku_name               = var.postgresql_flexi_sku_name
  tags                   = var.tags_pg_flexi
  dbversion              = var.postgresql_version
}

**Comment by gruebel** [comment]
hey @zameer712 thanks for reaching out.

The check was added 3 months ago and we are adding constantly new ones, so it expected you will see new findings with newer `checkov` versions. More info, why you should commit hashes and not tags, can be found [here](https://docs.bridgecrew.io/docs/terraform-module-sources-do-not-use-a-git-url-with-a-commit-hash-revision)
