### ISSUE TITLE
Azure Kubernetes Service - Ensure that a temporary name for rotation is set

### ISSUE THREAD

**Issue by tdefise** [bridgecrewio/checkov#5648]
**Describe the issue**
It seems that there are no checks which ensure that a "temporary name" as been set.
It is recommended to already set a "temporary name", so that when one of the following properties are changed, there are no issues

- enable_host_encryption
- enable_node_public_ip
- kubelet_config
- linux_os_config,
- max_pods
- node_taints
- only_critical_addons_enabled
- os_disk_size_gb
- os_disk_type
- os_sku
- pod_subnet_id
- snapshot_id
- ultra_ssd_enabled
- vnet_subnet_id
- vm_size, zones

**Examples**

````hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                    = "aksexamplewithprivatednszone1"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  dns_prefix              = "aksexamplednsprefix1"
  private_cluster_enabled = true
  private_dns_zone_id     = azurerm_private_dns_zone.example.id

    default_node_pool {
      name                         = "defaultpool"
      temporary_name_for_rotation  = "poolrotation"

  }  
}
````

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**
Already explained in the issue description

**Comment by gruebel** [comment]
hey @tdefise thanks for the suggestion, but I don't really see the security context with this setting. Most of our checks have a security aspect or are related to a benchmark, like CIS,NIST, etc.

**Comment by gruebel** [comment]
Sorry, don't see it having any security specific benefit. Such a behaviour exists in multiple different resources, where you have to set a name prefix otherwise you won't be able to update it, add a lifecycle policy, which enforce creation before deletion etc.

I'll keep the issue open, if there other opinions on it.
