### ISSUE TITLE
[Commit hash version] please accomodate our request for adding git tags to revisionhash.py

### ISSUE THREAD

**Issue by zameer712** [bridgecrewio/checkov#5650]
Hello Team,

Hope you are doing well

In our whole code we are using git tags for source code , please can you add git tags as well as an another check point to pass

Our repo is getting flooded with alerts from 2 to 886 directly please help 

Terraform module sources do not use a git url with a commit hash revision
High
Terraform module sources do not use a git url with a commit hash revision

![image](https://github.com/bridgecrewio/checkov/assets/102033066/51b47a74-10fe-4f0c-bd08-cc2e4c493741)

https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/module/generic/RevisionHash.py

https://github.com/bridgecrewio/checkov/pull/5651. -- PR Opened for tags addition please verify and merge the same

please add git tags as well as an additional check point to pass in above code

**Comment by gruebel** [comment]
hey @zameer712 thanks for reaching out.

The whole point of the check is to not use tags and instead use commit hashes, because tags are mutable and therefore they are vulnerable to supply chain attacks as under the guideline link described.
