### ISSUE TITLE
How to switch to alpine docker image

### ISSUE THREAD

**Issue by flydipen** [bridgecrewio/checkov#5666]
Hello
We are using old checkov docker image. Default os is debain. Even 2.0.163 default is debain. How to switch to alpine. 
Was trying to update image and clamav that's when I noticed. The reason it's still working without update since we build and store locally.

````dockerfile
FROM bridgecrew/checkov:2.0.163

RUN checkov --version

ENV CLAM_VERSION=0.103.2-r0

# Install clamav 
RUN apk add --no-cache clamav=$CLAM_VERSION clamav-libunrar=$CLAM_VERSION

ENTRYPOINT
````

**Comment by gruebel** [comment]
hey @flydipen thanks for reaching out.

We don't offer an Alpine version and we officially don't support Alpine at all. To my knowledeg it is possible, but then you need to create your own starting from an Alpine based image and install everything as needed.
