### ISSUE TITLE
Support Pulumi

### ISSUE THREAD

**Issue by thewizarodofoz** [bridgecrewio/checkov#568]
Great job on this tool guys.
Do you have plans to support [Pulumi](https://www.pulumi.com/)?

**Comment by schosterbarak** [comment]
@thewizarodofoz 
This is definitely doable :) 
And would accept a contribution. 
I'd love to discuss more and give guidance on it if you'd like at https://slack.bridgecrew.io/

**Comment by GaboFDC** [comment]
Hey, this would still be really nice to have? I could check about the guidance on how to implement, just a bit concerned on how big the scope will, I can contribute, but don't really have that much time.

**Comment by metahertz** [comment]
Hey @GaboFDC! Thanks for jumping in here to 'unstale' this issue :) Any time at all is much appreciated. I've added the help wanted tag too, lets see if we can create a little Pulumi team!

**Comment by paige-wdc** [comment]
Any updates on this? My org is migrating to Pulumi and it would be incredibly helpful for us.

**Comment by joshrichards37** [comment]
Would be really good to get this support added as my org are currently using Pulumi but haven't implemented any policy validation yet.

**Comment by spaceoddite** [comment]
hi, I would love to contribute as well. A starting point of exploration would be policy as code module of pulumi - https://www.pulumi.com/docs/guides/crossguard/

**Comment by WP-LKL** [comment]
I think we could reopen this, a highly requested feature X)

**Comment by jmcvetta** [comment]
It's a shame these obnoxious bots go around closing Issues that aren't actually closed.

**Comment by DaniWS** [comment]
Would be nice to have!

**Comment by dulakm** [comment]
Could this be reopened?

**Comment by juancho088** [comment]
Hi all, also we are starting to use Pulumi and I think the tool is getting a really decent traction, this should be reopened

**Comment by mdschuym** [comment]
Please reopen this issue :-)

**Comment by praneetloke** [comment]
@schosterbarak @metahertz I am curious. How is support for Terraform implemented in Checkov? I'd love to take a look.

**Comment by mjaggard** [comment]
Naughty bot.

@schosterbarak would you consider re-opening this issue so the Pulumi community can know if there's progress or to give up on Checkov.

**Comment by dano0b** [comment]
would be really nice to use for pulumi

**Comment by izaakschroeder** [comment]
+1 from me :)

**Comment by jtelleria-kirol** [comment]
+1
