### ISSUE TITLE
Breaking changes in 3.0.6

### ISSUE THREAD

**Issue by Nitive** [bridgecrewio/checkov#5689]
Flags `--no-guide`, `--skip-suppressions` and `--skip-fixes` were removed in 3.0.6 https://github.com/bridgecrewio/checkov/commit/3c970fea6452c1971832f4c1cfbb306f8d99308d

Should the major version be bumped for such cases?

I originally faced the problem when GitHub Action `bridgecrewio/checkov-action@v12`. Update there was also without major version bump

**Comment by gruebel** [comment]
https://github.com/bridgecrewio/checkov/blob/main/docs/1.Welcome/Migration.md#deprecated-flag-removal

Not sure what you mean with the GHA, those flags were not exposed there, so it is not a breaking change.

**Comment by Nitive** [comment]
@gruebel it was exposed via config file
