### ISSUE TITLE
GoogleCloudMySqlLocalInfileOff.py - local_inline check

### ISSUE THREAD

**Issue by panihin** [bridgecrewio/checkov#572]
**Describe the bug**
Ensure MySQL database 'local_infile' flag is set to 'off' for configuration:

`File "/usr/local/lib/python3.8/site-packages/checkov/terraform/checks/resource/gcp/GoogleCloudMySqlLocalInfileOff.py", line 28, in scan_resource_conf
    if (flag['name'][0] == 'local_infile') and (flag['value'][0] == 'on'):
TypeError: list indices must be integers or slices, not str`

`if attribute == 'database_flags':
                            for flag in conf['settings'][0]['database_flags']:
                                if (flag['name'][0] == 'local_infile') and (flag['value'][0] == 'on'):
                                    return CheckResult.FAILED`
Here type of flag is array, it causes to error.

**To Reproduce**
1. update TF with:
`resource "google_sql_database_instance" "mag_mysql" {
  project = "${var.project}"
  name = "${var.name}"
  region = "${var.region}"
  database_version = "MYSQL_5_7"
  count = "1"

  settings {
    user_labels {
      app = "xxx"
    }

  ...
    database_flags = [
      {
        name = "max_allowed_packet",
        value = "536870912"
      },
      {
        name = "lock_wait_timeout",
        value = "300"
      },     
    ]
  }`
2. Run cli command  'checkov -d tf -o cli --quiet'
3. See error

**Desktop (please complete the following information):**
 - OS:  iOS
 - Checkov Version 1.0.544

**Comment by GiladMark** [comment]
Fixed and merged in #577 
Thank you for that!
Now resolved
