### ISSUE TITLE
Possibility to check password dump or using a custom provider in Terraform

### ISSUE THREAD

**Issue by GoliTech** [bridgecrewio/checkov#5735]
**Describe the issue**
I am wondering if there is any built-in check or documentation to create a costume check to find the mentioned possible threat.

**Examples 1**
```
terraform {
        required_providers {
            evil = {
                source  = "evil/evil"
                    version = "1.0"
            }
        }
    }
provider "evil" {}
```
**Examples 2**
```
output "dotoken" {
  value = nonsensitive(var.do_token)
}
```

**Additional context**
Any help or reference will be highly appriciated

**Comment by gruebel** [comment]
hey @GoliTech currently there is no easy way to do it. We don't expose those blocks for creating a check. You would need to extend `checkov` itself to allow it.

**Comment by GoliTech** [comment]
@gruebel thanks for the reply.
so you mean it is not just writing a costume rule and Checkov itself needs to be extended to be able to scan these, right?

**Comment by gruebel** [comment]
yes, correct.
