### ISSUE TITLE
documentation for checkov policy evaluation logic 

### ISSUE THREAD

**Issue by junhu73** [bridgecrewio/checkov#5736]
Is there a documentation to illustrate the Checkov Policy evaluation logic? ([similar to the one - logic when AWS evaluates IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html)). Especially interested in the answers for the following questions:

- When must a resource be checked against every condition in a Checkov policy? 
- When a condition does not have a resource type defined for the checked resource, what are possible checked results and their dependency on the checked condition logic type (AND, OR, NOT)?
- Can connection type policy be used to check Terraform Plan file? If not, is there a way to connect two resources in the Terraform plan file in a Checkov policy?
      - Even with scanning Terraform *.tf files, if two resources are created in different modules (or at least one is created through another module), what is an example Checkov policy to connect these two resources?

Thank you.

**Comment by tsmithv11** [comment]
Hi @junhu73, I'd be happy to help, but I'm not clear on your questions.

1. The policies are defined such that if there is a resource of the type mentioned in the `supported_resources` (Python) and `supported_resources` in YAML policies must meet the conditions of the check.
2. Can you share an example of what you're talking about?
3. Yes, graph policies are applied against TF Plan files.
4. If Checkov is able to render the modules, it will be evaluated using the graph and connected resources.
