### ISSUE TITLE
The tittle of this rule is not correct

### ISSUE THREAD

**Issue by pingoleon108** [bridgecrewio/checkov#5745]
https://github.com/bridgecrewio/checkov/blob/b62d3c4cd049764d1ceedf4a34d3524272600e68/checkov/cloudformation/checks/resource/aws/BackupVaultEncrypted.py#L8

I'll posting the chatgpt explanation about this:

The BackupVaultEncrypted rule you've defined in Checkov (a tool for infrastructure-as-code analysis) is designed to ensure that AWS::Backup::BackupVault resources are encrypted at rest using a KMS Key (Key Management Service Key). However, based on the provided code, it seems that this rule does not specifically differentiate between a customer-managed KMS key (CMK) and an AWS-managed KMS key.

Here are the reasons:

    Inspection of the EncryptionKeyArn Key: The rule inspects the EncryptionKeyArn property of the AWS::Backup::BackupVault resource. This property can contain the ARN (Amazon Resource Name) of a KMS key, either a customer-managed key (CMK) or an AWS-managed key.

    Expectation of Any Value (ANY_VALUE): The rule expects the EncryptionKeyArn to have any value (ANY_VALUE). This means that the rule is satisfied as long as an ARN for the KMS key is specified, regardless of whether it's a customer-managed or an AWS-managed key.

To make a distinction between a customer-managed KMS key and an AWS-managed KMS key, you would need to implement additional logic in the rule. This logic should analyze the ARN of the KMS key and determine whether it is a customer-managed or an AWS-managed key. AWS-managed keys typically have a specific ARN format, while customer-managed keys have a slightly different format that includes a unique key identifier.

If your goal is to ensure that only customer-managed KMS keys (CMKs) are used for encryption, you would need to modify the get_expected_value function to specifically verify this type of key. This could involve validating the pattern of the KMS key ARN to ensure it matches the format of a CMK.

**Comment by gruebel** [comment]
hey @pingoleon108 thanks for reaching out.

Sadly I have to inform you, ChatGPT is wrong here. you can't differentiate between an AWS owned or Customer owned by the ARN. Feel free to try it out, create your own and let AWS create one and see the difference, because there is none 🙂
