### ISSUE TITLE
incorrect rule tittle

### ISSUE THREAD

**Issue by pingoleon108** [bridgecrewio/checkov#5746]
https://github.com/bridgecrewio/checkov/blob/b62d3c4cd049764d1ceedf4a34d3524272600e68/checkov/cloudformation/checks/resource/aws/S3Encryption.py#L8
The rule tittle is incorrect. The rules is checking SSE or KMS (aws managed) or KMS CMK

**Comment by gruebel** [comment]
Hey @pingoleon108 thanks for reaching out.

This title is correct, because checking for SSE or KMS (AWS managed) or KMS CMK is equivalent with 'server-side-encryption enabled'
