### ISSUE TITLE
Support data. aws_iam_policy_document reference in CKV_AWS_70

### ISSUE THREAD

**Issue by sleepwhilealive** [bridgecrewio/checkov#5751]
**Describe the issue**
CKV_AWS_70 doesn't seem to load/run/work.  Although it will be listed with "-l", it won't show up as either pass or failing while checking a terraform plan.  

I only stumbled upon this because I was trying to make a custom check and used it as a base.  No matter what I tried I couldn't get this custom check to work.  Even copying the code verbatim and only modifying the ID number failed to load.  Trying a different check, CKV_AWS_93, showed me that it was a problem with CKV_AWS_70  check.  

**Examples**
main.tf
```hcl
module "s3-bucket" {
  source  = "terraform-aws-modules/s3-bucket/aws"
  version = "3.15.1"
}
```
cmds:
```bash
terraform init
terraform plan -out tfplan.plan
terraform show -json tfplan.plan > tfplan.json
checkov -f tfplan.json --external-checks-dir ~/devel/scratch/checkov --run-all-external-checks
```

**Version (please complete the following information):**
 - Checkov Version: 3.0.33 (pip3)

**Additional context**
I have also tested against the source directory with the same result (not running CKV_AWS_70).

**Comment by gruebel** [comment]
hey @sleepwhilealive thanks for reaching out.

We don't support `data` references for the policy in this check and multiple others, it needs to be inline. Taken from the module code

```hcl
resource "aws_s3_bucket_policy" "this" {
  count = local.create_bucket && local.attach_policy ? 1 : 0

  # Chain resources (s3_bucket -> s3_bucket_public_access_block -> s3_bucket_policy )
  # to prevent "A conflicting conditional operation is currently in progress against this resource."
  # Ref: https://github.com/hashicorp/terraform-provider-aws/issues/7628

  bucket = aws_s3_bucket.this[0].id
  policy = data.aws_iam_policy_document.combined[0].json

  depends_on = [
    aws_s3_bucket_public_access_block.this
  ]
}
```

and looking  at you usage of the module it looks like there won't be any policy attached

**Comment by gruebel** [comment]
same applies for the `aws_s3_bucket` resource, if we can't process the policy argument (also when it is missing) then we set it to unknown state. Not all policies behave  this way, but this one was especially adjusted to handle those undefined cases. Same behaviour would need to be applied to `CKV_AWS_93`.
