### ISSUE TITLE
How to handle terraform "known after apply"?

### ISSUE THREAD

**Issue by sleepwhilealive** [bridgecrewio/checkov#5752]
**Describe the issue**
How do we handle the case when terraform doesn't know what the value will be during a plan?

While trying to create a custom check for terraform I realized that checking against any value that shows as "known after apply" in the plan will not be available for checking against.  For example, I tried creating a custom check to verify a S3 Bucket policy contained a certain condition but it fails when the plan value is "known after apply". Looking at the plan json file I can see that the planned resources indeed don't list the "policy" value (it exists in another section of the file, just not the in the section with resources).

**Example Value**

To recreate:
Use registry module: `terraform-aws-modules/s3-bucket`
Set `attach_deny_insecure_transport_policy` to true

Use following custom module:
```python
from __future__ import annotations

import json
from typing import Any

from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.terraform.checks.resource.base_resource_check import BaseResourceCheck
from checkov.common.util.type_forcers import force_list


class MYCOMPANY_AWS_CRY_04(BaseResourceCheck):
    def __init__(self) -> None:
        name = "Ensure S3 Bucket Policy is set to deny HTTP requests"
        id = "MYCOMPANY.AWS.CRY.04"
        supported_resources = ('aws_s3_bucket', 'aws_s3_bucket_policy')
        categories = (CheckCategories.IAM,)
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf: dict[str, list[Any]]) -> CheckResult:
        try:
            policy_block = json.loads(conf['policy'][0])
            if 'Statement' in policy_block.keys():
                for statement in force_list(policy_block['Statement']):
                    if statement.get('Effect') != 'Deny':
                        continue

                    if 'Condition' in statement.keys():
                        values = statement['Condition']['Values']
                        if statement['Condition']['Variable'] == "aws:SecureTransport" and ((isinstance(values, str) and values == 'false') or (isinstance(values, list) and 'false' in values)):
                            return CheckResult.PASSED

        except Exception as e:  # nosec
            print(f"************ Exception: {e}")
        return CheckResult.FAILED

    def get_evaluated_keys(self) -> list[str]:
        return ['policy']


check = MYCOMPANY_AWS_CRY_04()
```

To be clear although the example given to recreate may have a workaround (looking for the data.aws_iam_poiicy_document), the issue still stands for any attribute that is "known after apply"

**Comment by gruebel** [comment]
hey @sleepwhilealive thanks for reaching out.

We ignore values, which are marked as `known after apply` in the plan file, because there is no way to know the value, when Terraform also doesn't know. The policy value you mentioned is indeed stored in a `data` in the Terraform file and also in the plan file, as far as I remember. You would need create a YAML-based policy and use the connection feature there, but it can become tricky.
