### ISSUE TITLE
Update CKV_AWS_211 to allow new certificates

### ISSUE THREAD

**Issue by stevec1980** [bridgecrewio/checkov#5757]
**Describe the issue**
Checkov fails the check when new certs are used.

**Version (please complete the following information):**
 - Checkov Version 3.0.36

**Additional context**
AWS are asking people to update the cert which expires next year, you can find the new values in this link:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

**Comment by Saarett** [comment]
Hey @stevec1980 , thanks for reaching out

Great insight, are you interested in contributing the needed change?

**Comment by stevec1980** [comment]
Sure, I'm happy to do that.

What process do you follow?

**Comment by ArjunMenon-bit** [comment]
@gruebel  Could you please assign this issue to me?

**Comment by gruebel** [comment]
@stevec1980 what the new cert names exactly? we currently suggest these 3 `rds-ca-rsa2048-g1`, `rds-ca-rsa4096-g1` and `rds-ca-ecc384-g1`. I didn't see any others on the linked page.

**Comment by stevec1980** [comment]
Yes, they are the one.

The 2019 cert will expire August 22nd but the account default will change in Jan I believe....

**Comment by gruebel** [comment]
ok, it looks like the 2019 cert will expire in August next year. There shouldn't be any harm in enforcing a newer version to be set explicitly.
