### ISSUE TITLE
ckv_aws_157 - Optional Constructs cannot be evaluated properly by checkov

### ISSUE THREAD

**Issue by pingoleon108** [bridgecrewio/checkov#5764]
**Describe the issue**
 Checkov needs to be able to handle boolean cases and object type. The object variables are set correctly in TF. And when deployed the features are set to the correct secure setting.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

This variable.tf configuration don't pass the chv_aws_157

`variable "instance" {
  type = object({
snip...
    multi_az                              = optional(bool, true)
}`

This variable.tf configuration do pass the chv_aws_157

`variable "instance" {
snip...
    multi_az                              = true
}`

**Version (please complete the following information):**
 - [Checkov Version [e.g. 22]](version: 3.0.37)

**Additional context**

**Comment by gruebel** [comment]
duplicate #4874
