### ISSUE TITLE
Versions 3.1.0 and up fails when credentials for BridgeCrew integration is missing.

### ISSUE THREAD

**Issue by eliasbrange** [bridgecrewio/checkov#5770]
**Describe the issue**
The changes introduced in https://github.com/bridgecrewio/checkov/pull/5760/files#diff-2ce0ea68256051d5aa80a54fb68b2e7ec9c3802f3cb2c6a8efa957ddf18255e8R131 causes all of our CI pipelines that use `checkov` to fail.

It works fine with versions 3.0.40 and below.

**Exception Trace**
```sh
File "/.../site-packages/checkov/common/bridgecrew/platform_integration.py", line 397, in set_s3_client 
    raise ValueError("Credentials for client are not set")
```

**Desktop (please complete the following information):**
 - OS: Windows (WSL) & Ubuntu
 - Checkov Version >= 3.1.0

**Comment by tknisch** [comment]
Same error here which causes our CI pipelines to fail also

**Comment by gruebel** [comment]
you can just add `--skip-framework sast` because SAST won't be available for non-customers.
