### ISSUE TITLE
PyPI setting unstable releases to HEAD

### ISSUE THREAD

**Issue by jordancparker** [bridgecrewio/checkov#5775]
Hi Checkov, 

thought i would note below that unofficial releases, official being released on GitHub. Are being deployed to PyPi and being pulled into pipelines as the latest version. 

https://pypi.org/project/checkov/#history

We are seeing issues with requiring client s3 errors. However i think the main issue is that PyPi should only being pointing to 3.0.40 instead of 3.1.2

**Comment by gruebel** [comment]
We generate once a day an official GitHub release to bundle all the changes during the day. All releases on `pypi` are official, so there is nothing to be done additionally. With a minor release there are always possible breaking changes, therefore upper bound and test properly.
