### ISSUE TITLE
checkov.cloudformation.parser.node.TemplateAttributeError: list_node.items is invalid

### ISSUE THREAD

**Issue by dannyburke1** [bridgecrewio/checkov#578]
Hi, I'm running Checkov as part of a pipeline using the ubuntu-latest image and install python 3.7 to run Checkov. I'm getting the following error using the example Github action script:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/bin/checkov", line 5, in <module>
    run()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/checkov/main.py", line 66, in run
    files=file, guidelines=guidelines)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/checkov/common/runners/runner_registry.py", line 28, in run
    runner_filter=self.runner_filter, collect_skip_comments=collect_skip_comments)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/checkov/cloudformation/runner.py", line 57, in run
    for resource_name, resource in definitions[cf_file]['Resources'].items():
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/checkov/cloudformation/parser/node.py", line 202, in __getattr__
    raise TemplateAttributeError('%s.%s is invalid' % (self.__class__.__name__, name))
checkov.cloudformation.parser.node.TemplateAttributeError: list_node.items is invalid
Error: Process completed with exit code 1.
```

Github actions:
```
     - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkov tests
        run: |
          pip install checkov
          checkov -d .
```

I've tried using pip, pip3, upgrading and also installing setup-tools to help install extra deps. Is there anything else I can do?

**To Reproduce**
1. Create a github action with the above script

**Expected behavior**
Checkov runs tests successfully and installs relevant dependencies 

**Desktop (please complete the following information):**
 - OS: ubuntu-latest / Github Action container image.
 - Checkov Version : latest

**Comment by schosterbarak** [comment]
Thank you for reporting this. Can you please share a cloudformation template?

**Comment by dannyburke1** [comment]
Hi, no problem. I'm running any CF with this. It's part of a terraform pipeline and to my knowledge no CF stacks are created with Terraform.

This was working previously, so I'm not too sure where the issue is coming from.

Cheers.

**Comment by schosterbarak** [comment]
Thanks @dannyburke1 . Mind setting environment variable `LOG_LEVEL=WARNING` and share a log?

You can share those on private message at http://slack.bridgecrew.io/

**Comment by dannyburke1** [comment]
Hi @schosterbarak thanks for your help. I've set it to debug instead and I can see the file which it is failing on, which is a AppSec yaml file, so I suppose hence the Cloudformation error. I've requested to the join the Slack channel, so I can send over the specific issue on there.

Thanks again!

**Comment by dannyburke1** [comment]
For now, I've set: `CKV_IGNORED_DIRECTORIES: appspec, buildspec, taskdef, .terraform` which gets around the issue.

**Comment by metahertz** [comment]
Hey @dannyburke1
Hello from Manchester!

Glad you've found a workaround, if you wanted to share the appspec/appsec? yaml file which is causing an issue, i'll take a look whats tripping it up.

I'm on our slack `@Matt Johnson`

**Comment by dannyburke1** [comment]
Good morning @metahertz ! Hope you're keeping safe from Covid in Manchester. :) 

Yeah, sure. I'll send it over. Just received the Slack invite now. Thanks!

**Comment by nimrodkor** [comment]
I believe this was sorted out @dannyburke1, by #607 
Mind updating your checkov version and trying again?

**Comment by dannyburke1** [comment]
@nimrodkor thank you! I'll give it ago sometime this week hopefully and I'll let you know, appreciate the fix!

**Comment by dannyburke1** [comment]
@nimrodkor sorry for the delay. I've still not tried this out yet and I'm annual leave next week, we can close this if you want as I have a workaround by ignoring those directories but I'll be sure to try it without ignoring them and reporting back via Slack or something if I do encounter any issues. Thanks!
