### ISSUE TITLE
Validate Terraform value filtered by Resource Name Against multiple sources with the same resource type

### ISSUE THREAD

**Issue by justinkhoo002** [bridgecrewio/checkov#5783]
I am trying to validate Terraform value one of the resource created when there are multiple resource names with the same resource types 

For example, for below TF 
resource "postgres_server" "tls"{
     for each ... 
     name = "require_secure_transport"
     value = "on" 
}

resource "postgres_server" "enforcer"{
     for each ... 
     name = "enforcer"
     value = "on" 
}

I am only interested in checking "tls", not "enforcer" 
is there anyway to check using custom policy? 

     cond_type: "attribute"
        resource_types:
          - "postgres_server"
        attribute: "name"
        operator: "equals"
        value: "require_secure_transport"
      - cond_type: "attribute"
        resource_types:
          - "postgres_server"
        attribute: "value"
        operator: "equals"
        value: "on"

 - Checkov Version : 3.0.32

In the above example, bridgecrew checked for both "tls" and "enforcer". We only want to check "tls".

**Comment by gruebel** [comment]
there are some internally available attributes, which you could use to kind of achieve it, ex. `__address__`. For your example it will something like this `__address__ = postgres_server.tls["xyz"]`

**Comment by justinkhoo002** [comment]
@gruebel  thanks for the fast response. 
what does "xyz" supposed to be in this case? since we can't really grab iterated items in the cond. 

alternatively, can I do something like this? 

cond_type: "attribute"
    __address__:
      - "postgres_server.tls"
    attribute: "name"
    operator: "equals"
    value: "require_secure_transport"

**Comment by gruebel** [comment]
`xyz` is typically the key name of the `for_each` iteration. Your approach won't work, because we only look at the resource type.

you could probably try something like this, can't promise it will work at the end.
```yaml
cond_type: "attribute"
address:
- "postgres_server"
attribute: "__address__"
operator: "contains"
value: "postgres_server.tls"
```

**Comment by khooj002** [comment]
@gruebel  I have tried several ways and still is going breaking through. Is there anyway to escalade this question and get some more help? 
`- and:
      - cond_type: "attribute"
        resource_types:
          - "postgres_server"
        attribute: "address"
        operator: "contains"
        value: "enforce_tls"
      - cond_type: "attribute"
        resource_types:
          - "postgres_server"
        attribute: "name"
        operator: "equals"
        value: "require_secure_transport"
      - cond_type: "attribute"
        resource_types:
          - "postgres_server"
        attribute: "value"
        operator: "equals"
        value: "on"`

> `xyz` is typically the key name of the `for_each` iteration. Your approach won't work, because we only look at the resource type.
> 
> you could probably try something like this, can't promise it will work at the end.
> 
> ```yaml
> cond_type: "attribute"
> address:
> - "postgres_server"
> attribute: "__address__"
> operator: "contains"
> value: "postgres_server.tls"
> ```

**Comment by khooj002** [comment]
@gruebel  could this feature be requested?
