### ISSUE TITLE
SCA Scan Doesn't Work for go.sum

### ISSUE THREAD

**Issue by hi-artem** [bridgecrewio/checkov#5785]
**Describe the issue**

SCA scanning for go.sum is always failing with `2023-11-21 13:53:02,021 [MainThread  ] [ERROR]  {'status': 'FAILED'}`

**Examples**

Find any golang app with go.sum file, and run the following:

```sh
checkov --framework sca_package  --bc-api-key $PRISMA_ACCESS_KEY::$PRISMA_SECRET_KEY --repo-id go-repo/go-app -f go.sum
```

You will see:

```
2023-11-21 13:53:02,021 [MainThread  ] [ERROR]  {'status': 'FAILED'}

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By Prisma Cloud | version: 3.1.9
```

**Version (please complete the following information):**
 - Checkov Version 3.1.9

**Additional context**

We are using Government tenant for Prisma Cloud

**Comment by Saarett** [comment]
Hi @hi-artem , thanks for reaching out.
I've started investigation the issue. I'll keep you posted as soon as possible.
Thanks!

**Comment by Saarett** [comment]
@hi-artem Could you please share the rest of the logs? If you have any confidential/private information in the logs, you could also file a ticket via your company's Customer Success/Solution Architect representative.

**Comment by Saarett** [comment]
@hi-artem Sure. Please let me know if you need further assistance. For now, I'll close this issue. Thanks
