### ISSUE TITLE
CKV_AZURE_18 still detecting

### ISSUE THREAD

**Issue by chielboogaard** [bridgecrewio/checkov#5787]
**Describe the issue**
We are adding the `http20Enabled` marker to the site config but checkov is still giving the error

the error message is:
```Ensure that 'HTTP Version' is the latest if used to run the web app```

**Examples**
```
resource _webApplication 'Microsoft.Web/sites@2022-03-01' = {
  dependsOn: []
  name: format(subNameInfix, 'WA', WaName, WAnumber)
  location: Location
  tags: Tags
  kind: WaKind
  properties: {
    serverFarmId: _asp.id
    httpsOnly: HttpsOnly
    reserved: Reserved
    siteConfig: {
      http20Enabled: true
    }
}
```

**Version (please complete the following information):**
 - checkov-3.1.9

**Additional context**

**Comment by Saarett** [comment]
Hey @chielboogaard , I've fixed the issue. Please upgrade Checkov to the latest version. Thanks!
