### ISSUE TITLE
Checkov gets stuck on regex into TF variables.tf 

### ISSUE THREAD

**Issue by panihin** [bridgecrewio/checkov#579]
**Describe the bug**
There is variables.tf file which contains follow vars:
`
variable "external_fqdn" {
}
variable "logout_url" {
  default = "https://example.com/logout?returnurl=https://apps.example.com"
}

logout_url  = "${format(replace(var.logout_url, "/^(https?://)([\\w|\\.]+)/(.*)/", "$1%s/$3"), var.external_fqdn)}"
`

I run `checkov -d tf -o cli` and its stuck in endless loop (only ctrl+c).
I have figured out by exclusioning that char `$`(**"$1%s/$3"**) causes to the problem in `logout_url  = "${format(replace(var.logout_url, "/^(https?://)([\\w|\\.]+)/(.*)/", "$1%s/$3"), var.external_fqdn)}"`.

I know that it has started happening in new versions. Perhaps are there some changes in requirements modules?

**To Reproduce**
1. Create file variables.tf with below code
2. Run cli command  `checkov -d tf -o cli`
3. See bahavior

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: linux/macos
 - Checkov Version 1.0.549

**Comment by schosterbarak** [comment]
@panhin thank you for reporting this.
@arielkru is it related t ok changes in the parser?

**Comment by schosterbarak** [comment]
Thank you for reporting this @panihin . a fix should be available on the version that will be published in 15 min.
