### ISSUE TITLE
Error parsing Bicep files with user-defined variable Type.

### ISSUE THREAD

**Issue by kpff-sanderson** [bridgecrewio/checkov#5791]
**Describe the issue**
After receiving several parsing errors when checking Bicep files, it appears that having user-defined types in a Bicep file causes a parsing error.

**Examples**
### Parsing Error
main.bicep (with a user-defined 'Type': param vpnSiteLink is of user-defined type 'vpnSiteLinkObject')

```bicep
targetScope = 'subscription'

//Parameters
@allowed([
  'prod'
  'dev'
  'test'
  'stage'
])
@description('Deployment environment. Default: test')
param enviroName string = 'test'

@allowed([
  'westus2'
])
@description('Location for all resources created, currently only \'westus2\'.')
param location string = 'westus2'

@description('Object that contains the settings for the VPN site link.')
param vpnSiteLink vpnSiteLinkObject

//Modules
module vpnSite '../../modules/vpn-site.bicep' = {
  name: 'vpnSite'
  scope: resourceGroup('TestRG')
  params: {
    enviroName: enviroName
    location: location
    vpnSiteNickname: 'Test-VPN'
    virtualWanName: 'Test-vWAN'
    vpnGatewayName: 'Test-vpnGW'
    vpnSiteLink: vpnSiteLink
    addressPrefixes: ['Test-Addresses']
    preShareKey: 'TestPSK'
  }
}

//Types
type vpnSiteLinkObject = {
  name: string
  properties: {
    linkProperties: {
      linkProviderName: string
      linkSpeedInMbps: int
    }
    ipAddress: string
  }
}
``` 

![image](https://github.com/bridgecrewio/checkov/assets/140095969/cfca62c7-846c-4f2b-870c-98bab68a6b68)

### No Parsing error
main.bicep (with user-defined 'Type' removed: param vpnSiteLink is of type 'object')
```bicep
targetScope = 'subscription'

//Parameters
@allowed([
  'prod'
  'dev'
  'test'
  'stage'
])
@description('Deployment environment. Default: test')
param enviroName string = 'test'

@allowed([
  'westus2'
])
@description('Location for all resources created, currently only \'westus2\'.')
param location string = 'westus2'

@description('Object that contains the settings for the VPN site link.')
param vpnSiteLink object

//Modules
module vpnSite '../../modules/vpn-site.bicep' = {
  name: 'vpnSite'
  scope: resourceGroup('TestRG')
  params: {
    enviroName: enviroName
    location: location
    vpnSiteNickname: 'Test-VPN'
    virtualWanName: 'Test-vWAN'
    vpnGatewayName: 'Test-vpnGW'
    vpnSiteLink: vpnSiteLink
    addressPrefixes: ['Test-Addresses']
    preShareKey: 'TestPSK'
  }
}

//Types
//type vpnSiteLinkObject = {
//  name: string
//  properties: {
//    linkProperties: {
//      linkProviderName: string
//      linkSpeedInMbps: int
//    }
//    ipAddress: string
//  }
//}
```

![image](https://github.com/bridgecrewio/checkov/assets/140095969/8cb97d0f-c1ca-42a9-8d2e-09d5d5461c29)

**Version (please complete the following information):**
 - Checkov Version 3.1.9

**Additional context**
The bicep file that includes the user-defined variable 'Type', along with a *.bicepparam file do successfully deploy via Template Specs and Deployment Stacks without issue.

**Comment by gruebel** [comment]
hey @kpff-sanderson thanks for reaching out.

User-defined types became GA ~2 months ago and looking at the syntax I don't think we will support it anytime soon.

**Comment by xaviermignot** [comment]
Hello, I'm having the same issue testing checkov on my Bicep repos as I have just heard about Bicep support by Checkov.  
I have started using user-defined types since it became GA as it's great to have static type validation in my codebase.

@gruebel your comment is not reassuring, I understand it can be very complex to support this kind of syntax but has your position (or the team's) evolved on this over the last few months ? The Bicep tooling ecosystem is not as rich as other IaC tools (cough cough Terraform cough cough), seeing Checkov supporting Bicep is exciting but I'm afraid the lack of support for user-defined types will be a blocker for many potential users...

Thanks for the amazing work anyway, sorry I hate to point out things like that, I just want to check on this issue and understand how complex and time-consuming maintaining open-source projects can be 🤗

**Comment by gruebel** [comment]
hey @xaviermignot I recently added partial support of custom data types to the underlying parser library. It will a couple restrictions and I'm not sure, if I will fix them any time soon. These will be the limitations, no support of
- Array type
- Decorators in object type
- Union type in object type

**Comment by xaviermignot** [comment]
Thanks @gruebel, that's great !

I guess it's a pretty hard feature to implement as every tool I have used breaks once my code uses custom data types (even Template Analyzer which is the official one). And Bicep moves pretty fast, for instance export of custom data types and user-defined functions has been recently added, which is great for users but not for developers working on code scanning tools...

**Comment by KaiLuettmann** [comment]
Many thanks @gruebel. I'm also interested in that feature. Are there any updates?

**Comment by tsmithv11** [comment]
Should be resolved with https://github.com/bridgecrewio/checkov/pull/6795

**Comment by brazarb** [comment]
For me the parsing still fails when exporting the type.

**Comment by tsmithv11** [comment]
@brazarb thanks for reaching out! The example provided in the original message issue now works. If you have an example that doesn't work, please open a new Issue with an example that recreates your issue.
