### ISSUE TITLE
Issues Generating Multiple Reports - Azure DevOps Pipeline

### ISSUE THREAD

**Issue by danieljpowley** [bridgecrewio/checkov#5793]
I'm trying to output two reports one in JSON and one in JunitXML. Running one report works fine, the XML will work fine if I'm using > $(System.DefaultWorkingDirectory)/Checkov-Report.xml publishing the tests works fine.

If I use --output-file-path $(System.DefaultWorkingDirectory)/Checkov-Report.xml - I can never find the results to publish them.

If I try and output two reports the like -o json -o junitxml > $(System.DefaultWorkingDirectory)/Checkov-Report.xml,$(System.DefaultWorkingDirectory)/Checkov-Report.json or use two on --output-file-path still no joy with a file or directory doesn't exist.

I've tried CSV instead of JSON and this tries to add the CSV file after $(System.DefaultWorkingDirectory)/Checkov-Report.xml/iac.csv and this fails.

One thing I read says don't put an extension on the end of the file and it will create both Checkov-Report.xml and Checkov-Report.json which isn't work for me either.

I'm probably missing something completely obvious here but what is it?

Currently running - 3.1.9
Scanning Terraform

**Comment by gruebel** [comment]
hey @danieljpowley thanks for reaching out.

I think you are almost there, you just need to use `--output-file-path` and of course the `-o` flag to actually define, which output formats you want.

something like that hsould work
```shell
checkov -d . -o json -o junitxml --output-file-path report.json,report.xml
```

**Comment by danieljpowley** [comment]
When I use - checkov -d . -o json -o junitxml --output-file-path $(System.DefaultWorkingDirectory)/report.json,$(System.DefaultWorkingDirectory)/report.xml - I need to publish the results.

**Comment by gruebel** [comment]
if you use this flags, what kind of error do you get? If Azure DevOps doesn't expand the `(System.DefaultWorkingDirectory)` correctly, then `checkov` will not be able to write the reports anywhere.

**Comment by danieljpowley** [comment]
I bumped up the version of Checkov I was using and the reports started working as expected.

Thanks @gruebel
