### ISSUE TITLE
Checkov scan throwing CKV_K8S_31 even when seccomp runtimedefault is added under container securitycontext.

### ISSUE THREAD

**Issue by vishrane** [bridgecrewio/checkov#5796]
**Describe the issue**
Checkov scan throwing CKV_K8S_31, even when seccomp runtimedefault is added under container securitycontext.

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 10001
  seccompProfile:
    type: RuntimeDefault

![image](https://github.com/bridgecrewio/checkov/assets/88649177/b7b6a359-35c1-4704-bbff-1e21fa92a400)

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**

**Comment by gruebel** [comment]
hey @vishrane thanks for reaching out.

Can you share the whole template? We check each container of a Pod and if one of them has it not set, it will fail. For Deployments it has to be set globally and not for each container.

**Comment by gruebel** [comment]
yeah, that's true. I think we do that in some checks, but not all. This is one of them `CKV_K8S_23 - Minimize the admission of root containers`

**Comment by Saarett** [comment]
Sounds like an easy fix for me 😄 
@vishrane Would you like to contribute the fix? The specific code file would be [this one](https://github.com/bridgecrewio/checkov/blob/7e838b449ff59fb5e7ed8f06cadd6f66ea6b64ea/checkov/kubernetes/checks/resource/k8s/Seccomp.py)

**Comment by vishrane** [comment]
@Saarett could you please help us with the fix ?

**Comment by Saarett** [comment]
@vishrane Could you please assist by fixing that issue? I could assist with whatever needed 🙂  [This is the relevant check](https://github.com/bridgecrewio/checkov/blob/e5e2c453edc4addbc7660b770032d0af33c0f5aa/checkov/kubernetes/checks/resource/k8s/Seccomp.py#L16)

Another possibility would be [skipping this check](https://github.com/bridgecrewio/checkov#running-or-skipping-checks), until this issue is resolved.

**Comment by ChanochShayner** [comment]
closing by this https://github.com/bridgecrewio/checkov/pull/6459
Thx @rutiNalenger and @pninib
