### ISSUE TITLE
CKV_AZURE_23 detecting on existing resources

### ISSUE THREAD

**Issue by chielboogaard** [bridgecrewio/checkov#5804]
**Describe the issue**
We are using existing resources in bicep and checkov is marking it as error on CKV_AZURE_23.

I'm expecting to not see these errors on existing resources.

**Examples**
```
resource _sqlServer 'Microsoft.Sql/servers@2020-11-01-preview' existing = {
  name: format(subNameInfixInfra, 'ASS', 1)
}
```

**Version (please complete the following information):**
 - 3.1.17

**Additional context**

**Comment by Saarett** [comment]
Hi @chielboogaard , thanks for reaching out.
Could you please share the relevant file? Not sure we could assist without more context.

**Comment by chielboogaard** [comment]
Hi @Saarett,

Not sure which file you mean, but here some more context.

In my template I setup a webapp in azure, so App service plan, web app and a log analytic workspace. To add a connection string to the db we use an existing resources

```
resource _sqlServer 'Microsoft.Sql/servers@2020-11-01-preview' existing = {
  name: 'dbserverName'
}

resource _sqlServerDb 'Microsoft.Sql/servers/databases@2021-11-01' existing = {
  name: 'dbName'
}
```

this then triggers the checkov CKV_AZURE_23: Ensure that 'Auditing' is set to 'On' for SQL servers

But as it is an existing resource we do not create this resource here. This happens in a different module, which has the auditing turned on as the check suggests.

**Comment by gruebel** [comment]
The check `CKV_AZURE_23` is what we call a graph check, because it needs to be able to validate a connection between 2 or more resources. We currently don't ignore Bicep resources with the `existing` keyword for graph checks or only for normal ones (Python-based).

**Comment by Saarett** [comment]
@chielboogaard Since it's currently not supported, I suggest you suppress this check 🙂 
Please let me know if you need further assistance. For now, I'm closing this issue.

CC @tsmithv11

**Comment by juupas** [comment]
> The check `CKV_AZURE_23` is what we call a graph check, because it needs to be able to validate a connection between 2 or more resources. We currently don't ignore Bicep resources with the `existing` keyword for graph checks or only for normal ones (Python-based).

@gruebel I do wonder if CKV_AZURE_25, CKV_AZURE_26, and CKV_AZURE_27 have the same thing because I had to disable them for similar reason?
