### ISSUE TITLE
Checkov Policy for Lambda Functions with Admin Privileges 

### ISSUE THREAD

**Issue by rlison47** [bridgecrewio/checkov#5813]
Do we have an existing Checkov Policy that will check for Lambda Functions with Admin Privileges?

**Comment by rlison47** [comment]
Hi @Saarett thanks for sharing the checkov's docs as checked this could be the checkov ID that can verify for any admin privileges. It will check for any IAM policy for full admin privileges

CKV_AWS_1

CKV_AWS_62

**Comment by Saarett** [comment]
@rlison47 Correct
