### ISSUE TITLE
How can I enable the newer features of Checkov 3.0

### ISSUE THREAD

**Issue by rlison47** [bridgecrewio/checkov#5821]
Hello I would like to ask if there's any configuration needs to be done to enable the newer features of Checkov 3.0? Currently, we are running on Checkov 2.4.33 and we are experiencing some checkov id's failing sample of that is CKV_AWS_19 it is failing even there's an existing rule.apply_server_side_encryption_by_default.sse_algorithm='aws:kms'. We are hoping that upgrading to checkov 3.0 will resolve the scanning issue that we have in Checkov. Any help would be appreciated

**Comment by JamesWoolfenden** [comment]
@rlison47 if you could post a sample of your code that you think is erroneously failing? Thanks

**Comment by rlison47** [comment]
Hi @JamesWoolfenden apology but the checkov id that is failing is CKV_AWS_145 Ensure that S3 buckets are encrypted with KMS by default. It should passed due to the presence of 'aws:kms'

"address": "module.s3_module.module.persistent[0].aws_s3_bucket_server_side_encryption_configuration.s3_bucket",
                  "mode": "managed",
                  "type": "aws_s3_bucket_server_side_encryption_configuration",
                  "name": "s3_bucket",
                  "provider_name": "registry.terraform.io/hashicorp/aws",
                  "schema_version": 0,
                  "values": {
                    "expected_bucket_owner": null,
                    "rule": [
                      {
                        "apply_server_side_encryption_by_default": [
                          {
                            "kms_master_key_id": "arn:aws:kms:ap-southeast-1:085094121557:key/mrk-da7f51e184b245d488114312e0d42025",
                            "sse_algorithm": "aws:kms"

<img width="960" alt="image" src="https://github.com/bridgecrewio/checkov/assets/130549613/1d045b02-c944-409b-aa56-07891346c4c7">
