### ISSUE TITLE
CKV_AZURE_109 case-sensitive

### ISSUE THREAD

**Issue by uadfs089314** [bridgecrewio/checkov#5827]
Using az bicep build to generate arm templates, it contains:
```
"networkAcls": {
  "defaultAction": "deny",
  "bypass": "AzureServices"
},
```
Which is not matching CKV_AZURE_109 [link](https://github.com/bridgecrewio/checkov/blame/9d6ea86a3b14232b0a6ceac6c21362971ffaf81c/checkov/arm/checks/resource/KeyVaultEnablesFirewallRulesSettings.py#L19)

Is it possible to run the check case-insensitive?

**Comment by Saarett** [comment]
@uadfs089314 Thanks for reaching out, and finding the source of the issue 🙂 
Do you with to create a PR that will solve this issue? That would be helpful 😄
