### ISSUE TITLE
CDK Roadmap & Future Plans ✌️ 

### ISSUE THREAD

**Issue by bakosa** [bridgecrewio/checkov#5831]
## What is the plan with the new CDK effort & future SAST capabilities?

I am seeing numerous pull requests enabling a new SAST runner and CDK check type, this looks awesome! I was really excited to try this feature out until I noticed this recent [PR](https://github.com/bridgecrewio/checkov/pull/5773) to "remove SAST frameworks for OSS users" 😢 

I was hoping that this would still fall under IaC check type considering the checks that are being added are really from the existing CloudFormation check type which contains lots of checks contributed by OSS users. My question is what is the roadmap regarding SAST/CDK support? Is this feature being built out primarily as a licensed feature? Are there any plans to open this up to the OSS community?

**Comment by gruebel** [comment]
Hey @bakosa thanks for reaching out.

Currently there is no plan to add CDK support to the OSS version of `checkov`.

**Comment by bakosa** [comment]
Interesting, ok.. what product will this be used for then behind the price wall?

**Comment by gruebel** [comment]
In Prisma Cloud 🙂
