### ISSUE TITLE
github_actions framework returns with no checks

### ISSUE THREAD

**Issue by RazRosh** [bridgecrewio/checkov#5838]
I'm running the following command inside a repository directory:
checkov -d . --soft-fail --output json --framework github_actions --output-file-path .

I'm getting the following output:
{
    "passed": 0,
    "failed": 0,
    "skipped": 0,
    "parsing_errors": 0,
    "resource_count": 0,
    "checkov_version": "3.0.35"
}

This issue seems to repeat it self in several repositories I manage, but it's not consistent usually it works.
I'm running the exact same command on several repositories.

**Comment by RazRosh** [comment]
So I found out what causing this issue, some of our actions using run-name 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name

And that seem to cause checkov to skip all checks(not sure why), I did multiple testing and once I remove the run-name line checkov works properly.
hope you can fix this :)

**Comment by gruebel** [comment]
hey @RazRosh thanks for reaching out.

This was fixed in version `3.1.6` so you just need to update it 🙂 PR #5742 for reference.

**Comment by RazRosh** [comment]
Thanks @gruebel ! didn't notice I'm not on the latest version :sweat_smile:
