### ISSUE TITLE
CKV2_IBM_6 is requiring a deprecated feature in order to pass

### ISSUE THREAD

**Issue by ocofaigh** [bridgecrewio/checkov#5855]
**Describe the issue**
`CKV2_IBM_6: "Ensure Databases network access is restricted to a specific IP range"` currently fails if not using the `allowlist` option with the [ibm_database](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database) resource. 

The problem however is that this feature has been deprecated by IBM Cloud in favour of CBRs (Context Based Restrictions). From the [official docs](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-allowlisting&interface=ui):
![image](https://github.com/bridgecrewio/checkov/assets/29608224/daa7e7d7-270c-4684-9bb0-fda8ed2527ef)

So I do not think `CKV2_IBM_6` should be mandating people to use a deprecated feature. Perhaps update the logic to check for CBRs? For example, our ICD redis module allows you to provision CBR rules to restrict network access -> https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/blob/bd9f6299366bf2f58a137e04500d4f2102e96cf4/main.tf#L143-L181

**Examples**
Module -> https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis
Failure:
```
Check: CKV2_IBM_6: "Ensure Databases network access is restricted to a specific IP range"
	FAILED for resource: module.icd_redis.ibm_database.redis_database
	File: /main.tf:52-141
```

**Version (please complete the following information):**
 - Checkov Version 3.1.31

**Additional context**

**Comment by Saarett** [comment]
Hi @ocofaigh , thanks for reaching out 😄 
That's a good catch 👍 Do you wish to contribute the fix? That would be very helpful 🙂 Otherwise, we could wait for @praveen-panw to introduce the fix. This is the relevant file path - checkov/terraform/checks/graph_checks/ibm/IBM_DatabasesNWaccessRestrictedToSpecificIPrange.yaml

**Comment by ocofaigh** [comment]
@Saarett What do you propose the fix would be here? CBR creation is handled as completely different terraform resources to [ibm_database](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database). You basically use [ibm_cbr_zone](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cbr_zone) to create a zone (such as IP address space), and then use [ibm_cbr_rule](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/cbr_rule) to create the rule. So it won't be as simple as updating the current yaml logic.

**Comment by ocofaigh** [comment]
Still an issue, so leaving comment to prevent issue from being closed

**Comment by Saarett** [comment]
@ocofaigh I apologize for the delayed response.
What if we changed this policy from a YAML-based policy to a Python-based policy? Would that make it easier?

**Comment by ocofaigh** [comment]
@Saarett How regardless of whether you go with yaml or python, I guess a decision has to be made on what exactly you plan to check. All that I know is that the rule `CKV2_IBM_6` is mandating a feature that is deprecated, so you either need to remove the rule, or update it. If you were to update it, I'm not actually sure what you replace it with since they suggestion is to use CBRs, and CBRs are account level setting that are created separately to database instances

**Comment by ChananM** [comment]
Hi @ocofaigh, looks like this was resolved in [this PR](https://github.com/bridgecrewio/checkov/pull/5970).
Closing the issue.
