### ISSUE TITLE
CKV_AWS_16 Encryption at rest Incorrect for Aurora 

### ISSUE THREAD

**Issue by jonjozwiak** [bridgecrewio/checkov#586]
**Describe the bug**
When checking a CloudFormation template, CKV_AWS_16 flags encryption at rest not being enabled against an aurora instance.  However, according to docs for aurora this is set at DB cluster level:
 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-storageencrypted

This check needs to be updated to exclude the check for aurora or updated to also check the AWS::RDS::DBCluster for the appropriate StorageEncrypted setting.  

**To Reproduce**
Here is an example resource: 
		138 |     Type: AWS::RDS::DBInstance
		139 |     Properties:
		140 |       AllowMajorVersionUpgrade: false
		141 |       AutoMinorVersionUpgrade: true
		142 |       CopyTagsToSnapshot: true
		143 |       DBClusterIdentifier:
		144 |         Ref: MyDatabaseCluster
		145 |       DBInstanceIdentifier: MyInstance0
		146 |       DBInstanceClass: db.r5.large
		147 |       DBSubnetGroupName:
		148 |         Ref: GreenDataSubnetGroup
		149 |       Engine: aurora-mysql
		150 |       Tags:
		151 |       - Key: Name
		152 |         Value: MyInstance0
		153 |     DeletionPolicy: Delete

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Checkov Version: 1.0.540

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by schosterbarak** [comment]
Thanks @jonjozwiak ! What's up 🙂.
Is it something you'd like to contribute?

**Comment by nickgibbon-nationwide** [comment]
I think that this issue along with https://github.com/bridgecrewio/checkov/issues/139 can now be closed.

**Comment by schosterbarak** [comment]
Thanks @nickgibbon-nationwide

**Comment by njgibbon** [comment]
I think that this issue along with #139 can now be closed.

EDIT: diff account aha
