### ISSUE TITLE
Checkov Check ID: CKV_GCP_5 Ensure Google storage buckets are encrypted

### ISSUE THREAD

**Issue by rlison47** [bridgecrewio/checkov#5860]
May I know why it is CKV_GCP_5 removed from Checkov Policy?

**Comment by JamesWoolfenden** [comment]
At one time you could create unencrypted bucket in gcp see this old issue https://github.com/bridgecrewio/checkov/issues/623 nowadays its on my default https://cloud.google.com/storage/docs/encryption

**Comment by JamesWoolfenden** [comment]
we should remove the online docs for this check.

**Comment by rlison47** [comment]
I see Thank you @JamesWoolfenden it was removed since GCP has default storage encryption. Appreciate your help and advice. I am currently mapping the checkov policy for GCP.

**Comment by JamesWoolfenden** [comment]
if theres any gaps,  do let me know
