### ISSUE TITLE
Support for Rust in SCA Scans

### ISSUE THREAD

**Issue by hi-artem** [bridgecrewio/checkov#5864]
Request to add Rust support to SCA scans since it is a stable language and used by many!

Upvote this issue if you feel like Rust support is needed!

**Comment by mannycepeda1989** [comment]
Good afternoon @hi-artem there's an existing Feature Enhancement Request for this support:

https://prismacloud.ideas.aha.io/ideas/PANW-I-5447

I would strongly encourage you and others to vote for this request.

**Comment by hi-artem** [comment]
@mannycepeda1989! Thank you for sharing this link. 🚀
