### ISSUE TITLE
Checkov 3.0: Upgraded Open-Source Infrastructure-as-Code Security

### ISSUE THREAD

**Issue by rlison47** [bridgecrewio/checkov#5865]
Hello May I know what your thoughts on this https://www.paloaltonetworks.com/blog/prisma-cloud/checkov-upgrade-iac-security/?
Do I just need to upgrade the checkov version to unlock the new features of checkov? Hoping for any help and guidance on this. Thanks in advance

**Comment by JamesWoolfenden** [comment]
If you update:

`pip install checkov -U`

and check the version:
```
checkov -v
3.1.38
```

You will see you are getting v3.

**Comment by rlison47** [comment]
Thank you @JamesWoolfenden
