### ISSUE TITLE
Baseline should be invalidated for a resource the moment it changes

### ISSUE THREAD

**Issue by audunmo** [bridgecrewio/checkov#5868]
**Describe the issue**
When I have a project with a generated baseline, I'd like to have the baseline-skip dropped when I change a baseline-skipped resource. This is to encourage clean-as-you go practices, to clean up previously skipped vulns when you introduce any change on the resource.

**Examples**
Lets say I have a `resource.tf` with a resource `resource.insecure.default`, which contains some bad stuff. I generate a baseline for it that makes it ignore all the existing vulns. When I then change  `resource.insecure.default` in some way, I want _all_ previously skipped vulns to no longer be skipped, even if I didn't change anything related to the vuln. 

**Version (please complete the following information):**
 - Checkov Version 3.1.26

**Comment by gruebel** [comment]
Hey @audunmo 

I understand what you want, but that was not the intended use case of baseline. Also what does it mean for you, someone changed something. Formatting the file? Adding tags? Renaming referenced blocks, like resources or variables?

**Comment by audunmo** [comment]
@gruebel yeah ideally I'd like it to run on change to the source code, as any time a dev is making changes there I'd like to surface the previously skilled vulns. That way, we can push a clean-as-you code approach to fixing policy violations. Just makes it easier for teams to stomach the large initial list of findings, and gives a sustainable way of resolving them over time.
