### ISSUE TITLE
Is there a way to use a file to store --skip-checks?

### ISSUE THREAD

**Issue by DerekTheBrave** [bridgecrewio/checkov#5871]
I want to centrally store a file like a .checkovignore file? So I can have a global skip file and users can also add one locally depending on the project.

Or is the config file the only option, if so can I just add the skip-check part and not worry about the rest of it?

Using Terraform, Azure, and Azure DevOps.

Checkov version - 3.1.38

**Comment by gruebel** [comment]
hey @DerekTheBrave thanks for reaching out.

You can use the flag `--config-file [xyz]` and set the check IDs you want to skip, but I don't think it will work with multiple files. you can use `--create-config [xyz]` to create the initial files. Here you can find an actually used config file by `checkov` itself https://github.com/bridgecrewio/checkov/blob/main/.github/checkov.yaml

**Comment by DerekTheBrave** [comment]
Hi @gruebel 

Rather than skip-paths, I'm looking to just do something like: -

skip-check:
  - CKV_DOCKER_3
  - CKV_DOCKER_2

I just want to skip the checks but I can picture it becoming too large to just put it into the arguments. Other tools I've used in the past have had either a config file that can be set up or .trivyignore for example. 

Ideally, this will be an artifact that can be downloaded during a build to avoid irrelevant scans getting into the Test Results at the end.

**Comment by gruebel** [comment]
You can do that, all CLI flags are supported in the config file. I just added the link as an example. But I'm not 100% sure, if you can define it as a list or it needs to be a long comma separated string.

**Comment by DerekTheBrave** [comment]
@gruebel the issue I'm having here is that I'm calling an external checks dir. I would need to put everything into the config file otherwise it fails because it's only expecting one file.

Is it possible to put a feature request in for separate.checkovignore file? Or something along those lines?

**Comment by iheanachochukwu** [comment]
Can't we just have an .checkovignore where one can add the Rule ID that want to skip and possibly reasons for this skips like other compliance tools I have used in the past.

**Comment by iheanachochukwu** [comment]
@DerekTheBrave this is how I have implemented .checkovignore, to centrally manage skip-checks, set expiration dates for the rules, and integrate them into Azure DevOps pipeline.
Creating a .checkovignore file and a Python script to manage the checks dynamically.

The .checkovignore file should be in YAML format and structured as follows:

`# .checkovignore
ignore:
  - id: "CKV_AZURE_189"
    expiry: "2024-07-01"
    created: "2023-06-01"
    reason: "Required for specific access"
  - id: "CKV_AZURE_109"
    expiry: "2024-07-01"
    created: "2023-06-01"
    reason: "Required for specific access"
`
Python script to process the .checkovignore file:
This script will read the .checkovignore file, filter out expired rules, and set the --skip-check parameter dynamically, ensuring that only the valid and active rules are skipped during the Checkov scan.

`# CHECKOV_IGNORE.py
import yaml
from datetime import datetime

def is_expired(expiry_date):
    current_date = datetime.now().date()
    expiry_date = datetime.strptime(expiry_date, "%Y-%m-%d").date()
    return current_date > expiry_date

try:
    # Load the YAML content from the file
    with open('.checkovignore', 'r') as file:
        data = yaml.safe_load(file)

    # Extract the 'id' values from the ignore list that are not expired
    ids = [rule['id'] for rule in data['ignore'] if not is_expired(rule['expiry'])]

    if ids:
        # Join the ids into a comma-separated string
        skip_checks = ','.join(ids)
    else:
        skip_checks = "null"

    # Get the total number of ids
    total_ids = len(ids)

    # Print the results in a way that can be captured by the shell script
    print(f"SKIP_CHECKS: {skip_checks}")
    print(f"TOTAL_SKIPPED: {total_ids}")

    # Set the pipeline variable for other tasks
    print(f"##vso[task.setvariable variable=SKIP_CHECKS]{skip_checks}")

except FileNotFoundError:
    # Handle the case where the file is not found
    skip_checks = "null"
    print("[INFO], Checkov ignore file not found, assign SKIP_CHECKS as null, for error handling when running checkov scan...")
    print(f"##vso[task.setvariable variable=SKIP_CHECKS]{skip_checks}")
`

Example of implementation using Azure DevOps pipeline:

`steps:
  - script: |
      python CHECKOV_IGNORE.py
    displayName: 'Process .checkovignore file'

  - script: |
      checkov --directory . --skip-check $(SKIP_CHECKS)
    displayName: 'Run Checkov scan'
`

**Comment by Saarett** [comment]
This is a great idea. Nonetheless, as we see there’s not much engagement for this use case, we will probably not implement it. However, we would be more than grateful for such a contribution. 🙂

For now, I’ll close this issue. Thanks.
