### ISSUE TITLE
CKV_GCP_29 - Checks failed after GCP resource renamed

### ISSUE THREAD

**Issue by hpapadopoulos** [bridgecrewio/checkov#589]
**Describe the bug**
Google has renamed the value
`bucket_policy_only ` to `uniform_bucket_level_access`.

When adding the new value in the configuration the check CKV_GCP_29 ( Ensure that Cloud Storage buckets have uniform bucket-level access enabled ) still fails as it is still looking for the old value

**To Reproduce**
1. On tearragoat, add the value `uniform_bucket_level_access = true` and the checks will still fail

**Expected behavior**
The check should pass.

**Comment by hpapadopoulos** [comment]
Raising a PR now

**Comment by metahertz** [comment]
Are you pushing to a branch on your own fork? Then raising a PR from there? Should work, if not, happy to raise the PR on your behalf, could you share a `git diff`? thanks!

**Comment by hpapadopoulos** [comment]
I tried to push to a branch:
```git push --set-upstream origin issue_589
ERROR: Permission to bridgecrewio/checkov.git denied to hpapadopoulos.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

**Comment by metahertz** [comment]
Thanks, yes the only way to submit a PR would be to fork checkov, push a branch to your own fork, then submit a PR from that branch (github will offer to create a PR to bridgecrewio/checkov from your own fork once you push your new branch to your fork :) 

With the change, is it possible some versions of the terraform module will still be using `bucket_policy_only/[0]`? so we'd need to check for one or the other? Or has the `bucket_policy_only/[0]` option been removed from GCP?

**Comment by hpapadopoulos** [comment]
Ah, good point and you're correct! It is marked as deprecated but is still present and will be fully removed in the next major release. So a check for either one would be better.

**Comment by hpapadopoulos** [comment]
I actually raised the above that has the check for either value.

Please do let me know if anything else is needed.

Thank you
