### ISSUE TITLE
AWS SES Checkov Policy

### ISSUE THREAD

**Issue by rlison47** [bridgecrewio/checkov#5890]
May I know why there is no Default Checkov Policy for AWS SES?

**Comment by JamesWoolfenden** [comment]
Lack of requests or demand, what checks did you have in mind? I could add one for aws_ses_configuration_set
- deliveryoptions.tls_policy is required? Other than that?

**Comment by rlison47** [comment]
Hi @JamesWoolfenden May I request if we can have checkov policy for the below AWS SES security controls? Thank You in advance

1. Ensure DomainKeys Identified Mail (DKIM) feature is enabled DKI
2. Ensure that your AWS SES identities (domains and/or email addresses) are not exposed to everyone.
3. Ensure Identities are configured to allow access only to trusted (friendly) AWS accounts
4. Ensure AWS SES identities (email addresses and/or domains) are verified.

**Comment by JamesWoolfenden** [comment]
If you give me a bit more to go I can make that happen.
I need to know what resources - e.g. if this is terraform - aws_ses_domain_dkim and what attribute should or shouldn't be set.
In this case https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_dkim doesn't really expose much? It maybe different with CFN. If this are relationship/graph type checks then i need to know which resources and their required settings?

**Comment by rlison47** [comment]
@JamesWoolfenden not yet familiar with the terraform resource for AWS SES it's just that they want me to have a checkov policy enforced based on the best security practice on this https://www.trendmicro.com/cloudoneconformity-staging/knowledge-base/aws/SES/

**Comment by JamesWoolfenden** [comment]
@rlison47 discus?
Ensure DKIM signing is enabled in AWS SES to protect email senders and receivers against phishing.
**- Would the existence of a aws_ses_domain_dkim resource related to a aws_ses_domain_identity be enough?** 

Ensure that your AWS SES identities (domains and/or email addresses) are not exposed to everyone.


Ensure that AWS SES identities (domains and/or email addresses) do not allow unknown cross-account access via authorization policies.
By looking into the policies attachment to a domain identity?


Ensure AWS SES identities (email addresses and/or domains) are verified.
**- every aws_ses_domain_identity has to have an accompaning aws_ses_domain_identity_verification resource?**
Not sure how you could do this for email?

**Comment by rlison47** [comment]
@JamesWoolfenden please refer below on my response

Ensure DKIM signing is enabled in AWS SES to protect email senders and receivers against phishing.
- Would the existence of a aws_ses_domain_dkim resource related to a aws_ses_domain_identity be enough? **This is what I am thinking as well to enable DKIM for SES using Terraform, need to configure the aws_ses_domain_identity and aws_ses_domain_dkim resources.****

Ensure that your AWS SES identities (domains and/or email addresses) are not exposed to everyone.

Ensure that AWS SES identities (domains and/or email addresses) do not allow unknown cross-account access via authorization policies.
By looking into the policies attachment to a domain identity? **I'm thinking about the IAM policy attached to it which is available already in checkov**

Ensure AWS SES identities (email addresses and/or domains) are verified.
- every aws_ses_domain_identity has to have an accompaning aws_ses_domain_identity_verification resource?
Not sure how you could do this for email? **It seems this is not applicable**

**Comment by rlison47** [comment]
Happy New Year @JamesWoolfenden Can we add these in Checkov? Appreciate your continuous support

Ensure DKIM signing is enabled in AWS SES to protect email senders and receivers against phishing. 

Would the existence of a aws_ses_domain_dkim resource related to a aws_ses_domain_identity be enough? This is what I am thinking as well to enable DKIM for SES using Terraform, need to configure the aws_ses_domain_identity and aws_ses_domain_dkim resources.**
Ensure that your AWS SES identities (domains and/or email addresses) are not exposed to everyone.

Ensure that AWS SES identities (domains and/or email addresses) do not allow unknown cross-account access via authorization policies.
By looking into the policies attachment to a domain identity? I'm thinking about the IAM policy attached to it which is available already in checkov

**Comment by JamesWoolfenden** [comment]
Can do, If they are useful it would be great if you could create a new open
issue for each with any further details or response on the suggested checks?
