### ISSUE TITLE
Please reopen CKV2_GCP_10 - false positive #4812 - it is still not fixed

### ISSUE THREAD

**Issue by brodowskid** [bridgecrewio/checkov#5897]
**Describe the issue**
Please have a look at "CKV2_GCP_10 - false positive #4812"

**Comment by mannycepeda1989** [comment]
@brodowskid as mentioned previously in the prior issue:

In your case you can't specify trigger_http as the attributes are not compatible with an event trigger block, and so you should be specifying https_trigger_security_level on which the check is based.

**Comment by Saarett** [comment]
Thanks @mannycepeda1989 !
@brodowskid Please let me know if you need any further assistance 🙂

**Comment by brodowskid** [comment]
Please can you assist. I have a **event-triggered** cloud function where checkov is murning 
MEDIUM: Ensure GCP Cloud Function HTTP trigger is securedCheckov [CKV2_GCP_10](https://docs.prismacloud.io/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-networking-policies/**ensure-gcp-cloud-function-http-trigger-is-secured**)
google_cloudfunctions_function hashicorp/google 5.10.0

This is the problem what the original issue opener requested.

**Comment by ashleyghooper** [comment]
Why should we need to specify the `https_trigger_security_level` property for a function that is not HTTP triggered?
