### ISSUE TITLE
CKV_GCP_69 doesn't function properly for default node pool

### ISSUE THREAD

**Issue by igitcode** [bridgecrewio/checkov#5913]
**Describe the issue**
`CKV_GCP_69` doesn't seem to work properly with the GKE default node pool. The GKEMetadataServerIsEnabled.py doesn't take into account the structure is different for default node pool within the `google_container_cluster`. 

```hcl
      + node_pool {
          + initial_node_count          = 0
          + instance_group_urls         = (known after apply)
          + managed_instance_group_urls = (known after apply)
          + max_pods_per_node           = (known after apply)
          + name                        = "default-pool"
          + name_prefix                 = (known after apply)
          + node_count                  = (known after apply)
          + node_locations              = (known after apply)
          + version                     = (known after apply)

          + node_config {
              + disk_size_gb      = (known after apply)
              + disk_type         = (known after apply)
              + effective_taints  = (known after apply)
              + guest_accelerator = (known after apply)
              + image_type        = "COS_CONTAINERD"
              + labels            = (known after apply)
              + local_ssd_count   = (known after apply)
              + logging_variant   = "DEFAULT"
              + machine_type      = "m1-ultramem-40"
              + metadata          = (known after apply)
              + min_cpu_platform  = (known after apply)
              + oauth_scopes      = (known after apply)
              + preemptible       = false
              + service_account   = <redacted>
              + spot              = false
              + tags              = [
                  + "gke-gke-staging",
                  + "gke-gke-staging-default-pool",
                ]

              + shielded_instance_config {
                  + enable_integrity_monitoring = true
                  + enable_secure_boot          = true
                }

              + workload_metadata_config {
                  + mode = "GKE_METADATA"
                }
            }
```

The structure is ["node_pool"]["node_config"], therefore the following logic fails
```
if 'node_config' in conf.keys():
```

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
latest, my workflow uses master branch within my workflow
```
uses: bridgecrewio/checkov-action@master
```

**Additional context**

**Comment by JamesWoolfenden** [comment]
I'm not sure how your getting the structure you're getting as node_config is a root parameter for google_container_cluster. From the example given on https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster and the current provider 5.10.0: 
Tf plans  - showing that a node_config block is available.
```

  # google_container_cluster.primary will be created
  + resource "google_container_cluster" "primary" {
      + cluster_ipv4_cidr           = (known after apply)
    ...
      + tpu_ipv4_cidr_block         = (known after apply)

      + node_config {
          + disk_size_gb      = (known after apply)
          + disk_type         = (known after apply)
          + effective_taints  = (known after apply)

```

**Comment by igitcode** [comment]
We are using the public module [https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/beta-private-cluster-update-variant](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-private-cluster-update-variant/cluster.tf#L347) which is setting the optional parameter [node_pool](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_pool) for the default node pool. 

Although it's not recommended to use `node_pool` config, it's still a valid configuration.

**Comment by JamesWoolfenden** [comment]
i'm more inclined to say that we need a check for the use of node_pools? as
you cant update a node_pool without recreating the cluster which seems like
an issue for it being at all useful/safe?

**Comment by igitcode** [comment]
I agree. That's why it's not recommended, but still a valid config that used in that public module provided by Google

**Comment by JamesWoolfenden** [comment]
Ive added a new check to cover nodepool usage https://github.com/bridgecrewio/checkov/pull/5916, from the Google provider documentation that the public module isn't inline with its state correct usage.

**Comment by igitcode** [comment]
Ok, I see what you meant now. I thought you meant "check" for node_pool in the CKV_GCP_69 check.

While the new check is great, I'd still have to exclude CKV_GCP_69 when using this public module, even though I have Metadata server enabled properly.

Even thought it's against best practice, do you think the CKV_GCP_69 check should still look for the proper Metadata server config within a default pool?

We implement this public module for a lot of customers, and I assume it's widely used in general.

**Comment by JamesWoolfenden** [comment]
they've put in an override with:
 ```
lifecycle {
    ignore_changes = [node_pool, initial_node_count, resource_labels["asmv"], resource_labels["mesh_id"]]
  }
```
on the cluster resource so if your pool set to  autoscale it wont touch the cluster. Maybe they have some reason for allowing the flexibility of using nodepools in the cluster that were unaware off. So it only going to break if anyones tries to change the config of the nodepools yourself.

**Comment by igitcode** [comment]
I think they have the default pool there in case no user supplied pools and they chose to use the optional `node_pools` config.

**Comment by JamesWoolfenden** [comment]
Yeah that's still firmly in the shouldn't be that way category.

**Comment by Saarett** [comment]
Hey @igitcode , following to @JamesWoolfenden 's new check, is there anything else? 🙂

**Comment by igitcode** [comment]
I still think there should be a check for `node_pools` in CKV_GCP_69. Right now I'm having to exclude both CKV_GCP_69 and CKV_GCP_123 when using this public GKE module.
