### ISSUE TITLE
Invalid key

### ISSUE THREAD

**Issue by beairwalk** [bridgecrewio/checkov#5919]
**Describe the issue**
I am using checkov locally, but checkov requires an api key otherwise I get the following error. I was using a bridgeworks key, but that has stopped working. Is there a work around so checkov will work without an api key please?

BCAuthError, Received unexpected response from platform (status code 403). Please verify that your API token is valid and has permissions to call the Bridgecrew APIs.The key must be associated with any role besides Auditor.

**Comment by JamesWoolfenden** [comment]
you don't need an api key to use Checkov, you probably have an api key in a .bridgecrew config file or an expired key as an env var, remove them. You can get OS support from the Slack channel codified security and don't need to raise an issue for this (https://slack.bridgecrew.io/).
