### ISSUE TITLE
Getting Error after upgrading Checkov version from 3.1.26

### ISSUE THREAD

**Issue by rlison47** [bridgecrewio/checkov#5929]
Hello need help I'm getting this error after after grading the checkov to the latest version from 3.1.26 to 3.1.57 using this command pip install checkov -U

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cyclonedx-bom 3.11.7 requires cyclonedx-python-lib<4.0.0,>=2.0.0, but you have cyclonedx-python-lib 6.3.0 which is incompatible.
Successfully installed bc-python-hcl2-0.4.2 checkov-2.3.331 cyclonedx-python-lib-6.3.0 py-serializable-0.17.1

**Comment by gruebel** [comment]
Looks like you have other packages installed, which use old dependencies. You either need to remove them or install `checkov` in a separate virtual env.

**Comment by rlison47** [comment]
We can close this issue it is related to #5930 issue
