### ISSUE TITLE
Error in Checkov ImportError: cannot import name 'sha1sum' from 'cyclonedx.model' 

### ISSUE THREAD

**Issue by rlison47** [bridgecrewio/checkov#5930]
ImportError: cannot import name 'sha1sum' from 'cyclonedx.model' (C:\Users\10004960\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyclonedx\model\__init__.py)

**Comment by gruebel** [comment]
Hey @rlison47 thanks for reaching out.

Please share your installed versions of `checkov` and `cyclonedx-python-lib`. One of them probably uses an old version and should be updated locally by you.

**Comment by rlison47** [comment]
@gruebel Please refer below I also noticed that since getting the error I was stuck in this checkov version 3.1.26 I can't upgrade it to the more latest version. If I run pip install checkov -U then after that I will check the version it will be upgraded to 3.1. 55 then it will crashed with the error I mentioned then I noticed it will return again to this checkov 3.1.26. Let me know how can I fix it. Appreciate your help. Please refer below for the installed version

Name: cyclonedx-python-lib
Version: 6.3.0

Name: checkov
Version: 3.1.26

**Comment by rlison47** [comment]
Does anyone here know how can I fix this issue?

**Comment by gruebel** [comment]
I think you can only fix it by cleaning up your Python env, this is a typical issue installing `checkov` with other tools in the same venv. I can highly recommend to use something like https://github.com/pypa/pipx which will create a dedicated venv for each tool you install.

**Comment by rlison47** [comment]
Thank you for the advice @gruebel

**Comment by Saarett** [comment]
Thanks @gruebel 🍾 
@rlison47 Please let us know if you need further assistance 🙂
