### ISSUE TITLE
AWS resource names inconsistent in checks.

### ISSUE THREAD

**Issue by quixoticmonk** [bridgecrewio/checkov#5965]
**Describe the issue**

- Some of the checks reference AWS resources by inconsistent names or incorrect resources: 
  - CloudFront vs Cloud Front vs Cloud front
  - `CKV_AWS_212` references EBS as the resource.
- Typo on name of the class `BDSnapshotCopyUsesCMK` inside `DBSnapshotCopyUsesCMK` check.

**Version (please complete the following information):**
 - Checkov Version : latest

**Additional context**
Opening a PR to update these.

**Comment by JamesWoolfenden** [comment]
thanks for the update!
