### ISSUE TITLE
SCA result: fixed version vs compliant version

### ISSUE THREAD

**Issue by za** [bridgecrewio/checkov#5972]
Hi there,

I see there is fixed version and compliant version columns on [SCA result](https://github.com/bridgecrewio/checkov/blob/main/docs/7.Scan%20Examples/Sca.md). What is the difference?

**Comment by JamesWoolfenden** [comment]
if you have a general query you can ask questions like this on the slack channel codified security - https://slack.bridgecrew.io/

**Comment by za** [comment]
Noted. Closing the issue.
