### ISSUE TITLE
www.bridgecrew.cloud redirects to www.prismacloud.io - unable to login to bridgecrew to check on or generate API key

### ISSUE THREAD

**Issue by Tim-H-OC** [bridgecrewio/checkov#6031]
Bridgecrew.cloud redirects to www.prismacloud.io - unable to login to bridgecrew to check on or generate API key.

**Comment by JamesWoolfenden** [comment]
Since the Bridgecrew platform has reached its EOL this reflects the expected state.

**Comment by Tim-H-OC** [comment]
So... what does this mean for using Checkov in VSCode... is this no longer an option... is there any documentation on what this change means for users? Does the VSCode extension no longer work? Do I need a new extension? Do I need a new API key, if so from where? I see Palo Alto own Prisma and bought out Bridgecrew, so now it's a paid service only?

**Comment by cpilson** [comment]
I, too, am left completely in the dark and abandoned by this shift.

Right or wrong, this move really feels like a rug-pull. `TfSec` is out there, it works, and I'm left moving forward with one, rather than two, configuration checkers.

**Comment by Tim-H-OC** [comment]
Hi @cpilson, I too have found tfsec, so we'll start using that instead from now on. Thanks for the info!

**Comment by Yrkki** [comment]
Rug-pull, indeed. Just discovered. 

All of my https://www.bridgecrew.cloud/badges... compliance badges are now gone and I am totally dumbfounded as to where were the underlying APIs migrated to, if at all, or else, aren't there any plans to do so, migrate compliance badges. 

Anyone in the know on alternatives, hit me up. 

Keep up the good work, Bridgecrew!!
