### ISSUE TITLE
Release Apple Silicon packages

### ISSUE THREAD

**Issue by florianmutter** [bridgecrewio/checkov#6041]
Currently only packages for

* darwin_X86_64
* linux_arm64
* linux_X86_64
* windows_X86_64

are created for a new release. It would be nice if you could also publish a pacakge for darwin_arm64

**Comment by Saarett** [comment]
Hi @florianmutter , thanks for reaching out. It is already supported 🙂

**Comment by florianmutter** [comment]
Could you point me to the binary for apple silicone? Looking at the last release I only see this:

![image](https://github.com/user-attachments/assets/d6eec1a4-8436-4849-a7b2-95cd5def9c8f)
