### ISSUE TITLE
remove pinning `boto3` (and `botocore`) to an exact version

### ISSUE THREAD

**Issue by ITProKyle** [bridgecrewio/checkov#6050]
https://github.com/bridgecrewio/checkov/blob/4a92ec2fa9ab8b927aaf2741b0a115c579b6b094/setup.py#L78

This was introduced in #6011 and causes dependency conflicts in projects that list checkov as a dependency (preventing the use of checkov ^3.2.11) or requiring them to also be locked to this singular version.

**Comment by Saarett** [comment]
Hi @ITProKyle , thanks for reaching out.
That is indeed a good point. At the same time, I would like to point out that Checkov is not intended to be used as a Python package, but rather as a CLI tool.
If we see there’s a high demand for this change or a quick contribution, we will test it and perhaps approve it.

Thanks!

**Comment by jg210** [comment]
This is preventing me from installing awscli and checkov at same time. See https://github.com/bridgecrewio/checkov/issues/7071#issuecomment-3426082726.
