### ISSUE TITLE
Current (latest) version is ambiguous

### ISSUE THREAD

**Issue by ethankent** [bridgecrewio/checkov#6067]
**Describe the issue**
At the time of this posting, [3.2.28](https://github.com/bridgecrewio/checkov/releases/tag/3.2.28) is listed as the `latest` release. However, [checkov:latest](https://github.com/bridgecrewio/checkov/pkgs/container/checkov/186541439?tag=latest) is at `ghcr.io/bridgecrewio/checkov:3.2.31`

**Examples**
N/A

**Version (please complete the following information):**
Ambiguous

**Additional context**
N/A

**Comment by gruebel** [comment]
Hey @ethankent 
End of day a new GitHub release is created, which summarizes the daily changes.

**Comment by ethankent** [comment]
Hi @gruebel,

Looks like the app repo and container image are now in sync again. Just like you were saying. I'm curious though, how is it that the container version was ahead of the version in the app repo? I would expect that the container version would be the one to lag behind.

**Comment by gruebel** [comment]
hey @ethankent 

I can understand it being a bit counter intuitive 😄 but let me draw the actual release flow

1. Each merge triggers the `pypi` release, which gives you the possibility to install it via `pip`.
2. Then the Docker image release is triggered
3. At the end of each day a GitHub release is triggered
4. And additionally publishes binaries in GitHub

**Comment by ethankent** [comment]
You're right! I find that counterintuitive 😂  - I would picture the merge creating a GitHub release and the Nightly run triggering the Docker image / pypi releases. Unless we were going to try to minimize the number of patch versions, then I'd expect the Nightly run to continue to trigger the GitHub release, and then adding the new release tag would trigger all other releases.

Just curious if there's a functional reason for not having it operate more intuitively, or is an "ain't broke / don't fix" situation?

**Comment by gruebel** [comment]
Yeah, kind of. The GitHub release part came actually much later then the pypi and Docker release. If I would.do it again, then I would use proper preview releases and every 1-2 weeks create a normal release.
