### ISSUE TITLE
CKV_AZURE_118 - Incorrect link to guide

### ISSUE THREAD

**Issue by msl0** [bridgecrewio/checkov#6093]
The output shows a check regarding IP forwarding, but the link provided refers to the virtual machine agent.
```
Check: CKV_AZURE_118: "Ensure that Network Interfaces disable IP forwarding"
        PASSED for resource: azurerm_windows_virtual_machine.vm
        File: /main.tf:1-49
        Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-179
```

**Comment by naveednawazkhan** [comment]
@msl0 Thanks for reaching out. It is fixed and if the issue persists please share the main.tf file.

**Comment by msl0** [comment]
@naveednawazkhan I can confirm, I see that it now works properly. Thanks!
