### ISSUE TITLE
Suppressing/Ignoring a check on Terraform Module level

### ISSUE THREAD

**Issue by samershr** [bridgecrewio/checkov#610]
Problem Description
Trying to ignore specific check_ids for some Azure resources (Azure Storage Account currently). This works great when adding the skip comment inside the terraform resource block. 
As most people use Terraform modules for multiple enviroments, we would like to ignore it only for some storage accounts while allowing it for the rest. This is unfortunately not possible since Checkov reads the skip comment from the resource block it self and not the module

Solution
Allow Checkov to read the comment also from the Module level.

Alternative Solutions
Didn't find any other solution. In case there is one, please pass it.

Additional Information:
We have a centralized modules, which is being used for several teams and several environments. These environments have static websites, Azure boot diagnostic storage accounts which require no firewall configuration on the storage account level. We would like to ignore/skip the check id CKV_AZURE_35 for these storage accounts without affecting the others.

**Comment by ismailyenigul** [comment]
I think skipping module is a very important feature to avoid reporting on external modules.

**Comment by schosterbarak** [comment]
fixed at: https://github.com/bridgecrewio/checkov/pull/1629

**Comment by paulolieuthier** [comment]
IIUC, #1629 allows one to ignore a check in every use of the module by adding the annotation to the module. Is that right?

What I'm missing, and I think is the original request of this issue, is to ignore the rule only on a specific use of the module. That is, skip a check for a resource defined by the module but only for one instance of the module. Is that possible?
