### ISSUE TITLE
Remediation guide not shown in 1.0.585 version

### ISSUE THREAD

**Issue by serxansherif** [bridgecrewio/checkov#612]
Hello,

I have installed the latest version 1.0.585 for scanning my IaC but the Guide not shown in the scan result. It was shown in previous versions.

**executed command**
checkov -d /tmp/

**expected result**
Check: CKV_AZURE_7: "Ensure AKS cluster has Network Policy configured"
        FAILED for resource: azurerm_kubernetes_cluster.dcs-kubernetes
        File: main.tf:1-20
        **_Guide: https://docs.bridgecrew.io/docs/bc_azr_kubernetes_4_**

**checkov scan result**
Check: CKV_AZURE_7: "Ensure AKS cluster has Network Policy configured"
        FAILED for resource: azurerm_kubernetes_cluster.dcs-kubernetes
        File: main.tf:1-20

**Comment by schosterbarak** [comment]
hi @serxansherif, i've used the same version and got a guide link: 
![image](https://user-images.githubusercontent.com/6033501/96252645-f5606100-0fba-11eb-8b66-9137fa82c2a0.png)

can it be a firewall configuration between your endpoint and bridgecrew's API's?

**Comment by serxansherif** [comment]
hi @schosterbarak 
should I configure anything after installing the checkov latest versions? I see Guide in the older 1.0.567 version but don't see in the latest version.
There is no internet restriction in the VM.

**Comment by metahertz** [comment]
Hi @serxansherif 

Nothing should need configuring on the new versions, I've just upgraded checkov on a mac with pip from 1.0541 to 1.0.585 and see the guide link in both for the same check:

```
python3 -m pip install --upgrade checkov

checkov --check CKV_AZURE_7 -d .

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 1.0.585

terraform scan results:

Passed checks: 0, Failed checks: 1, Skipped checks: 0

Check: CKV_AZURE_7: "Ensure AKS cluster has Network Policy configured"
	FAILED for resource: azurerm_kubernetes_cluster.k8s_cluster
	File: /azure/aks.tf:1-25
	Guide: https://docs.bridgecrew.io/docs/bc_azr_kubernetes_4

		1  | resource azurerm_kubernetes_cluster "k8s_cluster" {
		2  |   dns_prefix          = "terragoat-${var.environment}"
		3  |   location            = var.location
		4  |   name                = "terragoat-aks-${var.environment}"
		5  |   resource_group_name = azurerm_resource_group.example.name
		6  |   identity {
		7  |     type = "SystemAssigned"
		8  |   }
		9  |   default_node_pool {
		10 |     name       = "default"
		11 |     vm_size    = "Standard_D2_v2"
		12 |     node_count = 2
		13 |   }
		14 |   addon_profile {
		15 |     oms_agent {
		16 |       enabled = false
		17 |     }
		18 |     kube_dashboard {
		19 |       enabled = true
		20 |     }
		21 |   }
		22 |   role_based_access_control {
		23 |     enabled = false
		24 |   }
		25 | }
```
I used the terragoat project with a known `CKV_AZURE_7` vuln in this file: https://raw.githubusercontent.com/bridgecrewio/terragoat/master/terraform/azure/aks.tf

Out of interest, could you re-test with this `aks.tf` file and see if you still see the issue? Thanks

**Comment by serxansherif** [comment]
I found the source of the problem.
I have the Azure CLI in the same VM. Checkov latest versions conflict with the Azure CLI pip modules therefore I couldn't see Guide in the output. Issue solved after uninstalling the Azure CLI modules :)
Thanks for your help 👍
