### ISSUE TITLE
Check CKV_AZURE_44 point to the wrong guide link

### ISSUE THREAD

**Issue by jpaulo-kumulus** [bridgecrewio/checkov#617]
**Describe the bug**
The Check CKV_AZURE_44: "Ensure Storage Account is using the latest version of TLS encryption" give the wrong guide link.
It gives the link for a aws Athena Workgroup Prevents Disabling Encryption and not for the correct guide

**To Reproduce**
1. Go to a file with the following code
```
resource "azurerm_storage_account" "storagestest" {
  name                                  = "test"
  resource_group_name       = var.rgname
  location                              = var.location
  account_kind                       = "FileStorage"
}
```
2. Run cli command  'checkov -f storageaccount/main.tf --skip-check CKV_AZURE_3,CKV_AZURE_35 --quiet'

3. See error guide link pointing to BC_AWS_GENERAL_34 (Athena Workgroup Prevents Disabling Encryption) instead of BC_AZR_STORAGE_2 (Storage Account Using latest TLS)

```
terraform scan results:

Passed checks: 2, Failed checks: 1, Skipped checks: 0

Check: CKV_AZURE_44: "Ensure Storage Account is using the latest version of TLS encryption"
        FAILED for resource: azurerm_storage_account.storageaccpremium
        File: /main.tf:2-10
        Guide: https://docs.bridgecrew.io/docs/bc_aws_general_34
```

**Expected behavior**
I expect the Output to give the following link for the right Guide

```
Check: CKV_AZURE_44: "Ensure Storage Account is using the latest version of TLS encryption"
	FAILED for resource: azurerm_storage_account.logs
	File: /monitor/main.tf:2-10
	Guide: https://docs.bridgecrew.io/docs/bc_azr_storage_2
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 with Ubuntu 20.04 WSL2]
 - Checkov Version [1.0.544]

**Comment by nimrodkor** [comment]
Thanks for reporting!
I believe the issue was resolved, no version update is required. Cheers!
