### ISSUE TITLE
run time increased drastically for secrets scanning in 3.2.65+

### ISSUE THREAD

**Issue by tberreis** [bridgecrewio/checkov#6206]
**Describe the issue**
Starting with release [3.2.65](https://github.com/bridgecrewio/checkov/releases/tag/3.2.65) the secret scanning seems to take much more time and checkov becomes more or less unusable (depending on the json input / tf planfile).

In my tests I used a moderate plan.json with 24598 lines. (Plan: 18 to add, 6 to change, 18 to destroy)

Within the debug logs a huge gap of around 3 minutes can be found:
```
2024-04-24 17:38:48,999 [MainThread  ] [DEBUG]  should_run_check CKV2_K8S_6: True
2024-04-24 17:38:49,000 [ThreadPoolEx] [DEBUG]  Running graph check: CKV2_K8S_5
2024-04-24 17:38:49,001 [ThreadPoolEx] [DEBUG]  Running graph check: CKV2_K8S_2
2024-04-24 17:38:49,001 [ThreadPoolEx] [DEBUG]  Running graph check: CKV2_K8S_1
2024-04-24 17:38:49,001 [ThreadPoolEx] [DEBUG]  Running graph check: CKV2_K8S_4
2024-04-24 17:38:49,001 [ThreadPoolEx] [DEBUG]  Running graph check: CKV2_K8S_3
2024-04-24 17:38:49,001 [ThreadPoolEx] [DEBUG]  Running graph check: CKV2_K8S_6
2024-04-24 17:42:10,922 [MainThread  ] [INFO ]  file plan.json results len 20
2024-04-24 17:42:10,922 [MainThread  ] [INFO ]  Secret scanning for plan.json took 0:03:23.123006 seconds
``` 

With all releases prior 3.2.65 the scanning took only some seconds:
```
root@88313b999e81:/host# pip install checkov==3.2.22
root@88313b999e81:/host# time checkov -f plan.json >/dev/null

real    0m5.698s
user    0m7.277s
sys     0m1.679s


root@88313b999e81:/host# pip install --force-reinstall checkov==3.2.50
root@88313b999e81:/host# time checkov -f plan.json >/dev/null

real    0m6.116s
user    0m7.794s
sys     0m1.792s


root@88313b999e81:/host# pip install --force-reinstall checkov==3.2.60
root@88313b999e81:/host# time checkov -f plan.json >/dev/null

real    0m6.279s
user    0m7.790s
sys     0m1.614s


root@88313b999e81:/host# pip install --force-reinstall checkov==3.2.63
root@88313b999e81:/host# time checkov -f plan.json >/dev/null

real    0m6.200s
user    0m7.643s
sys     0m1.730s
```

**3.2.65+**
```
root@88313b999e81:/host# pip install --force-reinstall checkov==3.2.65
root@88313b999e81:/host# time checkov -f plan.json >/dev/null

real    3m52.939s
user    3m54.288s
sys     0m1.785s


root@88313b999e81:/host# pip install --force-reinstall checkov==3.2.68
root@88313b999e81:/host# time checkov -f plan.json >/dev/null

real    3m46.121s
user    3m47.823s
sys     0m1.659s


root@88313b999e81:/host# pip install --force-reinstall checkov==3.2.74
root@88313b999e81:/host# time checkov -f plan.json >/dev/null

real    3m41.371s
user    3m42.920s
sys     0m1.722s
```

I don't see any changes related to the secrets scanning nor any feature which has been enabled or disabled in 3.2.65.
The only relevant change seems to be [#6168 Azure Storage Key detector updates in bc-detect-secrets 1.5.7](https://github.com/bridgecrewio/checkov/pull/6168).

Am I missing something or am I doing wrong?
Disabling the secrets scanning via `--skip-framework secrets` helps but isn't the solution I'm looking for.

**Version (please complete the following information):**
 - Checkov Version 3.2.65, 3.2.74

**Additional context**

**Comment by nbowes24** [comment]
Also started to experience this from v3.2.65+ however ours will now hang for at least 6 hours when GitHub Actions times it out.

**Comment by tsmithv11** [comment]
Will be fixed with this PR being merged: https://github.com/bridgecrewio/detect-secrets/pull/214
