### ISSUE TITLE
CKV_GCP_73 False positive finding

### ISSUE THREAD

**Issue by 1azunna** [bridgecrewio/checkov#6214]
**Describe the issue**
CKV_GCP_73 reports a false-positive due to invalid matching. The [pattern](https://github.com/bridgecrewio/checkov/blob/6e2761b656b13305c7c131aa1626170b67d23c84/checkov/terraform/checks/resource/gcp/CloudArmorWAFACLCVE202144228.py#L28) used in matching preconfigured rules is probably deprecated. 

**Examples**
```
resource "google_compute_security_policy" "default" {
  name = "${var.service_name}-cloudrun-security-policy"

  rule {
    action      = "deny(403)"
    priority    = "1"
    description = "cve-canary"
    match {
      expr {
        expression = "evaluatePreconfiguredWaf('cve-canary')"
      }
    }
  }
}
```

**Version (please complete the following information):**
 - Checkov Version [3.2.74]

**Additional context**
This could be resolved by changing `evaluatePreconfiguredExpr('cve-canary')` to `evaluatePreconfiguredWaf('cve-canary')`

**Comment by 1azunna** [comment]
#4740

**Comment by 1azunna** [comment]
#4740  - Related Issue

**Comment by naveednawazkhan** [comment]
Hi @1azunna thank you for reaching out. `valuatePreconfiguredExpr('cve-canary')` is not deprecated. I have made changes in the code and waiting for the approval. Thanks

Ref:
https://cloud.google.com/armor/docs/waf-rules#cves_and_other_vulnerabilities
https://github.com/bridgecrewio/checkov/issues/6214

**Comment by 1azunna** [comment]
Okay great. Thank you
