### ISSUE TITLE
How to set CHECKOV_OUTPUT_CODE_LINE_LIMIT variable from config file ?

### ISSUE THREAD

**Issue by bioinfornatics** [bridgecrewio/checkov#6284]
Dear, 
I am looking to store into the config file the OUTPUT_CODE_LINE_LIMIT to 100.
After read test and [code](https://github.com/bridgecrewio/checkov/blob/3b177e20377e69d66318ed9d859586f6702ca117/checkov/common/output/record.py#L23), I do not see the alternative of the env var.

Indeed I use the `Azure/avm-res-storage-storageaccount/azurerm` and this module need round ~75 lines to be configured.

Thanks for your help

**Comment by gruebel** [comment]
Hey @bioinfornatics there is no option to configure it via the config file. I don't think this specific option will ever be configurable via a CLI argument and therefore you can't set it in the config file.
