### ISSUE TITLE
Summary of test results at the end of the run

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/checkov#631]
**Is your feature request related to a problem? Please describe.**
I'd like to see a summary of test results printed at the very end of the run vs. begging. Is it just me :D ?

**Describe the solution you'd like**
Something like :
```none
Terraform scan results:

Passed checks: 7, Failed checks: 15, Skipped checks: 2

CloudFormation scan results:

Passed checks: 1, Failed checks: 1, Skipped checks: 0

Total scan results:

Passed checks: 8, Failed checks: 16, Skipped checks: 2

```

**Comment by schosterbarak** [comment]
Loved the issue title 😂 
Let's be get some decisions by votes in that one to see that we have users that agree. On 30 thumbs up I'll make a change and add a summary also in the end of the run.

Just want to get a validation enough people agrees with it before doing a change to the output.
