### ISSUE TITLE
Momento Cache Checkov Policy

### ISSUE THREAD

**Issue by rlison47** [bridgecrewio/checkov#6358]
Hi anyone familiar with Momento Cache? Need help if we can add Checkov Policy for Momento Cache? any help is very much appreciated.

**Comment by tsmithv11** [comment]
Is there an IaC provider for Momento Cache, such as a TF provider? I'm not seeing one of significance. Or do you mean checks for Momento Cache's SDK? That wouldn't be a use case for Checkov

**Comment by rlison47** [comment]
Thank you @tsmithv11 I also can't find any terraform resource for momento cache.
