### ISSUE TITLE
CKV_GCP_124: Doesn't link out to any documentation 

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/checkov#6370]
**Describe the issue**
This check does not link out to any documentation.

**Comment by itariq20** [comment]
@brettcurtis Hi, thanks for pointing this out, it does seem that the check has the Doc link missing, we'll investigate and update you.

**Comment by fbreckle** [comment]
To anyone finding this issue, the docs are located here:
https://docs.prismacloud.io/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-networking-policies/bc-google-cloud-124

**Comment by itariq20** [comment]
The Check now has the Doc linked:
Check: CKV_GCP_124: "Ensure GCP Cloud Function is not configured with overly permissive Ingress setting"
	FAILED for resource: google_cloudfunctions_function.function
	File: /gcp124.tf:12-22
	Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-networking-policies/bc-google-cloud-124

**Comment by MaryArmaly** [comment]
Hey @brettcurtis,
Can we close the issue based on the comment by @itariq20?
