### ISSUE TITLE
CKV_AWS_104 - Replace 'enabled' with non legacy / deprecated value

### ISSUE THREAD

**Issue by GadgetGeekNI** [bridgecrewio/checkov#6438]
https://github.com/bridgecrewio/checkov/blob/f71452c6e164c6e033ddf3e15c9a08652e08ec1c/checkov/cloudformation/checks/resource/aws/DocDBAuditLogs.py#L19

As per the AWS Docs;

> enabled (legacy) | This is a legacy parameter setting that is equivalent to 'ddl'. Setting this will enable auditing for DDL events such as createDatabase, dropDatabase, createCollection, dropCollection, createIndex, dropIndex, authCheck, authenticate, createUser, dropUser, grantRolesToUser, revokeRolesFromUser, updateUser, and dropAllUsersFromDatabase. We do not recommend using this setting because it is a legacy setting.

Can we update this to match any other appropriate string such as ;
all or ddl etc

**Comment by arielkru** [comment]
Hey @GadgetGeekNI , thank you for noticing this,  please review this PR that implements your request: https://github.com/bridgecrewio/checkov/pull/6566
