### ISSUE TITLE
Checkov is protestware?

### ISSUE THREAD

**Issue by sergiomarotco** [bridgecrewio/checkov#6443]
**Describe the issue**
As i can see in https://github.com/search?q=repo%3Abridgecrewio%2Fcheckov+putin&type=code, we can see protestware code blocks. Can i add bridgecrewio/checkov to https://github.com/toxic-repos/toxic-repos ?

**Examples**
https://github.com/search?q=repo%3Abridgecrewio%2Fcheckov+putin&type=code

**Comment by JamesWoolfenden** [comment]
that is odd, dont know how that poisoned Antons code.

**Comment by bo156** [comment]
Thanks for reporting the issue @sergiomarotco and thanks @JamesWoolfenden for the quick removal.
