### ISSUE TITLE
Properties in AWS SAM Globals section not merged with associated resources

### ISSUE THREAD

**Issue by cjfryer** [bridgecrewio/checkov#6471]
This is a duplicate of #2758, which was closed due to inactivity.  But the problem persists.  Please would you re-open #2758?

**Comment by TaherKapasi** [comment]
Totally agree, trying to keep SAM templates DRY by using `Globals` results in CKVs being reported even though the resource actually complies.

**Comment by Saarett** [comment]
I've re-opened it. Thanks.
