### ISSUE TITLE
CKV2_AWS_5: SG attached not recognized in DMS serverless

### ISSUE THREAD

**Issue by makmnr** [bridgecrewio/checkov#6628]
**The issue**
Check fails even when the security group is attached to resource (DMS replication config/ DMS serverless)

**Example**

resource "**aws_security_group**" "**my_sg**" {
  ...
}

resource "aws_dms_replication_config" "migration_instance" {
 ...
  compute_config {
    **vpc_security_group_ids       = [aws_security_group.dms_sg.id]**
  }
  depends_on = [aws_security_group.dms_sg]
}

**Version** 
Checkov Version 3.2.84

**Comment by bhean** [comment]
Same here... in my case, the SG is attached to a DocumentDB database, but the check CKV2_AWS_5 is failing as well...

**Comment by makmnr** [comment]
Quick fix would be to skip the check, or raise a PR to fix the issue similar to what I have done. But it is pending for review from few weeks now!!

**Comment by bhean** [comment]
Yes, you are right! I already sent a pull-request (similar to this one) fixing the issue that I found.
I hope both pull-requests will be reviewed soon, thanks!
