### ISSUE TITLE
Unable to install Checkov since latest version

### ISSUE THREAD

**Issue by jakaxd** [bridgecrewio/checkov#6660]
**Describe the issue**
At precisely 2:15 PM GMT+1 today, all of our CI/CD builds started failing with a consistent error related to the installation of Checkov. This issue coincided with the following commit to the Checkov repository:

- Commit: [0f3ef0dbcb0a8fe68681f0d49f04e2011d94a7ef](https://github.com/bridgecrewio/checkov/commit/0f3ef0dbcb0a8fe68681f0d49f04e2011d94a7ef)

This sudden failure has disrupted our build pipeline across multiple environments, indicating that it is not an isolated incident.

The error occurs during the installation step when running the following command:
```sh
pip3 install -U checkov
```

I am wondering how we can get around this?

**Comment by deeps-sf** [comment]
@jakaxd could you share the error you are receiving?
which build are you trying? Azure?
