### ISSUE TITLE
CKV_AZURE_228 can no longer be satisfied in AzureRM 4.0

### ISSUE THREAD

**Issue by jgroves71** [bridgecrewio/checkov#6712]
**Describe the issue**
CKV_AZURE_228 checks that the "zone_redundant" property is enabled in an azurerm_eventhub_namespace. As of AzureRM 4.0, the zone_redundant field has been removed from the provider, so this check should be updated or retired.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Version (please complete the following information):**
3.2.245

**Additional context**

**Comment by tsmithv11** [comment]
Thanks for flagging, @jgroves71! It looks like it is done automatically based on region now. We will update the check and docs.
