### ISSUE TITLE
`azurerm_storage_account` local users

### ISSUE THREAD

**Issue by PeterBennink** [bridgecrewio/checkov#6713]
**Describe the issue**
By default Terraform will enable the ability to create local SFTP users for storage accounts. IMO local_user_enabled should be set to false unless explicitly required, since this feature will only be used very scarcely, and if enabled by default there's an increased risk of manual actions outside of Terraform going unnoticed (since this is generally an obscure feature as well).

**Examples**
Not explicitly setting `local_user_enabled = false` should trigger this.

**Version (please complete the following information):**
There's no mention of local_user_enabled anywhere in the checkov codebase.

**Additional context**
https://wmatthyssen.com/2023/04/18/create-a-local-user-with-password-authentication-for-a-sftp-enabled-storage-account-using-an-azure-powershell-script/

**Comment by matansha** [comment]
Thank you @PeterBennink  for the proposal!
@tsmithv11  please take a look at this proposal

**Comment by tsmithv11** [comment]
Great suggestion, @PeterBennink. I've opened a PR to add this check.
