### ISSUE TITLE
Terraform - boolean values break for_each handling

### ISSUE THREAD

**Issue by alanszlosek** [bridgecrewio/checkov#6731]
**Describe the issue**

Adding an Issue before submitting a PR since that's what the contributing guide recommends  ...

Checkov fails to correctly handle for_each resources when there are booleans in the for_each values. I believe this bug was introduced in 3.2.249, when [this line](https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/graph_builder/foreach/abstract_handler.py#L134) was changed from break to continue.

I'm seeing this error:

> Failed to process foreach handling, error: argument of type 'bool' is not iterable

I think breaking out of the loop on line 134 is the correct thing to do (instead of continue). When the attribute value is a simple interpolation expression referencing a single local/variable (ie. it matches the entire dollar_wrapped_str_to_replace), we no longer need to look for further interpolations to replace. Thus breaking out of the loop after the assignment is the correct action to take. If we don't break out of the loop, the conditional on 129 may throw an exception while trying to do "in" against a boolean value.

**Examples**

```
locals {
  servers = {
    one = {
      monitoring = false
      type = "m3.small"
    }
  }
}

resource "aws_instance" "servers" {
  for_each = local.servers
  instance_type = each.value.type
  monitoring = each.value.monitoring
}
```

I expect this IaC to result in a resource with an address of: aws_instance.servers["one"]

**Desktop (please complete the following information):**
 - OS: Windows
 - Checkov Version 3.2.249

**Additional context**

Perhaps whoever fixes can expand on the tests added in PR 6707 by adding a monitoring=false boolean as the first item in the vmhosts elements.

**Comment by Saarett** [comment]
@alanszlosek Thanks for the input and the contribution 👍
