### ISSUE TITLE
Cannot use Checkov VSCode extension - Cannot obtain API token

### ISSUE THREAD

**Issue by dbhaigh** [bridgecrewio/checkov#6743]
https://bridgecrew.cloud now points to https://www.prismacloud.io/ 

The option to create an account or the API token needed to enable the Checkov extension in VSCode does not appear to exist

How does one obtain the API token now?  And if the API token is no longer available? Is there an available workaround?

-=A=-

.

**Comment by ChananM** [comment]
Hi @dbhaigh,
You can refer to [this technical document](https://docs.prismacloud.io/en/enterprise-edition/content-collections/administration/create-access-keys) to see how you can create API keys so you can use them in the VS Code extension. 
If you  encounter any issues during this process please don't hesitate to contact your support representative.
If you wish to use the VS Code extension without using an API key (I.E, native Checkov execution) the extension does support it.

**Comment by ChananM** [comment]
Hi @dbhaigh 
I'm sorry I misunderstood your situation. I assume you are using [the old Checkov VS Code extension](https://marketplace.visualstudio.com/items?itemName=Bridgecrew.checkov). Please use the new [Prisma Cloud extension](https://marketplace.visualstudio.com/items?itemName=PrismaCloud.prisma-cloud) that can work without Prisma API keys, in which case it will run native Checkov.
Native Checkov supports IaC and some secrets scans, and requires a Prisma Cloud account to enable additional features
