### ISSUE TITLE
Ansible Playbook with empty tasks level causes python exception and abnormal exit.

### ISSUE THREAD

**Issue by mystery-rabbit** [bridgecrewio/checkov#6744]
**Describe the issue**
A valid playbook with an empty tasks section will cause a python exception and subsequently an abnormal exit for Checkov. An example for this is a simple playbook that calls a role. This is a valid ansible playbook, works in ansible, and is seen as valid by ansible-lint.

**Examples**

A Playbook of:
```yaml
---
- name: Using a Role
  hosts: all
  roles:
    - role: somerolename
  tasks:

```

will cause a python exception: (trimmed)
```shell
...
File "./venv/lib/python3.10/site-packages/checkov/ansible/utils.py", line 144, in build_definitions_context
    for task in code_block[ResourceType.TASKS]:
TypeError: 'NoneType' object is not iterable
```

**Exception Trace**
[debug_checkov.txt](https://github.com/user-attachments/files/17188458/debug_checkov.txt)

Attached

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 22.04,
 - Checkov Version 3.2.255

**Additional context**
none.

**Comment by naveednawazkhan** [comment]
Hi @mystery-rabbit  thank you for reporting the issue. It's not going to be a common situation to scan palybook without tasks. We have opened a ticket with low priority.
