### ISSUE TITLE
CKV2_AWS_5 fails to identify opensearch attachment

### ISSUE THREAD

**Issue by coilysiren** [bridgecrewio/checkov#6760]
**Describe the issue**

checkov does not detect when a security group is attached to an AWS OpenSearch instance.

The check ID is `CKV2_AWS_5`

**Examples**

[Here's an example of a PR with the failing checkout configuration in question.](https://github.com/HHS/simpler-grants-gov/pull/2341/files#diff-609600cbb65809fe1d58326675dd804822d0ca9645e49d442b5a4308b177d5ea)

**Version:**
 - [Github Action version v12.2875.0](https://github.com/bridgecrewio/checkov-action/tree/v12.2875.0/)
 - [Checkov version v3.2.257](https://github.com/bridgecrewio/checkov/tree/3.2.257)

**Additional context**

I suspect that the problem is that `aws_opensearch_domain` needs to be added to this list: https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/SGAttachedToResource.yaml

**Comment by coilysiren** [comment]
Linking the PR instead of the diff: https://github.com/HHS/simpler-grants-gov/pull/2341

**Comment by itariq20** [comment]
@coilysiren Hi, thank you for pointing out the issue and providing the relevant details. We are investigating this issue internally and will update you with our findings.
