### ISSUE TITLE
Bicep: Implement User Data Types and Safe Access

### ISSUE THREAD

**Issue by drokzi** [bridgecrewio/checkov#6771]
**Describe the feature**

Bicep has been introducing User Data Types and Safe Access (formerly contains) for some time now. In order for new Bicep files to be written more efficiently, both functions should work in CheckOV. Otherwise, I'll have to switch to another code security solution.

**Examples**

//Data Types
type siteConfigCustom = {
  numberOfWorkers: int
} 
param siteConfig siteConfigCustom

//Safe Access
old:
contains(domain, 'keyVaultId')? domain.keyVaultId : null

new:
domain.?keyVaultId ?? null

When will it work in CheckOV?

**Comment by tsmithv11** [comment]
Should be resolved with https://github.com/bridgecrewio/checkov/pull/6795
