### ISSUE TITLE
Severity Level in Checkov report

### ISSUE THREAD

**Issue by vivaro246** [bridgecrewio/checkov#6778]
Hello All,

I am trying to use the checkov tool and its reporting feature for the very first time.
When I create the report the output xml reports the severity level as NONE.
Is that because I am not using an API key and does that require me to have a paid license from prisma to get such a key?

**Comment by DiemanXT** [comment]
in short - yes. Free will only cover 50 resources as well so it is a rip off...

**Comment by lirshindalman** [comment]
hi @vivaro246 thank you for reaching out.
