### ISSUE TITLE
Security group attached to aws_mskconnect_connector is not recognized

### ISSUE THREAD

**Issue by uroshercog** [bridgecrewio/checkov#6779]
**Describe the issue**
Check CKV2_AWS_5 is failing when you try to create an MSK Connect connector using Terraform because the Security Group attached to the cluster is not recognized.

**Examples**
```
resource "aws_security_group" "main" {
...
}

resource "aws_mskconnect_connector" "pass_msk_connect" {
  ...
  kafka_cluster {
    apache_kafka_cluster {
      vpc {
        security_groups = [aws_security_group.main.id]
      }
    }
  }
  ...
}
```
**Version (please complete the following information):**
 - 3.2.267

**Additional context**
```
Check: CKV2_AWS_5: "Ensure that Security Groups are attached to another resource"
  FAILED for resource: aws_security_group.msk-connect
  File: /connect.tf:145-155
```

**Comment by lirshindalman** [comment]
hi @uroshercog thank you for reaching out. I reviewed your PR and approved it and I'm waiting for one more review.
thanks for contributing!
