### ISSUE TITLE
Checkov oddity scanning a directory containing relative Terraform modules

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#678]
**Describe the bug**

At some point between Checkov 1.0.625 and 1.0.634 module loading started producing some unusual results where it will say that a Terraform module could not be loaded but the displayed path is a different subdirectory, repeated for _every_ subdirectory in the entire project.

**To Reproduce**
1. Create a Terraform module with submodules
2. `checkov -d .`

**Expected behavior**

Scans work normally.

**Screenshots**

```
WARNING:root:Unable to load module (source="./rds/" version="None"): MY_PROJECT_ROOT/crypto-service/task-definitions/rds
```

The root module has a main.tf which loads that module using `source = "./rds/"` but the path shown is the result of taking a different sub-module (`crypto-service` above) and appending the first module to the end (in the above, `crypto-service/task-definitions` exists but there is no `rds` subdirectory). This is repeated for every permutation of every subdirectory, including the `.git` and `.terraform` directories.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Checkov Version 1.0.634

**Comment by robeden** [comment]
This would be due to the most recent changes that dropped today. If you're blocked, you can work around the issue by rolling back to 1.0.633.

I have a theory what the problem might be. Looking into it...

**Comment by robeden** [comment]
Nope, didn't pan out. Can you provide more detail on the structure of all your module references?

- MY_PROJECT_ROOT
  - main.tf  - references "./rds". Anything else?
  - Any other files in this directory with module references?

**Comment by robeden** [comment]
I've been able to replicate this.

**Comment by acdha** [comment]
That was fast! I can confirm that my project is happily scanning again.
