### ISSUE TITLE
Bicep Parsing Error: Iterative loops cannot be parsed

### ISSUE THREAD

**Issue by dupuyjs** [bridgecrewio/checkov#6781]
**Describe the issue**
When using iterative loops in a Bicep file, the whole configuration cannot be parsed, resulting in the following error message:

Error parsing file /workspaces/infrastructure/bicep/main.bicep

The syntax is however valid and the infrastructure can be successfully deployed.

**Example Value**
The following example works fine:
```bicep
var siteSubnets = [
  {
    name: 'snetsite1'
  }
  {
    name: 'snetsite2'
  }
]
```
The following example fails:
```bicep
var siteSubnets = [
  for i in range(1, 2): {
    name: 'snetsite${i}'
  }
]
```
I suppose this is the same issue described at #6682.

**Comment by lirshindalman** [comment]
Hi @dupuyjs thank you for reaching out and providing the relevant details, we will look into it and update you

**Comment by tsmithv11** [comment]
Should be resolved with https://github.com/bridgecrewio/checkov/pull/6795
