### ISSUE TITLE
Support multi files scanner

### ISSUE THREAD

**Issue by guy-suli** [bridgecrewio/checkov#68]
Today Checkov support to scan one file using the command:
`checkov -f /user/tf/example.tf`

I'd love to get Checkov support multi files scan. Instead of running Checkov multiple time with different path file.

For example:
`checkov -f [/user/tf/example.tf, /user/tf/example/main.tf]`

**Comment by tronxd** [comment]
Hi @guy-suli , a great idea!
I propose to pass the file paths as a standard `:` separated list of paths (`$PATH` format)

**Comment by schosterbarak** [comment]
argparse have an option for arrays input.
this is the way i chose to implement it here: https://github.com/bridgecrewio/checkov/pull/71
`checkov --file /user/tf/example.tf --file /user/tf/example/main.tf`
