### ISSUE TITLE
Harmonize Python versions

### ISSUE THREAD

**Issue by Porkepix** [bridgecrewio/checkov#688]
**Describe the bug**
The Dockerfile is using python 3.8 for six months (https://github.com/bridgecrewio/checkov/commit/5d2d2e5f23ed4fdf3fa0df256563dcb89112d465) but everywhere else in the repository, python seems fixed to 3.7 version.

I started to change it to 3.8, but first I'm not sure you want to do it, and what does it imply for you. But anyway 3.8 seems to be working great looking at how it's used with the docker images for months. Also, 3.9 is out for now 4/5 months. What do you think about those versions?

**Comment by robeden** [comment]
Good catch on the Dockerfile. Technically we only need 3.7 right now, though I did wish I had some functionality from 3.8 a bit ago.

**Comment by metahertz** [comment]
@robeden do you see any downsides bumping everything in unison to 3.9? 
Most of our install methods (pipenv, docker, etc) are pretty self-contained anyway.

Thinking out loud incase i've missed something!

**Comment by robeden** [comment]
We run checkov inside an AWS lambda, which doesn't currently support 3.9. So, I would hold back on that for the moment.

**Comment by robeden** [comment]
One slightly related thing: locking from python 3.9 doesn't work right now due to this error when running tests: `ModuleNotFoundError: No module named 'importlib_metadata'. Not sure if updating to python 3.8 would fix it or not, but it would probably at least be a step in the right direction.

**Comment by Porkepix** [comment]
PR https://github.com/bridgecrewio/checkov/pull/745#issuecomment-833226410 should resolve this issue? right?

**Comment by njgibbon** [comment]
Hey @Porkepix  et al. Thanks for raising the conversation on this. I think this can close now with ref to the comments i've made here to summarise our state on this topic - https://github.com/bridgecrewio/checkov/pull/745#issuecomment-869174272

**Comment by gruebel** [comment]
Closing with the reference to @njgibbon comment.
