### ISSUE TITLE
Consider Shannon entropy when detecting secrets

### ISSUE THREAD

**Issue by VimukthiPerera** [bridgecrewio/checkov#690]
**Is your feature request related to a problem? Please describe.**
An improvement to the secret detection in https://github.com/bridgecrewio/checkov/blob/master/checkov/common/util/secrets.py or any other sensitive data found during IaC scanning. 

**Describe the solution you'd like**
Fail the sensitive data stored in a variable check if the [Shannon Entropy](https://en.wiktionary.org/wiki/Shannon_entropy) is above a certain level. 

**Describe alternatives you've considered**
None.

**Additional context**
http://blog.dkbza.org/2007/05/scanning-data-for-entropy-anomalies.html

**Comment by schosterbarak** [comment]
I actually want to start working on that sometime soon. not stale.

**Comment by schosterbarak** [comment]
hey @VimukthiPerera  shanon entropy is being used as part of new set of scans delivered at: https://github.com/bridgecrewio/checkov/blob/b8a8f150359eb262dd4fdcc962f90bfcb0c2a850/docs/5.Policy%20Index/secrets.md#secrets-resource-scans-auto-generated 

the check "Hex High Entropy String" uses Shannon entropy. You can learn more about bridgecrew's secret scanning https://bridgecrew.io/blog/checkov-secrets-scanning-find-exposed-credentials-in-iac/
