### ISSUE TITLE
Latest CKV_TF_3 Is Incorrectly Reporting the Use of Dyanmodb Table as a Check Fail

### ISSUE THREAD

**Issue by surecloud-meason** [bridgecrewio/checkov#6915]
**Describe the issue**
CKV_TF_3 has introduced a new check for the presence of a lock in terraform s3 backend state. As per this PR: https://github.com/bridgecrewio/checkov/pull/6904. The check should validate that either use_lockfile is enabled for s3 or that a dynamodb_table value is set. However it incorrectly reports a check fail if dynamodb_table is set. These settings are mutually exclusive of each other as per the documentation: https://developer.hashicorp.com/terraform/language/backend/s3#state-locking

**Examples**
Here is a valid backend config that fails the check when it shouldnt:
"backend": {
"s3": {
"bucket": "XXX-state-bucket",
"dynamodb_table": "terraform-lock-state",
"encrypt": true,
"key": "terraform/XXX",
"profile": "my-profile",
"region": "eu-west-2"
}
},

**Version (please complete the following information):**
 - Checkov Version "checkov_version": "3.2.342"

**Additional context**

**Comment by mk-system402** [comment]
On top of that, the configuration for the backend can be provided through backend.config file, which is probably the common case when the same configuration is being deployed in multiple AWS accounts. In such a case, the s3 {} block can be left empty.
