### ISSUE TITLE
Add skip-check read config feature

### ISSUE THREAD

**Issue by RealArtemiy** [bridgecrewio/checkov#698]
**Describe the solution you'd like**
`--skip-check` reads some hidden config file with list of ignored checks

file: `.skip.conf`
content: `CKV_AWS_18,CKV_AWS_52`
Run scan: `checkov -d module_name`

It will ignore checks CKV_AWS_18 and CKV_AWS_52

For instance some quick way to run CI tests `for i in $(ls); do checkov -d $i; done`

**Describe alternatives you've considered**
Current skip-checks way: checkov -d module_name --skip-check $(cat module_name/.skip.conf)

**Comment by angatha** [comment]
Hi @RealArtemiy I worked on #555 wich may implement the requested feature. It allows you to specify some cli arguments (including --skip-check) in a configuration file.

**Comment by angatha** [comment]
Also this may be a subset of #560

**Comment by larryboymi** [comment]
@RealArtemiy I was about to ask for a feature similar to this, basically just allowing skip/suppression based on resource/module path (specified in CLI flag or external file such as you requested) rather than solely via annotation.

**Comment by gruebel** [comment]
Fixed with #1248
