### ISSUE TITLE
CKV_GIT_1 fails when github_repository visibility is "private"

### ISSUE THREAD

**Issue by jasonhuling** [bridgecrewio/checkov#714]
**Describe the bug**
CKV_GIT_1 fails even though the `visibility` is set to "private".

**To Reproduce**
1. Define a github_repository with visibility = "private"
```
resource "github_repository" "this" {
  name = "my_repo"
  visibility = "private"
}
```
2. Run checkov

**Expected behavior**
This check should pass.

**Screenshots**
```
Check: CKV_GIT_1: "Ensure Repository is Private"
        FAILED for resource: github_repository.this
        File: /example/main.tf:21-24

                21 | resource "github_repository" "this" {
                22 |   name       = "my_repo"
                23 |   visibility = "private"
                24 | }
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Checkov Version 1.0.645

**Additional Context**
It seems as though the `private` flag is depreciated which is why I am using `visibility`. If you set `private = true` you will get the following warning:
```
Warning: "private": [DEPRECATED] use visibility instead

  on main.tf line 21, in resource "github_repository" "this":
  21: resource "github_repository" "this" {
```

**Comment by njgibbon** [comment]
Hello :) 

Thanks for the report!

I think I can take a look at this.

According to the Provider docs[0] currently 'private' is still supported though it does seem to be deprecated as you've evidenced. So, we just need to adjust the check to also check for 'visibility' is 'private' or 'internal' which would also be acceptable.

I should be able to fix this in the next few days.

[0]: https://www.terraform.io/docs/providers/github/r/repository.html

**Comment by schosterbarak** [comment]
@jasonhuling thank you for reporting this. 
Thanks to @njgibbon  this is now resolved
