### ISSUE TITLE
setup.py very out of sync with Pipfile & pinning deps

### ISSUE THREAD

**Issue by robeden** [bridgecrewio/checkov#724]
**Describe the bug**
`setup.py` pins all its dependencies against [general guidance](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires-vs-requirements-files):

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

Also, it was pinning old versions of many things such as boto3. I hit this when moving a tool to poetry, which had trouble resolving dependencies. When I finally managed to get it to do so, here are the upgrades that happened when I *removed* checkov as a dependency:
<img width="338" alt="Screen Shot 2020-12-08 at 2 27 43 PM" src="https://user-images.githubusercontent.com/1891321/101538032-21b4b000-3962-11eb-8f9d-352fb7655318.png">

**Expected behavior**
I believe `setup.py` should be more imprecisely defined (as Pipfile is) to allow consuming tools to allow library updates.

**Comment by schosterbarak** [comment]
@robeden good catch. do you know of a way to automate the sync between the two?

**Comment by robeden** [comment]
@schosterbarak - I looked a good bit and I think we could do it with a bit more work than I wanted to put in right this instant. [dephell](https://github.com/dephell/dephell) does conversion and would probably work great if we had a `pyproject.toml` file. I think poetry can manage it a bit better too, though I'm not 100% sure. I think a Github action step similar to the homebrew action would definitely be nice though.

**Comment by schosterbarak** [comment]
@robeden thank you!
