### ISSUE TITLE
False positive on CKV_GCP_14 - Requires backup configuration enabled on read replica

### ISSUE THREAD

**Issue by pritho** [bridgecrewio/checkov#727]
**Describe the bug**
CKV_GCP_14 requires a backup configuration, but it does not take into consideration read replicas.
A read replica cannot have backup enabled in GCP.

**To Reproduce**
1. Create a google_sql_database_instance with master_instance_name and replica_configuration
2. Chekov will pop up error CKV_GCP_14

**Expected behavior**
Read replicas should not be considered needing a backup in GCP CloudSQL

**Desktop (please complete the following information):**
 - Checkov Version 1.0.660

**Comment by mzwennes** [comment]
This issue can be closed.

**Comment by gruebel** [comment]
Thanks to @mzwennes this now fixed in version `2.0.566` 🎉
