### ISSUE TITLE
Output Results in SARIF Format

### ISSUE THREAD

**Issue by tohch4** [bridgecrewio/checkov#735]
**Is your feature request related to a problem? Please describe.**
It would be great, given [Github](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning) and [potential Gitlab integration](https://gitlab.com/gitlab-org/gitlab/-/issues/118496) amongst other tools, it would be great if, aside `checkov`'s JSON support, it outputted [SARIF](https://github.com/oasis-tcs/sarif-spec).

**Describe the solution you'd like**
An additional output parameter supporting SARIF.

**Describe alternatives you've considered**
The alternative is continuing to use the JSON output of `checkov` and other tools. This is acceptable, but in the long-term standard output formats improve the chances of adoption, especially if Github and other source code repositories are accepting this format. As `checkov` supports static analysis of many different IaC formats, this would alleviate a lot of repeat busywork on data-mapping utilities, probably not just among my colleagues. :-)

**Additional context**
My colleagues increasingly integrate with a variety of tools supporting SARIF import, not just Gitlab, and many other tools in this space are adopting this format for re-usability of exported findings. I feel this would further justify the value of your already amazing tool and reduce friction, thanks!

**Comment by brntbeer** [comment]
Bump on this! Would love to see a SARIF output crated. 

Any thoughts? I anticipate a lot more people are going to want something like going forward, especially given the GitHub action you all have (https://github.com/bridgecrewio/checkov-action)

🙏

**Comment by tohch4** [comment]
Since it is you and I @brntbeer, 2 is better than 1, I try and take a look at this.

**Comment by fabasoad** [comment]
`+1` for this feature.

**Comment by jroberts2600** [comment]
+1 for this feature.

**Comment by schosterbarak** [comment]
done thanks to @ne0z :)

**Comment by myvali95** [comment]
Can I ask what the output should be to get results in Sarif? What I am looking to achieve is to get the output of the results in the CLI in SARIF format. So far I am running this:
