### ISSUE TITLE
Bad rule w/ Cloudwatch Log Encryption

### ISSUE THREAD

**Issue by byarbrough** [bridgecrewio/checkov#744]
**Describe the bug**
Rule CKV_AWS_97 "Ensure CloudWatch logs are encrypted at rest using KMS CMKs" is bad. It is misleading, presents false positives, and needlessly leads to increased complexity.

**To Reproduce**
Upgrade from a previous version to >= 1.0.675 (I was previously using 1.0.660)

**Expected behavior**
When I got a new failure on a `aws_cloudwatch_log_group` resource for not having KMS CMK encryption I had a mini panic attack that things were in the clear. But the [aws docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html) clearly state

> Log group data is always encrypted in CloudWatch Logs. You can optionally use AWS Key Management Service for this encryption. If you do, the encryption is done using an AWS KMS customer master key (CMK)

So, yes, you _can_ use CMK, but not doing so shouldn't be an error for the following reasons:
1. The logs are already encrypted with a default KMS key
2. Using a CMK increases complexity; a user has to add it to terraform, configure it properly, safeguard it, rotate it...
2. The benefit of CMK is chiefly to prevent AWS from being able to see your data, but cloudwatch is already completely visible to AWS. Some services, like GuardDuty, look at cloudwatch anyway.

The commit is 4ffe5b7a003f0b98e4a8e8fe75a2467c5270fa92

**Additional context**
I could not find an issue related to this change, where this could have been discussed. I also had to dig through files to figure out what suddenly happened since I couldn't find a CHANGELOG. This is the sort of inconvenience that forces teams to migrate to other tools. My team has gotten a lot of benefit out of Checkov, and want to keep using it and help making it better!

**Comment by schosterbarak** [comment]
adding @mikeurbanski1

**Comment by mikeurbanski1** [comment]
Hi @byarbrough , thanks for your feedback. We're going to revert this.

**Comment by schosterbarak** [comment]
thanks for reverting it @mikeurbanski1
