### ISSUE TITLE
Checkov test in Restricted Environment

### ISSUE THREAD

**Issue by niravgshah28** [bridgecrewio/checkov#759]
**Describe the bug**
Post installation and downloading all libraries and successful installation checkoff with api skip does run the test on terraform templates

**To Reproduce**
1. Go to linux shell
2. Run cli command checkov -f ***** -s  or even it doesn't not render policies checkov -l
3. See error

It should either display policies or should test the test terraform scripts

Checkoff latest version 1.0.864

**Comment by metahertz** [comment]
Hi @niravgshah28 

Thanks for reporting an issue, are you saying it does run the test or does not? `-s` is for soft fail, if you want no API-connections, try `checkov -f <file> --no-guide`, similarly, can you try `checkov --list --no-guide` 

Thanks,
Matt

**Comment by jmeredith16** [comment]
Hello @metahertz - not sure if this is the best spot for this but the title seems relevant to my needs.

Description:
Checkov still reaching out to Bridgecrew BE even when supplying `--no-guide`

```
[root@5f552093302e project]# checkov --version
1.0.669
```

I'm also running `checkov` in an restricted environment, and I need to disable the API calls. When I run `checkov` I get the following:
```
[root@5f552093302e project]# cat main.tf
resource "aws_s3_bucket" "foo-bucket" {
  region        = "us-east-1"
  bucket        = "example-bucket"
  force_destroy = true
  acl           = "public-read"
}
[root@5f552093302e project]# LOG_LEVEL=DEBUG checkov -f main.tf
DEBUG:root:Got checkov mappings from Bridgecrew BE
2021-02-16 22:10:08,837 [MainThread  ] [DEBUG]  Got checkov mappings from Bridgecrew BE
DEBUG:root:created context for aws_s3_bucket foo-bucket
2021-02-16 22:10:08,841 [MainThread  ] [DEBUG]  created context for aws_s3_bucket foo-bucket
DEBUG:root:Created definitions context
2021-02-16 22:10:08,842 [MainThread  ] [DEBUG]  Created definitions context
DEBUG:root:Scanning file: /main.tf
2021-02-16 22:10:08,842 [MainThread  ] [DEBUG]  Scanning file: /main.tf
...
```

Having read through the docs, I found the `--no-guide` option. I added that and get the following:
```
[root@5f552093302e project]# LOG_LEVEL=DEBUG checkov -f main.tf --no-guide
DEBUG:root:created context for aws_s3_bucket foo-bucket
2021-02-16 22:10:27,890 [MainThread  ] [DEBUG]  created context for aws_s3_bucket foo-bucket
DEBUG:root:Got checkov mappings from Bridgecrew BE
2021-02-16 22:10:28,301 [MainThread  ] [DEBUG]  Got checkov mappings from Bridgecrew BE
DEBUG:root:Created definitions context
2021-02-16 22:10:28,303 [MainThread  ] [DEBUG]  Created definitions context
DEBUG:root:Scanning file: /main.tf
2021-02-16 22:10:28,303 [MainThread  ] [DEBUG]  Scanning file: /main.tf
...
```

The "Got checkov mappings from Bridgecrew BE" line appears either way, which seems like it might still be making a call despite the added flag. Digging into it slightly I found that in my build 1.0.669 there are two paths to that log statement:

```
    def get_guidelines(self) -> dict:
        if not self.guidelines:
            self.get_checkov_mapping_metadata()
        return self.guidelines

    def get_id_mapping(self) -> dict:
        if not self.bc_id_mapping:
            self.get_checkov_mapping_metadata()
        return self.bc_id_mapping
```

The `get_guidelines()` seems OK and is driven by the `--no-guide` flag. However, `get_id_mappings()` seems to be less configurable.

Anything I'm missing? This is a blocker for me as I am unable to reach out to public endpoints in my CI.

Thank you!

**Comment by schosterbarak** [comment]
@niravgshah28 @jmeredith16 I have tried to add an environment variable that enables a skip:
https://github.com/bridgecrewio/checkov/pull/879 
can you try `export BC_SKIP_MAPPING=TRUE`

**Comment by jmeredith16** [comment]
Looks to be working now:

```
11:31 $ docker run --tty -e LOG_LEVEL=DEBUG -e BC_SKIP_MAPPING=TRUE --volume /my/path:/tf bridgecrew/checkov --directory /tf
DEBUG:root:Skipped mapping API call
2021-02-17 19:31:32,144 [MainThread  ] [DEBUG]  Skipped mapping API call
DEBUG:checkov.terraform.parser:Processing variables took 1 loop iterations
2021-02-17 19:31:32,150 [MainThread  ] [DEBUG]  Processing variables took 1 loop iterations
DEBUG:checkov.terraform.parser:Processing variables took 1 loop iterations
2021-02-17 19:31:32,151 [MainThread  ] [DEBUG]  Processing variables took 1 loop iterations
DEBUG:root:created context for aws_s3_bucket foo-bucket
2021-02-17 19:31:32,153 [MainThread  ] [DEBUG]  created context for aws_s3_bucket foo-bucket
DEBUG:root:Skipped mapping API call
2021-02-17 19:31:32,153 [MainThread  ] [DEBUG]  Skipped mapping API call
DEBUG:root:Created definitions context
2021-02-17 19:31:32,154 [MainThread  ] [DEBUG]  Created definitions context
DEBUG:root:Scanning file: /main.tf
2021-02-17 19:31:32,154 [MainThread  ] [DEBUG]  Scanning file: /main.tf
```

Might be bit nicer experience if I didn't need to set both to have all the API request stop, but that's easily worked around. Thank you for the quick fix!

**Comment by schosterbarak** [comment]
Sure @jmeredith16  since the environment variable did the trick I'm closing this for now :) 
Let me know there is anything else we can help with.
