### ISSUE TITLE
Allow for checks which are not enabled by default

### ISSUE THREAD

**Issue by robeden** [bridgecrewio/checkov#761]
**Is your feature request related to a problem? Please describe.**
From a conversation in #738, Checkov currently has checks that are obvious security problems and generally should be enabled. However, there is quite a bit we could do which gets more fuzzy. For example with RDS: "allow minor version upgrades" or "deny major version upgrade". If we solve this problem, it would also allow for a "baking" period with new checks where the community could test and comment without enabling by default.

**Describe the solution you'd like**
There's a lot we could do with this, but I recommend a simple solution to start: a parameter to `BaseCheck`'s `__init__` function (default "true") which tells whether the check should be enabled by default. This would be passed along to the registry. Then when runners are pulling `all_checks`, they could ask for only enabled checks. If no specific overrides were given, that would be the default action.

**Describe alternatives you've considered**
Sets of checks (CIS set, etc.), external project, ... many things.

**Comment by tsmithv11** [comment]
Hi @robeden, you can now filter by severity if you use an API key: https://bridgecrew.io/blog/checkov-iac-policy-severities-prioritize-skip-fail/

For example, you can run `-c MEDIUM` to ignore the LOW and unmapped policies.

Would that work for your use case?

**Comment by robeden** [comment]
That seems reasonable for now.
