### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by Temikus** [bridgecrewio/checkov#77]
**Is your feature request related to a problem? Please describe.**
It's a bit unusual that one needs to run the tool with no arguments to get the version, took me a bit to get it.

**Describe the solution you'd like**
`--version` flag printing the current version of the app

**Additional context**
If you ever get dependent modules, etc. in the future it may help with support tickets as you can print not only the core package version, but the version of the OS, dependencies, etc.

EDIT: I accidentally a word

**Comment by schosterbarak** [comment]
@Temikus you are absolutely right!
Feature added.
