### ISSUE TITLE
Feature request: report full module name if module instead of just the resource name

### ISSUE THREAD

**Issue by ismailyenigul** [bridgecrewio/checkov#772]
**Describe the solution you'd like**
It  would be cool  to see the full module name if module instead of just the resource name

**Comment by robeden** [comment]
@ismailyenigul - Would you mind posting a snippet of where you're looking in the report so I can verify we're looking at the same thing?

**Comment by ismailyenigul** [comment]
Hi @robeden 
Thanks for prompt reply.
code:
```
module "my_sg" {
  source = "terraform-aws-modules/security-group/aws"
  name        = "user-service"
  description = "sg"
  vpc_id      = "vpc-123"
  ingress_with_cidr_blocks = [
    {
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      description = "User-service ports"
      cidr_blocks = "0.0.0.0/0"
    },
    {
      from_port   = 80
      to_port     = 80
      protocol    = "tcp"
      description = "User-service ports 80"
      cidr_blocks = "0.0.0.0/0"
    },
    {
      from_port   = 443
      to_port     = 443
      protocol    = "tcp"
      description = "User-service ports 80"
      cidr_blocks = "0.0.0.0/0"
    }
  ]
}
```

check result:

```
Check: CKV_AWS_24: "Ensure no security groups allow ingress from 0.0.0.0:0 to port 22"
	FAILED for resource: aws_security_group_rule.ingress_with_cidr_blocks
	File: /tf.json:0-0
	Guide: https://docs.bridgecrew.io/docs/networking_1-port-security
```


it would be  
`FAILED for resource:  module.my_sg.aws_security_group_rule.ingress_with_cidr_blocks`

**Comment by robeden** [comment]
Perfect. Thanks, @ismailyenigul

**Comment by robeden** [comment]
Looking into this, I think it would also be helpful if the calling file were included in the report output.

For example, there's the parsed file key info for a test case that I have:
```
  "/<repo_path>/modules/kong/db_instance.tf[/<repo_path>/test/fixtures/bluegreen/main.tf#1]": { ... }
```

The reported file path is: `/modules/kong/db_instance.tf` ... which is true, but doesn't paint a great picture because there are 8 other references to that file from the "prod" locations which are all correct.

I would like to add `caller_file_path` as a possible output field to the report, which would in this case report `/test/fixtures/bluegreen/main.tf`. That would allow tooling to differentiate the true origin when a module is in play. (Bonus points: `caller_file_line_range` would also be helpful.)

(cc: @nimrodkor, @schosterbarak, @rotemavni)

**Comment by robeden** [comment]
Here is a sample test case with a full resource ID and "Caller File" added, from #917...

Text output:
![Screen Shot 2021-02-24 at 4 22 47 PM](https://user-images.githubusercontent.com/1891321/109074520-78a66780-76bd-11eb-9d5a-df776838c528.png)

Json output:
```json
{
    "check_type": "terraform",
    "results": {
        "passed_checks": [],
        "failed_checks": [
            {
                "check_id": "CKV_AWS_19",
                "check_name": "Ensure all data stored in the S3 bucket is securely encrypted at rest",
                "check_result": {
                    "result": "FAILED",
                    "evaluated_keys": [
                        "server_side_encryption_configuration/[0]/rule/[0]/apply_server_side_encryption_by_default/[0]/sse_algorithm"
                    ]
                },
                "code_block": [
                    [
                        11,
                        "resource \"aws_s3_bucket\" \"outside\" {\n"
                    ],
                    [
                        12,
                        "  bucket = \"outside-bucket\"\n"
                    ],
                    [
                        13,
                        "}"
                    ]
                ],
                "file_path": "/main.tf",
                "repo_file_path": "/../../../runner/resources/module_failure_reporting_772/main.tf",
                "file_line_range": [
                    11,
                    13
                ],
                "resource": "aws_s3_bucket.outside",
                "evaluations": null,
                "check_class": "checkov.terraform.checks.resource.aws.S3Encryption",
                "fixed_definition": null,
                "entity_tags": null,
                "caller_file_path": null,
                "caller_file_line_range": null,
                "guideline": "https://docs.bridgecrew.io/docs/s3_14-data-encrypted-at-rest"
            },
            {
                "check_id": "CKV_AWS_19",
                "check_name": "Ensure all data stored in the S3 bucket is securely encrypted at rest",
                "check_result": {
                    "result": "FAILED",
                    "evaluated_keys": [
                        "server_side_encryption_configuration/[0]/rule/[0]/apply_server_side_encryption_by_default/[0]/sse_algorithm"
                    ]
                },
                "code_block": [
                    [
                        7,
                        "resource \"aws_s3_bucket\" \"inside\" {\n"
                    ],
                    [
                        8,
                        "  bucket = \"inside-bucket\"\n"
                    ],
                    [
                        9,
                        "}"
                    ]
                ],
                "file_path": "/module/module.tf",
                "repo_file_path": "/../../../runner/resources/module_failure_reporting_772/module/module.tf",
                "file_line_range": [
                    7,
                    9
                ],
                "resource": "module.test_module.aws_s3_bucket.inside",
                "evaluations": null,
                "check_class": "checkov.terraform.checks.resource.aws.S3Encryption",
                "fixed_definition": null,
                "entity_tags": null,
                "caller_file_path": "/main.tf",
                "caller_file_line_range": [
                    6,
                    8
                ],
                "guideline": "https://docs.bridgecrew.io/docs/s3_14-data-encrypted-at-rest"
            }
        ],
        "skipped_checks": [],
        "parsing_errors": []
    },
    "summary": {
        "passed": 0,
        "failed": 2,
        "skipped": 0,
        "parsing_errors": 0,
        "checkov_version": "1.0.809"
    }
}
```

**Comment by wpts-it1** [comment]
> Hi @robeden
> Thanks for prompt reply.
> code:
> 
> ```
> module "my_sg" {
>   source = "terraform-aws-modules/security-group/aws"
>   name        = "user-service"
>   description = "sg"
>   vpc_id      = "vpc-123"
>   ingress_with_cidr_blocks = [
>     {
>       from_port   = 22
>       to_port     = 22
>       protocol    = "tcp"
>       description = "User-service ports"
>       cidr_blocks = "0.0.0.0/0"
>     },
>     {
>       from_port   = 80
>       to_port     = 80
>       protocol    = "tcp"
>       description = "User-service ports 80"
>       cidr_blocks = "0.0.0.0/0"
>     },
>     {
>       from_port   = 443
>       to_port     = 443
>       protocol    = "tcp"
>       description = "User-service ports 80"
>       cidr_blocks = "0.0.0.0/0"
>     }
>   ]
> }
> ```
> 
> check result:
> 
> ```
> Check: CKV_AWS_23: "Ensure every security groups rule has a description"
> 	PASSED for resource: aws_security_group_rule.ingress_with_cidr_blocks
> 	File: /tf.json:0-0
> 	Guide: https://docs.bridgecrew.io/docs/networking_31
> 
> Check: CKV_AWS_25: "Ensure no security groups allow ingress from 0.0.0.0:0 to port 3389"
> 	PASSED for resource: aws_security_group_rule.ingress_with_cidr_blocks
> 	File: /tf.json:0-0
> 	Guide: https://docs.bridgecrew.io/docs/networking_2
> Check: CKV_AWS_24: "Ensure no security groups allow ingress from 0.0.0.0:0 to port 22"
> 	FAILED for resource: aws_security_group_rule.ingress_with_cidr_blocks
> 	File: /tf.json:0-0
> 	Guide: https://docs.bridgecrew.io/docs/networking_1-port-security
> ```
> 
> it would be
> `FAILED for resource: module.my_sg.aws_security_group_rule.ingress_with_cidr_blocks`
> 
> same for passed checks. `PASSED for`

Hello, I am a novice at Checkov. I would like to know that Does it scan a module? but the result report showing the resource scanned. Could you tell me the step for scanning, and Can it scan internal modules. Thanks
