### ISSUE TITLE
Dynamic block for Terraform AWS ALB access_logs

### ISSUE THREAD

**Issue by ArneRiemann4711** [bridgecrewio/checkov#776]
**Describe the bug**
When using dynamic blocks to enable access_logs for AWS ALB checkov is marking
the check CKV_AWS_91 as failed.

**To Reproduce**
1.  Surround access_log bock with "dynamic"
2. Run checkov
3. Test for CKV_AWS_91 will fail

**Expected behavior**
Test for CKV_AWS_91 will pass

**Desktop (please complete the following information):**
 - OS: MacOs Big Sur
 - Checkov Version [1.0.675]

**Additional context**
```
  dynamic "access_logs" {
    for_each = module.s3_bucket
    content {
      bucket  = access_logs.value.bucket.id
      prefix  = "${var.environment}-public"
      enabled = true
    }
}
```

**Comment by schosterbarak** [comment]
@tronxd had an idea on how to solve a similar issue. @tronxd @nimrodkor let's talk somewhere this week. Maybe I can take this one.

**Comment by ngocketit** [comment]
Looks like Checkov doesn't work at all with dynamic bocks, not just the one in this example. Could someone please confirm?

**Comment by schosterbarak** [comment]
@ngocketit yes, you are correct. the current workaround would be to use checkov plan analysis (See guide [here](https://www.checkov.io/2.Concepts/Evaluate%20Terraform%20Plan.html)) 

I do plan to start working on that feature soon to enable dynamic blocks across the board.

**Comment by ArneRiemann4711** [comment]
> @ngocketit yes, you are correct. the current workaround would be to use checkov plan analysis (See guide [here](https://www.checkov.io/2.Concepts/Evaluate%20Terraform%20Plan.html))
> 
> I do plan to start working on that feature soon to enable dynamic blocks across the board.

Thanks, we are using the GitHub action to run Checkov - looks like this is not a workaround for us (;

**Comment by ArneRiemann4711** [comment]
Howdy, any updates on this?

**Comment by schosterbarak** [comment]
Hi @ArneRiemann4711 haven't started yet. I would accept a PR on it. Hope I will have time to get back to it soon.

**Comment by ArneRiemann4711** [comment]
> Hi @ArneRiemann4711 haven't started yet. I would accept a PR on it. Hope I will have time to get back to it soon.

Would love to contribute, but my python skills are horrible (-;

**Comment by schosterbarak** [comment]
@ArneRiemann4711 i've just created a PR that does basic support https://github.com/bridgecrewio/checkov/pull/836

**Comment by schosterbarak** [comment]
@ArneRiemann4711 do you mind testing checkov latest version and see if it works for you?

**Comment by ArneRiemann4711** [comment]
@schosterbarak Works like a charm (tested with Github Action) .. the package on Brew for Mac isn't updated today (-:
