### ISSUE TITLE
Document "__resolved__" OR promote "scanned_file" to the actual module/resource check

### ISSUE THREAD

**Issue by avishnyakov** [bridgecrewio/checkov#813]
**Is your feature request related to a problem? Please describe.**
All this is describe in a context of Terraform resource/module check but probably could also be useful for other cases.

Currently, it does not seem to be possible to get the actual file path or the module being scanned. Based on the source code, it seems that base check has access to scanned_file variable, but passes only a hash of properties to the actual module or resource check. Here is the line:
https://github.com/bridgecrewio/checkov/blob/master/checkov/common/checks/base_check.py#L42

Lack of access to the actual file path which is being scanned could be problematic for generalized module checks. Consider this examples with Terraform module check:
* we want all our modules to have 'tags' property

The simplest implementation would be:
```python
from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.terraform.checks.module.base_module_check import BaseModuleCheck

class Module_HasPropTags(BaseModuleCheck):
    def __init__(self):
        name = "Require 'tags' property on module"
        id = "MOD_HAS_TAGS"

        supported_resources = ['module']
        categories = ['CUSTOM']
        
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_module_conf(self, conf):
        """
        Requires modules to have 'tags' property.
        :param conf: module call
        :return: <CheckResult>
        """

        if 'tags' not in conf.keys():
            return CheckResult.FAILED
        
        return CheckResult.PASSED

scanner = Module_HasPropTags()
```

That works well. However, this check would be "all or nothing" lacking ability to narrow down, tune a scope on which this check will be applied. Consider mono-repository where we have custom modules written for Terraform: azure modules, aws modules, kubernetes modules, github, azure devops and many others.
* we still want to enforce tags property for aws/azure modules
* yet other modules for github, kubernetes and many other won't have to have tags property

We now have some choices:
* ignore this tag module check for non-applicable modules (yet this is not sustainable, as we write new checks OR terraform modules, we'll have to include/exclude needed checks)
* configure multiple runs of checkov per sub-folders or group of folders (which will lead to more work, scattered test results, bunch of hacks here and there)
* try to include/exclude needed checks per folder hierarhy OR folder path, naming convention (not sure how to do that, currently either in-line comment can enabled/disable check OR cli command to completely ignore things)
* finally, the custom check can know on which file it is being run -> make further decision if naming convention is agrred upon, this is where we need to know file path on which the current check is being run (apply itself to azure/aws modules, based on path, always pass on others file paths)

Looking into the source code, there are two ways to make custom check "file-path-aware": 
* somehow, pass/get access to scanned_file down to the actual check (this is NOT available at the moment, only props of the resource/module get passed down to check)
* rely on kind of internal, a bit undocumented and potentially could be changed "__resolved__" property which house an array of files related to the curent resource/module (this is an actual list of files checkov resolved for this module)

**Describe the solution you'd like**
Having described scenario above, we might want to consider two options:

First, update checkov to pass more meta-information about the current resource being validated. Some kind of context, one of which props will house `scanned_file` as a path to the file on which checkov runs the scan. It could also work same way as `__resolved__`, for example `__scanned_file__` for simplicity.

Second option, document `__resolved__` property and guarantee some kind of interface, backward compatibility so the check can rely on this property.

In both cases, the generic rule can now be scoped with agreed naming convention based on the file path:

```python
from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.terraform.checks.module.base_module_check import BaseModuleCheck

class Module_HasPropTags(BaseModuleCheck):
    def __init__(self):
        name = "Require 'tags' property on module"
        id = "MOD_HAS_TAGS"

        supported_resources = ['module']
        categories = ['CUSTOM']
        
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_module_conf(self, conf):
        """
        Requires modules to have 'tags' property.
        :param conf: module call
        :return: <CheckResult>
        """
        
        # two ways to get current file
        scanned_file = conf['__scanned_file__']
        scanned_file = conf['__resolved__'][0]  # there should be at least one, right?
 
        # example only - detect if we are on aws/azure modules, check 'tags' prop
        if scanned_file.contains('/aws-') OR scanned_file.contains('/az-'):
          if 'tags' not in conf.keys():
              return CheckResult.FAILED
        
        # pass for all other, non-azure and non-aws modules
        return CheckResult.PASSED

scanner = Module_HasPropTags()
```

**Describe alternatives you've considered**
* looked into chekov codebase, can use `__resolved__` property for the time being hoping it won't regress

**Additional context**
We co-locate all Terraform modules within a single mono-repository leveraging a pre-defined naming convention for modules. This allows us to write custom checks which would rely on file path to make additional decision on the check logic.

That said, I might have missed something in checkov features and/or codebase, please correct me or point to an alternative path.

**Comment by schosterbarak** [comment]
@avishnyakov you did go deep into the internal parts of the code and did an amazing mapping of valid options. @nimrodkor is in PTO for a few weeks. I would like to consult with him before choosing a path. I'll consult with him and will let you know. Would you be open to working on it together on a joined pull request?

**Comment by avishnyakov** [comment]
@schosterbarak sure, let me know what I can do.

Found several other little things while researching options. Essentially, here our case is based on TerraGrunt/TerraTest layout and approach:
* we have a mono-repo for Terraform modules
* each module has "examples" folder (a set of TerraTest tests, each module is run with some random params and variations)
* then, here is another repository where these TF modules are used (references to the modules)

What we want is to have a layer of governance around this setup. Not only resources, but also:
* shape of the modules
* shape of the providers (which provider and which versions, R&D atm how to handle that with Chekov)
* some other bits (irritating variable default like "tags -> default = {}" is not parsed by Checkov and is NOT included into the module props hash, could be similar to https://github.com/bridgecrewio/checkov/issues/651 )

The module related governance is exactly what I describe in this post initially. It would be really nice to know (1) where the module is being used (in "examples" folder under TerraTest suite, in "infra-live" config repo, in other places?) and (2) where the module is coming from (essentially, by naming convention we indicate the "type" of the module: azure/aws/github, etc).

Based on these two pieces of information, checkov rule can do a lot. Teams can agree on path based naming convention and write very interesting all-in-one rules. Hence the overall suggestion in this issue, hope we all have clarity now.

**Comment by metahertz** [comment]
Thanks for all the extra context @avishnyakov! 

Just adding my thoughts, while the file-path based solution would work well for a team/community following a convention, it would make "out of the box" rules and features around modules in general (skipping checks / specific check annotations per module for example) problematic. I'd like to explore the surfacing of module metadata idea into the checks more, but it sounds like given your needs, this wouldn't go far enough to cover your usecase?

I don't see why we wouldnt pass the file as some part of new structure too though, for these advanced cases! :)
