### ISSUE TITLE
Checkov does not handle multi yaml documents where a document may not be a dict

### ISSUE THREAD

**Issue by gregdurham** [bridgecrewio/checkov#824]
**Describe the bug**
When parsing multi yaml documents with the kubernetes parser, it appears that documents not containing maps cause the entire file to be exited (with return 0) rather than those documents being skipped or an error being risen.

This makes it so that the end user/ci system has no idea that checkov was unable to process the impacted file. 

**To Reproduce**
```---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
# some comment

```

When using helm template to render files an empty yaml doc is passed in which is how I found it. 
parse using checkov -f <file content.yaml> 
and see that it happily returns 0 with no output

remove the comment, see the expected failures. 

**Expected behavior**
Either skip the affected document and log that an item was skipped, or fail the scan since the file was unable to be parsed.

**Comment by gregdurham** [comment]
A workaround is instead of using stdout for `helm template` is to pass the `--output-dir` flag which will apparently not write empty files

**Comment by metahertz** [comment]
@gregdurham, is --output-dir meaning you're ending up with zero multi-yaml documents? With each object in it's own file?
