### ISSUE TITLE
Unable to install encprops via HomeBrew

### ISSUE THREAD

**Issue by roop983** [bridgecrewio/checkov#834]
Hi, Can you please help here with the below error. 

Is there any fix for it ?

brew tap ais-engineering/homebrew https://github.pie.apple.com/ais-engineering/homebrew.git
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 8 formulae.
==> Updated Casks
Updated 6 casks.

==> Tapping ais-engineering/homebrew
Cloning into '/usr/local/Homebrew/Library/Taps/ais-engineering/homebrew-homebrew'...
remote: Enumerating objects: 64, done.
remote: Total 64 (delta 0), reused 0 (delta 0), pack-reused 64
Unpacking objects: 100% (64/64), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ais-engineering/homebrew-homebrew/encprops.rb
encprops: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the ais-engineering/homebrew tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/ais-engineering/homebrew-homebrew/encprops.rb:11

Error: Cannot tap ais-engineering/homebrew: invalid syntax in tap!

brew -v
Homebrew 2.7.7

Thanks
Rupali

**Comment by schosterbarak** [comment]
This is not a project that is related to checkov. closing
