### ISSUE TITLE
CKV_AWS_103 on HTTP -> HTTPS redirect

### ISSUE THREAD

**Issue by ArneRiemann4711** [bridgecrewio/checkov#837]
**Describe the bug**

HTTP -> HTTPS Redirect reported as "insecure"
CKV_AWS_103: "Ensure that load balancer is using TLS 1.2"

**To Reproduce**
1. Add redirect as default action for ALB_LISTERNER

```
resource "aws_lb_listener" "http" {
  load_balancer_arn = aws_lb.public.arn
  port              = "80"
  protocol          = "HTTP" 

  default_action {
    redirect {
      port        = "443"
      protocol    = "HTTPS"
      status_code = "HTTP_301"
    }
    type = "redirect"
  }
}
```

2. Run cli command `checkov -d .`
3. Reported as CKV_AWS_103: "Ensure that load balancer is using TLS 1.2"

**Expected behavior**

Security check passed

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Checkov Version: GitHub Action with checkov@master

Workaround: Disable check via ` #checkov:skip=CKV_AWS_103:This is only an redirect`

**Comment by schosterbarak** [comment]
This should fix this one: https://github.com/bridgecrewio/checkov/pull/838
