### ISSUE TITLE
Enable auditing on SQL Servers

### ISSUE THREAD

**Issue by johnbooth** [bridgecrewio/checkov#859]
**Describe the bug**
Azurerm provider notified that extended_auditing_policy block has been moved and will be removed in version 3.0 of the provider.

 **Warning: "extended_auditing_policy": [DEPRECATED] the `extended_auditing_policy` block has been moved to `azurerm_mssql_server_extended_auditing_policy` and `azurerm_mssql_database_extended_auditing_policy`. This block will be removed in version 3.0 of the provider.**
 
Updated terraform code to use azurerm_mssql_server_extended_auditing_policy and these checks are failing even though auditing has been configured correctly.

> Check: CKV_AZURE_23: "Ensure that 'Auditing' is set to 'On' for SQL servers"
        FAILED for resource: azurerm_mssql_server.this
        File: /main.tf:47-61
        Guide: https://docs.bridgecrew.io/docs/bc_azr_logging_2

> Check: CKV_AZURE_24: "Ensure that 'Auditing' Retention is 'greater than 90 days' for SQL servers"
        FAILED for resource: azurerm_mssql_server.this
        File: /main.tf:47-61
        Guide: https://docs.bridgecrew.io/docs/bc_azr_logging_3
       
**To Reproduce**
Terraform code to reproduce:
```hcl
resource "azurerm_mssql_server" "this" {
  name = "mssql-server"
  resource_group_name = "rgname"
  location = "eastus"
  version  = 12
  administrator_login = "admin"
  administrator_login_password = "password"
  minimum_tls_version = "1.2"
  public_network_access_enabled = false

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_mssql_server_extended_auditing_policy" "this" {
  server_id = azurerm_mssql_server.this.id
  storage_endpoint  = "endpoint"
  retention_in_days  = 90
}
```

**Expected behavior**
Expect the CKV_AZURE_23 and CKV_AZURE_24 to check both the `extended_auditing_policy` block and azurerm_mssql_server_extended_auditing_policy resource .

**Desktop (please complete the following information):**
 - OS: [macos]
 - ➜  checkov -v 1.0.765

**Additional context**
Same error through bridcrew.cloud.

**Comment by JamesWoolfenden** [comment]
So on the one hand in v2 provider this is still a valid test, even though the properties are due to be deprecated when v3 is released.
There is also a newer way to implement the auditing with a new tf resource. So ideally wed want a test that could check for the existence of the block or the new resource? @johnbooth ?

**Comment by johnbooth** [comment]
Totally still a valid test in V2!  We would want the test to check the existing of the auditing configuration in both resources.

**Comment by johnbooth** [comment]
I updated the expected behavior in the comments:
Expected behavior
Expect the CKV_AZURE_23 and CKV_AZURE_24 to check both the extended_auditing_policy block and azurerm_mssql_server_extended_auditing_policy resource .
