### ISSUE TITLE
bc-python-hcl2: Multi-line ternary parse error

### ISSUE THREAD

**Issue by robeden** [bridgecrewio/checkov#864]
**Describe the bug**
From #855, multi-line ternary operations do not parse correctly. For example, the following:
```
multiline = (local.local_true) ?
  "correct" : "wrong"
```
Results in this error:

> Unexpected token Token(__ANON_0, '\\n') at line 10, column 35.
> Expected one of: 
>  * LSQB
>  * LBRACE
>  * LPAR
>  * NULL
>  * __ANON_11
>  * DECIMAL
>  * FALSE
>  * __ANON_3
>  * __ANON_10
>  * STRING_LIT
>  * MINUS
>  * TRUE
>  * BANG

**Expected behavior**
This should be legal terraform and I would expect a parsed result equivalent to:
```
multiline = (local.local_true) ? "correct" : "wrong"
```
(that is: `${local.local_true ? 'correct' : 'wrong'`)

**Comment by schosterbarak** [comment]
thanks @arielkru now the parser is not breaking. 
@robeden i've made a PR in: https://github.com/bridgecrewio/checkov/pull/894 but it seems there is a an issue in _process_vars_and_locals_loop

**Comment by schosterbarak** [comment]
found the issue. it's in the parser. on it.
