### ISSUE TITLE
Plan check fails:ERROR:checkov.terraform.checks.resource.aws.EKSNodeGroupRemoteAccess:Failed

### ISSUE THREAD

**Issue by kartheekbodapati** [bridgecrewio/checkov#876]
**Describe the bug**
When I scan the terraform plan of `aws_eks_node_group` with custom `aws_launch_template`, it reports a failed check for the rule `CKV_AWS_100`

**Error**
ERROR:checkov.terraform.checks.resource.aws.EKSNodeGroupRemoteAccess:Failed to run check: Ensure Amazon EKS Node group has implict SSH access from 0.0.0.0/0 for configuration: {'ami_type': ['AL2_x86_64'], 'capacity_type': ['SPOT'], 'cluster_name': ['test-123'], 'disk_size': [50], 'force_update_version': [None], 'instance_types': [['t3.medium']], 'labels': [{'Environment': ['test'], 'GithubOrg': ['terraform-aws-modules'], 'GithubRepo': ['terraform-aws-eks'], 'start_line': [0], 'end_line': [0]}], 'launch_template': [[]], 'remote_access': [[]], 'scaling_config': [{'desired_size': [1], 'max_size': [10], 'min_size': [1], 'start_line': [0], 'end_line': [0]}], 'subnet_ids': [], 'tags': [{'Environment': 'test', 'ExtraTag': 'example', 'GithubOrg': 'terraform-aws-modules', 'GithubRepo': 'terraform-aws-eks', 'start_line': 0, 'end_line': 0}], 'timeouts': [None], 'start_line': [0], 'end_line': [0]} at file: /tf.json
2021-02-17 16:49:41,391 [MainThread  ] [ERROR]  Failed to run check: Ensure Amazon EKS Node group has implict SSH access from 0.0.0.0/0 for configuration: {'ami_type': ['AL2_x86_64'], 'capacity_type': ['SPOT'], 'cluster_name': ['test-123'], 'disk_size': [50], 'force_update_version': [None], 'instance_types': [['t3.medium']], 'labels': [{'Environment': ['test'], 'GithubOrg': ['terraform-aws-modules'], 'GithubRepo': ['terraform-aws-eks'], 'start_line': [0], 'end_line': [0]}], 'launch_template': [[]], 'remote_access': [[]], 'scaling_config': [{'desired_size': [1], 'max_size': [10], 'min_size': [1], 'start_line': [0], 'end_line': [0]}], 'subnet_ids': [], 'tags': [{'Environment': 'test', 'ExtraTag': 'example', 'GithubOrg': 'terraform-aws-modules', 'GithubRepo': 'terraform-aws-eks', 'start_line': 0, 'end_line': 0}], 'timeouts': [None], 'start_line': [0], 'end_line': [0]} at file: /tf.json

**Code fix here?**
Terraform plan is generating an empty `remote_access":[ ],` seems like checkov code expects a key to present by default
https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/EKSNodeGroupRemoteAccess.py#L14

**To Reproduce**
Below is the public module code reference to reproduce 

    module "eks" {
      source          = "terraform-aws-modules/eks/aws"
      cluster_name    = "test-123"
      cluster_version = "1.17"
      subnets         = [“"]
      cluster_endpoint_private_access = true
      cluster_endpoint_public_access = false
      tags = {
        Environment = "test"
        GithubRepo  = "terraform-aws-eks"
        GithubOrg   = "terraform-aws-modules"
      }
    
      vpc_id = "”
      node_groups_defaults = {
        ami_type  = "AL2_x86_64"
        disk_size = 50
      }
    
      node_groups = {
        example = {
          desired_capacity = 1
          max_capacity     = 10
          min_capacity     = 1
    
      instance_types = ["t3.medium"]
      capacity_type  = "SPOT"
      k8s_labels = {
        Environment = "test"
        GithubRepo  = "terraform-aws-eks"
        GithubOrg   = "terraform-aws-modules"
      }
      additional_tags = {
        ExtraTag = "example"
      }
        }
      }

1. terraform plan -out tf.plan  
2. terraform show -json tf.plan  > tf.json
3. checkov -f tf.json

**Desktop (please complete the following information):**
 - terraform version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.28.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

 - ✗ checkov -v
1.0.785 and 1.0.692

**Comment by njgibbon** [comment]
Hello,

@kartheekbodapati  is part of my team. I can confirm now that the above PR has resolved this issue after a re-test :)

**Comment by njgibbon** [comment]
Hey @gruebel  - This can be definitely be labeled and closed now.

**Comment by gruebel** [comment]
thanks to @njgibbon it is fixed since version `1.0.815` 🚀
