### ISSUE TITLE
Versioned Rulesets

### ISSUE THREAD

**Issue by the-maldridge** [bridgecrewio/checkov#88]
**Is your feature request related to a problem? Please describe.**
Currently it is impossible to update to a new version of checkov to get bug-fixes without also getting potentially new rules.  This would result in a number of quick changes to get a repo to lint clean again.  While the new rules should be fixed and deficiencies should be corrected, it shouldn't be in the same change to update software.

**Describe the solution you'd like**
Each rule should be part of a rule set and these sets should be enabled or disabled independently of the version of checkov running.  New rulesets should default to disabled.

**Describe alternatives you've considered**
I've considered pinning checkov to a specific version, but this means I won't get bug-fixes anymore.

**Comment by schosterbarak** [comment]
some what related: @the-maldridge  you can now use `--check` flag (multiple times) and choose a set of predefined checks
