### ISSUE TITLE
BC_AWS_KUBERNETES_2 should not be reported if  EKS Public Endpoint is Not Accessible to 0.0.0.0/0

### ISSUE THREAD

**Issue by ismailyenigul** [bridgecrewio/checkov#883]
**Is your feature request related to a problem? Please describe.**
BC_AWS_KUBERNETES_2: Ensure Amazon EKS Public Endpoint is Disabled
This check good to have but should not be triggered if  EKS Public Endpoint is Not Accessible to 0.0.0.0/0
**Describe the solution you'd like**
Disabling EKS Public Endpoint is import but in some cases need to be necessarily enabled. 
For example if you are provisioning k8s on EKS  with github, circleci or jenkins pipelines.
For that reason, If I limit access to EKS public endpoint to the certain IP ranges, this check should report as success.

**Comment by njgibbon** [comment]
Helllo @ismailyenigul ,

I don't think we should look to do this.

Enabling access from anywhere even with a firewall is still inherently less safe than enabling access only with a private network.

These checks are default positions and so if you judge it not be relevant to your situation then you can just configure it to skip.

Networking from a reputable SaaS over the internet with firewall(s) is a reasonable risk-based decision to make.

But there are many safer options that take more work. To use all of your examples; Jenkins, Gitlab and GitHub (yes, even GitHub) can all be hosted inside your network.

Gitlab and GitHub also offer things like self-hosted runners through their SaaS e.g https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

That's my position anyways :)

**Comment by ismailyenigul** [comment]
Do you think that moving all repos from github.com to self-hosted one? 
I don't that people will do it just to not to EKS public endpoint 😄 

Another use case:
Even if you use CI/CD solution in your AWS infra, nowadays people users multi  accounts architecture. 
Different accounts for  stage,dev, prod, shared services. In this case you usually deploy CI/CD in shared services account(ie Jenkins) it uses assumes roles and EKS public endpoints in target accounts(dev, stage, prod)
And creating VPC peering to access other accounts is not recommended. In this case, we only allow EKS public endpoints from certain IPs.


Of course, I can always skip the rule that I don't want.  But you should consider real life use cases too :)

Thanks

**Comment by gruebel** [comment]
@ismailyenigul you actually don't need to access any VPC to do such a deployment, you could easily leverage CodeBuild to run inside that VPC to interact with the EKS cluster and AWS even offers a GitHub Action https://github.com/marketplace/actions/aws-codebuild-run-build-action-for-github-actions

As @njgibbon mentioned we won't adjust this specific check, because making the EKS cluster private is the best solution from a security perspective.
