### ISSUE TITLE
Add Severity to controls and option to specify the severity to be reported.

### ISSUE THREAD

**Issue by ismailyenigul** [bridgecrewio/checkov#884]
**Is your feature request related to a problem? Please describe.**
Currently, checkov only report success for failure. That would be great if you can add severity to each control
also add options to specify the desired severity level of violations to be reported.

**Additional context**
You can get severity of CIS rules for aws at https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html
Implementation in terrascan https://github.com/accurics/terrascan/pull/501

**Comment by VAnagani** [comment]
Really looking forward for this feature. 
Thanks!

**Comment by hj-johannes-lee** [comment]
We too wait for this.!!

**Comment by geowalrus4gh** [comment]
We evaluated Checkov, KICS, Trivy, Terrascan and datree from a misconfig check tooling perspective. Compared  these tools extensively and found checkov to be a great tool to opt for. But the only feature which is missing in checkov is this one. Severity controls. Checkov provides this feature only to BridgeCrew platform integrations which require paid solutions. Really would like to see this feature in Checkov open source too.

**Comment by JamesWoolfenden** [comment]
This is already available.  You need a BC api key- can be the community edition- so free
![image](https://user-images.githubusercontent.com/1456880/156788586-91fc8e10-7eb7-48b0-a5fa-e6c3b8698ce6.png)

from the main readme:
Run all checks that are MEDIUM severity or higher, but skip check CKV_123 (assume this is a medium or higher severity check):
```sh
checkov -d . --check MEDIUM --skip-check CKV_123 --bc-api-key ...
```

**Comment by geowalrus4gh** [comment]
Agree. But it would be very nice if the report contains the severity as well.

**Comment by stevieg27** [comment]
Using BC api key for severity checks are limited to 50 resources in community edition, Its not free after that.

**Comment by fidelcasto** [comment]
Still waiting for this to be implemented.

**Comment by staleyj15** [comment]
Is there any timeline on when this functionality will be available offline? We work in an air gapped environment and can't reach an external API to pull severities.

**Comment by hvechtomov** [comment]
Hello!

Any info about this feature? Would be very glad if it will be added soon

Thanks

**Comment by carjessu-trm** [comment]
Is there any update on this?

**Comment by fidelcasto** [comment]
@gruebel  is there any chance this gets looked at? I think that it would still be a great feature addition.

**Comment by iheanachochukwu** [comment]
Is there any update on this? Can this get looked at.

**Comment by gruebel** [comment]
I don't think this will be implemented, because this a functionality exclusive for platform user.

**Comment by tsmithv11** [comment]
We are leaving this Issue open for visibility. I know this isn't a popular decision, but we have no plans of implementing this without an API key.

**Comment by dtrouillet** [comment]
Maybe we need to develop an other api server to implement API with custom endpoint url
