### ISSUE TITLE
Enable encryption check on Azure managed disk

### ISSUE THREAD

**Issue by johnvanhienen** [bridgecrewio/checkov#897]
**Is your feature request related to a problem? Please describe.**
The current implementation of the Azure managed disk encryption policy only checks if encryption is enabled if the `encryption_settings` is defined. When this block is missing, it will simply pass the policy even though encryption is not enabled/configured. See: 

https://github.com/bridgecrewio/checkov/blob/82d707d52f3cfc870c7b9c79229a96cf77d5abd8/checkov/terraform/checks/resource/azure/AzureManagedDiscEncryption.py#L13-L24

The check currently passes since the example explicitly defines the `encryption_settings` block. https://github.com/bridgecrewio/checkov/blob/82d707d52f3cfc870c7b9c79229a96cf77d5abd8/tests/terraform/runner/resources/example/example.tf#L46-L55
**Describe the solution you'd like**
I think that the check should also fail when the `encryption_settings` block is missing, since the rule clearly describes that it should fail if encryption is not enabled.

**Comment by gruebel** [comment]
Thanks to @JamesWoolfenden this is fixed since version `1.0.817` 🎄
