### ISSUE TITLE
Rule check suppression comments do not work

### ISSUE THREAD

**Issue by mgrecar** [bridgecrewio/checkov#90]
**Describe the bug**
When attempting to use a comment to suppress a rule check, it does not work.

**To Reproduce**
1. Create a terraform file containing this minimal, stripped down example:
```
  resource "aws_eks_cluster" "main" {
    #checkov.skip=CKV_AWS_38:Testing suppression
    #checkov.skip=CKV_AWS_39:Testing suppression
    vpc_config {
      subnet_ids = [for value in aws_subnet.public : value.id]
    }

    enabled_cluster_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
  }
```
2. Run checkov via `checkov --directory . -o cli`
3. Observe that the output does not have 2 skipped checks, and instead lists failures:
```

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

version: 1.0.167

Passed checks: 1, Failed checks: 2, Skipped checks: 0

Check: CKV_AWS_37: "Ensure Amazon EKS control plane logging enabled for all log types"
        PASSED for resource: aws_eks_cluster.main
        File: /eks:1-9


Check: CKV_AWS_38: "Ensure Amazon EKS public endpoint not accessible to 0.0.0.0/0"
        FAILED for resource: aws_eks_cluster.main
        File: /eks:1-9

                1 | resource "aws_eks_cluster" "main" {
                2 |   #checkov.skip=CKV_AWS_38:Testing suppression
                3 |   #checkov.skip=CKV_AWS_39:Testing suppression
                4 |   vpc_config {
                5 |     subnet_ids = [for value in aws_subnet.public : value.id]
                6 |   }
                7 | 
                8 |   enabled_cluster_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
                9 | }


Check: CKV_AWS_39: "Ensure Amazon EKS public endpoint disabled"
        FAILED for resource: aws_eks_cluster.main
        File: /eks:1-9

                1 | resource "aws_eks_cluster" "main" {
                2 |   #checkov.skip=CKV_AWS_38:Testing suppression
                3 |   #checkov.skip=CKV_AWS_39:Testing suppression
                4 |   vpc_config {
                5 |     subnet_ids = [for value in aws_subnet.public : value.id]
                6 |   }
                7 | 
                8 |   enabled_cluster_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]
                9 | }

```

**Expected behavior**
I expected the output to list 2 skipped checks, and list both `CKV_AWS_38` and `CKV_AWS_39` as skipped and not failed.

**Screenshots**
The examples above should describe things sufficiently.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Checkov Version: 1.0.167

**Additional context**
The example above is the most stripped down example I could make from my original Terraform code that produced the error.  It's not intended to be a complete, sensible Terraform file, it's intended to illustrate the bug.

**Comment by schosterbarak** [comment]
@mgrecar 
Seems like a typo. can you try modifying this:
#checkov.skip=CKV_AWS_38:Testing suppression
 #checkov.skip=CKV_AWS_39:Testing suppression
to this:
#checkov:skip=CKV_AWS_38:Testing suppression
#checkov:skip=CKV_AWS_39:Testing suppression
- I've swapped "." with ":" and it worked.

**Comment by mgrecar** [comment]
Ah, you're right, I was completely unable to see that difference.  After making the swap, everything works as expected.  Thank you!

**Comment by schosterbarak** [comment]
@mgrecar super. thank you!
