### ISSUE TITLE
Can not run on cloudformation template + json + tabs

### ISSUE THREAD

**Issue by athurn** [bridgecrewio/checkov#904]
**Describe the bug**
I am trying to run checkov on a cloudformation template written in json + tabs, however no checks are executed against the file.
I only ran into this issue with some of my json templates. Json templates that are yaml compliant (they used spaces for indentation and were otherwise correctly indented) are working ok.

I digged into the code and could see that the cloudformation runner (checkov/cloudformation/runner.py) isn't running any checks. `cf_context_parser.extract_cf_resource_code_lines` doesn't return any lines.

It seems that CF templates with tabs are parsed using `cfn_json.load` (checkov/cloudformation/parser/cfn_json.py). This loading mechanism doesn't add any `__startline__` or `__endline__` properties to the parsed json objects.

**Demonstration and hack to fix the issue**
I've played around with the code and I was able to add a hack together a solution that worked for me. I don't think this is quite ready for a PR and I wanted to get some feedback before spending more time on this.
 
https://github.com/bridgecrewio/checkov/compare/master...athurn:parsing-issue-for-json-with-tabs

**Steps to reproduce**
1. Create a CF file (make sure you are using tabs)
```
{
	"AWSTemplateFormatVersion" : "2010-09-09",
	"Resources": {
		"MySourceQueue": {
			"Type": "AWS::SQS::Queue",
			"Properties": {
				"KmsMasterKeyId": "kms_id"
			}
		}
	}
}
```
2. Run checkov for the file
3. Notice that no checks are executed

**Comment by schosterbarak** [comment]
Hi @athurn , Thank you for reporting this. The code change looks good to go. by the way, why did you chose to use yield?

**Comment by athurn** [comment]
@schosterbarak Thank you for your quick response. 

The existing code is already using `yield`s, I was just following the existing code :).

I've created a PR for my changes here https://github.com/bridgecrewio/checkov/pull/912

**Comment by gruebel** [comment]
Fixed by yourself 😄
