### ISSUE TITLE
Multiple --file options given results in duplicate findings

### ISSUE THREAD

**Issue by KevinHock** [bridgecrewio/checkov#911]
**Describe the bug**
If you give checkov e.g. --file twice, the first file you give will have double the findings (repeats). There is also no check for uniqueness among the outputted findings.

**To Reproduce**

On any 2 files that have (e.g. 1 failing check in each file):
Run
`checkov --file fileA.tf --file fileB.tf`
and you will notice `fileA` findings are duplicated.

`checkov --file fileB.tf --file fileA.tf`
and you will notice `fileB` findings are duplicated.

This is also true for PASSED findings.

**Expected behavior**
No duplicated findings.

**Checkov version:**
 - Checkov Version `1.0.726`
- Ubuntu

This is in the same ballpark as #115, `checkov directory switch not repeatable`, but a different kind of bug.

**Comment by KevinHock** [comment]
In the meantime, I added this to my cool checkov wrapper package:
```python
    deduplicated_failed_checks = sorted(
        list(
            # This is necessary
            # Due to duplicates in checkov output
            # Please see
            #   https://github.com/bridgecrewio/checkov/issues/911
            # for more information.
            map(
                json.loads,
                set(
                    map(
                        json.dumps,
                        failed_checks,
                    )
                ),
            )
        ),
        key=lambda failed_check: (failed_check['resource'], failed_check['check_id']),
    )
```

**Comment by gruebel** [comment]
tested it and it scans both files and failed checks are referenced to the correct file 🎄
