### ISSUE TITLE
Not evaluating defaults from terraform lookup function for CKV_AZURE_15

### ISSUE THREAD

**Issue by sainooli** [bridgecrewio/checkov#913]
**Describe the bug**
Checkov is not evaluating the default values from terraform lookup function (lookup(map, key, default)). For instance, checkov compliance is failing for CKV_AZURE_15 with an error "Ensure web app is using the latest version of TLS encryption" for Azure app Service. Below is how I have it inside site_config  
min_tls_version = lookup(site_config.value, "min_tls_version", "1.2")
Initially had default as null which would anyhow by default use 1.2 but was failing so pinned 1.2 and is still failing
**To Reproduce**
1. Create a map for site_config and provide a default value for min_tls_version
2. Create a PR 
3. See error in "checks"

**Expected behavior**
Compliance testing should be successful since by default terraform will assign a TLS version of 1.2

**Screenshots**
![image](https://user-images.githubusercontent.com/73849606/108914172-9659cb00-75f0-11eb-8f26-1be3aca567e4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Checkov Version 2.277.1

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by ishara93** [comment]
i faced the same issue. try to evaluate variable according to current terraform workspace. but it is not resolving the value.

To Reproduce

1. create a map variable
```
variable "ami_id" {
 type = map(string)
 default = {
   prod : "ami-830c94e3"
   dev : "ami-830c94e3ss"
 }
}
```
2. create two workspace (prod, dev)
3. create a resource and use lookup function to assign ami according to workspace

```
resource "aws_instance" "example" {
  ami= lookup(var.ami_id, terraform.workspace)

  instance_type = "t2.micro"
  metadata_options {
    http_endpoint = "enabled"
    http_tokens = "required"
  }
  tags = var.tags
}

```

**Comment by nimrodkor** [comment]
Implemented [here](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py#L165)
