### ISSUE TITLE
Terraform plan check CKV_AWS_27 not working when kms_master_key_id does not gets set

### ISSUE THREAD

**Issue by ccom-dev-platform** [bridgecrewio/checkov#921]
**Describe the bug**
Checov passes the check CKV_AWS_27 even when SQS queues declared in either resource or module blocks don't have kms_master_key_id and thus does not have SSE enabled.

**To Reproduce**
1. Generate file
```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 3.27.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

module "sqs" {
  source  = "terraform-aws-modules/sqs/aws"
  version = "2.1.0"

  name = "module-queue"
}

resource "aws_sqs_queue" "non_encrypted" {
  name = "resource-queue"
}
```
2. Run cli commands:
```
terraform init
terraform plan -out tf.plan
terraform show -json tf.plan  > tf.json 
checkov -f tf.json
```
3. See error

**Expected behavior**
Checkov should not mark CKV_AWS_27 as passed since SSE is not enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/78803657/109225636-4b7cb680-779c-11eb-90b0-8780ab2ac8b3.png)

**Desktop:**
 - OS: Macos Big Sur
 - Checkov Version 1.0.812, installed via homebrew

**Comment by JamesWoolfenden** [comment]
This only fails for the plan check not a regular check, it also   throws an exception on windows 
`ERROR:checkov.cloudformation.parser:Cannot read file contents: tf.json
2021-02-26 08:09:53,181 [MainThread  ] [ERROR]  Cannot read file contents: tf.json
ERROR:checkov.kubernetes.parser.parser:Cannot read file contents: tf.json
2021-02-26 08:09:53,183 [MainThread  ] [ERROR]  Cannot read file contents: tf.json
ERROR:checkov.arm.parser:Cannot read file contents: tf.json
2021-02-26 08:09:53,184 [MainThread  ] [ERROR]  Cannot read file contents: tf.json
Traceback (most recent call last):
  File "/home/jim/.local/bin/checkov", line 5, in <module>
    run()
  File "/home/jim/.local/lib/python3.8/site-packages/checkov/main.py", line 96, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=args.file,
  File "/home/jim/.local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 34, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/home/jim/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 60, in run
    tf_definitions, template_lines = parse_tf_plan(file)
  File "/home/jim/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 106, in parse_tf_plan
    template, template_lines = parse(tf_plan_file)
  File "/home/jim/.local/lib/python3.8/site-packages/checkov/terraform/context_parsers/tf_plan/__init__.py", line 21, in parse
    (template, template_lines) = tf_plan_json.load(filename)
  File "/home/jim/.local/lib/python3.8/site-packages/checkov/terraform/context_parsers/tf_plan/tf_plan_json.py", line 341, in load
    content = fp.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

**Comment by ccom-dev-platform** [comment]
@JamesWoolfenden You are correct, I should have added that myself!

I was also able to partially re-create the behavior with SNS Topics:
1. File:
```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 3.27.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

module "non_encrypted_sns_topic" {
  source  = "terraform-aws-modules/sns/aws"
  version = "2.1.0"

  name = "module"
}

resource "aws_sns_topic" "non_encrypted" {
  name = "resource"
}

```
2. CLI commands:
```
terraform init
terraform plan -out tf.plan
terraform show -json tf.plan  > tf.json 
checkov -d .
```
3. See error

Screenshot:
![image](https://user-images.githubusercontent.com/78803657/109303081-00ed4f80-7819-11eb-89b3-46b46674b64f.png)

**Comment by gruebel** [comment]
checked it works correctly, probably was fixed at some point 🎄 
```shell
Passed checks: 1, Failed checks: 1, Skipped checks: 0

Check: CKV_AWS_41: "Ensure no hard coded AWS access key and secret key exists in provider"
	PASSED for resource: aws.default
	File: /main.tf:1-4
	Guide: https://docs.bridgecrew.io/docs/bc_aws_secrets_5

Check: CKV_AWS_26: "Ensure all data stored in the SNS topic is encrypted"
	FAILED for resource: aws_sns_topic.non_encrypted
	File: /main.tf:10-12
	Guide: https://docs.bridgecrew.io/docs/general_15

		10 | resource "aws_sns_topic" "non_encrypted" {
		11 |   name = "resource"
		12 | }


terraform_plan scan results:

Passed checks: 0, Failed checks: 1, Skipped checks: 0

Check: CKV_AWS_26: "Ensure all data stored in the SNS topic is encrypted"
	FAILED for resource: aws_sns_topic.non_encrypted
	File: /repos/checkov/anton/tf/tf.json:0-0
	Guide: https://docs.bridgecrew.io/docs/general_15
```

**Comment by abdulakhan-philips-partner** [comment]
Hi there, I'm having a similar issue, where, if I don't set [kms_master_key_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#kms_master_key_id) but I do set [sqs_managed_sse_enabled](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#sqs_managed_sse_enabled) (and I set it to false), it gives a false positive:

**test_checkov.tf**:
```
resource "aws_sqs_queue" "not_encrypted" {
  name = "unencrypted-queue"
  sqs_managed_sse_enabled = false
}
```

Here is the result of running checkov:
`checkov -f test_checkov.tf --framework terraform -c CKV_AWS_27`

![image](https://user-images.githubusercontent.com/113049894/215555314-f5f00c93-e3c6-4f6a-baac-d948cb48d952.png)

I suppose SSE-SQS is slightly different from SSE-KMS, which is what CKV_AWS_27 really checks for, but it still shouldn't give a passing check if I haven't specified `kms_master_key_id` right? Just wanted to make sure


**Notes**:
Running `checkov --version` gives me 2.2.316

**Comment by JamesWoolfenden** [comment]
hi abdulakhan,
It's a bug! well done and thanks for finding it and reporting, ill post a
fix first thing tomorrow and let you know,
James

**Comment by JamesWoolfenden** [comment]
Hi,
I've submitted a PR to fix checkov
https://github.com/bridgecrewio/checkov/pull/4382. This should be passed
and merged very soon. If the results of this check are blocking your
pipelines in Bridgecrew then I suggest you suppress it for now.
Thanks,
James
