### ISSUE TITLE
Uncheck bridgecrew dashboard

### ISSUE THREAD

**Issue by santoshmarepally** [bridgecrewio/checkov#927]
When I first ran Checkov.. I selected Yes to visualize the results and gave the email. Every time I run this check it takes a long time for the report to complete and sometimes times out. Is there an option to uncheck this? I tried uninstalling and re-installing but did not solve the issue. Any help resolve this issue is appreciated.

--- I want to uncheck a setting to not run the report every time I run Checkov
Sucessfully configured Bridgecrew.cloud...
Metadata upload complete
Report upload complete
COMPLETE! Your Bridgecrew dashboard is available here: https://bridgecrew.cloud 
Login information should be in your email inbox

**Comment by schosterbarak** [comment]
Run 'rm -rf ~/.bridgecrew'

**Comment by santoshmarepally** [comment]
Thanks for the help. It fixed the problem.
