### ISSUE TITLE
Unable to load module: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by eric-kinsa** [bridgecrewio/checkov#931]
**Describe the bug**
I'm getting the following warning for every module that is sourced in my TF code. Im running the following command to scan the root directory of my TF code:

`checkov -d ./terraform_sub --skip-check CKV_AWS_23,CKV_AWS_52`

Example:
`
[MainThread  ] [WARNI]  Unable to load module (source="/Users/ericprice/repos/server-infrastructure/terraform_sub/modules/aws/elasticsearch" version="latest"): 'NoneType' object has no attribute 'get'
`

sandbox/main.tf:
```
module "elasticsearch" {
  source         = "../modules/aws/elasticsearch"
  env            = "sandbox"
  instance_size  = "t3.small.elasticsearch"
  es_version     = "7.7"
  instance_count = 2
  volume_size    = 10
  log_retention  = 30
  alert_topic    = [data.aws_sns_topic.slack.arn]
}
```

I tested every version going backwards from the latest to nail down exactly when it started and its version 1.0.802 where I'm getting these warnings. Version 1.0.801 and below work fine.

https://github.com/bridgecrewio/checkov/compare/1.0.801...1.0.802

**Comment by nimrodkor** [comment]
Thanks for reporting @eric-kinsa !
The difference between those versions seems very relevant - https://github.com/bridgecrewio/checkov/pull/881
@robeden mind taking a look?

**Comment by robeden** [comment]
@nimrodkor - Yeah, looking now.

**Comment by nimrodkor** [comment]
Hi @eric-kinsa !

Thanks to the great @robeden , a fixed version should be released in the coming 15 minutes or so. If the problem persists please reopen this issue.

Thanks again!

**Comment by eric-kinsa** [comment]
Thanks for the quick fix! It's working perfectly now.
