### ISSUE TITLE
Crashing in runner.py due to AttributeError raised by checking None for keys

### ISSUE THREAD

**Issue by KevinHock** [bridgecrewio/checkov#941]
**Describe the bug**
I am getting a crash similar in appearance to #118 but for Terraform and not CloudFormation.

```bash
Scanning file: /some_directory/some-file.tf
full_file_path is /other_directory/some_directory/some-file.tf
Traceback (most recent call last):
  File "/my_path/bin/checkov", line 5, in <module>
    run()
  File "/my_path/lib/python3.7/site-packages/checkov/main.py", line 108, in run
    guidelines=guidelines, bc_integration=bc_integration)
  File "/my_path/lib/python3.7/site-packages/checkov/common/runners/runner_registry.py", line 35, in run
    runner_filter=self.runner_filter, collect_skip_comments=collect_skip_comments)
  File "/my_path/lib/python3.7/site-packages/checkov/terraform/runner.py", line 78, in run
    self.check_tf_definition(report, root_folder, runner_filter, collect_skip_comments)
  File "/my_path/lib/python3.7/site-packages/checkov/terraform/runner.py", line 100, in check_tf_definition
    scanned_file, runner_filter, abs_referrer)
  File "/my_path/lib/python3.7/site-packages/checkov/terraform/runner.py", line 104, in run_all_blocks
    for block_type in definition.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

**To Reproduce**
edit: See https://github.com/bridgecrewio/checkov/issues/941#issuecomment-790803047

That's the thing 😢 It's real hard to reproduce, if I run `checkov` just on the file that it crashes on, things work fine! If I run it on just the last 10 files it scans before crashing, things work fine. For testing this, I'd recommend you simply run this on a big repo with a lot of output from `find . -type f -name "*.tf"` and then turn all the files into individual --file arguments, like my cool checkov wrapper package does.
e.g. `checkov --check CKV_AWS_88 --file fileA.tf --fileB.tf` (to save time, I just limited this to 1 check, but it could be any other check id)

1. Run cli command `checkov --check CKV_AWS_88 --file fileA.tf --fileB.tf` on a ton of --file arguments. Pray it triggers the bug.
2. See error

**Expected behavior**
No crashing.

**Desktop (please complete the following information):**
 - OS: OS X
 - Checkov Version: the latest as of today: `1.0.825`

**Comment by robeden** [comment]
Checking...

**Comment by robeden** [comment]
@KevinHock - The terraform parser doesn't perform evaluation when it's pointed to a single file. So, are you saying it fails when in `-d` mode and works in `-f` mode? If so, for reproducing, you might want to copy the suspect file to a separate directory and then point checkov at that with the normal `-d` flag.

**Comment by KevinHock** [comment]
I haven't tested the `-d` mode, I am passing in many `--file` arguments.

Luckily, removing the 1 file that had a parsing error stopped the crash. I was able to include that file with a subset of the other files in the repo I was scanning, and have it not crash. So, calling checkov like `--file a-lot-of-other-tf-files.tf --file some-parse-error-causing-file.tf --file even-more-files.tf` with more `--file` arguments might trigger the bug for others.

**Comment by robeden** [comment]
Is there anything... weird... about the version of checkov you're running? I can't find a version where the line numbers match up with the content reported in your traces.

**Comment by KevinHock** [comment]
Oh whoops, sorry about that, I just added a print statement or two, I am on the latest version.

**Comment by robeden** [comment]
Ok. Normality restored. 🤪

**Comment by robeden** [comment]
Looks like it's encountering an error loading the file (or you're pointing it to a file that doesn't end with `.tf` or `.tf.json`).

**Comment by KevinHock** [comment]
If I run it with just `checkov --file problem-file.tf`, it gives a parse error, and doesn't crash. But combined with some unknown other --file args, it crashes 🤔

**Comment by robeden** [comment]
That might make sense given how it loops over things? Hard to say for sure without being able to reproduce, but I'm pretty sure I have a change that will avoid the problem.

**Comment by KevinHock** [comment]
Ahh I think I know what might be causing this

I ran into it again on a different repository, where if I do:
`checkov  --check CKV_AWS_2 --file ./problem_parsing_this.tf  --file ./some_legit_file.tf `
Because of, I suspect, #911, the dictionary of the problem file is re-used for the legit file, None is treated like a dictionary.

**Comment by KevinHock** [comment]
Ahh here is an easy repro, with 1 arg that is a valid file, and one arg that is a file that doesn't exist: `checkov --check CKV_AWS_2 --file does_not_exist.tf --file existing_and_valid.tf`

**Comment by KevinHock** [comment]
Btw, tested the fix and it works like a charm ❤️
