### ISSUE TITLE
bc-python-hcl2: parse error in TerraGoat's aws/consts.tf

### ISSUE THREAD

**Issue by robeden** [bridgecrewio/checkov#944]
**Describe the bug**
In one of the recent releases (still narrowing which one), parsing of [TerraGoat's `aws/consts.tf` file](https://github.com/bridgecrewio/terragoat/blob/master/terraform/aws/consts.tf) broke. It dies with the error:
> AttributeError("'Tree' object has no attribute 'items'")

**To Reproduce**
Try to parse that file with 0.3.17. It might not have originated in that release, but is something since 0.3.13 (all of which were released on 2021-03-04).

**Comment by schosterbarak** [comment]
@arielkru and I will try to fix it in Sunday

**Comment by schosterbarak** [comment]
@robeden found it. fixing now.
