### ISSUE TITLE
Support for Packer and Vagrant

### ISSUE THREAD

**Issue by djdta** [bridgecrewio/checkov#949]
**Is your feature request related to a problem? Please describe.**

Would like to see is the tool to support Packer Images and Vagrant Box.

**Describe the solution you'd like**

What I would like the tool to do is have the ability to scan packer image after they have been build for any security risks also the same with vagrant boxes created.  Then produce a report of the security risks.

**Describe alternatives you've considered**

There is no real tool that scans security risks with packer images or vagrant images.

**Additional context**

**Comment by schosterbarak** [comment]
@djdta sound like a great idea. what would be an example security check for that?

**Comment by djdta** [comment]
Hi,

Thanks for your reply.

For Packer you could do the following.
* Is the ssh Username and Password is in clear text.?
* No public Ip address to be used in deploy?
* Is the ebs volume in encrypted?
* No KMS used for encrypted Volume?

For Vagrant as this for locally Development.
* Is the ssh Username and Password is in clear text.?
* No public Ip address to be used in deploy?
* Is the ebs volume in encrypted?
* No KMS used for encrypted Volume?

You may have your own ideas also, but I think adding more support for the other tool would grow your project.

Keep up the great work with the tool :) 

Regards,
Mike
