### ISSUE TITLE
Four checks, three empty?

### ISSUE THREAD

**Issue by OctavioCore** [bridgecrewio/checkov#95]
**Description**
I've just attached Checkov to our pre-commit config, and when i run `pre-commit --all-files` it seems that Checkov is ran 4 times - first three are blanks, with just the ASCII logo and "Passed checks: 0, Failed checks: 0, Skipped checks: 0", and the 4th time is when the tests are done.

**To Reproduce**
1. Add Checkov to .pre-commit-config.yaml
2. Run `pre-commit --all-files`
3. See error

**Expected behavior**
I was pretty sure it would just run once, including all `.tf` files found in all directories, recursively, and print the results once.

**Desktop**
 - OS: Linux Debian 10, Python 3.7.3
 - Checkov rev: 1.0.170

**Additional context**
It doesn't seem a really large issue - but, as it prints quite a lot of lines, it does punch the rest of the `pre-commit run` results pretty far away.

**Comment by schosterbarak** [comment]
I believe this was resolved
