### ISSUE TITLE
CloudFormation - ES Domain Logging - Check logic issue

### ISSUE THREAD

**Issue by njgibbon** [bridgecrewio/checkov#967]
**Describe the bug**
Recently @laurrentt pointed out that the logic of the check implemented in https://github.com/bridgecrewio/checkov/pull/962 was off. Please read there in the spirit of not duplicating.

So, I will implement the fix.

I just wanted to first get a view on what to check for...

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-logpublishingoption.html

Log publishing options has 4 logging options:

* SEARCH_SLOW_LOGS
* ES_APPLICATION_LOGS
* INDEX_SLOW_LOGS
* AUDIT_LOGS

Should I check that all logging is enabled? Or just a sub-set.

I think that audit should always be used. Then for me application logs is a maybe / probably. And I don't personally have a priority for the other two.

But I don't know how opinionated to be on the check.

Can someone from the team just provide a view on what to check in this situation and i'll just implement that 🙂 

Thanks all!

**Comment by schosterbarak** [comment]
Thanks @njgibbon
