### ISSUE TITLE
support passing variable files

### ISSUE THREAD

**Issue by Marcus-James-Adams** [bridgecrewio/checkov#971]
I have recently started getting
Check: CKV_AZURE_43: "Ensure the Storage Account naming rules"

On code that deploys ok.

my code (abbreviated) looks like

```
resource "azurerm_storage_account" "remote-state" {
  name  = "${var.org_short}${var.env_short}${var.loc_short}${var.service}stg"
}
```

We use an external variables file (common.tfvars) and plan and deploy using the tf command

terraform plan -var-file=..\common.tfvars which is located in a different directory

**Describe the solution you'd like**
I would like to be able to tell checkov that it should also evaluate variables from this file eg:
_bridgecrew -d .   --var-file=..\common.tfvars

This would then allow the checks to validate length and others correctly

**Comment by HarleyB123** [comment]
Agreed - this would be super useful! Currently I am interpolating the variables file by running a terraform plan and sending the output to a JSON, as shown [here](https://bridgecrew.io/blog/terraform-plan-security-scanning-checkov/)

Happy to take this one on - might get stuck along the way! :)

**Comment by HarleyB123** [comment]
Additionally, assuming your branch structure matches your environment and their variable names (this was the case for me, where my branch was ```env/uat``` for ```uat.tfvars``` and the ```main``` branch was my ```prod.tfvars```), you could run bash in a github action like so to get the branch name:

```yaml
- name: Extract branch name        
   shell: bash       
   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"       
   id: extract_branch
```

and then rename the variables file

```bash
if [ "${{ steps.extract_branch.outputs.branch }}" == "main" ]; then            
      cp terraform/vars/prod.tfvars terraform/vars/variables.auto.tfvars          
else            
      branch="${{ steps.extract_branch.outputs.branch }}"            
      environment="${branch:4}"           
      cp terraform/vars/$environment.tfvars terraform/vars/variables.auto.tfvars          
fi
```

**Comment by Marcus-James-Adams** [comment]
> Agreed - this would be super useful! Currently I am interpolating the variables file by running a terraform plan and sending the output to a JSON, as shown [here](https://bridgecrew.io/blog/terraform-plan-security-scanning-checkov/)

@HarleyB123 , the problem with the above especially with tf 0.15 it only works on the new infrastructure code as plan now only shows the lines that change in order to make it more readable.

@bridgecrew-bot this really does need supporting as it stops us from taking checkov & bridgecrew forwards

**Comment by Marcus-James-Adams** [comment]
@schosterbarak

**Comment by gruebel** [comment]
Thanks to @mikeurbanski1 this is supported via the `--var-file` flag since version `2.0.380` 🚀
