### ISSUE TITLE
file and directory selection on command line

### ISSUE THREAD

**Issue by lewissw** [bridgecrewio/checkov#989]
**Is your feature request related to a problem? Please describe.**
We often include python modules within our source directories, which means there maybe hundreds of files in directory structure. It would be useful to process only yaml cloudformation files. Currently one of our projects times out, as the scan takes too long.

```
PS C:\Users\802996686\DCP\dcp-core-network> checkov -d .
ERROR:checkov.cloudformation.parser:Cannot read file contents: .\assets\btdcp-core-network-tgw-attach\botocore\data\alexaforbusiness\2017-11-09\service-2.json
2021-03-16 17:09:19,038 [MainThread  ] [ERROR]  Cannot read file contents: .\assets\btdcp-core-network-tgw-attach\botocore\data\alexaforbusiness\2017-11-09\service-2.json
ERROR:checkov.cloudformation.parser:Cannot read file contents: .\assets\btdcp-core-network-tgw-attach\botocore\data\backup\2018-11-15\service-2.json
2021-03-16 17:09:20,181 [MainThread  ] [ERROR]  Cannot read file contents: .\assets\btdcp-core-network-tgw-attach\botocore\data\backup\2018-11-15\service-2.json
```
etc

Command line supports:
-d DIRECTORY, --directory DIRECTORY
                        IaC root directory (can not be used together with --file).
  -f FILE, --file FILE  IaC file(can not be used together with --directory)

**Describe the solution you'd like**
Can there be a filespec added to command line to restrict file extentions that are scanned.

**Describe alternatives you've considered**
We only have cloudformation yaml files in certain locations, so this workaround works successfully for us:
```
 - checkov -f product.template.yaml --external-checks-dir /checkov/custom_checks/ --no-guide --skip-check CKV_AWS_53,CKV_AWS_54,CKV_AWS_55,CKV_AWS_56,CUSTOM_AWS_001 #S3 Public Checks (Blocked at Account Level) & Lambda VPC Check
    - checkov -d templates --external-checks-dir /checkov/custom_checks/ --no-guide --skip-check CKV_AWS_53,CKV_AWS_54,CKV_AWS_55,CKV_AWS_56,CUSTOM_AWS_001 #S3 Public Checks (Blocked at Account Level) & Lambda VPC Check
```

**Additional context**

**Comment by schosterbarak** [comment]
@lewissw checkov can be pointed at a directory and skip other directories using the env variable CKV_IGNORED_DIRECTORIES 
 https://github.com/bridgecrewio/checkov#skipping-directories
 
 would that solve the issue?

**Comment by nimrodkor** [comment]
We've also implemented a few guardrails to allow skipping these JSON and YAML files.
If this is still recurring, please reopen this ticket 🙏
