### ISSUE TITLE
Checkov fails to start in Windows environments 

### ISSUE THREAD

**Issue by JamesWoolfenden** [bridgecrewio/checkov#99]
**Describe the bug**
After you install Checkov on Windows, running Checkov does nothing.

**To Reproduce**
1. Open Powershell/cmd
2. Run cli command  'checkov'
3. Does nothing

**Expected behavior**
The tool running. Magic.

**Screenshots**
I'm not sure showing nothing would help.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Checkov Version 1.0.173

**Additional context**
I know Windows! Like who cares and tbh ive got WSL2 and it works a dream but customers, customers and their awful locked down... anyway.
I'm using Python37 where i've installed .
If you look in your c:/Python37/scripts folder there is a "checkov" bash script. This is the nub of it this doesn't run! However if you add a batch file "checkov-scan.bat" [or call whatever} with this content:
```cmd
C:\Python37\python C:\Python37\Lib\site-packages\checkov\main.py %1 %2
```
Then when you run "checkov-scan" at your shell, it works! So is there anyway you could package up something similar in a release? please? 
Also I made a python based pre-commit for checkov called checkov-scan - here <https://github.com/JamesWoolfenden/pre-commit>

**Comment by schosterbarak** [comment]
I haven't tried this batch file. Would it work in pipenv? Let me know if you'd like to do the PR and get into the contributors list

**Comment by JamesWoolfenden** [comment]
I can do the PR

**Comment by schosterbarak** [comment]
Go for it :)
