### ISSUE TITLE
Error parsing file when using condition

### ISSUE THREAD

**Issue by eladmotola** [bridgecrewio/checkov#991]
**Describe the bug**
The process cannot parsing the file when using if statement. non of the the examples works:
```
name                = "somestring-%{if terraform.workspace != "prod"}-${terraform.workspace}%{endif}"
name                = "somestring-%{if terraform.workspace != "prod"}-${terraform.workspace}%{else}%{endif}"
```
**To Reproduce**
1. use this config:
```
resource "azurerm_servicebus_namespace" "example" {
  name                = "somestring-%{if terraform.workspace != "prod"}-${terraform.workspace}%{endif}"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"

  tags = {
    source = "terraform"
  }
}
```
2. run the command at "Using Docker" section
3. There is an error of "Error parsing file ..... "

**Expected behavior**
The process should handle this type of scenario since its valid in terraform

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by eric-kinsa** [comment]
Just chiming in that I'm experiencing the same issue ("Error parsing file") with several of my Terraform state files. I use conditionals a fair amount since I use modules for mostly everything.

**Comment by eladmotola** [comment]
@schosterbarak Hey, sorry for pinging. Can you please take a look?
