### ISSUE TITLE
 Remote Modules Loading feature is not working on source with refs

### ISSUE THREAD

**Issue by ismailyenigul** [bridgecrewio/checkov#994]
**Describe the bug**

Hi
It seems  Remote Modules Loading #677  is not working well with module source with ref=

module "label" {
  source  = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2"
  context = module.this.context
}

 checkov --download-external-modules  true -d .
ERROR:checkov.terraform.module_loading.loader:failed to get git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2 because of Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2 /Users/ismail/dev/terraform-aws-vpc-flow-logs-s3-bucket/.external_modules/git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2
  stderr: 'Cloning into '/Users/ismail/dev/terraform-aws-vpc-flow-logs-s3-bucket/.external_modules/git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2'...
warning: redirecting to https://github.com/cloudposse/terraform-null-label?ref=tags/0.19.2/
fatal: https://github.com/cloudposse/terraform-null-label?ref=tags/0.19.2/info/refs not valid: is this a git repository?
'

You can get the full version of the file from https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/blob/f38956c669a371d1540d3c9d23383d58801579ba/main.tf

**Expected behavior**
It should be able to download remote repo.

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Checkov Version 1.0.838

**Comment by schosterbarak** [comment]
@ismailyenigul the fix should be applied to https://github.com/bridgecrewio/checkov/blob/master/checkov/common/goget/github/get_git.py we would love a contribution

**Comment by ismailyenigul** [comment]
Fixed by https://github.com/bridgecrewio/checkov/pull/997
